- .gitignore
- scss/application.scss
- scss/grids/_base.scss
- scss/grids/_grid_3.scss
- scss/grids/_grid_4.scss
- scss/grids/_grid_breakout.scss
- scss/styleguide/_styleguide.scss
- scss/utilities/_variables.scss
- views/components/sample_component/sample_component.hbs
- views/styleguide/layouts.hbs
just some styling for the layouts
> Layout grids

- .gitignore
- circle.yml
- client/gulpfile.js
- client/package.json
- server/controllers/index.js
- server/package.json
- server/routes/index.js
I've done this a million times, hopefully the last.
* adds build script for circle to create artifact
* took watch out of the default grunt tasks as it's a dev task
* add healthcheck endpoint
* add pm2 for process management on server
> add pm2 and build scripts

- circle.yml
Using a new build bucket on the renaming to wellcomecollection.
> New build bucket

- README.md
- client/gulpfile.js
- client/package.json
introduced gulp-sourcemaps for source map generation
introduced gulp-util to pass in environment vars to conditionally run task on local environment only
> Added sourcemaps to css files for development

- infra/README.md
Hopefully almost there to have others deploying.
> update airbag readme

- client/gulpfile.js
> fix typo from merge

- package.json
Not 100% sure why they're here.
@davidpmccormick is this just my mistake?
@wellcometrust/wellcomecollection-org
> remove root packages, they're slowing the build.

- infra/README.md
- infra/app.js
- infra/package.json
- package.json
Updated the readme after @gestchild took it for the first test run.
> Update readme on airbag after 1st test run

- README.md
Just noticed it while trying to run it.
> Update client readme to match package

- principles_guidelines.md
didn't get carried over from web platform repo
> Added principles doc

- client/gulpfile.js
Grunt JS compile errors were breaking the watch loop - this fixes that.
> update gruntfile to not break on JS compiling while watching

- .dockerignore
- Dockerfile
- build-docker.sh
- docker-compose.yml
Created a basic docker container.
This will help us move to better deploys and stability.
__Next up__
Add it to a registry, probably [ECR](https://aws.amazon.com/ecr/)
> Add docker config of app

- server/app.js
Not sure how this creeped in, but while deploying, realised this was throwing on the servers.
> remove koa views

- infra/app.js
> throw airbag erros

- server/TODO.md
- server/controllers/index.js
- server/model/article.js
- server/routes/index.js
- server/views/article/index.njk
Waiting on wellcometrust/collection#242.
How I wish there were case classes in PHP / Node.
> Use new drupal API

- server/controllers/index.js
- server/routes/index.js
- server/util/https.js
One problem spotted by developing on http.
We also need to add a catch for 404s as it's breaking the server. Watch this space.
> use HTTPS api

- infra/TODO.md
- infra/terraform/templates/elb.tf
- infra/terraform/templates/launch.tf
- infra/terraform/templates/vpc.tf
Reforming our VPC strategy - nicely this was done in a mater of seconds thanks to Terraform.
We've now got to availability zones, and a strategy behind associating IPs.
> Better vpc

- nginx/dev-wellcomecollection.org.conf
- nginx/setup.sh
A slight abstraction which might make it easier to use on other projects (I needed it for `collection`).
> use actual dev URL in nginx

- server/controllers/index.js
- server/filters/index.js
- server/filters/parse-body.js
- server/package.json
- server/test/mocks/explore-api.json
- server/test/util/body-parser.js
- server/util/body-parser.js
- server/view/env-utils.js
- server/view/render.js
- server/views/article/index.njk
We now have an array of body parts.
The order is:
* Get the body
* Turn it into a fragment
* recursively filter / clean the nodes and their children
* Split it into a 1 dimensional array
The stuff coming from the API is really simple - and seems to only allow `p`s and `h2`s - so we shouldn't need much more for now - but once things like `blockquote`s (#80) get in we'll have to start not just filtering but parsing.
> Body parsers

- server/filters/youtube-embed-url.js
> add missing youtube embed file

- infra/terraform/templates/alb.tf
I love you terraform.
That was so easy.
> listen to ssl on ALB

- server/views/_partials/analytics.njk
- server/views/layout/default.njk
Making sure we're tracking from the start.
Does this look okay @croberts2015?
[No white space CR](https://github.com/wellcometrust/wellcomecollection.org/pull/95/files?w=1)
> add google analytics code

- server/views/layout/default.njk
> use applicaiton.css not styleguide

- server/views/_partials/analytics.njk
You need to create before set.
> set version number after ga.create

- server/controllers/index.js
- server/routes/index.js
- server/views/explore/index.njk
So that I can stop looking up the IDs on wellcomecollection.org.
> add explore page for reference

- server/views/components/header/index.njk
- server/views/layout/default.njk
[For consistency](https://github.com/wellcometrust/wellcomecollection.org/pull/89#discussion_r88407321).
> use href for a tags

- README.md
- build-server.sh
- server/.gitignore
- server/app.js
- server/babel-entry.js
- server/package.json
- server/webpack.config.js
One step closer to having client and server being similar.
The reason I started doing this was so that we could actually start using CSS modules, which I think will give us a bit more clarity about how we structure components, similar to #94.
> Webpack on server

- server/routes/index.js
- server/views/explore/index.njk
We can now use the full path due to the work done on:
wellcometrust/collection#246
> move to new article paths

- build-server.sh
> actually RUN compile

- server/package.json
for some reason I can't get greenkeeper to work...
This'll do for now.
> update server deps

- client/scss/utilities/_variables.scss
- server/views/docs/layout.md
- server/views/global/typography/typography.config.yml
- server/views/global/typography/typography.njk
Just a couple of changes to bring typography and grid up to date with the final styleguide from code and theory
- added new font type
- changed max grid width
> Matching updates to styleguide

- .gitignore
- build-cardigan.sh
- circle.yml
- infra/terraform/templates/s3.tf
- infra/terraform/website-policy.json
- server/package.json
- server/views/components/button-link/index.config.yml
Building a static version of cardigan and deploying it to s3 bucket
> Fractal deploy

- circle.yml
Seems you can't have two sections in deploy.
Now one big section.
> docker and cardigan

- PULL_REQUEST_TEMPLATE.md
Adding a pr template to the repo with some very basic info. Should I leave this open for a bit and handle any additions/amendments we want to it in this PR's comments?
> Add starter template

- server/views/explore/index.njk
Moving to the new, pluralised URLs which will more closely mimc the API.
> add s to article URLs

- client/scss/application.scss
- client/scss/components/_standfirst.scss
- server/views/components/standfirst/index.config.json
- server/views/components/standfirst/index.njk
> Add standfirst styles

- server/routes/index.js
> add s to articles route

- server/fractal-app.js
- server/views/components/new-site-notice/index.config.yml
We make sure that the environment passed to the extensions, are aware of the extensions themselves.
> add extensions to fractal nunjucks env

- client/scss/components/_footer_nav.scss
- client/scss/components/_opening_hours.scss
Practice what I preach. Add BEM definitions to the footer and opening-hours sass files.
> Define footer and opening-hours

- client/scss/base/_row.scss
- client/scss/components/_body_content.scss
- client/scss/components/_footer.scss
- client/scss/components/_page_description.scss
- client/scss/grids/_grid_base.scss
- server/views/components/footer-nav/index.config.yml
- server/views/components/footer/index.config.yml
- server/views/components/footer/index.njk
- server/views/layout/default.config.yml
- server/views/layout/default.njk
- server/views/layout/preview-footer.njk
- server/views/pages/explore.njk
- server/views/pages/pages.config.yml
Adding the footer to the base layout and addressing a number of layout/spacing issues.
> Layout footer

- client/js/app.js
- server/views/partials/js-head.njk
Making sure app javascript is only run once after DOM content has loaded
> Js loading

- client/scss/utilities/_variables.scss
> Update cream colour hex

- server/views/global/palette.config.yml
Update the cream colour in the Fractal config (forgot to add to #189).
> Update cream colour in fractal config

- client/scss/components/_find_us.scss
- client/scss/components/_footer.scss
- client/scss/components/_footer_nav.scss
- client/scss/components/_opening_hours.scss
Tweaking footer label spacing (#193).
> Move footer header labels closer to related content

- server/views/components/figure/index.njk
Conditionally displaying a caption and associated icon only if a caption exists in the data. Fixes #123.
> Only show caption markup if caption exists

- client/scss/components/_author.scss
Aligns the spacing of the author component with the mobile article PSD.
> Add responsive author component spacing

- client/scss/components/_find_us.scss
- client/scss/components/_footer.scss
- client/scss/components/_footer_nav.scss
- client/scss/components/_footer_social.scss
- client/scss/components/_header.scss
- client/scss/components/_opening_hours.scss
- client/scss/utilities/_variables.scss
- server/views/components/find-us/index.njk
- server/views/components/opening-hours/index.njk
- server/views/global/palette.config.yml
Adding some CSS animations to the header and footer links/tabs/buttons.
Updated `keyline-grey` variable to work with the darker `cream`.
> Animations

- nginx/README.md
- nginx/next.dev-wellcomecollection.org.conf
- nginx/setup.sh
There's not point in pretending we've stolen the main URL already.
This just brings prod and dev closer together.
> use next subdomain in dev to replicate prod

- client/scss/base/_typography.scss
- client/scss/components/_blockquote.scss
- client/scss/components/_body_content.scss
- client/scss/components/_figure.scss
- client/scss/components/_page_description.scss
- client/scss/components/_standfirst.scss
This brings the mobile typography in line with the article PSDs.
> Mobile type

- server/controllers/index.js
- server/model/article.js
- server/model/media.js
- server/routes/index.js
We are now ingesting WP content from blog.wellcomecollection.org.
The benefits are:
* The content is fresh and relevant
* The content is richer, and more inline with the design
> added WP blog endpoint

- server/views/components/footer-nav/index.config.yml
- server/views/components/footer-nav/index.njk
- server/views/components/footer/index.njk
- server/views/layout/default.njk
> add footer NavLinks

- server/controllers/index.js
- server/model/opening-hours.js
- server/model/page-config.js
- server/views/layout/default.njk
- server/views/pages/article.njk
- server/views/templates/article.njk
We need some sort of way for the page to have config. There will be generic config, but there will also be page specific content, i.e. `inSection`. This is a start on how we might do that.
More like the preview as we have content.
~~As a note on the tabs, I'm not 100% sure I like the idea of it storing the current tab in the hash - what's the point?~~ It doesn;t
> Page config

- server/model/article.js
- server/model/person.js
- server/views/components/author/index.config.yml
- server/views/components/author/index.njk
- server/views/pages/article.njk
- server/views/templates/article.njk
* Adding the author to the article.
* Swapping the inheritance of the templates and pages.
The second point is because templates are specific to cardigan, no problem having them, and they're a good place to explore for when we do not have the API content, but they should inherit the PROD content.
Looks like Russel!
> Author article

- server/controllers/index.js
- server/routes/index.js
- server/views/components/header/index.njk
- server/views/pages/explore.njk
- server/views/pages/index.njk
Adds a basic homepage so that when people hit the URL they aren't greeted with a "not found"
> add index page so as not to break when hitting the URL

- server/views/components/find-us/index.njk
- server/views/pages/index.njk
The is too much, we're removing it.
> add new map and remove the

- client/webpack.config.js
- server/controllers/index.js
We need opening times on all pages.
This adds it to the explore page.
> add opening times to explore page

- server/controllers/index.js
> add opening hours to index

- server/model/image.js
- server/util/body-parser.js
Some images are wrapped in links, we need to deal with this.
We don't use it, although I imagine it's useful information.
It'd be good to see if we can find a pattern as to how we do.
> deal with some images being wrapped in links

- server/views/pages/article.njk
It's a basic inference, but might just cut it.
> infer standfirst

- server/views/docs/index.md
- server/views/docs/principles.md
Just some initial thinking about what Cardigan is for.
In short I would say patterns are the way in which we present ourselves to the public to allow them to interact with our products and services.
The principles are the processes that we follow to ensure that we achieve the quality we would like to achieve and inclusiveness of those products and services.
Thoughts?
> add generic definition of Cardigan

- client/gulpfile.js
Changed autoprefixer config to be inline with our support list
> Restricted autoprefixer to last 2 browser versions

- client/.babelrc
- client/js/app.js
- client/js/components/tabs.js
- client/js/util.js
- client/package.json
- client/scss/components/_cookie_notification.scss
- client/scss/components/_footer.scss
- client/scss/components/_header.scss
- client/scss/components/_opening_hours.scss
- client/webpack.config.js
Fixing a handful of IE layout issues and some JS errors.
> Fix assorted IE layout/JS issues

- client/scss/components/_opening_hours.scss
- server/views/components/opening-hours/index.njk
Making sure opening hours display nicely when JS isn't working (part of #193).
> Display opening hours when JS doesn't fire

- server/views/components/new-site-notice/index.njk
Updating the new site notice copy. Closes #170.
> Update new site notice copy

- server/model/image-gallery.js
- server/model/picture.js
- server/test/util/body-parser.js
- server/util/body-parser.js
- server/views/components/image-gallery/index.config.njk
- server/views/components/image-gallery/index.njk
- server/views/pages/article.njk
Converting the Wordpress HTML blob into an `ImageGallery` model.
> Create ImageGallery model from WordPress

- server/util/body-parser.js
- server/views/pages/article.njk
> fix typo and get correct caption from wordpress

- server/views/components/footer/index.config.yml
- server/views/components/footer/index.njk
Showing the footer nav links in the footer section of Cardigan
> Point to correct footer nav data

- client/scss/application.scss
- client/scss/components/_tags.scss
- server/views/components/tags/index.config.yml
- server/views/components/tags/index.njk
- server/views/pages/article.njk
- server/views/templates/article.config.yml
Adding a tags component which displays an inline list of links
Closes #256.
> Add article tags

- server/views/components/cookie-notification/index.njk
Link to Wellcome terms from cookie notification. Fixes #143.
Same same.
> Add link to Wellcome terms

- server/views/components/blockquote/index.config.yml
> make sure citation is correct for blockquote

- client/scss/components/_find_us.scss
> Bouncy icon

- server/views/components/blockquote/index.config.yml
> Lettera > Letera

- client/scss/components/_footer.scss
> make back to top link the normal color

- client/js/app.js
- client/scss/components/_article.scss
- client/scss/grids/_grid_dividers.scss
- server/views/components/article-body/index.config.yml
- server/views/components/article-body/index.njk
- server/views/components/figure/index.njk
- server/views/components/iframed-video/index.njk
- server/views/pages/article.njk
- server/views/templates/article.config.yml
- server/views/templates/article.njk
Code refactor so that the pages/article and template/article files aren't duplicating code.  They both now make use of the same component to render the various body parts.
I've done a bit of a tidy to remove unnecessary html and styles, and added examples of all bodyPart types to the template/article example page
Same as before, but with examples of all bodyPart types
> Article component

- server/model/opening-hours.js
> update opening hours

- server/views/components/new-site-notice/index.njk
Removing the link to opt out from the new explore reading experience.
> Remove opt-out link

- server/cardigan-theme/tweaks.css
- server/fractal-app.js
Widening the Cardigan sidebar's scrollbar (making @Norvard 's life a bit easier).
> Make scrollbar wide enough to be easily selectable in webkit

- client/scss/components/_figure.scss
- server/views/components/figure/index.config.yml
- server/views/components/figure/index.njk
Adding a link style within the image caption. Closes #245.
> Add caption link style

- server/views/components/figure/index.njk
- server/views/components/media-item/index.njk
Correcting the width of the hero image caption to be equal to that of the body content.
Same same but better.
> Fix hero-caption grid sizes

- server/views/components/footer/index.njk
- server/views/components/header/index.njk
- server/views/layout/default.njk
Making links reference the V1 website where we do not have content on this site.
It will give us a better idea of how the launch is going to work now that we've decided what it looks like.
> Make nav and search links refer to V1 of the site

- server/extensions/index.js
- server/filters/image-sizes.js
- server/filters/index.js
- server/fractal-app.js
- server/views/components/figure/index.config.yml
- server/views/components/image/i.yml
- server/views/components/image/index.config.js
- server/views/components/image/index.njk
Recreating the image component to:
* Use the JS models available
* Work out the sizes automatically
* Decouple it from the grid as it can't be used elsewhere if it is.
WIP
> Add new image component

- client/scss/components/_figure.scss
- server/views/components/footer-social/index.njk
- server/views/components/page-description/index.njk
- server/views/layout/default.njk
- server/views/macros.njk
- server/views/pages/article.njk
- server/views/templates/explore-landing.njk
Moving the `gridClasses` macro into a macros file and importing it where it's needed.
> Add macros file; import for grids where necessary

- client/scss/components/_find_us.scss
- client/scss/components/_footer_social.scss
- client/scss/utilities/_mixins.scss
Fixes #321 
Adds map icon hover animation to social icons
> Fixes #321 - unifies footer map and social icon hover behaviour

- server/package.json
> remove webpack from server

- client/scss/components/_figure.scss
- client/scss/components/_promo.scss
- server/views/components/figure/index.njk
Correcting the spacing above/below the hero figure caption. Fixes #251 and fixes #252.
> Fix figure caption spacing

- server/controllers/index.js
* Added a call to WP from perf script
* Added the render function to perf script
> add rendering and wp call to performance script

- client/scss/components/_interview.scss
Swapping interview type weights and matching weight to participant. Fixes #380.
> Invert question/answer type weights; match weight to questioner/answerer

- server/util/body-parser.js
> get gifs from WP

- client/scss/application.scss
- client/scss/components/_promo.scss
- client/scss/components/_transporter.scss
- server/filters/concat.js
- server/filters/index.js
- server/views/components/promo/index.njk
- server/views/components/transporter/index.config.yml
- server/views/components/transporter/index.njk
> Transporters

- infra/terraform/templates/alb.tf
Adds a 500 alarm when we have a 500 error on the live site.
So far we only have the fake ones 🐐
> add basic email 500 alert for alb

- server/views/layout/default.njk
- server/views/partials/html_top.njk
Allow users to zoom into pages on their devices
> Removed maximum scale for better accessibility

- client/js/app.js
- server/views/layout/default.njk
- server/views/partials/js-head.njk
- server/views/partials/monitoring.njk
Adding sentry so we can start catching client errors RUM like.
> Add sentry

- client/js/app.js
> dont use camelCase for lazysizes library

- server/app.js
- server/package.json
Serving files gzipped to reduce page weight
> Added kia-compress middleware to send gzipped files

- client/webpack.config.js
Further reducing the size of the app.js file
This drops the file from approx. 80KB to approx. 27KB (with gzipping from #424 it then goes to 9.1KB)
> Minify javascript file on production

- client/js/app.js
- server/views/partials/monitoring.njk
Only error on prod domain to make sure we pay attention to errors reported.
😯
> only error on PROD domain

- server/views/components/find-us/index.njk
Reduce the size of the map image being requested
> Responsive map image

- server/util/body-parser.js
Re-adding the tweet converter that got erroneously removed. [Last seen here](https://github.com/wellcometrust/wellcomecollection.org/commit/bd1b3d2b91001b7b2436ff83af706da08fa660cf#diff-6ddd737b5aca2e7ffcb9d0c91b5c0960R31).
> Re-add tweet converter

- server/extensions/component-v2.js
- server/extensions/index.js
- server/filters/component-classes.js
- server/filters/index.js
- server/views/components/article-body/index.njk
- server/views/components/captioned-image/index.njk
- server/views/components/image-gallery/index.njk
- server/views/components/main-media/index.njk
- server/views/pages/article.njk
Kind of going against technologically pragmatic (we already have what we need), but I think this is a good exercise at how we might want to be looking at components in the future.
I also think it will start to help us ensure that we're thinking about our data model while templating. 
the basic question I am trying to ask is:
"What thing do we have available, how does it look, and what about it might look it look a little different?" 
Inspired by a conversation with @kenoir
> add new component extension that uses model/modifiers/data

- server/controllers/index.js
- server/model/article.js
- server/model/image-gallery.js
- server/model/list.js
- server/model/media.js
- server/model/opening-hours.js
- server/model/page-config.js
- server/model/person.js
- server/model/picture.js
- server/model/tweet.js
- server/model/video.js
- server/util/body-parser.js
- server/views/components/captioned-image/index.config.js
- server/views/components/tweet/index.config.js
Move to standard types rather than Immutable records.
* I'm not sure having the function that creates the type being called the type with a small first letter is a great idea as you often wat to have: `const video = video(videoData);`... I'm not sure what to do about that. In the `Tweet` example I used `createTweet`. thoughts?
⌨️
> Move to types over Immutable Records

- server/package.json
We should be reading off the `.babelrc` file.
> remove babel config from package

- docs/monitoring-strategy.md
Just a first draft of the whats and whys of monitoring.
I wouldn't mind having at trying to split each type of monitoring in to what and why, but first testing the waters to see if this is useful.
> Add first draft of monitoring doc

- server/app.js
Just added far future date for fonts, so browsers use them from cache
> Adding far future Cache-Control heading to font files

- client/scss/components/_new_site_notice.scss
> position relative notiication bar to make find out more clickable

- client/scss/components/_captioned_image.scss
- client/scss/utilities/_variables.scss
- server/views/components/captioned-image/index.njk
Fixes #426
Brought up some interesting conversation around vertical spacing with @Norvard. 
We should be using units of 6, and we also seem to have excess `line-height`... I think it's worth looking at that as a whole at some stage.
> add underline to images that aren't captioned

- client/scss/components/_find_us.scss
- server/model/organization.js
- server/views/components/find-us/index.config.js
- server/views/components/find-us/index.config.yml
- server/views/components/find-us/index.njk
- server/views/components/footer/index.njk
- server/views/layout/default.njk
> Address json ld

- server/views/components/main-media/index.njk
> ensure main media caption is always cream

- client/gulpfile.js
> Added iOS 8 to autoprefixer list

- server/package.json
Realised we weren't copying the files across during build.
This has blown the whole thing up.
> add copy-files to babel compile to include JSON config files

- server/fractal-app.js
- server/package.json
- server/test/mocks/wp-api.json
- server/views/components/article-body/index.config.yml
- server/views/components/captioned-image/index.config.js
- server/views/components/transporter/index.config.yml
- server/views/templates/article.config.yml
- server/views/templates/explore-landing.config.js
- server/views/templates/templates.config.yml
Fixes #400
Update references images to 16/9.
This will not apply to images from old content.
Makes me think we should have a doc in Cardigan about image use.
> Image ratios

- client/scss/components/_article.scss
- client/scss/components/_body_content.scss
- client/scss/utilities/_variables.scss
Fixes #244
Before: 
After (with author):
After (without author):
> Adjusted margin of first rail image

- server/views/components/find-us/index.njk
Making the google map link more specific to Wellcome Collection's address
nothing to see here
> Updated map link to be more specific to Wellcome Collection

- client/scss/components/_promo.scss
- server/views/pages/explore.njk
> Explore feature tweaks

- client/scss/components/_page_description.scss
> Adjusted spacing for article page description

- server/model/organization.js
- server/views/components/open-graph/index.njk
- server/views/components/twitter-card/index.njk
Fixes #506 based on [this strategy](https://github.com/wellcometrust/wellcomecollection.org/wiki/V1-=--V2-URL-migration-plan).
🐦
> use next. for article open graph data

- infra/app.js
Realised that the ordering was going a bit haywire.
This is a bit of an odd way to do it - but that's what you have to work with in JS.
> order tags from Docker correctly

- client/scss/components/_captioned_image.scss
- client/scss/components/_promo.scss
- server/views/components/main-media/index.njk
> Image captions

- server/views/components/captioned-image/index.njk
- server/views/components/promo/index.njk
Stops invalid srcset properties being generated, which was causing console errors
> Pass width to image component

- client/scss/components/_promo.scss
Fixes #461
Less dramatic image zoom
> Image zoom

- client/scss/components/_find_us.scss
- server/views/components/find-us/index.njk
Fixes #504 as per [their recommendation](https://www.mapbox.com/help/attribution/)
FYI @Norvard
> add required mapbox credit

- client/scss/components/_find_us.scss
- client/scss/components/_promo.scss
- client/scss/utilities/_mixins.scss
- server/views/components/find-us/index.njk
> Made map in footer zoom in the same way as the images in promos

- server/data/people.js
- server/model/person.js
- server/services/author-lookup.js
Adds Ruth as an author and assigns her to the article.
We are going to have to think about what we do with the author bios as is i.e. The ones that are just added to the body content.
> add ruth as author and assign her to article

- server/controllers/index.js
Noticed we've been in a state of alarm for ages.... Not great that it was a constant alert...
> Use defined `slug` value.

- server/views/pages/explore.njk
> Specified grid layout for medium screens

- server/app.js
- server/config/index.js
- server/controllers/index.js
- server/middleware/enforce-ssl.js
- server/view/render.js
As per the [Koa guidelines](https://github.com/koajs/koa/blob/2.0.0/docs/guide.md) there were a few things we were meant to be doing (for good reason of maintaining the flow).
Things:
* I left the rendering functions calling `next()` incase we'd like to alter the response post it running.
* I removed async from the rendering as we don't use it.
> move middleware vals to config and follow Koa recommendations

- client/scss/base/_row.scss
> Wobbly line

- client/scss/base/_row.scss
> Adjusted row spacing

- package.json
[I've broken the builds back in October last year](https://github.com/wellcometrust/wellcomecollection.org/commit/904e3be2b69820b6945b3cc165a6d70553efa354).
We must have been riding Circle's cache for this to have kept working.
> readd concurrently to root build

- server/views/templates/article.config.yml
> Remove copyright symbol from cardigan article images

- server/controllers/index.js
I can't wait to get compilation setup to not allow silly stuff like this.
> add next to preview controller to stop undefined error

- client/js/components/instagram.js
Clarifying a variable name as per discussion on #453.
> Clarify variable name/intent

- client/scss/components/_new_site_notice.scss
- server/views/components/new-site-notice/index.njk
Change copy on new site notice as per comment on #170.
> Update new site notice

- server/views/components/new-site-notice/index.njk
- server/views/layout/default.njk
- server/views/pages/index.njk
As above; also prevented link showing on that page as it's redundant
> Pointing find out more link to the correct destination

- server/views/pages/explore.njk
> use the right link to articles

- client/scss/components/_promo.scss
- server/views/components/promo/index.njk
> use large title in featured / lead promos

- client/scss/base/_icons.scss
- server/views/components/header/index.njk
Fixing the mobile logo. Fixes #548.
> Fix mobile logo

- server/.babelrc
Annoyingly the build passed although it explicitly through an error - we'll need to definitely investigate.
https://circleci.com/gh/wellcometrust/wellcomecollection.org/1229
> dont' compile NJK file with babel

- server/views/components/promo/index.njk
Bumping the summary text to 140 as per chats with @RussellDornan and @dannybirchall
> up link text count to 140

- server/model/opening-hours.js
Fixes #590 
Please merge in if you are happy as I'm not in today.
> Fix typo on calendar from Monday => Sunday

- infra/terraform/templates/cloudfront.tf
[Seems you need to](https://github.com/hashicorp/terraform/issues/10572). 
I thought that might just take defaults...
> add custom_origin_config to cloudfront for alb

- infra/terraform/templates/cloudfront.tf
A few updates to get CloudFront setup correctly.
[See here](https://d32rbdr1u62yly.cloudfront.net/).
> Cloudfront update

- server/util/body-parser.js
Some null checks in the body parser...
We need to kill this thing.
> add in some annoying body parsers null checks

- client/scss/components/_body_content.scss
> Removed unnecessary clear property that was causing a bug in firefox

- server/views/components/article-body/index.njk
- server/views/components/captioned-image/index.njk
- server/views/components/image/index.njk
- server/views/components/promo/index.njk
> Image componentv2

- client/scss/components/_more_info_link.scss
Fixing the more info link/icon layout. Fixes #584.
> Make less-than-ideal fix

- server/views/pages/explore.njk
Make the 'You may have missed' scrolly section scroll nicely on iOS.
> Include momentum iOS scroll on 'you may have missed'

- package.json
Thought it appropriate for the milestone.
Seems to be a sensible way of versioning? Once we have 100% traffic we can launch as V1.
> bump version as milestone was reached

- infra/deploy.sh
After updating the Task Definition we have to make sure we update the service to read from that.
> when deploying update ecs service with new task-def

- server/pm2.yml
I thought this would have worked.
It doesn't and it's breaking the build - so I'll investigate later as to why not.
> Don't run PM2 in cluster mode

- Dockerfile
- server/package.json
- server/pm2.yml
Run through this with @gestchild and @davidpmccormick.
I'd really like to know how PM2 failed so silently...
> update pm2 to run the right script

- client/scss/components/_blockquote.scss
- server/views/components/blockquote/index.config.yml
Adding a smaller blockquote style. Closes #573.
> Add small blockquote style

- server/util/body-parser.js
> Search for img tag

- client/scss/base/_row.scss
Preventing a thin border appearing above the wobbly line on the explore page. Fixes #510.
> Compensate for browser rendering artefacts

- server/controllers/index.js
- server/model/article-stub.js
- server/services/wordpress.js
- server/views/components/promo/index.njk
Making the pagination work. Fixes #656.
> Add article pagination

- server/filters/index.js
- server/filters/object-assign.js
- server/views/components/transporter/index.njk
We need to apply a modifier on the promo only if there is a certain amount.
It makes sense for the template to do this - so I've added the assign to the filters.
I would like to start looking at moving towards having a component being able to contain logic - it seems really odd not to be able too.
> add object assign filter and apply it to transporter

- client/js/app.js
- server/views/components/page-description/index.njk
Redisplaying the article title date. Making the JS run.
> Display date; actually call init function

- server/views/pages/list.njk
Updating the `spacingClasses` on the list template (slipped through the net on initial change). Fixes currently broken list views.
> Update spacingClasses on list template

- server/views/components/iframed-video/index.njk
Enabling fullscreen U Toobs. http://stackoverflow.com/a/27784769.
Big.
> Allow fullscreen

- client/js/app.js
Reverts wellcometrust/wellcomecollection.org#695
> Revert "remove readystate check for DOMContentLoaded"

- client/js/components/async-content.js
- client/scss/components/_numbered_list.scss
- server/controllers/index.js
- server/model/numbered-list.js
- server/views/pages/article.njk
- server/views/templates/article.config.yml
Hooking up the horizontal numbered list component with the async content from the series-nav controller. This will need more attention once #693 is merged (in order to trigger the JS setup after the component has been loaded asynchronously).
> Wire up as much series nav as possible before redux is there

- infra/deploy.sh
- infra/terraform-config/README.md
- infra/terraform-config/terraform-config.tf
- infra/terraform/templates/state.tf
- infra/terraform/templates/vars.tf
- infra/terraform/terraform.tf
- infra/terraform/wellcomecollection.tf
Update to terraform 0.9.
This will hopefully help with auto deploying.
> add new terraform backend available from v0.9

- server/middleware/error.js
- server/package.json
- server/views/layout/default.njk
- server/views/pages/error.njk
Moving sentry server errors to the server.
[Waiting on this first though](https://github.com/getsentry/raven-python/issues/569#issuecomment-288028340).
> add raven to server

- server/views/layout/default.njk
- server/views/partials/analytics.js.njk
- server/views/partials/analytics.njk
We have a [Google Optimize](https://optimize.google.com) account - so it might be worth trying out.
Nothing yet, we have no tests.
> add recommneded code for google optimize

- server/data/people.js
- server/services/author-lookup.js
More authors as per @dannybirchall's list
> add new authors to author lookup

- test.sh
Seems breaking the tests doesn't break the build.
Now it does:
https://circleci.com/gh/wellcometrust/wellcomecollection.org/1562
> make sure we bork on errors from npm

- server/data/people.js
Adding @RussellDornan's preferred face.
:fox_face:
> Russel's face in the house

- server/model/series.js
As this code is hard to reach and also untested (as it's a hack) - it's problems were't rearing up.
This fixes those.
> Calculate forward filling of series correctly

- client/scss/components/_numbered_list.scss
- server/views/components/numbered-list/index.njk
Setting the currently-viewed item title to 'Currently viewing' and changing its colour to match that of the series.
> Set current series item title/colour

- server/filters/format-date.js
- server/filters/index.js
- server/model/promo.js
- server/views/components/numbered-list/index.njk
If the date is  in the future - we let people know it's coming soon.
How kind.
> Format date with coming soon prefix

- server/services/author-lookup.js
> add ruth as author for thunderbolts

- server/model/series.js
> Use correct name for digital story

- server/data/people.js
> Space in Ruth Gardes description

- infra/deploy.sh
- test.sh
I, like @alexwlchan, [prefer verbosity](https://github.com/wellcometrust/wellcomecollection.org/pull/716#discussion_r108649725).
Saying that - the trace out was annoying me.
> don't trace out in deploy.sh

- client/webpack.config.js
It seems babel and a few other things don't play too well with Uglify, so it's best to just suppress the 
warnings.
> Suppress uglify warnings

- infra/terraform/cloudfront/cloudfront.tf
- server/controllers/index.js
- server/services/wordpress.js
- server/test/query-object.js
Adding a query syntax to allow redirection from the blog without setting up permanent URLs.
The test should explain how this syntax works.
> Article query support

- circle.yml
Installing the AWS Cli so we can push to the S3 bucket for cardigan.
> aws cli test in circle

- circle.yml
> use circle_build_num for docker version

- client/js/app.js
- client/js/components/content-slider.js
- client/scss/components/_article.scss
- client/scss/components/_body_content.scss
- client/scss/components/_image_gallery.scss
- server/views/components/article-body/index.njk
- server/views/components/image-gallery/index.njk
- server/views/components/image/index.njk
Starts addressing some of the js interactions described in #629 and implementing [Tomi's designs](https://wellcomecloud-my.sharepoint.com/personal/t_lahdesmaki_wellcome_ac_uk/Documents/Design%20delivery/Article/PNGs/Image%20Gallery)
N.B. The positioning of the control arrows is different to the designs, as it was agreed they were better placed together, rather than at opposite ends of the gallery.
I've also prevented images from being wider than the screen width, so at certain dimensions letter-boxing will be introduced, see screenshot below.
**Mobile:**
**Desktop:**
**Letter-boxing:**
> Js image galleries

- server/controllers/index.js
- server/data/series.js
- server/filters/get-commissioned-series.js
- server/filters/index.js
- server/model/article-stub.js
- server/model/article.js
- server/model/promo.js
- server/model/series.js
- server/services/wordpress.js
- server/views/components/captioned-image/index.njk
- server/views/components/chapter-indicator/index.njk
- server/views/components/numbered-list/index.njk
- server/views/components/promo/index.njk
- server/views/pages/article.njk
Adding chapter-indicator bars to the article hero and promo images. Closes #727.
> Indicators

- nginx-proxy/nginx.conf
Somehow I thought that gzipping was occurring, I think this might be the solution.
> proxy content through prox in nginx

- server/controllers/index.js
- server/services/wordpress.js
Requesting series in ASC order.
There's some work to do here around destructuring / types, but this will do for now.
> request series in ASC for nav

- client/scss/base/_row.scss
- client/scss/utilities/_variables.scss
- server/views/components/new-site-notice/index.njk
- server/views/pages/article.njk
Starting to think about tests - maybe we can get this out before the new edition goes out.
It is only on mobile (where we have the most traffic and it is easiest to implement).
It puts your name in a Mailchimp list specifically for the Digital Story: Electric Sublime.
It's currently at the bottom of the article.
I've chose the turquoise as you don't notice it in black as per the design, and for a test, that's not great. We can revisit that, or even test it.
__notes__
* The code is crap, I have tried to add as little code to the perm codebase so as to make sure we refactor if this works, and we don't add gumpf either that we forget to remove `.row--mobile-only`
* I haven't plugged it into Google Analytics, I wonder if we want a "saw component", "focussed on component", "submitted …
> Series email test

- server/services/author-lookup.js
Adding Chris as the author of Bill Morrison: Domesticating electricity
> Added Chris as author of domesticating elec video

- nginx-proxy/nginx.conf
Getting more ready for the big switcheroo.
This has made the category and tag redirects correct, and also allows feed (RSS) links to proxy through to Wordpress.
Once this is done, we take over the URL - and voi la.
Fixes #635
> Blog rewrite rules

- server/middleware/error.js
Having 404s sent to sentry 💥ed  our allowance.
I've also added the URL for debugging to be easier.
> 404 sentry notrack

- nginx-proxy/nginx.conf
Getting ready to become 👑  of the domains.
Then we can point `wellcomecollection.org` to our site and start adhering to [our URL strategy](https://github.com/wellcometrust/wellcomecollection.org/wiki/V1-=---V2-URL-migration-plan).
👻
> add server to nginx that proxies root domain traffic to prev.

- server/services/wordpress.js
- server/test/app/app.js
* Fixed adding a default value for query.
* Added test to make sure series pages render.
Not like an error.
> Default obj val

- client/js/components/content-slider.js
- client/js/utils/track-event.js
- server/controllers/index.js
- server/model/tracking-event.js
- server/views/components/article-body/index.njk
- server/views/components/image-gallery/index.njk
* Add ids to image galleries
* Add `trackEvent` that sends events to mixpanel (and could to GA).
> add tracking event to content slider controls

- server/services/wordpress.js
Let's not be 🐌  and just choose the first series. actually look it up.
Fixes #774.
> search for series instead of being lazy and just chosing the first one

- server/controllers/catalogue.js
- server/controllers/index.js
- server/model/catalogue-item.js
- server/routes/index.js
- server/services/wellcomecollection-api.js
This reverts commit d2bea786675a27838e74d5863997c9ecbac5850f.
Adds a very basic endpoint to return the JSON from the [catalogue API](https://api.wellcomecollection.org/catalogue/v0/demoItem)
> Read from the new amazing collections API

- server/model/promo.js
- server/views/components/transporter/index.config.js
- server/views/templates/article.config.yml
Thinking that cardigan needs a think.
And our content model (actually this has had a think, but some things need to catch up).
Maybe we have a think before the 30 June when we go to the patterns day?
> Fix cardigan

- server/controllers/catalogue.js
- server/services/wellcomecollection-api.js
- server/views/pages/catalogue-item.njk
Adding a basic page for the `demoItem`
> Catalogue item page

- client/libs/ga-scroll-depth.js
Updating the timingVar name to be more appropriate for GA's output.
> Add better timingVar name

- client/scss/components/_captioned_image.scss
- client/scss/utilities/_variables.scss
Addresses some of the contrast issues in #606, as per Tomi's instructions
Better contrast for image captions and links
> Colour changes

- client/scss/components/_numbered_list.scss
More contrast to pass WCAG AA. Fixes #781.
> Numbered list contrast

- client/scss/components/_numbered_list.scss
- server/views/components/numbered-list/index.njk
> Series nav part numbers

- client/scss/components/_numbered_list.scss
- client/scss/utilities/_mixins.scss
> change to series nav key line colour

- server/util/body-parser.js
> Return 'blockquote' if 'quote' isn't defined

- client/scss/base/_icons.scss
- client/scss/components/_article.scss
- client/scss/components/_author.scss
- client/scss/components/_body_content.scss
- client/scss/components/_buttons.scss
- client/scss/components/_captioned_image.scss
- client/scss/components/_divider.scss
- client/scss/components/_find_us.scss
- client/scss/components/_footer.scss
- client/scss/components/_footer_nav.scss
- client/scss/components/_footer_social.scss
- client/scss/components/_grid_placeholder.scss
- client/scss/components/_header.scss
- client/scss/components/_image_gallery.scss
- client/scss/components/_interview.scss
- client/scss/components/_more_info_link.scss
- client/scss/components/_numbered_list.scss
- client/scss/components/_opening_hours.scss
- client/scss/components/_page_description.scss
- client/scss/components/_promo.scss
- client/scss/components/_quote.scss
- client/scss/components/_tags.scss
- client/scss/components/_transporter.scss
- client/scss/grids/_grid_dividers.scss
- client/scss/styleguide/_styleguide.scss
- client/scss/utilities/_root-scope-classes.scss
- client/scss/utilities/_variables.scss
- server/views/global/palette.config.yml
- server/views/pages/explore.njk
- server/views/pages/list.njk
Replacing colour variable names like `action-green-2` with standalone values like `mint` to decouple colours from where/how they are used.
🎨
> Update colour names

- server/controllers/catalogue.js
- server/controllers/index.js
- server/data/people.js
- server/model/article-stub.js
- server/model/article.js
- server/model/body-part.js
- server/model/media.js
- server/model/organization.js
- server/model/page-config.js
- server/model/promo-list.js
- server/model/promo.js
- server/model/series.js
- server/model/ui-component.js
- server/model/video.js
- server/package.json
- server/services/author-lookup.js
- server/services/wellcomecollection-api.js
- server/services/wordpress.js
- server/views/components/promo/index.config.js
I was looking at linting and got into flow instead.
I want to figure out what we think is necessary to catch errors before they hit prod.
> Fix flow errors

- server/controllers/index.js
Importing of methods and types need to be separate.
> import methods and types properly

- infra/terraform/templates/alb.tf
This was manually set in the console.
__Next step:__ Automate the creation of the bucket and IAM roles etc
> add ALB logs to bucket

- server/cardigan-theme/partials/header.nunj
- server/cardigan-theme/tweaks.css
- server/fractal-app.js
Updating the header to be more `WellColl`.
> add new Cardigan header

- server/model/media.js
- server/util/body-parser.js
Getting `alt` and `data-copyright` definitions added to the featured image.
> Add alt and copyright defs to featured image

- nginx-proxy/nginx.conf
Sending the host to the `prev.` server to make sure it renders correctly.
> pass host to nginx-proxy for wellcomecollection.org

- .eslintignore
- .eslintrc.json
- client/gulpfile.js
- client/package.json
- package.json
- server/config/index.js
- server/controllers/index.js
- server/data/series.js
- server/extensions/component-v2.js
- server/fractal-app.js
- server/model/image-gallery.js
- server/model/opening-hours.js
- server/model/person.js
- server/model/promo.js
- server/optimise-svgs.js
- server/services/wordpress.js
- server/test/mocks/dom-nodes.js
- server/util/json-ld.js
- server/view/render.js
- server/views/components/find-us/index.config.js
- server/views/components/transporter/index.config.js
> Lint server

- client/js/components/content-slider.js
- client/scss/components/_image_gallery.scss
Showing users gallery images are clickable (scroll to the image) if JS is working.
Also blurring the slider controls after a click (but not a keypress) to remove the grey background of the focus state. Fixes #808.
> Make cursor a pointer over js-enhanced images

- server/services/author-lookup.js
> add rob as author of foot

- server/controllers/index.js
- server/package.json
- server/routes/index.js
- server/services/prismic.js
A first stab at getting prismic data into the site.
This has catered specifically for the webcoming.
> super basic support for prismic

- server/views/components/captioned-image/index.njk
Keep inline with:
https://creativecommons.org/licenses/by-nc/4.0/
> remove dash from CC

- server/data/people.js
- server/services/prismic.js
- server/views/pages/article.njk
De-duping the author component if there isn't any other body copy.
> Author bio repeat

- client/scss/components/_captioned_image.scss
Reducing the height of the comic to 95% of the viewport (so that it fits comfortably).
> Comic height

- server/data/people.js
- server/services/author-lookup.js
Adding Sarah and Robert's picture and bios as per @RussellDornan's request.
> add images and descriptions for authors: robert and sarah

- client/js/components/content-slider.js
- client/js/components/truncate-text.js
Adding tracking to the more/less things to see how much effort we should be putting into them
I'd like to decouple the tacking somehow, potentially just make it component based, but I will have a think.
Moved a couple of functions out to so they don't need to be defined for each truncator.
> add tracking to truncators of image gallery

- server/util/body-parser.js
Found it clogging up our logs.
> remove stray console.log

- client/js/components/feature-flags.js
- server/cache/interval-cache.js
- server/config/index.js
- server/controllers/index.js
- server/fractal-app.js
- server/package.json
- server/routes/index.js
- server/services/flags-lookup.js
- server/view/env-utils.js
- server/view/render.js
- server/views/layout/default.njk
Fixes #451 
Allows us to wrap our code in feature flags in the following ways:
```JS
import {intervalCache} from '../cache/interval-cache';
const featureFlags = intervalCache.get('flags');
const testFlag = featureFlags.testFlag;
if (testFlag) {
// test flag is set to true
} else {
// test flag is set to false or doesn't exist
}
```
```TWIG
{% set testFlag = featureFlags.testFlag %}
{% if testFlag %}
test flag is set to true
{% else %}
test flag is set to false or doesn't exist
{% endif %}
```
```JS
import { featureFlags } from './feature-flags';
const testFlag = featureFlags.testFlag;
if (testFlag) {
// test flag is set to true
} else {
// test flag is set to false or doesn't exist
}
```
> Feature flags

- server/cache/interval-cache.js
Bumping the polling time from 1 second to every 5 minutes
> Only poll for new flags every 5 minutes

- server/views/pages/article.njk
Don't show the 'send me the next part in this series' email if we're on the last part. Fixes #863.
> Check for final part

- server/data/people.js
> update Rob bidder

- server/build-cardigan.js
- server/package.json
Somewhere something has happened with the fractal build so it doesn't exit.
https://circleci.com/gh/wellcometrust/wellcomecollection.org/1884
[I've filed an issue with the Fractal team](https://github.com/frctl/fractal/issues/245). I think it might have something to do with Vorpal, but honestly can't really figure it out.
I think I might prefer this way as it way less noisy in the console.
> add programatic fractal/cardigan build

- client/scss/base/_row.scss
- server/views/pages/article.njk
The series is done.
Let's catch up about what we might want to do in the future?
> remove email signup

- client/js/components/truncate-text.js
Fixes this: https://sentry.io/wellcome/wellcomecollection/issues/269390704/
🌞
> Prevent error if slider images don't have caption text

- server/services/author-lookup.js
Adding Rob for his new piece.
🙏 ing for the new CMS.
> add Rob as author for thirst

- infra/deploy.sh
Adding the thumbor terraform resources to up date when we run deploy.
> add thumbor service and task definition to deploy script

- server/build-cardigan.js
- server/data/people.js
- server/services/author-lookup.js
Adding Elissavet Ntoulia as an author.
> Add Elissavet Ntoulia as an author

- client/scss/components/_captioned_image.scss
Explaining the existence of style so it's not removed by mistake in the future
> Added comment

- server/package.json
- server/prismic-export-app.js
Just a few fixes to make the export easier to manage.
> Couple of tweaks to the prismic export

- server/data/people.js
- server/services/author-lookup.js
Adding Lalita Kaplish and Briony Hudson as authors.
> Add Lalita and Briony

- client/scss/critical.scss
- client/scss/non-critical.scss
Fixes / References #
This is a:
Think when I rebased I accidentally put styles back into the critical css that shouldn't have been there.
This moves them out again.
> Moving styles from critical to non-critical

- client/js/app.js
- client/js/components/wobbly-edge.js
- client/scss/components/_image_gallery.scss
- client/scss/components/_slider.scss
- client/scss/components/_wobbly_edge.scss
- server/views/components/image-gallery/index.njk
- server/views/pages/article.njk
Relates to #941.
This is a:
Decoupling the wobbly line from the slider.
> Decouple wobbly line from slider

- server/views/components/find-us/index.njk
- server/views/components/image/index.njk
This is a:
Map image wasn't being lazy loaded, this shaves off some more KB from the page load
> Use lazy-loading for map image

- client/gulpfile.js
- client/scss/components/_body_content.scss
- client/scss/components/_pre.scss
- client/scss/non-critical.scss
- client/scss/shame.scss
- client/scss/utilities/_root-scope-classes.scss
- server/util/body-parser.js
- server/views/components/article-body/index.njk
Fixes #899 
✨ Feature  
People can read poetry and feel lovely.
We can publish poetry and know that they're feeling lovely.
> Preformatted

- server/services/author-lookup.js
🚑 Health
Because Rob drew the picture, he get's the credit
> add robert bidder to crisps

- server/services/author-lookup.js
🔧 Fix  
Gives credit where credit is due
> add rob to his works

- client/js/components/content-slider.js
- client/scss/base/_responsive-defaults.scss
- client/scss/components/_chapter_indicator.scss
- client/scss/components/_slider.scss
- client/scss/components/_slider__gallery.scss
- client/scss/utilities/_mixins.scss
References #897
🚑 Health
Improves janky slider behaviour in Chrome/ disappearing reappearing content flashes
Before:
After:
> Runtime performance

- server/services/author-lookup.js
🚑 Health
Adding Helen Babbs as the author of 'Blackout'.
> Add Helen as author of 'blackout'

- server/data/people.js
- server/services/author-lookup.js
🚑 Health
She get's credit for her work
> Add Sarah James to authors

- server/services/author-lookup.js
🚑 Health
People know who wrote the article 😃
> Added Helen as author of electropoise

- server/data/people.js
- server/services/author-lookup.js
✨ Feature  
Brings us a fine editor indeed.
> add Danny Birchall to our growing list of contributors

- Dockerfile
- server/fractal-app.js
🚑 Health
* making the application container run faster on V8
* Making it push to docker quicker as we're now using Alpine.
I would like to get the circle build to use Alpine too - but it's a bit of effort as you lose a lot of general functionality (`popd` etc).
> update to node8-alpine

- client/scss/base/_responsive-defaults.scss
- client/scss/components/_chapter_indicator.scss
🚑 Health
Makes sure images fill their containers
> Make sure images fill their containers

- server/model/page-config.js
🔧 Fix  
Stops pages erroring when an article isn't part of any series
> Account for article not being part of any series

- server/controllers/index.js
- server/views/partials/analytics.njk
🔧 Fix  
Uses the correct key to track the series information on both list and article pages.
> Use correct key for series tracking

- server/data/people.js
- server/data/series.js
- server/model/page-config.js
- server/services/author-lookup.js
✨ Feature  
Adding necessary meta for the upcoming _Outsiders_ digital story.
> Outsiders digital story

- server/services/author-lookup.js
🚑 Health
Adding Elissavet Ntoulia as author of _Wonder Woman's wonder women_ article.
- [x Any introduced code complexity has been flagged
> Add Elissavet as author of Wonder Woman article

- server/services/twitter.js
🚑 Health
Only displays the pure gold explorewellcome tweets (removes any `@replies`).
> Exclude replies from twitter response

- server/data/people.js
- server/services/author-lookup.js
🚑 Health
Adding authors to slugs.
> Update author info

- client/js/components/join-cohort.js
- server/views/pages/flags.njk
✨ Feature  
Visual feedback: updates the displayed cohort the user belongs to, when the click on a button
> Just a visual clue that cohort has changed

- server/services/author-lookup.js
🚑 Health
Does what it says in the commit message.
> Add 'camille-henrot-animating-horoscopes': people.chrisChapman

- server/data/people.js
> add sarah james twitter handle

- .gitignore
- client/js/components/instagram.js
Removes a stray log and adds package-lock to gitignore (we probably shouldn't do this, but I'd like to test it properly)
> Remove consolelog

- server/services/prismic-content.js
🔧 Fix  
Stops errors coming through and 😱 ing me.
> return nothing if the prismic article isn't found

- server/routes/index.js
🔧 Fix  
Things work as you expect them to. Who thought insensitive would be the default. Crickey.
> make router sensitive

- server/views/pages/list.njk
Fixes #924
🔧 Fix  
Appeases pixel manager.
> Spacing fixes

- server/services/prismic-content.js
🔧 Fix  
Using common language.
😶
> use the term editorial image over embedded

- server/services/prismic-curated-lists.js
🔧 Fix  
Typo from a merge when I renamed this thing.
Annoyingly, as we don't lint, and I have no tests on this page, it broke.
Luckily it's not a prod URL, and when it becomes one there is already a test written.
> renaming issue from mere

- .github/PULL_REQUEST_TEMPLATE.md
> Using common language of bug, albeit with fix postfixed.

- server/data/people.js
- server/services/author-lookup.js
Adding Wendy Moore
_PLEASE DO NOT MERGE_
> Add wendy moore

- server/data/people.js
> Remove (s)

- build-cardigan.sh
> NPM install on cardigan build

- server/cardigan-theme/partials/head.nunj
🐛 Bugfix  
Now I know exactly where I am and feel less lost, I hope other's feel the same.
> update Cardigan's title

- server/services/author-lookup.js
🚑 Health
Adds Helen as author of Sharing nature: making connections
> Add Helen as author of Sharing nature: making connections

- server/services/prismic-content.js
🐛 Bugfix  
Using common language leads to common understanding (or brainwashing).
Using language from here: #928
Model updated here: https://github.com/wellcometrust/wellcomecollection-content-model/pull/1/files
> use contributor over creator

- server/controllers/lists.js
- server/services/flags-lookup.js
🚑 Health
By allowing us to test with Prismic before we go live, giving editorial confidence.
This will eventually be promoted and the code removed.
> put prismic on explore section behind a cohort

- server/controllers/async-controllers.js
- server/controllers/content.js
- server/controllers/index.js
- server/controllers/utils.js
- server/package.json
- server/routes/index.js
- server/views/components/series-container/series-container.njk
🚑 Health
Makes the routes tidier - and clears up not using the Worpdress ones.
I was going to start some work on the RSS, and this seemed confusing.
> Routes tidy

- server/services/author-lookup.js
🚑 Health
Adds Rob as author of body-squabbles-parasites
> added Rob as author of body-squabbles-parasites

- nginx-proxy/nginx.conf
References #1099
🐛 Bugfix  
Using perm as it's perm
> Use permanent redirects for blog. traffic

- server/services/author-lookup.js
🚑 Health
Attaches author to article
> Add Helen as author of Animal Doctors

- client/scss/components/_promo.scss
- server/services/wellcomecollection-api.js
- server/views/components/promo/promo.njk
- server/views/pages/search.njk
References #1002
✨ Feature  
Begins implementing MVP features on search results:
Removed description
Align images at the bottom; 
mask the top of cut off images;
96 results per page
> Parts of #1002

- server/filters/index.js
- server/filters/json-ld.js
- server/model/organization.js
- server/util/json-ld.js
- server/views/layout/default.njk
- server/views/pages/article.njk
- server/views/pages/curated-lists.njk
Fixes #1099 
🚑 Health
By making us more searchable.
> Site descriptions jsonld

- server/controllers/content.js
- server/controllers/lists.js
- server/routes/index.js
- server/services/prismic-content.js
- server/views/pages/article.njk
🐛 Bugfix  
Matches the content model here:
https://github.com/wellcometrust/wellcomecollection-content-model/pull/2
Explanation as to why is in that PR.
> Update to match prismic model

- server/services/author-lookup.js
🚑 Health
Add Rob Bidder as author of body-squabbles-plague
> Add Rob Bidder as author of body-squabbles-plague

- client/scss/components/_promo.scss
- server/views/components/promo/promo.njk
- server/views/pages/search.njk
References # 1002
✨ Feature  
Adds styling to match designs
> Search results styling

- server/views/pages/list.njk
- server/views/pages/search.njk
✨ Feature  
Layout matches intended design
> Removed divider and adjusted spacing as per Tomi's feedback

- client/js/tracking.js
- server/views/components/back-to-top/back-to-top.njk
- server/views/pages/search.njk
References #1112 #1120 
🚑 Health
I'd like to keep tracking on all new components.
I would say this is controversial tracking as using it could suggest fault with our layout as opposed to success. 
Discussion here.
> add tracking to back to top

- server/util/json-ld.js
🐛 Bugfix  
Things work and we can see shrunken :rage1: again.
> allow null values in JSON LD

- server/views/docs/visual-architecture.njk
🚑 Health
Add anchors to visual architecture page.
> Add anchors to visual architecture page

- server/services/prismic-content.js
- server/views/pages/event.njk
✨ Feature  
We know who organised the event
> add contributors to events

- server/services/author-lookup.js
> Add Lalita to sunglasses

- server/controllers/content.js
- server/routes/index.js
- server/services/prismic-content.js
🐛 Bugfix  
Allows us to preview.
> Fix prismic preview

- README.md
> Remove Nginx from README

- docs/monitoring-strategy.md
- infra/README.md
- infra/deploy.sh
- server/README.md
🚑 Health / ✍️ Docs
Fixes to the documentation from the runbook session. Other developers can run the code!
> README fixes from the runbook session

- server/views/global/typography/typography.config.js
🐛 Bugfix  
Displays the correct type name/style in Cardigan.
> Add typography style name to config for Cardigan

- server/services/prismic-content.js
🚑 Health
It's a slightly nicer interface in Prismic.
> use slice_labels for weight

- server/middleware/error.js
> send full URI to sentry

- server/app.js
- server/middleware/interval-cache.js
🐛 Bugfix  
* Fix intervalCache.get error
* Allow error page to render by having the correct middleware order (not great, but it works)
> set correct default value for flags intervalCache

- server/views/components/numbered-list/numbered-list.njk
Fixes #1176
🐛 Bugfix  
It works again
> fix series nav positioning

- server/controllers/index.js
🐛 Bugfix  
We stop getting wrong errors.
I'd like to look at how we track 404s though.
> 404 when there is no series

- server/views/docs/visual-architecture.njk
🚑 Health
Documents the spacing/font filters to help with on-boarding/forgetfulness/posterity.
> Classes documentation

- server/middleware/error.js
- server/views/components/captioned-image/captioned-image.njk
- server/views/components/main-media-comic/main-media-comic.config.js
- server/views/components/main-media-comic/main-media-comic.njk
- server/views/components/main-media-video/main-media-video.config.js
- server/views/components/main-media-video/main-media-video.njk
- server/views/components/main-media/main-media.njk
- server/views/pages/article.njk
💊 
I think this makes it easier to fathom around how main media works.
It just splits it into video, comic, and article main medias.
Business as usual 🚗
> simplify (I think) the inheritance of how main media is displayed

- infra/deploy.sh
- infra/terraform/dev/wellcomecollection.tf
- infra/terraform/prod/wellcomecollection.tf
- infra/terraform/templates/launch.tf
- infra/terraform/templates/s3.tf
- infra/terraform/templates/vars.tf
🚑 Health
Making it easier to maintain the tfvars, and not requiring people to magically know what tfvars to have.
> use tfvars from s3

- server/views/pages/article.njk
> check for main media

- server/controllers/work.js
- server/views/components/image-iiif/image-iiif.njk
- server/views/components/promo/promo.njk
- server/views/pages/search.njk
Fixes #1190 
✨ Feature  
Allows us to use loris behind a switch.
Removes deps on ImgIx which we are not using.
> Iiif loris

- server/views/components/footer/footer.njk
- server/views/components/page-description/page-description.njk
🐛 Bugfix  
Add missing classes to fix slightly broken components at xlarge breakpoint.
> Fix footer/page-description at largest breakpoint

- client/scss/components/_captioned_image.scss
- server/filters/get-link-objects.js
- server/filters/index.js
- server/model/link.js
- server/test/mocks/wellcomecollection-api.json
- server/views/components/license/license.njk
- server/views/components/return-to-results/return-to-results.njk
- server/views/pages/work.njk
- server/views/templates/work.config.js
- server/views/templates/work.njk
Closes #1140
✨ Feature  
Displays title, licensing information and most relevant meta information with a clear visual hierarchy
> Work header area

- server/model/article.js
- server/services/prismic-content.js
- server/views/pages/article.njk
✨ Feature  
We can add multiple authors, when content comes from Prismic.
> support multiple authors with prismic content

- server/services/author-lookup.js
> Add Rob as author of body-squabbles-button

- server/views/components/captioned-image/captioned-image.njk
- server/views/pages/work.njk
🐛 Bugfix  
currently getting a broken image link, this fixes it
> use image-iiif component on work page

- server/views/components/drawer/drawer.njk
- server/views/components/header/header.njk
- server/views/components/work-drawer/work-drawer.njk
- server/views/pages/work.njk
- server/views/templates/work.config.js
Adding the drawers component to the work page (bit quick and dirty, but fine for now I think)
Can check designs and show potential users more complete version of the page - without having the data from the API
> Drawers on work page

- server/views/pages/article.njk
🐛 Bugfix  
Puts the authors back in their place.
> process authors properly at bottom of article

- server/filters/get-link-objects.js
- server/views/pages/work.njk
✨ Feature  
Improves the results returned from author links on work page
> prepend 'creators:' to author search links query

- server/controllers/content.js
- server/services/prismic-content.js
Noticed as Helen is trying to use the preview.
Was part of #1225 but need to get this out fast.
> UPdate to reflect new promsmic model

- client/scss/utilities/_root-scope-classes.scss
- server/views/components/article-body/article-body.njk
🐛 Bugfix  
Makes things look nice.
__Before__
__After__
> add some spacing to full width image

- server/controllers/work.js
- server/views/pages/work.njk
✨ Feature  
prevents us leaking google juice
> Add canonical url to work page

- client/scss/styleguide/_styleguide.scss
- client/scss/utilities/_variables.scss
- server/views/components/find-us/find-us.njk
- server/views/components/interview/interview.njk
- server/views/components/new-site-notice/new-site-notice.njk
- server/views/components/numbered-list/numbered-list.njk
- server/views/components/opening-hours/opening-hours.njk
- server/views/components/promo/promo.njk
- server/views/global/typography/typography.config.js
Tomi says we don't require HNL5 font style and can just use what was HNL6 in it's place
🚑 Health
less code
> removed current HNL5 font style and bumped the others down

- server/services/prismic-content.js
🐛 Bugfix  
As contributors is going to be common, let's pull it out.
Also it will now work on webcomics.
> abstract getting contributors out of prismic

- server/views/pages/curated-lists.njk
🐛 Bugfix  
Fixes broken layout
> Only show max 6 promos in 'you may have missed' section

- package.json
- server/controllers/content.js
- server/controllers/work.js
- server/util/body-parser.js
- server/views/components/search-box/search-box.njk
🐛 Bugfix  
Makes the search bar more specific
Fixes a eslint bug
> make search box placeholder more specific

- client/scss/base/_row.scss
- client/scss/utilities/_root-scope-classes.scss
- server/views/components/footer/footer.njk
- server/views/components/main-media-comic/main-media-comic.njk
- server/views/components/main-media-video/main-media-video.njk
- server/views/components/main-media/main-media.njk
- server/views/components/meta-unit/meta-unit.njk
- server/views/components/new-site-notice/new-site-notice.njk
- server/views/components/promo/promo.njk
- server/views/components/return-to-results/return-to-results.njk
- server/views/components/social-media-block/social-media-block.njk
- server/views/components/transporter/transporter.njk
- server/views/pages/article.njk
- server/views/pages/curated-lists.njk
- server/views/pages/event.njk
- server/views/pages/list.njk
- server/views/pages/search.njk
- server/views/pages/work.njk
- server/views/templates/explore.njk
🚑 Health
Removes duplicate classes that set background colours, and removes BEM variant naming convention where it didn't really belong.
> Update use of background color classes

- client/scss/utilities/_root-scope-classes.scss
🐛 Bugfix  
Can we get a Clippy linter that says, "Did you mean..."
> make no-padding apply no padding

- server/services/author-lookup.js
Add Helen as author of sharing-nature-dead
> Add Helen as author of sharing-nature-dead

- client/scss/components/_chapter_indicator.scss
🐛 Bugfix  
Stops the chapter indicator bars being mega.
> Fix chapter indicator bars

- server/views/pages/article.njk
> use the actual property for author bio

- server/views/components/footer/footer.njk
> Use UK spelling of 'licensed' for CC attribution

- server/views/components/footer/footer.njk
> Correct Licence spelling

- server/services/prismic-content.js
✨ Feature  
render links in image captions on Prismic articles
> allow links in captions

- server/controllers/work.js
🐛 Bugfix  
Stops images getting pixelated
> larger max image size for work images

- server/views/components/tags/tags.config.js
- server/views/components/tags/tags.njk
🚑 Health
Allows linking between Cardigan templates.
> Link to exhibition template from tags

- server/controllers/work.js
> Fix image origin address

- client/scss/base/_typography.scss
🚑 Health
Makes body copy easier to read on mobile (after line-height was decreased in #1274).
> Bump up mobile body font size

- client/js/tracking.js
- server/routes/index.js
- server/views/pages/work.njk
References #1117 #1004 
✨ Feature  
People can download the full image.
> add download button to works page

- server/controllers/content.js
- server/model/page-config.js
- server/views/partials/analytics.njk
🚑 Health
Makes the dimensions make more sense.
Also tracks this data from Prismic which it isn't doing.
> add analytics to the prismic content too

- server/views/components/tags/tags.config.js
- server/views/components/tags/tags.njk
- server/views/pages/search.njk
- server/views/templates/exhibition.config.js
References #1337
🚑  Health
Improves search landing page messaging/addresses some issues surfaced in usability testing.
> Search landing

- client/js/components/copy-url.js
- client/scss/components/_buttons.scss
- server/controllers/work.js
- server/views/components/copy-url/copy-url.njk
- server/views/components/meta-unit/meta-unit.njk
- server/views/pages/work.njk
- server/views/templates/work.config.js
References #1312 #1334 
✨ Feature  
Makes it slightly more clear as to what you're doing.
Let's get this to test and tidy.
> add more info to download section and fix up link sharing

- server/services/prismic-content.js
🐛 Bugfix  
Lists should never be nullable, just empty lists.
> ensure that series is always a list on articles

- server/controllers/work.js
- server/views/pages/work.njk
- server/views/templates/work.config.js
🐛 Bugfix  
Add the correct value for canonical urls/copy-url buttons.
> Use request.host instead of origin

- nginx-proxy/nginx.conf
✨ Feature  
Let's start stealing traffic directly from wellcomecollection.org.
> syphon traffic from explore to next.

- server/app.js
- server/controllers/work.js
🐛  Bugfix  
Another go at getting the correct/desired host value for canonical urls/copy-url buttons.
> Add proxy = true to Koa app

- server/views/partials/analytics.njk
Lost this a while ago - a shame as it makes filtering traffic from GA now retrospectively impossible.
> add back in GA version

- server/controllers/work.js
✨ Feature  
Add this `collections` category.
We will then have:
* editorial
* publicprograms
* collections
* list <= 😕
> add collections categoryto works

- server/views/pages/search.njk
🚑  Health
Tidies up information flow on search landing page
> Search page content rejig

- server/views/components/copy-url/copy-url.njk
- server/views/pages/work.njk
Just making all events categorised as the same thing.
The download will become more interesting as we add more items / locations etc, but for now, you are downloading the work.
> add analytics specific to works

- server/views/pages/work.njk
🐛 Bugfix  
Corrects the (hard-coded) licen(s|c)e information.
> CC-BY instead of CC-BY-NC

- server/views/pages/search.njk
Fixes #1364. I was waiting for a test to run and fancied reading a bit more of your codebase, hope you don’t mind. 🙂
Screenshot:
> Put more interesting suggested topics on the search page

- server/controllers/content.js
- server/routes/index.js
- server/services/exhibitions.js
- server/services/prismic-content.js
✨ Feature  
Allows editors to preview the exhibitions before publishing.
> allow exhibitions to be previewed

- server/filters/get-license-info.js
- server/filters/index.js
- server/model/license.js
- server/views/components/license/license.config.js
- server/views/components/license/license.njk
- server/views/components/main-media-comic/main-media-comic.njk
- server/views/pages/work.njk
- server/views/templates/work.config.js
References #1371
🚑 Health
Simplifies the license component template.
> Improve license mapping

- server/services/wellcomecollection-api.js
- server/views/pages/work.njk
References #1078 
✨ Feature  
Displays the _actual_ license from the _actual_ API
> Work license

- server/content-model/content-blocks.js
- server/model/image-gallery.js
- server/services/exhibitions.js
- server/services/prismic-content.js
- server/views/pages/exhibition.njk
✨ Feature  
🐛 Bugfix  
📈 Test  
🚑 Health
Brings in extra content from Prismic.
This was after talking to the content team, and they seem happy with the model.
__Next:__
* Add books module.
* add in default access statements.
> use a slightly updated model for prismic exhibitions

- client/js/components/async-content.js
- nginx-proxy/nginx.conf
- server/routes/index.js
✨ Feature  
Allow traffic through to wellcomecollection.org so we can start taking over the root domain.
It's a little technically annoying that there is actually quite a lot of traffic through to old articles. This makes me think that we could probably transfer those over.
> Nginx assets

- server/model/organization.js
- server/util/json-ld.js
- server/views/pages/article.njk
Fixes #1328
🐛 Bugfix  
Puts author back onto the article JSON-LD.
> fix JSON-LD for article authors

- server/filters/get-license-info.js
- server/views/components/license/license.njk
- server/views/pages/work.njk
> add license description to work

- nginx-proxy/nginx.conf
✨ Feature  
Adding a fallback for all 404s to V2.
Getting us 1 step closer to owning the whole domain.
> fallback for all 404s to V2 in nginx proxy

- server/views/partials/analytics.njk
🐛 Bugfix 
Hide the nav until google optimize has kicked in, so users don't see 'explore' change to 'magazine'
> Add async-hide styles for element controlled by google optimize

- server/routes/index.js
- server/views/components/work-media/work-media.njk
- server/views/components/works-search/works-search.njk
- server/views/pages/search.njk
✨ Feature  
The reason for this is so that we can move over to wellcomecollection.org, but we can't yet take over `/search` as it serves another function.
> use 'works' as the route for the works search

- server/app.js
- server/controllers/content.js
- server/controllers/work.js
- server/model/page-config.js
- server/views/layout/default.njk
- server/views/pages/work.njk
🚑 Health
Things should have canonical URIs.
Now they do.
> add canonical uris to all pages

- server/controllers/content.js
References #1099
🐛 Bugfix  
Ooops - titles are definitely needed.
> add article title in from primic content

- server/controllers/content.js
- server/filters/index.js
- server/filters/prismic.js
- server/views/pages/curated-lists.njk
✨ Feature  
Descriptions can now be controlled by an editor.
This will probably be us at first, but means that we can do it without a release etc.
> use descriptions on list pages from prismic

- server/controllers/work.js
- server/services/wellcomecollection-api.js
- server/views/pages/search.njk
🚑  Health
We now get thumbnails from the API. Let's use them.
> Use thumbnails from the API

- client/scss/critical.scss
- client/scss/non-critical.scss
🐛  Bugfix  
Prevents janky relayout of the search input on the`/works` page
Stops this
> Make search box styles critical

- client/js/tracking.js
🐛 Bugfix  
Noticed this in Sentry.
Best get it fixed prior release.
> fix ga event tracking

- server/filters/get-link-objects.js
> fix broken links

- server/filters/convert-image-uri.js
> removed console log

- server/middleware/error.js
- server/views/components/image/image.njk
Making it easier to debug from the instances, rather than having to dig in the logs...
> pass path to error

- infra/terraform/cloudfront/cloudfront.tf
Getting Drupal to work behind CloudFront.
Thanks @alfraser86 - amazing work.
> Drupal cdn

- server/views/components/article-body/article-body.njk
🐛 Bugfix  
Fixes the issue we noticed in GA, where galleries were all given the same ids
> Fix gallery ids, so they are sequential

- server/filters/convert-image-uri.js
- server/util/is-empty-obj.js
- server/views/components/article-body/article-body.njk
References #1369
🐛 Bugfix  
Page no longer returns a 500 error
> Fix error when imageList is first body part

- server/services/prismic-content.js
🐛  Bugfix  
Allows articles to render without an author
> Filter null authors

- server/views/components/work-drawer/work-drawer.njk
- server/views/pages/work.njk
Closes #1453
✨ Feature  
Puts useful information on the page.
> Use desciption where available

- server/controllers/work.js
- server/views/pages/search.njk
🐛  Bugfix  
Improves title content for the work/collections search pages
> Improve page titles

- server/views/pages/work.njk
🐛 Bugfix  
Fixes broken download links.
> Don't point at Amazon S3 bucket

- client/js/utils/flag-status.js
- server/util/flag-status.js
🐛 Bugfix  
correct feature flag value wasn't always returned
> make sure correct flag status is returned

- client/scss/components/_exhibition_hero.scss
- client/scss/critical.scss
- client/scss/utilities/_root-scope-classes.scss
- server/content-model/content-blocks.js
- server/filters/get-breakpoint.js
- server/filters/index.js
- server/services/exhibitions.js
- server/views/components/footer/footer.njk
- server/views/components/opening-hours/opening-hours.njk
- server/views/components/picture/picture.config.js
- server/views/components/picture/picture.njk
- server/views/pages/exhibition.njk
References #1466
✨  Feature    
Adds responsive picture behaviour to the top of the exhibition page
> Exhibition hero

- client/js/utils/flag-status.js
- server/util/flag-status.js
🐛 Bugfix  
Page templates render properly in Cardigan
> Check flagConfig is not undefined before preceeding

- infra/README.md
- infra/setup.sh
- infra/terraform-config/README.md
- infra/terraform/cloudfront/cloudfront.tf
- infra/terraform/dev/terraform.tf
- infra/terraform/dev/wellcomecollection.tf
- infra/terraform/prod/terraform.tf
- infra/terraform/prod/wellcomecollection.tf
Done as we didn't have docs while I was away on how to deploy infrastructure.
Hopefully this makes sense.
@davidpmccormick @gestchild - if you update your terraform, and try this out (the setup step being the important one) - and let's see if we're good.
> update infra docs to reflect how we actuall deploy

- infra/terraform/cloudfront/cloudfront.tf
> Add methods to fix search

- server/filters/format-date.js
References #1466
🚑  Health
Uses the correct date label copy based on the current date.
> Update copy from date

- server/views/pages/exhibition.njk
Fixes/Closes/References #1466
🚑  Health
Lets people know if it's a permanent exhibition
> Replace dates with 'Permanenet exhibition' if there isn't an end date

- server/content-model/content-blocks.js
- server/services/prismic-content.js
- server/views/components/article-body/article-body.njk
- server/views/pages/article.njk
References: #1396 #1428 
✨ Feature  
I'm going to allow an image list to be featured, that way we can pull it out of the body and do more with it, but still have a body if we want.
Maybe should have done this with web comics...
We've essentially split the article into two parts - featured media at the top, body at the bottom.
There is nothing saying we can't have both.
> Featured media as a concept

- nginx-proxy/nginx.conf
We're still under budget strangely, but we should do this anyway...
> add gzip to root directory

- client/scss/base/_icons.scss
- client/scss/components/_exhibition_hero.scss
- client/scss/components/_tags.scss
- client/scss/utilities/_root-scope-classes.scss
- server/content-model/content-blocks.js
- server/filters/format-date.js
- server/filters/index.js
- server/services/exhibitions.js
- server/views/components/back-to-top/back-to-top.njk
- server/views/components/tags/tags.njk
- server/views/components/work-media/work-media.njk
- server/views/icons/other/status-indicator.svg
- server/views/pages/exhibition.njk
> Exhibition hero updates

- server/views/components/more-info-link/more-info-link.njk
- server/views/pages/curated-lists.njk
- server/views/pages/exhibition.njk
🐛  Bugfix  
Improves readability.
> More info link

- README.md
- nginx-proxy/nginx.conf
- server/config/index.js
- server/views/docs/PROGRESS_NOTES.md
- server/views/templates/article.config.js
🚑 Health
@jennpb realised the what we're up to could do with some love.
> Emove next

- client/scss/components/_book-promo.scss
- server/views/components/book-promo/book-promo.njk
- server/views/pages/exhibition.njk
> Exhibition design tweaks

- server/services/exhibitions.js
🐛 Bugfix 
Makes the page work again after updating content model
> updated API id to match model

- server/services/exhibitions.js
🐛  Bugfix  
Doesn't output garbage if there isn't an uploaded file.
Stops this:
> Check for presence of text/captions doc URL

- server/views/pages/work.njk
> Don’t use iiif-origin for downloads

- client/js/components/content-slider.js
Closes #1499
✨  Feature  
Allows the tracking of clicks on images in galleries.
> Track clicking on image gallery images

- server/filters/format-date.js
- server/views/pages/exhibition.njk
🚑 Health
Improves exhibition messaging
> Update exhibition copy

- server/filters/format-date.js
- server/package.json
Fixes #1509
🐛 Bugfix  
Returns the same date consistently.
> use London as the place for times

- server/views/components/author/author.njk
🐛  Bugfix  
Actually resizes the author images
> Use IIIF for author image resizing

- client/scss/components/_iframe_container.scss
- client/scss/non-critical.scss
- server/services/prismic-content.js
- server/views/components/article-body/article-body.njk
- server/views/components/iframe/iframe.config.js
- server/views/components/iframe/iframe.njk
- server/views/components/iframed-video/iframed-video.njk
✨  Feature 
Allows content editors to embed iframes within articles.
> Allow iframes in article body content

- server/services/prismic-content.js
- server/views/components/numbered-list/numbered-list.njk
- server/views/components/open-graph/open-graph.njk
- server/views/components/twitter-card/twitter-card.njk
🐛 Bugfix  
Use the iiif API for images everywhere.
> get twitter card image from iiif API

- server/controllers/content.js
- server/routes/index.js
- server/views/partials/analytics.njk
Heavily wedging the ga exp ID into this.
If we like the metrics we get, I'll iron this out, but don't want to do all the work if we don't like the metrics.
> add ga exp ID for graphicdesign

- server/views/partials/analytics.njk
🚑 Health
@davidpmccormick is there a reason I am missing as to why we didn't do this?
> use nunjucks logic to apply analytics information

- server/services/prismic-content.js
- server/util/json-ld.js
- server/views/pages/exhibition.njk
References #440
🚑  Health
Adds exhibition data for SEO
> Exhibition json ld

- server/content-model/exhibition.js
- server/services/exhibitions.js
- server/util/json-ld.js
🐛 Bugfix  
All the merges left us in a bit of a broken state.
Happy to revisit assets around an exhibition once this is out.
> untidy the exhibition model to stop the site breaking

- server/views/pages/exhibition.njk
🚑  Health
Lets us know how many people are clicking the 'Download exhibition texts' link.
> Track exhibition texts pdf download

- server/controllers/content.js
- server/filters/format-date.js
- server/services/events.js
- server/views/pages/event.njk
References #1532 
✨ Feature  
Allows us to attach a team to the event in which to contact for booking.
This is definitely a system that could use some exploring.
> Events booking enquiry

- nginx-proxy/nginx.conf
- server/services/prismic-content.js
🚑 Health
On event of moving onto events, we're going to want to render from V2 first/
> render events from v2, then v1

- server/services/prismic-content.js
- server/views/components/article-body/article-body.njk
🚑 Health
Noticed it as I was searching for schedule stuff for events.
> Remove schedule

- server/content-model/content-blocks.js
- server/content-model/event.js
- server/services/events.js
- server/services/prismic-content.js
- server/util/json-ld.js
- server/views/pages/article.njk
- server/views/pages/event.njk
- server/views/templates/event.njk
References #1532  wellcometrust/wellcomecollection-content-model/pull/15
✨ Feature  
Allows us to show off our amazing staff who organise events.
> Contributors

- server/model/article.js
🐛 Bugfix  
It's breaking the build, and I don't want to patch unsupported bits of the stack./
> Authomap remove

- nginx-proxy/nginx.conf
Reverts wellcometrust/wellcomecollection.org#1534
> Revert "render events from v2, then v1"

- server/views/pages/search.njk
🐛 Bugfix  
Puts the tags back on the works search page.
> Correct tags data shape

- server/routes/index.js
🐛 Bugfix  
Fixes the previews which I broke in #1575
> Add preview parameter regex

- server/util/json-ld.js
- server/views/pages/work.njk
References #1581
🚑 Health
Improves work page SEO
> Add as much work schema.org info as we currently have from the API

- nginx-proxy/nginx.conf
Should fix issue about uploading a large image in the drupal interface.
✨ Feature  
🐛 Bugfix  
📈 Test  
🚑 Health
> add drupal proxy config

- nginx-proxy/nginx.conf
Reverts wellcometrust/wellcomecollection.org#1572
> Revert "Revert "render events from v2, then v1""

- server/util/json-ld.js
- server/views/pages/event.njk
Fixes/Closes/References #1532
🚑 Health
Making our superduper events findable by SEs.
> Event JSON-LD

- server/views/partials/monitoring.njk
🚑 Health
Makes the monitoring script async.
> async loading of monitoring script

- nginx-proxy/nginx.conf
Reverts wellcometrust/wellcomecollection.org#1591
> Revert "Revert "Revert "render events from v2, then v1"""

- server/test/app/app.js
This reverts commit 95da5410538837ad6b536bc69c23856d0dcb1ed5.
✨ Feature  
🐛 Bugfix  
📈 Test  
🚑 Health
> Revert "remove explore test"

- infra/terraform/container-definitions.json
- infra/terraform/templates/launch.tf
🚑 Health
As we're taking on more traffic from events / exhibitions, we should be able to handle more traffic.
> update to t2 medium containers

- content-model/access-statements.json
- content-model/articles.json
- content-model/books.json
- content-model/curatedLists.json
- content-model/editorial-contributor-roles.json
- content-model/event-contributor-roles.json
- content-model/events.json
- content-model/exhibitions.json
- content-model/featureflag.json
- content-model/featurescohort.json
- content-model/galleries.json
- content-model/people.json
- content-model/promo.json
- content-model/series.json
- content-model/webcomics.json
🚑 Health
Moving the content model here as it makes way more sense.
> move prismic content model into this repo

- content-model/articles.json
- server/services/prismic-content.js
🚑 Health
Series can never be anything but a series, so I've moved to be a group.
This is to move forward with the work on the Why Sound series.
> use series as a group rather than a slice

- server/views/components/work-media/work-media.njk
🐛 Bugfix  
Rotate the back to results arrow icon some more.
> Moar icon rotate

- client/js/utils/flag-status.js
- content-model/featureflag.json
- server/controllers/work.js
- server/filters/index.js
- server/services/flags-lookup.js
- server/services/wellcomecollection-api.js
- server/util/flag-status.js
- server/views/pages/flags.njk
Closes #1594
✨ Feature
Allows us to use feature flags set in prismic to assign groups to a particular index for image searches
Using regular index:
Using new index:
> Search more images

- content-model/articles.json
- server/services/prismic-content.js
- server/views/components/article-body/article-body.njk
- server/views/components/soundcloud-embed/soundcloud-embed.njk
✨ Feature  
Enables the embedding of Soundcloud in articles
> Article Soundcloud embed

- content-model/articles.json
- server/services/prismic-content.js
- server/views/components/soundcloud-embed/soundcloud-embed.njk
✨ Feature  
Only outputs a minimal amount of SoundCloud chrome
> Build our own tiny iframes for SoundCloud

- infra/terraform/cloudfront/cloudfront.tf
- infra/terraform/prod/wellcomecollection.tf
✨ Feature  
Adds terraform for static cloudfront distribution and s3 bucket (applied successfully).
> Add static bucket/cloudfront distribution

- client/scss/utilities/_root-scope-classes.scss
Fixes some linting issues that fell through... sorry.
> Mobile events

- server/controllers/work.js
- server/views/pages/work.njk
Closes #1460
✨ Feature  
Allows users to to see more information about a work, or to request to view it in the library.
> Add catalogue link to work 

- content-model/articles.json
- content-model/series.json
- server/data/series.js
- server/services/prismic-content.js
- server/views/components/chapter-indicator/chapter-indicator.njk
- server/views/components/numbered-list/numbered-list.njk
✨ Feature  (in the loose sense)
Not sure about the modelling, as this was done a while ago - but it'll work for now.
> Editorial series schedule

- server/data/series.js
I wonder what the actual fix is to this?
Have an automatic commit of "linter autofixing"?
> add spacing fixed by lintre

- server/controllers/work.js
🐛 Bugfix  
prevent 500 when no description
> check for description

- .gitignore
- infra/terraform/prod/wellcomecollection.tf
- infra/terraform/templates/vpc.tf
- router/Dockerfile
- router/README.md
- router/docker-build.sh
- router/docker-push.sh
- router/nginx.conf
- router/terraform/alb.tf
- router/terraform/ami.tf
- router/terraform/asg.tf
- router/terraform/ecs.tf
- router/terraform/iam.tf
- router/terraform/iam_policy_document.tf
- router/terraform/locals.tf
- router/terraform/s3.tf
- router/terraform/services.tf
- router/terraform/terraform.tf
- router/terraform/topics.tf
- router/terraform/userdata.tf
- router/terraform/variables.tf
- router/terraform/vpc.tf
- server/data/series.js
This re-uses some modules from the `platform` repo to create a router service.
**TODO:**
- The nginx config is incorrect!
> Adds separate Router stack to firewall changes to top level nginx config

- client/js/components/async-content.js
🐛 Bugfix  
Makes sure the supporting images stick in the correct place.
Before:
After:
> Only shrinkStoriesNav if it's sticky

- server/views/components/book-promo/book-promo.njk
> Align more info icon with text

- server/views/pages/event.njk
🐛 Bugfix  
Consistency with the exhibitions:
> make event dates not bold

- .circleci/config.yml
- router/README.md
- router/nginx.conf
- router/terraform/services.tf
- router/terraform/variables.tf
Fixes/Closes/References #1616 
✨ Feature  
This will split basic traffic to the different parts of our apps (v1, v2).
> Router v1 v2 setup

- server/controllers/content.js
✨ Feature  
Editors can get to series pages without having to copy/paste things from URLs etc.
> add preview for series

- router/nginx.conf
🐛 Bugfix  
Add articles endpoint to v2.
> Articles endpoint in nginx

- server/controllers/content.js
- server/views/components/tags/tags.config.js
- server/views/components/tags/tags.njk
- server/views/pages/event.njk
- server/views/pages/exhibition.njk
🚑 Health
Makes things cosmetically more pleasing.
> Cosmetics to events / exhibitions

- content-model/events.json
- content-model/exhibitions.json
- server/content-model/event.js
- server/model/picture.js
- server/services/prismic-parsers.js
- server/views/pages/event.njk
✨ Feature  
Takes a lot of the work of creating strange aspect ratios for editors.
Let's keep it like this and see when they might have a need for overrides (which we do allow on Exhibitions).
> Events exhibitions responsive images

- content-model/events.json
- content-model/exhibitions.json
- server/services/prismic-parsers.js
> 32:15 is more descriptive than thinvideo

- server/data/series.js
🐛 Bugfix  
Dang it.
More complete fix is to not have this.
Coming soon.
> Use correct URL for digital story.

- server/views/components/footer/footer.njk
✨ Feature  
People will know we have an API, and hopefully use it.
> add developers link to the footer

- content-model/event-booking-enquiry-teams.json
- server/content-model/event.js
- server/controllers/content.js
- server/services/prismic-parsers.js
- server/services/prismic.js
- server/views/pages/event.njk
- server/views/pages/exhibition.njk
🐛 Bugfix  
Makes things look nicer, and brings in some relevant information.
> Cosmetics events exhibtions

- content-model/exhibitions.json
- server/services/prismic.js
- server/views/pages/exhibition.njk
🐛 Bugfix
Allows us to do what we once could do.
Apologies @davidpmccormick
> add gallery level back to the equation

- server/data/series.js
🚑 Health
Hardcodes the second part of the pharma series in.
> Add second part of pharma series to data

- server/data/series.js
🐛 Bugfix  
Use correct article/ID
> Correct article/ID

- cardigan/terraform/terraform.tf
- infra/terraform/cloudfront/cloudfront.tf
- infra/terraform/prod/wellcomecollection.tf
- shared-infra/terraform/https-s3-website/cloudfront.tf
- shared-infra/terraform/https-s3-website/s3-website-policy.json
- shared-infra/terraform/https-s3-website/s3.tf
- shared-infra/terraform/https-s3-website/variables.tf
🚑 Health
This will make it safer to deploy things.
@kenoir @alexwlchan any use for the `https_3s_website`?
> create https s3 module and apply it to cardigan

- server/data/series.js
> Add thumnail to poor child's nurse article

- server/views/pages/event.njk
- server/views/pages/exhibition.njk
🚑 Health
Rationalises type styles across events/exhibition fonts.
> Exhibition fonts

- client/package.json
- nginx-proxy/nginx.conf
- server/controllers/content.js
- server/routes/index.js
References #1693 
👋 Removal
All exhibitions will be published from Prismic and rendered through v2
Actions to merge:
* Report
* Setup drupal redirect.
> Remove graphicdesign v1/v2 test

- server/views/pages/event.njk
🐛 Bugfix  
Corrects font size.
> Match booking-info/time font size at medium breakpoint

- nginx-proxy/nginx.conf
- router/nginx.conf
- router/terraform/cloudfront.tf
Closes #1616
🚑 Health
After much mucking about - this configuration is simple, understandable, and most importantly, works.
I have run incremental tests by deploying certain routes and deploying those containers and testing.
All works well, and this infrastructure is already deployed.
> separate concerns of the app proyx and router once and for all

- nginx-proxy/nginx.conf
🚑 Health
Ran it through Google PageInsights and it suggested this.
We're using it in a few places, so could give us some nice earnings.
> gzip any JSON requests

- .gitignore
- cardigan/package-lock.json
- client/package-lock.json
- config/package-lock.json
- package-lock.json
- server/package-lock.json
🚑 Health
Just getting things into a proper shape.
For the package-lock files, we should commit these:
https://docs.npmjs.com/files/package-lock.json
I've also removed some things from the `.gitignore` which are user specific, you can exclude these from projects using your own global `.gitignore`. There's some more stuff in there (`logs`?) but not sure what it is.
https://help.github.com/articles/ignoring-files/
> add package lock and update gitignore to be project specific

- server/controllers/async-controllers.js
- server/model/article-stub.js
- server/model/article.js
- server/model/content-type.js
- server/services/prismic.js
- server/views/components/promo/promo.njk
✨ Feature
Allows series nav/transporter to be rendered dynamically from Prismic content (editorial series)
Looks the same
> Async series nav

- server/views/pages/event.njk
🚑 Health
Realised the button only is a boundary to entry.
This feels nicer.
> add email address to event page

- content-model/events.json
- content-model/exhibitions.json
- server/content-model/event.js
- server/content-model/exhibition.js
- server/views/pages/event.njk
- server/views/pages/exhibition.njk
✨ Feature  
Adding subtitle (required for exhibitions).
This is step 1, we will then remove subtitle from the description block once the data has been moved over.
> Intro/subtitle to the model: Part 1

- content-model/events.json
- content-model/exhibitions.json
- server/content-model/event.js
- server/content-model/exhibition.js
- server/views/pages/event.njk
- server/views/pages/exhibition.njk
References #1723 
✨ Feature  
Once the data has been ported, we can deploy this to update things to The Way They Should Be ™️ .
> Subtitle / intro part 2

- router/README.md
- router/nginx.conf
- router/terraform/cloudfront.tf
- server/controllers/content.js
- server/routes/index.js
References #1624 
📋 Test
We can measure that what we're planning on releasing is at least as good as the current pages.
This is not a test of our actual event pages, which we know we'd like to improve, but rather a confidence to move over to v2.
## Before merge
> Events A/B

- server/services/prismic-parsers.js
- server/views/pages/exhibition.njk
🐛 Bugfix  
Slipped through the cracks.
> Fix intro copy on events and exhibitions

- server/controllers/content.js
- server/data/series.js
- server/services/prismic-parsers.js
🚑 Health
Gets article position in series data from Prismic, so we don't need to hard code this any longer
> Get series poisition from prismic data

- server/routes/index.js
🐛 Bugfix  
As per the docs, I forgot to attach which version this is:
https://developers.google.com/analytics/solutions/experiments-server-side
> add version to optimize test ID

- router/nginx.conf
- server/routes/index.js
🐛 Bugfix  
Removing the event as it's ticketed, which we don't support as yet.
> remove ticketed event from test

- server/services/prismic.js
Not sure how we might have a better test.
@gestchild @davidpmccormick did we explain the logic to the editorial team?
i.e. The articles override the schedule?
Thanks @davidpmccormick fir spotting where the bug is
> lowercase on digital story schedule deduping

- .circleci/config.yml
🚑 Health
In place or #1728 as it doesn't include linting.
> add new circle workflows

- server/controllers/work.js
From the flow type conversion.
> dont try ot convert null to Number

- server/controllers/work.js
Fixes #1739 
I wondered about this... all done.
> Remove superfluous prefix in work titles

- server/services/prismic-parsers.js
Updating Types for Flow.
Makes things a bit more clear I think.
Also - sorry for merging a broken branch into master...
> update flow for tasl

- server/controllers/work.js
References wellcometrust/platform/issues/1131
Not sure if this is what we shoudl expect (optional titles), but we have to for now as it's better than 500.
> sometimes we won't have a title fr works

- infra/README.md
🚑 Health
Making README accurate
> Don’t need to specify prod

- client/js/app.js
- client/js/components/image-viewer.js
- client/js/tracking.js
- client/js/util.js
- client/scss/components/_back-to-top.scss
- client/scss/components/_buttons.scss
- client/scss/components/_captioned_image.scss
- client/scss/components/_image_viewer.scss
- client/scss/components/_scroll_to_info.scss
- client/scss/components/_slider__in-content.scss
- client/scss/components/_slider__numbered-list.scss
- client/scss/components/_work_media.scss
- client/scss/critical.scss
- client/scss/non-critical.scss
- server/views/components/image-viewer/image-viewer.njk
- server/views/components/scroll-to-info/scroll-to-info.njk
- server/views/components/work-media/work-media.njk
- server/views/pages/work.njk
> Zoom tweaks

- server/views/pages/search.njk
> Use fewer font sizes on /works

- cardigan/package-lock.json
- cardigan/package.json
🚑 Health
I was going to do the rest - but I want to get Greenkeeper working.
> general housekeeping on cardigan

- server/util/json-ld.js
Closes #440 
🚑 Health
Last bit to be added to the event LD
> add image to JSONLD for event

- server/app.js
🐛 Bugfix  
I wondered where the errors had gone to.
> pluralise beaconError

- server/pm2.yml
Reading through the PM2 docs, this is what we should be doing (at the moment we are running the task on 1 core, when we have 2).
http://pm2.keymetrics.io/docs/usage/cluster-mode/
> when using PM2 use cluster mode

- .circleci/config.yml
- Dockerfile
❓ Test
If this proves to give us some useful metrics, I'll go about putting the vars in more securely.
> add kissmetrics vars

- client/.babelrc
- client/package-lock.json
- client/package.json
FIxes #738
🚑 Health
Once the file is compiled, it's exactly the same, I compared the hashed values of the files.
> use babel env

- .circleci/config.yml
- Dockerfile
Reverts wellcometrust/wellcomecollection.org#1776
> Revert "add ~kiss~keymetrics vars"

- client/js/components/info-banner.js
- router/nginx.conf
- server/views/pages/search.njk
References #1304
✨ Feature 
Allows us to point wellcomeimages.org URLs to appropriate equivalents at /works
> Images redirect

- router/nginx.conf
> Listen on port 443

- server/services/instagram.js
- server/services/twitter.js
- server/services/wellcomecollection-api.js
Came about when thinking of what we might do to find the bottleneck in the app.
We have a strategy for for async content, we might as well stick to one.
> remove the use of then when we have await

- router/nginx.conf
🚑 Health
Allowing us to test things with router.wellcomeimages.org
> add router.wellcomeimages.org back for testing

- router/terraform/alb.tf
Using a cert that covers wellcomecollection.org, wellcomeimages.org, and wellcomelibrary.org
> use cert that covers all bases

- infra/terraform/prod/wellcomecollection.tf
- infra/terraform/templates/vars.tf
Using the mega cert for the WC ALB.
#1798
> use mega cert on w infra

- server/middleware/error.js
This should hopefully allow us to filter errors more easily.
> Status code to setry

- server/routes/index.js
Noticed the download image route wasn't async.
Now it is.
> make download route async

- router/nginx.conf
We need to redirect html and htm files
> redirect htm files to new works from wi.org

- router/terraform/cloudfront.tf
It's in the args, not the cookies... Silly me.
> Miro args, not cookies

- infra/deploy.py
A little more clarity into what you're deploying (not too pretty though):
> add commit message to the deploy script

- router/nginx.conf
- server/routes/index.js
There is no conclusive results.
We are going to regroup and come up with another plan for releasing events.
> remove events a/b test

- content-model/events.json
- server/content-model/event.js
- server/services/prismic-parsers.js
- server/util/json-ld.js
- server/views/pages/event.njk
Moving event dates to use groups, and it turns out Slices aren't query-able....
That's going to give us something to think about where we've used them.
> use groups for event dates

- content-model/exhibitions.json
- server/content-model/exhibition.js
- server/services/prismic-body-parser.js
- server/services/prismic-parsers.js
- server/views/components/iframed-video/iframed-video.njk
- server/views/pages/exhibition.njk
Fixes/Closes/References #1813 
Adds the video to the exhibition.
It really feels as though we should reuse the body for this, especially as we know image galleries etc are coming up too.
> add a body to exhibitions that can contain video

- client/scss/components/_work_media.scss
- server/content-model/exhibition.js
- server/services/prismic-body-parser.js
- server/services/prismic-parsers.js
- server/views/pages/exhibition.njk
We removed the idea of featured video, as it doesn't really work with the rest of our model.
I forgot to update the template / parsers.
> remove featured body from exhibition

- content-model/articles.json
- server/services/prismic-parsers.js
✨ Feature  
Allows articles from Prismic to have video as featuredMedia
This will do the job until we pull featuredMedia out as it's own thing
> Featured video

- server/views/pages/exhibition.njk
First bit of making sure we label the video / image gallery as featured media.
> add Exhibition highlights for image galleries or videos

- server/views/partials/analytics.njk
Series has been surfaced as something we report on from @hthair
> add series to G2 tracker

- server/controllers/content.js
Realised we were getting a 500 where we should have got a 404.
> only check for page tracking info if we have an article

- server/views/pages/exhibition.njk
> reinstante download on exhibition

- server/services/prismic-body-parser.js
- server/views/components/iframed-video/iframed-video.njk
Let's not show unrelated related videos.
> add rel=0 to youtube video embeds

- server/controllers/async-controllers.js
- server/views/pages/work.njk
🐛 Bugfix  
Displays the full URL for copying on the work pages
> Work share link

- content-model/series.json
> fix series model

- exhibitions/app/views/exhibition.njk
- server/filters/format-date.js
- server/filters/index.js
- server/views/pages/exhibition.njk
Closes #1722
🚑 Health
Updates messaging around exhibition status (based on time).
> Exhibition status

- server/views/layout/default.njk
> fixed path to non-critical.css inside noscript

- .circleci/config.yml
- build_prod_config.py
- exhibitions/app/build_prod_config.py
We need to bake the prod_config into all services.
I've done it via crappy copy / paste - we should try abstract it out.
> Rely on client

- node-docker/Dockerfile
Install everything in one step
> install docker via other means

- .circleci/config.yml
- node-docker/Dockerfile
Seems I can't get Docker installed in a way that circle will run it.
Back to the old way so I can start doing some other work,
> be boring and add docker manually

- .circleci/config.yml
As it doesn't seem to be running on circle either.
:rage4:
> revert back to manual docker-compose install

- server/model/pagination.js
> urlEncode on pagination

- build/Dockerfile_nginx
- build/events_webapp.yml
- events/terraform/services.tf
- events/terraform/variables.tf
- exhibitions/terraform/services.tf
Did the maths properly this time.
Needs double the resources of a service to start - so this is that.
> sort service resources to be able to deploy

- build/exhibitions_webapp.yml
- build/nginx.conf
Make the proxypass in the nginx container dynamic.
And remember to send it over from the exhibitions service.
> add webapp_port to docker nginx container

- server/index.js
> removed duplicate export

- events/app/views/pages/event.njk
Just holding info for now.
Waiting on copy.
> Holding information for ad tour

- server/views/components/drawer/drawer.njk
Adds the label id/section to tracked drawer clicks.
> Fix typos in and around tracking data-attributes

- exhibitions/app/views/pages/exhibition.njk
🐛 Bugfix  
Missed updating some icon paths, which is causing 500 on exhibition page
> Corrected file paths

- server/services/prismic-parsers.js
Make the logic the right logic
> better check on whether HTML is empty

- server/views/docs/index.njk
Adding notes on adding notes to component.
> add notes on how to add notes to cardigan

- client/js/components/async-content.js
> Remove async-content placeholder and query the correct element

- server/utils/json-ld.js
- server/views/pages/list.njk
Fixes #1878
Adds JSON-LD for the article list page. Checked with Google's structured data testing tool.
> Add json-ld to article list page

- exhibitions/app/views/pages/exhibition.njk
- server/views/components/footer/footer.njk
Adds missing word, 'December' to the festive opening hours.
> Add 'December'

- devappy/Dockerfile
- devappy/README.md
- devappy/docker-compose.yml
- devappy/nginx.conf
A simple docker container that runs as a proxy to all of your apps.
> add devapp to run all apps at once

- server/services/prismic.js
Reference #1934 
Use the promo parser as we have it.
> use promo parser for event promos

- server/services/prismic.js
> add order to exhibitions list

- events/app/views/pages/events.njk
- exhibitions/app/views/pages/exhibitions.njk
I've left the articles one, as who knows what that should say.
> fix past events / exhibitions list link

- server/views/components/list-header/list-header.njk
* Remove item count
* Tidy spacing classes
> remove item count from list heading

- eventbrite/terraform/service.tf
Perhaps having something in the `/service_name/config` with:
```
port=3004
```
That's read everywhere might help...
> update eventbrite container port

- client/js/app.js
- client/js/components/focus-trap.js
- client/js/components/header/burger.js
- client/js/components/segmented-control.js
- client/js/components/show-hide.js
- client/js/util.js
- client/scss/base/_layout.scss
- client/scss/components/_header.scss
- client/scss/components/_segmented_control.scss
- client/scss/critical.scss
- client/scss/utilities/_root-scope-classes.scss
- client/scss/utilities/_variables.scss
- server/views/components/header-search/header-search.njk
- server/views/components/header/header.njk
- server/views/components/list-header/list-header.njk
- whats-on/app/views/components/segmented-control/segmented-control.njk
- whats-on/app/views/components/whats-on-list-header/whats-on-list-header.njk
- whats-on/app/views/pages/whats-on.njk
WIP for merging this back into @gestchild 's whats-on branch
> Segmented control

- infra/terraform/templates/alb.tf
> Add matcher to health_check block

- exhibitions/app/controllers.js
> change exhibitions tag link to /exhibitions

- server/filters/get-icon-for-content-type.js
Icons aren't nested in directories any more. This was breaking the server.
> Use correct icon path

- router/nginx.conf
References #1897
Re-route `/exhibitions` to V2.
> Test for exhibitions/ and exhibitions/W

- client/scss/components/_exhibition_promo.scss
- exhibitions/app/views/components/exhibition-promo/exhibition-promo.njk
Spacing amends for the exhibition promo.
> Do Tomi tweaks

- router/nginx.conf
Redirects `/whats-on/exhibitions/all-exhibitions` to (V2) `/exhibitions`
> Redirect to /exhibitions from /whats-on/exhibitions/all-exhibitions

- router/nginx.conf
> Add progress route to router

- server/views/pages/progress.njk
> Limit width of progress page content

- exhibitions/app/views/pages/exhibition.njk
- server/views/components/footer/footer.njk
- server/views/layout/default.njk
- server/views/pages/search.njk
- server/views/pages/work.njk
> Remove seasonal banner

- client/scss/components/_daily_promo.scss
- server/data/daily-promos.js
- server/views/components/daily-promo/daily-promo.njk
- whats-on/app/controllers.js
- whats-on/app/views/components/whats-on-list-header/whats-on-list-header.njk
- whats-on/app/views/pages/whats-on.njk
- Simplifies `daily-promo`
- Adds SPIRIT booth promo
- Adds today's opening hours to header area
> Dmc whats on

- prismic-model/articles.json
- server/views/components/article-body/article-body.njk
Image list descriptions should be allowed to be multi line
> make image list descrpition multiline

- prismic-model/articles.json
Do it to the image description.
> make image description multiline on image lists

- client/gulpfile.js
- client/scss/grids/_css_grid.scss
- events/app/views/pages/event.njk
- server/browserstack/test-browsers.json
- server/ui-config/grid-config.js
References #1790
✨ Feature  
Uses CSS grids to layout template
> Event desktop layout

- events/app/views/pages/event.njk
Decoupling access options and event format as discussed.
> show event format description and access options

- events/app/controllers.js
- exhibitions/app/controllers.js
Typo that I spotted from #1993
> publicprograms VS public-programme

- infra/terraform/prod/wellcomecollection.tf
- preview/terraform/cloudfront.tf
- preview/terraform/locals.tf
- preview/terraform/terraform.tf
Adds a cache, that effectively doens't cache, as a layer of protection in front of our origin.
It's worth the $0.085 it'll cost a month.
> add preview service cache

- server/views/layout/default.njk
> Apple icon to use hashedFile filter

- client/js/app.js
- client/js/components/focus-trap.js
- client/js/components/header/burger.js
- client/js/components/segmented-control.js
- client/js/components/tabs.js
- client/js/polyfills.js
- client/js/util.js
- client/libs/ga-scroll-depth.js
- devappy/nginx.conf
- router/terraform/cloudfront.tf
- server/data/facility-promos.js
- server/model/content-type.js
- server/utils/json-ld.js
Splitting #1993 into more manageable chunks (will ultimately need all merged into master together, in order not to break anything. Once each PR is individual approved I'll merge them back down the chain)
> mostly js ui, plus a few random tweaks

- client/js/components/gif-video.js
- client/scss/components/_gif_video.scss
- client/scss/critical.scss
- client/scss/non-critical.scss
- server/views/components/gif-video/gif-video.njk
> Gif video fixes

- client/js/components/gif-video.js
- client/scss/components/_gif_video.scss
- prismic-model/articles.json
- server/filters/prismic.js
- server/model/license.js
- server/services/prismic-body-parser.js
- server/services/prismic-parsers.js
- server/views/components/captioned-image/captioned-image.njk
- server/views/components/gif-video/gif-video.njk
- server/views/components/tasl/tasl.njk
Removes the need for a poster image (redundant now we're autoplaying videos as soon as there's _any_ of it on-screen) making the editor flow much less fiddly.
> Gif video poster

- server/services/prismic-parsers.js
- server/services/prismic.js
There's a couple of discrepancies between article series and webcomic series (although webcomics and event share the same, we've learn from our (my) mistakes).
This accounts for them
> fetch webcomics correctly

- server/views/components/gif-video/gif-video.njk
> Align caption correctly

- client/scss/components/_tabs.scss
- client/scss/grids/_css_grid.scss
- client/scss/utilities/_mixins.scss
✨ Feature  
Uses flexbox as a fallback for browsers that don't support css grids
> Grids flex fallback

- nodemon.json
- server/nodemon.json
- server/package.json
References #2033 
Adds watch for service apps and `/server`.
> add /common to app and server app:dev

- client/scss/components/_buttons.scss
- events/app/controllers.js
- events/app/views/pages/event.njk
> responsive event heading and tags

- router/nginx.conf
> add webcomics and webcomic-series to router

- client/js/components/gif-video.js
- prismic-model/articles.json
- server/services/prismic-body-parser.js
- server/views/components/gif-video/gif-video.njk
- server/views/components/jsx-test-component/jsx-test-component.js
Lets editors alter the playback rate of gif-videos (between 0.1x and 2x original speed).
> Video playback rate

- client/scss/grids/_grid_scroll.scss
as requested by Heesoo
Fixes/Closes/References 
🚑 Health
> Changed min-width of scrolled promo items

- client/scss/grids/_css_grid.scss
- client/scss/utilities/_root-scope-classes.scss
- events/app/views/pages/events.njk
- exhibitions/app/views/pages/exhibitions.njk
- server/views/components/event-promo/event-promo.njk
- server/views/components/exhibition-promo/exhibition-promo.njk
- whats_on/app/views/partials/mixed_exhibition_event_promos.njk
- whats_on/app/views/partials/separate_exhibition_event_promos.njk
🚑 Health
Better layout for browsers that don't support grids
> Whats on layout fallback

- server/content-model/events.js
- server/filters/index.js
- server/services/prismic.js
- server/views/components/event-promo/event-promo.njk
A few things needed updating on the event promo to correlate with the event model.
> get event promo up to date with new model

- events/app/controllers.js
- events/app/views/pages/event.njk
- server/services/prismic-parsers.js
- server/services/prismic.js
* Put back in the booking enquiry team info
* Change the language around primary interpretations
> slightly tighter language around primary interpretations

- .circleci/config.yml
Builds are breaking, this should help.
> make common modules a dep in cardy build

- server/services/prismic-parsers.js
> Stop parsing HTML text twice

- events/app/views/pages/event.njk
Take 2 of add to calendar test
> add to calendar, take 2

- server/data/facility-promos.js
> add photos to cafe, restaurant, and bookshop

- events/app/views/pages/event.njk
Hangover from somewhere.
Fixes #2069
> remove unnecessary font size setting on events

- server/controllers/content.js
- server/services/prismic.js
> Fixed comic series pagination

- server/content-model/events.js
- server/data/facility-promos.js
Typing didn't catch it...
Works now though
> add format properly to events

- server/views/layout/default.njk
Makes it easier to navigate to via preview, seen a few people having to manually mess with the link, which is slow
> make nav lin kto whats on relative

- server/controllers/content.js
- server/services/prismic.js
Use a universal size across the site.
It's arbitrary, but universal.
> use default page size for series

- package.json
- yarn.lock
Already better, as I changed the package and yarn file and no linting happened.
Taken from [`prettier`](https://prettier.io/docs/en/precommit.html).
> use lint-staged for linting

- build/nginx.conf
If a user isn't in a cohort, assign them to A/B/nothing.
I'd like to see if we can use this in conjunction with #2110 for a/B testing.
> create user cohorts for them

- .circleci/config.yml
- .eslintignore
- .flowconfig
- common/utils/format-date.js
- common/views/components/Buttons/ButtonButton/ButtonButton.js
- common/views/components/Icon/Icon.js
- common/views/components/Image/Image.js
- common/views/components/PageDescription/PageDescription.js
- common/views/components/WorkMedia/WorkMedia.js
- common/views/global/palette/palette.js
- eventbrite/app/controllers.js
- exhibitions/app/controllers.js
- flow-typed/npm/moment_v2.x.x.js
- flow-typed/react-stub.js
- package.json
- yarn.lock
Adding a global flow to watch the good work going on with the JSX converting.
Now to start on this:
> global flow!

- prismic-model/series.json
- prismic-model/teams.json
> update model name in prismic models

- common/views/components/DefaultPageLayout/DefaultPageLayout.js
Adding analytics to the head of the doc.
Couple of TODOs but thought this will do and wanted to see if `next5` blows everything or works before continuing as we can then use `Fragment`s.
> add analytics to next app

- common/views/components/CopyUrl/CopyUrl.js
- common/views/components/HTMLInput/HTMLInput.js
A few flow bits that slipped through the cracks.
@gestchild @davidpmccormick we could stop merging on tests failing while we get used to flow, or happy to just keep sliding with it?
> make flow go

- cardy/docs/principles.jsx
- common/views/components/CopyUrl/CopyUrl.js
- common/views/components/Header/Header.js
- common/views/components/Icon/Icon.js
- common/views/components/MoreInfoLink/MoreInfoLink.js
- common/views/components/PageDescription/PageDescription.js
- common/views/components/ScrollToInfo/ScrollToInfo.js
- common/views/components/WorkMedia/WorkMedia.js
Make Icon extraClasses prop a string
> extraClasses from array to string

- server/views/pages/article.njk
The sticky nav isn't sticking. This makes it stick once more!
> Re-stick sticky nav

- build/nginx.conf
Sets the cookie so we can start seeing it propagate in GA.
> set the cohort testing cookie

- whats_on/app/views/pages/whats-on.njk
It'd be good to find a way to open this up to King Kontent changing it.
Fixes #1796
> add meta description to whats on

- server/data/facility-promos.js
- whats_on/app/controllers.js
- whats_on/app/views/pages/whats-on.njk
> Text changes to what’s on promos

- server/services/prismic.js
- whats_on/app/views/partials/date_range.njk
Fixes #2137
✨ Feature  
Everything view shows everything we have coming up, not just the next few months
@Heesoomoon The month controls in the events section can show non consecutive months (see screenshot). Shall we discuss if this is ok and, if not, what we could do about it when you have a moment?
> Whats on final qa

- server/services/prismic-body-parser.js
- server/services/prismic-parsers.js
- server/views/pages/article.njk
References #2129
Just a quick WIP to see if we can get image lists into a nice flashy state.
Questions:
* Restrict to viewport height?
* What about other media, should we be building media galleries?
Any other questions below please!
> beta featured image gallery

- server/services/prismic.js
- whats_on/app/views/partials/mixed_exhibition_event_promos.njk
- whats_on/app/views/partials/separate_exhibition_event_promos.njk
> Whats on exhibitions ordering

- prismic-model/events.json
To see if, when content editors start using it Friday, it makes a difference.
I'm sure there'll be more changes, but would rather get the feedback from the sessions.
> being more descriptive in our event model

- server/data/facility-promos.js
- whats_on/app/views/partials/mixed_exhibition_event_promos.njk
Fixes #2139
Text change and only shows daily tour promo on day view if the galleries aren't closed
> Daily tour promo

- server/views/components/search-box/search-box.njk
- server/views/components/tags/tags.njk
An `elf-green` slipped through the net in the markup for the tags. It should just be `green`.
> Kill rogue elf

- whats_on/app/views/partials/date_range.njk
> Closed statement should only appear on today view

- common/views/components/CopyUrl/CopyUrl.js
- common/views/components/HTMLInput/HTMLInput.js
- server/filters/get-license-info.js
Syncing with the API.
Picked up from the Athena / Cloudwatch logs.
> Right license type

- common/views/components/MetaUnit/MetaUnit.js
- common/views/components/MoreInfoLink/MoreInfoLink.js
- common/views/components/WorkMedia/WorkMedia.js
- eventbrite/app/views/components/eventbrite-button/eventbrite-ticket-status.njk
- exhibitions/app/views/pages/exhibition.njk
- server/views/components/book-promo/book-promo.njk
- server/views/components/meta-unit/meta-unit.njk
- server/views/components/work-media/work-media.njk
- server/views/pages/work.njk
Update `icon--` colour names in line with palette.
> Update missing colours

- client/scss/components/_exhibition_hero.scss
- client/scss/components/_tags.scss
- client/scss/components/_tasl.scss
- server/views/components/picture/picture.njk
> Prevent hero content appearing behind image

- events/app/views/pages/event.njk
> Removed ‘what to expect’ header from event page

- server/views/components/book-promo/book-promo.njk
- server/views/components/event-promo/event-promo.njk
- server/views/components/exhibition-promo/exhibition-promo.njk
- server/views/components/facility-promo/facility-promo.njk
- server/views/components/promo/promo.njk
Make sure we're tagging up the relevant component.
This may allow us to start A/B testing.
Almost felt like it was a good place to convert them to JSX until I saw `promo.njk`.
> Tag-up promos

- events/app/views/pages/event.njk
- prismic-model/interpretation-types.json
- server/content-model/events.js
- server/services/prismic-parsers.js
- server/services/prismic.js
Just some tidying up around the reservation messaging.
* Bug fix around reservation (ticketed etc) messaging not showing up.
* Allows for primary vs not primary interpretation messaging
* Layout standardising
> Events reservation text

- server/filters/format-date.js
_Should_ get remaining missing colours updated (relates to #1950).
> Fix (hopefully) remaining colour name issues

- .circleci/config.yml
- build_and_deploy_cardigan.sh
- cardy/build-cardigan.js
- cardy/package.json
Swapping over to the new cardy.
Next to remove our old cardigan.
> start building and deploying new JSXy cardigan

- server/views/components/chapter-indicator/chapter-indicator.njk
> Remove -graphics suffix

- catalogue/webapp/pages/work.js
- common/utils/convert-image-uri.js
- common/utils/striptags.js
- common/views/components/DefaultPageLayout/DefaultPageLayout.js
- common/views/components/WorkMedia/WorkMedia.js
Get's the TwitterCard and OpenGraph data working.
Next up I'll deprecate the old nunjucks ones along with the analytics, let's make sure we're happy with this first.
> Social graph Next

- client/scss/utilities/_root-scope-classes.scss
- server/controllers/async-controllers.js
- server/model/numbered-list.js
- server/views/components/numbered-list/numbered-list.njk
Looks the same, just the headers are links.
Just makes it easier for the editors to get to it as well.
> add the series URL to series lists

- prismic-model/events.json
- prismic-model/places.json
- server/content-model/events.js
- server/services/prismic-parsers.js
- server/services/prismic.js
As per @silveroliver's suggestion, they use `Location` with a very different meaning, so we're calling this place, which sounds more friendly I think.
It'd be good to get this in before the session this afternoon.
> use place over location property for events

- catalogue/webapp/pages/work.js
- server/views/pages/work.njk
> label change Download original => Download full size

- events/app/views/pages/events.njk
> Added meta description and summary text to events listing

- server/services/prismic-parsers.js
Events listing and What's On are giving 500 errors, this fixes them
> Update location property to place to match model

- prismic-model/events.json
- prismic-model/organisations.json
- server/services/prismic-parsers.js
- server/services/prismic.js
Starting to add organisations as contributors.
I've moved away from the old contributor structure as I can just see it being a massive hassle in the future, especially with different contributors types (person / org etc).
TODO:
> Orgs as contributors
