wellcomecollection/wellcomecollection.org

.stylelintrc, client/.stylelintrc
This adds a symlink from the root of the repo to the .stylelintrc in the client directory so that IDEs can pick up on it from the root
=> Add symlink to .stylelintrc

infra/.gitignore, infra/README.md, infra/TODO.md, infra/airbag.sh, infra/packer/node6.json, infra/terraform/launch-script.tpl, infra/terraform/templates/elb.tf, infra/terraform/templates/iam.tf, infra/terraform/templates/launch.tf, infra/terraform/templates/provider.tf, infra/terraform/templates/sg.tf, infra/terraform/templates/state.tf, infra/terraform/templates/vars.tf, infra/terraform/templates/vpc.tf, infra/terraform/wellcomecollection.tf
Adding the deploy infra to wellcomecollections.org.
We can now deploy artifacts created by circle.
The instructions are in the [README](https://github.com/wellcometrust/wellcomecollection.org/blob/3a35283f7e27df3011d2940418530f5e1d60ff63/infra/README.md).
There is still a bit [to do](https://github.com/wellcometrust/wellcomecollection.org/blob/3a35283f7e27df3011d2940418530f5e1d60ff63/infra/TODO.md) (not an exhaustive list) - but for now we have a ELB with content serving, so great.
=> add deploy infra

client/js/styleguide/palette.js, client/scss/styleguide/_styleguide.scss
Fixes the result of a heavy handed find-and-replace colour -> color
=> Use British 'colour' spelling for class name

infra/terraform/wellcomecollection.tf
We don't actually support depoying other branches yet, so this just stops potentially faulty deploys.
=> only deploy master

build.sh, client/gulpfile.js, client/package.json
Having the `lint`ing running on `watch` was riving me insane as I write a lot of pseudo code etc.
If you'd like lint, we could add a `npm run dev:linted` as this is modular enough to do that.
=> Modularise gulp

server/package.json
We can come up with a logic for what is on what port.
For now, I don't install global npm modules, so this is better than "./node_modules/.bin/fractal".
=> add fractal run script

client/gulpfile.js
Points the SVG creation gulp task to the correct directory (now `_partials`, previously just `partials`).
=> Update partials path for SVG sprite generation

server/filters/index.js, server/model/article.js, server/views/article/index.njk
We can show the video now.
It also makes sure that we don't show the image with the video, as that's completely overkill (although we could probably use the image as a fallback).
=> add video to article

infra/terraform/container-definitions.json
This is not the long term solution - adding machines with more cores is (1024CPU units / core).
=> use less than all the CPU units

infra/terraform/container-definitions.json
Again, the solution is to get beefier machines, but this will do for now.
=> don't use all the memory

infra/terraform/templates/ecs.tf, infra/terraform/templates/iam.tf, infra/terraform/templates/launch.tf, infra/terraform/wellcomecollection.tf
This allows us to have 3 tasks running to be able to start the new ones up.
=> Allow ECS to go 200 over capacity

server/fractal-app.js
As fractal doesn't let you pass it or exposes it's nunjucks `env` - we just create a new one, and pass it to the component.
It does mean we have two environments - but it doesn't really matter.
=> pass env to component

infra/TODO.md, infra/app.js, infra/console.js, infra/deploy.js, infra/terraform/container-definitions.json, infra/terraform/templates/alb.tf, infra/terraform/templates/launch.tf, infra/terraform/templates/sg.tf
We now allow for dynamic `hostPorts` on the container hosts. 
This moves deployment from 10+ minutes to about 1 minute.
Before we were having to drain one task, which seems to take ages, restart it, and then do that again for each host as having a hard-coded port means you can only run that service once on the host.
🚤 🐎
=> Ecs allow dynamic ports

client/scss/components/_blockquote.scss, client/scss/utilities/_functions.scss
I hadn't realised that the grey borders around the blockquotes in the C&T styleguide were part of the blockquote design. Spotted them in the article page design and added them here.
Also updated the quote colour from green to turquoise after colour picking (not much difference to my colour-blind eyes).
=> Use correct (turquoise)  quote colour; add grey borders

server/views/components/font-example/index.njk
The data for the font-example component didn't exist (presumably after a refactor). Removed the `font.` prefix to make it work again.
=> Unbreak font component

client/scss/application.scss, client/scss/components/_body_content.scss, server/views/components/body-content/index.config.json, server/views/components/body-content/index.njk
Adding some `h2`, `ul`, `a` and `::selection` styles for content contained within a `class="body-content"` block. This should allow styling of e.g. article content elements without requiring us to class every element during parsing.
The styles I've added so far are based on type styles from the visual designs, but I imagine there will likely be other elements that we want to have default styling.
Do we think e.g. `table`s should belong in here, or would we specifically add classes to them during the parsing stage? Any other obvious omissions.
=> Add body-content type styles

client/scss/application.scss, client/scss/base/_row.scss, client/scss/grids/_grid_alignment.scss, server/views/grid/aligning/README.md, server/views/grid/aligning/aligning.njk
1. The designs call for full-bleed background colours (e.g. cream on the article pages). The `row` class added here is designed to wrap an e.g. `container` to add background to the whole page around that container.
2. The `grid--spaced` class added here adds `justify-content: space-between` to `grid__cell`s to distribute them evenly on the line. This is useful for when there are two `grid__cell`s on a row that have one or more empty columns between them.
=> Add row background colour option and spaced grids

client/scss/utilities/_mixins.scss, server/views/article/index.njk, server/views/grid/aligning/README.md, server/views/grid/aligning/aligning.njk
Grid containers in the visual designs can be shifted over to enable the creation of empty columns. This allows for any number of empty columns to be created at each breakpoint.
Before (no shift in copy):
After (copy shifted one-column to the right):
=> Grid shift

server/views/article/index.njk, server/views/components/figure/index.njk, server/views/components/icon/index.njk
The caption content within the e.g. hero image should align with any content that follows it.
Because it lives in a separate grid, it needs the option to accept grid size/shift classes.
Before:
After:
=> Allow for alignment of figcaption content

client/gulpfile.js, client/package.json
Browsersync wasn't actually being used for what it was put in for since the move to Fractal.
=> Removed browsersync from client

client/scss/base/_row.scss, server/views/components/header/index.njk
Unwanted [collapsing margins](http://reference.sitepoint.com/css/collapsingmargins) are causing the lead row to overlap the nav. This PR ensures the rows are flush.
Before (grey 'starter block' line overlapping nav):
After:
=> Prevent margin collapse on row--lead

client/scss/components/_blockquote.scss, server/views/components/blockquote/index.config.json, server/views/components/blockquote/index.njk
In a design review, we agreed to remove the big quote marks from the monospace `blockquote` variant. This PR adds a `--with-marks` modifier to the blockquote component to enable this. #122
Before:
After:
=> Make with-marks modifier

server/views/components/figure/index.njk
The figure caption will become misaligned with body content at wider screen widths, because the negative left margin applied to the `grid` class overrides the `margin: 0 auto;` of the `container` class.
Nesting the `grid` within the `container` solves this. 
Before:
After:
=> Nest 'grid' instead of applying to 'container'

server/views/components/figure/index.njk
Fixing the border-bottom of the figure so that it isn't shifted over to the left (as a result of negative margin on the `grid`). Done by nesting the `figure__caption` element within the `grid__cell`.
Before (underline shunted over to the left):
After:
=> Nest figcaption within grid__cell to correct underline

client/.stylelintrc, client/scss/components/_header.scss, server/views/layout/default.njk, server/views/layout/preview-no-container.njk, server/views/layout/preview.njk, server/views/partials/js-head.njk
- Help us to ensure we provide a functional experience if javascript fails to load or is unavailable.
- Help us to ensure we provide a functional experience to users of older browsers.
- Only loading the app.js and fonts in browsers deemed capable.
- Applying a class to the html element when the app.js has successfully loaded, which can then be utilised in the CSS to apply 'enhanced' styles.
Previously if  javascript was unavailable functionality such as the navigation was hidden behind a non functional button
Now it is visible
Previously the app.js and fonts were being called by all browsers, regardless of their capabilities, now this only happens if they are deemed capable. The cut off at the moment is Internet Explorer < 10 and Android browsers based on WebKit.
=> Cutting the mustard

server/routes/index.js
As URIs on the site now include `articles` - we don't have to fudge it here.
e.g. https://wellcomecollection.org/api/v0/articles/aids-posters
=> update API uri

client/scss/components/_header.scss
Stopping the search box from overlapping the Wellcome logo with the addition of `max-width`
Before:
After:
Additionally, I had to bump a couple of z-index values because the work to cover the new-site banner meant the navigation was no longer being covered by the search input when opened.
=> Prevent search box from over-stretching

server/views/global/palette.config.yml
Adding 'charcoal' (#323232) the the palette config so the Cardigan palette is in sync with the Sass variables.
=> Add charcoal to palette config

client/scss/components/_header.scss
Getting rid of excess padding that was causing the nav to break when squished in the 'desktop' configuration.
Before:
After:
=> Remove excess padding when nav is 'desktop'

client/js/components/header/search.js, client/scss/components/_header.scss, server/views/components/header/index.njk
Enabling close of the search input either by clicking the (added) cross, or by clicking anywhere on the page that isn't the search form. Fixes #157.
=> Add close search functionality

client/js/app.js, client/js/components/wobbly-edge.js, client/js/util.js, client/scss/application.scss, client/scss/components/_wobbly_edge.scss, server/views/components/wobbly-edge/index.config.yml, server/views/components/wobbly-edge/index.njk, server/views/layout/default.njk, server/views/partials/html_top.njk
Adding a 'wobbly edge' component (created to 'breathe a bit
of life and irregularity into the design'). The background colour, max-intensity (how high the peaks can grow) and number of points can be passed in as data-attributes. Animation between (randomised) points is triggered on/off scroll
(jsbin demo: http://output.jsbin.com/hujeboc/3)
=> Wobbly edge

infra/deploy.sh, infra/setup.sh, infra/terraform/templates/cloudfront.tf
Making deploys more reliable.
If the remote state and your state aren't configured there is a risk of killing the entire stack.
This is not good.
But this is the danger of using our stack deployment to do app deployment.
What might be nice is to have your stack deployed, and somehow only update the ECS task definition... I will have a think about this.
=> check that terraform remote state is configured before release

server/controllers/index.js, server/routes/index.js, server/services/artefacts.js, server/views/pages/explore.njk
As it seems we're heading as using WordPress content as article truth (for the time being).
Eventually most things will be migrated to `/articles`, and I assume we will deprecate the `/artefacts` URL.
=> separate articles and artefacts

server/views/components/footer/index.njk, server/views/templates/article.config.yml, server/views/templates/templates.config.yml
Getting opening hours and misc article data to display in Cardigan (after updates to the app).
Also slipped in a realignment of the footer map at the awkward intermediate breakpoint after a chat with @Norvard.
=> Fix opening hours/article page description in Cardigan

server/views/docs/index.md, server/views/docs/principles.md
This link was added in #234, but visiting that page on the live site (https://cardigan.wellcomecollection.org/docs/principles) gives a server error.  Changing to `principles.html` seems to work.
Fix a broken link on Cardigan.
Docs and A11y testing not needed.
Tests: it’s theoretically possible to test for broken links in CI (which might have caught this). Serve the website locally, then run a crawler that follows every link it can find and looks for pages that throw an error. In practice, not sure if it’s worth spending the time (and the incurred CI delays) to actually do so.
=> Fix link to principles on the Cardigan home page

.gitignore, PULL_REQUEST_TEMPLATE.md, server/README.md, server/browserstack/browserstack.js, server/browserstack/test-browsers.json, server/package.json
- Allows us to make a call to the Browserstack screenshots API to generate screenshots of a local url in a variety of supported browsers. Can then follow links to actual instances of those browsers.
From the server folder you can generate screenshots against a local URL with the following command:
npm run test:browsers <url>
In order for this to work need to add your browserstack credentials to 'browserstack/browserstack-config.js' in the following format:
{
"username": "<browserstack_username>",
"key": "browserstack_key"
}
**N.B. This file is git ignored, but worth mentioning that it should not be committed**
N.B. Not all supported browsers are available via the screenshots API
=> Browserstack

client/scss/utilities/_variables.scss, server/views/templates/article.njk
Giving a bit more room to the content on mobile (36px of horizontal padding, rather than 60px).
Before:
After:
=> Reduce padding on narrow screens; add containers to article template

client/scss/components/_body_content.scss, server/views/pages/article.njk, server/views/templates/article.njk
Adding a divider after the body content. Closes #255.
This was more convoluted than I had initially imagined, given that the divider needs to run off the horizontal position of the content, which can be shifted by any number of grid cells. I've added a class to the final grid cell within the body content (rather than creating a long and confusing selector with lots of pseudo-selectors) – I'm sure there's a way to do this with less duplication in the nunjucks, though (cc @jamesgorrie).
=> Add divider after body content

client/scss/application.scss, client/scss/components/_author.scss, client/scss/components/_body_content.scss, client/scss/components/_divider.scss, server/views/components/author/index.config.yml, server/views/components/author/index.njk, server/views/pages/article.njk, server/views/templates/article.njk
Adding a variant of the author component to appear after the article. It appears after the body content, but before the dividing rule that was previously part of `body-content` element. Done some rejigging accordingly. Closes #280.
The template is defensive enough to handle combinations of with/without twitter handle/image
=> Update author to include border-left variant

server/test/util/body-parser.js, server/util/body-parser.js
Fixes #283
We now remove a whitelist of attributes from the HTML from WP.
The `bodyParser` now works like:
* Clean Nodes
* Convert Nodes
* If not converted, change to DomNode and clean.
=> remove certain atts from WP API

client/scss/base/_row.scss, client/scss/utilities/_variables.scss, server/views/global/palette.config.yml
The `keyline-grey` used to be `#e8e8e8`. It was darkened in order for it to work with the darkened `cream` page background.
The lead-in block (running alongside e.g. the page title) uses that variable currently, but sits on a white background, so didn't need the update.
This PR re-adds the trusty `#e8e8e8` as the new color variable, 'smoke'.
Fixes #247.
=> Add 'smoke' grey for lead-in block

client/scss/components/_article.scss
=> Aligned top of vertical  keyline to bottom of author block

client/scss/base/_row.scss, client/scss/components/_page_description.scss, server/views/components/page-description/index.config.yml, server/views/components/page-description/index.njk, server/views/pages/article.njk
This optionally includes the 'lead' row as part of the page-description component to allow the bottom of the grey bar to align with the title baseline, even when the component contains date info. Fixes #246.
=> Rework page-description to allow grey lead bar to run off text baseline

server/test/util/body-parser.js, server/util/body-parser.js, server/views/components/article-body/index.njk
Adding the standfirst body part type.
This is to try and get the model into a more complete state.
We are currently importing all the HTML content into the field as it seems variable (Sometimes there's links, italics, quotes etc) and a standfirst should be able to support HTML rather than just text - so this is good for now.
Same as before
=> add standfirst bodypart type

server/views/components/footer/index.njk
Per the commit message.
“Wellcome” is a proper noun and should be capitalised as such.
=> Correct the capitalistion of 'Wellcome' in the footer

Dockerfile, build-server.sh, server/.babelrc, server/.gitignore, server/package.json
Webpack as a build step was slow and annoying - given we don't need bundling on the server, I thought I'd try use babel exclusively.
Webpack also makes it hard to use libs like [Flow](https://flowtype.org) (which I really want in) by adding the bundle step.
=> Use babel over webpack for server compilation

client/scss/components/_page_description.scss, server/views/components/page-description/index.njk
Correcting some spacing inconsistencies within the page description when the lead grey bar and intro copy are/aren't present.
Before:
After:
=> Fix page-description spacing with/without lead bar/intro

server/views/components/article-body/index.njk, server/views/components/button-button/index.njk, server/views/components/button-input/index.njk, server/views/components/button-link/index.njk, server/views/components/figure/index.njk, server/views/components/footer/index.njk, server/views/components/gallery/index.njk, server/views/components/icon/index.njk, server/views/components/media-item/index.njk, server/views/global/icons.njk, server/views/global/palette.njk, server/views/global/typography/typography.njk, server/views/layout/default.njk, server/views/pages/article.njk, server/views/pages/explore.njk, server/views/pages/index.njk, server/views/templates/article.njk
I got bored of looking at different things, and though I'd try write a regex for my find/replace.
This is the result.
We use single quotes as that's what we do in JS, and HTML often uses double, and Jinja use them.
I've added a space between the template var denoter and the content for clarity.
=> add some consistency to njk templates with regards to quotes and spacing

server/views/layout/default.njk, server/views/pages/explore-landing.njk, server/views/templates/explore-landing.config.yml, server/views/templates/explore-landing.njk
Adding a template to house components being built for the explore landing page.
Also adding a macro to set grid classes.
=> Add starter explore-landing template

server/controllers/index.js, server/filters/index.js, server/filters/parse-body.js, server/fractal-app.js, server/model/article.js, server/views/pages/article.njk
Just gives me an endpoint to lookat to see what the JSON would look like for the article.
As I am experimenting with Contentful and WP APIs for content creation (as a intermediary step before the API team get going) - this is very useful to me.
=> add bodyParts to article model and return article as JSON

client/scss/components/_promo.scss, server/views/components/promo/index.config.yml, server/views/components/promo/index.njk, server/views/templates/explore-landing.njk
- Makes the promo component more generic for use in the various explore page blocks.
- Adds some styles for the different promo variants.
=> Promo component

client/scss/components/_promo.scss
Adding hover transitions to promos. Closes #346.
=> Add hover transitions to promos

server/views/components/author/index.config.yml
Removing the copy beneath the author in the 'border-bottom' variant (which appears above the article) in Cardigan, so that it is a better representation of how it will display in reality (see #257).
=> Remove copy from below 'border-bottom' author in Cardigan

client/scss/components/_footer_social.scss, client/scss/components/_header.scss, client/scss/components/_opening_hours.scss, client/scss/components/_page_description.scss, client/scss/components/_skip_link.scss, client/scss/utilities/_mixins.scss, server/views/components/skip-link/index.njk, server/views/templates/explore-landing.njk
Adding an `h1` to the explore landing page for good markup-validation/a11y/~snake-oil sales~SEO.
Like this:
It's hidden. Geddit?
=> Add explore landing (hidden) h1

server/controllers/index.js, server/routes/index.js
[We are adding a script to the v1 site](https://github.com/wellcometrust/collection/pull/254) that will link to this file.
Given that it's generated dynamically, the point would be to do the heavy lifting of rendering a page (API calls etc), but then just return a boring JS file. This way we can see how our infrastructure holds up against real time users metrics, but also not vacuum up their bandwidth.
Nothing to see here.
=> add script to be included on v1 for perf testing

client/scss/components/_figure.scss
Limits the max-width of the hero-image to 100%, preventing horizontal scrollbars. Fixes #373.
=> Prevent >100% width image

server/util/body-parser.js
We are going to infer weight of an image dependant on the alignment within the WordPress CMS.
It's a hack, but it's simple for editors, and simple to have the same inference when we migrate.
`right => supporting content`
`center => standalone content`
=> infer weight of image from wordpress align

server/views/components/footer/index.njk
Adding missing quotes to fix the footer grid. Fixes #389.
Before:
After:
=> Unbreak footer grid classes (add quote marks)

server/util/body-parser.js
Turns out centre align is used a lot for image that are portrait.
I cannot find instances of left (which would basically mean nothing), or right aligned images.
As per #381
=> use left instead of center align to infer standalone

server/app.js, server/middleware/enforce-ssl.js
Might fix #317 
Adds the [HSTS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) header over. We're sending a very lax `max-age` across to allow for some wriggle room if we've got something that __needs__ to be sent over `http`, but it'd be good to change that as soon as.
=> send HSTS header across to enforce SSL

client/scss/components/_page_description.scss
Correcting the spacings in the page-description – doing [pixel manager's bidding](https://github.com/wellcometrust/wellcomecollection.org/issues/366#issue-202162846). Closes #366.
With date:
Without date:
=> Fix page-description spacings

client/scss/application.scss, client/scss/base/_container.scss, client/scss/utilities/_classes.scss, server/views/components/article-body/index.njk, server/views/templates/explore-landing.njk
Containers with overflowing content don't, by default, have momentum scrolling (the kind you _do_ get when scrolling down the body of a page) by default on iOS.
This PR adds a utility class – `touch-scroll` – to enable that behaviour for use on our horizontal scrolling containers.
=> Scroll touch

server/model/article.js, server/package.json, server/util/body-parser.js
WordPress sends over HTML as entities.
As we're rendering as UTF-8 it's not really necessary.
An example is here:
https://next.wellcomecollection.org/articles/no-photography
=> Decode HTML entities from WordPress

server/controllers/index.js, server/model/page-config.js, server/views/layout/default.njk
Adding titles to pages.
I thought about adding it to the template in a `{% block title %}{% endblock %}` - but that felt like it wasn't the templates job.
=> add title to pageConfig

client/.babelrc, client/js/app.js, client/js/util.js, client/package.json, client/webpack.config.js
This reverts commit dcbef7fbc5ac0373a8853017242406430860b297.
`babel-polyfill` adds about 250kb onto the JS pack.
Let's not do that - I've reverted out the change, and if we want to use specific polyfils, let's make sure we keep an eye on the monitoring (or better yet, setup alerting) and use [`core-js`](https://github.com/zloirock/core-js) if we need to (which is what babel-polyfill uses anyway).
💨
=> Remove babel-polyfill

circle.yml
Run a speedtracker test on merge with master.
This isn't perfect as it will actually track the last deploy's performance, but it will at least have it automated. It will be easier when we're deploying master automatically.
=> Add speedtracker api call to circleci

client/js/app.js, client/package.json, client/scss/components/_wobbly_edge.scss, server/views/components/captioned-image/index.njk
Adds lazyloading to images, so the initial page weight is reduced and high quality images are only loaded if the user sees them.
Same but reduces initial page load (most significant on wide screens).
Before:
After:
~~- [ ] A11y testing - Have you run pa11y against the component and fixed/verified all errors, warnings and notices?~~
=> Lazyloading

server/util/body-parser.js
Fixes #369 
Turns out you can have:
* images
* images wrapped in `a`s
* images with captions
* images with captions in `a`s
This caters for all of those. There might be something more elegant, but the quicker we can get rid of the need for these parsers, the better.
=> find images wrapped in a tags

server/util/body-parser.js
Removing the `em` from the WP inferred standfirst (i.e. first paragraph).
=> Add unwrapFromEm method to fix standfirst style

client/scss/base/_row.scss, client/scss/components/_new_site_notice.scss, client/scss/utilities/_variables.scss, server/views/pages/explore.njk
After talking to @Norvard it seems we should be using vertical spacing that is multiples of 6, specifically 60 for desktop, 30 for mobile.
See #496 as a solution.
## Desktop
=> use proper vertical spacing (6px) on rows

server/data/people.js, server/model/article.js, server/model/person.js, server/services/author-lookup.js
Authors will have to be from a lookup somewhere.
At the moment this will be manual - we will be having someone help assign articles to authors.
# Version No author
=> use autho lookup rather than WP author

server/views/components/new-site-notice/index.njk
=> align new site notice correctly

client/.stylelintrc, client/scss/components/_captioned_image.scss, client/scss/components/_image_gallery.scss, client/scss/components/_promo.scss, server/controllers/index.js, server/filters/image-sizes.js, server/model/body-part.js, server/model/content-type.js, server/model/display-type.js, server/model/promo.js, server/model/weight.js, server/views/components/captioned-image/index.njk, server/views/components/image/index.config.js, server/views/components/image/index.njk, server/views/components/promo/index.config.js, server/views/components/promo/index.njk
Reduce explore landing page size by making promo images use responsive srcset/sizes attributes and lazy loading.
Before:
After:
=> Promo images

circle.yml
As we override the deps step we need to ensure running the default `npm install`
=> ensure that we install root packages

infra/terraform/container-definitions.json, infra/terraform/templates/launch.tf
I think this is overkill - but as we'll be driving traffic from FB etc - seems better safe than sorry.
I'd like to look at optimising this as we still have a lot of unallocated resource as we need to leave some spare for deployments - @kenoir - do you have the same thing?
=> bump servers up just slightly

server/middleware/enforce-ssl.js
Removing this as it's a bit more complicated as headers etc from AWS vs local Nginx are completely different.
I will do this on the URL level to avoid application complexity.
=> remove redirect to https

client/scss/base/_container.scss, client/scss/components/_promo.scss, client/scss/grids/_grid_featured.scss, client/scss/utilities/_variables.scss, server/views/pages/explore.njk, server/views/templates/explore-landing.njk
Fixes #487 (almost)
- This only works for Safari, Chrome and Opera, as they are the only browsers that support these properties
- I'm not able to reduce the vertical space above the scrollbar without it appearing too close to the content in browsers that don't support these properties.
=> Scrollbars

server/util/body-parser.js
We've decided that we want to have supporting more than standalone.
This shouldn't be an issue once wordpress rendering is deprecated.
=> swap wordpress inferance of supporting and standalone around

server/views/components/promo/index.config.js
Removing the colour treatment from the standalone article promo as per discussion on #352.
=> Remove colour treatment from standalone promo

client/scss/components/_captioned_image.scss
Fixes #553  
We've decided that we don't want max-height on images.
=> remove max height form images

client/scss/base/_row.scss, server/views/pages/explore.njk
=> remove spacing from the 'May have missed' container

server/util/body-parser.js
We've had this error before where Wordpress misformats the HTML.
I thought it was a once off thing - much better to not throw an error here.
=> check for childnodes in body parser when looking for an image

server/.babelrc
This doesn't error as there is no nunjucks specific code in it - but we should exclude it.
Let's have a think of a more scalable solution.
=> dont' compile hotjar NJK file with babel

infra/terraform/container-definitions.json
Had to drop it slightly as Docker uses up memory so you can't just divide by 2.
We're still running at way below 10% - I'd like to find a way to be more efficient with this.
=> drop memory requirements on ecs

server/model/article-promo.js
`.values` is part of es2017 - I thought this would have been added using [`babel-preset-env`](https://github.com/babel/babel-preset-env) - alas not. 
__TODO:__
Either add some health checks to the ALB to not use the service is `/explore` isn't up - or add it to the tests to break the build.
=> use supported Object.keys instead of .values

client/scss/components/_captioned_image.scss, server/views/components/captioned-image/index.config.js, server/views/components/image-gallery/index.njk, server/views/pages/article.njk, server/views/pages/index.njk
This reverts commit 3bc550714d553524eb4261a773fcd51332a09354.
Sorry for the reversion. I merged into master mistakenly.
This adds the main  image to the homepage.
It also removes the `max-out-height` that was hangover of not making images full width.
=> Revert "Revert "add main image to index page""

client/scss/grids/_grid_featured.scss
Unbreaking the 'featured' grid on IE.
Before:
After:
=> Fix featured grid in IE

server/controllers/index.js, server/views/components/promo/index.njk
Reduce the page size by providing sizes attribute to images
Before:
After:
=> Added default sizes attribute to articles promos

server/model/article-promo.js, server/model/article.js
We won't always have a thumbnail from WP - so make it nullable.
There's a bit of modelling to be done here around allowed data vs validated data.
=> only add thumbnail if we have one from Wordpress

infra/terraform/templates/cloudfront.tf
Adding CloudFront to the site as the response times are slow.
I suppose some might be from the small stack we're using, but the latency between us and Wordpress is something we can't control, which makes this seem more like a good idea.
=> add cloudfront distribution for next.

client/scss/components/_header.scss
Fixes input/close cross display on iOS. Fixes #592.
=> Fix close cross

client/scss/components/_promo.scss
Keeping the promos in a `grid--m8` in a side-by-side configuration rather than breaking them into a one-column layout.
Before:
After:
=> Keep m8 promo in side-by-side configuration

client/package.json, package.json, server/app.js, server/package.json, server/run.js, server/test/app/app.js, test.sh
Adding a few integration / endpoint tests.
These are rudimentary - and would like to keep them that way.
It'd be good to see if keeping the WP API call in here slows the build too much - if so, we'll have to create some mock API - and then probably start looking at dependency injection os the Wordpress service... quite a bit of work for something that I am unsure will be a problem.
Locally I don't think this a problem locally as you can run `npm run test:watch ./test/app/app.js` to not run all the tests.
=> add integration / endpoint tests

infra/deploy.sh
When we do a deploy - we are essentially deploying the whole stack.
This makes me uneasy - but also causes problems if the deployer isn't on master or the stack is out of sync for some reason. 
This will also allow me to let something like Circle deploy with minimal permissions.
=> Only deploy task definition with deploy script

client/scss/components/_header.scss
Fixing issue where two taps are required on a nav link in order to follow link on iOS. Fixes #622.
Adding the `pointer: coarse` media query to _remove_ the desktop styles rather than adding the required styles with `pointer: fine` is necessary because IE only supports the `pointer` media query property in nightly builds, at present.
=> Prevent iOS double-tap link issue

client/scss/base/_typography.scss
Removing browser common ligature correction (which doesn't play nice with our loosened up Helvetica). Fixes #490.
See [here](https://github.com/wellcometrust/wellcomecollection.org/issues/490#issuecomment-282158278) for before/after. Props to @alexwlchan for debugging skills.
=> Remove browser common ligature correction

Dockerfile, circle.yml
Main reason being it puts the secret into our public docker.
I've deleted those docker tags and cycled the key,
=> remove keymetrics from docker

server/views/components/more-info-link/index.njk
Removes the 'More from' before a series title to avoid clunky mid-sentence title case. Fixes #575.
=> Remove 'More from' before series title

client/scss/components/_promo.scss
Moving the standalone promo description text to the top of the containing box on desktop. Fixes #483.
(guide for illustration, obvz).
=> Align standalone promo copy with meta on desktop

client/scss/components/_header.scss
Adding a keyline to the top of the burger navigation. Fixes #261.
=> Add keyline to top of burger nav

client/scss/components/_captioned_image.scss, server/views/components/captioned-image/index.njk, server/views/components/image/index.njk, server/views/pages/article.njk, server/views/templates/article.config.yml
Adding the chapter indicator bars to the hero image area where required. Allows the captioned-image template to choose whether it should have chapter indicator bars based on the presence/absence of series information in the model. Closes #653.
=> Pass series data into article header area

client/scss/base/_row.scss, server/views/pages/article.njk
Adding space to the bottom of the article (before the footer). Fixes #560.
It is our intention to try and refactor out the `$v-spacing-unit` altogether (creating standalone classes to handle component spacing), but this quicker solution to this issue will only create negligible extra effort for that much larger piece of work.
=> Add space to bottom of article

client/scss/components/_numbered_list.scss, server/model/numbered-list.js, server/views/components/numbered-list/index.config.js, server/views/components/numbered-list/index.njk
Creating a horizontal version of numbered lists to be used in series navigation
=> Added styles for horizontal numbered lists

client/js/components/make-sticky.js, client/js/components/prevent-overlapping.js, client/scss/components/_body_content.scss
Scrolly-shove instead of fading out the sticky elements in the right-hand rail. Fixes #574.
=> Shunt images offscreen instead of fading out

client/scss/components/_footer_social.scss, server/views/components/footer-social/index.config.yml, server/views/components/footer-social/index.njk, server/views/components/footer/index.njk, server/views/layout/default.njk
Adding a 7-up style for the social media icons on large desktops. Fixes #571.
=> Layout social media icons 7-up at widest desktop size

client/js/app.js
Reducing noise in Sentry by not reporting local/Cardigan errors. Fixes #664.
=> Don't init with Raven when localhost/cardigan

client/js/components/prevent-overlapping.js
Checking if `Element`s prototype has a `before()` method (required for wrapping the sticky right-hand rail stuff) and bailing out if it isn't supported. Should reduce noise in Sentry.
=> Bail out if Element doesn't have a  method

client/js/app.js, server/views/partials/monitoring.njk
We now use the Sentry config correctly (its not passed to the `install` method, but the `contrustor` method).
Tested and is silent on everything but `next.`.
😶
=> use sentry config correctly

server/model/article-stub.js, server/model/article.js, server/model/media.js, server/model/promo.js, server/model/video.js, server/util/body-parser.js, server/views/components/captioned-image/index.config.js
Implementing @davidpmccormick's good work on the Video main media.
I haven't thought of a way to bring in a thumbnail / promo image.
Normally we get it from the featured image in WP, but we don't have this on video pages so as not to knock dow the video.
The reason we can't get it on promo pages is because we would have to ask for the article content for every articles, which is way to much data to send down the pipes.
This is the current functionality on WP, but it would be nice to not have it like that.
e.g:
Options:
* We add a featured image and accept that it will look strange on the blog.
* ???
=> Video in main media

client/js/app.js
We don't serve the enhanced version to anyone who doesn't support `DOMContentLoaded` - so let's not pretend we do.
🐐
=> remove readystate check for DOMContentLoaded

client/scss/components/_promo.scss, server/filters/get-icon-for-content-type.js, server/model/content-type.js, server/views/components/promo/index.config.js, server/views/components/promo/index.njk
Using the correct model key to display icons on promos.
=> Redisplay contentType icons on promos (using filter)

infra/terraform/container-definitions.json
Adding nginx so we can start proxing to different places.
First on the list is making sure we can redirect traffic from `blog.` => `next.`.
The corresponding project is here:
https://github.com/wellcometrust/wellcomecollection-nginx-proxy
I'm not sure how we will do service discovery as yet.
=> Nginx proxy

server/views/components/article-body/index.njk
Making sure that the standfirst is the standfirst on pages with mainMedia as video.
This won't cause regressions as the standfirst is always the first paragraph anyway.
=> add standfirst if it's the first in the body parts loop

infra/terraform/prod/wellcomecollection.tf, infra/terraform/templates/vars.tf
These aren't needed anymore as the provider is specified in the main tf file.
=> remove terraform provider vars

server/model/article-stub.js
Importing `getSeriesCommissionedLength` from `data` rather than `model` (fixes promos on e.g. explore landing).
=> Import getSeriesCommissionedLength from data directory

client/js/components/make-sticky.js, client/js/components/shrink-stories-nav.js, client/js/utils/dom-events.js
Just throttling means the nav can end up at the wrong size if a user has scrolled quickly. A debounce that will always fire after scrolling finishes fixes this.
=> Add a debounced window scroll event

server/model/article.js
Not sure why the API doesn't return the main image in the attachements - but hey, it's not our API.
=> revert to thumbnail if we don't have main image in attachments

server/views/components/captioned-image/index.njk, server/views/components/main-media/index.njk, server/views/pages/article.njk
Removing the wobbly line from articles with a `contentType` of `video` or `image` to prevent unwanted distraction from the main content.
Also re-adds the accidentally removed series data, used to display chapter indicator bars on main-media images. And only displays those bars if the `contentType` is 'article' (so they don't overlay e.g. videos or webcomics).
=> Remove wobbly line from videos and 'image' contentType

client/scss/components/_promo.scss, server/views/components/promo/index.njk
Moving the margin from the icon to the meta info so the icon has equal padding when e.g. the timestamp isn't present. Fixes #732.
=> Move margin from icon to length

server/app.js, server/config/index.js, server/package.json
Removing the compression from the JS app.
[We've moved this into the `nginx` config](https://github.com/wellcometrust/wellcomecollection.org/blob/master/nginx-proxy/nginx.conf#L33-L36) as Nginx is made for this, JS isn't really.
It also nicely decouples HTTP logic from app logic.
@gestchild what do you think about moving cache controlling here too?
e.g. https://serversforhackers.com/nginx-caching
🌵
=> remove koa-compress as we're gziping with nginx

client/js/components/make-sticky.js
We don't want to add sticky behaviour on browsers that don't support `before`, because it's required to do the element wrapping that allows for the shunting of sticky right-hand rail stuff on/off the screen. Fixes #743.
=> Don't apply sticky class if 'before' not supported

server/util/body-parser.js
From the past it seemed like a gallery group would only ever have one gallery item.
This isn't the case - so we then great groups of images, and reduce them into a single dimensional array.
MORE 🖼 !
=> loop through gallery items in bodyParser for image galleries

server/views/components/promo/index.njk
Zooming the clipped images at the same time as the main image. Fixes #753.
=> Enable zooming of clipped promo images

client/scss/components/_promo.scss
Preventing large hero promo type overlapping the image. The largest type size is still used at the very largest screen size ('xl'), but a slightly smaller one between 'l' and 'xl'
Before:
After:
=> Add an intermediate title size to prevent text overlapping

infra/terraform/templates/alb.tf
Use the *.wc.org cert so we can cater for things like blog.wc.org
=> use *.wc cert on ALB

server/util/body-parser.js
Parsing images that aren't from the WC blog.
e.g. https//i1.wp.com/www.sciencemuseum.org.uk/HoMImages/Components/400/40024_3.png
on: https://next.wellcomecollection.org/articles/mummies-revealed
=> parse images that aren't from WC Wordpress

client/scss/components/_numbered_list.scss
Chrome has a bug where the borders sometimes vanish on elements that have position:sticky applied. This would occasionally happen to the series nav when the page was scrolled.
Compensating by adding a background to the series nav.
=> Compensate for disappearing border in Chrome on series nav

client/scss/components/_body_content.scss
Fixes bug where an image caption can overlap the footer if it doesn't have position: sticky applied (which it won't if it's longer than the window)
Not like this anymore:
=> clear last floated element

client/js/components/async-content.js, client/js/components/content-slider.js, client/scss/components/_numbered_list.scss, server/views/components/numbered-list/index.njk
Fixes #779
After discussion with Tomi, we've decided to ensure the current item is always in view onLoad and have added a highlight style to the current item in order to make it more identifiable.
=> Position nav at x

client/js/components/content-slider.js, client/js/components/truncate-text.js, client/scss/components/_captioned_image.scss, client/scss/components/_image_gallery.scss, client/scss/utilities/_root-scope-classes.scss, server/views/components/captioned-image/index.njk, server/views/components/image-gallery/index.njk
Addressing 'quick fixes' to image gallery. Closes #777.
- One caption visible at a time,
- Control buttons moved over (and to the right of) images
- 50% opacity non-selected images
- Clicking image moves to that image
- Cream slide background
- Slides bottom-aligned with background
=> Image gallery quick fixes

client/scss/components/_article.scss, client/scss/components/_author.scss, client/scss/components/_body_content.scss
Ensuring the content is centred on the page – currently there is less space to the right of the content than there is on the left.
=> Center content in grid--no-gutters

server/views/components/promo/index.config.js, server/views/components/promo/index.njk, server/views/templates/explore-landing.config.js, server/views/templates/explore-landing.njk
Adding a 'comic' `contentType` and adding it to the explore-landing template in Cardigan. Closes #803.
=> Comic promo

server/views/components/promo/index.njk
Adding the part of the digital story in place of the promo content type. Addresses #770.
=> Add digitial story part to promo

infra/terraform/cloudfront/cloudfront.tf
Allow the format param, we'll need this for migration to get the articles in JSON format.
=> add format query param to cloudfront

server/filters/image-sizes.js
Seems the upper limit of the WP resizer is 2048 for some reason (probably memory).
=> add extra image size to upper limit or wordpress image resizer

server/filters/get-principle-main-media.js, server/model/article.js, server/model/picture.js, server/util/body-parser.js
Leaving the WP 'featured image' free to operate as the (16:9) promo image, similar to how we've done it with video articles.
=> Use first body image as 'main-media'

server/filters/image-sizes.js
Reduce the size of images loaded on small screens.
The getImageSizesFor filter was jumbling up the order of the sizes array, which meant the default image src being selected was larger than intended. This makes sure the array is ordered correctly, so the small size is chosen by default.
=> Sorting image sizes smallest to largest

server/views/components/author/index.njk
We're serving up the full image size, and we shouldn't be.
=> use image resizer on author image

infra/terraform/container-definitions-thumbor.json, infra/terraform/container-definitions.json, infra/terraform/dev/wellcomecollection.tf, infra/terraform/prod/wellcomecollection.tf, infra/terraform/templates/alb.tf, infra/terraform/templates/ecs.tf, infra/terraform/templates/launch.tf, infra/terraform/templates/s3.tf, infra/terraform/templates/vars.tf, thumbor/Dockerfile, thumbor/docker-build.sh, thumbor/docker-push.sh
As we'll be losing the Wordpress image resizer, and Prismic doesn't come with one, e need to roll our own (or, in this case, just host a well tested solution).
We'll need to add some perf metrics in here, and cache.
Next will be adding this to the build.
There's also a need to maybe start tidying the Terraform - but it works and is clear enough for now.
🎨
=> Add thumbor Docker container and have it run in ECS

circle.yml, infra/terraform/container-definitions-thumbor.json, nginx-proxy/docker-push.sh
Push the thumbor docker build when we build in circle...
This is actually seeming like overkill, because the nginx-proxy, and the thumbor docker container is actually the same most of the time...
I\ve raised an issue to look at this at some stage:
https://github.com/wellcometrust/wellcomecollection.org/issues/874
=> add thumbor docker push to circle build

thumbor/Dockerfile
Sources are meant to be the source only as they're matched against the host.
We can use regex's - but as the aspl/thumbor uses ENV vars over python config, I haven't quite found a way to do this.
This is the line of code from thumbor that uses regex:
https://github.com/thumbor/thumbor/blob/522a0ec364285662e6101b8cc479b928b90078eb/tests/loaders/test_http_loader.py#L124
I'd just like to get this on to move forward.
=> use root source for prismic bucket in thumbor

server/services/prismic-api.js
Access prismic over https because we should (and it's causing problems moving over to the new API).
=> access prismic over https

client/scss/components/_captioned_image.scss
Fixes bug in firefox. When scrolling on article pages with sticky images, the height of the figcaption on images in the main section would keep increasing in size, which had the effect that the user constantly scrolled passed the same content.
**Before**:
**After**:
=> Fixing firefox bug on article pages

server/test/util/body-parser.js, server/util/body-parser.js
While doing the Prismic migration I noticed from [this article](https://next.wellcomecollection.org/articles/voicings) we have wordpress embedded articles.
We're not doing anything special with them now, it's just so I can semantically get the embed code later.
also removed `hr` tag and `script` tags.
=> format wordpress videos and remove scripts and hrs

server/views/components/numbered-list/index.njk
Changing 'Currently viewing' to 'Currently reading'. Closes #848.
=> Change 'currently viewing' to 'currently reading'

server/views/components/page-description/index.njk, server/views/pages/article.njk
While adding content to Pocket, I realised it wasn't parsing our article.
Weirdly this doesn't work either, but it's something we should probably do.
I haven't added a whole bunch of the stuff (author etc) as I'm waiting to hear back from Pocket to see if they support JSON-LD - if they do, we'll just dump that on the page.
=> add article schema tags

server/views/components/article-body/index.njk
Old content sometimes has images as the first bit of content.
Assuming that's before the world of featured image.
We could have made it main media - but the content actually doesn't seem high enough quality to.
e.g: https://next.wellcomecollection.org/articles/lunch-on-drugs
=> account for articles that have the first body part as an image

client/scss/application.scss, client/scss/components/_captioned_image.scss, client/scss/components/_lazyload.scss, client/scss/utilities/_mixins.scss, server/filters/image-sizes.js, server/views/components/article-body/index.njk, server/views/components/captioned-image/index.njk, server/views/components/find-us/index.njk, server/views/components/image-gallery/index.njk, server/views/components/image/index.njk, server/views/components/numbered-list/index.njk, server/views/components/promo/index.njk, server/views/components/series-container/index.njk, server/views/components/transporter/index.njk, server/views/pages/explore.njk, server/views/pages/list.njk, server/views/templates/article.njk, server/views/templates/explore-landing.njk
Reduce the size and number of images we are loading
e.g explore landing page
Before:
After:
=> Image loading

server/controllers/index.js
Just updating as the intervalCache is on the context now, so this is broken
=> intervalCache object no longer on config

nginx-proxy/nginx.conf, server/controllers/index.js
This is a:
Allowing us to forward traffic to the new old site successfully thus take over the URL without having to proxy via `next.`. This was just a header missing that @alfraser86 let me know about to make drupal use https.
=> Nginx proxy with https x header

client/js/components/content-slider.js
Quick fix for broken digital story series nav (no prev/next buttons and horizontal page scroll). Git bisect put it down to the `.trim()` move, so I've put it back to how it was. All of this will be refactored out with an upcoming re-implementation of the slider/numbered-list.
=> Fix series nav

client/gulpfile.js, server/views/components/numbered-list/index.njk
This is a:
Reducing the size of images loaded on the explore landing page (by about 2.5 MB)
=> Added correct sizes attribute to transporter images

server/views/components/chapter-indicator/index.njk
Fixes #948.
This is a:
Making the digital story text/chapter-indicator bar colour match.
=> Use foreground colour for chapter bars

server/views/partials/monitoring.njk
Allowing us to prevent Sentry reporting on errors from browsers that we don't support.
This is a:
=> Don't send old iOS errors to Sentry

client/js/app.js
This is a:
Ensuring any polyfills are available in the browser before they may be needed.
=> Ensure polyfills are available before anything else

server/views/partials/monitoring.njk
This is a:
- Updating the Sentry ignored browser browser list to include Bing Preview
- Updating the Sentry ignored urls list to include Google Translate.
=> Sentry ignore browsers

server/views/pages/article.njk
References #919.
This is a:
Adding a consistent underline beneath the hero image.
=> Add underline below main media (hero)

client/scss/components/_slider__in-article.scss, client/scss/components/_slider__in-content.scss, client/scss/components/_slider__in-explore.scss, client/scss/non-critical.scss, server/views/pages/explore.njk
This is a:
Decoupling a few more things on the image slider - there will be more of a follow up on this again.
This came up when trying to do some work on the preformatted text which shows that things are a little to coupled.
You can see this article to see how it's out of whack:
/articles/eels-and-feels
=> decouple a few more slider scss things

client/scss/components/_divider.scss, server/views/components/divider/index.config.js, server/views/components/divider/index.njk, server/views/components/series-container/index.njk, server/views/pages/article.njk, server/views/pages/explore.njk, server/views/pages/list.njk, server/views/templates/article.njk
References #670.
✨ Feature  
Adding a dashed divider (in preparation for use with #670) and componentising the divider.
=> Componentise divider

client/scss/components/_pre.scss
🔧 Fix  
Makes things look nicer when you don't need to scroll.
=> use scroll:auto for reformatted text

client/scss/components/_tweet.scss
Fixes #975
🔧 Fix  
Removes the horizontal scrollbar that can occur on iOS as a result of `width` not being honoured for iOS iFrames.
=> Use min-width instead of width (fixes iOS, supported everywhere)

server/controllers/index.js, server/model/page-config.js, server/views/partials/analytics.njk
Closes #940.
This is a:
Sends the page content type through as a custom dimension to GA.
Can be one of
- article
- digital story ('digital story: name of digital story')
- comic
- video
- article list
- series list
=> Add content types for GA tracking

client/scss/components/_captioned_image.scss
🔧 Fix  
Fixes regression where comic image could stretch the full width of the viewport while having a constrained height.
before:
after:
=> Override min-width: 100% for comics

client/js/app.js, client/js/tracking.js
✨ Feature  
Will allow us to see what the destination URL is from an exit page in GA.
🔍
=> Enable tracking of external links in GA

server/services/author-lookup.js
🔧 Fix  
Adds Rob as author of _Pundit_ comic.
=> Add Rob Bidder as author of pundit comic

client/scss/components/_grid_placeholder.scss, client/scss/components/_promo.scss, client/scss/utilities/_mixins.scss, client/scss/utilities/_variables.scss, server/views/components/footer/index.njk, server/views/components/main-media/index.njk, server/views/components/page-description/index.njk, server/views/components/promo/index.njk, server/views/components/series-container/index.njk, server/views/components/social-media-block/index.njk, server/views/components/transporter/index.njk, server/views/docs/visual-architecture.md, server/views/grid/aligning/aligning.njk, server/views/grid/container_queries/README.md, server/views/grid/container_queries/container_queries.njk, server/views/grid/nesting/nesting.njk, server/views/grid/sizing/README.md, server/views/grid/sizing/sizing.njk, server/views/pages/article.njk, server/views/pages/catalogue-item.njk, server/views/pages/explore.njk, server/views/pages/flags.njk, server/views/pages/list.njk, server/views/templates/article.njk, server/views/templates/explore-landing.njk
Fixes #992
🚑 Health
This simplifies the grid to use 12 columns at all breakpoints, making it easier reason about.
It will change the width of some components on medium screens, but not dramatically, and have run this passed Tomi.
=> Grid refactor

server/controllers/async-controllers.js, server/data/series.js
🔧 Fix  
Enables the series nav to show up
=> Update series info

client/scss/benched.scss, client/scss/critical.scss, client/scss/styleguide.scss, server/views/layout/default.njk
References #910
✨ Feature (less)
The banner took up space and kept people from recognising that they're in 'Explore' section
=> removed alert banner

server/data/series.js
🚑 Health
Adds full 'The Outsider' titles into series navigation
=> Use full titles

client/js/components/shrink-stories-nav.js
🔧 Fix  
Puts rail items in the correct position under the series nav.
=> Use up-to-date nav height data

client/scss/components/_slider__numbered-list.scss, server/data/series.js
🔧 Fix  
Removes the doubled-up border that resulted from removing the new site notice.
=> Series nav border

infra/terraform/cloudfront/cloudfront.tf, server/controllers/content.js
🔧 Fix  
Makes the redirect service work.
* Fixed mixed promise function names (`resolve` and `reject`).
* Also does't use the cache for `/preview` and `/preview/*`.
=> add nocache to preview and fix promise function names

client/scss/components/_body_content.scss, client/scss/components/_slider__transporter.scss, server/views/pages/article.njk
Fixes #965
🔧 Fix  
Cleans up the spacings at the end of the digital story page.
=> Fix spacing at end of digital story page

client/scss/components/_divider.scss
Fixes #1025
🔧 Fix  
Stops the dashed divider looking weird on high pixel density screens.
=> Use background image instead of linear gradient to fix retina rendering

client/scss/components/_slider__gallery.scss
Fixes #1011
🔧 Fix  
Moves the gallery slider buttons up.
=> Move image gallery slider buttons up

infra/terraform/cloudfront/cloudfront.tf
🔧 Fix  
Stops search params being ignored by Cloudfront
=> Pass query parameter

server/controllers/content.js, server/services/prismic-api.js, server/services/prismic-content.js
🔧 Fix  
We make sure we return the latest version of the article.
If we only load the Prismic API on app launch, and then update the master ref (essentially the master branch of our content), we will be retrieving an old value.
I could setup a webhook on Prismic but that's feels a little to decoupled, but might if this causes problems, which I can't imagine it will.
=> refresh prismic API every minute

server/controllers/work.js, server/views/pages/search.njk, server/views/pages/work.njk
✨ Feature  
Puts imgix in front of the S3 bucket holding the miro images, so we can resize the images. Therefore page weight is reduced and images load much more quickly.
=> Imgix wellcome images

server/controllers/lists.js, server/services/prismic-content.js
Fixes #1033 
✨ Feature  
Consumes articles from Prismic and slams them onto the `/explore` page.
This means we can start producing Prismic articles, which will support things like multiple creators, footnotes, books, etc.
=> consume articles from prismic onto the explore page

client/scss/components/_body_content.scss
🐛 Bugfix  
We can now see bold.
I didn't use the `include font('BLAH')` as I want it to inherit the body sizes.
💪
=> Use helvetica medium for strong and b elements in body

server/controllers/lists.js
🐛 Bugfix  
Messed the order up a little, content lists are meant to be excluded, not the curatedLists.
=> exclude content from explore when flag is off

client/scss/base/_icons.scss, server/views/components/pagination/pagination.njk, server/views/pages/search.njk
🚑 Health
Updates the styles of 'Showing x of y' and pagination.
=> Update pagination styles

cardigan/config/statuses.js, cardigan/fractal-app.js, server/filters/array-from-object.js, server/filters/index.js, server/views/docs/index.config.js, server/views/docs/index.njk
🚑 Health
Adds a table of our component status codes to the front of the docs, for clarity (as seen on/cribbed from the [Perch UI pattern library](http://patterns.perchcms.com/)).
=> Add status codes/descriptions to Cardigan docs

client/scss/styleguide/_styleguide.scss
🚑 Health
Makes the code preview look a little bit smaller/nicer in Cardigan (currently looks kind of childishly big).
=> Decrease code preview size in Cardigan slightly

client/scss/utilities/_root-scope-classes.scss, server/filters/font-classes.js, server/filters/index.js
🚑 Health
We have a set of 24 possible typography styles and 4 breakpoints. This adds a font-at-breakpoint class for each combination (e.g. `.font-HNM3-s`).
The end goal is that we could do away with any font-family declarations within components and handle them in the markup (using  a `fontClasses()` filter, à la `spacingClasses()`).
Updating each component to use these classes in the markup will be a fairly tedious bit of grunt work if we want to do it. Reckons?
=> Add font-at-breakpoint classes

server/controllers/async-controllers.js, server/controllers/content.js, server/routes/index.js, server/services/eventbrite.js, server/services/prismic-content.js, server/views/pages/event.njk
✨ Feature  
Shows users the eventbrite widget so they can buy tickets.
We use a proxy here as EB have a crappy bug that means the iframe doesn't resize and we can't read the document dimensions as it's cross domain. This way we can.
Having it this way also means we don't need to say when the tickets go on sale (which isn't available on the EB public API) as the widget tells you.
=> embed eventbrite widget via proxy

server/app.js, server/middleware/error.js, server/routes/index.js
🐛 Bugfix  
Errors are actually sent over to sentry (I don't know why I thought that errors should be at the bottom us the `use` chain).
We also send over the URL correctly:
https://docs.sentry.io/clients/javascript/usage/#raven-js-additional-context
=> fix server sentry errors and send URL over correctly

infra/terraform/cloudfront/cloudfront.tf, infra/terraform/dev/wellcomecollection.tf, infra/terraform/prod/wellcomecollection.tf, infra/terraform/templates/alb.tf, infra/terraform/templates/ecs.tf, infra/terraform/templates/iam.tf, infra/terraform/templates/launch.tf, infra/terraform/templates/s3.tf, infra/terraform/templates/sg.tf, infra/terraform/templates/vars.tf, infra/terraform/templates/vpc.tf, infra/terraform/website-bucket/website-bucket.tf
Adds an `aws_iam_role` and associated policy and role policy to delegate ECS and ECR access to the platform team account root, from where it can be further distributed to devs.
This is in order that platform team members have visibility of experience team infrastructure and to provide for emergency infra changes.
It's also mixed in with a `terraform fmt` because I do not git correctly.
=> Delegate ECS/ECR access to platform team

server/app.js
🐛 Bugfix  
We were rendering the page before determining the cohort the user belongs to, thus breaking feature flags and stopping the search from showing. Now we're not
=> 'determineFeaturesCohort' before 'render'

server/views/components/promo/promo.njk
🐛 Bugfix  
We were incorrectly checking the modifiers instead of the contentType to determine whether or not to display Helvetica instead of Wellcome Bold.
=> Use contentType to set search promo type classes

server/data/people.js, server/services/author-lookup.js
🚑 Health
Adds Nicola Cook and Loesja Vigour as authors for the article, 'six-personal-health-zines-that-might-change-your-life'.
Uses a single `Person` model because WP can't handle the truth.
=> Add two authors to article as single person (hack)

client/scss/components/_captioned_image.scss, server/middleware/error.js, server/services/prismic-content.js, server/views/components/captioned-image/captioned-image.njk
✨ Feature  
First bash at putting copyright info on images.
A step towards using Prismic over WP.
The design isn't done, but we don't publish live from Prismic, so no wakkas.
=> add copyright holder to images (from prismic)

client/scss/base/_row.scss, client/scss/components/_captioned_image.scss, server/views/components/captioned-image/captioned-image.config.js, server/views/components/captioned-image/captioned-image.njk, server/views/components/main-media-work/main-media-work.njk, server/views/pages/article.njk, server/views/pages/work.njk
References #1116
🚑 Health
Limits the height of the work `main-media` image such that it covers maximum 95% of the viewport height (and shares this logic between the work page and where it was previously being used on the articles with `contentType` 'comic').
=> Limit height of image on work page (as with comic)

server/views/components/main-media-work/main-media-work.config.js
🐛 Bugfix  
Prevents `main-media-work` displaying in Cardigan as a standalone component.
=> Hide main media work in Cardigan

server/services/prismic-content.js
🐛 Bugfix  
Allows editors to see something that doesn't say "Invalid date".
=> add date.now for preview content from prismic

infra/terraform/templates/iam.tf
✨ Feature  
Provide visibility on experience team costs alongside platform team costs on the shared dashboard.
💻 
This change adds an extra role for `grafana` in order to reduce the scope of `grafana` access. 
In addition account owners will need to enable the IAM billing option described here: https://aws.amazon.com/blogs/security/dont-forget-to-enable-access-to-the-billing-console/
=> Delegate access for billing view to platform account

server/controllers/work.js, server/views/pages/work.njk
References https://github.com/wellcometrust/platform-api/issues/698
At present, trying to get an image from Loris that is larger than its original resolution returns a 404 and so we're getting broken images on some pages.
This fixes that by getting the original image size from the iiif API, so we don't request anything larger. Does mean another API call though :(, but probably ok for now
🐛 Bugfix  
This doesn't happen anymore:
This does:
=> Get original image size so we don't request images that are larger

server/controllers/content.js, server/routes/index.js, server/services/prismic-content.js
🐛 Bugfix 
The editorial team can preview `webcomics`.
Not massively elegant, but allows editorial to keep on keeping on.
There'll probably be some more abstractions as we go on.
=> add a way of previewing webcomics

client/scss/components/_input.scss, server/views/components/input/input.njk
If font size is less than 16px, [iOS will automatically zoom the field](https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone) . This fix has the added benefit of aligning the font size with the header input field (which is already larger than 16px).
Fixes #1245
🐛 Bugfix
=>  Fix input zoom in iOS

server/views/components/icon/icon.njk
=> Preventing NVDA reading empty links in footer

client/scss/components/_header.scss, server/controllers/work.js, server/views/components/input/input.njk, server/views/components/search-box/search-box.njk, server/views/components/works-search/works-search.njk, server/views/pages/search.njk
🐛 Bugfix  
Having two types of search is nonsense.
This just turns the search button into a link for the `beta` cohort.
=> remove two search boxes on beta search

server/services/prismic-content.js, server/views/components/captioned-image/captioned-image.njk, server/views/pages/article.njk
References #731 
🐛 Bugfix  
A bit of a hack for crediting images.
We'll be addressing this as a whole thing at some stage, so for now we just remove it from the featured image.
Also fixed the date saying "Invalid date" on preview.
=> hide copyright on comics

client/scss/components/_body_content.scss, client/scss/utilities/_root-scope-classes.scss, server/services/prismic-content.js, server/views/components/article-body/article-body.njk, server/views/components/list/list.njk
✨ Feature  
Allows editors to create a semantically meaningful image list, aka, listicle.
I have limited it to images, as we haven't had the requirement to do anything more.
Here's the model, which is also up for scrutiny.
Once #1242 is in, I can start adding content blocks to this repo, negating the need for the other.
=> Add image list as a content type

server/controllers/content.js, server/routes/index.js, server/services/prismic-content.js
🐛 Bugfix  
As much as I can see this is an abstraction, I'd probably like to bring it back in once we have answered the couple questions below.
Now using the same URLs for `/webcomics` and `/articles`.
This has two reasons:
* So we don't have to think about URIs just yet
* I can hijack Wordpresses email / RSS functionality until we figure out what to do with the followers on that platform.
=> Articles webcomics uri

server/views/components/input/input.njk, server/views/components/search/search.njk
🐛 Bugfix  
Enables more characters to fit on screen (e.g. 'Search image collections' placeholder text isn't cut off at 320px wide).
=> Decrease input font size at small breakpoint

client/js/components/content-slider.js, client/package.json
Fixes #1178
🐛 Bugfix  
Allows content-slider caption text to be selectable (Hammer was hijacking those events). Also shaves 20k off our JS.
=> Remove Hammer.js

client/scss/components/_search_box.scss, server/views/components/search-box/search-box.njk
🐛 Bugfix  
Improves the size/alignment of the search icon (button)
=> Improve search button size/alignment

server/controllers/work.js
Fixes #1287. Reverts #1240.
🚑 Health
Making less requests means search pages will be faster.
=> Don't look up the info.json when loading images on the search page.

client/scss/components/_scroll_to_info.scss
References #1141
🚑 Health
Removes the 3s wobbling animation from the info button in advance of A/B testing the info button's usefulness.
If it turns out to be useful/necessary, then a further A/B test of it with/without animation could be done.
=> Remove info button animation

server/controllers/work.js, server/views/components/image-iiif/image-iiif.njk
Closes #1289
✨ Feature 
Enables more accurate load testing of image search pages by using a feature flag to determine if images are requested from origin or CDN. 
The feature flag is currently enabled for the 'platformTeam' cohort, i.e. any page request sent with a cookie of WC_features_cohort = platformTeam, will have the flag enabled and receive images from the origin.
=> wrap iiif image requests in feature flag

server/views/pages/article.njk
🐛 Bugfix  
Prevents unnecessary markup (and associated styles) being added to the page when there isn't an author for an article
__Before:__
__After:__
=> Only display author markup if there's an author

server/views/templates/event.config.js, server/views/templates/exhibition.config.js
🐛 Bugfix  
Highlights the correct navigation link ('What's on') when the Event/Exhibition templates are viewed in Cardigan.
=> Highlight correct section in Cardigan for events/exhibitions templates

server/model/work.js, server/test/mocks/wellcomecollection-api.json, server/views/pages/search.njk, server/views/pages/work.njk
There’s a pending change to the Catalogue API which makes changes the data model to use "title" instead of "label" (https://github.com/wellcometrust/platform-api/issues/751). You can see what the new API will look like at https://api-stage.wellcomecollection.org/catalogue/v0/works
This patch prepares the Collection site for this change – now it can pick up a "title" or a "label" field. I’ve tested it against both the new and the old API, and behaves correctly in both cases.
When we flip the switch, this interim code will need to be removed, but this is good to go now.
~This patch flips the Collection site to use the updated field name, and I’ve tested it against the staging API.~
~We’ll need to make sure we both flip the switch at the same time, or the Collection site doesn't show any …
=> Rename 'label' to 'title' for results from the updated Catalogue API

client/js/components/copy-url.js
References #1312
🐛 Bugfix  
Only copies the url to the work, rather than the work + any other (e.g. query) parameters
=> Only copy origin and pathname from URL

server/model/work.js, server/views/pages/search.njk, server/views/pages/work.njk
Related: #1311, https://github.com/wellcometrust/platform-api/issues/751
The API has now flipped entirely to using "title", so we can remove this interim code.
=> Remove references to 'label'

infra/terraform/cloudfront/cloudfront.tf, server/middleware/features-cohort.js
✨ Feature  
Will help with getting worst case performance metrics for search in Speedtracker, by allowing us to request images from origin rather than CDN
=> Allow feature flags cohort to be passed as url parameter

client/scss/utilities/_root-scope-classes.scss, server/views/components/promo/promo.njk
Fixes #1184
✨ Feature  
Prevents titles from taking up too much space, enabling user to scan results quickly
=> Truncate text

server/services/prismic-content.js
🐛 Bugfix 
stops null appearing on the page, when the citation and source fields are empty
=> Only show quote footer if there is content for it

server/controllers/content.js
🚑 Health
Simplifies the code. We are now displaying articles/comics from prismic on Explore for all users, so no longer require the code to be wrapped in feature flags.  
N.B once this is merged we should also delete the 'webcomicsFromPrismic' and 'prismicArticlesOnExplore' flags in prismic.
=> Removed flags wrapping prismic content on explore

server/model/work.js, server/test/mocks/wellcomecollection-api.json
See https://github.com/wellcometrust/platform-api/issues/334
We’ve changed the way identifiers are represented in the API.
Before:
```json
"identifiers": [
{
"source": "Miro",
"name": "MiroID",
"value": "V0042826ER",
"type": "Identifier"
}
],
```
After:
```json
"identifiers": [
{
"identifierScheme": "miro-image-number",
"value": "V0042826ER",
"type": "Identifier"
}
],
```
The code that looks up identifiers for choosing images isn't affected by this change -- this just brings your models and examples into line with the new API.
=> Use the new identifierScheme in the API

server/config/index.js, server/middleware/set-cache-control.js
🚑 Health
Sets cache-control header to 30 mins for html pages, potentially speeding up users experience.
(Allowa different maxAges for different content types)
=> Add cache-control header for html docs

server/views/partials/analytics.njk
🚑 Health
The .async-hide style is being applied for Google Optimize, to ensure that users don't see the initial page content prior to it being modified by an experiment. However, this causes a noticeable delay in the rendering of the page.
Since we are only using Google Optimize to test the digital-story transporter, which appears way below the fold, this is pretty redundant and removing it will speed up page rendering.
In the future, if required, we could use the .async-hide class to more directly target page components, rather than hiding the whole page.
=> remove async-hide styles

server/content-model/content-blocks.js, server/services/exhibitions.js, server/views/templates/exhibition.config.js
🚑  Health
Uses correct (plural) naming convention for exhibitions content type.
=> Use plural 'exhibitions' (with updated type in Prismic)

infra/terraform/cloudfront/cloudfront.tf
Useful for when we pull it from Koa - but also using it in NGINX.
=> forward Host header from cloudfront

client/js/components/content-slider.js
Fixes #1353 
🐛  Bugfix  
Prevents slider controls from being hidden while they're still useful.
=> Don't hide slider controls when images fit in viewport

client/js/components/work-media-controls.js
🚑  Health
Prevents the 'return to results' and scroll-down-to-main controls from being hidden if they are under the cursor.
=> Don't hide controls when they're hovered

client/scss/components/_opening_hours.scss, client/scss/utilities/_root-scope-classes.scss, server/views/components/footer/footer.config.js, server/views/components/footer/footer.njk, server/views/components/opening-hours/opening-hours.config.js, server/views/components/opening-hours/opening-hours.njk, server/views/pages/exhibition.njk
✨ Feature  
Adds in-page opening times to the exhibition page ( aUX recommendation as a result of user research).
=> Add drawer containing opening hours to top of exhibition page

server/controllers/index.js, server/controllers/work.js, server/middleware/error.js, server/services/wellcomecollection-api.js, server/views/pages/error.njk
🐛 Bugfix  
404 when we should 404 - `catch`ing promises is no longer really necessary with `async`.
This just sends the API error to the client, which isn't great, but at least prevents other programatic errors further down the chain.
=> Error handling

server/views/components/open-graph/open-graph.njk, server/views/components/twitter-card/twitter-card.njk, server/views/pages/article.njk, server/views/pages/curated-lists.njk, server/views/pages/event.njk, server/views/pages/exhibition.njk, server/views/pages/list.njk, server/views/pages/search.njk, server/views/pages/work.njk
References #1310
🚑  Health
Adds Open Graph/Twitter card meta data to `work`, `event` and `exhibition` pages.
=> Update Open Graph/Twitter cards for works, events and exhibitions

client/scss/components/_captioned_image.scss
Fixes #1382
🐛  Bugfix  
Fixes image captions.
=> Inline caption paragraphs

server/controllers/work.js, server/views/components/promo/promo.njk, server/views/components/work-media/work-media.njk, server/views/pages/search.njk, server/views/pages/work.njk
Fixes #1376
✨ Feature 
Positions page at appropriate search result, when using 'back to results link' - so people can quickly pick up where they left off
=> Added item id to ‘back to results' link

nginx-proxy/nginx.conf
✨ Feature  
If we hit a 404 on `/articles`, `/events`, or `/exhibitions` - we `proxy_pass` to  V2.
=> fallback to v2 for 404 articles, exhibitions, and events

nginx-proxy/nginx.conf
🐛 Bugfix  
I forgot to actually send the site to prev, so we were hitting 404 for everything.
=> try to intercept 404 errors from prev.wc.org

cardigan/fractal-app.js, server/controllers/content.js, server/controllers/index.js, server/controllers/utils.js, server/controllers/work.js, server/middleware/error.js, server/model/page-config.js, server/views/pages/article.njk, server/views/pages/curated-lists.njk, server/views/pages/event.njk, server/views/pages/exhibition.njk, server/views/pages/list.njk, server/views/pages/search.njk, server/views/pages/work.njk, server/views/templates/event.config.js, server/views/templates/exhibition.config.js
🚑  Health
Gives every template access to the requested URL (i.e. the path being rendered) via the `pageConfig` object. Useful for e.g. consistently passing the shareable URL along with Twitter card and Open Graph data.
=> Give templates access to request URL via pageConfig object

infra/terraform/cloudfront/cloudfront.tf
I haven’t demoed or tried this – I don’t think I have access to your AWS account? But this is my best guess for what’s causing #1394, so hopefully resolves that (when applied).
=> Use the uri query parameter to distinguish cached URLs

server/app.js, server/config/index.js, server/controllers/work.js, server/package.json, server/pm2.yml, server/run.js, server/view/render.js, server/views/pages/work.njk, server/views/templates/work.config.js
Alternative to #1384
🚑 Health
By explicitly setting the path - it is no longer a contextual variable which could cause trouble with cache e.g. Someone hits the site using another request URL (the origin perhaps) - this could get cached and then served with the wrong domain to someone visiting from the normal domain.
I'd also like to use this as an opportunity to start using the root wc.org domain, this way we make sure we're getting all the SEO juice to the same place (#1387 #1388 #1389 helps with this).
@jennpb ^ in regards to this - it would be good to see if we can get the Editorial team to start sharing from the root too - let's chat.
=> explicitly set the root domain in config

server/views/pages/search.njk
This tweaks the social media preview on the root search page – where currently it says _A Wellcome Collection search for ''_, now it says _Explore 53,000 Artworks and Photos_. I saw this in Slack this afternoon and it was annoying me, so I changed it. Views for search result pages are unchanged.
Before:
After:
(I don’t feel strongly about the new wording, but it feels like an improvement on the current state of affairs.)
=> Tweak the social media preview for the root search page

nginx-proxy/nginx.conf
🐛 Bugfix  
Currently we force a `200` (my lack of understanding thought it would 200, then inherit the new location's code) - this will inherit whatever code v2 responds with.
=> Dont force 200

client/js/components/content-slider.js, client/scss/components/_slider__gallery.scss, client/scss/components/_slider__in-article.scss, client/scss/components/_slider__in-content.scss, client/scss/components/_slider__transporter.scss, server/views/pages/article.njk, server/views/pages/curated-lists.njk
🐛  Bugfix  
Currently, only the top half of '+more' links under images in galleries is clickable – the bottom half is obscured by the slider controls. This fixes that issue, by using a pre-existing helper class.
It has the side-benefit of aligning the controls beneath the transporter on the explore page correctly (at present they're too far to the left).
=> Slider controls

server/views/pages/work.njk
🐛 Bugfix  
Puts in missing design element
before:
after:
=> Added missing divider between Date and Lettering

server/views/components/header/header.njk, server/views/components/works-search/works-search.config.js
References #1372
🚑 Health
Removes unnecessary code. The header search will no longer be needed as a way to access the image search, once the images link is present.
N.B. Once deployed we should delete the searchWorks flag from Prismic.
=> remove works-search component and associated feature flag code

server/middleware/error.js
🚑 Health
There's not need to track 4xx errors, they're not fatal, and we've chosen to send them, so sentry isn't the place for them.
=> don't track 4xx errors in sentry

server/package.json, server/views/components/twitter-card/twitter-card.njk, server/views/pages/work.njk
Fixes #1420 
🐛 Bugfix  
Twitter doesn't consider a card valid without a description.
I'm passing the title in for now, but wonder if something more like, "one of 53,000 image to explore from the Wellcome Collection" <= @jennpb?
=> use title as description on twitter cards if description doesn't exist

server/services/prismic-content.js, server/views/components/article-body/article-body.njk
🎩 Content test
Adding subtitles to image lists as a test to see how editorial are using them.
The image lists are still a WIP, so the markup is too (although nicely with what we have I didn't need any more CSS).
=> allow subtitles on image lists

server/filters/get-tasl-markup.js, server/filters/index.js, server/model/license.js, server/model/picture.js, server/services/prismic-content.js, server/util/prismic-parser.js, server/views/components/captioned-image/captioned-image.njk, server/views/templates/article.config.js
References #1404 
✨ Feature  
🐛 Bugfix  
We can start attributing images correctly.
https://wiki.creativecommons.org/wiki/Best_practices_for_attribution#Title.2C_Author.2C_Source.2C_License
This is a hack, but it's one until Prismic decide on what they're going to do with this.
__with all information__
__without author__
__without copyright or source link__
=> get tasl from prismic

server/filters/convert-image-uri.js
🐛 Bugfix  
Loris won't serve gifs, so we're getting broken links. This makes sure we don't send gif image requests to loris
=> don’t get gifs from loris

infra/terraform/cloudfront/cloudfront.tf, nginx-proxy/nginx.conf
Adding some headers that _might_ be needed for Drupal to not send us in a loop when traffic is coming from CloudFront.
=> add headers to send to drupal to prevent https 301 loop

infra/terraform/cloudfront/cloudfront.tf, nginx-proxy/nginx.conf
Moving back to a more peeled back attempt at stoping Drupal redirect loop traffic.
I recon it's the fact that we had the `origin_protocol_policy` set to `http` - so I'm going to try that in isolation.
=> Https throughout

server/views/components/input/input.njk
Fixes #1376
✨ Feature  
🐛 Bugfix  
As oer @jamesgorrie 's suggestion, this takes care of the issue in Chrome, where autofocus overrides the link target. 
Assumes we only want autofocus when the search input is empty, which seems reasonable.
=> only add autofocus attribute if there is no query in the search box

nginx-proxy/nginx.conf
✨ Feature  
For /exhibitions/.* we will go to v1 and fallback to v2.
This to get around the fact that `/exhibitions/say/wat` is invalid, but returns a 200, which unfortunately also includes https://wellcomecollection.org/exhibitions/WZwh4ioAAJ3usf86
=> Default to v2 and fallback to v1 for /exhibitions urls

server/services/prismic-content.js
✨ Feature
Allows us to publish content that isn't automatically listed.
=> don't include delisted articles in lists

server/util/flag-status.js, server/views/templates/article.config.js, server/views/templates/exhibition.config.js
🐛 Bugfix  
Makes articles and exhibition templates render in Cardigan again
=> Cardigan fixes

server/filters/convert-image-uri.js
In the vein of #1429.
Right now, you’re asking Loris for a JPEG regardless of what the source format is, which gets you URLs like this: https://iiif.wellcomecollection.org/image/wordpress:2017/04/head-apaprt-from-body-1.png/full/282,/0/default.jpg
Following that URL will give you a 500 error  and a sad message from Loris:
> Server Side Error: cannot write mode RGBA as JPEG 
>
> This is likely a permissions problem, though it's possible that there was a problem with the source file (/mnt/loris/resolver_cache/wordpress/fb/f26/a4f/a92/6bf/c3b/958/a04/e7f/313/3de/loris_cache.png). (500)
You get a broken link, the user doesn't see their image, we get an alarm from Loris. Everybody is sad. 😭 
If you ask Loris to convert PNG to PNG, all it has to do is a resize, which works fine (e.g. …
=> Ask Loris for PNG images if the source is PNG

server/views/components/copy-url/copy-url.njk
Fixes #1446 
🐛  Bugfix  
Makes it clearer that 'copy link' is clickable.
=> Use cursor: pointer for copy url link

client/scss/components/_promo.scss, client/scss/utilities/_root-scope-classes.scss, server/views/components/pagination/pagination.njk, server/views/components/promo/promo.njk, server/views/components/series-container/series-container.njk, server/views/pages/curated-lists.njk, server/views/pages/list.njk, server/views/pages/search.njk, server/views/templates/article.njk
References #1442 and #606 
🐛  Bugfix  
🚑  Health
Corrects the a11y contrast issues referenced directly in #1442 (uses 'charcoal' for the promo 'type' label and the 'showing x results for y' text.
Also removes some unused css selectors.
This PR doesn't address the remaining issue in #606 of white-text-on-turquoise-background.
=> A11y font colours

server/controllers/work.js
🐛 Bugfix    
🚑 Health
This prepares for an API change (see below) that would break our works page.
"We’re planning to roll out a change in the next day or so that adds a second identifier to the `identifiers` field in API responses (specifically, the _sierra-system-number_). Previously it just contained _miro-image-number_." - @alexwlchan
=> Get the miro id, when there is more than one identifier from API

client/scss/components/_promo.scss
References #1442
🐛  Bugfix  
Fixes a11y font colour issue for promo description on cream bg
=> Change promo descrption font colour to charcoal

client/js/tracking.js, client/libs/ga-scroll-depth.js, server/views/partials/analytics.njk
Fixes #1464
✨ Feature 
Gives cleaner usage data through Google Analytics, by allowing us to exclude staff use while working from home/on the road.
If someone goes to  wellcomecollection.org/flags and joins the wellcomeUser cohort - analytics data won't be sent
=> GA exclusion

server/filters/get-breakpoint.js
🐛  Bugfix
The `getBreakpoints` filter is pointing at a file that isn't deployed wholesale (it is packaged as a node module instead). This PR points the filter to the node module version.
=> Use config node module

server/views/components/license/license.njk
Fixes #1404
🐛  Bugfix  
Stops license looking broken on webcomics (puts the description and the CC info/icons on separate lines – consistent with work page).
=> Display license description and CC info on separate lines

server/content-model/content-blocks.js, server/services/exhibitions.js, server/views/pages/exhibition.njk
References #1428
✨  Feature  
Adds location and provides more information around availability of magnifying glasses/sheets
=> Update accessibility info with location

server/filters/convert-image-uri.js
Fixes #1483
🐛  Bugfix  
Fixes full-size IIIF image downloads.
=> Don't add comma to URL for full iiif images

client/scss/utilities/_root-scope-classes.scss, server/views/pages/exhibition.njk, server/views/templates/exhibition.njk
References #1472 
✨  Feature  
Provides a link (tag) to all exhibitions from the exhibition page.
=> Add exhibition tag to exhibition page

client/scss/components/_exhibition_hero.scss, server/views/pages/exhibition.njk
References #1466
🚑  Health
Keeps the copy over the image whenever it's displayed at 16:9 (from the medium breakpoint upwards). This means there only need to be two copy/image lock-ups. There would have needed to be three if the title was below the image between the medium and large breakpoints (~= tablet).
=> Keep text over image from medium breakpoint up

server/views/partials/monitoring.njk
We know this happens, we don't seem to care, so I want to remove it from sentry so we can start fixing things in there.
=> ignore hotjar errors

nginx-proxy/nginx.conf
🚑 Health
Push all `next.` traffic to root domain.
This should hopefully help with duplicate content across Google.
=> redirect next. to root URL

server/filters/convert-image-uri.js, server/views/components/image/image.njk, server/views/components/picture/picture.njk
Closes #1136
🚑 Health
We've been using iiif images from Loris for a while now, but it's been wrapped in a feature flag/imgix safety blanket. Platform team is happy for us to rely on Loris now, so removing imgix related stuff.
=> remove imgix completely and related feature flag code

client/scss/components/_exhibition_hero.scss
🐛  Bugfix  
Prevents the flash of orange when the exhibition page loads
=> Remove orange background from the exhibition hero

infra/terraform/cloudfront/cloudfront.tf, nginx-proxy/nginx.conf, server/controllers/content.js, server/routes/index.js
✨ Feature  
This allows us to split traffic between V1 and V2.
At first we're doing it for `/graphicdesign` only (potentially not, maybe `/visit-us`).
the process is:
* Assign a version, 1 or 2, to a user on visit
* if you land on a designated URL, `/graphicdesign` form example, you get stuck in your group.
* We can then measure through Google Analytics.
@jennpb @hthair I'd like to discuss which method, this or optimise, would be better for testing v1 vs v2 content.
=> add version 1 vs 2 testing to nginx

server/views/pages/exhibition.njk
🐛  Bugfix  
Makes the exhibition page promos scroll nicely on iOS
=> Make exhibition promos momentum-scrolly on iOS

client/scss/components/_is_preview.scss, client/scss/non-critical.scss, server/controllers/content.js, server/services/prismic-content.js, server/views/layout/default.njk
🚑  Health
Alerts content editors to the fact that alt text hasn't been added to images by displaying them on a disgusting background.
=> Add manky background to non-alt-texted images in previews

server/content-model/content-blocks.js, server/content-model/event.js, server/controllers/content.js, server/routes/index.js, server/services/events.js, server/services/exhibitions.js, server/services/prismic-content.js
References #1532 wellcometrust/wellcomecollection-content-model/pull/12
🚑 Health
Getting a model together which takes the design and events team feedback into account.
This is by no means anything to do with the display to the user, but next we can plug it into the [cardigan template](https://cardigan.wellcomecollection.org/components/detail/event-template.html)
I'm going to wait till I've done some work on the Exhibition type and then work this flow thing out so we can't push broken models.
=> Event model fixup

server/services/wellcomecollection-api.js, server/test/mocks/wellcomecollection-api.json
Related: https://github.com/wellcometrust/platform/issues/582
🚑 Health
The V1 API comes with shiny guarantees of uptime and us not making backward-compatible changes to the data model. This is the “production-ready” Catalogue API.
Currently we’re running both v0 and v1, so it should be possible to deploy this at any time without disruption to the Collection site. But once it’s done, we plan to shut down the v0 API – so please tell us when you’ve deployed this patch. :-)
I’ve tested this change locally.
=> Switch to using the v1 Catalogue API

server/controllers/content.js, server/services/prismic-content.js
🐛 Bugfix  
Removing all the junk logic from when we had to deal with WP / Prismic content on `/explore`.
Should hopefully speed the page up.
=> defer ordering of articles to API query and remove WP articles from explore

server/routes/index.js
🐛 Bugfix  
We're getting `500` errors from urls like `/exhibitionsandevents/events/WTX053590.htm`. This is because the current route handler allows for an optional `preview` segment in the url, but that segment is set as a variable (`:preview`) rather than the actual word, 'preview'.
=> Use 'preview' verbatim in route handler

client/scss/components/_captioned_image.scss, server/views/components/captioned-image/captioned-image.njk
Fixes #1563
🐛 Bugfix  
Ensures hero image copyright info is visible. Not proposing that this should be how it ends up, but it's better than what we've got.
=> Move article hero copyright to top of image

server/middleware/set-cache-control.js
✨ Feature  
Prevents browsers from caching preview pages, so that previews update without the need to refresh
=> If viewing a preview then prevent the browser from caching it

server/controllers/content.js
🐛 Bugfix  
If the event isn't defined, this errors.
I hate not having types.
=> only reference event once we know it exists

server/filters/get-tasl-markup.js, server/services/prismic-content.js
🐛 Bugfix  
Trims off excess whitespace between `|` characters in the TASL. This prevents unwanted gaps before any punctuation in the TASL information, and ensures the correct license information is displayed.
=> Trim pieces of TASL to prevent unwanted space/make sure license renders

server/views/components/article-body/article-body.njk
🐛  Bugfix  
Displays TASL information on standalone images
=> Show copyright on standalone images

server/views/components/find-us/find-us.njk
🐛 Bugfix  
Happy to have a chat about what we do in the future.
Mapbox is a great service, and doesn't have loads and loads of tracking when you serve their files.
For now we cache the tile in Prismic, this is not against their [TOS](https://www.mapbox.com/tos/).
=> serve mapbox tile from prismic

nginx-proxy/nginx.conf, server/controllers/content.js, server/controllers/index.js, server/routes/index.js, server/services/prismic-content.js, server/views/pages/list.njk
🚑 Health
Adding the ability to list all of our Prismic articles and also make sure that we link through to our WP content.
The thinking here is that having a link, for SEO more than anything given the analytics, should be linking through to our new articles with an option to link through to the WP articles until migration.
I'd like to demo to @jennpb, but here's a screenshot for now:
Analytics over 3 months:
=> Articles archive

server/app.js, server/config/index.js, server/middleware/error.js
🐛 Bugfix  
I noticed sentry errors weren't coming through.
I've created a new sentry project called `node-app` (I'd like to standardise these names).
Before we were making koa treat 404s and 500s the same, which made it a little hard to fathom as to when errors etc would beacon.
Now, on application error, we beacon, else we wait for no response from the other middleware, and respond with a 404 page.
=> separate 500 and 404 error handline

server/services/prismic-content.js
🚑 Health
Given the copyright info is already a pain to insert, let's not 500 if it's done incorrectly.
=> don't 500 on copyright error

content-model/articles.json, server/services/prismic-content.js, server/views/components/soundcloud-embed/soundcloud-embed.njk
✨ Feature  
Third time lucky. If the track is private, a secret is added to the SoundCloud iframe src, so we need the whole thing rather than just the ID.
=> Use the whole iframe src (enables private embeds)

content-model/articles.json, server/services/prismic-content.js
✨ Feature  
Allows us to display iframed content in the same way as editorial images – full grid width, or in the right-hand rail.
=> Allow iframe to be supporting/standalone

infra/terraform/container-definitions.json
I still haven't quite figured out the math.
Either way, this gives us enough room to deploy tasks efficiently.
=> drop memory to allow for faster deploys

client/scss/components/_back-to-top.scss, client/scss/components/_buttons.scss, client/scss/components/_captioned_image.scss, client/scss/components/_work_media.scss, client/scss/critical.scss, client/scss/non-critical.scss, client/scss/utilities/_root-scope-classes.scss, config/colors.js, server/views/components/back-to-top/back-to-top.njk, server/views/components/button-button/button-button.njk, server/views/components/button-link/button-link.config.js, server/views/components/button-link/button-link.njk, server/views/components/captioned-image/captioned-image.njk, server/views/components/scroll-to-info/scroll-to-info.njk, server/views/components/work-media/work-media.njk
Closes #1491
✨ Feature  
Usability testing demonstrated that the black horizontal transparency on a /works/ viewing area gets in the way of reading any of the text at the top and bottom of the image. We now only add a background to controls themselves.
before:
after: 
- [-] Structured data tested: https://search.google.com/structured-data/testing-tool 
- [-] Works without JS in the client
- [-] Relevant tracking/monitoring has been considered
=> Work image hover

server/views/components/captioned-image/captioned-image.njk
🐛 Bugfix  
Puts the dark background back on in-page info icons (so they can be seen on light images).
=> Add background to captioned image body icons

server/services/prismic-parsers.js
🐛 Bugfix  
The `asText` has a check in for this, so stops the 500.
=> use asText on exhibitions promo list

server/util/json-ld.js, server/views/pages/exhibition.njk
🐛 Bugfix  
Allows editors to preview exhibitions without `featuredImages`
=> render exhibition pages without featured images

content-model/webcomics.json
🐛 Bugfix  
Use the series structure that articles use.
[Annoyingly, because of the lack of an `OR` predicate, we can't have webcomics on our series page anyway](
https://github.com/wellcometrust/wellcomecollection.org/blob/master/server/services/prismic.js#L131).
Definitely not a smart move to making webcomics a separate type.
Now, if only the import / export tool worked properly... (Prismic 🤦‍♂️).
=> do the series properly for webcomics

server/views/pages/exhibition.njk
🐛 Bugfix  
Stops the title box from bleeding to the edge of the screen. Keeps the wobbly line at every breakpoint.
=> Fix exhibition hero title box padding regression

server/views/pages/exhibition.njk
🐛 Bugfix  
Corrects exhibition related content grid at the medium breakpoint (aligns it with the body content).
=> Align related exhibition content at medium bp

router/terraform/alb.tf, router/terraform/asg.tf, router/terraform/cloudfront.tf, router/terraform/locals.tf, router/terraform/s3.tf, router/terraform/services.tf, router/terraform/terraform.tf, router/terraform/userdata.tf
References #1616 
✨ Feature  
Puts a CloudFront dist in front of the new router service.
It's a copy / paste job and we can refine it as we move some parts (namely the no-cache routes) into their relevant places.
=> Router cloudfront

client/js/components/image-viewer.js, client/scss/components/_image_viewer.scss
References #1125
✨ Feature  
Shows viewer within the browser if fullscreen is not supported,  e.g. iOS
=> Show viewer in webpage if fullscreen not supported

server/data/series.js, server/services/prismic-parsers.js
🐛 Bugfix  
Displays the correct series part on digital stories from Prismic.
=> Get the correct series position

server/services/prismic-body-parser.js, server/views/components/iframed-video/iframed-video.njk
✨ Feature  
🐛 Bugfix  
Allows Vimeo videos to show up on the front end. Also fixes a regression where YouTube videos wouldn't display because of missing classes on the iframe/container.
=> Treat Vimeo the same way as YouTube

content-model/articles.json, server/services/prismic-body-parser.js, server/views/components/article-body/article-body.njk
✨ Feature  
Allows editorial team to add supporting (sticky) videos in the right hand rail, or 'standalone' videos that span the full grid width
=> Allow supporting/standalone YouTube/Vimeo videos

nginx-proxy/nginx.conf, router/nginx.conf
References #1616
🚑 Health
It seems when we pass the wellcomecollection.org host to the Drupal NGXIN conf, we hit something that is not transparent, so we can't tell what it's doing.
This makes sure our test / prod envs are the same.
I ran the test on the nut / router first, so we should be good.
=> pass prev. as host to drupal site

client/js/components/image-viewer.js, server/services/prismic-parsers.js
🐛 Bugfix  
Deals with the fact that people might partially add access option data.
It is a bit hard to fathom what is required / not required, but for preview, nothing should be required as you might want to check impartial data.
=> deal with empty access linked documents

nginx-proxy/nginx.conf, router/nginx.conf
🚑 Health
Allows URIs to go to V2.
Next is to remove all routing from the `nginx-router` attached to that should be the router's job.
=> add management and download URIs to pass to v2

router/nginx.conf
🐛 Bugfix  
Turns out I need to work on my Nginx Regex.
This helps: http://nginx.viraptor.info/
Will stop these 404ing:
https://wellcomecollection.org/articles/tetanus-cut-finger
=> better regexp in nginx for /articles

server/views/layout/default.njk
🐛 Bugfix  
Noticed it didn't show in Firefox.
Now it does.
Still doesn't make it much easier to know it's Wellcome Collection unless I know the icon.
=> add favicon

router/nginx.conf
🐛 Bugfix  
stops /flags from 404ing
=> update rules for nginx so /flags goes to V2

router/nginx.conf
🐛 Bugfix  
Caters for and tested on Drupal, Wordpress and Prismic article paths:
https://wellcomecollection.org/articles/tetanus-cut-finger
https://wellcomecollection.org/articles/museuminstaswap
https://wellcomecollection.org/articles/WcppcigAAJwPEevo
(Currently WP articles don't work)
=> use routing that deal with all 3 of our types of articles

server/data/series.js
🐛 Bugfix
Quick fix so that 'Theriac: an ancient brand?' articles shows the correct position in series.
Will look into long term fix next
=> Correct title in series json

server/controllers/work.js, server/routes/index.js, server/services/prismic-parsers.js, server/services/prismic.js
🐛 Bugfix
Puts missing indicator bars back on transporter
=> Part indicators back on transporter

content-model/exhibitions.json
🐛 Bugfix  
Stops people putting the summary in the subtitle box.
=> label subtitle correctly

.circleci/config.yml
Turns out node8's `install file:` creates a symlink, and doesn't actually copy the files over.
This is an interim solution, we can either look at moving backwards and using something like [`install-local`](https://github.com/nicojs/node-install-local) or start thinking about how to manage inter-project dependencies.
We have the problem with the coupling of the client / server with the `js/css-assets` which I hope to solve by making `client` it's own app.
This also points out that we should probably running the tests in our docker containers.
=> revert to node 6 for build

server/services/prismic-parsers.js
🐛 Bugfix  
At the moment we're returning nothing, making content editors believe that it's broken.
My fear now is that they will not look behind the show / hide copyright button, leaving broken copyright info.
Thoughts? Show copyright all the time? Show it on;y if it's broken?
=> return copyright if it's not set correctly

client/scss/utilities/_root-scope-classes.scss, client/scss/utilities/_variables.scss, server/views/components/tags/tags.config.js, server/views/components/tags/tags.njk, server/views/pages/search.njk, server/views/templates/exhibition.config.js
🐛 Bugfix  
Makes the tags more accessible by giving a visual change on hover/focus. Tag colour is not configurable (for now). They're black and elf-green on hover.
=> Make all tags black; link tags hover to elf-green

client/scss/components/_footer_nav.scss, client/scss/utilities/_root-scope-classes.scss, server/views/components/footer-nav/footer-nav.njk, server/views/components/footer/footer.njk
FIxes #720
🐛 Bugfix
`visibility: hidden` is hidden from screenreaders, which is great, as the SVG has a title.
Although I do wonder what the heading adds to screenreader users in general?
=> align footer content

server/views/pages/article.njk
Fixes #1771
🐛 Bugfix  
Removes excess padding above author byline.
=> Reduce padding above author block on article page

server/views/components/tags/tags.njk
🐛 Bugfix
Makes tags less zingy when they're on a dark background.
=> Use black instead of white for tag border to be less zingy

server/pm2.yml
Restarts PM2 every 6 hours.
I would have loved to have had this on CPU usage, but there is no such option.
Hopefully this will wedge it until we get to the bottom of the solution and will stop us having to be on support.
=> restart PM2 on cron

server/package.json
Allows us to use the Chrome inspector for nodejs.
=> add inspect to node JS command app:dev

.circleci/config.yml, build-cardigan.sh, client/terraform/terraform.tf, shared-infra/terraform/https-s3-website/cloudfront.tf
Creating a bucket / CF dist that we can send assets from.
This should stop us having to serve static assets through Koa.
- ~Bad idea?~
=> add i.wc.org for static assets

router/terraform/cloudfront.tf
🚑 Health
Allows us to redirect  wellcome images traffic to the router on cloudfront
=> Add wellcome images domains to router cloudfront

.circleci/config.yml
Realised we weren't saving the cache of the `node_modules` leading to slow builds.
This should speed stuff up.
=> checksum on actual file in circle

server/middleware/error.js
🚑 Health
They make a noise.
We can track these in webmaster tools and GA.
=> Don't throw 404s to sentry

Dockerfile, server/package.json
While looking through the processor use on the docker containers, I found this:
That's near 100% - which we don't want.
This might help but not jumping through loads of hoops to get our app running.
=> remove npm script for running app in prod

server/services/prismic-parsers.js
🐛 Bugfix  
Prismic can send us empty html elements, and we conditionally show/hide UI based on whether certain bits of content exist. An empty element can cause e.g. the caption photo icon to appear below a picture even if the caption is empty. This prevents this from happening by checking that at least one piece of `text` from the content to be passed to `asHtml` is non-empty.
=> Check for non-empty html from Prismic

router/nginx.conf
🚑 Health
Seeing redirected urls of the form '/ixbin/hixclient.exe?MIROPAC=M0003688' showing up in analytics.
At present these will just go to /works. This addition will redirect such urls to a search for the miro number instead, which is probably more relevant
=> added another redirect rule

server/views/pages/work.njk
Was broken now fixed.
@hthair note that we can't rely on the numbers for this* until we merge.
* This being the number of clicks on the small download button.
=> small download tracking fix

server/filters/get-hashed-file.js
Blast it - don't know how this slipped through - not really a test I can write for it either.
=> use the filepath when useing hashedAsset helper

.circleci/config.yml
As the files are copied to the `dist` folder on server build, running the prod config before doesn't get carried over.
The order is now:
* Build prod-config into overrides
* Build all of that in .dist
* Run app from .dist
=> build prod config before the server build

.circleci/config.yml
A new order:
* Build client, create asset hash
* Take those hashes, stick them into the server overrides
* Build server with the assetHashes and prod overrides
=> build in the right order to get assetshashes in

router/terraform/cloudfront.tf
Allows the MIRO args through the cache.
=> allow MIRO args through cache for redirects

client/scss/components/_work_media.scss, server/views/components/work-media/work-media.njk
Seems, after trolling through the internet explorer bugs and features, this is the Goldilocks combination to get `max-width` / `width: auto` / and `flex-center` working.
Tested in IE / Firefox / Safari / Chrome.
Related: #1304
=> fix the works image ratio in IE

server/views/pages/event.njk
While playing around with WeCo Bot realised the image wasn't coming through.
We should have a chat about whether to use the promo or the main image.
=> use featured image for events twitter card

server/views/components/open-graph/open-graph.njk
https://stackoverflow.com/questions/25100917/showing-thumbnail-for-link-in-whatsapp-ogimage-meta-tag-doesnt-work
No idea why. Tested it by sending all my friends ngrok links.
They were satisfied.
=> add itemprop to og:image for what's app

server/views/components/open-graph/open-graph.njk
I can't see why it was there is the first place.
I tested across content types, and they all link correctly/
=> Don't repeat the URL in og:url

router/nginx.conf
We're creating quite a lot of noise and unnecessary strain on the server for articles that exist on v1.
We should go through and find these, but for now, I'd like to look for them on v1 first, then fallback to v2.
As `/articles/W(REST_OF_ID)` get's picked up earlier, this only affects Wordpress articles.
=> 404 on v1 first, then fall back to v2

server/controllers/content.js, server/model/page-config.js
References #1823 
This will return as a comma separated list of series attached to an article, with it's ID attached to ensure uniqueness (in the case of Wordpress articles the slug).
e.g.
`Memory objects:WdJB3CcAAIE-RlQp,The Outsiders:the-outsiders`.
@hthair would this be god for you to answer the question of how a series is performing via GA?
=> track series across WP and Prismic content

server/services/prismic-body-parser.js
Realised that some videos weren't embedding due to this.
It's not a great solution still... but hey ho.
=> update youtube embed regex to contain potential ID chars

server/routes/index.js, server/views/pages/exhibition.njk
Annoyingly following a terrible pattern as the `/download` path is hanging.
=> use target blank on exhibition downloads

client/scss/components/_work_media.scss
🐛 Bugfix  
Removes excess padding around image, increasing the chances of it being flush with the charcoal background (the image has a max-width of 800px).
=> Remove work image padding

server/filters/get-license-info.js
It's what we get from the API - so what we should use.
=> use cc-0 over cc0

server/views/pages/exhibition.njk
Perhaps shining some light on what they're used for.
As a tip off, I heard two people asking if the items would be on the website while in the exhibition.
If @jennpb's happy for this to go in, it's inactive in 'otjar, so we can merge and refine the copy, then activate it.
=> add 'otjar poll when someone downloads the exhibition texts

.circleci/config.yml
* Use `package-lock` as key as it's more accurate
* Remove the second cache lookup, it was acting unexpectedly, and we don't need it.
=> remove fallback cache keys to see what happens

client/gulpfile.js, client/package-lock.json, client/package.json, server/views/pages/exhibition.njk
Old file: 324kb
New file: 323kb
Webpack 3 has some new features which might help us get this down (it's quite heavy).
Updated the watch JS to just compile, as we don't reference the hashed version on dev leading to a quick dev cycle.
=> New webpack

client/scss/components/_footer.scss
🐛 Bugfix  
Stops the lower footer links breaking at the widest breakpoint – with the addition of the 'developers' link, there are too many to make it a sensible thing to try and do (and the design works without it).
=> Don't change bottom footer link layout at xlarge

server/views/components/work-drawer/work-drawer.njk, server/views/pages/work.njk
Closes #1854
🚑 Health
Improves layout/labelling of information on the work pages
=> Works source order

client/js/tracking.js, server/model/page-config.js
Fixes #1843 
🐛 Bugfix  
Prevents external links that _should_ open in a new tab or window from opening in both the current and the new windows (e.g. links with `target="_blank"` or `ctrl`/`⌘`-clicked links) as a result of our GA setup.
This prevents GA from running the `hitCallback` function if we decide you've opened a new tab.
It's a bit of a blunt instrument but I can't think of any real negatives.
=> Target blank analytics

.circleci/config.yml, exhibitions/app/package.json, exhibitions/app/webpack.config.js, exhibitions/app/yarn.lock
Makes the dependency more explicit, instead of relying on the client app to have _potentially_ run before.
Happy to leave the client gulp one in for dev.
=> compile sass in requiring app

node-docker/Dockerfile
I thing this might fix the build, as the containers can't find the docker client.
=> add docker client to /usr/local/bin

server/package.json, server/services/interval-cache.js, server/view/render.js, server/yarn.lock
My bad - new version of interval cache needs `.start()`.
We should also remove having GA in a flag if we can.
=> start interval cache

exhibitions/app/setup-app.js, server/controllers/content.js
Once we get to the events we can come up with a nicer way to do this, but seems sensible for now.
=> move exhibitions preview to exhibitions service

client/js/components/async-content.js
Allows for more than one async `js-numbered-list-transporter` per page.
=> Target the correct element when adding async transporter

events/app/views/pages/events.njk, exhibitions/app/views/pages/exhibitions.njk, server/views/components/list-header/list-header.njk
References #1897. Closes #1893
Adds the copy in #1893 to the events/exhibitions listing pages' meta-descriptions. Also adds the copy for the exhibition to the `list-header` component on the `/exhibitions` page (as specified in #1897).
=> Exhibitions meta description

exhibitions/app/controllers.js, exhibitions/app/routes.js
`/exhibitions` isn't working, and we don't support preview on lists yet - so getting rid of it.
=> fix exhibition routes to be consistent with others

client/js/components/eventbrite-ticket-button.js, eventbrite/terraform/iam.tf, eventbrite/terraform/service.tf, eventbrite/terraform/terraform.tf, router/nginx.conf
Couple of tweaks to make sure the service works.
The terraform work was because we're using v3 of the wellcometrust/terraform-modules.
The router was to allow the request to go through to v2.
=> Eventbrite infra update

exhibitions/app/views/pages/exhibition.njk
=> remove double statement of permanancy of exhibition

prismic-model/exhibitions.json, server/content-model/exhibition.js, server/services/prismic-parsers.js, server/services/prismic.js
* Force 16:9 images for exhibition promos.
* Move over to using promo for featured content on exhibitions
=> use promo image for exhibitions

client/scss/components/_tags.scss
=> Fix firefox alignment bug

server/views/components/twitter-card/twitter-card.njk
🐛 Bugfix 
🚑 Health
Reduces the size of the image being used for twitter cards to the recommended size (https://business.twitter.com/en/help/campaign-setup/advertiser-card-specifications.html)
=> Changed image path to 800px version

exhibitions/terraform/services.tf
Allows the catching of `/exhibitions`
=> catch all exhibitions in path_pattern of exhibition service

exhibitions/app/views/components/exhibition-promo/exhibition-promo.njk, exhibitions/app/views/pages/exhibition.njk
Uses en-dashes between dates on exhibition pages and promos.
=> Use en-dashes without surrounding space for date ranges

server/views/layout/default.njk, server/views/pages/search.njk, server/views/pages/work.njk
Smaller banner; moved above heading; not shown on works pages.
=> Update seasonal info banner to not show on works

client/js/components/truncate-text.js, server/views/components/captioned-image/captioned-image.njk
Turns out you could be 3-5 characters out because of the ellipsis itself.
But, it's not an exact science either, I have found 1 edge case where if you are 1 `i` extra, the text won't be ellipsised, but will show the control. Better this though, whereas before you weren't getting the control, and you couldn't see the text.
I'd really like to start looking at why we hide all this content, if editorial has put the effort in to explain something, why do we hide it? For this I have added tracking to the control.
=> use a more accurate calc to see if text has been ellipsisised

prismic-model/exhibitions.json
We don't use it in the template anymore - this came up in the content meeting too.
=> remove featured image from exhibitions model

server/controllers/content.js
We're running off of `preview.wellcomecollection.org` - so having the longer time won't conflict with anything being viewed on wellcomecollection.org.
I was going to work on how we chose the preview API - but from Sadek @ Prismic:
"sharing previews is something we’ll most probably be working on next".
Fixes #1974 
Fixes #1973
=> make preview cache a day

server/filters/get-license-info.js, server/views/pages/work.njk
Addresses 2/3rds of #1981. Specifically:
* CC BY-NC-ND licensed images now have human-readable text;
* "Licence information" is correctly spelt, with the British variant of "licen[cs]e".
I wasn’t sure exactly what to do about the extra space/full stop, so I decided to leave that for now.
=> Bugfixes for Licence information text

.circleci/config.yml, build/Dockerfile_webapp, node-docker/Dockerfile, node-docker/docker-compose.yml
Tidy up the circle build a wee bit by using their [preconfigured node image](https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/node/images/8.9.3/Dockerfile), which basically just installs Docker and a few other bits.
This will make it clearer and simpler to add a new service.
=> Use circleci node containers

.circleci/config.yml
As we need to be root to run the specific commands.
Perhaps we could build another one off the circleci builds, but for the weekend this will do 🍾
=> use generic node containers to deploy AWS apps

server/controllers/work.js
Must have slipped through.
I'd like to find out more why this is useful, and also how we can be sure to test this stuff.
=> add category to works search analytics

events/app/views/pages/event.njk
As per the wireframes.
We show either `event.format.description` or `accessOptions.description`.
Not sure it should be either or, and the model starts to fall apart when we apply this to educational events - but this is just a UI fix for now.
=> use proper headings when giving more info on event

client/js/components/gif-video.js, client/scss/components/_captioned_image.scss, client/scss/components/_gif_video.scss, client/scss/components/_tasl.scss, client/scss/critical.scss, prismic-model/articles.json, server/services/prismic-body-parser.js, server/views/components/article-body/article-body.njk, server/views/components/captioned-image/captioned-image.njk, server/views/components/gif-video/gif-video.njk, server/views/components/tasl/tasl.config.js, server/views/components/tasl/tasl.njk
Closes #1991 
Allows content editors to add movies-that-behave-like-gifs to articles.
=> Add gif video from Prismic

server/filters/get-tasl-markup.js
=> Remove 'by' from TASL

prismic-model/webcomic-series.json, prismic-model/webcomics.json, server/controllers/content.js, server/routes/index.js, server/services/prismic.js
As the idea of a series becomes specific to type (Event series, article series), it feels like webcomics should follow suit.
This will also allow us to have a page that points to the Body Squabbles (and future webcomics) as a corpus.
=> Webcomics series

server/filters/prismic.js, server/services/prismic-body-parser.js, server/services/prismic-parsers.js
Allows users to add internal links to Prismic content.
Way nicer and easier for the editor and stops us copy / pasting links and running into sharing preview link problems.
=> add linkResolvers to allow linking of prismic=>prismic content

prismic-model/webcomics.json
As it's not needed in webcomic-series.
=> remove position in series from webcomic series

client/scss/components/_body_content.scss, client/scss/components/_gif_video.scss
Closes #2017
It's not clear to me what the `.author + .article &:first-child` selector should be doing, but whatever it is, I don't think it's doing it correctly. All items in the right-hand-rail are currently being negatively margined up by 30px, causing potential overlap when there's a lot of stuff in the rail.
I think the safest approach is to remove the selector for now.
=> Remove faulty selector

server/content-model/exhibition.js, server/filters/format-date.js, server/services/prismic-parsers.js
We could make the type of the fields `Date`s - but it feels like we might lock ourselves into something, and I have very rarely seen a place where a Date is better than a DateTime.
A test is hard to write as this logic is on the template side, where we don't have tests.
Fixes #2019
=> make exhibition date range span from beginning - end of respective dates

server/services/prismic-parsers.js
Stops us showing "Invalid date"
https://wellcomecollection.org/exhibitions/Weoe4SQAAKJwjcDC
=> correctly parse nullable dates in exhibitions

events/app/views/pages/event.njk, prismic-model/events.json, server/content-model/events.js, server/services/prismic-parsers.js
Some events need a place to put in specific booking information e.g. School events that follows no pattern, but is very important.
This allows them to do that.
=> add generic booking info to events

events/app/controllers.js, server/services/prismic.js
Let's keep it tidy from the get go.
No trailing slashes (although they will work).
=> remove the training slash from what-on

events/app/views/pages/event.njk, server/services/prismic-parsers.js
Drop in isn't really a booking type, let's not pretend it is.
We don't really know if the wording actually works for people either, so this just decouples it from our booking logic.
=> have drop in as it's own thing

server/services/prismic.js
Default is 20 and the number of events was pushing the exhibitions from the returned results
Might have to look at dynamic loading in the future, but works for now.
🐛 Bugfix
=> Increased page size to 100

server/services/prismic.js
It'll help with the installation work.
Also, it makes sense to have expected behaviour.
=> Don't show delisted items universally

client/scss/components/_captioned_image.scss, client/scss/components/_tasl.scss, server/services/prismic.js, server/views/components/tasl/tasl.njk
Updates the TASL info overlay to what @Heesoomoon and @Norvard have been asking for for a while.
=> Image info overlay

client/scss/utilities/_root-scope-classes.scss, events/app/views/pages/events.njk, exhibitions/app/views/pages/exhibitions.njk, server/views/components/list-header/list-header.njk, whats_on/app/views/components/whats-on-list-header/whats-on-list-header.njk, whats_on/app/views/partials/mixed_exhibition_event_promos.njk, whats_on/app/views/partials/separate_exhibition_event_promos.njk
=> Move position of free text on what’s on, exhibitions and events

events/app/views/pages/event.njk, server/filters/add-to-calendar.js, server/filters/index.js, server/services/prismic-parsers.js
Only for events that have no other form of booking, and only if there is 1 date.
If this seems to prove popular (via tracking) we could look at implementing it across all dates - but something to explore, not have as part of a 404(ish) test
__TODO__
=> add to calendar test

whats_on/app/views/components/segmented-control/segmented-control.njk
This will have the following tracking:
* Component tracking on the date range switchers (Today / Weekend / Everything and month switcher). This will give us the component `whats-on-daterange-picker:click` with the label as the label of button e.g. `Today` or `March`
* Introducing a new referring component / data tracking letting us figure out where we came from i.e. Page stats of traffic that came from `Today` instead of clicks on the "Today" view. 
References: #2050
=> add whats on date picker tracking

client/scss/components/_image_gallery.scss, server/views/components/image-gallery/image-gallery.njk
=> Add image gallery heading if available

server/views/pages/article.njk
The divider above the content/below the hero image is wider than the content at the medium breakpoint (which has one blank column either side). This fixes it.
=> Align divider under hero with content at medium bp

client/js/tracking.js, server/views/components/exhibition-promo/exhibition-promo.njk, server/views/pages/article.njk, server/views/partials/analytics.njk, whats_on/app/views/pages/whats-on.njk, whats_on/app/views/partials/mixed_exhibition_event_promos.njk
Fixed #2050 
There is a new type of tracking on the block. This will allow us to say, "Give us pages that people visited by using the X component". X component is actually a hierarchical list e.g. WhatsOn,ExhibitionPromo. The state is also save with the component.
All of this is stored in JSON, which makes it a bit trickier to use in the console, but not any trickier than the comma separated lists. This is in the hope that we might be able to get machines to use it e.g. give me all pages that have a referring component... now analyse 🤖!
An example is:
```JS
[
{ ExhibitionPromo: {} },
{ WhatsOn: {active: 'tomorrow'} }
]
```
Stringified to `"[{"ExhibitionPromo":{}},{"WhatsOn":{"active":"tomorrow"}}]"`.
I have also added this to the component tracking label in case that is more useful.
In …
=> add componentList to ga event tracking label

prismic-model/articles.json, prismic-model/audiences.json, prismic-model/curated-lists.json, prismic-model/editorial-contributor-roles.json, prismic-model/event-formats.json, prismic-model/event-series.json, prismic-model/featureflag.json, prismic-model/featurescohort.json, prismic-model/interpretation-types.json, prismic-model/people.json, prismic-model/series.json, prismic-model/webcomic-series.json, prismic-model/webcomics.json
* After the discussion around promo, I realise we had some inconsistencies re: Image crops that needed addressing.
* Added it to a the series content types.
* Updated the titles to human readable niceness.
Do we think it would be better to have this?
```JS
const Promo = {
type: 'Slices',
config: {
label: 'Promo',
choices: {
editorialImage: {
type: 'Slice',
fieldset: 'Editorial image',
config: {
label: 'Editorial image'
},
'non-repeat': {
caption: {
type: 'StructuredText',
config: {
label: 'Promo text',
single: 'hyperlink, strong, em'
}
},
image: {
type: 'Image',
config: {
label: 'Promo image',
thumbnails: [
{
name: '16:9',
width: 3200,
height: 1800
},
{
name: 'square',
width: 3200,
height: 3200
}
]
}
}
}
}
}
}
}
const WebcomicSeries = {
'Webcomic series': {
title: {
type: …
```
=> add promo to relevant content types

build/nginx.conf
`split_clients` has to be in the `http` block.
=> move split_clients into http block in nginx

client/js/tracking.js
If there's no component, we still want to send over the page state.
=> record referral page state

client/js/app.js, client/js/components/eventbrite-ticket-status.js, eventbrite/app/controllers.js, eventbrite/app/routes.js, eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk, eventbrite/app/views/components/eventbrite-button/eventbrite-ticket-status.njk, server/content-model/events.js, server/services/prismic.js, server/views/components/event-promo/event-promo.njk
Fixes #2008 
Basic implementation of the ticket status.
We can take a look at it once it's out to see how it fits with the other elements of the design (the traffic light system specifically used on exhibitions).
This does __not__ cater for multi-events, which we haven't addressed yet here nor on the actual event pages.
=> Add ticket status to event promos

client/scss/components/_slider__in-article.scss
There's a horizontal scrollbar that appears when the page is larger than the xl breakpoint because we've not measured the size of the slider correctly.
Just realised these screenshots are pretty much meaningless on a white background, but you can see the bug by going to [this page](https://wellcomecollection.org/articles/WnBAsSoAACsA5tuj), making your browser wider than 1338px and scrolling to the right.
One day soon, this will all be simplified by css grid.
=> Prevent horizontal scroll (measure width correctly)

prismic-model/articles.json, server/services/prismic-body-parser.js, server/views/components/article-body/article-body.njk
The content has been updated to reflect this.
Run it past King Kontent and they reckon default off is best.
=> add listStyle to image lists

events/app/views/pages/event.njk, exhibitions/app/views/pages/exhibition.njk, server/views/components/picture/picture.njk
Fixes #2140
✨ Feature  
Adds image credit info. to main images on event page and exhibition page
N.B. not many event images have credit info. populated
=> Whats on image credits

server/controllers/async-controllers.js
The ID contained `/series` already.
=> fix series link on top/bottom nav

server/controllers/content.js, server/controllers/index.js, server/routes/index.js, server/views/pages/list.njk
We removed the format query parameter as we don't use it.
Well we do, but incorrectly, this creates a separate route for the article archive.
=> create new route for the archive artidles

client/js/components/segmented-control.js, whats_on/app/views/components/segmented-control/segmented-control.njk
Also, moves event listeners up the DOM, so don’t have to attach one to every link.
When the segmented control is used to move from the 'Today' view to the 'Weekend' view, and then the browser back button is used to navigate back to the 'Today' view, the active state does not update correctly. It seems that Safari is running the click event handler for the segmented control link, which is odd. I couldn't prevent that, but have added a check in the function that gets fired to prevent the weird behaviour.
🐛 Bugfix
=> Fixes weird Safari bug

prismic-model/events.json
As it's important and it's used everytime, let's move it up (it was lost otherwise).
=> move place to the top of access in prismic

eventbrite/app/controllers.js, eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk, events/app/views/pages/event.njk, prismic-model/interpretation-types.json, server/content-model/events.js, server/services/prismic-parsers.js, server/services/prismic.js
__Adds waiting list text when an event is fully booked. Currently:__
"A waiting list will operate for most free ticketed events. This opens in Wellcome Collection 60 minutes before the event starts and must be registered for in person. If you register for the waiting list, you'll be given a numbered ticket to take away, so you can enjoy the café, galleries and bookshop if they are open before the event. Moments before it starts, pre-booked places that fail to show are allocated to waiting list ticket holders according to the numbers on their tickets.
If you come to register for the waiting list in person, you can take away a maximum of two tickets."
@jennpb @Heesoomoon ^ this might need some work.
__fixes showing time on when tickets become available, previously was just the date (not so …
=> organise event by booking info / event description

server/filters/format-date.js, server/views/components/exhibition-promo/exhibition-promo.njk
We now flag if an exhibition is permanent or current (temporary).
The times we surface are:
* Coming soon
* Past
* Last week
* Now on
I wonder if the "Last week" should be "Ending soon" or "Final week" as last week, in my head means, well... last week.
Do we also want to flag perm / current on the exhibitions pages?
=> mark exhibitions as to whether they are permanent or current

whats_on/app/routes.js
To deal with the URLs Drupal creates e.g. `/whats-on/events/all-events`.
=> Wedge for what-on content to redirect to root

router/nginx.conf
Left the functionality in so we can go the other way _if_ we need to over the weekend.
=> 100% to whats on v2

server/config/index.js, server/controllers/content.js, server/middleware/set-cache-control.js
We should think about moving cache control config to CloudFront.
An analysis of our cache would be good, as it's where we will probably get the best performance gains.
=> don't cache HTML

events/app/controllers.js, server/services/prismic.js
To prevent events that have ended popping up at the top.
Waiting on some feedback from Prismic as I think there is a problem their side.
=> ordering of events reverse startDate

common/views/components/HTMLInput/HTMLInput.js, common/views/components/Index/index.js, common/views/components/SearchBox/SearchBox.config.js, common/views/components/SearchBox/SearchBox.js, server/views/pages/search.njk
References #2175
Converts the search box (used at the top of the works search page) to JSX.
=> Add search box

server/services/prismic.js
On event series pages, as some need to be listed there.
It might be worth rethinking the tagging, as delisted should mean that.
=> Show delisted events

client/scss/utilities/_root-scope-classes.scss, events/app/controllers.js, events/app/views/pages/events.njk, prismic-model/event-series.json, server/index.js, server/services/prismic.js, server/views/components/list-header/list-header.njk
Raises the question - where do we deserialise?
In my head it feels like it should always be at the template level?
Or we start creating things like `textDescription`, `htmlDescription` and `description` and just use `description` as the whatyoumightexpect type.
=> allow multiline events titles

common/views/components/Index/index.js, events/app/controllers.js
Fixes a bad merge – Tags JSX hadn't been added to the index and tags themselves were being passed in as an array instead of an object containing an array.
=> Pass tags as an object

.scripts/webapp/development/package.json, catalogue/webapp/pages/work.js, catalogue/webapp/pages/works.js, catalogue/webapp/server.js, catalogue/webapp/yarn.lock
To allow us to navigate between `/works` and `/work` whilst maintaing the URL structure we'd like.
I was thinking about making it a common server, but thought the small amount of work required, we'd land up introducing loads of abstractions to deal with that case, where we could just copy / paste.
We can then also try new servers for performance (potentially not node).
=> add koa server to catalogue webapp

common/utils/convert-image-uri.js, server/filters/convert-image-uri.js
From Prismic:
"On Mar 12, 2018 we will activate our CDN by default for every repo and redirect all the queries for content and assets through this CDN."
Just tried out using their CDN and the image sources in the API responses get changed. As a result ,we no longer convert them to iiif urls and so end up with huge images being loaded.
This fixes that. 
🚑 Health
=> Prepare for prismic CDN

server/views/components/article-body/article-body.njk
🐛 Bugfix  
Source name and link was missing from tasl info., this puts it back
Before:
After:
=> show source name and link on TASL info

events/app/views/pages/event.njk
Allows the usage of the `isSoldOut` flag to change the status on eventbrite events too.
=> allow the use of sold out on eventbrite shows too

catalogue/terraform/terraform.tf, router/terraform/asg.tf, router/terraform/cloudfront.tf, router/terraform/services.tf, router/terraform/terraform.tf
💻  As a webapp I need a place to live in the cloud to pass on my value to people.
To do this we are setting up the infrastructure needed to host the webapp.
__Notes__
* This app might not live in the `app_cluster`, but the `router` cluster as we want to have it accessible to the router ALB and potentially bypass the router service completely and just have it go straight from the request to the app.
* This should allow us to split traffic to the two different services to test for improved performance, which is one of the reasons we have done this.
in favour of #2277
=> add infra for catalogue

server/views/components/image-gallery/image-gallery.njk
Based on this data:
Timeframe: 1 Jan - Today
Total more clicks: 4,770
Total views for the top pages with more clicks: 7,971 + 3,400 (11371)
The two articles:
https://wellcomecollection.org/articles/WjK0mSsAAJCEh4A1
https://wellcomecollection.org/articles/Wi_yzSQAAFqPOrDY
Meaning that under half of people aren't seeing the interesting editorial content that gives the image gallery a narrative and context (which is the point of not using image descriptions as captions).
Thoughts are it would be good to show the content.
=> remove truncate text from image gallery

.dockerignore
We can see that the docker size went down massively here in commit: ad7b7baf06482b89dba43be9d2af15e934c60f0b
https://hub.docker.com/r/wellcome/wellcomecollection/tags/
Seems we need the node_modules.
I'll relook at the docker context size as a separate thing with it's own set of testing.
=> include node_modules in docker builds

common/views/components/Image/Image.js
🐛 Bugfix  
Noticed sizes attribute was missing from images, meaning that larger images than necessary are loading
Currently:
With sizes attribute back in:
=> Added missing sizes attribute

prismic-model/articles.json, server/controllers/content.js
Make sure we have an article to get a `displayType` from.
Also null as default, and basic as override.
=> check for article before retrieving displayType

common/views/global/typography/typography.config.js
Gareth O spotted these were back to front in Cardigan (this only changes the _displayed_ value – the font styles won't actually change).
=> Correct HNL4/5 displayed lineheights

common/views/components/Tasl/Tasl.js
=> Conditionally add punctuation if TASL section exists

events/app/controllers.js, events/app/views/pages/event-series.njk, server/filters/format-date.js, server/filters/index.js, server/views/components/event-promo/event-promo.njk
Closes #2354
Worth noting the 'past event' label will be added to all event promos that have ended in the past (not just those on the event-series pages – this consistency seems like desirable 
Obviously needs more design (@Heesoomoon and Gareth) (but perhaps good enough to ship?)
=> Move event-series to its own template; highlight past events

common/views/components/EventScheduleItem/EventScheduleItem.js, common/views/components/MoreInfoLink/MoreInfoLink.js
🚑 Health
Allows us to add additional text to MoreInfoLinks for screen readers. This is important if the link text, in isolation, doesn't provide enough details to describe the link destination.
Not sure if this is the correct approach, or we should just never have links that just say 'more information'.
=> Additional text on more info links, specifically for screen readers

events/app/views/partials/event_with_schedule.njk, server/services/prismic-parsers.js
See tin for details.
First pass, we'll look at contributors as a whole later when we're not being so responsive.
=> Event schedule contributors

common/styles/components/_prismic_toolbar.scss, common/styles/non-critical.scss, server/services/prismic-parsers.js, server/views/pages/article.njk
There is a pre-build prismic toolbar. It has:
* edit button from the article
* Preview sharing
~The button could do with a little styling.~
=> add prismic preview toolbar as test to articles

events/app/views/pages/event-series.njk, server/views/components/event-promo/event-promo.njk
References #2355 
(Also moves 'past event' messaging to same style/location as status (e.g. 'fully booked') messaging).
=> Display 'no upcoming events' where necessary

client/js/components/wobbly-edge.js
While updating the wobbly line to allow for 'valleys' and 'mountains', I missed a comma off the start of the mountain string, which breaks the wobbly line. Everything's cool with this re-added comma.
=> Fix wobbly line on articles

common/styles/components/_event_schedule.scss, events/app/views/partials/event_with_schedule.njk, prismic-model/json/background-textures.json, prismic-model/json/events.json, server/content-model/events.js, server/services/prismic-parsers.js, server/services/prismic.js
Adding a `backgroundTexture` property to the `Event` model so that we can display a background image at the top of the events with schedules.
I'm not really happy with the implementation though – doesn't really seem like this deserves to be part of the event model. I'm still not clear on how much freedom we want to give to anyone adding this content as regards which image should appear behind. Ideas?
One idea is that an event could be given a 'mood' (or something similar) property, and we select an appropriate background from a pre-determined library based on this mood. Which would be _less_ of an abuse of the event model.
=> Add basic background implementation

common/styles/components/_wobbly_edge.scss
Safari doesn't need the `-webkit` prefix for `clip-path`, but it fails to transition the property without it.
Autoprefixer presumably doesn't add it because Safari doesn't report needing it.
=> Make Safari transition clip-path

common/views/components/DefaultPageLayout/DefaultPageLayout.js, common/views/components/FooterNav/FooterNav.js, server/views/components/footer-nav/footer-nav.config.js, server/views/layout/default.njk, server/views/pages/curated-lists.njk, server/views/templates/explore.njk
Changing 'Explore' to 'Stories' because there wasn't a difference in A/B and we prefer 'Stories'.
This doesn't affect the url or the `inSection` (used to e.g. highlight active route in nav).
=> Change 'Explore' to 'Stories'

common/views/components/FindUs/FindUs.js
Inline elements in HTML add a space for a newline. [This isn't true for JSX](https://github.com/facebook/react/issues/1643#issuecomment-45148887):
> This is an intentional deviation from HTML because usually you don't want extra whitespace between tags. See here for a summary of the current rules:
http://facebook.github.io/react/blog/2014/02/20/react-v0.9.html#jsx-whitespace
One fix is to add `{' '}` after inline elements that want space when written on a new line.
=> Add space in footer address

common/styles/components/_cookie_notification.scss, server/views/components/cookie-notification/cookie-notification.njk, server/views/layout/default.njk
During in-person testing it seemed as though the cookie notification causes a natural barrier to what people might consider the end of the page [see screenshots].
Put it in as a test, but might need to think about what data to use for success measures.
We can use scroll depth, but we don't append whether the bar is visible or not to the pageview, so it would be hard to measure only scroll depth of pages with the cookie notification.
We could however measure that we aren't breaking anything by moving it up, and then rely on the qualitative research to make the decision on moving it.
=> run test on cookie notification position

server/views/components/cookie-notification/cookie-notification.njk
🚑 Health
Makes the cookie notice more discoverable by users of AT, such as screen readers
=> Added heading to cookie notification

common/views/components/Picture/Picture.js, exhibitions/app/views/pages/exhibition.njk, whats_on/app/views/pages/installation.njk
Hero images TASL should appear top-right (so's to avoid being covered by the wobbly-edge). This fixes a regression that prevented that from happening.
=> Allow TASL information to appear at top right

common/views/components/Index/index.js, common/views/components/ScrollToInfo/ScrollToInfo.js, exhibitions/app/views/pages/exhibition.njk
References #1544
Doesn't work on articles, as the article header is a special case.
We should just keep an eye on whether it get's used... but that's for a component audit.
=> add scroll to exhibition content

server/services/prismic.js
We should be 404ing when an event doesn't exist, this creates a 500 as we try to access the event object before we know we've got it.
Got it from the alerting.
=> only use the event once we know it exists

cardigan/docs/BodyBlock.jsx, common/icons/index.js, common/icons/status_indicator.js, common/utils/classnames.js, common/utils/format-date.js, common/views/components/Index/index.js, common/views/components/PageHeaders/ExhibitionPageHeader/ExhibitionPageHeader.config.js, common/views/components/PageHeaders/ExhibitionPageHeader/ExhibitionPageHeader.js, common/views/components/PageHeaders/Hero/Hero.config.js, common/views/components/PageHeaders/Hero/Hero.js, common/views/components/Picture/Picture.config.js, common/views/components/WobblyEdge/WobblyEdge.config.js, common/views/components/WobblyEdge/WobblyEdge.js, common/views/components/layout/Container.js, common/views/components/layout/Grid.js, exhibitions/app/views/pages/exhibition.njk
As we're thinking about our site in more conceptual and abstract terms, I think it would be safe to assume that we can have the concept of a page header, as we use it all over the place.
So far we seem to have
* Hero e.g. https://wellcomecollection.org/exhibitions/WeobUyQAAKdwjbEO
* Text only: https://wellcomecollection.org/event-series/WoK-NioAACkANeWK
* Text with texture: https://wellcomecollection.org/events/Wqkd1yUAAB8sW4By
Thinking with these concepts we might be able to support different content types having configurable headings etc passing on the power to the content team.
And maybe some thoughts about when we do and don’t use them (I've left the components in a state of WIP until they have this)?
The articles header is it’s own thing as it’s actually part of the body blocks.
This …
=> add page headers as a component type

common/views/components/CaptionedImage/CaptionedImage.js, common/views/components/ImageGallery/ImageGallery.js
Also fixing the index of the image captions
__before__:
__after__:
=> Add space for JSX

common/styles/base/_typography.scss, common/styles/components/_body_content.scss
Was causing spacing issues, e.g tags__list on installations page
=> Made generic style less generic

server/views/pages/article.njk
Makes the article use the right rail.
We gain that when we have content that isn't right-raily, it doesn't look odd *.
What we don't have at the moment is the idea of supporting image, which, if we designed, could have easily **.
__TODO:__
=> make articlebody more basic and less right raily

server/services/prismic.js
Get all the `null` `publishDate`s to the front, and then order by `first_publication_date desc` which reorders  the `null` publishDate.
The downside is the tail end of the content will be ordered `asc`.
=> order content old => new then new => old

nginx-proxy/nginx.conf
The conversation with @hthair made me realise that we don't set the featuresCohort cookie on the infra app, which includes articles.
=> set featuresCohort cookie on infra project

.circleci/config.yml, .gitignore, pa11y_report.js, package.json, yarn.lock
Instead of #2236 I thought HTML reports are simpler, need no infrastructure, and can be created at build.
For now, similar to speedtracker, this will be run on build against the live site, but we can enhance this to run the app and then run the reporter against itself.
=> run a really rudimentary pa11y report

common/styles/components/_body_text.scss
Setting `transition: all` on the link styles had the effect of transitioning their font-size at different breakpoints, which looks broken.
=> Only transition specified properties

server/services/prismic.js, whats_on/app/controllers.js
Using the traffic splitting we're doing (Baseline / A / B) to run a test on the what's on landing page.
Whether more events are viewed if the default view is everything.
The testB group will default to the everything view
=> What's on default view testing

server/views/pages/work.njk
My general sanity check because of the alerts going off in dotorg-explosions.
Moving the download link to not use our webapp as a proxy.
If we do want to do this, it might be worth thinking about creating a new service.
Now that I've removed it and used it, I wonder if this experience is actually better, which makes me realise we chose an experience without asking the people who use it.
Something to note when testing the catalogue.
=> use direct image link for downloading image

catalogue/webapp/pages/catalogue/work.js, catalogue/webapp/pages/catalogue/works.js, catalogue/webapp/server.js
Fixes/References #2472 
The team to test the new works page
Puts it on the `/catalogue` URL so we don't disrupt service.
=> Catalogue urls

common/styles/components/_body_part.scss
The transporter at the bottom of a digital story is currently too far over to the left. This fixes that.
=> Offset the transporter by the same amount as if it were in an .article

events/app/views/pages/event-series.njk
Fixes #2542
Adds some spacing below each event-series promo.
=> Space out event-series promos

whats_on/app/views/components/whats-on-list-header/whats-on-list-header.njk
Fixes #2264
Because the (new) secondary link style uses the same font variant as the 'Galleries closed today' copy, this problem (misalignment) goes away 🎉
=> Use a secondary link for opening hours

events/app/controllers.js
Fixes #2478
We weren't sending enough past events to the template.
=> Show three past events, not two

prismic-model/js/info-pages.js, prismic-model/js/tag-types.js, prismic-model/js/tags.js, prismic-model/json/info-pages.json, prismic-model/json/tag-types.json, prismic-model/json/tags.json
References #2526
People who would still like to use our informational pages after we turn Drupal off.
Allowing us to tag up pages with site sections.
=> add tags to info pages

common/model/info-pages.js, common/services/prismic/info-pages.js, prismic-model/js/info-pages.js, prismic-model/js/parts/link.js, prismic-model/js/parts/text.js, prismic-model/json/info-pages.json, server/controllers/content.js
References #2526 
All of us, to get away from Drupal
It's allowing us to import Drupal content without importing the media.
The process will be:
* Import with links to Drupal content
* Create a list that content editors can use to go through content that still has a Drupal image attached.
* Over time, this list should shrink to 0, at which time we deprecate the hack.
* Or we deprecate the hack, Drupal images in the body will just fall away, and promo images will be replaced with a placeholder.
An example of this can be seen on the schools info page: WtYmMiAAAOYZI206
=> Prepare info page for migration

common/services/prismic/multi-content.js, server/controllers/content.js, server/routes/index.js
Fixes/References #2526 
People who want to see all of the content listed as "What we do" or "Visit us".
This works with preview due to the nice new Prismic API service. 
Gives them a list of pages tagged as "what-we-do" or "visit-us".
We are currently using the internal Prismic tags. 
This is because, at the moment, you cannot query multiple content types with tags and query all of it. For now it'll do, but we can't attach metadata to it - although I have a plan of tagging the custom type with the tag, pulling that out and using it as the tag's metadata. Let's see.
=> add tag list pages

eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk
Makes the eventbrite button look like a primary button, without using the `Button` component (so as to avoid hacking in the `data-eventbrite-id` attribute.
=> Style eventbrite button correctly

common/styles/components/_back-to-top.scss
The back-to-top styles contained unneeded transforms which were overriding the styles which rotate the button (meaning the back-to-top icon was pointing downwards when viewed on a wide enough monitor).
=> Remove unnecessary styles

common/services/prismic/exhibitions.js
Add the Drupal hack to exhibition content.
Tested on the current release.
=> add drupal migration info to exhibitions

prismic-model/js/info-pages.js, prismic-model/json/info-pages.json
Fixes/References #2490 
People who want to see the dates of press releases
Allows us to add to add the date to press releases
=> add date published to basic pages for press releases

server/controllers/content.js, server/views/pages/article.njk
People who want to see more body squabbles, but can't as we hide it from them.
A test to see if we point it out that this is part of a series, people will see more of them.
A list would be better, but this was already lying around on the article page.
The test results are easy - do we get more traffic to the body squabbles series page.
If this proves good over the next week - we can think of a better execution.
=> add webcomic series tag to body squabbles

server/controllers/content.js
People trying to access articles that don't exist
Giving them a 404, not 500.
=> only look for article tags if we have an article

server/services/prismic.js
Following the A/B test, this sets 'everything' as the default view for everybody and reorders the filters:
Everything/Today/This weekend
=> Everything as default view, reordered filters

common/services/prismic/parsers.js, common/views/components/ContentList/ContentList.js, prismic-model/js/parts/body.js, prismic-model/json/info-pages.json, server/controllers/async-controllers.js
Editors when they want to create pages that have dynamically updated lists e.g. tags, content types, some other query we make available.
Giving them a field to put in a query to make the lists update on the page when the content updates.
=> add backfillQuery and requiredCount to content list

common/services/prismic/parsers.js, common/views/components/BasicPromo/BasicPromo.js
Those promos who have no companion images.
We're going to have to support promos without images (some but not all press releases will have them).
We need to have a nice hard look at our typing here to help us parse a little neater, but let's do that as a whole thing.
=> add support for promos without images

prismic-model/js/books.js, prismic-model/js/info-pages.js, prismic-model/json/books.json, prismic-model/json/info-pages.json
References #2492 
📖 🐛 
Giving us the chance to move over the books from Drupal.
The metadata isn't great (authors aren't linked for instance, and should be contributors) but Drupal has it in free text.
Not a hard job with a little manual intervention and some remapping in June when we do this.
[See here for more details](https://github.com/wellcometrust/prispal/blob/master/converters.js#L141-L170).
=> add books model

catalogue/webapp/pages/catalogue/work.js, common/views/components/Buttons/Button/Button.js, common/views/components/CopyUrl/CopyUrl.js, server/views/pages/work.njk
References:
> [Why don't we have `TertiaryButton` again?](https://github.com/wellcometrust/wellcomecollection.org/pull/2585#pullrequestreview-117230382)
We have a `<Button extraClasses='btn--tertiary' />` and this is, indeed, more appropriate (but needed some extra props to be added).
Have updated the work.njk and work.js templates to use this. The CopyUrl doesn't yet use the `Button` component, but should do in the future.
=> Tertiary button

server/routes/index.js
Us to help with the migration.
So as to not confuse what there are - let's move it here.
As stated, they are still temporary, and meant to be used to help facilitate the migration.
They will not work on the root domain, only preview.
=> use tag URL to not pollute the existing URL on v1

.github/PULL_REQUEST_TEMPLATE.md
People reading what we do on Slack
Make it easier to read by only including relevant info.
I'm also not sure checklists make people do things.
(☝️ How meta)
=> remove checklist from PR template

common/services/prismic/pages.js, common/services/prismic/parsers.js
People who want promos with no images.
The object returned by "No image" is `{ '32:15': {}, '16:9': {}, square: {} }`.
This is making me think, soon, is time to start writing some generic parsers, and we should try choose 1 type for images, and then refactor out the rest.
=> use isDocumentLink over isEmptyObject

common/views/components/Templates/BasicPage/BasicPage.js, common/views/components/Templates/BasicPage/InstallationPage.js, common/views/components/Templates/BasicPage/WobblyBackground.js
Devs / designers wanting to create a page for some type of future content, and not wanting to create a new page type.
Allowing us to pass a background component to the `BasicPage`.
This means that the installations, events, and pages (and potentially books) will hydrate the `BasicPage` template.
=> make basic page background a passable component

common/services/prismic/pages.js
The content team
removes the images from `Pages` as they have no credit info and alt text.
=> remove promo images from pages body

.github/PULL_REQUEST_TEMPLATE.md, router/terraform/cloudfront.tf
1. People who want the heading above to be in the present tense
2. People who like seeing confirmation of newsletter subscriptions/errors
Changing the tense of the first heading and stopping Cloudfront from ignoring the 'result' query.
=> Add 'result' to query string cache keys

common/views/components/Tasl/Tasl.js
Fixes #2603
Users.
Prevents empty TASL displaying on images.
=> Only show TASL if at least one necessary piece of info present

common/model/event-series.js, common/model/events.js, common/model/multi-content.js, common/services/prismic/events.js, common/services/prismic/fetch-links.js, common/services/prismic/multi-content.js, common/services/prismic/pages.js, common/services/prismic/parsers.js, common/views/components/SearchResults/SearchResults.js, events/app/controllers.js
People wanting to attach an event series to another piece of content.
Putting the event series in the multi content list.
I imagine we might want to display this slightly differently, potentially event creating an event-series Promo that is aware of the content it has e.g. current events.
As we're mainly doing manual attachment of content, this seems more valuable that looking at automated queries, which I think will be useful for the homepage, but we can look at that then.
=> Event series in multi content

common/styles/critical.scss, common/styles/utilities/all.scss
Users.
Reducing page weight.
The `root-scope-classes` were being called in from both the `critical` and the `non-critical` scss partials. This puts it in the critical alone.
__before__
__after__
=> Only load root scope classes once

common/views/components/BasicPromo/BasicPromo.js
Promos who don't have images
Allows them to be displayed as they were created to be.
=> allow imageless BasicPromos

common/views/components/PageHeaders/BasicHeader/BasicHeader.js, common/views/components/Templates/BasicPage/BasicPage.js, common/views/components/Templates/BasicPage/Page.js, common/views/components/Templates/BasicPage/TexturedBackground.js, prismic-model/json/installations.json
People who like pretty pages
Sets the rules of:
* First item of body is an image - used TexturedBackground. This stretches down the page, similar to the WobblyBackground.
* If not, just apply a texture behind the header.
__Next up__
I need to with with @GarethOrmerod on the spacing, as I can't quite figure out the annotations in Zeplin.
=> Page template headers

catalogue/terraform/terraform.tf, catalogue/webapp/next.config.js, catalogue/webapp/pages/work.js, catalogue/webapp/pages/works.js, catalogue/webapp/server.js, catalogue/webapp/yarn.lock, common/styles/works.scss, router/terraform/services.tf
Devs wanting to test the `works` Next.js app prior to launch.
This will make it available on `next.wellcomecollection.org`. This is necessary as we will be needing to host [multiple zones](https://github.com/zeit/next.js#multi-zones) for the different apps. 
We'll the serve the HTML content from `https://weco.org` but the static assets will come from `https://works.weco.org` (as far as I can tell from the docs).
=> prepping works for prime time

server/routes/index.js
Fixes/References #2490 
🗞 
Letting them see our press releases.
After talking to @jennpb we thought we can manage the URLs in code as we only want a few.
Once we're happy that that page looks like it should, we can set the router nginx config to be `/press` over `/press/.*`
=> add root press redirect

common/views/components/PageHeaders/BasicHeader/BasicHeader.js, common/views/components/Templates/BasicPage/InstallationPage.js
Fixes #2633
Making TASL information display on the featured image for installations.
I'm wondering if we might benefit from a `parseTaslFromImage` helper, because we might run up against this more in future.
=> Pass tasl to InstallationPage's UiImage

router/nginx.conf
Didn't actually specify the `@v1` location.
As this happens on runtime, the compile didn't pick up on it.
=> make sure we specify a v1 route

common/services/prismic/multi-content.js, common/services/prismic/search.js, common/views/components/BasicBody/BasicBody.js, common/views/components/SearchResults/AsyncSearchResults.js, prismic-model/js/parts/body.js
🚓 
Makes `orderings` and `pageSize` explicit from Prismic.
e.g. `tag:press pageSize:10 orderings:"my.pages.datePublished desc"`
Also fixes the bug of having orderings on things that don't have that field order randomly?
=> add dynamic orderings to search results

common/model/books.js, common/services/prismic/books.js, common/views/components/Templates/BasicPage/BookPage.js, server/controllers/content.js, server/views/pages/book.njk
📖 
Adds basic information into the `BasicHeader` description block.
We are obviously missing a lot, but this felt like a decent start using what we have.
It has made the decision though that we are happy to have `PrimaryLinks` in the `Description` block.
=> add basic metadata to books

router/nginx.conf
🦊 
Redirects pages that either had `/visit-us/*` or `/what-we-do/*` to the V2, with the fallback of V1.
This feels safer than just all of V1 => V2. It is also an alternative to #2661 which we have issues with because of Prismic.
=> redirect pages that had visit-us or what-we-do in the URL

events/app/views/pages/event.njk, server/views/pages/page.njk, whats_on/app/views/pages/exhibition.njk, whats_on/app/views/pages/installation.njk
🎰 
Adds the promo text as the meta description.
This should probably be done for the JSON LD - the installation JSON ld needs to be done, so I will do it there.
=> use promo text as description universally

server/views/pages/curated-lists.njk
After re-configuring the number of promos per row on the /stories page, the sizes queries for the responsive images were no longer optimal (and the six at the bottom of the page could look particularly blurry if loaded with a wide viewport).
This sharpens them all up.
=> Update stories promo image sizes queries

common/services/prismic/parsers.js
Between bad image typing, and fetched data from Prismic....
:rage4: 
I think we need to spend some time on Fire proofing rather than fire fighting.
=> check  for linked content data before parsing it

.circleci/config.yml
Ref: #2685
🏗 
The build system seems to have some for of caching that I can't figure out.
=> remove whats_on tests from circle

common/styles/grids/_grid_dividers.scss
The 6 promos at the bottom of the /explore page have dividers in the wrong place between the medium and large breakpoints (because they used to be laid out differently).
__before__
__after__
=> Do the divider nth-child dance at the correct breakpoint

common/services/prismic/exhibitions.js, common/views/components/ExhibitionPromo/ExhibitionPromo.js, server/views/layout/default.njk, whats_on/app/views/pages/exhibition.njk
Editors and viewers of the site
* Adds a validator bar that only show on preview. The first validation is looking for the meta description text, which comes from the promo text. 
* Removes the PROMO TEXT IS MISSING 💩 
* Simplifies the exhibition promo by not showing promo text on any of them.
Point 3 is contentious - if we still want to show the text there (and be strangely inconsistent) we can add a field to the promo which is something like `display`.
@jennpb ☝️ ?
=> add validator bar instead of showing nonsense contet to live userse

common/views/components/EventPromo/EventPromo.js, common/views/components/ExhibitionPromo/ExhibitionPromo.js
=> fix layout of event promos on what's on

router/nginx.conf
🐓 
Routing the root domains, bar `/press` through to V2.
And a bit of a tidy to get rid of that massive line.
=> route root domains to V2

server/controllers/content.js, server/views/pages/homepage.njk
👥 
Adding meta data and json-ld so that search results pages/shares on social media are more informative/useful
It's using the Medicine Now promo image for the twitter card etc. - we might want to use something else?
We have the description from the old site
=> Add meta data to homepage

router/nginx.conf
Fixes/References #2571 
Waiting on https://github.com/wellcometrust/wellcomecollection.org/pull/2656
Moves all `/press` to v2 (and if 404, v1).
=> push all /press through to v2

events/app/views/pages/event-series.njk, events/app/views/partials/event_with_schedule.njk
Before
https://wellcomecollection.org/event-series/WifrbikAAGSyDtHk
After
not sure when we started not being able to put padding on containers?
=> add padding where padding once was (frame header)

common/model/contributors.js, common/model/people.js, common/services/prismic/books.js, common/views/components/BasePage/BookPage.js, common/views/components/BasePage/InstallationPage.js, common/views/components/Contributors/Contributors.js
🐛 
Shows contributors on the BookPage.
We need to think about how we might migrate the 💩 Drupal people into new shiny Prismic people as contributors.
=> Books contributors

common/views/components/BasePage/BookPage.js, router/nginx.conf
* Checks if contributors > 1 before rendering contributor component
* Add's `/books` to router.
Annoyingly, as we only send `/what-we-do/*` and `/visit-us/*` through the druapl lookup for redirect, books don't get caught, and because the Drupal domain strategy doesn't put the content type in the URL, we can't filter this.
They will get caught when we make V2 the default, and fallback to V1.
=> add books to root routes

server/views/layout/default.njk, server/views/pages/newsletter.njk
Just noticed the newsletter signup is not showing for default users even though the flag was switched on. This fixes it.
=> fixed newsletter  flag logic

server/views/partials/monitoring.njk
Devs supporting users by fixing their errors.
Getting sentry into a less noisy state so we can respond better to actual problems.
=> Ignore 'blocked a frame' error in sentry

common/views/components/ImageViewer/ImageViewer.js
Devs solving errors on the client
With the aim of allowing us to respond to errors properly, ew should clear out the ones we have.
This is also a reminder that we should never use string construction for JSON when we have `JSON.stringify`
=> usse JSON.stringify for tracking on image viewer controls

common/model/image-promo.js, common/services/prismic/parsers.js, common/views/components/BasicPromo/BasicPromo.js, common/views/components/SearchResults/SearchResults.js, prismic-model/js/parts/image.js, prismic-model/js/parts/promo.js, prismic-model/json/books.json, prismic-model/json/exhibitions.json, prismic-model/json/installations.json, prismic-model/json/pages.json
References #2492 
People who want to have content link to places other than the `pages/{id}`.
You can add a link to a promo, which will then override the Prismic link.
This is useful for, say, `/opening-hours` as well as `/books`. It can also be used for the shop.
I imagine though books is going to evolve into something more fleshed out (managed list page), but this is useful elsewhere as stated ☝️ .
=> add link property to promo

common/styles/components/_promo.scss
Looks like we lost the overflow: hidden during the promo refactor and now tall images overlap others. This puts the style back.
Before:
After:
=> stop overlapping images on works listing

common/views/components/Excerpt/Excerpt.js, common/views/components/Index/index.js, server/services/prismic-body-parser.js, server/views/components/article-body/article-body.njk
Editors adding excerpts
Turns out we didn't do the excerpt at all.
This adds the UI in for Excerpts. 
* Also chooses between `UiImage` and `CaptionedImage`in the body dependant on whether the image has a caption. This is to get rid of the bug of showing the image caption with no text. What I would like to do is use the `parseImage` to return `CaptionedImage | UiImage` as we shouldn't really serve up all the captioned image stuff if there is no caption.
=> add excerpt

server/services/prismic-body-parser.js
People trying to cite quotes
Shows `citation - source` or `citation` or `source`.
=> parse quote footer correctly

common/services/prismic/parsers.js, common/utils/json-ld.js, server/controllers/content.js, server/services/prismic-parsers.js, server/utils/body-parser.js, server/utils/json-ld.js, server/utils/prismic-parser.js, server/views/components/twitter-card/twitter-card.njk, server/views/pages/article.njk, server/views/pages/curated-lists.njk
Fixes #2760
Devs and users wanting consistent promos
In light of #2760 - we need to really start moving things over to the new system / naming / parsing.
Articles are probably going to be last on this list, so this is just a partial upgrade.
=> put promos on articles

catalogue/webapp/pages/work.js
People use the 'back to search results' link on work items, so we're making sure the Next app keeps the functionality.
=> Add back to search results link

common/package.json, common/views/components/PageWrapper/PageWrapper.js, common/yarn.lock
Fixes #2472 
Users not wanting to download opening times every page load.
We add a cache. We still don't have the benefit of the `intervalCache` from the last app, where other users will benefit from the cache of others, but given that we don't page refresh all that often, we should be _ok_. I'd like to release against what we have, and we can optimise from there, but adding in HTTP calls is a big no no, so let's stay clear if we can.
What's the reason for using the `PageWrapper`? It does feel as though we could have the logic in the `DefaultPageLayout`?
=> add a cache for opening times on nextjs apps

common/package.json, common/services/unleash/feature-flags.js, common/test/services/unleash/feature-flags.test.js, common/yarn.lock
Ref #2801 
The team wanting to run tests
Adds (unleash)[https://github.com/Unleash/unleash] (created by Schibsted).
This has some great functionality, especially around % releases.
It feels like we would be able to create a system more customised to us by starting with a system built for the purpose we're using it for.
We also decouple ourselves from Prismic, and it get's the flags out of the way of the editors.
See the repo for the service, needs work, but works.
https://github.com/wellcometrust/feature-flags
=> add unleash for feature flags

common/views/components/WorkEmbed/WorkEmbed.js, common/views/components/WorkImage/WorkImage.js, server/controllers/work.js, server/views/pages/work.njk
People wanting to embed our catalogue images into their content.
Giving them a basic oEmbed output that is the image, wrapped in a link to the work.
If we added coords to the zoomer, we could use it as the cropper.
=> add oembed to works page

common/views/components/BasePage/BookPage.js, server/views/pages/book.njk
Fixes #2817 
People who like to know how many pages are in a book, and how hard it's cover is before purchasing.
:trollface: 
Giving them this information.
We could think about how we add extra metadata to pages.
e.g. should the contributors and meta information and any other added meta block have the same container i.e. `MetablockContainer`.
=> add metadata to books

common/styles/utilities/_mixins.scss
An empty string (possible after we added fonts to js config) breaks css font declarations.
Checking for empty strings in the sass stops this from happening.
=> Check font declaration exists

common/views/components/ImageViewer/ImageViewer.js
Fixes #2822 
Tracking arguments in ImageViewer were in the wrong order for the zoom in button.
=> Order the button tracking arguments correctly so ga data isn't junk

client/js/components/async-content.js, whats_on/app/controllers.js
Catching and handling 404 errors when we do a lookup for what which exhibition an installation is part of.
That's to be expected as an installation doesn't need to be part of an exhibition.
=> handle errors from 404 exhibition lookup on installations

common/views/components/HTMLInput/HTMLInput.js
`defaultValue` only gets set set on initial load, because we are currently using an 'uncontrolled' React input.
A tidy and immediate solution is to give any updated value as a `key` to the input's wrapping element.
This lets us punt the question of input state down the park for a bit.
👟🏈
Fixes #2798
=> Update input value when tag clicked

server/views/components/article-body/article-body.njk
Makes the article headings Wellcome Bold again.
=> Wrap PrismicHtmlBlock component in 'body-text' class

catalogue/webapp/package.json, catalogue/webapp/pages/work.js, catalogue/webapp/pages/works.js, catalogue/webapp/yarn.lock, common/views/components/PageWrapper/PageWrapper.js
Devs who want to use flags, hopefully easily
Allowing us to use a `pageStore` for the flags.
We can use the React Context to use them in the templates too - I tried it, but didn't want to introduce it without a use case as I haven't tested bundle size / performance of it.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy
https://reactjs.org/docs/context.html#when-to-use-context
=> Api v2 test flags store

common/styles/components/_divider.scss, common/styles/utilities/_root-scope-classes.scss, common/views/components/EventPromo/EventPromo.js, common/views/components/ExhibitionPromo/ExhibitionPromo.js, common/views/components/NewsletterPromo/NewsletterPromo.js, server/views/pages/homepage.njk
Addressing the standalone issues on under the Zeplin 'QA' tag.
Will pick up the remaining issues in separate tickets.
=> Standalone design QA amends

server/views/components/article-body/article-body.njk
In the (rare) instance that an image caption overlaps with the image gallery area, the captioned image _not_ having its own background looks less broken.
**Before**
**After**
=> Remove cream bg from image on article page

prismic-model/js/parts/contributors.js, prismic-model/json/books.json, prismic-model/json/events.json, prismic-model/json/exhibitions.json, prismic-model/json/installations.json
Noticed that what's being put into Prismic is
```
Role: Collaborator (<= no idea where this came from)
Description: Scientist
```
Where scientist should definitely be in role.
Will chat to the content team about it tomorrow.
=> chnge label of contribution description

common/styles/components/_gif_video.scss, common/views/components/Index/index.js, server/services/prismic-body-parser.js, server/views/components/article-body/article-body.njk, server/views/components/gif-video/gif-video.njk
The gif video had its own snowflake caption – this aligns it with the caption used elsewhere.
=> Use the Caption component in the gif-video

common/test/components/Contributors.test.js, common/views/components/BasePage/BookPage.js, common/views/components/BasePage/EventPage.js, common/views/components/BasePage/InstallationPage.js, common/views/components/Contributors/Contributors.js
Working with Alice W on how we pull in collaborators and how we give people context.
Turns out they have a guideline document (which is actually law) on the headings of the page.
1 being "About your [contributor.role](s)".
It's an easy thing to automate, and she said it would be of much relief if we did.
It will also create consistency, which is an important thing with accessibility. If you look at #2871 there is already inconsistencies creeping in Drupal style from copy and paste (your vs our).
We can definitely add in an override when this doesn't cater for the needs of the content team, but after talking to them, this feels like a good place to start and iterate on.
For those who don't read JavaScript.
It goes as such:
=> Contributors heading

cardigan_beta/stories/components/SectionHeader.js, common/styles/components/_divider.scss, common/styles/components/_slider__in-content.scss, common/styles/utilities/_root-scope-classes.scss, common/styles/utilities/compiled_variables/_fonts.scss, common/views/components/Divider/Divider.config.js, common/views/components/Index/index.js, common/views/components/SectionHeader/README.md, common/views/components/SectionHeader/SectionHeader.js, server/views/pages/curated-lists.njk, server/views/pages/homepage.njk
Componentising the `<SectionHeader />` as a thing that can head up a block of promos, with an optional link off to more of the same.
This is the current 'rule' – it may evolve.
=> Section header

common/styles/utilities/_mixins.scss
Fixes #2443.
If `letter-spacing` isn't specified in the font config object, we have to specify `normal`, otherwise we could inherit the (undesired) previous breakpoint's `letter-spacing` value.
=> Declare normal letter-spacing if not defined

catalogue/webapp/pages/work.js, common/views/components/PageWrapper/PageWrapper.js
Stops throwing a 500 error if we don't have a work.
We'll also be able to update the 404 page when we get to it.
=> add error to work page

events/app/views/partials/event_without_schedule.njk
So we can tell if people are using the button or email.
So far looks like no-one has used the email, but I also don't know how GA works with screen readers etc.
=> add tracking to email address

router/terraform/cloudfront.tf
In a bid to undo some of the work we did exploring whether we could have `nut.` and `geb.`
This will allow us to get rid of this domain which isn't doing anything.
=> make alb point straight to ALB

router/terraform/cloudfront.tf
Adds the subdomain to the distribution to allow us to send CDNed versions of the files.
=> add works subdomain to cloudfront"

server/views/layout/default.njk
This was added to be able to get support from pocket on why our articles aren't being parsed correctly in their system.
We now have a support ticket open, and should have some clarity on it.
=> remove pocket site verification

nginx_webapp/nginx.conf, server/middleware/error.js
From all the debugging on the installations preview, realised this was the issue, so the app in the container was getting the ECS URL of `app:3000`.
=> add Host header to weapp nginx and remove logging

common/services/prismic/event-series.js, events/app/controllers.js
Fixes #2840 
Ordering in JS can cause some unexpected results, and also have thing work differently in different parts of the site, so let's keep it in the API requests.
=> remove event ordering on event series

catalogue/webapp/pages/work.js, catalogue/webapp/pages/works.js, common/views/components/DefaultPageLayout/DefaultPageLayout.js, common/views/components/ErrorPage/ErrorPage.js, common/views/components/Footer/Footer.js, common/views/components/PageWrapper/PageWrapper.js
Realised that the `url` prop is actually being overriden by the Next JS props, thus pushing an object to the page.
This fixes that and adds the `oEmbedUrl`.
Waiting on #2919
=> Oembed and canonical urls

client/js/polyfills.js
The `closest` polyfill we were using wasn't doing its job in IE11; this is the cause of our [most seen JS error](https://sentry.io/wellcome/wellcomecollection-website-client/issues/345745353/?query=is:unresolved) (3K occurrences). The [MDN recommended polyfill](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill) works as expected (tested in Browserstack).
The old polyfill (on the same MDN page) carried this caveat:
> However, if you really do require IE 8 support, then the following polyfill will do the job very slowly, but eventually. However, it will only support CSS 2.1 selectors in IE 8, and it can cause severe lag spikes in production websites
So we'll be good to be rid of it.
=> Use a polyfill for 'closest' that works

client/js/tracking.js, client/js/util.js, common/utils/analytics.js, server/views/partials/analytics.njk
We're getting [some 'Access Denied' errors](https://sentry.io/wellcome/wellcomecollection-website-client/issues/446535915/?query=is:unresolved) when attempting to write to IE11 `localStorage`. This wraps a read/write test to `localStorage` in a `try/catch` to gobble the errors and bail on any `localStorage` operations if necessary.
It pains me that I've had to write the same function three times.
WET: Write Everything Thrice.
=> Check localStorage i/o before use

client/js/util.js
Click event delegation on e.g. the close cross on the Google map needs to account for the possibility that as it traverses up through the DOM, the parentElement may no longer exist (because it's been removed by JS).
This fixes our [fourth most 'popular' JavaScript error](https://sentry.io/wellcome/wellcomecollection-website-client/issues/418754406/?query=is:unresolved)
=> Account for the possibility that a clicked element's parent no longer exists

client/js/components/segmented-control.js
We were searching for an `href` on a `ul`.
[Fixes Sentry JS issue #5](https://sentry.io/wellcome/wellcomecollection-website-client/issues/478906462/)
=> Target the correct elements

client/js/app.js
Babel automatically adds the `Array.from` as part of the transform of spread in e.g. `[...a]`, but you have to polyfill it.
Adding the core-js Array.from polyfill seems like the most consistent approach with what we already have.
[More here](https://github.com/necolas/react-native-web/issues/409) and [here](https://github.com/babel/babel/issues/5682).
=> Polyfill Arry.from

client/js/components/segmented-control.js
The 'fix' in #2932 missed the existence of the JS controlled segmented controls. This reverts the change, but adds a check for the presence of an `href` to do the `.charAt()` test on, and returns early if it isn't there.
=> Check that there's an href to .charAt()

common/views/components/BasicPromo/BasicPromo.js
After chatting with @GarethOrmerod, we settled on this as a satisfactory interim solution before a (necessary) rewrite to have things in css grid (as opposed to flexbox).
Css grid is _better_ suited to this, but it isn't (as I'd hoped) going to be a silver bullet; will likely involve a rethink of how we do grid-like things altogether.
=> Increase basic promo image size

client/js/components/eventbrite-ticket-button.js, client/js/components/eventbrite-ticket-status.js
Prevents a client JS error if the `fetch` to Eventbrite fails. Fixes [this](https://sentry.io/wellcome/wellcomecollection-website-client/issues/599321149/?query=is:unresolved), [this](https://sentry.io/wellcome/wellcomecollection-website-client/issues/568014561/?query=is:unresolved) and [this](https://sentry.io/wellcome/wellcomecollection-website-client/issues/568799189/?query=is:unresolved) error in Sentry.
=> Catch the Eventbrite fetch

client/js/components/newsletter-signup.js
Using the better supported `appendChild` method to prevent [this](https://sentry.io/wellcome/wellcomecollection-website-client/issues/589669902/?query=is:unresolved) and [this](https://sentry.io/wellcome/wellcomecollection-website-client/issues/567617424/?query=is:unresolved) Sentry error.
=> Use appendChild instead of append

server/views/partials/monitoring.njk
Unsure why the `ignoreErrors` block isn't filtering the string `document.getElementsByClassName.ToString is not a function` from Sentry. Trying with a (shortened) regex instead (for consistency with `/Blocked a frame with origin/`, which appears to be working).
=> Use a regex instead of a string to filter ToString error

client/js/util.js
Our `featureTest` util that allows us to check if a browser supports a CSS property was creating a `<test>` element, which doesn't work in Chrome on iOS apparently ([Sentry error](https://sentry.io/wellcome/wellcomecollection-website-client/issues/603667340/?query=is:unresolved)).
This PR tidies the function and creates a `<div>` instead.
=> Tidy feature-test function

prismic-model/js/installations.js, prismic-model/js/parts/heading.js, prismic-model/json/installations.json
ref #2871 
For talk about the naming etc of how we might add UI elements into the CMS.
There is not implementation UI here.
Questions:
=> add contributors heading to model

catalogue/webapp/pages/work.js, server/views/pages/work.njk
Titles of works that contain quotes were causing `JSON.stringify` (which we call on tracking data) to break. Fixes [this Sentry error](https://sentry.io/wellcome/wellcomecollection-website-client/issues/605641288/?query=is:unresolved).
=> Sanitize tracking data prior to JSON stringifying

build/nginx.conf, nginx-proxy/nginx.conf, nginx_webapp/nginx.conf
When this was created it was created as `""` for baseline, and then two variants `testA` and `testB`.
In reality we've been sing `testA` as a baseline, and `testB` as the variant.
Given that we often have just enough traffic for A/B testing, having MV testing yet doesn't seem to be of much use. We will have this when we move to Unleash anyway.
=> move to using only testA and testB

common/services/prismic/parsers.js
As it's part of the design system, we use the square crop from prismic.
The editors can change and perfect that crop in prismic.
=> use square image from prismic for contributors

server/views/partials/monitoring.njk
The Sentry `oldSafari` regex test was too greedy (it should only have filtered out Safari versions 0–8, but it restarted filtering at version 10).
This only allows one number before the dot.
http://rubular.com/r/O6UxOzW87G
=> Fix greedy Safari useragent regex

common/styles/utilities/_root-scope-classes.scss
Reducing the min-height of the promos slightly, to make them look less awkward when they get close to the medium/large breakpoint (in accordance with @GarethOrmerod's wishes).
=> Jiggle the min promo height

prismic-model/js/parts/contributors.js, prismic-model/json/books.json, prismic-model/json/events.json, prismic-model/json/exhibitions.json, prismic-model/json/installations.json
To help editors understand what it actually does.
Ran it past them and this made sense.
=> change CMS label for contribution context

router/terraform/cloudfront.tf, whats_on/terraform/services.tf
Allows us to access the whats_on service directly.
We'll need it for the next app too.
=> add whats-on subdomain

common/styles/components/_body_part.scss, common/styles/components/_body_text.scss
Make `<ul>`s within `body-text` have their long-ago-created styles.
=> Move ul bullet code into body_text partial

common/services/prismic/event-series.js, common/views/components/BasePage/EventSeriesPage.js, events/app/controllers.js, events/app/views/pages/event-series.njk
Allows us to render the old description way, and new body way across both templates.
This way we can migrate and deprecate the old description way without any of the frontend breaking.
Then remove the code to deal with the deprecation.
=> Event series parse and render body

server/middleware/error.js
Stops the page rendering and thus prismic preview not working
=> don't throw error before render

whats_on/app/controllers.js
Prevents a 500 for e.g. https://wellcomecollection.org/exhibitions/WgV_ACUAAIu2P_ZM/exhibits?query=ids:
(404s instead).
=> Bail out of renderExhibits if there aren't any IDs

server/views/partials/monitoring.njk
Pages that Sentry reports having errored with the URL 'https://translate.googleusercontent.com/translate_c' are still showing up in our dashboard in spite of our whitelist and blacklist settings. (e.g. [this error in Sentry]).(https://sentry.io/wellcome/wellcomecollection-website-client/issues/607078821/?query=is:unresolved).
Here we're trying to check what data _would_ be sent to Sentry, and preventing if from doing so if the `data.reqest.url` contains 'googleusercontent'.
=> Test raven data.request.url for 'googleusercontent'

catalogue/webapp/pages/works.js
@hthair 
Improves the title information for a better GA life.
Fixes #2953.
=> Append query to works title if it's there

common/views/components/InstallationPromo/InstallationPromo.js, server/services/prismic.js, server/views/pages/homepage.njk, whats_on/app/views/pages/whats-on.njk
=> Add pharmacy of colour promo to 'try these too' on the what's on page

server/middleware/error.js
Because the prismic js isn’t loaded, the cookie not set and the preview doesn’t work
People who want to see prismic previews
showing them the  preview instead of 'not found'
=> Don’t throw if it’s a preview link

server/views/pages/article.njk
Re-introduce height limit (and black background) for the comic to ensure it can fit 100% in the viewport.
=> Limit height of comic based on viewport

common/views/components/Avatar/Avatar.js
Uses `overflow: hidden`, `border-radius`, and `transform: scale()` for better support than `clip-path`.
Fixes #3068.
=> Fix jaunty contributors cross-browser

common/views/components/ChapterIndicator/ChapterIndicator.js
Updating the babel config to use the `next/babel` preset removed the ability to create a new empty array with a length defined and spread over it straight away. The ability to spread over arrays that have items (and not _just_ a length property) remains.
Using `Array.from()` is probably the more appropriate/readable method to accomplish this in any event.
This gives us back our delightful chapter indicator bars.
Fixes #3071.
=> Use Array.from() instead of spread

server/services/prismic.js
filter undefined values from scheduleIds
=> prevent event page from breaking

common/model/events.js, common/views/components/BasePage/EventPage.js, common/views/components/EventPromo/EventPromo.js, server/content-model/events.js, server/data/facility-promos.js, server/index.js, server/services/prismic.js, whats_on/app/views/pages/whats-on.njk
fixes #3079
Instead of creating individual promos for each instance of an event, we now only show one, with an indication that there are other dates/times
=> Multi date promo

cardigan_beta/stories/components/Links.js, common/model/events.js, common/services/prismic/events.js, common/styles/utilities/_root-scope-classes.scss, common/views/components/BasePage/EventPage.js, common/views/components/Labels/Labels.js, common/views/components/Links/PrimaryLink/PrimaryLink.js, whats_on/app/controllers.js, yarn.lock
References #3022.
Adding the relevant date/messaging information to event page headers based on
- whether booking is required
- if so, if it's email or Eventbrite
- single or multiple dates
- if all events are in the past
__TODO:__
__TODO in another PR:__
=> EventPage header date/info bar

events/app/controllers.js, server/services/prismic-parsers.js
Allowing the `event-series` route to be viewed with the Prismic preview API.
=> Allow Prismic preview on the event-series page

router/nginx.conf
An attempt to catch the newline character (`%0A`) in some Wellcome Images URLs before it causes a 5xx error. Unsure if it will work, but can't see that it would hurt trying?
=> Send WI urls containing newline character straight to /works

common/model/generic-content-fields.js, common/services/prismic/parsers.js, common/views/components/BasePage/EventSeriesPage.js, common/views/components/BasePage/InstallationPage.js, server/views/layout/default.njk, whats_on/app/views/pages/event-series.njk, whats_on/app/views/pages/installation.njk
Introduces `promoText` and `promoImage` - I'll get on deprecating using `promo`.
This helps with not having to null check the whole time.
Couple of bug fixes in the event series page too.
=> use promoImage and promoText over a seperate promo property

events/terraform/services.tf, whats_on/terraform/services.tf
Turns out I got it wrong. From [here](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html).
> Each rule has a priority. Rules are evaluated in priority order, from the lowest value to the highest value. 
Also added https listeners so preview works.
=> use alb priority properly and add https listners to whats_on service

common/services/prismic/api.js, server/middleware/error.js
We are in preview mode if we are on `preview.` or not prod.
This was because the preview links functionality doesn't actually set a cookie on the site, but rather on `prismic.io`, which it then pings, which we should not be passing on to users who aren't expecting that.
=> fix preview links

common/services/prismic/api.js
Turns out it's a Koa specific object, we can get it more typed when this is working.
=> match on right request object property

common/services/prismic/events.js, prismic-model/js/events.js, prismic-model/json/events.json
Ref #2864 
Add the body slice and the migration script to events.
Next is to deprecate description once the content has been remapped.
=> add body to events

catalogue/webapp/services/catalogue/works.js
The new API rule is, if it's a list, you need to include it.
This does that.
=> include fields that are lists in catalogue app

common/services/prismic/event-series.js, common/services/prismic/events.js, common/views/components/EventPromo/EventPromo.js, server/middleware/error.js, whats_on/app/controllers.js, whats_on/app/routes.js, whats_on/app/views/pages/events.njk
In prep for removing the old events service, which will then render events from `whats_on`.
=> render events page from whats_on service

common/model/events.js, common/services/prismic/events.js, common/utils/format-date.js, common/views/components/BasePage/EventPage.js, prismic-model/js/events.js, prismic-model/json/events.json
Added a date/time field in Prismic to indicate when ticket sales start.
If it's filled in, and the date/time is in the future, the booking button will be swapped out for messaging about when tickets will become available. The date and time formatting are in line with what we currently have (propose to update all of our date formatting at the same time).
__TODO:__
=> Future ticket availability

router/terraform/cloudfront.tf
Caching the event pages for a maximum of 60 seconds ensures that the 'Book from xxxx' messaging will be replaced with the appropriate button when the tickets become available.
=> Cache event pages for 1 minute to clear future availability message

common/services/prismic/parsers.js
References #3143
Fixes the not-quite-rounded-off corners weirdness
=> Use square image for default contributor fallback

common/views/components/BasePage/BasePage.js
Getting rid of slightly arbitrary space at the bottom of the `BasePageColumn` so any spacing decisions we make start from a level playing field.
=> Remove BasePageColumn bottom padding

common/services/prismic/event-series.js
Turns out you can still query for things that are linked to broken / archived documents.
In this instance Library Tours.
Spotted in explosions.
=> only return series if there is a series

common/utils/classnames.js
> There should be one-- and preferably only one --obvious way to do it.
We can then use this everywhere with an array or object?
@wellcometrust/experience-dev ❓
=> add one classname function to rule them all

common/styles/base/_responsive-defaults.scss, common/styles/utilities/_root-scope-classes.scss
Images with `width: auto` can wind up wider than the viewport and create horizontal scrollbars (e.g. https://wellcomecollection.org/books/WwVK3CAAAHm5ExxN on a phone screen).
Limiting max-width of the `width-auto` class elements to 100% fixes it.
=> Image width

common/styles/components/_buttons.scss, eventbrite/app/controllers.js
References #3143 
The Eventbrite widget 'E' logo has an absolute linked path, and since we were proxying it, it was linking to a route on wellcomecollection.org that doesn't exist.
The markup is built in JS, so adding a `<style>` block to the end of the iframe made more sense than trying to wait for the markup to be built and replace classes.
Also preventing clicks on `<a>`s with a `disabled` class using `pointer-events: none`. This appears to have the side-effect of preventing the `cursor: not-allowed` styling, but I'd consider this the lesser of two ills.
=> Hide broken 'E' link

common/services/prismic/parsers.js
Spotted by Alice.
The contribution description wasn't overriding the contributor description.
=> parse contribution description better

common/views/components/BasePage/EventPage.js
It's not good enough to wait for the iframe to load to measure the content height, because the iframe's content is built with JS after it loads.
So we wait for a second to let that happen.
=> Wait a second before making Eventbrite button clickable

common/services/prismic/event-series.js, common/views/components/BasePage/EventSeriesPage.js
Ref #2989 
* Cap past events to 3 events
* Add "No events scheduled at the moment, check back soon…" messaging
=> have "no events" mesaging on event series, and cap list to 3 events

common/views/components/BasePage/EventPage.js, common/views/components/EventScheduleItem/EventScheduleItem.js, common/views/components/LabelsList/LabelsList.js
People who don't like having to decide whether there should be 1 or 6 pixels of space between labels.
Removing the spacing decision and making all labels have 3px of space between them.
=> Normalise label spacing to 3px everywhere

common/views/components/BasePage/EventPage.js
Fixes #3226
When the vertical spacing between labels changed from 6px to 3px in #3219, it had the knock-on effect of mis-aligning the linked labels.
This PR fixes the alignment with an inline style, but as 3px is looking like a necessary spacing unit for at least a few things, we should consider how we're going to incorporate it into our spacing strategy.
=> Re-align labels

common/styles/components/_body_text.scss
Fixes #3223.
Indenting all list item lines the same amount.
=> Align bulleted lists better

.circleci/config.yml, common/services/prismic/exhibitions.js, server/controllers/content.js, server/package.json, server/yarn.lock
Catching old exhibitions that we have back-filled and redirecting to them on the V2 site rather than going to Drupal. Also, adding analytics to report that this has happened (saying where we redirected from and to).
A couple of things to note
1. I've not managed to see this working locally (using `micro-proxy`) but can't see why it wouldn't work in prod (not ideal)
2. I've not seen any evidence of the GA events showing up in GA – not sure if this is because we filter out events from localhost, or if I've not configured it correctly.
Lots of eyes and suggestions welcome.
Not got any reason to believe that this (a) wouldn't work or (b) would break anything even if it didn't work, but probably safest not to merge until after the bank holiday.
=> Exhibition drupal redirect

server/utils/body-parser.js
💥 from the past:
https://wellcomecollection.org/articles/why-the-world-needs-collectors/
=> replace nbsp on wordpress standfirst

common/views/pages/_document.js
Turns out we were using the `user-agent` header to work out whether to server polyfill.
We don't send that header through due to our cache control, and rightfully so.
So now we serve up polyfill to all, which for chrome looks like this:
It feels like being able to move onto the new platform and start optimising from there over rules the 50ms.
Fixes #3240
=> use polyfill with next app

CONTRIBUTING.md
After chatting to @davidpmccormick and @gestchild it seemed `health` didn't make much sense as if we were doing something  to maintain the status quo, we should probably just leave it.
=> improve contributing labels

server/controllers/content.js, server/controllers/wordpress.js
`inSection` in the `pageConfig` needed updating from 'explore' to 'stories' in all places where we'd expect 'Stories' to be underlined in the nav.
=> Fix nav underline for stories content

prismic-model/js/parts/article-body.js, prismic-model/json/articles.json
Annoyingly this means we don't have square crops for most the content.
~I'm not 100% sure if a reimport would do this for us, as, I think, re-saving does.~
Scrap ☝️ - were just going to have to accept we don't have them.
=> add crops to article body slices

common/model/books.js, common/model/captioned-image.js, common/model/contributors.js, common/model/events.js, common/model/exhibitions.js, common/model/generic-content-fields.js, common/model/image.js, common/model/people.js, common/services/prismic/parsers.js, common/views/components/FacilityPromo/FacilityPromo.js, common/views/components/Images/Images.js
As we've `import {Image as ImageType}` a million times, lets just make it the norm.
=> Image => ImageType

prismic-model/js/exhibition-resources.js, prismic-model/js/exhibitions.js, prismic-model/json/exhibition-resources.json, prismic-model/json/exhibitions.json
References #3009
Adds a Prismic model for exhibition-resources and updates the exhibitions model to allow for linking to them
=> Exhibition resources

common/services/prismic/events.js
Realised we were 5000ing if someone didn't put in times, which should be valid for previewing
=> filter out blank times from Prismic

server/services/prismic.js
Plan
* exclude `wordpress` tagged content
* reindex the content with the time in the proper format
=> exclude articles with wordpress tag

content/webapp/pages/exhibition.js
References #3009
People who want to share/browse our content on social media platforms
Allowing Twitter et al. to display content snippets when wellcomecollection.org links are shared on their platforms
=> Exhibition meta

common/services/prismic/events.js
On the event schedule, multi date events are listed separately for each day on which they occur.
However, for each day, they are displaying the times for all of the days on which they occur:
This fixes that so only the times of the relevant day are displayed:
=> Filter out irrelevant event times from schedule

cardigan/stories/components/WobblyBottom.js, common/data/the-pharmacy-of-colour.js, common/model/exhibitions.js, common/model/generic-content-fields.js, common/services/prismic/exhibitions.js, common/services/prismic/parsers.js, common/views/components/BaseHeader/BaseHeader.js, common/views/components/BasePage/BasePage.js, common/views/components/BasePage/EventSeriesPage.js, common/views/components/BasePage/InstallationPage.js, common/views/components/Body/Body.js, common/views/components/ExhibitionHeader/ExhibitionHeader.js, common/views/components/Header/Header.js, common/views/components/Index/index.js, common/views/components/Layout/Layout.js, common/views/components/WobblyBottom/WobblyBottom.js, content/webapp/pages/exhibition.js
Move `HeaderText` above image and use `TextLayout` instead of `BasePageColumn`.
=> Exhibition header update

common/views/components/BasePage/EventSeriesPage.js
@pollecuttn was asking what the ordering logic was for the event series events.
It appears to be just whatever Prismic gives us (unsure exactly what that is – not obvious at a glance).
This PR assumes that we'd want _upcoming_ events to be ordered chronologically and _past_ events to be ordered reverse chronologically.
Don't know that this is the desired behaviour, but leaving this here so we don't forget to address the issue.
=> Order upcoming/past event series events

router/Dockerfile, router/nginx.conf, router/redirects.conf
Makes it easy enough to add.
How do we feel about moving [this](https://github.com/wellcometrust/wellcomecollection.org/blob/master/redirects/config.json) here? 
The JSON service will die once we deprecate the server app, so we would have to move it, and it would be nice to move it closer to the edge.
=> add nginx redirects to router

server/views/pages/page.njk
Adding open-graph/twitter-card image to pages. This fixes the issue of Prismic preview warning that there isn't an image when there is one. More importantly, makes that image appear on the socials.
=> Add image to open-graph meta

common/views/components/BasePage/BasePage.js, common/views/components/Contributors/Contributors.js, content/webapp/pages/article.js
I know we've been passing components about, but that was based on the loose layout and evolutionary phase we've been going through.
This still works for things like the `FeaturedMedia`.
Coming closer to a [refinement on this](https://github.com/wellcometrust/wellcomecollection.org/issues/3327), we know where the contributors go (and a few other things).
How do we feel about this then? Or do we feel it will make things too inflexible, and if so, is it worth it to stop us having to make decisions for all content types and the maintenance overheads on what is going to become an `maintain` part of the project?
__If we're happy for this to go ahead, I'll implement it across the content types in this PR for completeness.__
=> add contributorProps to BasePage and implement on articles

common/services/prismic/parsers.js, common/styles/utilities/_root-scope-classes.scss, common/views/components/BaseHeader/BaseHeader.js, common/views/components/BasePage/BasePage.js, common/views/components/Body/Body.js, common/views/components/Images/Images.js, common/views/components/Layout12/Layout12.js, common/views/components/Layout8/Layout8.js
Ref #3297 
Add image weights and image restrictions:
* Images in body are restricted to `100% width`, or `90vh, which ever they hit first
* 100% = 
* supporting: 8 cols (same as text)
* default: 10cols
* standalone: 12cols
On medium / small breakpoints :point_up: doesn't make a difference, same as on mobile now.
Where this falls apart a little is when we have a portrait supporting image, as it reaches it's mx height before filling the column width.
But I wonder if this solves for the fact that they were using the supporting to get the portrait images into the right rail as they look terrible on desktop as it stands [e.g.](https://wellcomecollection.org/articles/W4z18x4AACIAmwSs)
=> Image weights

common/views/components/CompactCard/CompactCard.js, common/views/components/EventCard/EventCard.js, common/views/components/SearchResults/SearchResults.js
Might then abstract this further into genericContentFields, as nearly everything should have labels, and we want to make sure they're the same across the different places we display them i.e. page header, cards etc.
=> use labels property instead of component on cards

common/services/prismic/event-series.js, common/services/prismic/events.js, common/views/components/BasePage/BasePage.js, common/views/components/Contributors/Contributors.js, common/views/components/SearchResults/SearchResults.js, content/webapp/pages/article.js, content/webapp/pages/event.js
I was going to abstract the spacing out, realised that we don't actually put the series on the events pages anyway.
Thinking I would rather get this released and then work on getting the `BasePage` children into some sort of shape... but seems like an over optimisation when there is so much to do.
=> add some spacing to article series

common/views/components/EventbriteButton/EventbriteButton.js
Short-term fix for Eventbrite – removing the iframe and linking the button through to the eventbrite page.
=> Remove JS enhanced EB iframe (just use link)

content/terraform/terraform.tf, shared-infra/terraform/service_alb_listener/alb_listener.tf
Let's start with pages as a test for GA etc before moving onto the articles and exhibitions.
=> add ALB listener rule to serve pages from content app

common/views/components/Images/Images.js, server/views/components/article-body/article-body.njk
Prevents images in the current article page getting distorted if they're larger than 80% of the viewport.
=> Remove height limit from current article page images

content/webapp/pages/article.js
Mistakingly thought it was an index bug, turns out it was a logic bug.
A little bit more self explanatory as to how it all works in the code now.
---
=> don't show part # on articles that aren't in series

common/services/prismic/parsers.js, common/views/components/Body/Body.js, common/views/components/DeprecatedImageList/DeprecatedImageList.js, common/views/components/Images/Images.js
Add the image list as an `h2`, `image` and `paragraph`.
Works until we decide what to do with them.
Is we added title to the new image list, we would be able to migrate them.
See #3257 for articles with them in.
=> add DeprecatedImageList component

common/views/components/DefaultPageLayout/DefaultPageLayout.js
Fixes #3461
Nice on white pages:
Strange on articles:
Let's get this in then we can deal with the latter.
=> add NewsletterPromo to DefaultPageLayout

common/styles/components/_captioned_image.scss, common/styles/components/_gif_video.scss, common/views/components/GifVideo/GifVideo.js
References #3257
Now gif-videos are displayed in the new template, we need to limit their size. This makes them behave the same way as captioned images (limited to 80vh)
Before:
After:
=> Gif video layout

common/services/prismic/pages.js, common/views/components/DefaultPageLayout/DefaultPageLayout.js
2 minute investigation showed that we show no drupal image as we have a promo, there's just no image in it.
This way . we use the drupal image, even if we have a promo.
Fixes #3423
=> do a combo of promo and drupalised promo for pages

router/terraform/cloudfront.tf
As per https://spectrum.chat/thread/602ba081-7fea-4c73-9007-a8f0d5a55152
Bumped up the next asset cache times, so they should always outlive the HTML.
Tested this with pages over the weekend, and no errors, but we'll keep an eye out.
=> make sure next asset cache is stronger than HTML cache

content/terraform/terraform.tf
Serves all pages and exhibitions from content app (thus the new template).
=> serve all pages and exhibitions from content app

common/model/articles.js, common/services/prismic/article-series.js, common/services/prismic/articles.js, common/services/prismic/multi-content.js, common/views/components/ImageGalleryV2/ImageGalleryV2.js, common/views/components/SeriesNavigation/SeriesNavigation.js, content/webapp/pages/article.js, prismic-model/js/webcomic-series.js, prismic-model/json/webcomic-series.json
Adds webcomics to the mix.
This allows us to maintain the `/articles/{ID}` URL, but it really would be nice to actually bring these into the `articles` fold.
=> Webcomic series parsers

common/model/periods.js, common/services/prismic/exhibitions.js, common/views/components/CardGrid/CardGrid.js, common/views/components/LayoutPaginatedResults/LayoutPaginatedResults.js, common/views/components/Pagination/Pagination.js, content/webapp/pages/exhibitions.js, content/webapp/server.js, whats_on/app/views/pages/exhibitions.njk
Move exhibitions rendering completely over to nextJS.
NEXTIBITIONS!
I'll change the route listener once I've tested this with `/exhibitions/past`.
There will be quite a lot of deprecation and deletion after this.
=> add period routes to content app

common/model/events.js, common/views/components/BasePage/EventPage.js, common/views/components/CardGrid/CardGrid.js, common/views/components/DailyTourPromo/DailyTourPromo.js, common/views/components/DateRange/DateRange.js, common/views/components/EventDateRange/EventDateRange.js, common/views/components/EventPromo/EventPromo.js, common/views/components/EventsByMonth/EventsByMonth.js, common/views/components/StatusIndicator/StatusIndicator.js, common/yarn.lock, content/webapp/pages/event.js, whats_on/app/views/pages/events.njk, whats_on/app/yarn.lock
Fixes #3400 in conjunction with #3494 
Makes the `EventPromo`take an `UiEvent` as it's prop, letting us miss the event => event promo parsing all over the shop.
We do however lose the sold out booking status that sometimes worked - not sure how we integrate better here.
This will amount to more work for the content team unless we can find some time to talk Eventbrite.
=> Event promo

content/webapp/pages/page.js
Need to remember that [data from `getInitialProps` is serialised](https://github.com/zeit/next.js#fetching-data-and-component-lifecycle).
I wonder if this means that the data models should only ever carry JSON basic types which are then converted when needed in rendering / logic? [That could be particularly annoying with things like events](https://github.com/wellcometrust/wellcomecollection.org/blob/master/content/webapp/pages/event.js#L82), but it doesn't look like it's going to be changed soon.
We could have something like:
* Prismic API
* Our normalised JSON API
* Converted into Dates etc
=> make sure we deserialise the serialised date from getInitialProps

common/utils/dates.js, common/utils/format-date.js, common/views/components/EventDateRange/EventDateRange.js, common/views/components/EventPromo/EventPromo.js, common/views/components/EventsByMonth/EventsByMonth.js, common/views/components/FindUs/FindUs.js
Shows the correct event time for an event promo determined by the month it is displayed in
Fixes #3407 
This solves the second problem raised in the issue above, i.e.:
"Event cards are being displayed in the wrong months. For example, there are 3 November events in 'December'."
The issue wasn't that they were displaying in wrong months. They were events that happen in both November and December. We were correctly showing the event in both months, but the display date was the next upcoming date (which was in November).
This PR changes the display date for the card to the next upcoming date for the month it is in and then orders the events in that month by that date.
For example:
HIV and Aids event displayed under the November tab:
HIV and Aids event displayed under the December tab:
=> Correct displayed time for event by Month
