wellcomecollection/wellcomecollection.org

- server/data/facility-promos.js
Remove space.
Remove oxford comma.
> remove the oxford comma

- events/app/views/pages/event.njk
Let people know about our amazing partnerships.
> add UI for partners on events

- prismic-model/events.json
- prismic-model/organisations.json
- server/services/prismic-parsers.js
- server/services/prismic.js
> add organisations as contributors for events

- server/views/components/event-promo/event-promo.njk
A nice and elegant solution that is way better than `{format} | {audience} only`.
A nice way of using metadata to construct human friendly language.
> {format} for {audience}

- events/app/controllers.js
- events/app/views/pages/event.njk
- server/views/components/tags/tags.njk
We'll be tracking the clicks through to this.
@jennpb could we add the hotjar event when / if we think of the question as it's not as trivial as I thought.
> Wedge series title into the tags at the top

- eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk
> add new waiting list messaging

- events/app/views/pages/event.njk
- server/content-model/events.js
Same as #2200 but on event page
> add for audience on event page

- eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk
Thanks @Heesoomoon for spotting.
Complete #2198
> remove unnecessary sentence from waiting list event info

- whats_on/app/views/components/whats-on-list-header/whats-on-list-header.njk
Spotted another.
Similar to #2210
> use absolute URL for opening hours

- eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk
> Remove "on" from eventbrite ticket

- events/app/controllers.js
- events/app/views/pages/event.njk
- server/services/prismic-parsers.js
Makes body copy universally styled.
> add body content styling to all body content on events

- client/scss/utilities/_root-scope-classes.scss
- events/app/views/pages/event.njk
- events/app/views/pages/events.njk
- exhibitions/app/views/pages/exhibition.njk
- exhibitions/app/views/pages/exhibitions.njk
- whats_on/app/views/partials/mixed_exhibition_event_promos.njk
- whats_on/app/views/partials/separate_exhibition_event_promos.njk
Removes the ticket icon, which was confusing users
> Removed ticket icon from Free notification

- events/app/views/pages/event.njk
> update event ticket info

- events/app/views/pages/event.njk
- prismic-model/events.json
- server/content-model/events.js
- server/services/prismic-parsers.js
> Costly events

- events/app/views/pages/event.njk
- exhibitions/app/views/pages/exhibition.njk
Noticed the card wasn't showing correctly on Slack.
> Event twitter info

- router/nginx.conf
> send 1% of people to v2 of whats on

- router/nginx.conf
[50 / 50 split](https://www.youtube.com/watch?v=DI3pMj9Pkx4).
> ramp up what's on to 50%

- events/app/views/pages/event.njk
- prismic-model/events.json
- server/content-model/events.js
> make event cost a string

- deploy/terraform_apply_service.sh
- infra/apply_task_definition.sh
As we ask for confirmation in the python scripts.
> auto approve terraform update via deploy scripts

- router/nginx.conf
- whats_on/app/routes.js
Drupal has some strange restrictions that we don't understand.
Let's keep using router for this.
> Use router for redirecting what's on

- .scripts/webapp/development/package.json
- catalogue/webapp/next.config.js
- catalogue/webapp/yarn.lock
Seemed like a useful thing for the community, so turned it into a module.
Best to be dog-fooding.
> use next-plugin for transpiling modules

- server/views/components/article-body/article-body.njk
> Show copyright on image

- server/views/components/event-promo/event-promo.njk
Does exactly what it says in the title
> Add ID to eventpromo

- events/app/controllers.js
- events/app/routes.js
- events/app/views/pages/event.njk
- events/app/views/pages/events.njk
- server/index.js
- server/services/prismic-parsers.js
- server/services/prismic.js
As an events organiser, I would like to be able to promote events to users that are in the same series.
> event series page v1 added

- server/services/prismic.js
> Put back ordring of event for whats on

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- package.json
- yarn.lock
Based on or conversations this morning, it felt as though trying to explain our process externally, it might be a good way to document it internally.
The COC was taken from the [Contributor Covenant](https://www.contributor-covenant.org/), as if we have a contributing doc, we should have a COC. We should have one for internal / contractor  / freelance reasons too.
[More, unstructured, notes here](https://github.com/orgs/wellcometrust/teams/experience/discussions/7).
> Add a contributing and code of conduct docs

- build-speedtracker.sh
Add the correct speedtracker endpoints.
> add correct speedtracker endpoints

- server/services/prismic.js
> only change order of events on whats on

- router/terraform/cloudfront.tf
Fixes #2260 
I can see this rearing it's ugly head when tickets are sold out too...
> remove cache from /eventbrite/*

- eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk
As it's not free.
this for now, more intelligent for later.
> remove free ticket messaging from eventbrite button

- server/controllers/utils.js
- server/controllers/wordpress.js
- server/routes/index.js
> rename controllers in server to be more specific

- client/scss/components/_promo.scss
- common/views/components/Promo/Promo.js
- server/views/components/numbered-list/numbered-list.njk
- server/views/components/promo/promo.njk
- server/views/pages/curated-lists.njk
- server/views/pages/list.njk
Fixes the promo type label to not be capitalised but also take position in series into account.
> decapitalise promo type and pull in positionInSeries

- common/.flowconfig
- events/app/controllers.js
- events/app/views/pages/event.njk
- prismic-model/events.json
- server/content-model/events.js
- server/data/facility-promos.js
- server/services/prismic-parsers.js
- server/services/prismic.js
- server/views/components/event-promo/event-promo.njk
> introduce the concept of fully booked to event times

- events/app/views/pages/event.njk
> use range property on event times

- eventbrite/app/controllers.js
- eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk
- server/views/components/event-promo/event-promo.njk
Remove the messaging for paid events.
> remove waitinglist messaging from paid events

- events/app/views/pages/event.njk
Just noticed we'd missed replacing this one
> use CaptionedImageComponent

- catalogue/webapp/pages/works.js
- common/views/components/DefaultPageLayout/DefaultPageLayout.js
- server/views/partials/analytics.njk
Tying up some loose ends on the the next app.
Added appVersion too to see if we can use it in GA - could be really useful for tracking bugs / improvements etc.
> update analytics on catalogue and add appVersion

- common/views/components/Tags/Tags.js
- events/app/views/pages/event.njk
- server/extensions/component-jsx.js
Fixes #2078 
Also fixes the key warning coming from React.
> add event title to event mailto links

- server/views/layout/default.njk
Just waiting on confirmation of final wording
> Added global message about early closing

- common/model/opening-hours.js
- common/views/components/OpeningHours/OpeningHours.config.js
- common/views/components/OpeningHours/OpeningHours.js
> Jsxify opening hours

- common/views/components/FooterNav/FooterNav.config.js
- common/views/components/FooterNav/FooterNav.js
> Created FooterNav component

- common/icons/index.js
- common/icons/location.js
- common/model/opening-hours.js
- common/model/organization.js
- common/utils/json-ld.js
- common/views/components/FindUs/FindUs.config.js
- common/views/components/FindUs/FindUs.js
References #2284
Converts FindUs (part of the footer) to JSX.
> Add FindUs component

- common/views/components/DefaultPageLayout/DefaultPageLayout.js
- common/views/components/Footer/Footer.js
- common/views/components/OpeningHours/OpeningHours.js
References #2270
Adds the Footer to the Next app.
> Next footer

- server/views/layout/default.njk
Uses the `componentJsx` version of the footer in the V2 app.
> Use componentJsx for the v2 footer

- catalogue/webapp/pages/work.js
- catalogue/webapp/pages/works.js
- common/views/components/DefaultPageLayout/DefaultPageLayout.js
- common/views/components/Header/Header.js
Correctly highlight the site section we're in
> Update active nav item

- server/views/partials/analytics.njk
The analytics have tanked and this is the only change.
> remove app version from analytics

- server/views/layout/default.njk
> remove message for closing times

- events/app/controllers.js
- server/index.js
- server/services/prismic.js
> Don’t show past events on event series; order ascending

- router/terraform/cloudfront.tf
They ID is used as a key to for the cache behaviours so needed updating.
> update the origin IDs being used by the cache behavoiurs

- server/services/prismic-parsers.js
> allow HTML in contributor description

- events/app/controllers.js
As a @hthair I'd like to use the series dimension for events as well as articles.
I'll be sure to add it to the annotations.
> add event series to Google analytics

- server/views/components/event-promo/event-promo.njk
Quick version of adding the series to the promo - more work to be done with Gareth O comes back.
> add event series to promo

- catalogue/webapp/next.config.js
- catalogue/webapp/pages/_document.js
- catalogue/webapp/pages/work.js
- catalogue/webapp/pages/works.js
- common/data/series.js
- common/package.json
- common/utils/image-sizes.js
- common/views/components/DefaultPageLayout/DefaultPageLayout.js
- common/views/components/Header/Header.js
- common/views/components/Promo/Promo.config.js
- common/views/pages/_document.js
Trims it down pretty significantly.
I'd like to add the styles to the actual component though before moving forward to make sure this does actually make a difference.
> make really critical scss

- catalogue/webapp/pages/_document.js
- common/styles/works.scss
- common/views/pages/_document.js
Allowing us to pass _all_ the CSS we need through without interrupting the service on v2.0.
Hopefully allowing us to get this out sooner.
> _document as function to be able to pass specific CSS through

- server/model/basic-page.js
- server/services/prismic-parsers.js
✨ Feature  
Adds a BasicPage type and function to output that type from a prismicDoc
> Basic page type

- server/services/prismic.js
> pass through displayType for comic

- common/views/components/Header/Header.js
🍔 🍔 🍔 🍔 🍔 🍔 🍔 🍔 
Now with added 🍔 .
I'm going to leave the search for now, well, as it might be best that we remove it for now, unless we're using to gather user info?
> use JS to make fancy burgers

- .circleci/config.yml
- catalogue/webapp/docker-compose.yml
- catalogue/webapp/next.config.js
- catalogue/webapp/package.json
- catalogue/webapp/yarn.lock
- common/package.json
Allows us to publish this somewhere static.
Options:
- ~cardigan~
__TODO__
> Bundle analyzer static reporting

- .circleci/config.yml
Messed up the cache.
Fixed the cache.
> fix repo caching in circle on the catalogue

- events/app/views/partials/event_without_schedule.njk
> track event booking buttons

- common/views/components/EventScheduleItem/EventScheduleItem.js
- events/app/views/partials/event_with_schedule.njk
Remove round corners from schedule list images and tidy mobile type.
> No round corners

- common/styles/non-critical.scss
> removed instagram_thumbnail.scss import

- prismic-model/articles.json
Just removing it from the model for now until we have some larger conversations around how this might work. This will stop us creating content in Prismic that might be hard to back out of.
> remove page display

- router/nginx.conf
Does what it says in the title.
> Rewrite goddess event-series url to the event with schedule

- common/styles/base/_container.scss
- events/app/views/partials/event_with_schedule.njk
Allows the container to be framed by a background image at widths narrower than the maximum container width (previously only the top strip of this background would display).
> Allow container to have frame

- common/styles/styleguide/_styleguide.scss
- common/views/components/Footer/Footer.config.js
- common/views/components/Header/Header.config.js
- common/views/components/InfoBanner/InfoBanner.config.js
- common/views/components/layout/preview-no-container.js
- common/views/components/layout/preview.js
Making sure components in Cardigan have some data if they're going to be displayed, and adding in JS.
> Cardigan tidy

- exhibitions/app/views/pages/exhibition.njk
- server/content-model/exhibition.js
- server/services/prismic-parsers.js
> remove reference to exhibition body

- common/model/installations.js
- common/services/prismic/installations.js
- common/services/prismic/parsers.js
- prismic-model/js/installations.js
- prismic-model/js/parts/timestamp.js
- prismic-model/json/installations.json
- whats_on/app/views/pages/installation.njk
Adding the start and end to an installation.
Sorry for the stacked PRs once the first ones get merged, I'll merge it into these to make it clearer. I didn't compare against the parent branch, as then everything merges downwards and makes the initial PR a nightmare.
https://github.com/wellcometrust/wellcomecollection.org/commit/3205dc58096973ed1ef2acaa28d8a612f81d3079
> Installation ui dates

- catalogue/webapp/pages/works.js
- common/services/prismic/article.js
- common/views/components/DefaultPageLayout/DefaultPageLayout.js
- common/views/components/EventScheduleItem/EventScheduleItem.js
- common/views/components/Header/Header.js
- common/views/components/Pagination/Pagination.js
- events/app/views/partials/event_with_schedule.njk
- package.json
- yarn.lock
Now with even stronger type checking!
> upgrade flow

- server/middleware/error.js
- server/views/pages/error.njk
Prismic then works out how to inject the content on the page.
> add prismic preview code onto 4040 pages

- common/model/installations.js
- common/model/place.js
- common/services/prismic/fetch-links.js
- common/services/prismic/installations.js
- common/services/prismic/parsers.js
- prismic-model/json/events.json
- whats_on/app/views/pages/installation.njk
Add place and description to installation:
> add description and place to installation

- whats_on/terraform/services.tf
The service modules seem to be setup to have a URL prefix to point at a service, and then strip that, and pass only the leftovers to the application.
We have the setup that installations, what's on, exhibitions, and events, all which have root urls (`/exhibitions`) will all be part of the `whats_on` application.
Alternatives would be:
* Edit the modules to accept a list and break the theory of 1 URL per service
* Have `/whats_on/installations`
Neither of which are what we want.
@kenoir ^
> add listener to what_on service for installations

- events/app/views/pages/event-series.njk
Closes #2355
Adds copy from Jen.
> No upcoming events messaging

- common/views/components/Header/Header.js
- server/views/components/header/header.njk
As search is returning nothing relevant to what is being searched for we have decided to disable it for the time being until we have a more useful search.
> remove search for now

- README.md
As a person stumbling across the repo I'd like to know what this is all about.
---
Thought that the technical details could live in their folders, seems as this is front of house, it should probably reflect more what we're trying to achieve so I nicked the lovely stuff from notion.
CC @GarethOrmerod as I can't seem to add him as a reviewer.
> update core readme to reflect our vision

- client/js/app.js
As we don't have a search in the header any more and it's causing an error
🐛 Bugfix
> removed header search js

- server/views/components/article-body/article-body.njk
TASL info isn't pulling through properly.
> use the correct tasl stuff on article body

- router/nginx.conf
> Added /info to v2 urls

- events/app/views/partials/event_with_schedule.njk
> Change contributor to In collaboration with

- events/app/views/partials/event_without_schedule.njk
> use contributor model for events contributors

- common/views/components/EventScheduleItem/EventScheduleItem.js
> better event labelling on event schedules

- common/utils/format-date.js
- server/filters/format-date.js
- server/views/pages/opening-times.njk
Prevents isDatePast returning true too soon, which means modified opening times will show correctly.
> Fix is date past

- server/content-model/events.js
- server/services/prismic-parsers.js
We've called all other types to do with website display, 'UiThingy'.
> Use 'ui' instead of 'display' for consistency

- exhibitions/terraform/services.tf
- whats_on/terraform/services.tf
Use whats_on service to serve exhibition content.
__Next up__ remove exhibition files from exhibitions app.
> setup route for individual exhibitions to be served from whats_on app

- whats_on/terraform/services.tf
> rename path rules uniquely in whats_on

- common/services/prismic/exhibitions.js
one last thing before moving this over to whatson
> null check text document before setting it's size

- server/controllers/content.js
- server/views/layout/default.njk
- server/views/pages/article.njk
- whats_on/app/controllers.js
- whats_on/app/views/pages/exhibition.njk
I'll be sure to add it into events etc - just so Lalita can use it now.
> add preview properly to exhibitions

- server/controllers/content.js
- server/services/prismic-parsers.js
> add link resovler and preview for installations

- server/views/layout/default.njk
- whats_on/app/views/pages/exhibition.njk
I'm going to try and get some tests in for this as we migrate.
> add opening hours props to exhibition opening hours

- catalogue/webapp/pages/work.js
- server/controllers/work.js
> use 7 rather than 8 digita b number for sierra records

- server/extensions/component-jsx.js
Not great, but better (not silent).
I'd rather spend some time getting Jest into other more important parts (i.e. does the page render).
> at least tell the console where the error is when we have a JSX error

- whats_on/app/views/pages/installation.njk
> add spacing beneath installation tags

- server/routes/index.js
Got it from the sentry error.
Interesting question around why people are going there, but could just be a bot.
> check for URI before running regex on it

- catalogue/webapp/pages/work.js
- common/views/hocs/withToggler.js
As @davidpmccormick was working on #2473 we realised toggler typing was broken.
Worth a read:
https://flow.org/en/docs/react/hoc/
> fix typing on withToggler HOC

- server/views/components/article-body/article-body.njk
I would prefer to add some sort of placeholder image, but this will work for now.
> only render image if it has an contentUrl

- common/services/prismic/fetch-links.js
- common/services/prismic/installations.js
- prismic-model/js/installations.js
- prismic-model/js/parts/description.js
- prismic-model/json/installations.json
> couple of fixes to make installations work

- catalogue/webapp/package.json
- catalogue/webapp/yarn.lock
I'm going to investigate how we upgrade things with greenkeeper, mono-repo style though.
> upgrade all packages in catalogue app

- client/js/app.js
- common/views/components/BasicBody/BasicBody.js
- prismic-model/js/installations.js
- prismic-model/json/installations.json
- whats_on/app/views/pages/installation.njk
Not sure why I didn't think to just move the body into the side.
> reinstate installation body

- common/services/prismic/opening-times.js
Reduce the period during which the opening times alert is displayed
> show alert one week before modified opening hours apply

- .github/PULL_REQUEST_TEMPLATE.md
Sick of hitting cmd+a 🔙 .
Two simple questions, three simple checkboxes, seems like it should be doable if we think they're valuable.
> simplify the PR template

- events/app/controllers.js
Got the 500s from Athena.
Need to remember to be protective, especially as this sets of alarms that can make us feel complacent.
> only run event series code once we know there is an event series

- client/js/components/opening-hours.js
- common/services/prismic/opening-times.js
- common/styles/components/_opening_hours.scss
- common/styles/utilities/_root-scope-classes.scss
- common/views/components/DefaultPageLayout/DefaultPageLayout.js
- common/views/components/Footer/Footer.js
- common/views/components/Index/index.js
- common/views/components/OpeningHours/OpeningHours.js
- common/views/components/OpeningHoursTable/OpeningHoursTable.js
- common/views/components/OpeningHoursTableGrouped/OpeningHoursTableGrouped.config.js
- common/views/components/OpeningHoursTableGrouped/OpeningHoursTableGrouped.js
- common/views/components/PageWrapper/PageWrapper.js
- server/controllers/content.js
- server/view/render.js
- server/views/layout/default.njk
- server/views/pages/opening-times.njk
- whats_on/app/views/pages/exhibition.njk
Fixes/References #2506
**Larger screens:**
**Small screens:
**
> Opening times updates

- client/js/components/opening-hours.js
- common/services/prismic/opening-times.js
- common/styles/components/_opening_hours.scss
- common/styles/utilities/_root-scope-classes.scss
- common/views/components/DefaultPageLayout/DefaultPageLayout.js
- common/views/components/ExceptionalOpeningHoursTable/ExceptionalOpeningHoursTable.js
- common/views/components/Footer/Footer.js
- common/views/components/Index/index.js
- common/views/components/OpeningHours/OpeningHours.js
- common/views/components/OpeningHoursTable/OpeningHoursTable.js
- common/views/components/OpeningHoursTableGrouped/OpeningHoursTableGrouped.config.js
- common/views/components/OpeningHoursTableGrouped/OpeningHoursTableGrouped.js
- common/views/components/PageWrapper/PageWrapper.js
- server/controllers/content.js
- server/view/render.js
- server/views/layout/default.njk
- server/views/pages/opening-times.njk
- whats_on/app/views/pages/exhibition.njk
> Modified hours display logic

- server/controllers/content.js
- server/routes/index.js
Fixes/References #2526 
Using the new Prispal API.
https://github.com/wellcometrust/prispal
https://prispal.glitch.me/info-pages/what-we-do/proposing-online-article
## Questions
* We use the promo image as the header image. If we don't do this, do we want to have it as part of the body?
For us wanting to move onto the new site.
A demo site so we can see what the content looks like 1-1.
> add prototype route for basicPages

- dash/pa11y_dashboard/Dockerfile
- dash/pa11y_dashboard/Makefile
- dash/pa11y_dashboard/README.md
- dash/pa11y_dashboard/docker-compose.yml
- dash/pa11y_dashboard/docker-entrypoint.sh
- dash/pa11y_dashboard/terraform/iam.tf
- dash/pa11y_dashboard/terraform/locals.tf
- dash/pa11y_dashboard/terraform/services.tf
- dash/pa11y_dashboard/terraform/task_definition.json.template
- dash/pa11y_dashboard/terraform/terraform.tf
- dash/pa11y_dashboard/terraform/topics.tf
- dash/terraform/ami.tf
- dash/terraform/asg.tf
- dash/terraform/ecs.tf
- dash/terraform/iam.tf
- dash/terraform/locals.tf
- dash/terraform/terraform.tf
- dash/terraform/topics.tf
- dash/terraform/userdata.tf
- dash/terraform/variables.tf
Setting up [pa11y-dashboard](https://github.com/pa11y/pa11y-dashboard) as a service.
Almost there, but for reason the instances aren't registering with the target group.
> beginnings of pally

- common/services/prismic/opening-times.js
Sorry @gestchild I couldn't figure out what the types are and it's breaking master.
> opening hours ducktyping

- server/controllers/content.js
- server/routes/index.js
- server/views/pages/list.njk
Making it easier to audit the drupal content.
> Drupal info pages list

- common/views/components/Buttons/Control/Control.js
> Use href attribute for url value

- catalogue/webapp/Dockerfile
See here:
https://github.com/yarnpkg/yarn/issues/5477
> Fix Node version on catalogue docker file

- router/nginx.conf
For those who want to see the catalogue app before we release it.
Letting us see the app pre-release.
> push /catalogue through to v2

- catalogue/webapp/pages/catalogue/works.js
- events/app/views/partials/event_without_schedule.njk
- server/views/pages/search.njk
Picking off a couple of plain-text links that missed the initial round.
> Add some more plain-text blocks

- prismic-model/js/exhibitions.js
- prismic-model/json/exhibitions.json
References #2493 
For us to get the drupal data in
It get's the drupal data it
> add drupal export data to exhibitions

- common/services/prismic/multi-content.js
- common/services/prismic/types.js
- server/controllers/content.js
- server/routes/index.js
The 📰 
Letting them write the 🗞
> Press releases

- infra/deploy.py
Reverts wellcometrust/wellcomecollection.org#2554
> Revert "Substitute urllib for requests"

- whats_on/app/views/pages/exhibition.njk
Fixes/References #
👕 
Making use of the reasoning around when to use primary vs secondary links.
> make accessability link secondary

- common/views/components/BasicBody/BasicBody.js
- common/views/components/BasicPromo/BasicPromo.js
- common/views/components/ContentList/ContentList.js
- common/views/components/ContentList/ContentListItems.js
People looking at the info pages
Makes it prettier to look at
> plainify content list promos

- common/views/components/BasicBody/BasicBody.js
Me
Giving some breathing room under the image until we get the slices into Cardigan
> add a little bit of spacing under the body image

- common/model/installations.js
- common/services/prismic/installations.js
- common/services/prismic/parsers.js
- prismic-model/js/installations.js
- prismic-model/js/parts/captioned-image-gallery-slice.js
- prismic-model/json/installations.json
- whats_on/app/views/pages/installation.njk
The content team for their installation sprint
Just putting the right info on the page.
This is not styled.
> a few fixes to installations

- common/services/prismic/exhibitions.js
> check if exhibit link is broken

- common/views/components/CopyUrl/CopyUrl.js
- server/views/pages/work.njk
Font size design tweaks after chat with GarethO and @Heesoomoon.
> Make tertiary buttons HNM5 at all sizes

- prismic-model/convert.js
- prismic-model/json/collection-venues.json
- prismic-model/json/info-pages.json
> convert all models if model not given

- common/views/components/Quote/Quote.js
> support wordpress quotes

- prismic-model/js/pages.js
- prismic-model/json/books.json
- prismic-model/json/pages.json
Editors and me
Not letting the beta work get in their way, but allowing me to use it.
> put tags behind a beta tab

- common/model/contributors.js
- common/services/prismic/parsers.js
- common/views/components/Contributor/Contributor.js
- common/views/components/Templates/BasicPage/BasicPage.js
- common/views/components/Templates/BasicPage/InstallationPage.js
Fixes/References #2367 
The contributors to installations and the people who see them and want to know who did them.
By making ☝️ visible
> add contributors to installation page"

- client/js/components/content-slider.js
- common/styles/components/_image_gallery.scss
- common/styles/components/_slider.scss
- common/styles/components/_slider__in-basic.scss
- common/styles/utilities/_mixins.scss
Makes the gallery appearance acceptable on a basic page:
> Basic gallery styling tweaks

- common/services/prismic/installations.js
- common/views/components/InstallationPromo/InstallationPromo.js
- whats_on/app/views/components/exhibits/exhibits.njk
References #2367 
People who want to see what is exhibited in an exhibition
Fixes the bugs that stop the component showing.
> fix the exhibits list on exhibition pages

- server/utils/body-parser.js
- server/views/components/article-body/article-body.njk
Developers wanting to deploy
Fixes the build
> parse WP standfirst in prismic style

- common/styles/utilities/_root-scope-classes.scss
- common/views/components/PageHeaders/BasicHeader/BasicHeader.js
- common/views/components/Templates/BasicPage/BasicPage.js
- common/views/components/Templates/BasicPage/InstallationPage.js
- router/terraform/cloudfront.tf
- whats_on/app/controllers.js
Consistinites
Making sure we use the big tags for "Part of"
> use normal tags for installations

- whats_on/app/views/pages/exhibition.njk
References #2367 
Merge once we're happy with it.
people who want to know what is exhibited in an exhibition
Showing them the exhibits on an exhibitions
> remove exhibitsOnExhibitions flag

- build_and_deploy_cardigan.sh
- cardigan_beta/.storybook/addons.js
- cardigan_beta/package.json
- cardigan_beta/stories/index.js
- cardigan_beta/yarn.lock
People who want to see our components as living things that contain multiple types of data, and have varying displays dependant on the data supplied
Allows you to see which parts of a component are dynamic, what happens when you get unexpected content (different characters, lengths etc).
> add nkobs to story book

- .circleci/config.yml
- cardigan_beta/.storybook/.babelrc
- cardigan_beta/.storybook/webpack.config.js
- cardigan_beta/package.json
- yarn.lock
People who hate red builds and love cardigans
Making green builds and deploying cardigans.
> use react babel plugin

- common/views/components/BasicBody/BasicBody.js
- common/views/components/BasicPromo/BasicPromo.js
- common/views/components/Image/Image.js
- common/views/components/SearchResults/SearchResults.js
Fixes/References #2617 
People wanting to see nice looking embedded lists in content
Making the lists look beautiful.
This will help me move onto allowing event series etc to be embedded.
> first pass of basic inline links

- common/views/components/SearchResults/SearchResults.js
> fix url used for event series on search results

- .circleci/config.yml
- catalogue/terraform/terraform.tf
- catalogue/webapp/Dockerfile
Devs trying to deploy the catalogue app
allowing us to deploy multiple versions
> Build catalogue with tag

- client/js/components/newsletter-signup.js
- common/styles/base/_wellcome_normalize.scss
- common/views/components/HTMLInput/HTMLInput.js
- common/views/components/NewsletterPromo/NewsletterPromo.js
- common/views/components/NewsletterSignup/NewsletterSignup.js
- server/controllers/content.js
- server/routes/index.js
References #2431 #2601
Updating copy in the newsletter signup form, and removing the default (normalize) `fieldset` styles.
> Newsletter copy changes

- common/services/prismic/pages.js
- router/nginx.conf
- server/controllers/content.js
- server/routes/index.js
Fixes/References #2526 
People who want nicer pages
Redirects them to the nicer pages.
`/press/*` for now.
> Redirect from drupal path

- catalogue/terraform/terraform.tf
> add nextjs listeners to the catalogue app

- catalogue/webapp/pages/works.js
- common/views/components/Pagination/Pagination.js
People who paginate (band name?)
Adds pagination.
For some reason it doesn't seem to respect the fact that is next links, and refreshed the page.
> put pagination on the bottom of works

- common/views/components/NewsletterPromo/NewsletterPromo.js
- common/views/components/NewsletterSignup/NewsletterSignup.js
- server/routes/index.js
- server/views/pages/newsletter.njk
Making the newsletter available beneath the (pre-existing) /pages route.
> Move newsletter to /pages

- common/views/components/ExhibitionPromo/ExhibitionPromo.js
> don’t show dates for permanent exhibitions

- common/views/components/PageHeaders/BasicHeader/BasicHeader.js
> add padding to basic page title

- common/services/prismic/multi-content.js
- common/views/components/Templates/BasicPage/BasicPage.js
- common/views/components/Templates/BasicPage/InstallationPage.js
- common/views/components/Templates/BasicPage/Page.js
👩‍⚖️ and 👮 
Some content types will have default orderings, this adds this to the search results.
> Search results ordering

- common/views/components/Pagination/Pagination.js
Fixes #2662 
Just to get it working, I'd like to consolidate how we do pagination, but was taking longer than I thought.
> pagination regression fix

- server/routes/index.js
🚌 
Adding Core activity routes.
> add basic root routes

- common/model/pages.js
- common/services/prismic/pages.js
- server/controllers/content.js
- server/views/layout/default.njk
🗺 
Makes sure people know where they are on the site.
> loosely type site section

- common/views/components/NewsletterPromo/NewsletterPromo.js
- common/views/components/NewsletterSignup/NewsletterSignup.js
- router/nginx.conf
Updating newsletter page references to `/newsletter` rather than `/pages/newsletter`.
> Use /newsletter instead of /pages/newsletter

- common/views/components/Promo/Promo.js
Don't show the label on the work promos.
> Hide label on work promos (hack)

- client/js/components/content-slider.js
> Fix the digital stories nav

- common/views/components/EventPromo/EventPromo.js
> check for the content URL before using the image

- events/app/views/partials/event_without_schedule.njk
Ensures fully booked status shows on event page
Think the logic is right...
> Show fullyBooked if it is and  eventbriteId or bookingEnquiryTeam

- common/styles/components/_map.scss
- common/styles/non-critical.scss
- common/views/components/Map/Map.js
Visitors to the website
Makes the map a more usable size on small screen devices
> change map aspect ratio for small screens

- common/model/books.js
- common/model/multi-content.js
- common/services/prismic/books.js
- common/services/prismic/fetch-links.js
- common/services/prismic/multi-content.js
- common/views/components/SearchResults/SearchResults.js
- server/controllers/content.js
- server/routes/index.js
🐛 
Shows them all our books (with 16:9 promo)
> add book list with 16:9 promos

- server/views/pages/opening-times.njk
> update cafe link and remove friday late link from opening times

- common/model/books.js
- common/services/prismic/books.js
- common/services/prismic/parsers.js
- common/styles/base/_responsive-defaults.scss
- common/styles/utilities/_root-scope-classes.scss
- common/views/components/BaseHeader/BaseHeader.js
- common/views/components/BasePage/BasePage.js
- common/views/components/BasePage/BookPage.js
- common/views/components/Body/Body.js
- common/views/components/Images/Images.js
- server/views/pages/book.njk
Fixes/References #2490 
People who like to see books
Shows them the cover of the book
forked from: #2688
> Books featured image

- common/views/components/NewsletterSignup/NewsletterSignup.js
- server/data/facility-promos.js
- server/views/pages/homepage.njk
- server/views/pages/newsletter.njk
References #2691 
Fixes #2692
still awaiting the last bit of text to replace 'the free destination for the incurably...'
> Text changes to newsletter sign up and homepage

- common/views/components/BaseHeader/TexturedBackground.js
People with 👀 
Makes things prettier
> nicer textured background ratio

- prismic-model/js/parts/body.js
- prismic-model/json/articles.json
- prismic-model/json/books.json
- prismic-model/json/installations.json
- prismic-model/json/pages.json
Adds h3's to body text.
It was styled when @davidpmccormick did some work with @GarethOrmerod.
https://github.com/wellcometrust/wellcomecollection.org/blob/master/common/styles/components/_body_text.scss#L10-L12
https://github.com/wellcometrust/wellcomecollection.org/blob/master/common/styles/base/_typography.scss#L79-L88
> add heading3 to body text

- common/styles/base/_responsive-defaults.scss
> use width on responsive images

- router/nginx.conf
👪 
Makes the V2 homepage the homepage
> route homepage through to V2

- common/views/components/Footer/Footer.js
> remove press from footer

- whats_on/app/views/components/whats-on-list-header/whats-on-list-header.njk
- whats_on/app/views/pages/whats-on.njk
Before: https://wellcomecollection.org/whats-on
> add a bit of padding to whats_on

- router/nginx.conf
> route visit us and what we do properly

- router/nginx.conf
> don't route /exhibitions/* to V2

- server/controllers/content.js
Book publishers
Ordering books by date published.
This doesn't address the data issue we have #2733
> order books by pubished date

- server/controllers/content.js
> add books to what we do section

- server/package.json
- server/views/partials/monitoring.njk
- server/yarn.lock
Upgrading raven for housekeeping.
> raven upgrade

- client/js/components/eventbrite-ticket-button.js
- devappy/rules.json
- eventbrite/app/controllers.js
- eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk
- events/app/views/partials/event_without_schedule.njk
Going through sentry errors and spotted this.
Not sure how it hasn't stung us yet given that we don't update the eventbrite button properly.
> don't use button component for events, and add unavailable state

- common/views/components/EventPromo/EventPromo.js
- common/views/components/ExhibitionPromo/ExhibitionPromo.js
- server/views/pages/homepage.njk
> Track promo position on homepage

- whats_on/app/views/pages/exhibition.njk
Spotted in the wild by @Heesoomoon 
We're serving up some rather large images on the exhibitions page.
Makes me think #2734 is pressing.
> use the right image sizes on exhibitions pages

- prismic-model/js/events.js
- prismic-model/js/installations.js
- prismic-model/js/parts/boolean.js
- prismic-model/json/events.json
Devs
Makes it easier and more consistent to change the event model
> put events model into JS

- cardigan_beta/.storybook/addons.js
- cardigan_beta/.storybook/config.js
- cardigan_beta/.storybook/preview-head.html
- cardigan_beta/package.json
- cardigan_beta/stories/components/BaseHeader.js
- cardigan_beta/stories/components/Body.js
- cardigan_beta/stories/components/Links.js
- cardigan_beta/stories/content.js
- cardigan_beta/yarn.lock
- common/views/components/Body/Body.js
* Adds [`faker`](https://www.npmjs.com/package/faker) content to the testing
* Makes `app.js` run on component change
* Puts the body into the components block
* Composes ☝️ into the `BasePage`
> add Body to storybook

- common/views/components/Index/index.js
- events/app/views/partials/event_with_schedule.njk
- events/app/views/partials/event_without_schedule.njk
Deprecate the old captioned image in favour of the UiImage.
> Use the new UiImage on event

- cardigan_beta/stories/components/Body.js
- common/views/components/Body/Body.js
so the body component renders in storybook
> Storybook fix

- common/utils/analytics.js
References #2472 
Use both trackers.
Turns out I had my privacy turned high, so GA wasn't working.
> track catalogue ga on both accounts

- catalogue/terraform/terraform.tf
- catalogue/webapp/pages/embed.js
- catalogue/webapp/server.js
- common/styles/utilities/_root-scope-classes.scss
- common/views/components/ImageViewer/ImageViewer2.js
- common/views/components/ImageViewer/ImageViewerImage.js
References #2382 
People who want to embed our content into their blogs etc.
Creates a page we can add into an iframe.
If this proves to be something people use, we can start optimising it further (e.g. extract all the superfluous CSS).
> Work embed

- cardigan_beta/stories/global/palette/README.md
- cardigan_beta/stories/global/palette/palette.js
- cardigan_beta/stories/global/typography/README.md
Moving palette into Storybook.
> Add palette to Storybook

- build/nginx.conf
- common/views/components/Header/Header.js
- nginx_webapp/Dockerfile
- nginx_webapp/README.md
- nginx_webapp/nginx.conf
Moves our lighthouse rating from 12 => 53.
Still way under the 80 we get on the current page.
> Add gzip to nginx

- cardigan_beta/stories/global/icons/README.md
- cardigan_beta/stories/global/icons/icons.js
Displays our svg icons in Storybook
> Add icons to Storybook

- common/views/components/FooterSocial/FooterSocial.js
> bye tumblr

- router/nginx.conf
As books came through with `drupalPath`s - they will now be directed to the new books pages.
> add books to v2 route

- common/views/components/SearchBox/SearchBox.js
> use JSON.stringify on tracking for clear search

- common/styles/base/_fonts.scss
Uses the static URL for static assets.
💥
> use i.weco.org for fonts

- client/embed.js
- client/gulpfile.js
- client/js/components/image-viewer.js
Related to #2786 
When combined, the powers of these PRs should allow us to start testing some sort of oEmbed.
> add a hypothetical embed script to be included with the oembed endpoint

- .github/PULL_REQUEST_TEMPLATE.md
> Remove ticket reference from PR template we're using projects.

- common/views/components/PageWrapper/PageWrapper.js
Running a test to see what the site looks like in API V2 mode.
Plan is to parse V2 into the shape of V1 so we don't have to change any UI, and V2 is not stable.
> make sure we store flags in clientStore

- common/views/components/BasePage/BookPage.js
- common/views/components/BasePage/InstallationPage.js
> add book tag to books

- common/views/components/BasePage/BookPage.js
Put order link behind the swtich.
> put the order link behind the books switch

- server/services/prismic-body-parser.js
- server/views/components/article-body/article-body.njk
Use Prismic HTMLString when sending text to FeaturedText
Fixes #2835
> send HTMLString to standfirst from prismic

- whats_on/app/views/pages/exhibition.njk
Fixing Broken promos on exhibition pages
> Uppercase P

- common/views/components/Index/index.js
- server/views/components/article-body/article-body.njk
make sure HTML is parsed in the article.
> use primihtmlblock for article body text

- cardigan_beta/.storybook/config.js
- cardigan_beta/stories/components/Promos.js
- cardigan_beta/stories/wip/BookPromo.js
- whats_on/app/yarn.lock
Lets us group types of components under sub-sections in Storybook and order stories alphabetically. Closes #2809.
> Add hierarchy separator

- .circleci/config.yml
- .gitignore
- common/package.json
- server/middleware/error.js
> add whats_on tests to cirleci

- catalogue/webapp/package.json
- catalogue/webapp/pages/work.js
- catalogue/webapp/pages/works.js
- catalogue/webapp/utils/remap-v2-to-v1.js
- catalogue/webapp/yarn.lock
- common/views/components/PageWrapper/PageWrapper.js
Internal people wanting to see what the V2 API world might look like.
It looks like a baron place from an image perspective 🌚. But a wealth of knowledge from a data perspective 📜 .
Allows us to swap into the API v2 version via a switch (now using unleash).
> Api v2 test api call

- .circleci/config.yml
Haven't pushed the docker container for four days.
> actually push catalogue app to docker

- server/data/facility-promos.js
- whats_on/app/controllers.js
> Removed spirit booth promo from what’s on

- catalogue/webapp/pages/work.js
For the API V2 test.
Shouldn't affect anything else.
> check for image on work before trying to render

- catalogue/webapp/server.js
Decoupling us a little more from the Prismic FF.
> allow setting of cohort from query string in next app

- common/views/components/Contributor/Contributor.js
- common/views/components/Contributors/Contributors.js
- events/app/views/partials/event_with_schedule.njk
- events/app/views/partials/event_without_schedule.njk
> remove title from contributors component

- server/services/prismic-parsers.js
- server/services/prismic.js
- server/utils/flags.js
#2848 
todo
- [  ] make sure the image is changed on the list page as well.
> change image dependant on cohort and ID of event for A/B test

- CONTRIBUTING.md
- ISSUE_TEMPLATE/feature.md
- ISSUE_TEMPLATE/research.md
@hthair 
Allows 👩‍🔬 to add their research to github, which makes it discoverable, surface through channels (slack) and 👍
> add research template to issue template and description of research tags

- whats_on/app/controllers.js
We should show the installations tag irrespective.
I wish we had a way to do this synchronously.
> show installations tag

- prismic-model/js/parts/geolocation.js
- prismic-model/js/places.js
- prismic-model/json/places.json
Pre-empting the need to create places pages for accessability on the conversation I had with @Heesoomoon saying it's on the cards somewhere.
Will add the rendering next.
> add body to places

- common/model/places.js
- common/services/prismic/parsers.js
- common/services/prismic/places.js
- common/views/components/BasePage/PlacePage.js
- common/views/components/Index/index.js
- server/controllers/content.js
- server/routes/index.js
- server/views/pages/place.njk
See #2881 
Feels like a lot of this can be abstracted away neatly somewhere.
> add places rendering

- common/model/organization.js
- yarn.lock
> add flags for publis access and free to Wellcome organisation

- events/app/views/pages/events.njk
- whats_on/app/views/pages/exhibitions.njk
> remove links to past events and exhibitions

- catalogue/webapp/server.js
So we can start using the V2 API.
> set cohort cookie properly from catalogue app

- server/middleware/error.js
Need to chose a way, and make it universal.
> set preview on preview.

- catalogue/webapp/pages/works.js
Noticed this while looking into other health issues.
Typing here would help.
> serve an error when we get one back from the API

- catalogue/webapp/pages/work.js
- common/utils/analytics.js
- common/views/components/CopyUrl/CopyUrl.js
- common/views/components/ImageViewer/ImageViewer2.js
- common/views/components/PageWrapper/PageWrapper.js
- common/views/components/WorkMedia/WorkMedia2.js
Seems we left the tracking of a few of the components.
I've left the old `data-` method in case we need to role back, but prefer the more implicit `onClick`.
> restore most of the works analytics

- catalogue/terraform/terraform.tf
> remove redundant listener in catalogue app

- server/middleware/error.js
> preview on error page

- server/middleware/error.js
I'm completely baffled - so going old school.
Makes me think we should think about logging...
> add logging to see where the problem is with preview

- server/views/layout/default.njk
So we can verify that we own the site through pocket.
> add pocket meta tag

- common/views/components/BasePage/InstallationPage.js
- whats_on/app/views/pages/installation.njk
> add contributor title flag to installations

- server/middleware/error.js
- server/views/partials/monitoring.njk
Only check errors for the JS on our own domain.
?
> Whitelist wellcomecollection.org in Sentry

- common/views/components/DefaultPageLayout/DefaultPageLayout.js
- common/views/components/ErrorPage/ErrorPage.js
- common/views/components/Footer/Footer.js
- common/views/components/PageWrapper/PageWrapper.js
☝️ 
~Adding the `ErrorPage` to the catalogue~
~I wonder if there's a way to render this error page from the other apps, getting us closer to rendering with JSX / React only?~
> type up DefaultPageLayout and PageWrapper

- common/styles/utilities/_root-scope-classes.scss
- common/views/components/BaseHeader/BaseHeader.js
- common/views/components/BasePage/BookPage.js
- common/views/components/BasePage/EventPage.js
- common/views/components/BasePage/InstallationPage.js
- common/views/components/BasePage/Page.js
- common/views/components/BasePage/PlacePage.js
Fixes #2883
Way more explicit on the image height thing, but I would like to have the conversion about images across the site e.g. Do we ever show images taller than the viewport etc?
Also fixed the typing on the component-as-arguments front... turns out you have to:
Element<typeof ComponentYouWant>
> 70vh for book images

- common/model/events.js
- common/services/prismic/api.js
- common/services/prismic/events.js
- common/services/prismic/parsers.js
- common/services/prismic/types.js
- common/utils/is-empty-object.js
- common/views/components/BasePage/EventPage.js
- common/views/components/EventBookingButton/EventBookingButton.js
- common/views/components/EventScheduleItem/EventScheduleItem.js
> Adds event schedule to new event page

- common/services/prismic/events.js
- common/views/components/BasePage/EventPage.js
References #2863
Designers/Devs
Adds the audience to the format tag
> Add audiences to new event page

- server/controllers/content.js
- server/views/pages/homepage.njk
Hypothesis:
If something is in position 1, it will get loads more traffic than if in position 9.
Winning metric:
Handle with care get's loads more traffic
Health metrics:
Make sure we don't detrimentally affect traffic to SIB.
Definitely raised the topic of managed lists.
@jennpb @hthair
> move handle with care to the top of the list on the homepage

- client/webpack.config.js
Might work?
Seems to produce them, let's see if sentry picks them up.
> client sourcemaps

- common/model/events.js
- common/services/prismic/events.js
- common/views/components/BasePage/EventPage.js
- common/views/components/BasePage/EventPageV2.js
- common/views/components/Index/index.js
- whats_on/app/controllers.js
- whats_on/app/routes.js
- whats_on/app/views/pages/event.njk
The team
- Creates Option 1 for testing
- Displays single date for a multi date event (either next upcoming or one passed via url parameter)
- Adds show/hide for all dates
Fixes #2943
> Events prototypes

- client/js/components/info-banner.js
Fixes [this error](https://sentry.io/wellcome/wellcomecollection-website-client/issues/599532618/?query=is:unresolved) in Sentry.
> Check for presence of close button on info-banner

- server/views/layout/default.njk
Fixes [this error](https://sentry.io/wellcome/wellcomecollection-website-client/issues/571506511/?query=is:unresolved) and [this error](https://sentry.io/wellcome/wellcomecollection-website-client/issues/568874435/?query=is:unresolved) in Sentry.
> Check for descriptionEl existence

- .gitignore
- common/views/components/DefaultPageLayout/DefaultPageLayout.js
breaking #2958 into smaller bits
> tidy gitignore

- client/js/app.js
- common/model/events.js
- common/package.json
- common/services/eventbrite/event-embed.js
- common/services/prismic/events.js
- common/views/components/BasePage/EventPage.js
- common/views/components/BasePage/EventPageV2.js
- common/views/components/Index/index.js
- common/yarn.lock
- whats_on/app/controllers.js
- whats_on/app/routes.js
- whats_on/app/views/pages/event.njk
The team
References #2944
- Creates Option 2 for testing
- Displays date range and number of events for a multi date event 
- Adds an anchor link for viewing all dates and booking lower down the page
- eventbrite widget integration
> Events prototypes 2

- common/views/components/BasePage/EventPageV2.js
make jump link work; show dates if no eventbrite widget
> Prototype tweak

- common/views/components/BasePage/EventPage.js
- common/views/components/BasePage/EventPageV2.js
Adding Headers and dates as per @Heesoomoon request
> Prototype tweaks

- server/controllers/content.js
- server/services/prismic-parsers.js
- server/services/prismic.js
> remove homepage promo placement a/b test

- cardigan_beta/.storybook/config.js
- cardigan_beta/package.json
- cardigan_beta/stories/components/Contributors.js
- cardigan_beta/stories/components/Links.js
- cardigan_beta/yarn.lock
- common/views/components/Contributors/README.md
- flow-typed/npm/@storybook/react_v3.x.x.js
> add blank storybook contributors

- common/views/components/BasePage/EventPage.js
- common/views/components/BasePage/EventPageV2.js
- server/services/eventbrite.js
> reordering info; fix height of iframe

- common/views/components/BasePage/EventPageV2.js
> fix style attributes

- common/views/components/BasePage/EventPage.js
- common/views/components/BasePage/EventPageV2.js
> Removed duplicate link

- common/utils/analytics.js
Measuring how long it takes for the  route to change.
Not sure this is a useful metric, so might have more of a think about it.
> add measurement to route change on next app

- catalogue/webapp/pages/work.js
- catalogue/webapp/pages/works.js
- common/next/next.config.js
- common/views/components/DefaultPageLayout/DefaultPageLayout.js
- common/views/components/PageWrapper/PageWrapper.js
- common/views/pages/_document.js
> account for IE in next app

- whats_on/app/views/pages/exhibition.njk
References #2990
This is just a stop-gap
> Added family pack info to Teeth exhibition

- server/services/prismic-parsers.js
- server/services/prismic.js
> remove accidentally removed image test

- common/package.json
- common/services/prismic/events.js
- common/services/prismic/types.js
- common/views/components/BasePage/EventSeriesPage.js
- common/views/components/EventPromo/EventPromo.js
- common/views/components/Index/index.js
- common/yarn.lock
- events/app/views/pages/event-series.njk
- server/middleware/error.js
- whats_on/app/controllers.js
- whats_on/app/routes.js
- whats_on/app/views/pages/event-series.njk
Adding event series to BasePage.
> add event series basepage skeleton

- common/services/prismic/parsers.js
> check for image before getting it's square

- common/styles/utilities/_root-scope-classes.scss
- common/views/components/Contributor/Contributor.js
Couple of small contributor issues
> fix width issue on contributors

- whats_on/app/routes.js
As we now have the whats-on subdomain
> use actual route for events in whats_on service

- router/nginx.conf
Caught from some sentry errors
> send request URI not request from nginx

- server/views/partials/monitoring.njk
Using the most up-to-date Raven JS in server (same as catalogue). Still trying to get to the bottom of why our Raven config isn't working as expected.
> Use same raven-js as catalogue app

- prismic_remapper/README.md
- prismic_remapper/event_series_description_to_body/after.json
- prismic_remapper/event_series_description_to_body/before.json
- prismic_remapper/event_series_description_to_body/premapped/W0dMzyYAACYAZuDf$468e7ab2-887d-43d4-a982-5ba9330ed489.json
- prismic_remapper/event_series_description_to_body/premapped/WiAsdScAAH8F2VJJ$954fe16e-9ec0-4354-af14-9aca9f3be2fe.json
- prismic_remapper/event_series_description_to_body/premapped/WiAsvycAAIMF2VOW$20075789-a591-4bad-8d0f-7fa0133c79ff.json
- prismic_remapper/event_series_description_to_body/premapped/WifrbikAAGSyDtHk$954d3d26-ef4d-493c-8e47-17a049980d80.json
- prismic_remapper/event_series_description_to_body/premapped/WlYT4yQAACQAWcaw$670db46a-39d6-4905-ae55-db6d2b811901.json
- prismic_remapper/event_series_description_to_body/premapped/WlYT_SQAACcAWccj$1009fee3-d75c-42f0-b663-ab0447e6e4f4.json
- prismic_remapper/event_series_description_to_body/premapped/WlYUDCQAACQAWcdt$dd0595d7-0bc2-4ef9-abd9-53fa7ba43b42.json
- prismic_remapper/event_series_description_to_body/premapped/WlYVPyQAACcAWczA$42b46b26-43ba-4f2e-966d-db8f068c8259.json
- prismic_remapper/event_series_description_to_body/premapped/Wn28GCoAACkAIYol$fe66af57-0077-4ebb-8671-302b186227e7.json
- prismic_remapper/event_series_description_to_body/premapped/Wo1YeCoAACoAZFoN$48e94f62-759e-4bf7-9b74-c08006cc1a82.json
- prismic_remapper/event_series_description_to_body/premapped/WoK-NioAACkANeWK$5373db47-2098-4b3f-b79a-f1d072424767.json
- prismic_remapper/event_series_description_to_body/premapped/WoLgbSoAACgANnxB$3c61b785-8387-4557-a18f-61568050768f.json
- prismic_remapper/event_series_description_to_body/premapped/Wp1WGSUAAM8VKCLz$40d70885-b028-44f2-ab0c-f19d55bb7929.json
- prismic_remapper/event_series_description_to_body/premapped/Ws8XgiUAAN0dkYan$40ba654f-715c-4289-a1be-bf749bb45fae.json
- prismic_remapper/event_series_description_to_body/remap.js
- prismic_remapper/package.json
- prismic_remapper/remap.js
- prismic_remapper/yarn.lock
> remap event series description to body

- CONTRIBUTING.md
> remove techprofit from docs

- common/services/prismic/books.js
- common/services/prismic/parsers.js
- common/views/components/BasePage/BookPage.js
- server/controllers/content.js
- server/middleware/error.js
Showing books of all shapes and sizes
> use book cover as promo

- cardigan_beta/stories/components/Contributors.js
- cardigan_beta/stories/components/LinkLabels.js
- cardigan_beta/stories/content.js
- common/model/contributors.js
- common/model/people.js
- common/model/same-as.js
- common/services/prismic/fetch-links.js
- common/services/prismic/parsers.js
- common/test/services/prismic/parsers.test.js
- common/views/components/BasePage/BookPage.js
- common/views/components/Contributor/Contributor.js
- common/views/components/LinkLabels/LinkLabels.js
- common/views/components/LinkLabels/README.md
- prismic-model/js/organisations.js
- prismic-model/json/event-series.json
- prismic-model/json/organisations.json
- prismic-model/json/people.json
> add sameAs to person model

- whats_on/app/views/pages/exhibition.njk
This reverts commit 1fdb37edc2560fe52e9357e2b453300fab263863.
References #3011
The pack isn't available until August
> Revert "Added family pack info to Teeth exhibition"

- common/model/events.js
- common/model/place.js
- common/services/prismic/events.js
- common/services/prismic/fetch-links.js
- common/services/prismic/parsers.js
- common/views/components/BasePage/EventPage.js
References #3022 Adds info box to event page
> Event page info box

- common/views/components/BaseHeader/BaseHeader.js
- common/views/components/BasePage/BookPage.js
- common/views/components/BasePage/EventPage.js
- common/views/components/BasePage/EventPageV2.js
- common/views/components/BasePage/EventSeriesPage.js
- common/views/components/BasePage/InstallationPage.js
- common/views/components/BasePage/Page.js
- common/views/components/BasePage/PlacePage.js
- whats_on/app/routes.js
References #3022
Adds top link to page header
> Event page type link

- server/services/prismic-parsers.js
- server/services/prismic.js
Getting rid of no-longer-needed A/B test.
References #2848.
> Remove A/B test that changes event images

- whats_on/app/views/partials/separate_exhibition_event_promos.njk
> Remove month picker and show all events based on cookie for A/B test

- whats_on/app/views/pages/exhibition.njk
**N.B the packs haven't been delivered yet (01/08/18), so won't merge/deploy this yet**
References #2990
This reverts commit dfb60b11d5d02c3e82e6ee41648e0d9512542a7e.
> Revert "Revert "Added family pack info to Teeth exhibition""

- common/views/components/BasePage/EventPage.js
Grey out past events in dates list
> Grey out past events in list

- common/services/prismic/event-series.js
- common/services/prismic/events.js
- server/middleware/error.js
- server/setup-app.js
- whats_on/app/controllers.js
In an effort to find out why preview isn't working for event series.
> simplify error handling

- events/terraform/services.tf
- whats_on/terraform/services.tf
Makes traffic for event-series forward to the `whats_on` service
> serve event series from whats_on service

- eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk
- events/app/views/partials/event_without_schedule.njk
A bit of duplication, but just to make sure the messaging is consistent.
> add fully booked info to events without eventbrite IDs

- server/data/facility-promos.js
> use page link for shop promo

- catalogue/webapp/pages/work.js
Adds the Universal Viewer when there's a DigitalLocation
> Use Universal Viewer on works behind toggle

- prismic-model/json/articles.json
- server/views/pages/article.njk
It was never used.
also helps to remove image.njk
> remove featured image list

- whats_on/app/views/pages/exhibition.njk
removing the image njk template.
> remove njk image component from exhibition

- server/views/layout/default.njk
- server/views/pages/newsletter.njk
The downside of having switches in code is that we can let them linger.
Deleted loads in Prismic too.
> clean up switches

- common/views/components/BasePage/EventSeriesPage.js
> add event series tag

- catalogue/webapp/pages/work.js
- catalogue/webapp/pages/works.js
- catalogue/webapp/services/catalogue/works.js
> use include over includes on v2 API

- server/views/components/iframe/iframe.njk
Last one, next, once all are merged, I'll remove `image.njk`
> remove njk image component from ifram component

- catalogue/webapp/pages/work.js
> add items and production to work

- common/views/components/BasePage/EventPage.js
Adds missing text and logic to get new new event page working in the same way as the old one
> Event page

- cardigan_beta/stories/components/Label.js
- common/views/components/Label/Label.js
- common/views/components/LabelsList/LabelsList.js
> creates label component

- common/services/prismic/parsers.js
> update link resolver

- prismic-model/js/pages.js
- prismic-model/js/parts/body.js
- prismic-model/json/books.json
- prismic-model/json/event-series.json
- prismic-model/json/installations.json
- prismic-model/json/pages.json
- prismic-model/json/places.json
Jen S was trying to add an event series to a content list, which is supported, but we were masking them off.
This unmasks them.
> put available links in content list model

- common/views/components/BasePage/EventPage.js
- common/views/components/LabelsList/LabelsList.js
> Adds new style ‘part of <series>’ to page

- catalogue/webapp/pages/work.js
- common/services/prismic/api.js
Noticed the page was breaking.
> fix a few works page bugs

- events/app/controllers.js
- events/app/routes.js
We no longer use this service to render event series, so we 🗑 ed it.
> remove event series from events service

- cardigan/package.json
- cardigan/stories/components/DateRange.js
- cardigan/yarn.lock
- common/views/components/DateRange/DateRange.js
Ref: #3125 
Makes the `DateRange` component  respond to the amount of time between date ranges.
Currently the logic is:
* Same day? Day date month year, time range
* Across multiple days? Date month year-Date month year
> Date range

- common/views/components/BasePage/EventPage.js
- server/controllers/content.js
- server/middleware/error.js
> route events preview correctly and check for promo correctly

- .circleci/config.yml
> remove events config from circle config

- deploy/deploy_service.js
> remove events from deploy script

- catalogue/webapp/components/WorkMedia/WorkMedia.js
- catalogue/webapp/pages/work.js
- common/utils/ga.js
- common/views/components/BasePage/EventPage.js
- common/views/components/Buttons/Button/Button.js
- common/views/components/Buttons/Control/Control.js
- common/views/components/ImageViewer/ImageViewer.js
- common/views/components/Links/PrimaryLink/PrimaryLink.js
- common/views/components/Links/SecondaryLink/SecondaryLink.js
- common/views/components/PageHeaders/Hero/Hero.js
- common/views/components/WorkMedia/WorkMedia.js
- common/views/components/WorkMedia/WorkMedia2.js
- server/views/pages/search.njk
- server/views/pages/work.njk
Simplified the API to the components and reduces error by typing up the shape of the tracking event rather than sending strings all over the place.
Also adds tracking to the times/dates.
> Tracking event

- catalogue/webapp/components/WorkMedia/WorkMedia.js
- catalogue/webapp/pages/work.js
- common/utils/ga.js
- common/views/components/BasePage/EventPage.js
- common/views/components/Buttons/Button/Button.js
- common/views/components/Buttons/Control/Control.js
- common/views/components/ImageViewer/ImageViewer.js
- common/views/components/Links/PrimaryLink/PrimaryLink.js
- common/views/components/Links/SecondaryLink/SecondaryLink.js
- common/views/components/PageHeaders/Hero/Hero.js
- common/views/components/WorkMedia/WorkMedia.js
- common/views/components/WorkMedia/WorkMedia2.js
- server/views/pages/search.njk
- server/views/pages/work.njk
Ref #3143 
Waiting on #3153 to avoid mega conflicts
If a link is internal, we default to scrolling.
Wondering if we should use the native:
https://css-tricks.com/smooth-scrolling-accessibility/
> Scroll on internal link

- common/services/prismic/books.js
I'd rather use GraphQL - but this will do.
> fetch links on books

- cardigan_beta/stories/components/Cards.js
- common/model/weight.js
- common/views/components/Card/Card.js
- common/views/components/CompactCard/CompactCard.js
- common/views/components/EventCard/EventCard.js
- common/views/components/FeaturedCard/FeaturedCard.js
- common/views/components/Promo/Promo.config.js
- common/views/components/Promo/Promo.js
- common/views/components/SearchResults/SearchResults.js
- server/controllers/content.js
- server/model/weight.js
- server/views/pages/curated-lists.njk
Introduces 2 concepts
* FeaturedCard
* Card
* CompactCard
These will be able to be constructed according to their content types, similar to `BasePage`.
* `featured`
* null / `default` (I prefer `null`)
* `compact`
The other's are there for legacy reasons.
`compact` was introduced in the sense that it would normally be used for lists of content tightly compacted, e.g. event lists.
TODO
> Card organisation

- common/styles/components/_buttons.scss
- common/views/components/BasePage/EventPage.js
- server/views/layout/default.njk
There is a very small edge case that a user might see the button before the widget has loaded.
No we have feedback saying we're in the process of loading.
Also makes the button accessible as a link again...
> eventbrite widget loading is now more correct

- common/views/components/BasePage/EventPage.js
Sometimes "in the", sometimes "around the" etc etc.
Just defer to the content team me thinks.
> don't thinkk we can infer language about an event location

- whats_on/app/controllers.js
> s/coming up/upcoming

- prismic-model/js/exhibitions.js
- prismic-model/json/exhibitions.json
- whats_on/app/views/pages/exhibition.njk
> remove galleryLevel from exhibition and use place

- common/model/events.js
- common/model/exhibitions.js
- common/model/installations.js
- common/model/label-field.js
- common/model/place.js
- common/model/places.js
- common/services/prismic/events.js
- common/services/prismic/exhibitions.js
- common/services/prismic/fetch-links.js
- common/services/prismic/installations.js
- common/services/prismic/parsers.js
- common/services/prismic/places.js
- common/views/components/BasePage/EventPage.js
- common/views/components/BasePage/PlacePage.js
- common/views/components/InfoBox/InfoBox.js
- server/services/prismic-parsers.js
Begin putting policies into practice.
It's a nice exercise to go through what we're adding into the box.
Fixes #3053
> Event policies ui

- whats_on/app/views/pages/whats-on.njk
> add urls back to facility promos

- common/services/prismic/events.js
- common/services/prismic/parsers.js
> make sure we check isBroken === false not  !isBroken

- common/services/prismic/parsers.js
Trying to think of the best way to do tests on these parsers...
> Label parser fix

- common/utils/json-ld.js
- server/utils/json-ld.js
- server/views/layout/default.njk
- whats_on/app/views/pages/event-series.njk
- whats_on/app/views/pages/event.njk
- whats_on/app/views/pages/exhibition.njk
- whats_on/app/views/pages/installation.njk
> Add metadaata to whats on

- catalogue/webapp/yarn.lock
Not sure how this went out of sync.
> update catalogue yarn lock

- cardigan/stories/components/Cards.js
- cardigan/stories/components/Promos.js
Trying the new style navigation grouping too.
> add cards back into cardigan

- common/services/prismic/parsers.js
Just noticed the 500 while previewing.
> use the placeholder for the image in a captioned image

- common/model/events.js
- common/services/prismic/events.js
- common/services/prismic/parsers.js
- common/utils/json-ld.js
- common/views/components/BasePage/EventPage.js
- common/views/components/EventScheduleItem/EventScheduleItem.js
- prismic-model/json/events.json
- server/utils/json-ld.js
Fixes #3019 
Removes description on events from the model and parsers. Getting closer to 1 way of doing this.
> add some extra fields to the JSON LD for events

- common/services/prismic/parsers.js
> remove log

- common/views/components/BasePage/EventPage.js
- common/views/components/EventScheduleItem/EventScheduleItem.js
> Rmove has event description

- prismic-model/js/events.js
- prismic-model/json/events.json
After talking to the content team, they said it made sense to live in reservation.
> move ticketSalesStart to reservation section in primic

- server/services/prismic.js
Found this in sentry
https://wellcomecollection.org/webcomic-series/WleP3iQAACUAYEoN?page=3
> check results size before rendering series

- common/services/prismic/events.js
Let's try automatically create these queries?
> make sure we fetch contributors for event series

- common/views/components/BasePage/EventPage.js
> move contributors and add info box to events

- router/nginx.conf
- whats_on/app/views/partials/mixed_exhibition_event_promos.njk
- whats_on/app/views/partials/separate_exhibition_event_promos.njk
> add past exhibitions and events

- common/views/components/BasePage/ErrorPage.js
- common/views/components/Index/index.js
- server/views/pages/error.njk
Boring for now.
I quite like the duck-like v that the links create though.
ref #2826 
fixes #2908
> first stab at error page

- common/views/components/BasePage/ErrorPage.js
- common/views/components/ErrorPage/ErrorPage.js
Not sure if there a neater way code wise to do this?
> add archive content to error page

- cardigan/stories/components/Links.js
> tidy up links in cardy

- common/services/prismic/utils.js
- server/test/app/app.js
> Get correct events for current-and-upcoming

- common/services/prismic/parsers.js
- prismic-model/js/parts/article-body.js
- prismic-model/json/articles.json
- server/services/prismic-body-parser.js
- server/views/components/article-body/article-body.njk
ref #3257
Add the new quote to the article body, deprecate the old one.
It's a nicer model and allows for the editors to add links etc to the citation.
> Add new Quote to article body

- README.md
- build-speedtracker.sh
- common/views/components/BasePage/ErrorPage.js
- common/views/components/DefaultPageLayout/DefaultPageLayout.js
- common/views/components/FooterNav/FooterNav.js
- router/nginx.conf
- server/controllers/content.js
- server/routes/index.js
- server/test/app/app.js
- server/views/docs/index.njk
- server/views/docs/visual-architecture.njk
- server/views/layout/default.njk
- server/views/pages/homepage.njk
@davidpmccormick just wondering, how would you decide to use nginx over the json config?
> add /explore => /stories redirect

- prismic-model/js/articles.js
- prismic-model/json/articles.json
- prismic_remapper/article_contributors_remodel/after.json
- prismic_remapper/article_contributors_remodel/before.json
- prismic_remapper/article_contributors_remodel/remap.js
- server/controllers/content.js
- server/services/prismic-parsers.js
Ref #3253 
Putting this is without the JSON files (next PR) so we can see what we're doing as it's quite important.
I think the steps I would like to do to avoid remapping in Prismic too many times is:
> Article contributors reindex

- common/services/prismic/events.js
- common/test/services/prismic/events.test.js
- common/views/components/BasePage/EventPage.js
- common/views/components/EventSchedule/EventSchedule.js
- common/views/components/EventSchedule/EventShedule.js
- common/views/components/EventSchedule/README.md
- common/views/components/EventScheduleItem/EventScheduleItem.config.js
Probably need to tidy up some naming, and get the groups into the event schedule.
Fixes #3265
> Add grouped event schedule.

- prismic_remapper/README.md
- prismic_remapper/remap.js
Just to give you info and to stop me counting documents in folders.
> add nicer logging to remapper

- prismic-model/js/parts/article-body.js
- prismic-model/json/articles.json
From an audit #3257, we don't use it.
Let's remove it then.
> remove list from article body

- cardigan/stories/components/LinkLabels.js
- common/services/prismic/articles.js
- common/views/components/Contributor/Contributor.js
- common/views/components/LinkLabels/LinkLabels.js
- content/webapp/pages/article.js
Not so much styling, just trying to get the components in, and see how it works with `BaseHeader`, so that if we have to change it, we can make a call as a refactor across where it's used vs creating a new header (which looks like we don't need to do). 
ref #3063
> add author to article header

- common/data/the-pharmacy-of-colour.js
- common/model/generic-content-fields.js
- common/services/prismic/parsers.js
- common/views/components/BasePage/EventSeriesPage.js
- common/views/components/BasePage/InstallationPage.js
- content/webapp/pages/exhibition.js
Moves us over to the more concise `Image` type.
It should help us deprecate the `Picture` type.
`// Some flow todo still`
> add images to genericfields

- server/services/prismic-parsers.js
To stop this, we'll be removing this code soon.
> make thumbnail same as promo

- common/data/the-pharmacy-of-colour.js
- common/model/image.js
- common/services/prismic/exhibitions.js
- common/services/prismic/parsers.js
- common/views/components/BasePage/BookPage.js
- common/views/components/DailyTourPromo/DailyTourPromo.js
- common/views/components/EventPromo/EventPromo.js
- common/views/components/ExhibitionPromo/ExhibitionPromo.js
- common/views/components/StaticWorksContent/StaticWorksContent.js
- common/views/components/WorkImage/WorkImage.js
Waiting on #3286 
Adds crops to the model, and parser
> Image crops

- router/nginx.conf
Pulled from GA - we need to keep an eye on it.
> add some redirects for 404s

- common/services/prismic/fetch-links.js
- common/services/prismic/parsers.js
* Few image rendering bugs
* Mae sure organisation description percolates down into the template
> attach organisation description onto contributor parser

- common/views/components/FeaturedText/FeaturedText.js
- common/views/components/Index/index.js
- common/views/components/Standfirst/Standfirst.js
- server/views/components/article-body/article-body.njk
Simplifying the `FeaturedText` style and adding a `Standfirst` component to keep what we currently have in the articles consistent.
> Featured text

- common/styles/components/_divider.scss
- whats_on/app/yarn.lock
> Make dashed divider thicker

- .circleci/config.yml
- catalogue/webapp/next.config.js
- common/next/next.config.js
- content/terraform/terraform.tf
- content/webapp/next.config.js
- deploy/deploy_service.js
- router/terraform/asg.tf
- router/terraform/cloudfront.tf
> Content in circle

- common/views/components/DefaultPageLayout/DefaultPageLayout.js
- common/views/components/PageWrapper/PageWrapper.js
- content/webapp/pages/article.js
- content/webapp/pages/exhibition.js
Ue our errorpage over the generic next error page.
> Next error

- content/webapp/pages/article.js
Going to try find a way to get the typing here working as we've left the JSON LD off too...
> add metadata to articles in content service

- common/views/components/Body/Body.js
Fixes #3309 (again :trollface: @jamesgorrie)
> Get rid of excess container

- common/services/prismic/articles.js
- common/services/prismic/parsers.js
Parsing and attaching format to articles
> get article format from prismic

- server/services/prismic.js
Turns out it is an accumulator...
> only exclude on delist tag

- whats_on/app/views/pages/events.njk
We're getting closer to illuminating these inconsistencies...
JSX and Flowtype 🏆 
Fixes #3331
> add audience to events listing promos

- content/webapp/test/exhibitions.test.js
#References #3009
Makes sure the exhibitions page is being rendered
> Added test for exhibition page

- common/styles/content.scss
> add body_text scss to content app

- content/webapp/pages/exhibition.js
> Making Gallery opening times dumb (for now)

- common/views/components/BasePage/EventPage.js
> use DateRange component on DateList

- common/views/components/EventbriteButton/EventbriteButton.js
Ref #3341 
Using classic JS DOM manipulation is a real :rage4:
> localise eventbrite widget opener

- cardigan/stories/components/Links.js
- common/styles/content.scss
- common/views/components/BaseHeader/HeaderBackground.js
- common/views/components/BasePage/BookPage.js
- common/views/components/BasePage/ErrorPage.js
- common/views/components/BasePage/EventPage.js
- common/views/components/BasePage/EventSeriesPage.js
- common/views/components/BasePage/InstallationPage.js
- common/views/components/BasePage/Page.js
- common/views/components/BasePage/PlacePage.js
- common/views/components/Body/Body.js
- common/views/components/DateAndStatusIndicator/DateAndStatusIndicator.js
- common/views/components/Links/SecondaryLink/SecondaryLink.js
- common/views/components/PageHeader/PageHeader.js
- content/webapp/pages/exhibition.js
3rd in the trilogy of four, the next will be to deprecate everything, but I will do that as a last step once these are merged in.
> Page header trilogy

- cardigan/stories/components/Links.js
- common/views/components/BasePage/BookPage.js
- common/views/components/BasePage/EventPage.js
- common/views/components/Links/SecondaryLink/SecondaryLink.js
- common/views/components/PageHeader/PageHeader.js
- content/webapp/pages/exhibition.js
Working my way through the different content types, you can go through the commits to see each one done.
Will run it past @GarethOrmerod before merging.
> Page header prop

- cardigan/stories/components/Links.js
- common/styles/content.scss
- common/views/components/BaseHeader/HeaderBackground.js
- common/views/components/BasePage/BookPage.js
- common/views/components/BasePage/ErrorPage.js
- common/views/components/BasePage/EventPage.js
- common/views/components/BasePage/InstallationPage.js
- common/views/components/DateAndStatusIndicator/DateAndStatusIndicator.js
- common/views/components/Links/SecondaryLink/SecondaryLink.js
- common/views/components/PageHeader/PageHeader.js
- content/webapp/pages/exhibition.js
Round two - happy for the earlier PRs to be reviewed, I can merge and make this easier to see, or you can hop through the commits, they're relatively small and self-contained.
> Page header returns

- common/views/components/BasePage/EventPage.js
- content/webapp/pages/exhibition.js
> add isFree back to events and exhibitions

- common/views/components/EventScheduleItem/EventScheduleItem.js
> only show event booking button if tickets are on sale

- prismic-model/js/series.js
- prismic-model/json/series.json
> put schedule as a field on the model

- catalogue/webapp/pages/work.js
> add workLd

- common/views/components/Body/Body.js
> tidy up some body spacing

- common/services/prismic/article-series.js
- common/services/prismic/articles.js
- common/views/components/SeriesNavigation/SeriesNavigation.js
- content/webapp/pages/article.js
* Standardises how we construct prismic queries
* add the series nav, which will apply to event and article series
Styling coming to a list near you soon.
> Article series nav

- common/views/components/BasePage/BasePage.js
- common/views/components/Body/Body.js
- common/views/components/Contributors/Contributors.js
- content/webapp/pages/article.js
- content/webapp/pages/series.js
Makes the creaminess envelope all directly related content,
> Creamy body

- common/utils/json-ld.js
- content/webapp/pages/article.js
- content/webapp/pages/event.js
Waiting on #3385 
Adds JSON LD to events and articles in the content app.
> Json ld articles events

- common/styles/utilities/_root-scope-classes.scss
Works for now, will look at the floaty _i_ next.
> make max-heighted images width: auto

- common/data/the-pharmacy-of-colour.js
- common/model/generic-content-fields.js
- common/model/labels.js
- common/services/prismic/article-series.js
- common/services/prismic/articles.js
- common/services/prismic/books.js
- common/services/prismic/event-series.js
- common/services/prismic/events.js
- common/services/prismic/exhibitions.js
- common/services/prismic/installations.js
- common/services/prismic/parsers.js
- common/services/prismic/places.js
- common/views/components/BasePage/BookPage.js
- common/views/components/BasePage/EventPage.js
- common/views/components/BasePage/EventSeriesPage.js
- common/views/components/BasePage/InstallationPage.js
- common/views/components/EventCard/EventCard.js
- common/views/components/EventScheduleItem/EventScheduleItem.js
- common/views/components/Label/Label.js
- common/views/components/LabelsList/LabelsList.js
- common/views/components/PageHeader/PageHeader.js
- common/views/components/SearchResults/SearchResults.js
- content/webapp/pages/article.js
- content/webapp/pages/exhibition.js
- content/webapp/pages/series.js
Noticed there was a lot of copy pasting, so made labels part of generic content fields.
Feels pretty safe.
> Generic labels

- common/model/pages.js
- common/services/prismic/multi-content.js
- common/services/prismic/pages.js
- common/services/prismic/search.js
- common/views/components/CompactCard/CompactCard.js
- common/views/components/SearchResults/AsyncSearchResults.js
- content/webapp/pages/page.js
- content/webapp/server.js
- router/redirects.conf
Prepping for removing the server app.
Fixes #3392
> add pages to content app

- router/redirects.conf
> Accessibility redirect

- common/services/prismic/opening-times.js
- common/services/prismic/pages.js
- common/utils/format-date.js
- content/webapp/pages/opening-times.js
> add opening times to content app

- content/webapp/pages/newsletter.js
> add newsletter to content app

- common/data/the-pharmacy-of-colour.js
- common/model/generic-content-fields.js
- common/services/prismic/parsers.js
- common/views/components/BasePage/EventSeriesPage.js
- common/views/components/BasePage/InstallationPage.js
- common/views/components/Body/Body.js
- common/views/components/PageHeaderStandfirst/PageHeaderStandfirst.js
- content/webapp/pages/article-series.js
- content/webapp/pages/article.js
- content/webapp/pages/exhibition.js
- prismic-model/js/articles.js
- prismic-model/js/parts/body.js
- prismic-model/json/articles.json
- prismic-model/json/books.json
- prismic-model/json/event-series.json
- prismic-model/json/events.json
- prismic-model/json/exhibitions.json
- prismic-model/json/installations.json
- prismic-model/json/pages.json
- prismic-model/json/places.json
- prismic-model/json/series.json
- prismic-model/yarn.lock
Adds `standfirst` to the body.
The `standfirst` will always be rendered in the `PageHeader`.
`FeaturedText` will be rendered in bold in the body.
For now we're not rendering the standfirst on anything but `articles` and `article-series`, due to the fact we might want to move this onto a field of the content type, but this at least gives us 1 consistent way to deal with future and present content creation.
> Standfirst

- catalogue/webapp/yarn.lock
- common/services/prismic/article-series.js
- common/services/prismic/articles.js
- common/styles/utilities/_root-scope-classes.scss
- common/styles/utilities/compiled_variables/_colors.scss
- common/views/components/ArticleCard/ArticleCard.js
- common/views/components/CompactCard/CompactCard.js
- common/views/components/ImagePlaceholder/ImagePlaceholder.js
- common/views/components/SearchResults/SearchResults.js
- content/webapp/pages/article-series.js
- content/webapp/pages/article.js
- content/webapp/yarn.lock
- server/yarn.lock
- whats_on/app/yarn.lock
- yarn.lock
* Update labels
* Add background to serial page
* Add spacing to series navigation
* Only use 1 serial
> Serial tidy

- content/terraform/terraform.tf
- content/webapp/server.js
Start pushing the site sections through to the new content app.
> add routes for site sections to content terraform

- content/webapp/pages/opening-times.js
- server/views/pages/opening-times.njk
Makes sure correct date displays
> Caters for normal closed day being part of an exceptional closed period

- router/redirects.conf
> Added redirects for exhibitions

- content/terraform/terraform.tf
Forgot you need unique names
@wellcometrust/experience-dev you'll have to run a `terraform init` before hand.
> name pages routes correctly

- content/webapp/pages/exhibition.js
> Added free label and text change

- .github/ISSUE_TEMPLATE.md
Add the templates we have to the main issue template so we remember.
> Add issue templates to main issue template

- common/services/prismic/parsers.js
- prismic-model/js/parts/body.js
- prismic-model/json/books.json
- prismic-model/json/event-series.json
- prismic-model/json/events.json
- prismic-model/json/exhibitions.json
- prismic-model/json/installations.json
- prismic-model/json/pages.json
- prismic-model/json/places.json
- prismic-model/json/series.json
Makes sure the quotes can be added in all the places there is `Body`
> ubiqitously apply quotes pulled, and reviewed

- common/views/components/ImageViewer/ImageViewer.js
Unfortunately this means we have lost the data.
:rage1: 
Standardising all this is really going to relieve some of this strain.
> stop using strings for tracking

- common/views/components/BasePage/BasePage.js
- content/webapp/pages/article.js
Follow the structure:
* Header
* Body
* Content Specific
* Contribs
* Siblings
This might hopefully allow us to start standardising spacing too. 👾
> add some semantic structure to how the article page is built

- common/styles/components/_captioned_image.scss
- common/styles/components/_lazyload.scss
- common/styles/shame.scss
- common/views/components/Images/Images.js
- common/views/components/MainMedia/MainMedia.js
> Get the images to load correctly in old and new land

- prismic-model/js/parts/body.js
- prismic-model/js/parts/gif-video-slice.js
- prismic-model/js/parts/iframe-slice.js
- prismic-model/js/parts/link.js
- prismic-model/js/parts/text.js
- prismic-model/json/books.json
- prismic-model/json/event-series.json
- prismic-model/json/events.json
- prismic-model/json/exhibitions.json
- prismic-model/json/installations.json
- prismic-model/json/pages.json
- prismic-model/json/series.json
References #3257 
Adds gifVideo and iframe slices to the body
> Body slices

- router/redirects.conf
There will be more, it's easy to generate this list though as we have the info in Prismic.
> add wordpress article redirects

- common/services/prismic/articles.js
- content/webapp/pages/article-series.js
> add contributors to article series

- common/views/components/BaseHeader/HeaderBackground.js
Noticed it wasn't working on article series.
> add WobblyEdge to HeaderBackground

- common/services/prismic/installations.js
- content/terraform/terraform.tf
- content/webapp/pages/event.js
- content/webapp/pages/installation.js
- content/webapp/server.js
As says on tin, will allow us to serve these with the nice new image gallery, and a low traffic test for next.
> Installations in next

- common/services/prismic/events.js
- common/views/components/BasePage/EventPage.js
> Event past dates

- common/views/components/EventScheduleItem/EventScheduleItem.js
- common/views/components/EventbriteButton/EventbriteButton.js
Quick fixes #3460 until we look at spacing universally.
> add some spacing below full event details

- common/services/prismic/article-series.js
> only use serial label if there is a schedule on the series

- catalogue/terraform/terraform.tf
[DOT NOT MERGE FOR THIS REASON](https://spectrum.chat/?t=602ba081-7fea-4c73-9007-a8f0d5a55152)
After #3042
> [do not merge] catalogue back to next.js

- common/views/components/GifVideo/GifVideo.js
- common/views/components/Iframe/Iframe.js
Since the Iframe and GifVideo components aren't going to be used outside of React land we don't need to replicate the javascript class hooks and data attributes
> Gif video iframe redundant code

- catalogue/terraform/terraform.tf
Content = 100 - 199
Catalogue = 200 - 299
> make catalogue service use 200 namespace for router listeners

- content/webapp/pages/article-series.js
Easy for now, need to figure it out for later.
> hackfix in pagesize until we have pagination on SearchResults with compact cards

- router/redirects.conf
Noticed By Hannah
Must check 404 logs
> proposing an article redirect

- common/model/events.js
- common/views/components/BasePage/EventPage.js
- common/views/components/CardGrid/CardGrid.js
- common/views/components/StatusIndicator/StatusIndicator.js
- content/webapp/pages/event.js
ref #3400 
Next up - looking at the same thing in promos
> add is sold out to event pages

- common/model/organization.js
- common/styles/components/_find_us.scss
- common/views/components/FindUs/FindUs.js
> Tel number in footer

- content/terraform/terraform.tf
> deploy the smarticles

- common/views/components/FindUs/FindUs.js
> remove semicolon

- common/views/components/DefaultPageLayout/DefaultPageLayout.js
- content/terraform/terraform.tf
- content/webapp/server.js
> add preview to test

- common/styles/components/_prismic_toolbar.scss
- common/styles/content.scss
- content/terraform/terraform.tf
- content/webapp/package.json
- content/webapp/server.js
- content/webapp/yarn.lock
Main issue was leaving the `api/v2` off the end of the api URL
> get the preview up and running

- common/utils/analytics.js
It'd probably be nicer to be using autotrack, but just reinstating this for now as to not have to many moving parts.
> reinstate scroll analytics across the next apps

- content/webapp/pages/article.js
#3511 
Show the first of the series on the last of the series
> use correct index maths to workout whether to show part 1 in a series

- common/services/prismic/articles.js
#3511 
Shows contributors on the comics
> add contributor to webcomic graphQL

- common/services/prismic/article-series.js
The oredering was based on the published date, where as it should respect the ordering of the schedule.
Slightly simpler to understand I think.
> use series order for ordering of serials

- common/services/prismic/parsers.js
This was preventing related articles appearing on exhibition pages
> prevent error when parsing article

- common/views/components/DailyTourPromo/DailyTourPromo.js
> daily tours link fix

- common/utils/json-ld.js
- common/views/components/Breadcrumb/Breadcrumb.js
- common/views/components/DefaultPageLayout/DefaultPageLayout.js
- content/webapp/pages/article-series.js
- content/webapp/pages/article.js
- content/webapp/pages/book.js
- content/webapp/pages/event.js
- content/webapp/pages/exhibition.js
- content/webapp/pages/installation.js
- content/webapp/pages/place.js
Nice and simple, let the breadcrumbs component render it's JSON LD.
With article LD fixes too.
> render breadcrumbs LD

- common/data/our-voice-our-way.js
- server/controllers/content.js
- server/views/pages/homepage.njk
- whats_on/app/controllers.js
- whats_on/app/views/pages/whats-on.njk
> add our voice our way installation

- content/webapp/pages/exhibitions.js
> add past to past exhibitions title

- content/terraform/terraform.tf
- content/webapp/pages/opening-times.js
- content/webapp/server.js
#3540 
Route newsletter and opening times through next app.
> Update opening times before launch

- cardigan/stories/components/Outro.js
- cardigan/yarn.lock
- common/views/components/Outro/Outro.js
- common/views/components/Outro/README.md
> add base outro component

- cardigan/stories/components/CaptionedImage.js
- common/styles/components/_captioned_image.scss
- common/styles/components/_image_gallery_v2.scss
- common/styles/non-critical.scss
- common/views/components/Images/Images.js
- common/views/components/Images/README.md
Closes #3543.
Includes a README about image height logic.
> Add CaptionedImage to Cardigan

- cardigan/stories/components/Outro.js
- common/views/components/Outro/Outro.js
Ref #3363 
#3560 - I somehow lost the code that was in that PR, so I just committed an empty component.
This is the actual interface:
> Outro ui actually

- common/services/prismic/search.js
Fixes content not loading on pages.
> use object.keys not object.entries for IE11

- whats_on/app/views/partials/mixed_exhibition_event_promos.njk
- whats_on/app/views/partials/separate_exhibition_event_promos.njk
Makes everything just a little more consistent
> use consistent language around links

- router/redirects.conf
The series has been re-published, redirecting to the new versions
> redirect the outsiders serials to the new Prismic versions

- common/views/components/Body/Body.js
- common/views/components/ImageGalleryV2/ImageGalleryV2.js
Closes #3554 
Make sure we know when people are opening the image galleries (by clicking either the image itself, or the button).
__TODO:__
e.g.
```
category: 'component',
action: `ImageGallery:click`,
label: `image-gallery:1`
```
> Track opening of the image galleries

- common/views/components/DefaultPageLayout/DefaultPageLayout.js
- content/webapp/pages/homepage.js
> update homepage metadata

- README.md
- prismic-model/js/webcomics.js
- prismic-model/json/webcomics.json
Brings webcomics into the fold of allowing editors to add a body, specifically a standfirst.
> add body to webcomics

- common/model/multi-content.js
- common/model/weblinks.js
- common/services/prismic/articles.js
- common/services/prismic/exhibitions.js
- common/services/prismic/types.js
- common/styles/utilities/_root-scope-classes.scss
- common/views/components/Outro/Outro.js
Ref #3363 
Adds the outro fields to the GraphQuery.
Seems to be working. Just add `?toggles=outro:true` and refresh.
> add outro properties to article graph query

- common/services/prismic/articles.js
Add installations to the types for outro
> add installations to outro types

- common/services/prismic/articles.js
Another one we forgot...
I'd love to get this stuff through generated code someday....
> allow pages on outro

- cardigan/stories/components/Promos.js
- common/views/components/Tasl/Tasl.js
- common/views/components/VideoEmbed/VideoEmbed.js
Gets Event Promo story working again too
> Accessibility fixes for Cardigan components

- common/model/events.js
- common/services/prismic/events.js
- common/views/components/DailyTourPromo/DailyTourPromo.js
- content/webapp/pages/event.js
- prismic-model/js/event-policies.js
- prismic-model/js/events.js
- prismic-model/json/events.json
- server/content-model/events.js
- server/services/prismic-parsers.js
Adds the "Arrive early to register" messaging on the end of an event.
I would have preferred to have found a way to do this with policies - but given it's infrequency, we decided against it. Thoughts?
> Booking required

- common/views/components/Outro/Outro.js
> change outro copy to be more generic

- content/webapp/pages/events.js
Need to remember to do this.
Also need to find a way to make sure we do it in the future...
Thoughts?
> convert JSON events to typed events before render

- .circleci/config.yml
Need chrome dependencies so report can be generated
> install chrome dependencies

- content/webapp/pages/stories.js
> Re-add first sentence to story page description

- pa11y/webapp/pages/index.js
changed url of report so it points to the newest one
> Pally Dashboard report

- common/services/prismic/exhibitions.js
https://sentry.io/wellcome/wellcomecollection-website-client/issues/742474671
> Fixing sentry error

- common/model/article-series.js
- common/model/multi-content.js
- common/services/prismic/article-series.js
- common/services/prismic/multi-content.js
- common/views/components/SeriesNavigation/SeriesNavigation.js
> Show article series on outros

- common/data/facility-promos.js
- common/views/components/DailyTourPromo/DailyTourPromo.js
- server/data/facility-promos.js
> text change as per Jen’s request

- catalogue/webapp/yarn.lock
- common/views/components/LayoutPaginatedResults/LayoutPaginatedResults.js
References #3564
Adds the `SpacingSection` to `LayoutPaginatedResults`.
> Space out paginated results with SpacingSection

- content/webapp/pages/homepage.js
- content/webapp/pages/whats-on.js
> Remove Our Voice promo from homepage and what’s on

- content/terraform/terraform.tf
Ref #3540 
Waiting on #3591 #3589 
Routes traffic to content app.
> add /stories and /articles listeners to content app

- common/utils/tracking.js
- common/views/components/BookPromo/BookPromo.js
- common/views/components/EventPromo/EventPromo.js
- common/views/components/ExhibitionPromo/ExhibitionPromo.js
- common/views/components/Promo/Promo.js
- common/views/components/WorkPromo/WorkPromo.js
Clicks on Promos still aren't being registered in GA. This should fix that
> Promo tracking

- content/terraform/terraform.tf
Getting the priorities straight
> get priorities straight for content listeners

- common/views/components/GifVideo/GifVideo.js
- common/views/components/Iframe/Iframe.js
> use the right tracking function

- common/koa-middleware/withToggles.js
- content/webapp/server.js
Null checking. Love it.
GlobalAlert wasn't available on `stories` as stories doesn't run through the server...
> add stories route to server to get globalAlert

- common/utils/analytics.js
- common/views/components/DefaultPageLayout/DefaultPageLayout.js
One thing left off the other PR.
> send pageState down the pipes

- common/views/components/CompactCard/CompactCard.js
noticed this still had the data-track-event attribute
> Add tracking to CompactCard

- content/webapp/pages/stories.js
puts the hyperlink on the correct part of the intro text
> stories hyperlink on correct part of text

- common/services/prismic/articles.js
People who like seeing webcomics in outros instead of 500 errors.
> Account for webcomics being in the outro

- build/nginx.conf
- catalogue/webapp/server.js
- nginx-proxy/nginx.conf
- nginx_webapp/nginx.conf
> remove featuresCohort cookie

- prismic-model/js/series.js
- prismic-model/json/series.json
> remove name from series model

- router/redirects.conf
Articles in the top 50:
http://prev.wellcomecollection.org/articles/measuring-and-classifying
http://prev.wellcomecollection.org/articles/black-death-and-early-public-health-measures
http://prev.wellcomecollection.org/articles/science-and-art
http://prev.wellcomecollection.org/articles/drugs-trade
http://prev.wellcomecollection.org/articles/childbirth-athletic-feat
> add more of the 404s to the list

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/testing.md
> User testing issue template

- common/views/components/BackToTop/BackToTop.js
- common/views/components/CopyUrl/CopyUrl.js
- common/views/components/FacilityPromo/FacilityPromo.js
- common/views/components/InstallationPromo/InstallationPromo.js
- common/views/components/Links/PrimaryLink/PrimaryLink.js
- common/views/components/Links/SecondaryLink/SecondaryLink.js
- common/views/components/SearchBox/SearchBox.js
- common/views/components/SegmentedControl/SegmentedControl.js
- common/views/components/StoryPromo/StoryPromo.js
- common/views/components/Tags/Tags.js
Moving to having only 1 way of doing things.
(although saying that these should be using the action tracking function...)
> remove old tracking and reinstate with new

- common/views/components/DefaultPageLayout/DefaultPageLayout.js
Lost in the wash.
There's probably a way nicer Reacty way to do this... but hey.
> reinstate prismic validations

- content/webapp/pages/stories.js
> update stories serial to be hidden persuaders

- router/redirects.conf
> add redirects for some wordpress articles

- content/webapp/pages/event.js
- router/redirects.conf
> use page URL for ticket ts and cs

- common/views/components/DefaultPageLayout/DefaultPageLayout.js
> put hotjar back in

- common/utils/analytics.js
page state tracking was lost...
> check for length to reinstate pageState tracking

- catalogue/webapp/services/catalogue/worksv2.js
> filter worksv2 results

- catalogue/webapp/pages/workv2.js
Interestingly, not the image URL is https://wellcomelibrary.org/iiif/b20643512/manifest/full/800,/0/default.jpg, which is returning another manifest... might have to dig into this.
> get manifest as iiif-presentation type

- common/styles/utilities/compiled_variables/_colors.scss
- server/ui-config/colors.js
> Update green hex to have enough contrast on cream

- router/redirects.conf
> add photography redirect

- common/services/prismic/opening-times.js
- content/webapp/pages/opening-times.js
- content/webapp/yarn.lock
> Opening times into ContentPage

- catalogue/webapp/app.js
- catalogue/webapp/test/app.test.js
Happened due to a bad merge.
Tried adding a test, Jest doesn't like next yet.
> /works/progress Routes

- router/redirects.conf
Hopefully URLs are finally becoming more stable.
> add webcomic-series redirect

- cardigan/stories/components/Pagination.js
- common/views/components/Pagination/README.md
> Add Pagination to Cardigan

- catalogue/webapp/pages/worksv2.js
- catalogue/webapp/services/catalogue/worksv2.js
- toggles/webapp/pages/index.js
For when we release V2 and want to offer the option of having all the results.
> Add filter toggle

- common/services/prismic/link-resolver.js
Make sure we resolve the webcomic-series correctly
> fix webcomic resolver

- deploy/deploy_service.js
- router/terraform/services.tf
- router/terraform/variables.tf
My laziness finally got the best of me, and instead of copy pasting the container tag, it's finally made it into the deploy script.
> add router service to deploy script

- content/webapp/pages/book.js
Adds published date to the books page.
We might still have issues with the date being pulled through from the migration, but we can fix those as they come up.
> add published date to books

- prismic-model/js/parts/body.js
- prismic-model/json/books.json
- prismic-model/json/event-series.json
- prismic-model/json/events.json
- prismic-model/json/exhibitions.json
- prismic-model/json/installations.json
- prismic-model/json/pages.json
- prismic-model/json/places.json
- prismic-model/json/series.json
- prismic-model/json/webcomics.json
> add articles to content list

- .circleci/config.yml
> install aws on cardigan

- .circleci/config.yml
- deploy/deploy_service.js
- deploy/package.json
- deploy/yarn.lock
Seeing if it's possible to autodeploy app.
Maybe we need more coverage first, but just testing.
> autodeploy content app

- .circleci/config.yml
- deploy/deploy_service.js
- deploy/package.json
- deploy/yarn.lock
Reverts wellcometrust/wellcomecollection.org#3754
> Revert "autodeploy content app"

- catalogue/webapp/pages/worksv2.js
When passing though props, the pattern is as such:
https://reactjs.org/docs/hooks-faq.html#how-do-i-implement-getderivedstatefromprops
Not to complicated, but I feel it a fix for now as pagination is broken on V2. I might have a stab an redoing the pagination to work more Reacty like.
> make sure pagination works with the new hooks

- cardigan/stories/components/Tags.js
- common/views/components/Tags/README.md
> Add Tags to Cardigan

- cardigan/stories/components/Divider.js
- common/views/components/Divider/README.md
> Add Divider to Cardigan

- cardigan/stories/components/License.js
- common/views/components/License/README.md
> Add License to Cardigan

- cardigan/stories/components/CopyUrl.js
- common/views/components/CopyUrl/README.md
> Add CopyUrl to Cardigan

- cardigan/.storybook/webpack.config.js
- cardigan/config/colors.js
- cardigan/config/fonts.js
- cardigan/stories/components/Header.js
- common/views/components/Header/README.md
> Cardigan Header

- common/utils/get-license-info.js
> Get license back in TASL

- router/terraform/cloudfront.tf
Puts redirector, and toggles back in place.
Tests should be catching most things now.
Trying to think of a safer way to deploy, but have a check list:
> apply lambda functions to @edge

- toggles/webapp/babel.config.js
- toggles/webapp/package.json
- toggles/webapp/pages/index.js
- toggles/webapp/yarn.lock
Before sending out the link to the toggles page, wanted to add some state to let people know what state they're in.
> Toggles state

- common/styles/components/_promo.scss
- common/styles/works.scss
Unpredictably still needed this on `works`/
> add promo styles back for works

- router/terraform/cloudfront.tf
Quick tidy up and reinstate the `toggle_*` cookie.
> remove some useless query params and add toggle_* cookie to cloudfront

- router/webapp/redirects.json
> add some redirects

- catalogue/webapp/pages/_app.js
- catalogue/webapp/pages/workv2.js
- package.json
Toggles was just being left as an empty `{}` as [the null check](https://github.com/wellcometrust/wellcomecollection.org/pull/3822/files#diff-92d3b5408872dc948ee1ab59a1103940R44) wasn't returning true, and using the props value.
> ensure toggles is null, so null check works in _app contructor

- catalogue/webapp/pages/work.js
- common/utils/get-license-info.js
We've got two licenseMaps, one with uppercase, one with lowercase keys. This just gives us the lowercase one.
> Fix copyright not cleared

- content/webapp/pages/book.js
Fixes  #3664 
Should probably wait for @GarethOrmerod
> add book subtitles

- common/model/events.js
- common/services/prismic/events.js
- common/views/components/DailyTourPromo/DailyTourPromo.js
- common/views/components/EventPromo/EventPromo.js
> Show number of scheduled events on EventPromo

- catalogue/webapp/pages/work.js
Pa11y told us the title was broken.
This wraps the word page in PageLayout to get it back.
> use PageLayout on work page

- package.json
Read this so did this:
https://stackoverflow.com/questions/45034124/what-naming-convention-do-i-use-for-scripts-in-package-json
> Use package.json naming conventions

- common/styles/components/_body_text.scss
> Make strong and b tags normal Helvetica Neue Medium

- catalogue/webapp/pages/progress.js
> add markdown heading renderer to give headings IDs

- catalogue/webapp/pages/worksv2.js
- catalogue/webapp/pages/workv2.js
- common/views/components/ErrorPage/ErrorPage.js
- content/webapp/yarn.lock
For when we receive deleted message from the API:
https://api.wellcomecollection.org/catalogue/v2/works/jqp7ngre
> add removal message for a work

- dash/webapp/pages/toggles.js
Had an email from Tanya and subsequently asked if we could make things clearer on the toggles dash by @Heesoomoon.
Any other suggestions welcome!
I'd like to be directed by how people are using it, and what questions they have, and by by what functionality we need to website to keep things simple, and to avoid over-engineering it.
> add clearer actions and explanations to toggles

- catalogue/webapp/components/WorkRedesign/WorkRedesign.js
- catalogue/webapp/pages/workv2.js
Use the _actual_ Flow syntax (`@Flow`) rather than the one I made up (`$Flow`).
> Make Flow work

- .circleci/config.yml
- common/views/components/BookPromo/BookPromo.js
Not sure, how, but the cardigan build is kaput.
This is trying to fix it.
> Fix cardy build

- catalogue/webapp/components/WorkRedesign/WorkRedesign.js
- common/services/prismic/opening-times.js
> Added default daysInAdvance

- catalogue/webapp/components/SearchForm/SearchForm.js
- common/views/components/TextInput/TextInput.js
- common/views/pages/_app.js
> Use ThemeProvider for styled components

- content/webapp/pages/opening-times.js
Implements temporary measures outlined in #3439
> Opening times summary; remove future closure dates

- common/views/components/Images/Images.js
Addresses TASL icon displaying before image (after #3879)
> Wait till image lazyloaded before showing tasl icon

- common/views/pages/_app.js
The engagement event got dropped during code refactor, this puts it back in a way the works for SPA
> trigger engagement event after 10 seconds has elapsed

- router/webapp/redirects.json
> add medieval manuscripts redirect

- common/views/components/Paginator/Paginator.js
> set end of page range accurately

- content/webapp/pages/stories.js
> replace the Hidden Persuaders serial with the Intoxicants one

- package.json
Not saying we don't need auto linting, but we definitely don't need a precommit step doing nothing.
> remove legacy linting issues

- router/terraform/edge_lambdas.tf
Some manual testing led me to find out I hadn't add the file to the zip.
It'd be good to get #3923 started to get a more thorough release process in place.
> add wiRedirector to lambda

- common/services/prismic/eventsV2.js
Checks that an event has a future date to avoid trying to reduce on an empty array.
Thought that this might get picked up by Flow, might look into other linting to make sure it does.
It would be good to have a non empty array type.
> add check to make sure event has a future date

- common/services/prismic/eventsV2.js
Merge of the empty array check and @gestchild's #3932
> don't filter dates that are on the same day

- common/services/prismic/eventsV2.js
- common/views/components/CardGrid/CardGrid.js
- common/views/components/ExhibitionsAndEvents/ExhibitionsAndEvents.js
- content/webapp/pages/homepage.js
Check the right event before ordering.
Filter events before ordering.
> Check right event when ordering

- common/views/pages/_app.js
> bump polyfill version to 3

- catalogue/webapp/pages/works.js
☝️ 
Possibly related to #3877, although I've been unable to replicate that issue as described.
> Reinstate scroll-to-top after using paginator

- content/webapp/pages/article.js
> Don't display 'By ' if there aren't any contributors

- dash/webapp/pages/toggles.js
Noticed the toggles weren't working.
Must have removed this for debugging.
> readd domain to toggles cookie

- .github/ISSUE_TEMPLATE/research.md
@hthair - I've updated the research ticket to be exactly what you have on the research card.
e.g: ![](https://user-images.githubusercontent.com/26549021/51183438-14533000-18c9-11e9-8ce5-923940cf3f52.png).
This not only makes it easier to follow, but if we keep these in text as well, they're searchable within github.
> update research issue template to reflect research card

- catalogue/webapp/components/SearchForm/SearchForm.js
I was setting it form the `workType` value, which is obviously incorrect.
> set itemsLocationsLocationType from correct value

- catalogue/webapp/components/SearchForm/SearchForm.js
- catalogue/webapp/components/SingleColumnWork/SingleColumnWork.js
- catalogue/webapp/pages/work.js
- common/utils/ga.js
- common/views/components/BackToResults/BackToResults.js
- common/views/components/BookPromo/BookPromo.js
- common/views/components/Buttons/Button/Button.js
- common/views/components/Buttons/Control/Control.js
- common/views/components/CompactCard/CompactCard.js
- common/views/components/CopyUrl/CopyUrl.js
- common/views/components/EventDatesLink/EventDatesLink.js
- common/views/components/EventPromo/EventPromo.js
- common/views/components/ExhibitionPromo/ExhibitionPromo.js
- common/views/components/FacilityPromo/FacilityPromo.js
- common/views/components/GifVideo/GifVideo.js
- common/views/components/Iframe/Iframe.js
- common/views/components/ImageGalleryV2/ImageGalleryV2.js
- common/views/components/ImageViewer/ImageViewer.js
- common/views/components/InstallationPromo/InstallationPromo.js
- common/views/components/Links/MoreLink/MoreLink.js
- common/views/components/Outro/Outro.js
- common/views/components/SearchBoxV2/SearchBoxV2.js
- common/views/components/SegmentedControl/SegmentedControl.js
- common/views/components/StoryPromo/StoryPromo.js
- common/views/components/Tags/Tags.js
- common/views/components/Tasl/Tasl.js
- common/views/components/WorkMedia/WorkMedia.js
- common/views/components/WorkPromo/WorkPromo.js
- common/views/pages/_app.js
> Ga event tracking default

- content/webapp/pages/page.js
> use 16:9 image as featured media if it exists on pages

- common/services/prismic/events.js
to answer the question here:
https://github.com/wellcometrust/wellcomecollection.org/pull/3984#discussion_r249412693
And it is nicer.
> simplify orderEventsByNextAvailableDate

- catalogue/webapp/pages/work.js
- dash/webapp/pages/toggles.js
- router/webapp/ab_testing.js
The outcome of the A/B test for the single column work page vs. work page with download links in a right-hand sidebar was that there was no significant change in downloads, so we are happy to move all traffic to a single-column view.
Closes #3953
> Promote single column work to production for 100% of traffic

- content/webapp/pages/events.js
- content/webapp/pages/whats-on.js
To make sure what's on get's all the events.
> bump page count on whats-on

- common/utils/ga.js
- common/views/pages/_app.js
> Ga time on page

- catalogue/webapp/components/WorkDetails/WorkDetailsNewDataGrouping.js
- catalogue/webapp/pages/work.js
- dash/webapp/pages/toggles.js
References: #3954
Creates a new component to group work metadata differently.
Puts it behind a toggle so people can see it.
> Works meta grouping

- catalogue/webapp/pages/works.js
> make search filters persist for pagination

- catalogue/webapp/pages/works.js
Worth starting to think about contextual error handling, but this should do for now.
> add error message to works page

- catalogue/webapp/pages/works.js
Reverts wellcometrust/wellcomecollection.org#4009
All fixed now.
> Revert "add error message to works page"

- common/model/iiif.js
- common/views/components/IIIFBookPreview/IIIFBookPreview.js
Completely WIP, just trying to get the bits in place to start thinking about next steps.
> add IIIFBookPreview

- common/views/components/IIIFBookReader/IIIFBookReader.js
From the prototyping work we have been doing in our CoDI sprint.
> add IIIFBookReader component

- common/views/components/IIIFBookGrid/IIIFBookGrid.js
> add IIIFBOOKGrid component

- common/model/iiif.js
- common/views/components/IIIFBookGrid/IIIFBookGrid.js
- common/views/components/IIIFBookPreview/IIIFBookPreview.js
- common/views/components/IIIFBookReader/IIIFBookReader.js
> add IIIF types

- catalogue/webapp/components/WorkDetails/WorkDetails.js
- catalogue/webapp/components/WorkDetails/WorkDetailsNewDataGrouping.js
> use production label on works

- catalogue/webapp/pages/work.js
- catalogue/webapp/pages/works.js
- catalogue/webapp/services/catalogue/urls.js
- dash/webapp/pages/toggles.js
- router/webapp/ab_testing.js
References #3956
B condition wins, so search box is now on all individual work pages
> Stop search box A/B test

- catalogue/webapp/components/WorkDetails/WorkDetails.js
- catalogue/webapp/components/WorkDetails/WorkDetailsNewDataGrouping.js
The `field:"value"` searches don't work.
Let's remove them to make them slightly better.
> remove not-working field search from works

- common/views/components/EventsByMonth/EventsByMonth.js
fixes issue on what's on listing where promo is linking to the wrong event
> Use lodash sortBy not sort

- common/model/iiif.js
- common/utils/convert-image-uri.js
- common/views/components/IIIFBookReader/IIIFBookReader.js
- common/views/components/ImageViewer/ImageViewer.js
- common/views/components/ImageViewer/ImageViewerImage.js
- common/views/components/WorkEmbed/WorkEmbed.js
- common/views/components/WorkMedia/WorkMedia.js
Adds image zoom to IIIFBookReader component
> IIIFBookReader zoom

- common/views/components/ImageViewer/ImageViewer.js
- common/views/components/ImageViewer/ImageViewerImage.js
Using context so don't have to pass props down the component chain
> Image viewer props

- common/views/components/NewsletterSignup/NewsletterSignup.js
Ref #4061 
Adding types to the newsletter signup as it was missing it's `@flow`.
> add type to newletter button

- .eslintrc.json
- catalogue/webapp/pages/work.js
- catalogue/webapp/pages/works.js
- package.json
- yarn.lock
Adding a linting plugin for react hooks and making the appropriate linting changes to `/pages/*.js`
[Rules of Hooks](https://reactjs.org/docs/hooks-rules.html)
> Add eslint-plugin-react-hooks

- prismic_remapper/installations_to_exhibitions/after.json
- prismic_remapper/installations_to_exhibitions/before.json
- prismic_remapper/installations_to_exhibitions/premapped/W-K6iBUAAJqYxKMi$0743d833-015b-454f-a632-5309c32c35c0.json
- prismic_remapper/installations_to_exhibitions/premapped/W-K8VhUAAKOcxKsl$26bb4478-29f7-4995-b3a9-bb76ebc428fc.json
- prismic_remapper/installations_to_exhibitions/premapped/W-LESBUAAJ-dxM5y$948ba27b-f081-4aa4-91f5-b3050c4ec332.json
- prismic_remapper/installations_to_exhibitions/premapped/W3LDcCkAACcAEKqy$a8f91af1-5b4c-464a-8222-b1ebdc1d2f55.json
- prismic_remapper/installations_to_exhibitions/premapped/W5Y-NyYAACMALAdp$81b921be-f154-4eba-9dcd-3aedaebe402e.json
- prismic_remapper/installations_to_exhibitions/premapped/W78dJBEAAB8NpQle$45db05f9-e8e0-447c-9f39-2f7317f3d47c.json
- prismic_remapper/installations_to_exhibitions/premapped/W7T-FxAAADRy0mu0$e7c08027-0bda-42ac-9e69-d2e56d5a324d.json
- prismic_remapper/installations_to_exhibitions/premapped/W9sIhRUAANoQovHe$406c72dc-876d-4424-81f9-2f5f6b702f05.json
- prismic_remapper/installations_to_exhibitions/premapped/W9xNPBUAAO5nqHyO$c964cf57-9e79-4b06-b791-28a9038d301e.json
- prismic_remapper/installations_to_exhibitions/premapped/WqwC1iAAAB8AJgFB$9b5afa48-f5b6-430c-bf85-309b2ec29546.json
- prismic_remapper/installations_to_exhibitions/premapped/Wrynhx8AAAjk9XX-$c94dd47b-2a21-49f2-af38-38ad9fe5c277.json
- prismic_remapper/installations_to_exhibitions/premapped/WryoVx8AAAjk9Xmg$2f9a0c3d-f168-49f1-8a18-070e30225186.json
- prismic_remapper/installations_to_exhibitions/premapped/Wryoox8AAAjk9Xr0$e023a8cd-4220-4551-b56e-34276f7f360c.json
- prismic_remapper/installations_to_exhibitions/premapped/WthzICAAAOObLY5K$168afd46-abb3-4f64-ab10-215132d1711d.json
- prismic_remapper/installations_to_exhibitions/premapped/WyuWLioAACkACeYv$562e587b-ab4b-451f-bc00-c8b12faa3c46.json
- prismic_remapper/installations_to_exhibitions/remap.js
Ref #3738 
Remap installations to exhibitions.
Make sure they're delisted.
Next step: Add exhibitions to exhibitions.
> remap exhibitions to installations

- common/services/prismic/exhibitions.js
- common/views/components/SearchResults/SearchResults.js
- prismic-model/js/exhibitions.js
- prismic-model/json/exhibitions.json
ref #3738 
Exhibition exhibiting exhibitions.
We'll remove all the installation references when they are no more.
> Exhibitions in exhibitions

- cache/terraform.tf
Adds the new redirects for installations => exhibitions
> bump lambda versions on prod cache

- catalogue/webapp/components/SearchForm/SearchForm.js
- catalogue/webapp/pages/work.js
- catalogue/webapp/pages/works.js
- common/views/components/TextInput/TextInput.js
Ref: 
Brings the search bard size down by 1 when on the work page.
> bring the search bar size down a notch on /work/id

- catalogue/webapp/pages/work.js
- common/views/components/WorkHeader/WorkHeader.js
> shrink vertical spacing on WorkHeader

- common/views/components/WorkHeader/WorkHeader.js
> Work header spacing

- common/views/components/OutboundLinkTracker/OutboundLinkTracker.js
> check for type of href as SVG's hrefs aren't strings

- content/webapp/components/Exhibition/Exhibition.js
- content/webapp/components/Installation/Installation.js
Putting the yellow box on the installation page template.
> Share info box items with installation page

- common/views/components/Paginator/Paginator.js
☝️ 🐎 
https://github.com/zeit/next.js/#prefetching-pages
(As seen on Wes Bos's course).
> Prefetch next/previous page of paginated results

- content/webapp/pages/book.js
> Use button for order book CTA

- common/model/exhibitions.js
- common/services/prismic/exhibitions.js
- common/views/components/CardGrid/CardGrid.js
- common/views/components/ExhibitionPromo/ExhibitionPromo.js
> Remove installation description

- cache/terraform.tf
> increase lambda versions on prod cache

- cache/README.md
> add deploy section to README

- content/webapp/pages/event.js
References #4033
Having spoken with Alice, it is safe to infer that events with a cost will not be 'just turn up'.
> Don’t show ‘Just turn up’ if the event has a cost

- catalogue/webapp/pages/PROGRESS_NOTES.md
The 678 people who viewed `/works/progress` last month.
Giving them some more information.
> add release notes for feb 2019

- common/model/events.js
- common/services/prismic/events.js
- common/views/components/DailyTourPromo/DailyTourPromo.js
- content/webapp/pages/event.js
- prismic-model/js/events.js
- prismic-model/json/events.json
references #4033
Allows third party link to be used for booking events and displays it in our button style
> Event booking

- catalogue/webapp/components/WorkCompactCard.js/WorkCompactCard.js
- common/styles/utilities/_root-scope-classes.scss
> update designs on work card

- content/webapp/pages/book.js
Addresses missing piece on #4089
> Change CTA text to 'Buy the book'

- .github/ISSUE_TEMPLATE.md
Makes the links apply the relevant labels.
> Emojify the GitHub issue templates

- catalogue/webapp/components/SearchForm/SearchForm.js
- catalogue/webapp/pages/works.js
- dash/webapp/pages/toggles.js
* Adds a feedback toggle that is now behind it's own switch
* Makes work types links
* Use checkboxes for "selected" as they're a common pattern. Design as per chat with @GarethOrmerod 
I'd like to look into the accessibility of check boxes outside of forms before we push this live, and if we decide to keep them.
They're also a little unresponsive, something else to work on.
> put feedback behind a toggle and remove pseudo filter of 'images'

- cache/terraform.tf
This might get a little tedious, might be worth thinking of how we might decouple the actual tests and the testing config from the testing infra.
> bump edge lambdas for A/B test

- common/model/opening-hours.js
As per https://github.com/wellcometrust/wellcomecollection.org/pull/4180#discussion_r260717715
The times aren't needed any more.
> remove last years exceptional times from JSON+LD

- catalogue/webapp/pages/work.js
- catalogue/webapp/pages/works.js
- common/styles/utilities/_root-scope-classes.scss
- common/views/components/BetaBar/BetaBar.js
- dash/webapp/pages/toggles.js
Ref #3959 
Sits behind a toggle.
Just moves the current messaging into a bar.
To see what it looks like and if it interferes with any other elements.
> beta bar commence!

- common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
Fixes broken landscape image thumbnails, thumbnails need both width and height
> provide max width for thumbnails

- catalogue/webapp/pages/item.js
- catalogue/webapp/pages/work.js
- common/model/iiif.js
- common/services/catalogue/urls.js
> Individual canvas per page starter

- catalogue/webapp/pages/works.js
- common/views/components/Header/Header.js
- dash/webapp/pages/toggles.js
For confidence when we release.
We could create a branch called `books_release` or something, merge things into that and release.
Pretty old school and makes me think planning it as smaller releasable chunks would be nicer, but maybe my tech hat clouding the waters with not wanting to release bugs.
> seperate toggles a little to prepare for testing of books release

- catalogue/webapp/pages/works.js
Ensure we send the right parameters through to the API when we need to include books.
Hopefully made the property names more descriptive.
Lot's of features = mass confusion.
I'll tidy these up as we go on.
> add logic around how toggles affect filters on  results

- catalogue/webapp/components/WorkCard/WorkCard.js
> add image alt so screenreaders don’t read out file name

- cache/cloudfront_dev.tf
- cache/cloudfront_prod.tf
Needs doing for server side rendering for `/items`
> add sierraId and canvas to cloudfront query params

- catalogue/webapp/components/WorkDetails/WorkDetails.js
> Change label title to Type/Technique

- catalogue/webapp/pages/works.js
> hide the search header when there are results

- common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
> text change and layout of preview cta

- catalogue/webapp/pages/works.js
> Name the "explore our collections" toggle correctly

- common/views/components/BetaBar/BetaBar.js
- common/views/components/TabNav/TabNav.js
* Gets the syntax highlighting working a bit nicer 
* Keeps styles associated with relevant DOM
* Sightly less code.
✨
> use attrs(className) on BetaBar / TabNav

- catalogue/webapp/components/WorkDetails/WorkDetails.js
- common/views/components/WorkHeader/WorkHeader.js
> make contributors LinkLabels on WorkHeader and tags in WorkDetails

- cache/edge_lambdas/redirector.js
- cache/edge_lambdas/redirector.test.js
- cache/edge_lambdas/toggler.test.js
- cache/edge_lambdas/wiRedirector.js
- cache/edge_lambdas/wiRedirector.test.js
Before doing some work on it, it felt like it would be worth linting.
> lint cache JS

- common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
Does the same as this #4266, but for the main image of the preview
> request max thumbnail for preview

- catalogue/webapp/pages/work.js
Noticed the search wasn't working on the work page
> Add SearchProvider to work

- cardigan/stories/components/IIIFPresentationPreview.js
- catalogue/webapp/pages/work.js
- common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
- common/views/components/IIIFPresentationPreview/README.md
Adds the IIIFPresentationPreview component to cardigan
> add IIIFPresentation component to cardigan

- catalogue/webapp/pages/item.js
> Use 90% of viewport height for viewer

- catalogue/webapp/pages/item.js
> Rotate arrows instead of both buttons

- common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
Sends a GA event when the book preview link is clicked
> Add tracking to preview link

- cardigan/stories/components/TruncatedText.js
- catalogue/webapp/pages/item.js
- common/views/components/TruncatedText/README.md
- common/views/components/TruncatedText/TruncatedText.js
> Move heading above viewer and truncate title to one line

- catalogue/webapp/pages/item.js
uses the OCR text for a canvas as the alt attribute value of the main image in the viewer
> Viewer alt

- catalogue/webapp/components/SearchForm/SearchForm.js
~Haven't put this behind a toggle, but marked as draught only to be merged once book stuff is in.~
Put this behind the same toggle as `catalogueSearchHeaderExploreMessaging` to be ready for @hthair in user testing.
> Change input message

- catalogue/webapp/pages/item.js
UI tweak that was bothering me.
> Use consistent spacing after button rotation

- catalogue/webapp/components/SearchForm/SearchForm.js
- catalogue/webapp/pages/work.js
- catalogue/webapp/pages/works.js
- common/views/components/Header/Header.js
- toggles/webapp/toggles.js
Combination of
* Collections in navigation
* Filters
* Explore content in search bar
Next step would be to turn it on by default.
> Janeway - Dante's Inferno: Consolidate the toggles for books release

- common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
> preview is breaking if there is no table of contents

- catalogue/webapp/pages/item.js
- common/model/iiif.js
- common/views/components/IIIFResponsiveImage/IIIFResponsiveImage.js
- common/views/components/ResponsiveImage/ResponsiveImage.js
Using `srcset` ~and lazyloading to render images at appropriate sizes~.
The current `Images` components are doing a lot of work that feels custom to the editorial/Prismic-y areas of the site, so starting out with a fresh component that _only_ did the responsive~/lazy~ image stuff felt appropriate. Thoughts?
> Add ResponsiveImage component

- toggles/webapp/toggles.js
The toggle wasn't being referenced anywhere anyway.
> remove collectionsInMainNavigation toggle

- content/webapp/pages/stories.js
Need to have a think about how this is manual - maybe the first part of looking at managing lists.
> swap out for architecture stories on stories page

- catalogue/webapp/pages/item.js
- common/views/components/Buttons/Control/Control.js
- common/views/components/ImageGallery/ImageGallery.js
- common/views/components/Pagination/Pagination.js
- common/views/components/Paginator/Paginator.js
Fixing invalid markup (an `<a>` shouldn't contain a `<button>` as a descendant).
> Move NextLink inside Control

- common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
not all manifests have structures, so checking first
> check for structures before mapping

- catalogue/webapp/pages/PROGRESS_NOTES.md
Updating progress notes to reflect new beta status and updates about this release.
Note that I removed the past updates
```
From the feedback we've had over the past couple of months, we've been adding
clarity and emphasis to the information on our library item pages.
This will hopefully help with getting an overview of the item and to assess its
relevance more effectively.
What we've done:
* The title is the first piece of information seen, along with a summary of
the object, including contributors and its publication date.
* The details about the item have been grouped in sections to help to scan the
information more easily.
* The ordering of the information has been slightly tweaked on the feedback of
what people consider important.
The search bar persists through the search journey, …
```
> Janeway beta update March 2019

- prismic-model/js/interfaces/ContributedThing.js
- prismic-model/js/interfaces/LocatedThing.js
- prismic-model/js/interfaces/Thing.js
- prismic-model/js/interfaces/TimedThing.js
- prismic-model/js/types/event.js
- prismic-model/js/types/exhibition.js
- prismic-model/js/types/person.js
- prismic-model/js/types/place.js
- prismic-model/js/types/story.js
- prismic-model/json/types/articles.json
- prismic-model/json/types/event.json
- prismic-model/json/types/exhibition.json
- prismic-model/json/types/people.json
> [Example] Consolidate Prismic models

- toggles/webapp/toggles.js
> Janeway engage

- common/styles/components/_header.scss
- common/views/components/Header/Header.js
> recentre logo in header

- catalogue/webapp/pages/works.js
- common/views/components/TabNav/TabNav.js
> actually attach the onclick handler to tabbed nav items

- catalogue/webapp/pages/work.js
- common/views/components/Buttons/Button/Button.js
- common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
> no JS view item link from work page

- catalogue/webapp/pages/item.js
- common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
- #4313 means we now have a link to the viewer for works that only have PDFs wrapped in a iiifManifest.
- The viewer can't handle this so the page breaks.
- This gets the pdf url and shows it in a iframe.
N.B. we'll want to revisit/tidy this up but want to get it in before going home as it's breaking the site.
> Viewer pdf

- common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
> center full view text on Safari

- common/views/components/VenueHours/VenueHours.js
> s/The Library/Library

- common/views/components/FindUs/FindUs.js
Addresses [point](https://github.com/wellcometrust/wellcomecollection.org/issues/4361#issuecomment-482610540) on #4361.
> Move 'Getting here' up

- cache/cloudfront_dev.tf
- cache/cloudfront_prod.tf
> whitelist _queryType in cloudfront

- common/model/opening-hours.js
- common/model/organization.js
- common/views/pages/_app.js
- common/views/pages/_document.js
Noticed we were getting the opening times for the Library and Collection from static code, not Prismic, for the json-ld. This rectifies that.
> Json ld from prismic

- common/utils/dates.js
- common/views/components/EventsByMonth/EventsByMonth.js
fixes #4389, which is still useful before removing the date picker
> Whats on bug

- content/webapp/pages/opening-times.js
> text changes

- cache/edge_lambdas/redirects.js
> added redirect

- cache/terraform.tf
> bump lambda versions

- cardigan/stories/components/EventSchedule.js
- common/views/components/EventSchedule/README.md
- content/webapp/pages/event.js
> Add EventSchedule to cardy

- catalogue/webapp/pages/work.js
References #4341 
Adds the work object to the data layer, so we can make use of it in tag manager
> add work object to data layer

- common/services/prismic/parsers.js
- common/views/components/Body/Body.js
- prismic-model/js/parts/body.js
- prismic-model/json/books.json
- prismic-model/json/event-series.json
- prismic-model/json/events.json
- prismic-model/json/exhibitions.json
- prismic-model/json/pages.json
- prismic-model/json/places.json
- prismic-model/json/series.json
- prismic-model/json/webcomics.json
Adds the ability to create anchor points within the body of a page in Prismic, so we can link to them.
> In page linking
