wellcomecollection/wellcomecollection.org

common/package.json
common/services/prismic/api.js
common/services/prismic/articles.js
common/views/components/DefaultPageLayout/DefaultPageLayout.js
common/yarn.lock
content/webapp/server.js

Use our own implementation of when to serve preview content as Prismic's is likely to change, and their advice is use preview everywhere 😿 .

use isPreview cookie and stop relying on Prismic's preview implementation

---

common/views/components/DefaultPageLayout/DefaultPageLayout.js
content/webapp/server.js

deletes the preview cookie before setting another.
Seems to help, I'd like to understand more why, but that can wait.
Also accounts for the cookie being the last cookie and thus not having the `;`.

delete troublesome prismic cookie

---

common/services/prismic/events.js
common/utils/dates.js
common/views/components/EventsByMonth/EventsByMonth.js
whats_on/app/controllers.js
whats_on/app/views/pages/events.njk

Finishing up the events ordering stuff
As discussed with @Heesoomoon 
/events shows current and upcoming in ascending order (with the next available date displayed)
/past shows past in descending order
N.B. @Heesoomoon was keen to remove past events from /events and it was also necessary technically, so as not to get into weird ordering issues with pagination. We probably need to add a link to past events, from events?
There's quite a lot going on here in terms of the difficulties that arise between how we can query from prismic and how we want to display things. I want to write it all down, so it's clear to myself and others, but haven't managed to yet - will do this ASAP.

Events ordering

---

common/services/prismic/html-serialisers.js
router/redirects.conf

Makes sure we render all this children.
It was a slight misunderstanding of how the serialisers work.
This case, when there are multiple spans, there will be multiple string children returned.
---

make sure drop cap serialises serialises all text

---

catalogue/terraform/terraform.tf
catalogue/webapp/server.js
content/terraform/terraform.tf
content/webapp/server.js

Noticed some 500s on the `nextjs` JS. 
This time not content that couldn't be served because the cache had cleared, but rather content that wasn't available yet as the healthcheck was passing, but the next app hadn't actually started.
The reason for this is the healthcheck `/management/healthcheck` is serving from the nginx server, and in this case, the nginx `server` of the server app.
So now we have the healthcheck render from the app itself meaning we will only start passing content to it once the app is up.

add healthchecks to nextjs apps

---

common/services/prismic/exhibitions.js

Annoyingly promos can be `null`, `[]`, or `[{ promoContent }]` - so we need to double check.
Tried to think of a more scalable solution, but think that would be migrating the promo to not be slices, but root properties - which will be hard.

allow no promo on exhibitions

---

common/styles/utilities/_root-scope-classes.scss
common/views/components/Body/Body.js

Applies the drop cap to the first text slice in the body, rather than the first slice - which might be an image etc.

apply drop cap to first instance of text slice in body

---

toggles/README.md

Gives us a checklist, but also a place to start for toggles.
Might work on the purpose / process of how we might use them once I've got through the checklist.

Move toggles readme over to repo

---

common/services/prismic/event-series.js
content/terraform/terraform.tf
content/webapp/pages/event-series.js
content/webapp/server.js

Fixes #3538
Ref #3540 
Regressed because when creating the new logic around event ordering, we filter a list if it is ordered `desc`. So now we order `asc`.

Event series

---

content/webapp/pages/event-series.js
content/webapp/pages/event.js

Had a load of explosions alerting us to the fact that we're not parsing the JSON dates.
It'd be good to have a think about how we might do this more scalably?

parse JSON event dates in event series

---

common/data/our-voice-our-way.js
common/model/periods.js
common/services/prismic/articles.js
common/services/prismic/utils.js
common/views/components/CardGrid/CardGrid.js
content/webapp/pages/homepage.js
content/webapp/server.js

Ref #3540 
Forked from #3570 
Renders the homepage from the `content` app.
It won't serve traffic until we setup the listeners, so this is pretty safe and will be able to be tested on `content.`.

Render homepage from content app

---

common/views/components/Contributor/Contributor.js

Fixes #3480
Makes sure the contributor image isn't squashed by the text.

Stop flex child from shrinking if sibling text gets too long

---

catalogue/webapp/services/catalogue/works.js

Not sure why we weren't  doing this?
Any idea?
Noticed it from the erroring:
https://wellcomecollection.org/works?query=creators%3A%22Petros%20M%C3%85%C2%8Drait%C3%84%E2%80%9Cs%22

encode query for works

---

content/terraform/terraform.tf

Ref #3540 
~Waiting on: #3573~
Routes traffic for the `/` and `/whats-on` to the new content app.

route traffic for whats_on and homepage to content app

---

common/views/components/PageHeader/PageHeader.js

We don't always have a widescreen image - this is to do a check before we use it to stop articles erroring.
Found from dotorg explosions./

check for widescreen image before we use it

---

common/views/components/Contributor/Contributor.js

Not sure when this started happening - might be time to look at how we're setting the width etc of our images.
Broken
Fixed

Force size on contributor org image

---

common/views/components/DefaultPageLayout/DefaultPageLayout.js
common/views/pages/_document.js

Moves the polyfill service into DPL.
Oddly, I noticed that the script was being injected quite far down the head, where we had already run some of the JSON LD JS, which includes `Object.assign`.
Adding it here seems to add it to the top of the `<head>`. Not much time to figure out why, just needed to know that it did.
Seems the org logos also look good in IE.

move polyfill io into default page layout

---

common/views/components/BookPromo/BookPromo.js
common/views/components/EventPromo/EventPromo.js
common/views/components/ExhibitionPromo/ExhibitionPromo.js
common/views/components/WorkPromo/WorkPromo.js

When we moved to the Next apps the tracking stopped working, because we were relying on the client/app.js which we no longer use.
This puts the tracking into the components

Put tracking back

---

.circleci/config.yml
pa11y/webapp/next.config.js
pa11y/webapp/package.json

Just copies the nicer dash to the same location.
Didn't want to do more work on it, as I wonder if there's something better we could be building i.e.
- Commit
- Build app (content / catalogue)
- In app testing phase: Run report
- Compare to old report
- Regressions? Error
- No regressions? Commit new report
We're missing a few things to be able to do this, (having circleci commit for us, which would also be good for linting).

add pa11y to circle

---

catalogue/webapp/server.js
common/services/unleash/feature-toggles.js
content/webapp/server.js

## Requirement
Allow us to develop a feature, behind a switch (available on prod) - and to turn that switch on and off for the public. 
This means `isUserEnabled` is set via the URL and cookie.
There is also not a field in Unleash which is `isPublic` that will turn this on for everyone.
The alternative, I suppose, would be, when we would like to switch, we could change the strategy to `default` and just turn it on off.
I think I prefer a three phase switch:
- Off
- Off for public, switchable for us
- On for all

allow userenabled switches to be set to public via app

---

common/services/unleash/feature-toggles.js
content/webapp/server.js

If we're good with this and #3607 - I'd like to send an event off to GA, just to get confidence that we are splitting by what we say we're splitting __with cache__. 
It worked for the NGINX bit, so we might be good.

add ab strategy to unleash

---

content/terraform/terraform.tf

Waiting on #3593 
Routes all event traffic through to content app. Currently `/events/{id}` already is, this is just for the listings.

route all events to content app

---

content/webapp/pages/exhibition.js

Underlining 'What's on' in the nav when you're on an individual exhibition.

Re-add underline under what's on for exhibitions

---

cardigan/stories/global/spacing/README.md
cardigan/stories/global/spacing/spacing.js

Spacing info feels like it belongs in the `Global` section of the docs. Moved it there along with a basic demo of the Section and Component spacings.
Would be good to find a way to fix the (ironically awful) markdown spacing for the documentation.

Move spacing (and add demo) to Global section of Cardigan

---

common/utils/analytics.js

Previously, we treated scrolling as an interaction in GA, so it affected bounce rate. When we switched to use `ReactGA` we stopped doing this. This PR reinstates scrolling as an interaction so that @hthair gets consistent data to analyse.

Specify scrolling as an interaction (to keep data consistent)

---

common/styles/utilities/_root-scope-classes.scss

Reducing the space between sections and components for narrower viewports after discussion with @Heesoomoon. We should ask @GarethOrmerod to review the hierarchy when he's back.

Scale spacing between sections and components responsively

---

common/koa-middleware/withGlobalAlert.js
common/services/prismic/opening-times.js
content/webapp/server.js

Ref #3632 
Realising the initial page load at the moment is getting very heavy.
Looking at the stats, it's the initial page load that taking a while which would make sense, as for every page load we are making 2 synchronous calls to Prismic, and then whatever other API calls we need to make for data, so the latency is going to be large - and this is before anyone even sees the page.
Looking at the averages, I think we're mitigating this by:
- On content pages, CloudFront cache
- On Works, having the initial page load and then the rest of the interface being asynchronous
In the future though, it feels as though relying on cache for highly user centred requests (search), or letting people wait ages for the initial app to load seems unfair.
We have also coupled the whole site with Prismic …

get global alert on server

---

common/styles/components/_captioned_image.scss
common/styles/components/_lazyload.scss
common/styles/components/_work_media.scss
common/styles/utilities/_root-scope-classes.scss
common/views/components/Image/Image.js
common/views/components/Images/Images.js

Without js enabled the images were displaying weirdly on the site: duplicated/ blurry with alt text showing/ covering the whole page on works:

No js image display

---

catalogue/webapp/server.js
common/koa-middleware/withGlobalAlert.js
common/views/components/PageWrapper/PageWrapper.js

Makes use of the work James did here: #3613, so we don't have to wait for the API call to Prismic for the globalAlert

Global alert perf

---

build/nginx.conf
nginx-proxy/nginx.conf
nginx_webapp/nginx.conf
router/terraform/ab_testing.tf
router/terraform/cloudfront.tf
router/terraform/terraform.tf
router/webapp/ab_testing.js
router/webapp/index.js
router/webapp/test_event_request.json
router/webapp/test_event_response.json

Ref #3631 
After hassling around with the cache for ages, I thought, surely we could use a lmabda for this.
Turns out it's a pretty standard way as you can have lambdas @ edge (before the cache).
It feels like this would be a way more sustainable solution to A/B testing, and breaks from using subsiderary services (unleash).
[It also seems to be quite common](https://www.google.com/search?q=lambda+A%2FB+testing).
Here's a flow of cookies / headers: https://docs.google.com/drawings/d/1053dECKDOsVwIAUqtq-Q5N6DEJJ7TmYIW-mu3_TtpgI/edit?usp=sharing
__Edit__
Moved to a multi cookie setup where we have `toggle_*`.
This will allow us much more control over what we allow, and don't allow, and will also allow us to more finally tune a users experience. e.g.
Vimbai visits the site, we see there are …

Add infra for ab_testing lambda@edge

---

content/webapp/pages/event.js

The `getInitialProps` issue again, serialising `Date`s down to strings.
Then the comparison is on strings, which then puts everything out of whack when reordering the events.

parse date range as date on events from getInitialProps

---

common/koa-middleware/withToggles.js
content/webapp/server.js

Adds a simple way of setting toggles thanks to #3638.
A user toggle now needs to stay in the URL, which might not be ideal, but that's relatively easy to fix, I'd rather wait for it to come up as a requirement though.
The stickyness would be dealt with in the lambdas, this abdocates all cookie writing to the lambda, which makes way more sense.

add simpler toggles

---

common/views/components/PageWrapper/PageWrapper.js

We need to check if we're on the server first, before retrieving anything off of the `ctx.req`.
If we aren't on the server, we use the `clientStore`.

retrieve global alert

---

common/utils/analytics.js

dont report on empty page state

---

common/styles/utilities/_root-scope-classes.scss
common/views/components/PageHeader/PageHeader.js

Fixes #3661 
The absolutely positioned cream background that has to go behind part of the hero image _and_ cover the white gap that would appear between sections as a result of the section spacing now has to be responsive (since the section spacing is larger on desktop than mobile).

Responsive hero-image-bg

---

common/views/components/Image/Image.js
common/views/components/Promo/Promo.js

We want `Promo` images to be 16:9 everywhere, so we should use the 16:9 Prismic crop that we auto-generate for this.

Use 16:9 crop for promo image if available

---

common/utils/parse-query-string.js
content/webapp/pages/newsletter.js

Fixes #3666
`context.query` was no longer the object that we wanted to search for the 'error' or 'success' strings since moving to NextJS. Added a util that creates the object we want from a URL path.

Add url query parser util

---

catalogue/webapp/server.js
common/koa-middleware/withCachedValues.js
common/package.json
common/services/prismic/api.js
common/yarn.lock
content/webapp/server.js

A few errors caught us recently by not serving the cached values to our pages.
This helps with that by abstracting it out. I wonder if we should also deal with null cvalues as we've otherwise tightly oupled the templates and external resources.
TODO:

add composed middleware and add helper route to avoid duplication, and buggy, code

---

catalogue/webapp/pages/worksv2.js
catalogue/webapp/pages/workv2.js
catalogue/webapp/server.js
catalogue/webapp/services/catalogue/worksv2.js

Use V2 for the works.
Seems the best way to go ahead, just create some new routes, we can then start testing them later, or allowing people to swap to them.
Does not look pretty on purpose so we can start defining what components we need:

add v2 pages to catalogue app

---

cardigan/.cache/325c8f456729b912b0d2134054eb7448-dfeeb2271cc2857eb0a45a5003c8bbee
cardigan/stories/components/Promos.js
catalogue/webapp/pages/works.js
catalogue/webapp/pages/worksv2.js
catalogue/webapp/pages/workv2.js
catalogue/webapp/services/catalogue/links.js
catalogue/webapp/services/catalogue/worksv2.js
common/views/components/WorkPromo/WorkPromo.js

Feels like a decent way to get about it.
Links are always programmatically defined, and turned into things next can understand.
Could work for content as well, where you just pass a type too.

add work links to catalogue app

---

common/views/components/BasePage/BasePage.js
common/views/components/BasePage/ErrorPage.js

Only render the `SpacingSection` that wraps the `Body` if the `Body` has something in it.
Also, use `li`s inside the `ul` on the 404 page.

Tidy up error page spacing/list

---

common/views/components/Contributor/Contributor.js

Add plain-text class to contributor to add link-hover style

---

common/styles/components/_footer.scss

Darkening the green made the link in footer inaccessible. This leaves the default underline on the link in the footer and removes it on hover.

Fix footer link a11y

---

prismic-model/js/series.js
prismic-model/json/series.json

Fixes #3716
I've updated the handful of serials that were using turquoise to use teal in Prismic, too.

Change turquoise to teal in serial colours

---

common/views/components/ContentPage/ContentPage.js

We're still potentially adding an empty spacing component because the check for a non-empty body section didn't account for a standfirst slice ([which we now ignore since it has been moved to the header](https://github.com/wellcometrust/wellcomecollection.org/blob/master/common/views/components/Body/Body.js#L41)). 👇 Twice as much space as desired 👇

Account for non-rendered standfirst being in body props

---

.circleci/config.yml

Feels like removing it from here might show us the deps, which I think are none, then we can remove the code that this is relying on.
* build_client
* build_common_webapp
* install_server_modules
* deploy_assets
* client_modules_circleci_node_8_
* built_dist_
* built_server_

remove old server and client steps from the build

---

catalogue/webapp/pages/worksv2.js
common/views/components/Buttons/Control/Control.js
common/views/components/Pagination/Pagination.js
common/views/components/Paginator/Paginator.js

Starts to use the `useEffect` hooks for fetching data.
We now have the `query` and `page` state, that when changed, trigger the effect of setting loading, change the URL and fetching the works.
There's a couple of `TODO`s but it feels like the code is concise and then interface responds much more fluidly.

add paginator to catalogue

---

router/nginx.conf
router/webapp/redirects.json

A few more added, and some of the older ones removed from router.
I want to get router cleared of all wellcomecollection.org content, then it can become a wellcomelibrary.org router.

add some redirects for the old drupal content

---

catalogue/webapp/pages/workv2.js

For situations like this:
https://wellcomecollection.org/worksv2/bsp5r2cj
Because we don't have all the fields in there and the punctuation is still in there, we now land up with this:

null check fields that make up physical description

---

content/terraform/terraform.tf

We no longer support wordpress articles so don't need to support the `/W` URLs, which is no longer the case as we've moved onto `X...`

unsupport wordpress articles in the listnerns

---

catalogue/webapp/pages/worksv2.js

If you use the pagination at the bottom of the list of works, you don't go back to the top of the list because we're not doing a page refresh.
[This seems to be the approved way to do it](https://github.com/zeit/next.js/issues/3249#issuecomment-342735512).

Scroll to top of page after using pagination

---

catalogue/webapp/pages/workv2.js

As per the [Marc spec](https://www.loc.gov/marc/bibliographic/bd300.html), it should be extent, other physical description, dimensions.

use marc subfield ordering for Physical description

---

common/views/components/StoryPromo/StoryPromo.js
common/views/components/StoryPromoFeatured/StoryPromoFeatured.js

The `srcset` sizes for the first `StoryPromo`  on `/stories` needs to be able to handle a larger image. Currently, we're only loading a ~380px-wide image in a ~800px-wide space.

Make sizesQueries configurable for StoryPromoFeatured

---

common/icons/calendar.js
common/icons/index.js
common/utils/dates.js
content/webapp/pages/exhibition.js

From a message with @Heesoomoon, knowing that an exhibition isn't open yet is integral to the access information.
This just adds it to the top of the info box.

add opening date to exhibition info box

---

common/styles/utilities/_root-scope-classes.scss

☝️ 
Fixes first promo on /stories page in IE11.

Don't check for grid before displaying promo links as flex

---

catalogue/webapp/pages/work.js
catalogue/webapp/pages/workv2.js

We're just sending the string 'work.id' at the moment, which isn't very helpful.

Send work id to GA

---

catalogue/webapp/pages/PROGRESS_NOTES.md

Adds the new release notes at the top of the page, beneath the general blurb.
Notes:
* I've left off the fact that there are more results, as there actually aren't. It's about even. Some queries are returning more, some less, I am trying to chat to the content team to see what's going on with those.
* I've left off anything coming up, as it feel like, if we do tis regularly, that would be better. We might need to remember when we've used user feedback so we can let people know! Maybe we do this every Demo?
Good read on this: https://slackhq.com/a-little-thing-about-release-notes#

November 2018 release notes

---

package.json

Allows you to run the deploy scripts from the root directory.
Aware this point out my sever laziness.

add deploy script to root directory

---

catalogue/webapp/pages/worksv2.js
common/views/components/SearchBox/SearchBox.js
dash/webapp/pages/toggles.js

Adds a toggle to allow us to turn on the `workType` filters, and to sow things without images.
The reason being so people that aren't used to using the API JSON responses can see what we have.
---
Technically I've moved the `SearchBox` out of the form, as the filters need to be part of the request.
I haven't done anything with the URL yet, as it feels like it starts to open up the potential to introduce bugs for non-wc users.
I'm assuming we will try to mimic the API request `/works?query=huddle&workType=q`, but let's see when we get closer to implementing filters.
The UI is rubbish

start adding workType filters

---

common/styles/utilities/_root-scope-classes.scss

We set a class of `flex` on promos, so shouldn't be adding `display: block` to the `promo-link` properties. Prefer this to #3853?

Remove block from promo links

---

cardigan/stories/components/Links.js
catalogue/webapp/components/StaticWorksContent/StaticWorksContent.js
catalogue/webapp/pages/worksv2.js
catalogue/webapp/pages/workv2.js
catalogue/webapp/services/catalogue/urls.js
catalogue/webapp/services/catalogue/works.js
common/model/next-link-type.js
common/model/url.js
common/views/components/LinkLabels/LinkLabels.js
common/views/components/Links/SecondaryLink/SecondaryLink.js
common/views/components/StaticWorksContent/StaticWorksContent.config.js
common/views/components/Tags/Tags.js
common/views/components/WorkPromo/WorkPromo.js
common/views/global/typography/typography.js
content/webapp/pages/event.js
content/webapp/pages/whats-on.js

Stops a bug where we `routeChange`, thus `pageview` GA, but then reload the page, and call GA again.
Should also fix the tag bug we have where the page looks for the `works` route, which no longer exists, it's `href: worksv2, as: works`.

use next links for back to search

---

common/services/prismic/events.js
content/webapp/pages/event.js

We seem to have hijacked the model quite substantially to be able to fit loads of our business logic around dates and times. This goes for opening times too.
It might be good to define the shape of the simplest model / type (and thus the type) and then write some functions, that'll be testable, on how we process the information about that model.

null check on parsing displayTime property on event

---

common/views/components/Images/Images.js

The only thing I can see this affects is that TASL is visible when the image isn't.
Better than not showing it on any image that doesn't inherit the logic from `CaptionedImage`

remove coupling of state and showing tasl

---

catalogue/webapp/components/WorkRedesign/WorkRedesign.js
catalogue/webapp/pages/worksv2.js
catalogue/webapp/pages/workv2.js
common/services/prismic/types.js
common/views/components/ErrorPage/ErrorPage.js
common/views/pages/_app.js
content/webapp/pages/_error.js
content/webapp/pages/article.js
content/webapp/pages/articles.js
content/webapp/pages/event-series.js
content/webapp/pages/installation.js
content/webapp/pages/page.js
content/webapp/pages/stories.js

There are two cases in which we need to serve errors.
1. There has been an error somewhere in the stack (generally 500)
1. There has been an error from an API request (generally 404)
The general error is dealt with by `_error`, and the other case is when the `getInitialProps` returns a `PrismicApiError`.

Serve errors correctly to allow us to use Prismic script on 404

---

common/views/pages/_app.js
content/webapp/pages/articles.js
content/webapp/pages/events.js
content/webapp/pages/exhibitions.js

Error handling was overcomplicated, and only worked on the server.
Now we only show an error in `_app` if the caller `getIntialProps` sends an override.
Otherwise other errors will be picked up by `_error`.
Fixes #3884

only error when we override the status code from getInitialProps

---

common/views/pages/_app.js

Noticed the page title was undefined.
Turns out we're always rendering the ErrorPage component (shows at bottom of the page) and it was overriding the page meta data too

don’t render ErrorPage component unless there is a pageProps.statusCode

---

catalogue/webapp/app.js
common/koa-middleware/withCachedValues.js
content/webapp/app.js

~Forked from #3891~
If we ever hit a page that isn't handed with out routes, our error page can't render as we don't have the `openingHours`, `globalAlert`, nor `toggles`.
I keep hitting 500s and ignoring it, but it felt like a thing to button up before it bites us.

Cached values handler

---

common/views/components/OpeningHours/OpeningHours.js
content/webapp/pages/opening-times.js

references #3439
- make language consistent
- don't show link to revised opening hours when there aren't any
- only show message above regular opening hours in footer

Opening times tweaks

---

catalogue/webapp/services/catalogue/urls.js

We don't want to the URL to reflect the `workType` and `items.locations.locationType` if they are "default".
"default" meaning filtered.
It raises some interesting thoughts around how we might want to measure search, and also that our implementation is the opposite of what we really have, AKA, lots of data filtered is default, not the filters applied to all data.

don't set values in URL if they are default

---

catalogue/webapp/Dockerfile
content/webapp/Dockerfile

Turns out our builds were inconsistent with local as we weren't copying over the lock file.
The error was raised when we started getting the error that suggests that we were using two instantiations of React, that we had started using yarn workspaces to make sure we had 1 consistent React.
Adding the yarn.lock makes sure our builds are now consistent with local.

make sure we put yarn.lock into the Dockerfiles

---

dash/webapp/next.config.js
dash/webapp/pages/pa11y.js
dash/webapp/pages/toggles.js

`getIntialProps` runs differently on exported app.
On initial page load, it doesn't run (so selected toggles weren't been flagged as selected).
I moved everything into the standard JS lifecycle.

remove getInitialProps from dash app

---

common/views/components/EventsByMonth/EventsByMonth.js

The events on the What's on page are not always showing the correct display date, when grouped by month. For example, events listed under March are showing their February date. This fixes that.

Shows correct display date on an event when grouped by month

---

common/services/prismic/eventsV2.js
content/webapp/pages/homepage.js

With unpaginated results from the API, we're going to apply a consistent, programatic ordering and display.
These are, for now, only events in the future (an end date exists that is after today).
Ordering will then be by next available date in the times list.
The date displayed will be the date that it is ordered by.
This ordering will be considered business and display logic, therefor be kept on the edge.
I've pulled it out into it's own file as to not disrupt anything else.
Paginated results (the full list) will have to work off simpler logic.
Fixes #3914

create new events getter that only works with past and future events

---

common/services/prismic/html-serialisers.js
common/services/prismic/parsers.js
common/styles/utilities/_root-scope-classes.scss
common/views/components/Body/Body.js

Refs 3800
- uses rich text templating to style links to documents as per designs
Before:
After:

Download link styling

---

common/services/prismic/eventsV2.js
content/webapp/pages/whats-on.js

The filters for what's on today / this weekend view are suffering [the same problem as the homepage was](#3918).
This uses the same mechanism as fetching future events, and filtering programatically.

make today and weekend filters programmatic

---

common/services/prismic/html-serialisers.js

Fixes #3927
If download links (anything that links to a Prismic document) are used within a paragraph, the link will be aligned to the text baseline.

Align download links to baseline

---

common/views/components/EventsByMonth/EventsByMonth.js

Fixes broken (when not enhanced by JavaScript) links on the /whats-on page (as reported by the pa11y dashboard).

Use correct id for month h2

---

catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/pages/works.js
common/views/components/TextInput/TextInput.js

Autofocuses form element if there is not query.
It would be good to know if we should when there is no query.
Based on the fact we had it, and on the feedback:
> I use your website almost every day and previously, on the search page, there was a cursor already in the box, so you didn’t have to click on it to use it. For regular users, this saved a lot of time. That has now disappeared. Any chance it could be reinstated and make my and many other researchers’ live easier?
[And using this as inspiration to the execution](https://www.brucelawson.co.uk/2009/the-accessibility-of-html-5-autofocus/).

add autofocus back to form

---

common/views/components/StoryPromo/StoryPromo.js

☝️ 
Solves an a11y issue reported on the pa11y dashboard.

Remove StoryPromo ids (to prevent duplicates on page)

---

common/views/components/Outro/Outro.js

The `Outro` is currently displaying the 'research' item description for all three possible types ('research', 'read', 'visit').

Fix outro description bug

---

common/views/pages/_app.js

I've added (and paused) this in tag manager.
It's proving a nice testing ground to see if we could move over the `Collection` account to GTM.

remove v2 10 second engagement timer

---

catalogue/webapp/components/SingleColumnWork/SingleColumnWork.js
catalogue/webapp/pages/work.js
dash/webapp/pages/toggles.js

☝️ 
Before working on any iterations of the components in the work page, we agreed to get everything into a single column.
- added an 'Item details' heading above the data groupings
- removed the 'Download' heading
- moved 'Share' and 'We're improving…' to the bottom
- added some spacing with the `SpacingComponent` wrapper
I added a keyline above section headings ('Item details', 'Using this image' and 'Share') in an attempt to make it feel section-y. This is almost certainly a thing we're going to need (not sure if we've got anything formalised for this yet – maybe one for @GarethOrmerod and @Heesoomoon to look at).

Work single column

---

catalogue/webapp/pages/work.js

Check for the iiif image before we use it.
Not sure why typing didn't pick this up. Will look later.
Only happens on items we don't surface.

check for image before using it

---

prismic_remapper/people_remodel/after.json
prismic_remapper/people_remodel/before.json
prismic_remapper/people_remodel/remap.js

A while back we updated the people model to deprecate twitterHandle and add sameAs #3034
I've just noticed that we have 130 out of 271 people in Prismic, with a twitterHandle, which is not being rendered. Running the remapper in this PR will create a sameAs link for each twitterHandle and remove the twitterHandle

remap twitterHandle to sameAs

---

router/nginx.conf
router/webapp/wiRedirector.js

Forked from #3950 
In an attempt to have functionality in 1 place, this migrates _all_ the wellcomeimages.org redirects to the lambda.

Wellcome images redirects at edge

---

router/nginx.conf

I'd like to deprecate the router app (but keep the infrastructure).
Next up I'll start getting the rest of the Wellcome Images stuff into the lambda@edge.

remove references to V1 in nginx

---

common/views/components/ImageViewer/ImageViewer.js

Openseadragon is a client only lib.
We should be only including it on the client.
This gets rid of that really annoying hot reloading error of "document is not defined".

only include component that has openseadragon on the client

---

common/styles/utilities/_root-scope-classes.scss

☝️ 
(to be consistent with other cards, as reported by @GarethOrmerod).

Underline CompactCard titles in green on hover

---

common/services/prismic/articles.js

Uses the same data as articles on webcomics when they're not yet published.
This makes it more accurate as it puts today's date in.
It also keeps tings consistent so that editors don't get scared that it's a bug.

calculate datePublished consistently across webcomis and articles

---

catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/pages/work.js
dash/webapp/pages/toggles.js
router/webapp/ab_testing.js

References #3956 
Because we're not sure we can rely on GA's search console data for an accurate count in the A/B test, we've added a new tracking event when a visitor submits the `SearchForm`:
```
category: 'SearchForm',
action: 'submit search',
label: {the search query}
```
@hthair – the condition a visitor is in will be available in the 'Toggles' dimension as `showSearchBoxOnWork: true` or `showSearchBoxOnWork: false`.

 Promote search box from toggle to A/B test

---

shared-infra/terraform/account_iam.tf

Developers who want to easily switch roles when working in AWS.
Allows developers from the platform account to easily switch roles into the wellcomecollection.org account.
This module can also be used to allow access to any other users, including assuming roles from your own account.

Adds assume roles from platform account

---

works_analysis/get_metadata_by_work_type_tally.py

Turns out the assumption that everything doesn't have subjects, genres and any field that is an array was true.
This checks for empty array before adding to the tally.

account for empty arrays when tallying works metadata

---

cardigan/stories/components/Cards.js
common/views/components/ArticleCard/ArticleCard.js
common/views/components/Card/Card.js
common/views/components/CompactCard/CompactCard.js
common/views/components/EventCard/EventCard.js
common/views/components/FeaturedCard/FeaturedCard.js
common/views/components/Outro/Outro.js
common/views/components/SearchResults/SearchResults.js

This remove the `promoType` prop as it wasn't doing anything.
It does raise the question that, if a card can take multiple `contentTypes` - do we, and how should we, track that.

remove promoType field

---

.circleci/config.yml
router/terraform/edge_lambdas.tf

The very starts of lambda deployments.
In short:
* Build lambda ZIP super simply in circle after testing (event having the test in there are making me less 💦 )
* Push Lambda to S3
* If we deploy `aws_lambda_function.edge_lambda_response_test` it reads the version from the Terrraform provider `aws_s3_bucket_object.edge_lambda_request` and deploys it.
What we need to go through:
* Once that the lambda is deployed, does it deploy the CloudFront lambda, or is that another step?
* If that's another step, how can we make it 1 less step?

Edge lambda deploy

---

common/views/pages/_app.js

Putting back 10 second engagement event; always sending visible time on page as a nonInteraction event

Time on page tweaks

---

common/model/articles.js
common/views/components/StoryPromo/StoryPromo.js

Noticed it while reading the new series.
Moved it off of the model, as it it feels like we should keep that in line with the Prismic model, and then have calculations from there to keep things more immutable (if it were on the model, you could change it whenever).

add getArticleColor function to do exactly that

---

catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/components/WorkDetails/WorkDetailsNewDataGrouping.js

We're rendering `{' '}` as a string instead of having it output a space.

Output space in JSX

---

common/views/components/IIIFPresentationDisplay/IIIFPresentationDisplay.js

Looks like some single image works have IIIF manifest data sequences containing one item. We're currently displaying a 'Show all' button to reveal all images if these sequence lengths are greater than 0. So we can end up with something like this:
Checking the sequence length is greater than one feels like it makes sense.

Hide 'Show all' button for single-sequence works

---

catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/pages/work.js
catalogue/webapp/pages/works.js

Ref #4034 
We're adding two filters to the search bar to be able to search for images (`Pictures` and `Digital images`), Books, or both.
---

add images and books filter checkboxes

---

common/model/color-selections.js
common/model/editorial-series.js
prismic-model/js/series.js
prismic-model/json/series.json

The orange which was an option for content editors to change the background colour for series isn't accessible. Have switched it out for our green (#007868) and updated the two series that were using orange (architecture and yoga).
__5.40:1__

Use green instead of orange for accessible contrast

---

catalogue/terraform/terraform.tf
content/terraform/terraform.tf
terraform-modules/service_alb_listener/alb_listener.tf

Remove all the very specific rules that have been added for the very special routes that all inevitably fallback to the content app.
This makes the content app a priority of 50000, and we can work down from there.
While doing this, I made the terraform module more generic to be able to handle more options.
Once this is done, the router nginx app can be removed (not the infra).

Make content the fallback app in the ALB

---

catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/components/WorkDetails/WorkDetailsNewDataGrouping.js
catalogue/webapp/pages/work.js
common/views/components/LinkLabels/LinkLabels.js
common/views/components/WorkHeader/WorkHeader.js

As per the commits:
* Makes the `WorkHeader` a component 
* Hides the date label if there are no production dates
* Hides the title on WorkDetails (and alternative) if the header is present
* Fix wrapping on smaller screens
__Before__
__After__
Next up
* Add `WorkHeader` to cardigan

Header improvements

---

client/terraform/terraform.tf
terraform-modules/https_s3_website/cloudfront.tf

Clears up the pesky font loading error.
Also pumps up the cache times, as these never change, and if they do, we can clear the cache.
We could probably bump it up further too, but would like to start measuring impact before we do.

Static cors

---

catalogue/terraform/terraform.tf
content/terraform/terraform.tf

Preparing to start trimming the old `./infra`.
Realised we were oddly using the old loadbalancer in CloudWatch, it will be interesting to see if any errors arise.

remove refs to old ALB and use new ALB for CloudWatch

---

deploy/deploy_service.js
package.json

The router is no longer a service, and can't be deployed.

remove router from deployable services

---

catalogue/webapp/components/WorkDetails/WorkDetailsNewDataGrouping.js
catalogue/webapp/pages/work.js
common/views/components/MetaUnit/MetaUnit2.js
dash/webapp/pages/toggles.js

Puts the Work page header and new layout/groupings of the details behind the same toggle.
It doesn't make sense to show the new work details without the header since the header contains data now missing from this version of the work details section.
I've also put the original MetaUnit component back for now, as it was changing the original page, and made a new one for the redesigned page

Work header and details toggle

---

.eslintrc.json
common/views/components/ContributorTextList/ContributorTextList.js
common/views/components/GifVideo/GifVideo.js
common/views/components/Iframe/Iframe.js
common/views/components/Images/Images.js
common/views/components/InfoBanner/InfoBanner.js
common/views/components/TextInput/TextInput.js
package.json
yarn.lock

Using an appropriate eslint config for the tech we use.
For now, I've turned off the `flowtype/no-types-missing-file-annotation` setting, so we can incrementally fix flow in our files without breaking linting.
And we've got `lint-staged` back in to check (and autofix if possible) anything that doesn't meet our requirements.

Add prettier/standard, prettier/flowtype and prettier/react

---

common/services/prismic/exhibitions.js
common/services/prismic/multi-content.js

Adds the installation label to exhibition results.

add installation label to exhibition results

---

.circleci/config.yml

Make sure we actually copy the edge@lambda file over to S3.
Hence the versions weren't being bumped when we were trying to deploy earlier.

run edge lambda deploy on master

---

common/utils/domain.js
common/utils/ga.js
common/views/components/Links/MoreLink/MoreLink.js
common/views/components/OutboundLinkTracker/OutboundLinkTracker.js
common/views/pages/_app.js

Closes #3970
Wraps the `_app` in a component that listens for clicks, tests if those clicks are on things with `href`s at external domains, and fires an event to GA if so: 
```
{
category: 'outbound',
action: 'click',
label: url,
}
```
Took the outbound link tracking off the `MoreLink` component to prevent duplication.

Add outbound link tracking

---

cache/cloudfront_dev.tf
cache/cloudfront_prod.tf

At some stage we might create a catalogue specific cache, but for now this will do.

allow works specific query parameters through the cache

---

dash/webapp/pages/toggles.js

Noticed the state wasn't being set when someone clicked on the toggle.
But was when you were refreshed, turns out you need to send a new object to the hook, which is probably the better way of doing it.
Also added a domain setting as doing it in Chrome was annoying, but put it behind a button.

Toggles fix

---

common/styles/components/_image_viewer.scss

Should keep some of the noise in the explosions channel down a bit.

Ignore touch events on ImageViewer controls

---

cardigan/stories/components/EventDateRange.js
common/views/components/CompactCard/CompactCard.js
common/views/components/EventCard/EventCard.js

Ref #4101 
Probably need to revisit the structure of the compact card.
It would be nice to codify this idea of the card & header being relatively the same.
Some linting happened too.

show all dates/times on event compact card

---

catalogue/webapp/components/WorkDetails/WorkDetailsNewDataGrouping.js

As per our discussion, just because something is in the header, doesn't mean it needs to be removed from the details.
The point of the head is to give an overview, and allow quick scanning of what might be important to a specific type of thing, the details below can replicate this.
This will avoid having inconsistent details across the different works if the decision is to have different overview structure.
e.g. we might pull contributors out as really important on books, but not ephemera.
[Ordering taken from here](https://github.com/wellcometrust/wellcomecollection.org/issues/3954#issuecomment-456986989)

add contributors back to work details

---

common/data/the-pharmacy-of-colour.js

We need to remember that not all browsers are equal when coming to dates, especially Safari.
This is why we use moment.
Having a strategy for this, and applying it universally would be nice.
Fixes this 👇

use moment to create dates on pharamacy of colour

---

catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/pages/work.js
catalogue/webapp/pages/works.js
common/views/components/WorkHeader/WorkHeader.js
dash/webapp/pages/toggles.js

Adding the work locations toggle to the header.
The discussion we had was that the header and the new metadata ordering is good to go.
One piece that potentially needs work is the work's locations #4043.
Instead of holding this up any more, we can release the header and metadata by removing the current `WorkPagesChanges` toggle.

add new work locations toggle

---

catalogue/webapp/pages/works.js
common/views/components/Header/Header.js

If someone opts in to showCatalogueSearchFilters they can search more than just images. 
To avoid confusion we want to change the navigation link from Images to Collections and the text above the search box from 'Search our images' to 'Search our collections'.

Images becomes Collections

---

common/services/prismic/exhibitions.js
content/webapp/components/Installation/Installation.js

Alternative for #4120 
To be clear, the reason for not having to async calls for non-integral information on a page is latency. It's one of the least performant things, so even when calling to the same service, we double the latency, which feels like bloat that we can avoid with the common pattern of loading other content in asynchronously.

add partof to exhibitions

---

common/styles/components/_image_viewer.scss
common/views/components/WorkMedia/WorkMedia.js

We currently have a 'scroll to' control button on work pages (mobile view). However, it doesn't work well now we have the header on works.
Rather than apply a fix, this PR removes the control, as we're likely to be exploring in-page navigation that will supersede it and it's rarely used:
Before:
After:

Remove scroll to

---

dash/webapp/pages/toggles.js

Currently it's using dash.wc.org.
That means the cookies can't be read from wc.org.

set domain to root when setting cookies on toggler

---

common/styles/components/_image_gallery_v2.scss

The pseudo element we use to create the hover effect on the first item of an inline gallery, is preventing the correct context menu from showing if the user right clicks above any image in the gallery.
No 'Save Image as...', 'Copy Image' etc.

Don’t display :before pseudo element when gallery is active

---

common/styles/components/_image_viewer.scss

A bit of a punt to reduce the noise we're getting in Sentry along the lines of `Cannot read property 'minus' of undefined`. The problem is with Openseadragon, and seems to have to do with touch events.
Preventing touch actions on the element that contains the controls for the viewer didn't prevent the errors, so this PR adds them to the `Control` elements within that area as well. This seems to be the approach taken on the example at the top of the [Openseadragon homepage](https://openseadragon.github.io/).

Prevent touch-actions on a and button elements in Openseadragon viewer

---

common/styles/components/_image_gallery_v2.scss
common/styles/utilities/_root-scope-classes.scss
common/views/components/Buttons/Button/Button.js
common/views/components/Buttons/Control/Control.js
common/views/components/ImageGallery/ImageGallery.js

Screenreader users should be alerted to the fact that the gallery will expand when they click the open-gallery button, and that it is expanded when they do. Focus should be moved to the close button once the open button is clicked.
__TODO__

Gallery close a11y

---

catalogue/webapp/components/WorkCompactCard.js/WorkCompactCard.js

Fixed in #4133 
But waiting for that might take too long.
Removes the `Date` label from the work compact card if there are no production dates.

don't show date label when there are no dates on work card

---

.circleci/config.yml
build/Dockerfile_webapp
catalogue/webapp/Dockerfile
content/webapp/Dockerfile
package.json

Builds successfully and runs locally without any apparent issues on `10.15.1`. Not keen to deploy until @jamesgorrie has been over it, though.

Bump NodeJS versions to 10.15.1 lts

---

cardigan/stories/components/SectionHeader.js
common/views/components/CardGrid/CardGrid.js
common/views/components/EventsByMonth/EventsByMonth.js
common/views/components/ExhibitionsAndEvents/ExhibitionsAndEvents.js
common/views/components/LayoutPaginatedResults/LayoutPaginatedResults.js
common/views/components/SectionHeader/README.md
common/views/components/SectionHeader/SectionHeader.js
content/webapp/pages/homepage.js
content/webapp/pages/stories.js
content/webapp/pages/whats-on.js

Move `MoreLink`s out of `SectionHeader`s to be below the block of promos that follows.
Rationalising more of our inter-/intra-component spacing in the process.

More link position

---

catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/components/WorkCompactCard.js/WorkCompactCard.js
catalogue/webapp/pages/works.js
common/views/components/LinkLabels/LinkLabels.js

Adds a message to the search to say we're in beta.
---
When looking around at other `beta`s, there are quite a few that aren't opt in, they just have clear messaging to let people know things are in testing. Similar to [how gov.uk use beta](https://www.gov.uk/help/beta), and other services just label them as such (Github for example).
[e.g.](http://beta.charitycommission.gov.uk/charity-details/?regid=210183&subid=0)
In our case, if the person doesn't want to use the extra filters, they don't have to, and leaving the `Images` and `Online` filters checked (default) allows it to stay as it currently is. 
[I have created a not-for-release version of a feedback survey in Survey monkey](https://www.surveymonkey.co.uk/r/W3NBWV2). [Seems a pretty common pattern to just link off to another …

add feedback message to search

---

catalogue/webapp/pages/works.js
dash/webapp/pages/toggles.js

As we can work on this in parallel and release it without blocking the work going on in getting the works search out, a switch has been added for this.
This means we could A/B it too.

add imagelesssearchresult toggl

---

common/model/exhibitions.js
common/services/prismic/exhibitions.js
content/webapp/components/Installation/Installation.js
prismic-model/js/exhibitions.js
prismic-model/js/parts/single-line-text.js
prismic-model/json/exhibitions.json

Fixes #1716
We've decided this piece of metadata is predominantly, if not exclusively, for display purposes.
The title of the exhibitions works similar to a `Work` where is has _a_ title.

add shortTitle to exhibitions

---

common/views/components/TextInput/TextInput.js

__Before__
__After__
I suppose this could mean we over-pad the right end of the input if we use  the `StyledInput` component without the close cross, but I figure that shouldn't be a serious issue

Add enough padding for close cross

---

common/model/opening-hours.js
common/model/organization.js
common/utils/json-ld.js
common/views/components/FindUs/FindUs.js
common/views/pages/_app.js
common/views/pages/_document.js

No idea how we missed this off.
The two tests we had on for this were incredibly brittle (using Yandex didn't always work, and the Google API rate limits you).
Might be worth sticking in some structural page analysis.
The warnings below are about adding performers and offers.

put museum and library LD on the pages

---

catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/pages/works.js

Ref #4134
TL;DR
* ✨ Clears up confusion around filter function
* 🐛 Makes sure we're not searching the whole catalogue as noticed by @hthair 
From the exploratory work done on #4181 and working with @GarethOrmerod, there were a couple of things that were confusing the matter:
* Are the filters tied to the results or search term? In this case it seems to be the search term as the `workType`s are not tied to any aggregation data on the results themselves and can be applied Google example in #4181). 
* Are these link style filters, or checkboxes, i.e. do you apply them pre-search, or post-search. As per discussion with @Heesoomoon, they are to act like links and affect the results immediately.
All in all feels quite nice, I'm sure some things will come out in the wash during testing.
For the …

remove checkboxes from filters to be explicit about how they work

---

catalogue/webapp/components/SearchForm/SearchForm.js
common/styles/base/_icons.scss
common/views/components/SelectableTags/README.md
common/views/components/SelectableTags/SelectableTags.js

To allow users to know they can, and also to not be so linky, but more selectable (similar to a segmented control).
As our design system is growing and becoming more robust, it felt good practise to follow this lifecycle, especially for testing (hence the copy/paste from `Tags`, although the follow the purpose of taking you to a new search).

Make work types more obviously (de)selectable

---

catalogue/webapp/app.js
catalogue/webapp/package.json
catalogue/webapp/pages/item.js
catalogue/webapp/pages/work.js
common/services/catalogue/urls.js
common/utils/works.js

Ref: #4147
Adds a link to, for example, `/works/fwquzvcf/items` which will then render the `DigitalLocation` of the first item.
Not all items have IDs due to the fact that the ID is based on Sierra's Item ID, and we only have this for items with `PhysicalLocation`s.

add item page

---

catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/pages/works.js

Fixes #4198 
* Add E-Books under books filter
* ~Add non-digitised works (remove filter to return only items with `iiif-presentation` or `iiif-image` item locations)~ we are only returning digitised content.

add e-books and don't filter out non-digitised works

---

common/views/components/Images/Images.js

Fixes #4055 
SEO crawlers/humans without JavaScript.
Letting them read captions for images.

Show captions on captioned images when there's no JS

---

catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/components/WorkCard/WorkCard.js
catalogue/webapp/pages/work.js
catalogue/webapp/pages/works.js
common/services/catalogue/urls.js

Hopefully simplified the logic of how we construct and use the query parameters down the way.
`QS` = `QueryString`
This allows us to group filters by Books / Visual.
* If there is no `QS`, filter is set to `null`
* If this is set to `null`, we send a default array to the API dependant on the toggle, but the interface still gets `null`
This means we can still send and read a `QS` like `['k', 'v']` that doesn't get picked up further down the line  as default, and removes it, making it really hard for the interface to respond to the `QS`, i.e. the `SelectableTags`.

make search query logic simpler by making parameters nullable

---

catalogue/webapp/pages/item.js
common/views/components/RenderlessPaginator/RenderlessPaginator.js

Making the pagination a bit more reusable(/customisable) and giving the individual item pages some very basic styling.
__TODO:__

Add RenderlessPaginator

---

catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/pages/works.js
common/model/text-links.js
common/views/components/TabNav/README.md
common/views/components/TabNav/TabNav.js
dash/webapp/pages/toggles.js

Creates two types of Tabbed nav for the work type filters.
One associated with the search bar (as discussed) and another with results as it's something that feels worth mucking around with.
The filters are Books (Books & E-Books) and Visuals (Images & Pictures).

Work type filters as a segmented control

---

catalogue/webapp/pages/item.js
catalogue/webapp/pages/work.js
common/model/iiif.js
common/services/catalogue/urls.js
common/views/components/RenderlessPaginator/RenderlessPaginator.js

Ref #4147 
Thinking we could restructure the URLs, more specifically the query string, to be:
`/works/{id}/items?sierraId={sierraId}&page={3}&canvas=12`.
Assuming `pageSize` is `5`, and we _aren't_ `zeroIndexing` here, we could then show canvases `11` - `15`, with `12` in the main focus.
__Next up__ Layout

add thumbnails for navigation to item page (no JS)

---

dash/webapp/pages/toggles.js

Moved the ones relevant to the process of opening up books to the public to the top.

reorder and fix typos on toggles

---

common/views/components/BetaBar/BetaBar.js

Anything wrapped in `styled` needs to have a template string after it, or it doesn't return a component.

don't wrap betabar with style

---

catalogue/webapp/pages/works.js
common/views/components/Paginator/Paginator.js

As discussed with @Heesoomoon, this seems clearer, and be more based on the segmenting of the page into Beta, Search, Filter, Nav, Results.

move results count to pagination

---

catalogue/webapp/pages/work.js

Some works have 2 sierra records, these are works that have been merged.
https://api.wellcomecollection.org/catalogue/v2/works/v6zxz262?include=items,identifiers
The manifest is only related to one of those IDs, so we make sure we pull it from the actual manifest URL.
Interestingly, the manifest B number doesn't have a corresponding library record. e.g. 
__exists:__ https://search.wellcomelibrary.org/iii/encore/record/C__Rb1298367?lang=eng
__doesn't exist:__ https://search.wellcomelibrary.org/iii/encore/record/C__Rb22021814?lang=eng
It might be worth getting to the bottom of this.

use b number from manifest file for viewing items

---

catalogue/webapp/pages/work.js
common/utils/works.js
common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js

Not sure how this past the build, I'd like to look into it.
For now I guess we think about how we name IIIF things as we have a mixture of caps and small, the pattern seeming like if it's:
* `camelCase` and starts with `IIIF`, we leave it small e.g. `iiifImageThings`
* `camelCase` and has it in between it's large e.g. `thingsThatHaveIIIFInIt`
* `PascalCase` and starts = large `IIIFImageLocation`
* `PascalCase` and in between = large `ThingsIIIFImageLocation`
Either way, we had `type`s and `const`s named the same, which should never really be the case.

get the naming right on iiifPresentationLocation

---

common/services/prismic/articles.js
common/services/prismic/events.js
common/services/prismic/parsers.js

Event parsing on the outro doesn't work as we don't always get linked docs etc.
This hopefully deals with that, but adds really rubbish null checking in our parsers.
It'd be nice to move to GraphQL completely...

be hyper conservative with event parsing

---

catalogue/webapp/components/SearchContext/SearchContext.js
catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/pages/work.js
catalogue/webapp/pages/works-context.js
catalogue/webapp/pages/works.js

In a bid to simplify the search routing, we're using a combo of state hooks and next's router.
This will maintain the state of the search in a context that is provided at the root of the application.
[You can read more about it here](https://github.com/wellcometrust/wellcomecollection.org/pull/4196).
__Next:__ add query type

Use search context

---

dash/webapp/pages/index.js

Annoyed that I have to keep looking them up.
This adds the updown / uptmie robot stats to the dash index.

add updown / uptimerobot to dash index

---

catalogue/webapp/components/SearchContext/SearchContext.js

This allows us to use `null` values where `null` values are valid.
e.g. 
```JS
let state = {};
const defaultState = { workType: ['k', 'q'] };
const initialState = { workType: null };
state = { workType: initialState.workType || defaultState.workType};
// state = { workType: ['k', 'q'] } <= wrong!
state = { ...defaultState, ...initialState };
// state = { workType: null } <= right!
const newInitialState = { otherProp: 'value' };
state = { ..defaultState, ...newInitialState };
// state = { workType: ['k', 'q'], otherProp: 'value' } <= right!
```

spread initialState over defaultState to allow for null values

---

catalogue/webapp/pages/item.js

A `display: flex` container around an image with `width: auto; height: auto; max-width: 100%; max-width: 100%` causes Safari to get confused on resize. Making it `display: block` and doing the centering with `translateY()` instead solves the problem.

Center images without flex-box (fixes Safari bug)

---

common/views/components/EventbriteButton/EventbriteButton.js
eventbrite/webapp/app.js

Saw that `/eventbrite/widget` are being tracking in GA.
This is because we still reference these in iframes on event pages and event schedules.

remove unused consts

---

catalogue/webapp/pages/item.js
common/views/components/BetaBar/BetaBar.js
common/views/components/TabNav/TabNav.js

Use `attrs(props => ({}))` syntax for styled components as per deprecation notice.

Use new syntax for styled component attrs

---

catalogue/webapp/pages/item.js

Fixes the broken thumbs being used as the main image in the main preview.
Tl;DR; some image max bounding size is actually 1000x1000.
This is something that has just been lingering as it hasn't caused problems before.
The longer explanation can be found on slack.
This uses the `max` size in the IIIF Image API, which, on the thumbs service, can be `1000`, but will select `1024` if available.
As a point it's the `1000` images that are in the minority (6%).

use max in main image in item viewer

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

As there are many other uses, we are removing the share heading from the link copy component.

remove share heading

---

catalogue/webapp/pages/item.js

Prevent navigation changes while paging through a book from being recorded in the history.
The back button will thus just take you back to the work page.

use history.replace on item pagination

---

common/utils/works.js

when we're creating the download options from the iiif Presentation Manifest using sequence.rendering we sometimes get an object and sometimes an array of objects. We always wan't to return an array

always return a flat array

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

references  #4290
repository information from the iiif presentation manifest can contain images, we don't want to display them

remove images and whitespace from repository value

---

catalogue/webapp/pages/item.js
common/model/iiif.js
common/utils/works.js
common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js

Work type v, i.e. E-books can include multi volume works, which is causing errors on the work and item pages because the iiif manifest doesn't have any sequences, but links to other manifests.
There are also works which have sequences for non iiif content, such as PDFs
We need to work out what to do with these but in the meantime, this prevents the work page from breaking and suppresses the link to the viewer under those circumstances.

don’t always have sequences and some aren’t valid

---

catalogue/webapp/components/SearchContext/SearchContext.js
catalogue/webapp/pages/works.js
common/views/components/TabNav/TabNav.js

When you use a context, you need to remember to update things as you have an initialState that you need to make sure you update for effects to be used elsewhere.
I don't think this is the solution to it, and would like to maybe tie the router to the context so that you don't need to remember to do this every time.

maintain worktype state

---

common/views/components/TabNav/TabNav.js

Fixes #4312
We have a line that stops the need for double-tapping links on iOS using [this technique](https://css-tricks.com/annoying-mobile-double-tap-link-issue/), but the style was also preventing filter highlight on ~iOS~ touchscreen devices.
This PR splits the relevant style pieces out so the yellow highlight can still be visible without affecting the double-tap stuff.

Fix TabNav highlight for iOS

---

catalogue/webapp/pages/item.js

Appends the sierraId onto the canonical url for the items of a work.

add sierraId to canonical href of items

---

common/model/iiif.js
common/utils/works.js

If we have a work, that only has a iiif presentation manifest wrapping a pdf, there is currently no way for a user to get hold of the pdf.
This uses gets the url of the pdf, from the manifest mediaSequences, and adds it to the download options.

get pdf url from mediaSequences if it’s available

---

cache/cloudfront_dev.tf
cache/cloudfront_prod.tf
cache/terraform.tf

We had too many query parameters, so we now have a new ✨ cache behaviour.
This is probably better in the long run as it feels like we'll have different requirements for `/works` anyway.

create new cache behaviour for /works

---

catalogue/webapp/pages/item.js
common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js

Makes the logic more explicit as to what we want to render.
This way we don't land up rendering the link when we know there aren't any images from the manifest.
As, without JS, we can't tell if we'll be able to render the item, we just show the button.
@wellcometrust/experience-devs do we think this is a decent strategy for non-js loading (the `loaded`) or would something more generic make sense? I can't think of what that is though.
There's a few fixes where we are being a bit loose with out array checking, we should think about how not to let these slip in, probably with typing.

show button only if we haven't managed to load the page with JS

---

common/views/components/IIIFResponsiveImage/IIIFResponsiveImage.js

@Heesoomoon noticed we were getting a few errors on images from DLCS.
They seem to be `503`s, and non-replicable. 
I have asked DLCS if they could give us further insight into this, and have now added sentry tracking.
It might be worth looking at sentry as a point to get it into a usable state again.

add error handling to IIIF images

---

common/styles/base/_icons.scss
common/views/components/Icon/Icon.js

Fixes #4314
The `canvas` element as a shim for icon sizing was useful when we didn't know the icons' aspect ratios. Now all of our icons are square, it is redundant.
Setting both icon dimensions was the most straightforward, but it alerted me to the fact that the `viewbox` for some of our icons is `0 0 24 24` (24x24) and some `0 0 26 26` (26x26).
We're still displaying them all at 26x26, but I think @GarethOrmerod did work to update them to be sized by a number that works with our base sizing unit (6px).
This probably leads to aliasing of the 24x24 icons meaning that they won't render as sharp as they would if they were displayed at 24x24.
We should probably push to get all icons using a `0 0 24 24` viewbox and display them all at 24px.

Set both icon dimensions

---

common/views/components/FooterNav/FooterNav.js

Could(/should?) have a `NavigationItemsContext` that stores this in the one place in `common/_app.js`

Change 'Images' to 'Collections' in footer

---

catalogue/webapp/pages/item.js
common/utils/works.js
common/views/components/BetaMessage/BetaMessage.js
common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js

Fixes #4333 and adds tracking when we display the user a message saying we are unable to show the work online.
N.B. Wording of the message and styling might need work.
When we have javascript available we replace the link to the viewer with the message:
When we don't have javascript available we show the message on the viewer/item page:

Check a work is viewable

---

common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js

While trying to replicate #4347 (which I couldn't), noticed that there were unnecessary scroll bars on the preview in edge

remove scroll bars from preview

---

common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js

While trying to replicate the bug reported in #4347 (still can't), noticed the preview doesn't look good in browsers that don't support css grid.
This makes the preview look nicer in browsers that don't support css grid, by just showing a single image like we do on mobile

only show first preview image if browser doesn’t support css grid

---

docs/rfcs/001-url_parameters/README.md
docs/rfcs/001-url_parameters/url_parameters_strategy.md

Simpler RFC for how we deal with URL parameters in terms of privacy and clarity.
@jennpb are we agreed that we should not be sharing the query state in the URL? Or more broadly, if it's not related to the core content on the page and can be used to infer what someone is looking for, we should obfuscate it?
@wellcometrust/experience-devs do we feel this is enough guidance for now on how to act in the future?

add RFC for URL parameters

---

common/views/components/Tags/Tags.js

Fixes #4335
The medium and light helvetica neue can be slightly different heights depending on your system. Rather than setting a `min-height` for the tags, this adds two empty elements – one for each of the possible font weights – such that the taller of the two will be used for the tag height.

Make sure tags will be equal heights

---

common/styles/utilities/_root-scope-classes.scss
common/views/components/Breadcrumb/Breadcrumb.js
common/views/components/ErrorPage/ErrorPage.js
content/webapp/pages/opening-times.js
content/webapp/pages/page.js

Removes the `Home` breadcrumb and sets the height of the Breadcrumb component if there are no breadcrumbs to avoid jumpiness when navigating.
Request from @Heesoomoon 
## With

remove Home breadcrumb

---

client/terraform/terraform.tf
dash/terraform/terraform.tf
terraform-modules/https_s3_website/cloudfront.tf
terraform-modules/https_s3_website/variables.tf

[Noticed that our Page Insights score is actually very very sad](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwellcomecollection.org).
One thing was that the cache times aren't being set (although the cache is being hit quite well) for assets on `i.weco`. Those very very rarely have been changed, and we could probably be more conservative with the cache times.
This just gives us the option to start optimising.

update s3 website to have cache times and apply to dash.

---

catalogue/webapp/components/SearchForm/SearchForm.js

I noticed when you search from the `Work` page, when returning to the `ResultList` page, if you had a previous `SearchForm` mounted, it maintains the state from that.
By updating the `inputQuery` => `query` when query changes (from the Router), this fixes that problem.
Worth thinking about if this is all worth it, especially as we've now simplified the URL structure. We could just maintain the query state in sessionStorage or similar.
The benefit of this is that we get really fine grained control over the interface, how we would load things in etc, but we're not massively leveraging that. 
If we think it's worth removing, let's have a chat about it.

refresh inputQuery state when query changes

---

catalogue/webapp/components/SearchForm/SearchForm.js

Makes the selectable queries available on the landing page.

make selectable queries available upfront

---

content/webapp/pages/opening-times.js

Opening times is currently a template of its own (rather than using the `page` template), so we have to put any breadcrumbs in the template itself.
Now venue hours are in the shape they are, we _could_ make the opening times page use the `page` template with a bit of work…

Add visit us breadcrumb to opening times

---

catalogue/webapp/pages/item.js
catalogue/webapp/pages/work.js
catalogue/webapp/pages/works.js
common/views/components/SearchLogger/SearchLogger.js

* Uses a more standard segment implementation as the custom one was causing issues with how the page was tracked
* Actually sends the event name down the pipe (annoyingly segment doesn't error if you don't)
* Reduces the scope to search as that is the issue we're working on. If and when we move to more thorough journeys through the app, we can add those bits and pieces as and when.

use a more standard segment implementation and reduce scope to search

---

common/services/prismic/events.js

Until now the start and end date of an event had always occurred on the same day, this is not the case for 'Smoke and Mirrors Live Performances' (although we might look at using an event series for this).
The filter didn't account for events that spanned the time period or started in the time period, so this event wasn't showing, it does now.

Event missing from homepage

---

router/terraform/alb.tf
router/terraform/terraform.tf

Noticed `works` / `preview` / `etc` were being indexed.
This assumes that this ALB should only be used for the root wellcomecollection.org, and things that we don't want indexed, which feels fine.

make subdomains return a strict robots.txt

---

common/views/components/SearchLogger/SearchLogger.js

Sentry error because we're sometimes trying to apply trim method to undefined

check for string before applying .trim

---

content/webapp/components/Exhibition/Exhibition.js

Allows us to show custom status messages on the exhibition template, e.g. 'Now closed' for Medicine Man, rather than 'Past' which would be the default from inference about dates.

Show the date override on the exhibition template

---

cardigan/stories/components/MessageBar.js
catalogue/webapp/pages/work.js
catalogue/webapp/pages/works.js
catalogue/webapp/services/catalogue/works.js
common/views/components/BetaBar/BetaBar.js
common/views/components/MessageBar/MessageBar.js
common/views/components/MessageBar/README.md
toggles/webapp/toggles.js

Allows access to the stage API for internal testing for those who don't browse the internet in JSON.
Adds the idea of a `MessageBar` too.

add toggle to allow access to stage API

---

catalogue/webapp/pages/works.js

The filters where showing up on the landing page.
This stops that.

only show filters when there are results to filter

---

common/services/prismic/opening-times.js
common/views/components/VenueHours/VenueHours.js

At present we group exceptional opening hours days for display as a group if they fall within a week of each other. Additionally, we backfill opening hours for venues that don't have override days in these periods, so we can show all the opening times for that period for each venue.
This works fine until we just want to show an override date for a single venue and/or that override date is within a week of other override periods.
This PR includes override dates in the same period only if their overrideType matches and only backfills dates if the override type is not 'other'.
Before:
After:

Don't group all exceptional opening hours

---

cardigan/stories/components/InfoBanner.js
catalogue/webapp/pages/work.js
catalogue/webapp/pages/works.js
common/views/components/InfoBanner/InfoBanner.js

Updating `InfoBanner` text to be in Prismic HTML shape. Fixing Sentry errors we're getting from WellcomeImages redirects.

Put InfoBanner text in correct shape

---

catalogue/webapp/pages/item.js

We currently run a `try/catch` block under a condition we know would be guaranteed to fail, and getting a lot of Sentry errors as a result.

Only try/catch when we know there's a textService

---

catalogue/webapp/pages/item.js

We might feasibly see `unexpected token > in JSON at…` errors from things other than IIIF services.
This makes the error message more specific and tags it with `dlcs` when we know that's the culprit.

Make error more specific/useful

---

common/views/components/ImageViewer/ImageViewer.js
common/views/components/ImageViewer/ImageViewerImage.js

Relates to #4442
Adding a rotate (90º clockwise) control to the `IIIFImageViewer`.

Add rotate control to IIIFImageViewer

---

common/styles/components/_image_viewer.scss
common/styles/components/_work_media.scss
common/views/components/IIIFViewer/IIIFViewer.js
common/views/components/ImageViewer/ImageViewer.js
common/views/components/ImageViewer/ImageViewerImage.js

Launching the OpenSeadragon image viewer immediately without the user having to click on the image or the zoom button.
There's some  get-'er-done styling for the `IIIFViewer`, but these components are on the verge of changing fairly dramatically with the new viewer designs, so I didn't want to be too precious about it.

Constrain and immediately launch OpenSeadragon viewer

---

common/views/components/ImageViewer/ImageViewerImage.js

Reusing the current viewer circumvents the JS errors we're getting with `destroy()`.

Reuse OSD viewer

---

catalogue/webapp/components/WorkCard/WorkCard.js
common/views/components/WorkHeader/WorkHeader.js

Closes #4452, closes #4280
Only display the first contributor in work search result lists and work headers. Display all contributors in the main body of the work page.
__Search result__
__Work page__

Display first contributor label in header/search results

---

cache/edge_lambdas/wiRedirector.js

Turns out it does, or doesn't, have a `.exe` - so we can just match both.

don't require .exe on wellcomeimages URLs

---

catalogue/webapp/components/WorkCard/WorkCard.js
common/views/components/IIIFResponsiveImage/IIIFResponsiveImage.js
common/views/components/IIIFViewer/IIIFViewer.js
common/views/components/ImageViewer/ImageViewer.js

Relates to #4459
We're currently loading all `/works` thumbnails at `300px` (often up to ~10MB per page of results 😦).
This PR adds lazy-loading for those images. It also makes them responsive, although because we limit image size by height and the `src-set`/`sizes` responsive `img` API expects a `w` (width) attribute, there's not a great way to do it.
I've reduced the width of the thumbnail to `178px` (which is the _height_ we're currently limiting to) since more often than not it doesn't come close to being `300px` wide (as the majority of images are portrait).
Seems to have been a problem since early March:
It also seems that shortly after that, we [stopped getting data from speedtracker](http://ghp.wellcomecollection.org/speedtracker/works/?period=month)
Have opened #4469 to look into …

Use responsive lazyloaded image for works thumbnails

---

catalogue/webapp/components/WorkCard/WorkCard.js

If there isn't a thumbnail image for a work search result, we don't need to show the element which would hold the thumbnail (and which has a height).

Don't show space for image if there isn't an image

---

cache/edge_lambdas/toggler.js
common/views/components/ExhibitionPromo/ExhibitionPromo.js
dash/webapp/pages/toggles.js

The test is over.
Short titles performed significantly better on the homepage, but not on the 'what's on' page.
Because we don't understand the result, we're going to stick with what we have.
I think we should think/specify more about what we're going to do in the event of various outcomes to these tests – seems like this one could be seen as a bit of a waste of time?
I promise this thought was less passive-aggressive than it sounds.

Remove short title toggle

---

common/styles/components/_divider.scss

Using `repeating-linear-gradient` function instead of a background repeating base64-encoded svg works in all browsers.
And because it's CSS we could do this:
Sorry.

Fix divider in IE

---

common/styles/base/_icons.scss
common/views/components/CopyUrl/CopyUrl.js

Fixes #4216 
Sizing the icon relative to the button's text height, rather than the default (24px) prevents the button from growing once the icon is displayed.

Match icon to text size to prevent page jump

---

catalogue/webapp/pages/item.js

This reverts commit de912e87301a4cf57a7a78b9a86699ebe2eaff5e.
> is `mainImageService` a necessary check anymore? Doesn't look like we use it inside this conditional.
Turns out it is

Revert "remove unnecessary conditional"

---

catalogue/webapp/components/Download/Download.js
catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/pages/work.js
common/views/components/IIIFImagePreview/IIIFImagePreview.js
common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
common/views/themes/default.js

References: #4492
Implements new work preview designs (includes making page background white and restyling download):

Work preview

---

prismic-model/js/parts/body.js
prismic-model/json/books.json
prismic-model/json/event-series.json
prismic-model/json/events.json
prismic-model/json/exhibitions.json
prismic-model/json/pages.json
prismic-model/json/places.json
prismic-model/json/series.json
prismic-model/json/webcomics.json

[The `SearchResults` can  handle](https://github.com/wellcometrust/wellcomecollection.org/blob/master/common/views/components/SearchResults/SearchResults.js#L124exhibitions), so we should allow them to be added.

add exhibitions to content list

---

cache/cloudfront_dev.tf
cache/cloudfront_prod.tf

In favour of https://github.com/wellcometrust/wellcomeimages which can redirect people to the actual source.

remove wellcomeimages.org cnames from cache

---

common/styles/utilities/_root-scope-classes.scss
common/views/components/EventPromo/EventPromo.js
common/views/components/ExhibitionPromo/ExhibitionPromo.js
common/views/components/StoryPromo/StoryPromo.js

Fixes #4366 
A flexbox bug in IE is causing a couple of issues:
1. The physical height of the `srcset` image is being used to calculate the amount of space taken up at the top of the card (rather than the image's height once it has been resized to 100% of the width of the card).
2. The card height isn't growing to accommodate its contents (we had set a `min-height`, but it often isn't large enough).
This PR adds a `flex-ie-block` class that will display `flex` for browsers that understand `@supports` (evergreens) and block for those that don't (basically, IE).
__Before:__
__After:__
A side-effect of this is the first (featured) card on the `/stories` page now lays out vertically in IE, rather than horizontally. This feels like the lesser of two evils.
We _could_ write some more specific …

Display block cards in IE to fix flex layout issues

---

catalogue/webapp/pages/work.js

Don’t show wobbly line if no preview available

---

common/services/prismic/exhibitions.js
docs/rfcs/002-public-feedback-on-search-relevancy/README.md

It would be so nice to consolidate how we interact with Prismic... Maybe GraphQL!?
Makes it possible to put event series in the content list of exhibitions.

add fetchLinks for event series on exhibitions

---

cache/edge_lambdas/toggler.js
catalogue/webapp/pages/works.js

Switch the _queryType param when someone is in the test.
Make things camelCase. I do wonder how you destructure data from elsewhere, which might be underscored, if you have this rule set?

toggle queryType on a/b

---

common/views/components/ImageViewer/ImageViewer.js

This ensures as much of the zoomed image as possible is maintained within the viewport (it was set at this before we made OpenSeadragon programmatic).

Keep visibilityRatio at 1

---

common/views/components/GifVideo/GifVideo.js

The `canplaythrough` and `canplay` events don't fire in Safari unless you're in the user's whitelist.
`loadedmetadata` is the last event that fires consistently.
This change makes `GifVideo` work in Safari.
https://stackoverflow.com/a/50102809

Use loadedmetadata to decide when to play video

---

common/views/components/GifVideo/GifVideo.js

Polling the `video.readyState` doens't work in Safari (it never gets above `0`).
Using the `loadedmetadata` event seems to be the most consistent cross-browser thing (that works).

Use loadedmetadata event

---

common/views/components/IIIFViewer/IIIFViewer.js

Making the viewer thumbnails bigger and spacing them out a bit, to make them easier to scan.

Amend thumbnail size/space

---

catalogue/webapp/pages/work.js
common/services/catalogue/urls.js
common/views/components/IIIFViewer/IIIFViewer.js

Going to the viewer from the preview page sets a flag to make the viewer display the overview thumbs.
Arriving from anywhere else/refreshing the page will display the detail view instead.
__TODO__

Add isOverview to query for initial thumbs view

---

cache/edge_lambdas/toggler.js
common/views/components/IIIFViewer/IIIFViewer.js
common/views/components/ImageViewer/ImageViewer.js
toggles/webapp/toggles.js

~If we want to test this, we can come up with a question and promote the toggle to an A/B test.~
This splits traffic 50:50 into a condition with all controls top right, and a condition with the zoom/rotate top right and pagination bottom left.

Add toggle for moving image controls closer to pagination controls

---

common/views/components/ImageViewer/ImageViewer.js

Fixes #4552 
We need to check that we haven't already kicked off initialising the OSD viewer before doing so again clicking on the zoom/rotate controls.

Guard against loading multiple viewers

---

cache/terraform.tf

Allows us to deploy lambda@edge to devcache.

Use an appropriate role for cache terraform

---

cardigan/stories/components/Contact.js
common/services/prismic/fetch-links.js
common/services/prismic/pages.js
common/services/prismic/parsers.js
common/views/components/Body/Body.js
common/views/components/Contact/Contact.js
common/views/components/Contact/README.md
prismic-model/convert.js
prismic-model/js/parts/body.js
prismic-model/js/teams.js
prismic-model/json/pages.json
prismic-model/json/teams.json

Relates to #4355 
Adding a `Contact` component which allows a team name, email and/or phone number to be displayed.
Adds a `subtitle` field to the current `Team` (and we've changed the Prismic UI to display `Contact` instead of `Team`, to make the editorial flow make more sense).
~@jennpb Is the ability to add individuals a requirement? If so, I think this will require rethinking. Sticking with teams feels like it should be more future proof (even if individuals move roles, the teams remain the same), but not sure if it fits the needs.~

Contact card

---

dash/webapp/pages/toggles.js

Displaying `groupImageControlsWithPagination` on the [toggles/AB dash](https://dash.wellcomecollection.org/toggles/).

Add groupImageControlsWithPagination to dash

---

common/views/components/IIIFViewer/IIIFViewer.js

prevents error that was leading to footer being rendered twice

noscript inside noscript causing issues

---

catalogue/webapp/components/Download/ViewerDownload.js
common/views/components/IIIFViewer/IIIFViewer.js

Since the work to fix the header, the stacking of elements means the download options are never visible. This fixes that.

prevent downloads from being hidden

---

common/services/prismic/multi-content.js
prismic-model/json/books.json
prismic-model/json/event-series.json
prismic-model/json/events.json
prismic-model/json/exhibitions.json
prismic-model/json/places.json
prismic-model/json/series.json
prismic-model/json/webcomics.json

`AsyncSearchResults` needs to be able to parse everything that it receives – `teams` (contact) fields were missing.

Add team fields to async search

---

catalogue/webapp/app.js
catalogue/webapp/components/Download/Download.js
catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/pages/download.js
catalogue/webapp/pages/work.js
common/services/catalogue/urls.js
common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
common/views/components/WobblyRow/WobblyRow.js

The download and license information for works that have a iiif-presentation manifest location, is contained within the iiif-manifest and not in the catalogue API response.  In order to avoid waiting for 2 successive API calls before rendering a work page, we get this information client side. 
This is fine except in situations where javascript doesn't run in the client.
This PR adds a link to a download page for the work, in non js scenarios, so at least the information is available.

Non js work

---

cache/edge_lambdas/toggler.js

We need more traffic to the different query types for more confidence.
We have a hunch the `msmboost` is winning the race, and a good place to start - but we thought we could send `25%` of traffic to all queries (msm, boost, msmboost and default) just to be sure.

boost the amount we're sending to test queries

---

cardigan/stories/components/PageHeader.js
catalogue/webapp/components/StaticWorksContent/StaticWorksContent.js
catalogue/webapp/components/WorkCard/WorkCard.js
catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/pages/download.js
common/styles/components/_footer.scss
common/styles/utilities/_variables.scss
common/views/components/Caption/Caption.js
common/views/components/CompactCard/CompactCard.js
common/views/components/EventScheduleItem/EventScheduleItem.js
common/views/components/Footer/Footer.js
common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
common/views/components/IIIFViewer/IIIFViewer.js
common/views/components/ImageViewer/ImageViewer.js
common/views/components/Label/Label.js
common/views/components/LayoutPaginatedResults/LayoutPaginatedResults.js
common/views/components/MetaUnit/MetaUnit.js

Removing all remaining occurrences of `margin-top`, `margin-bottom`, `padding-top`, and `padding-bottom` utility classes from the styles and within the markup – vertical spacing is now controlled by `SpacingComponent`, `SpacingSection`, and `VerticalSpace` components.

Vert spacing tidy

---

catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/pages/work.js
common/hooks/useOnScreen.js
common/styles/works.scss
common/views/components/HeaderBackground/HeaderBackground.js
common/views/components/IIIFImagePreview/IIIFImagePreview.js
common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
common/views/components/Label/Label.js
common/views/components/Number/Number.js
common/views/components/PartNumberIndicator/PartNumberIndicator.js
common/views/components/WobblyRow/WobblyRow.js
common/views/components/WorkHeader/WorkHeader.js

references #4483
Removes the multi volume preview from behind a toggle and updates it based on Gareth's design.
Updates other previews to match.

Multi volume preview

---

catalogue/webapp/components/WorkCard/WorkCard.js
common/views/components/IIIFImagePreview/IIIFImagePreview.js
content/webapp/pages/event.js

I noticed the cursor wasn't a pointer when `<NextLink />`s contained a `<VerticalSpace />` as the first child (so links wouldn't work with JS off). This sorts it. (instead of #4617). Fixes #4616.
[See here for explanation](https://github.com/zeit/next.js/#forcing-the-link-to-expose-href-to-its-child)

Make sure spacing component has href passed when it's an a tag

---

content/webapp/pages/visit-us.js

The opening times on `/visit-us` are too big (after the repo-wide typography reshuffle). This sorts it.

Fix type size on visit us

---

common/services/prismic/parsers.js

[SoundCloud have changed something to do with `secret_token`s](https://community.soundcloud.com/share-embed-230064/playlist-secret-token-not-authenticating-playlist-tracks-getting-404-error-7429924) (which we previously relied on).
This probably means SoundCloud embeds won't be working anywhere.
This fix does a null check on the `secret_token` so pages won't 404, but we'll still need to get SoundCloud embeds working again.

Check for existence of secret token from SoundCloud

---

catalogue/webapp/pages/works.js

Improving the no-results messaging to account for work types and date ranges.

No results messaging

---

catalogue/webapp/components/SearchForm/SearchForm.js
common/views/components/TabNav/TabNav.js

- Add `month-day` to link so Safari can handle client side routing by date
- Wait for the search form to have been submitted with the term 'darwin' before showing the aggregate links
- Keep the `TabNav` with the yellow underline for 'All', 'Books', and 'Pictures' links.

Aggregate date bugfixes

---

catalogue/webapp/pages/works.js

Currently we don't fetch works if the query is null or an empty string, but it's not unreasonable to expect people might want to refine the entire collection by date (regardless of whether a search term is included).

Empty query with dates

---

catalogue/webapp/components/WorkCard/WorkCard.js
catalogue/webapp/pages/item.js
common/views/components/IIIFViewer/IIIFViewer.js
common/views/components/MessageBar/MessageBar.js
common/views/components/RelevanceRater/RelevanceRater.js
common/views/components/TabNav/TabNav.js
common/views/components/Tags/Tags.js
common/views/components/TextInput/TextInput.js
common/views/components/VenueHours/VenueHours.js
common/views/components/styled/Space.js

When we use the `Space` component as-is, we get typing. Unfortunately, if we wrap the `Space` component in a different `styled` component (e.g `const Thingy = styled(Space)...`), the typing from `Space` doesn't come along for free – we have to type the wrapped components in the same way.

Flow Space component

---

common/views/components/Tags/Tags.js

The check for the last item in the array of items that can be within a `Tag` has a bug after the spacing update. This fixes it.
__Before__
__After__

Fix check for last item in tag array

---

common/views/components/LayoutPaginatedResults/LayoutPaginatedResults.js
content/webapp/pages/articles.js
content/webapp/pages/books.js
content/webapp/pages/events.js
content/webapp/pages/exhibitions.js

Fixes #3572
Adds a 'View past events' link to the bottom of the `/events` page. In the (unlikely) event that there is more than a single page of current-and-upcoming events, this link will appear at the end of each page of results.

Add past events link to /events

---

catalogue/webapp/pages/item.js
catalogue/webapp/pages/works.js
common/utils/works.js
common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
common/views/components/WobblyRow/WobblyRow.js
toggles/webapp/toggles.js

references #4326
removes audio and video from behind toggle; allows audio and video to be played on item page instead of in the work  preview if there is no javascript

Audio and video in search

---

content/webapp/content/visit-us-content.js
content/webapp/pages/visit-us.js

We've currently got a hard-coded template for `visit-us`, so need to do this content change manually.

Use Contact component on visit-us template

---

common/model/contributors.js
common/services/prismic/parsers.js
common/utils/capitalise.js
common/utils/grammar.js
content/webapp/pages/article.js
content/webapp/pages/book.js
content/webapp/pages/event.js
prismic-model/js/editorial-contributor-roles.js
prismic-model/json/editorial-contributor-roles.json

References #4479
Adding what a contributor _does_ to their mention in the byline.
Added the concept of `describedBy` to contributor roles in Prismic, with these two for starters (if this is incorrect, it is content editable in Prismic, of course).
| role | describedBy |
|-----------|----------|
|Author | words |
|Photographer | images |

Add describedBy words to contributors in bylines

---

dash/webapp/pages/toggles.js

Removes the old candidate queries.
I didn't remove the queryType selector as we don't currently have another way to do this, although I would like to have a think about it before we do it again soon.

remove candidate queries

---

common/services/prismic/exhibitions.js
common/services/prismic/fetch-links.js
common/services/prismic/multi-content.js
common/services/prismic/parsers.js

☝️ 
I'm not sure how articles were ever working in content lists without _something_ `articles` related having been added to `fetchLinks`?

Allow for articles in content lists

---

catalogue/webapp/pages/works.js
common/services/catalogue/urls.js
common/views/components/CatalogueSearchContext/CatalogueSearchContext.js

Remove a bit of unnecessary complexity, which was a bit confusing (at least for me)
We were passing several props to Works via WorksSearchProvider, which weren't being used as they were coming from the CatalogueSearchContext anyway

Tidy works

---

common/services/prismic/exhibitions.js
common/services/prismic/fetch-links.js
common/services/prismic/parsers.js

Content team
Letting them add `event` items to a content list slice

Allow events in content list

---

common/views/pages/_app.js
toggles/webapp/toggles.js

Experience team initially. Maybe everyone who longs for legible text on the site, ultimately.
Giving them the option to swap out Helvetica light for regular via the toggles dash.

Helvetica regular

---

catalogue/webapp/pages/works.js

I accidentally removed the existing works filter when adding the filters for the prototypes.
This PR re-adds them, only if you don't have either of the prototype toggles selected.

Reinstate work filter on works

---

cardigan/config/colors.js
common/styles/base/_typography.scss
common/styles/utilities/compiled_variables/_colors.scss

☝️ 
@GarethOrmerod suggested this change for improved readability after reading about [Material Design dark theme contrast and legibility](https://material.io/design/color/dark-theme.html#properties)

Update 'black' per Google Material Design guidelines recommendation

---

common/utils/get-license-info.js

- Some works are licensed under Open Government Licence V2, as  specified in the iiif presentation manifest for the work.
- The licenseMap object, we use for our license information, doesn't account for this.
- This PR adds information to the object, so that license information will be displayed to the user.
- Open Government Licence V2 is directly compatible with the Creative Commons Attribution License 4.0, so I'm using the same wording, but linking to the Open Government Licence.

Add license information

---

common/views/components/FeaturedCard/FeaturedCard.js

Fix Safari bug that could hide labels in featured card

---

common/icons/svgs/status_indicator.svg
common/views/components/Dot/Dot.js
common/views/components/EventPromo/EventPromo.js
common/views/components/FeaturedCard/FeaturedCard.js
common/views/components/StatusIndicator/StatusIndicator.js
content/webapp/pages/event.js

@GarethOrmerod has pointed out a handful of visual bugs with the cards regarding spacing, typography, and the status indicator dot.
The svg that we're currently using as the dot is vertically centered with CSS, but the position of the type within the box that the letters are drawn (which is specific to the cut of the font) affects whether this _appears_ vertically centered. This became apparent when we put Helvetica regular behind a toggle, at which point the status indicator dots end up looking mis-aligned.
Using the [black large circle ascii character](http://www.amp-what.com/unicode/search/black%20large%20circle) solves this problem.

Status indicator fixes

---

common/utils/backgrounds.js
common/views/components/NewsletterPromo/NewsletterPromo.js
common/views/components/RepeatingLs/RepeatingLs.js
content/webapp/pages/newsletter.js

Updating the newsletter promo copy and design.
I don't think the pure css option is feasible with the Ls as they appear in the design, but an svg mask still allows us to change the foreground/background colours without having to upload a different image per colour option.
Also, removing the newsletter promo from the /newsletter page because it links to the page itself and could definitely cause confusion.
[Caniuse data for css mask](https://caniuse.com/#search=mask) – basically not supported in any Internet Explorer, but is almost everywhere else. I didn't think the pattern not displaying in IE would be a serious issue, because the content is still there.
__Most browsers__
__IE__

Use mask to accomplish repeating pattern

---

cardigan/stories/components/FilterDrawer.js
common/services/data/facility-promos.js
common/services/data/licenses.js
common/services/data/series.js
common/views/components/FilterDrawer/FilterDrawer.js
common/views/components/FilterDrawer/README.md

Adding the markup, styles and UI interaction/animation for the filters container on /works, with a demo in Cardigan.
I imagine a fair bit will change when we hook up real content, but felt like it made sense to get this in sooner rather than later.
Using `aria-hidden` to hide the zero-opacity elements from screenreaders – this allows the elements to remain visible while they crossfade (the `hidden` attribute has the effect of hiding them visually straight-away, which was no good, and this way felt better than listening for `transitionend` events to apply e.g. `display: none`).
Also includes a debounced resize handler that will update the height of the drawer in line with the active section's new height after the resize.
With JavaScript disabled, all sections will be visible, and the links …

Filter drawer into Cardigan

---

common/views/components/Dot/Dot.js

When we changed the status indicator dot from an svg to an ascii character, pa11y started to care about the colour contrast (because it is being treated as text).
The dot isn't meaningful as text – this PR adds an `aria-hidden` attribute to make sure screenreaders ignore it.
Also, moving the dot within the `content` of a `:before` pseudo element prevents it from being considered for contrast-ratio testing by pa11y (passing locally).

Use pseudo element for status dot and hide from screenreaders

---

catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/components/StaticWorksContent/StaticWorksContent.js
catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/pages/item.js
catalogue/webapp/pages/work.js
catalogue/webapp/pages/works.js
catalogue/webapp/services/catalogue/works.js
common/babel.config.js
common/jest.config.js
common/package.json
common/services/catalogue/params.js
common/services/catalogue/search-params.js
common/services/catalogue/urls.js
common/test/utils/dates.test.js
common/test/utils/json.test.js
common/utils/json.js
common/views/components/BackToResults/BackToResults.js
common/views/components/FilterDrawerRefine/FilterDrawerRefine.js
common/views/components/IIIFViewer/IIIFViewer.js
yarn.lock

Gets SSR search working again, if we need the search params on the other pages, we use a client side implementation. Parsers are proving pretty useful here.
Moved the toggles out of the getInitialProps of the works page, this seems like a dangerous place to be putting loads of side effects.
I think this messes a little with the other toggles, but those need to be implemented with SSR too, so maybe a good chance to do that.
Renamed the function to `clientSideSearchParams` to allow for when it is used again, that is made clear.
Updated the test on common to actually work, which showed that the date test there was broken, so sorry for being lazy and commenting that out, but I wasn't 100% sure how it was supposed to work.

make SSR work on works search

---

cardigan/stories/components/BackToResults.js

allows the search query to be edited in the storybook UI

Fixes the display of the BackToResults component in cardigan by mocking the router

---

catalogue/webapp/pages/work.js
catalogue/webapp/pages/works.js

Getting rid of the cream background behind the search area on `/works` and `/works/:id` in line with the new visual design for the filter drawer.

Remove beige background from search area (prep for filter drawer)

---

catalogue/webapp/pages/item.js
catalogue/webapp/pages/work.js
catalogue/webapp/pages/works.js
common/views/components/CataloguePageLayout/CataloguePageLayout.js

Fixes #4761 
We could probably abstract it further by having a `<WorksPageLayout />` which extends `<CataloguePageLayout />` which extends `<PageLayout />` and then have an `<ItemPageLayout />` so we stop using all the `hideThisThing` logic, but seems over kill.

reinstate beta bar

---

catalogue/webapp/components/PaletteSimilarityBox/PaletteSimilarityBox.js
catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/pages/work.js
toggles/webapp/toggles.js

Add a basic component connecting to the palette API.
This is giving us a chance to see what shape the API should be in, and what we're missing.

add basic similarity panel

---

catalogue/webapp/pages/works.js
common/views/components/Tracker/Tracker.js

Ref: https://github.com/wellcometrust/wellcomecollection.org/issues/4341
Adds the properties to the search result that has been selected.
It treats everything as a string, or a list of strings to not pollute the ES index too heavily. I have added a suggestion to the issue if we'd like more structured querying.

add extra properties to search result selected

---

catalogue/webapp/pages/works.js
common/services/catalogue/urls.js
common/views/components/Tracker/Tracker.js

Went to see how dates were doing, and the tracking wasn't there.
Might have another think about how we do this and tying it to the URL (hence I've used the URL param names).

add tracking for dates

---

catalogue/webapp/pages/works.js
catalogue/webapp/services/catalogue/works.js

Now we have [`query` and `page` in the `apiSerialisers`](https://github.com/wellcometrust/wellcomecollection.org/blob/4697006fe1610db1f37dfb41fcc2cac8cb643ccc/common/services/catalogue/search-params.js#L71-L72), they're being added twice in the query string to the API.
This doesn't affect the end result, but made me wonder, is there a good reason to treat them differently from any of the other query string parameters, or does this simplification make sense?

Treat all query string parameters equally

---

common/styles/base/_typography.scss
common/utils/classnames.js

After discussing with @GarethOrmerod it seems like there may be occasions on which we need font sizes (and probably spacings) that don't follow the default scale.
The first of these is the `UserInitiatedDialog`, the styles for which essentially remains the same from the smallest to largest breakpoints.
This PR introduces a `fontSizeOverrides` utility, that allows us to output whichever of the 10 possible font sizes that exist in the system at each of the `small`, `medium` and `large` breakpoints.

Font overrides

---

common/views/components/Footer/Footer.js

Fixes the spacing between the clock icon and text
Before:
After:

fix spacing in opening times

---

common/views/components/PopupDialog/PopupDialog.js

Adding tracking events to the `PopupDialog` for the opening and closing of the dialog box (i.e. clicking the button to launch the dialog, and clicking the close button/pressing escape/clicking `body` outside dialog when the dialog is open).

Add tracking to open/close PopupDialog events

---

common/styles/base/_typography.scss
common/utils/classnames.js
common/views/components/FeaturedText/FeaturedText.js

When we override a font-size at a breakpoint, we want the override to target _only_ that breakpoint. I think this is an appropriate use of `respond-between`, because we don't want a e.g. `small` override to mobile-first percolate up to the `medium` breakpoint.

Font overrides ii

---

common/views/components/CardGrid/CardGrid.js
common/views/components/EventsByMonth/EventsByMonth.js

Noticed that multi date event promos were displaying their next available date, regardless of the month they were grouped into. This makes them display the next available date for the month.
Before:
After:

Display the correct date for events, based on the month they are grouped in

---

common/utils/convert-image-uri.js
common/views/components/Image/Image.js
common/views/components/Images/Images.js
common/views/components/Picture/Picture.js
common/views/components/WorkEmbed/WorkEmbed.js

Prepares for Prismic switching on its imgix service.
Using the imgix service has page weight improvements:
Before:
After:

Image urls

---

cardigan/stories/components/PopupDialog.js
common/views/components/PopupDialog/PopupDialog.js

☝️ this space deserves to be part of the `PopupDialog` instead of being passed in every time by the `children`.

Bake space into component instead of passing it in children

---

common/koa-middleware/withCachedValues.js
common/koa-middleware/withPrismicPreviewStatus.js
common/services/prismic/api.js
common/views/pages/_app.js

Make shared Prismic preview links work
We were relying on hitting /preview to set a cookie which in turn determined whether or not to load the Prismic javascript. Shared links never hit /preview so now also if the subdomain is preview.

Fix preview

---

common/views/components/PopupDialog/PopupDialog.js

Fixes an a11y issue where you can't tab away from the `PopupDialog` button (doubly bad since it's the first thing on the page).

Prevent tabbing inside dialog when it first renders

---

common/views/pages/_app.js

☝️ 
__before__ (body is `light` and part of is `medium`)
__after__ (body is `regular` and part of is `bold`)

Swap Helvetica medium for bold behind toggle

---

common/views/pages/_app.js

We push the heights of pages into a cache as a result of Next `Router` events, then temporarily set the html to the last height in the cache (and pop it off the cache) on `Router.beforePopState`, so that if the page we're navigating to is taller than the one we've come from when we click the back button, there'll be enough space that we can scroll to the correct position.
Fixes #4289

Make sure documentElement is tall enough when back button clicked

---

catalogue/webapp/components/WorkCard/WorkCard.js
catalogue/webapp/services/catalogue/works.js
common/views/components/WorkHeader/WorkHeader.js
toggles/webapp/toggles.js

Pushes each search down by about 20kb to 34kb (query=botany).
Removes the location toggle as we'll be changing how that works, we shouldn't have to dig through the items to get the information.

use specific includes for works search

---

catalogue/webapp/pages/works.js
catalogue/webapp/test/search-params.test.js
common/services/catalogue/params.js
common/services/catalogue/search-params.js
common/services/catalogue/urls.js
common/views/components/Tracker/Tracker.js

- Deserialisers replicate _exactly_ what we get from the URL. The only addition is to add number and array parsers. The site then reacts with that.
- We then use an API deserialiser if we receive a `null` for any value with a default, we use the default.
Feels a bit more close to what we were talking about.

be more precise about how the parsers work

---

catalogue/webapp/pages/works.js
common/services/catalogue/search-params.js
common/services/catalogue/urls.js
common/views/components/RelevanceRater/RelevanceRater.js

My bad.
Things like string arrays serialise to `prop=val&prop=val2` in normal next land, we need to hijack that and make it a CSV.

add serialisers for links

---

dash/webapp/pages/toggles.js

Forgot to add this.
@jamieparkinson this is an annoying step - I'll make some docs for it.
What would be nicer is if we could find a way for the edge lambda to serve off another path / subdomain and this webapp just consumes that...

add search by and op test to toggler dash

---

common/views/components/OptIn/OptIn.js

Addresses the width of the purple opt in text mentioned here:
https://github.com/wellcometrust/wellcomecollection.org/issues/4411#issuecomment-557038698

width of opt in message determined by content

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

Display each note using its noteType.label as a heading
Before:
After:

Notes fields

---

catalogue/webapp/pages/works.js
toggles/webapp/toggles.js

references: #4411
Removes the search rating opt in from behind a toggle, so that everyone can opt in

remove search rating opt in from behind a toggle

---

common/icons/components/Captioned.js
common/icons/index.js

Closes #4878.
We camelize the interpretation title in order to get the icon svg. The interpretation is 'Captioned', so this PR renames `closedCaptioning` to `captioned` in order for the icon to display.

Rename Captioned icon

---

common/views/pages/_app.js

References #4862
User research/content team
Displays the survey popup on story pages. We append the `location.pathname` to the surveymonkey url, which will display as the final column in the exported 'all responses data' xls.

Add surveymonkey survey to individual story pages

---

catalogue/webapp/pages/PROGRESS_NOTES.md

People who want to stay up to date with changes we're making to search relevance
Tells them about the opt-in mechanism for collecting explicit feedback, and about a test we ran on changing the default query operator from `OR` to `AND` 
---
I'm sure there are more tests and changes to add here - please add and edit!

Update progress notes with explicit feedback and AND/OR test

---

common/styles/base/_typography.scss

Closes #4860
I think this is the minimum required change to the `.spaced-text` to align systematically with what @GarethOrmerod has specified.
`margin-top`s at desktop:
`p+p` = `*+*` = `1.55em` = `31px`
`h2+p` = `1.2em` = `24px`
`h3+p` = `0.3em` = `6px`
Using `em` means margins will scale proportionally with the type at the smaller breakpoints.

Amend space around h2 and h3 within .spaced-text blocks

---

common/services/prismic/events.js

This event https://wellcomecollection.org/events/XagmOxAAACIAo0v8 has an event missing from its schedule.
This is because the prismic request to get the scheduled events, is limited to the default of 20 items per response. This bumps that up, so all the attached schedule events are returned.

bump up the pageSize of prismic request

---

catalogue/webapp/app.js

People who might want hijack cognito redirection
Allows us to:
* Set redirect URL
* Send off to cognito URL with redirect = `https://wc.org/works`
* Redirect that redirect to `https://wc.org/works/where/you/actually/want`

add auth redirector to works

---

common/services/data/workTypeAggregations.js
common/views/components/FilterDrawerRefine/FilterDrawerRefine.js

Because we are relying on the workType aggregations from the API to display active filters, they sometimes don't appear in the UI, which is confusing for the user.
Here we're filtering by a work type of pictures(k), which in combination with the productionDatesFrom, returns no results:
However, we're only telling the user that the date filter is active (since the pictures workType is not part of the aggregations returned by the API for this query combination - as there aren't any)
This PR fixes that:
Downside is needing to keep a list of the workTypes in code.

show all active filters

---

common/styles/base/_typography.scss
common/views/pages/_app.js

☝️ 
Getting rid of the blanket `0.02em` letter-spacing for Helvetica to optimise readability.

Remove letter-spacing

---

cache/edge_lambdas/toggler.js
catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/pages/work.js
catalogue/webapp/pages/works.js
common/views/components/CataloguePageLayout/CataloguePageLayout.js
dash/webapp/pages/toggles.js
toggles/webapp/toggles.js

There's a few things in here.
Normally I wouldn't do it like this, but it seems things were backing up.
* New metadata on works from API
* Search using AND and scoring tiers
* remove palette toggle as it's now in the image search
* Put the `WorkItemsStatus` behind the toggle as it's broken
* Remove staging API as it's not useful
* other toggles tidy up

Tidy toggles and add search with scoring tiers

---

catalogue/webapp/components/Auth/Auth.js

Folk who want to use the requesting service.
Making it work.
The application needs an effective way to differentiate between the development and production keys. Having the production key in code means that the prod version will work but the dev version won't (which is better).

Use Web Auth client_id

---

catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/components/WorkItemsStatus/WorkItemsStatus.js

Probably needs some labelling, but removing the bug for now.

remove errant label on 'Where to find it' section of work details

---

cache/edge_lambdas/toggler.js
cache/edge_lambdas/toggler.test.js

Spoke with @davidpmccormick and it feels like expected behaviour is that  range of a test has nothing to do with your chances of being put in `A` or `B`.
Decision path:
- Should the test run
- Flip a coin - 50/50 chance of getting in

Use ranges with more expected behaviour on test lambda

---

catalogue/webapp/services/image-similarity.js

anyone who wants to see images with similar colour palettes 🎨 
pointing them to the correct name of the API

Update image-similarity.js with renamed palette-similarity API

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

Fixes #4925
People who like de-duped 'location of the original' information.
De-duping the 'location of the original' information, and moving the version from the newer data to the appropriate ('where to find it') section of the page.
(sparkles are for illustrative purposes only)

Move 'location of original'notes to 'where to find it' section

---

dash/terraform/terraform.tf
terraform-modules/https_s3_website/cloudfront.tf

It's irritating that we can't link directly to dash.wellcomecollection.org/toggles/ - the reason for this is that, despite setting the S3 bucket up as a website, the CloudFront origin that we use is that of the "plain" bucket, and that server does not perform URL rewrites to serve `/blah/index.html` when `/blah/` is accessed.
Next.js's export relies on a directory structure full of `index.html`s, hence the issue, and it's OK when direct linking as in this case it loads the new page via an XHR request.

Fix toggles page downloading when loaded from server

---

common/views/components/ImageGallery/ImageGallery.js

Currently we use a link to close the gallery.
This feels semantically wrong, and also updates the URL so if it is later shared, they would be taken to the image gallery.
While this is functionality we might want to support (adding links to sections) - having the close button do this again feels semantically wrong.

use button for closing image galleries

---

common/views/components/Checkbox/Checkbox.js

Keyboard navigators
Allowing them to see which checkbox they're focused on.

Improve focus states for checkboxes

---

common/views/components/NumberInput/NumberInput.js
common/views/components/TextInput/TextInput.js

☝️ 
(Aligning with Zeplin where focus states are tending towards having black borders).

Make input focus borders black

---

catalogue/webapp/components/Download/ViewerDownload.js
catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/pages/download.js

I thought about moving it into the `WorkDetailsText` component, but that felt like the component would be dealing with data management as well as rendering so left it in the components that were aware of the data model.
Assuming `humanReadableText` might become something else when being returned from the API anywho.

account for empty humanReadableText on licenses

---

common/views/components/PopupDialog/PopupDialog.js

☝️ 
The helper gets a more comprehensive set of things that can be focused, so makes sense to re-use it everywhere we need this logic.

Use getFocusableElements helper in PopupDialog

---

catalogue/webapp/test/search-params.test.js
common/services/catalogue/search-params.js

Looks like these were accidentally removed

add sound (i) and videorecordings (g) to defaultWorkTypes

---

catalogue/webapp/components/WorkCard/WorkCard.js

Those who love clean layouts
If the API returns a PDF thumbnail, we don't bother trying to render it.
This is only happening as we had to roll forward with some changes on the API which made it hard to mitigate this. We will be fixing it in the future - apologies.

hack to not try render thumbnails that are PDFs

---

catalogue/webapp/components/SearchForm/SearchForm.js

IE11 users
Allows the search form to be sumitted – `RadioNodeList` isn't defined in IE11, so checking if the `input` is an `instanceof` it was killing IE. If `RadioNodeList` isn't defined, we check for `HTMLCollection` instead.

Test for RadioNodeList to stop IE breaking

---

catalogue/webapp/components/WorkCard/WorkCard.js

☝️ 
Addresses the immediate problem with #4981 
__TODO:__

Only show thumbnails for Digital Images and Pictures for the time being

---

catalogue/webapp/components/SearchForm/SearchForm.js
common/views/components/SearchFilters/SearchFiltersDesktop.js

☝️ 
Addresses part of #4989
- The check marks aren't centred, but they do now work.
- The dates now work

Make checkbox filters work in IE11

---

catalogue/webapp/components/SearchForm/SearchForm.js

Closes #4989 
IE doesn't have `RadioNodeList`, so we need to find the checked item's value from the `HTMLCollection` instead.

Fix IE radios

---

cache/edge_lambdas/redirects.js

Alice W found loads of logs of people leaving on the lowercase version, so it must be shared somewhere in the lowercase.

redirect lowercase article URL to proper case

---

catalogue/webapp/components/SearchForm/SearchForm.js
common/views/components/SearchFilters/SearchFilters.js
common/views/components/SearchFilters/SearchFiltersDesktop.js
toggles/webapp/toggles.js

Internal researchers using the complete catalogue search that want to swap between things that have been digitised or not.
Behind a the complete catalogue search toggle.
This adds the filter to works that have a `iiif-image` or `iiif-presentation` `locationType.id`.
We're working on making it better, but for internal people, this i useful and fine for now.
This was a little more fiddly than I would have liked - the way we're doing the form and filters could probably be simplified. I haven't added a mobile filter as internally we use desktops mostly.

add digitised filter for whole catalogue search

---

cache/cloudfront_dev.tf
cache/cloudfront_prod.tf
preview/terraform/cloudfront.tf
terraform-modules/https_s3_website/cloudfront.tf

People who 💘 👮‍♀ 
https://tools.ietf.org/id/draft-ietf-tls-oldversions-deprecate-03.html
https://caniuse.com/#feat=tls1-2
Removing the old insecure ways of connecting to wc.org

deprecate TLS < 1.2

---

cache/cloudfront_dev.tf
cache/cloudfront_prod.tf
preview/terraform/cloudfront.tf
terraform-modules/https_s3_website/cloudfront.tf

As per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-viewercertificate.html#cfn-cloudfront-distribution-viewercertificate-minimumprotocolversion

update viewer certificate with correct TLS enum

---

common/views/components/Header/Header.js
common/views/components/ViewerTopBar/ViewerTopBar.js
common/views/components/ZoomedImage/ZoomedImage.js

Places ZoomedImage over the ViewerTopBar instead of under it, so users have to dismiss zoom before interacting with the links in the ViewerTopBar
Before:
After:

Zoom image position

---

common/styles/components/_header.scss

Fixes #4603
This issue is now preventing the menu from being usable on works.

Bump header z-index to make sure it's above everything

---

common/views/components/FreeSticker/FreeSticker.js

Move free sticker above desktop header

---

common/views/components/IIIFViewer/parts/MainViewer.js

We're seeing the following error inside the MainViewer component:
`Can't perform a React state update on an unmounted component.`
The `ItemRenderer` is a `React.Memo` component and as such should be completely described by reference to its `props` (i.e. it shouldn't have any side-effects).
This PR moves the asynchronous `getOcrText` function into the parent, and passes the resolved `ocrText` in as `data`, which solves the problem.

Move async function out of memoised component

---

common/hooks/useIsKeyboard.js
common/views/components/Checkbox/Checkbox.js

Closes #4983
Currently, when you open the format filters by clicking the format button, the first checkbox has a black border and the rest have grey borders.
This is because the first checkbox has keyboard focus at that point.
This is potentially confusing, making all bar the first input appear disabled.
Knowledge of what has keyboard focus is only beneficial to a user if they're using the keyboard to navigate, and this PR introduces a hook that tracks just that, applying/removing visible focus styles accordingly.
Also updates the checkbox label colour to black to further reduce the potential for is-this-disabled confusion. 
__before__
__after__

Add useIsKeyboard hook to determine when to show visual focus

---

common/views/components/NewsletterPromo/NewsletterPromo.js

Adding a supported `case` to the newsletter signup (based on an error message sent to Sentry).
Also anonymising any error data we do send to Sentry.

Do newsletter signup error handling better

---

common/services/prismic/api.js

We've seen quite a few more errors in Sentry recently most likely coming from our fetching Prismic every minute (which is currently not wrapped in a `try catch`).
This PR will report the _actual_ error to Sentry so that we can act on it if there's anything we could do (instead of 'uncaught error in Promise').
If it transpires the problem lies solely with Prismic, we can 1. let them know and 2. stop pushing the errors through to Sentry (where they're threatening to soak up our quota).

Catch errors fetching Prismic

---

common/views/components/SearchFilters/SearchFiltersDesktop.js

This fixes a 500 we're seeing if there are zero results.
__UX issue for consideration__
If we do a search from `/works` then apply a `workType` filter, any subsequent searches will also have that filter applied. But only if the search returns at least one result. I.e. if one of the subsequent searches doesn't return results, the search scope is then broadened back out to all `workType`s (which might not be immediately apparent to the user).

Don't show cancel filter link if there aren't any results

---

catalogue/webapp/services/catalogue/works.js

The API expects URLs to be encoded.
This help with that.

encode URL params to API

---

common/views/pages/_app.js
content/webapp/pages/articles.js

People not wanting to see error pages and rather get stale cache pages
Makes sure the status code propagates down to the response level.
The `_app` page is probably a really good place to start looking at testing as:
* It needs a lot of work as it's composed of lots of hangover from nunjucks days
* Moving it to typescript means it will have to be refractored with type properly
* If something is wrong here, the whole app borks.

return 500 if getInitialProps throws an error

---

assets/terraform/terraform.tf
assets/terraform/versions.tf
cardigan/terraform/terraform.tf
dash/terraform/terraform.tf
dash/terraform/versions.tf
static/terraform/terraform.tf
static/terraform/versions.tf
terraform-modules/https_s3_website/cloudfront.tf
terraform-modules/https_s3_website/s3.tf
toggles/terraform/terraform.tf
toggles/terraform/versions.tf

Ref #5070 
It does mean that we are using two versions of terraform.
This will hopefully not be for long.
How I get around this is alias `tf => terraform0.12` and leave `terraform => terraform0.11`.

move s3 websites to tf0.12

---

catalogue/webapp/components/WorkCard/WorkCard.js
common/views/components/Image/Image.js

References #4339
Fixes the issue of book thumbnails appearing tiny under certain conditions:
Before:
After:

Work card thumbnails

---

common/views/components/SearchFilters/SearchFiltersDesktop.js
common/views/components/SearchFilters/SearchFiltersMobile.js

__Don't merge – needs wellcometrust/catalogue#391 to be deployed__
When the above PR makes it into the API, we will see all workType filters in the dropdown, even when they have an aggregation count of `0`.
This PR will hide those zero-count filters unless they have already been selected.

Handle zero count aggregation buckets

---

common/utils/works.js

Fixes the link from the catalogue to the old library site, currently this link is broken as it requires users to sign in. 
Linking to the `encore.wellcomelibrary.org` subdomain avoids this.

Fix "Where to find it" link

---

catalogue/webapp/components/ImageCard/ImageCard.js
catalogue/webapp/components/ImageSearchResults/ImageSearchResults.js
catalogue/webapp/components/WorkSearchResults/WorkSearchResults.js
catalogue/webapp/pages/works.js

Closes #5079 
People who want to search by image only
Gives them more images to look at on a page (100), no longer confined to a grid.

Take image search results out of grid

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.js
catalogue/webapp/components/RelatedImages/RelatedImages.js

Fixes #5080
If the modal _has_ to scroll, we scroll the lot with a scrollbar on the right. This looks less funky than a scrollbar in the centre of the modal.

Scroll entire modal, not just left column

---

common/views/pages/_app.js

People who like smaller websites
removing hotjar as we don't use it.
If we reinstate it, we should be hind a feature toggle so we can turn it on when we need it, and off when we don't.

remove hotjar

---

cache/cloudfront_dev.tf
cache/cloudfront_prod.tf

Allows the `_queryType` cookie that we are using for testing query types on the API.
It's not been a problem as we haven't allowed people to select this manually, but we want to do that, and this stops that as the set-cookie header gets cached and sent down the pipes

allow _queryType cookie through the cache

---

common/views/components/NewsletterPromo/NewsletterPromo.js

Closes #2703 
Going with the B condition of the `altNewsletterSignupCopy` A/B test. There wasn't a significant difference between the two, but B condition leaves us with the possibility to differentiate between newsletters if/when we add the ability to sign up to different newsletters from different pages.

De-toggle newsletter promo copy

---

catalogue/webapp/__mocks__/catalogue-work.js
catalogue/webapp/test/integration/works.test.js

Folk who want to test the catalogue search works
Mocking interactions with the catalogue API to ensure the front-end renders expected API results.
Based off https://github.com/wellcomecollection/wellcomecollection.org/pull/5116

Catalogue Integration tests with mocked API

---

cache/cloudfront_prod.tf

People trying to deploy the cache
Uses the `qualified_arn`s for the lambdas. [The docs specify here that the arn is unqualified](https://www.terraform.io/docs/providers/aws/d/lambda_function.html#arn).
I am trying to figure out if this changed on moving to 0.12, but can't find evidence of that.
🤷‍♂ 🦐

use qualified_arn for edge cache lambdas

---

common/model/global-alert.js
common/services/prismic/global-alert.js
common/views/components/PageLayout/PageLayout.js

Closes #5157 
Content team
Allowing them to decide which pages the alert banner should display on.
Because `/visit-us` is a vanity URL, this method requires knowing that the _actual_ url is `/pages/WwLIBiAAAPMiB_zC`. Not sure if this is a problem we need to solve.

Allow alert banner to be targeted based on page-path

---

common/utils/convert-image-uri.js

The code we use to determine the image src, so we can then provide various sized images in the src-set, wasn't always working for images from prismic.
Sometimes  we were receiving urls with the backslash encoded, which meant we didn't resize the images.

resize all prismic images, so we aren't loading huge images when we don't need to

---

content/webapp/pages/event.js

If an interpretation type is added to an event, and we don't have an icon for it, then the page breaks. This adds a check that the interpretation type is one of the ones we have an icon for before trying to render it.

check we have an interpretation icon before trying to render it

---

cache/cloudfront_prod.tf

Developers who want a clear CloudFront config
Removing unused aliases (`next.` and `whats-on.` are no longer referred to by the apps or on the internet).

Remove unused aliases

---

common/koa-middleware/withCachedValues.js
common/koa-middleware/withPrismicPreviewStatus.js
common/views/components/PageLayout/PageLayout.js
common/views/pages/_app.js

We are using the hijack of the isPreview query parameter to read the value, but setting it directly on the ctx.
This just sets the isPreview cookie giving us 1 way to do this, just in multiple places.
Trying to think of a E2E test, but nothing comes immediately.

add isPreview cookie in preview middleware

---

catalogue/terraform/main.tf
content/terraform/main.tf

Developers who want to use the staging environment.
Providing a clear template for creating staging apps for content and catalogue services.

Add prompts for creating stage deployments

---

catalogue/terraform/locals.tf
content/terraform/locals.tf

Bumps the [new nginx container](https://github.com/wellcomecollection/platform/pull/4383) that passes the host header across for preview to work.

bump nginx container version to include Host headers

---

catalogue/webapp/components/Download/Download.js
common/utils/works.js
common/views/components/IIIFViewer/IIIFViewer.js

References #4938
People who want to download single images from the viewer
Adds links to 2 sizes of the current image being displayed

Single image downloads

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

This ensures that scroll lock behaviour works.
Previously, the second rendered (but inactive) modal removed the body classes that locked scroll when the first modal was active.

Only render one modal at a time

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

We don't need the space for the cell that holds the checkbox if we're only displaying one item in the table (because it is checked by default), but we need to remove the extra space that's created.
__Before__
__After__

Fix table alignment when there's only one item

---

common/hooks/useAuth.js

If the `fetch` in `getToken` fails for any reason, the function will return `undefined` as the value of `token`. Code block [here](https://github.com/wellcomecollection/wellcomecollection.org/blob/eed80e96064b20fe9034980207e44e6b81263f70/common/hooks/useAuth.js#L44-L55).
We `JSON.stringify` the `token` and keep it in `localStorage`, but without checking that it is properly defined, we currently can end up with the string 'undefined' stored as the value for `auth.token` in `localStorage`.
This PR adds a check for the token in the `authorise` function, so it won't add an undefined value to `localStorage`, or set the `authState` to `authorised`, or change the URL. But I'm not sure what we should do _then_ – retry the authorisation somehow? Display an error message? Do nothing?

Check that token is defined before adding it to localStorage

---

catalogue/webapp/components/ItemRequestButton/ItemRequestButton.js
catalogue/webapp/components/LogInButton/LogInButton.js
catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/test/components/__snapshots__/WorkDetails.test.js.snap

Closes #5191 
Adds tracking events for:
1. Visiting the Cognito auth login
2. Launching the modal window to request items
3. Confirming item requests

Stacks requesting events

---

catalogue/webapp/components/Download/Download.js
catalogue/webapp/components/DownloadLink/DownloadLink.js
common/views/components/IIIFViewer/IIIFViewer.js

Fixes #5196
Researching using the digitised collections
Showing the size of downloadable images

Pixels for downloads

---

common/views/components/NewsletterPromo/NewsletterPromo.js

Spotted that we're still displaying the initial body copy in the `NewsletterPromo` before the message you get when form submission was successful.

Show the right copy at the right time

---

cardigan/stories/components/TextInput.js
catalogue/webapp/components/SearchForm/SearchForm.js
common/hooks/useValidation.js
common/test/components/TextInput.test.js
common/test/components/__snapshots__/TextInput.test.js.snap
common/views/components/NewsletterPromo/NewsletterPromo.js
common/views/components/TextInput/README.md
common/views/components/TextInput/TextInput.js
common/views/themes/default.js

Site users
Giving them a better input element
__TODO__
__Focus__

Input update

---

common/hooks/useValidation.js
common/views/components/NewsletterSignup/NewsletterSignup.js

Anyone who wants consistent text inputs.
Using the same email validation `TextInput` on the `/newsletter` page as appears in the `NewsletterPromo`.

Update TextInput on /newsletter page

---

common/styles/base/_typography.scss
common/views/components/AppContext/AppContext.js
common/views/pages/_document.js

People who like consistent link focus styles
Adding a turquoise border to all links when focused
In draft [while we consider whether we want these styles to always apply, or only with keyboard focus](https://github.com/wellcomecollection/wellcomecollection.org/issues/4946#issuecomment-615308773)
[Decision made on focus styles](https://github.com/wellcomecollection/wellcomecollection.org/issues/4946#issuecomment-616573719) is to apply turquoise-border focus state to links and buttons only when accessed via the keyboard.

Add turquoise border to focused links

---

common/views/components/CheckboxRadio/CheckboxRadio.js

☝️ 
Relates to #4946.
Question for @GarethOrmerod about whether or not the `border-color` and `box-shadow` should transition (which they are doing currently). If so, then should we update these properties for the other `:focus` states (links and buttons) to transition as well?
[Zeplin designs/rationale](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5ea1a9620e1d577b0a1e8dac)

Update checkbox and radio hover/focus states in line with designs

---

common/views/components/Collection/Collection.js
common/views/components/CollectionSearch/CollectionSearch.js

~I'm going to dig into why this fixes an issue when we hover over it as previously done, it tries to load `pages/works/[id].js`...~
☝️ is not true.
Just needed to use the `workLink`. Removed the scroll so you stay on the same part of the page.

Use work links on Collections

---

catalogue/webapp/components/RequestLocation/RequestLocation.js
catalogue/webapp/components/WorkDetails/WorkDetails.js

As we were running through some collection stuff, there were a few errors popping up from this component.
As it's untested, and still in development, it'd be good for it to live behind a toggle so the untested code can break, but safely.
Introducing code that is for an in-dev component is always dangerous and should be avoided. This makes quick easy iteration of the current beta feature even quicker and easier.

move requests service work behind a toggle

---

common/hooks/useOnScreen.js
common/views/components/IIIFViewer/parts/GridViewer.js
common/views/components/IIIFViewer/parts/MainViewer.js
common/views/components/IIIFViewer/parts/ThumbsViewer.js
common/views/components/ImageViewer/ImageViewer.js

Fixes #5269
Uses the top and bottom positions of the target element, relative to the mid point of the root element, in combination with the isIntersecting value to determine which image should be considered to be 'current'. Previously it was only using isIntersecting, with a 10% threshold.

Viewer bug

---

common/views/components/Collection/Collection.js

Just a small update to @jamesgorrie `Collection` component. Doubt this will make it through to the final user interface but wanted to display more of the functionality the current API offers (letting the user explore more of the archive without actually changing what work is selected).

Allow expanded of collections without selecting works

---

dash/webapp/pages/index.js

People who want to see the digital engagement indicators 
Giving them a link to the spreadsheet

added link to digital engagement indicators on dash

---

common/services/prismic/events.js

Fixes #5276
- the order that event dates are entered into Prismic shouldn’t determine which one determines the latest date of the event

order dates before finding the last one

---

cache/cloudfront_prod.tf
cache/cloudfront_stage.tf

People who like the site's client-side JS to work immediately after it's been deployed.
Reducing the time with CloudFront caches errors ([docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/custom-error-pages-expiration.html)).

Reduce min_ttl for assets at /_next/

---

catalogue/terraform/provider.tf

This provider existed in other stacks but not in the catalogue one, and without it Terraform was fetching a later version and getting upset

Add explicit template provider version for catalogue terraform stack

---

common/views/components/ArchiveBreadcrumb/ArchiveBreadcrumb.js

People who like slightly nicer styles for their archive breadcrumbs (especially when archive section/item titles are very long)
Top-aligning multi-line titles, limiting title line-length and preventing icons from shrinking.

Style breadcrumbs

---

common/services/prismic/html-serializers.js

If there isn't anything to drop-cap, as in the case of `/articles/W03jACYAACUAg5IR`, the serializer crashes. This stops it doing that.

Fix crash when trying to serialize a non-existent drop cap

---

catalogue/webapp/pages/works.js
common/views/components/CollectionSearch/CollectionSearch.js

People wanting to see collection results when there are no normal results
Doesn't hide the collection search if that search would actually yield results

show collection search even when the main search has no results

---

catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/test/components/__snapshots__/WorkDetails.test.js.snap
common/views/components/ButtonSolid/ButtonSolid.js

Replacing the final primary-esque button with a `ButtonSolid`. This one slipped through the net because it had no mention of `btn--primary` _or_ `import Button` (a good illustration of why we needed to rationalise our button styles in the first place).

Search form button

---

cardigan/stories/components/FeaturedCard.js
common/views/components/FeaturedCard/FeaturedCard.js

Enabling the copy/image for the `FeaturedCard` to appear on opposite sides to allow for less homogenous appearance especially when e.g. multiple `FeaturedCards` appear on the same page.

Allow FeaturedCard to have image and copy in reversed locations

---

common/views/components/ViewerTopBar/ViewerTopBar.js

People who don't want the download button to be invisible until you hover it on work pages.
Fixing it so the button is visible, has the correct colours, and still displays its text at smaller breakpoints.
Fixing a bug I introduced when updating button styles.

Show download button on work page

---

common/services/catalogue/api.js

People who don't want to find works on the website that they can't do anything with
Removing works with access conditions from search results until we can handle them on the front end
Fixes #5314, references #4529
- filters out 'open with advisory', 'restricted' and 'closed'

Filter access status

---

common/views/components/Card/Card.js
common/views/components/CardGrid/CardGrid.js
common/views/components/EventPromo/EventPromo.js
common/views/components/ExhibitionPromo/ExhibitionPromo.js
common/views/components/FacilityPromo/FacilityPromo.js
common/views/components/StoryPromo/StoryPromo.js
content/webapp/pages/stories.js
content/webapp/pages/whats-on.js

Preparing the different cards (exhibition/event/story/facility) to display differently based on a parent `css-theme` class, ready for the work to create various card sections in #5317.
For example
- cards that appear on a cream background should have a white background, and vice versa
- cards that appear on a charcoal background should have a transparent background and white text
- cards that have a transparent background should have no horizontal padding applied to the text

Card theme

---

catalogue/webapp/test/components/__snapshots__/WorkDetails.test.js.snap
common/views/components/ButtonSolid/ButtonSolid.js

Keyboard navigators
Dissociating hover and focus styles from buttons.
If a button has keyboard focus, it will continue to receive a blue outline (as will be the case for all focusable elements), but will no longer change its background as it does when currently hovered.

Don't apply hover styles to buttons on focus

---

common/views/components/FeaturedCard/FeaturedCard.js

☝️ 
`NextLink`s aren't for use with external links (which is how cards currently operate).

Don't use NextLink for FeaturedCard links

---

common/data/facility-promos.js
content/webapp/pages/whats-on.js

Reverting the links to what they were previously, but re-ordering the `eatShopPromos` array (which is where the problem was initially spotted).

Fix cafe/shop links (again)

---

common/views/components/FeaturedCard/FeaturedCard.js

This ensures the top of the image and the copy sections in the `FeaturedCard` are vertically offset even when there aren't any labels

Shim space if there aren't any labels in the FeaturedCard

---

common/views/pages/_app.js
content/webapp/pages/article-series.js
content/webapp/pages/article.js
content/webapp/pages/articles.js
content/webapp/pages/book.js
content/webapp/pages/books.js
content/webapp/pages/event-series.js
content/webapp/pages/event.js
content/webapp/pages/events.js
content/webapp/pages/exhibition.js
content/webapp/pages/exhibitions.js
content/webapp/pages/homepage.js
content/webapp/pages/page.js
content/webapp/pages/place.js
content/webapp/pages/stories.js
content/webapp/pages/visit-us.js
content/webapp/pages/whats-on.js

Fixes error we sometimes see on static pages

remove memoizedPrismic from ctx.query once we’ve made use of it

---

common/views/components/ContentPage/ContentPage.js
content/webapp/pages/user-panel.js

People who want a way to get to the `/user-panel` page without typing it in the url bar or being sent there from social media
Adding a `CompactCard` linking to the page from the bottom of the `/what-we-do` page.
__TODO:__

Add a compact card for the user panel

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.js
catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.js
catalogue/webapp/components/ImageSearchResults/ImageSearchResults.js
catalogue/webapp/components/VisuallySimilarImagesFromApi/VisuallySimilarImagesFromApi.js
common/model/catalogue.js

This fixes 2 of the biggest issues that the new image search had:
- The image in the modal is always shown (previously it tried to get the image off the work that the image was from 🙃 which failed sometimes)
- Clicking on the visually similar images will update the modal in-place. This fixes an issue where clicking them took you to a work where you couldn't see them (similar root to the first issue).
The view work / view image buttons still suffer from these cases but that requires some more thought and UX input to fix.

Image modal fixes

---

cache/cloudfront_prod.tf
cache/cloudfront_stage.tf

I'm not really convinced by this change, but I do remember having to do it before. It seems like it shouldn't be necessary because we shouldn't be getting a 404 to cache in the first place!
Anyway, maybe next time someone deploys I'll have a look and see if I have any more ideas. One other thought is - I wonder if the problem is that we're caching the old _page_ but not the old JS, so the assets that are 404ing might actually be the old ones? 🤷‍♂️

No caching of 404s

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.js
catalogue/webapp/components/VisuallySimilarImagesFromApi/VisuallySimilarImagesFromApi.js

Got to admit this is where React hooks are really, really nice to use

Fix: visually similar images do not refresh when changing image in modal

---

common/views/components/ArchiveBreadcrumb/ArchiveBreadcrumb.js
common/views/components/ArchiveTree/ArchiveTree.js
common/views/components/RelatedArchiveWorks/RelatedArchiveWorks.js

More of what's in #5315 to get prototype archive UI displaying (and stop the app from breaking if you have archive prototype toggles turned on).
Basically, we can't rely on `work` being in the archive api response, so have to check.

Don't rely on work being available

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.js
catalogue/webapp/components/VisuallySimilarImagesFromApi/VisuallySimilarImagesFromApi.js
catalogue/webapp/pages/download.js
catalogue/webapp/pages/item.js
catalogue/webapp/pages/work.tsx
catalogue/webapp/pages/works.js
catalogue/webapp/services/catalogue/common.js
catalogue/webapp/services/catalogue/images.js
catalogue/webapp/services/catalogue/works.js
common/services/catalogue/api.js
toggles/webapp/toggles.js

I realised I hadn't been using the `stagingApi` toggle where I should've been so I've moved the logic for that into the `get<Thing>` functions - hopefully will avoid the same mistake in future.

Add toggle for the miro merging test index

---

common/views/components/RelatedArchiveWorks/RelatedArchiveWorks.js

References #5365 
Before:
After:

amend RefNo's to AltRefNo's

---

catalogue/webapp/app.js
catalogue/webapp/components/VisuallySimilarImagesFromApi/VisuallySimilarImagesFromApi.js
catalogue/webapp/pages/image.js
catalogue/webapp/pages/item.js
catalogue/webapp/services/catalogue/images.js
common/services/catalogue/routes.js
common/views/components/IIIFViewer/IIIFViewer.js
common/views/components/IIIFViewer/parts/NoScriptViewer.js

This is similar to the items page in that it wraps IIIFViewer, albeit without all the other possibilities that items can bring. I also tried to reduce some of the duplication involved in the `iiifImageLocation`/`iiifImageLocationUrl`/`imageUrl` etc values in and around the viewer.
You would access this page with a route like:
```
/works/t867gjws/images?id=as33wqfn
```

Images page

---

common/views/components/FeaturedCard/FeaturedCard.js

Closes #5392
Copy and image are now flush against each other at the small and medium breakpoints.
Screenshot from Cardigan:

Remove FeaturedCard copy/image overlap

---

catalogue/webapp/middleware/withQueryType.js
common/services/catalogue/swagger.js
common/views/components/SearchToolbar/SearchToolbar.js

This is so we can test queries on the staging API first, before moving to prod.
We had to change the middleware as well as it would look at the swagger for the allowedValues, and these will be different on different stages.
I haven't cared much about the extra http request as it's only made by the app and cached.
Also added the entire catalogue switch onto the search toolbar.

Allow the query type selector to work in conjunction with the staging API

---

catalogue/webapp/components/WorkDetailsText/WorkDetailsText.js

and stops data disappearing from the page
We were trying to nest `<p>`'s in a `<p>`

fixes Warning: Prop `dangerouslySetInnerHTML` did not match.

---

common/model/card.js
common/views/components/FeaturedCard/FeaturedCard.js
common/views/components/LandingBody/LandingBody.js

Relates to #5317
This allows items with a `Card` content type to be rendered as a FeaturedCard in the `LandingBody`. This means that we can display a featured 'What's On' card (because 'What's On isn't a page in Prismic).

Visit us whats on card

---

common/styles/components/_body_text.scss
common/views/components/ButtonOutlined/ButtonOutlined.tsx

If a component comprised of an anchor tag is inside a `.body-text` block, the css currently applies any border bottom to be transparent on hover. This is undesirable if the component has its own border, e.g.
This adds a `:not(.link-reset)` declaration to the `.body-text` css, and anywhere we want to remove the hover behaviour within an anchor component, we can add the `link-reset` class.
This is branched off #5319 so there should only be a couple of files changes if/when that gets merged ([this commit](https://github.com/wellcomecollection/wellcomecollection.org/pull/5355/commits/0189b36e3ae78edfa0d282533fb70cd8506321a4)).

Link reset

---

common/views/components/FeaturedCard/FeaturedCard.js

The `Card` content type can have a format. If this has been added and we're rendering the content in a `FeaturedCard` component, we should display it.

Show the format label if there is one

---

common/views/components/LandingBody/LandingBody.js

If `LandingBody` items are already Prismic `Card` types, we don't want to convert them.
__Before__
__After__

Don't convert items if they're already of type 'card'

---

common/views/components/LandingBody/LandingBody.js

Fixes #5425
Removes excess space/wobbly-edge below final component.

Remove excess space from last items

---

common/utils/backgrounds.js
common/views/components/ErrorPage/ErrorPage.js
common/views/components/HeaderBackground/HeaderBackground.js
common/views/components/LayoutPaginatedResults/LayoutPaginatedResults.js
common/views/components/PageHeader/PageHeader.js
content/webapp/components/Exhibition/Exhibition.js
content/webapp/components/Installation/Installation.js
content/webapp/pages/article.js
content/webapp/pages/event.js
content/webapp/pages/page.js

Closes #5411
Uses the `PageHeader` component.
I added an (optional) `isContentTypeInfoBeforeMedia` prop to the `PageHeader` in order to determine when to display the `ContentTypeInfo` below the textured background area, rather than within it. I'd started trying to do this based on other factors (e.g. the presence of `FeautredMedia` or a `HeroImage`, but the conditionals got quite long and esoteric to the extent that a new prop felt better).
All `PageHeader` content is now aligned to the left edge of the grid (i.e. in line with the Wellcome logo), whereas previously it was padded in. The place where this makes most of a difference is on the individual article and exhibition pages, as these also use a version of the `PageHeader`. Agreed with @DominiqueMarshall that keeping left-alignment …

Use and update PageHeader for list pages

---

catalogue/webapp/Dockerfile
content/webapp/Dockerfile

We're falling out of line with the LTS and `apt` is playing up in places. Instead of running `apt update` which makes the build more inconsistent over time, and can run into every growing build times due to downloading more and more as we become out of date, let's just keep up to date.

update node versions to 12.18.3 on webapps

---

catalogue/webapp/pages/works.js
common/hooks/useHotjar.js
common/views/pages/_app.js
toggles/webapp/toggles.js

User researchers.
Letting them collect hotjar data.
Added the hotjar script as a hook so that it can be added/removed from individual pages relatively easily as needed. Currently only required on (so only added to) the works search pages.

Re add hotjar

---

common/views/components/ArchiveTree/ArchiveTree.js
common/views/components/ButtonOutlined/ButtonOutlined.tsx
common/views/components/Rating/Rating.js
common/views/components/RepeatingLs/RepeatingLs.js

Fixing a handful of stray instances not using the `color` function.
__before__
__after__

Use color function everywhere

---

catalogue/webapp/services/catalogue/common.js
toggles/webapp/toggles.js

It's hard to keep the miro merging test pipeline and the production pipeline mappings in sync with each other, so disabling the use of separate indices in the image search for now.

Disable miro merging test

---

catalogue/webapp/test/components/__snapshots__/WorkDetails.test.js.snap
common/views/themes/default.js

☝️ 
There is still a question of green on black being inaccessible, but that only happens on hover in the footer currently, so is less critical (and the footer is subject to change).

Update green hex value to be accessible on white and cream

---

common/views/components/SelectContainer/SelectContainer.js

Aligning our styled `select` element with the `DropdownButton` (inline variant) styles.
I think hover styles have to be distinct, because you can't afaik have e.g. text-decoration on an `option` element (and I don't _think_ we want to start hacking the `select`. I certainly don't). I've used the focus style for hover currently, but will check with @GarethOrmerod if there's something he'd prefer.

Select styles

---

deploy/deploy_service.js

☝️ 
Sometimes when I run the deploy script, it'll take a couple of tries before the most recent tag is the first one in the array. Sorting the array by `last_updated` ourselves should fix this.

Ensure the first docker tag in the array is the most recent

---

catalogue/webapp/components/RequestLocation/RequestLocation.js
catalogue/webapp/components/SearchForm/SearchForm.js
common/views/components/CheckboxRadio/CheckboxRadio.js
common/views/components/CheckboxRadio/CheckboxRadio.tsx
common/views/components/NewsletterSignup/NewsletterSignup.js
common/views/components/RadioGroup/RadioGroup.js
common/views/components/SearchFilters/SearchFiltersDesktop.js
common/views/components/SearchFilters/SearchFiltersMobile.js
package.json
yarn.lock

The font size for the filters and the All collection/Images only radios is currently one size larger than it is in the designs. This PR reduces those font sizes.
Using percentages for the `CheckboxRadio` icon sizing _seems_ to solve the browser rounding errors that resulted in radios possibly looking like googly eyes.

Filter font size

---

common/views/components/NumberInput/NumberInput.js
common/views/components/SearchFilters/SearchFiltersMobile.js

Fixes #5465
Also removes the inset box-shadow from the top of the input (added by iOS `-webkit-appearance`).

Make enough space for padding and 4 characters

---

catalogue/webapp/pages/works.js

Accidentally left these in for the images search

Don't show search title and description on images search page

---

catalogue/webapp/components/Work/Work.tsx
common/views/components/ArchiveTree/ArchiveTree.js
common/views/components/WorkHeaderPrototype/WorkHeaderPrototype.tsx

References #5281 
People testing the archive UI
- Sticky archive tree navigation with a max-height of 100% of the viewport. When an item has a lot of content (i.e. in the right-column) this ensures the navigation remains visible. It also alleviates the problem of being scrolled a long way down the archive tree navigation (i.e. in the left-column), clicking an item and not seeing the right-column content update.
- Moving the header section (title etc.) into its own row above the body of the content and including the archive collection title above the item.
- Clicking a link in the archive navigation will scroll the page to the title after the url has changed (this was actually slightly nicer when the title was aligned with the top of the nav because the nav would stay stuck but …

Archive tree updates for testing

---

content/webapp/pages/landing-page.js

Fixes #5478 with the addition of a 'visit-us' tag to the 'Visit us' page in Prismic.
Presumably the reason the tag has been removed from the page in Prismic is because it creates a breadcrumb and looks bad

Don't have any breadcrumbs on landing pages

---

common/views/components/WorkHeaderPrototype/WorkHeaderPrototype.tsx

Improving spacing for groups of header and body content on archive pages.

Amend spacing for WorkHeader

---

common/views/components/ArchiveBreadcrumb/ArchiveBreadcrumb.js
common/views/components/DropdownButton/DropdownButton.tsx

List items inside the archive breadcrumb have `min-width: max-content` set. Chrome expands the wrapper for these items accordingly, but safari doesn't. Setting `min-width: max-content` on the container solves the problem.
__Before__
__After__

Provide enough space for DropdownButton content

---

common/views/components/ButtonOutlinedLink/ButtonOutlinedLink.tsx
common/views/components/ReopeningBanner/ReopeningBanner.tsx
content/webapp/pages/homepage.js
toggles/webapp/toggles.js

☝️ 
part of #5457 
Adding a `buildingReopening` toggle so that we can view this and any other new bits of UI for testing.

Add static re-opening banner behind new buildingReopening toggle

---

catalogue/webapp/pages/item.js

☝️ 
Allows `mainImageService` to be null again.

Fix pdf viewer

---

catalogue/terraform/main.tf
catalogue/terraform/stack/main.tf
content/terraform/main.tf
content/terraform/stack/main.tf
infrastructure/terraform/modules/service/main.tf
infrastructure/terraform/modules/service/outputs.tf
infrastructure/terraform/modules/service/variables.tf

Developers who want deployments (quite possibly automated deployments from CI).
To use the new weco-deploy tool we need to upgrade some ECS infrastructure - this does that and allows tagging of ECS services/tasks that is required for weco-deploy to work.
*Note:* This enables the staging services as an upcoming step will be automatically deploying to stage from CI.

Upgrade ECS to 1.4 (to be compatible with weco-deploy)

---

.buildkite/pipeline.yml
package.json

Developers who want faster builds.
Making builds faster.

double install in setupCommon unnecessary

---

common/styles/base/_typography.scss
content/webapp/pages/covid-book-your-ticket.tsx
content/webapp/pages/covid-welcome-back.tsx

Until now we've only accounted for the spacing of `p`s after headings within `spaced-text` blocks, but recent copy indicates that we need to apply the same rules to `ul`s too. We _could_ make the selectors broader (e.g. `h2 + *`), but that feels a bit heavy handed to me.

Systematise spacing for uls after headings

---

catalogue/webapp/test/components/__snapshots__/WorkDetails.test.js.snap
common/views/components/ButtonSolid/ButtonSolid.tsx

`styled-components` don't merge `attrs`, so if one styled component styles another one and they both have `className` in their `attrs`, only the outer component's `className`s will exist.
Here, `BaseButton` had vertical alignment classes from `root-scope-classes`, but they were being overridden by the `SolidButton`'s classes.
Adding the properties directly to the components instead of using `root-scope-classes` solves this.
Most of the changes in this PR are the result of Prettier not previously having been run on this file.
See https://github.com/styled-components/styled-components/issues/2270 for more context.

Vertically-align contents of BaseButton

---

infrastructure/terraform/locals.tf
infrastructure/terraform/terraform.tf

Part of https://github.com/wellcomecollection/platform/issues/4802
We've rearranged some of our Terraform configs to reduce the amount of cross-account coupling. Changing the storage VPC shouldn't affect the Experience VPC, etc.
I've already checked this is a no-op.

Use the new location of the VPC terraform state

---

catalogue/webapp/components/ImageCard/ImageCard.js
catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.js

We hadn't noticed this because the link is overridden by the JS to open the modal, but it does crop up if you try to open an image in a new tab

Fix image card hrefs

---

common/views/components/SearchFilters/SearchFiltersDesktop.js

People who love convenient clearing of filters
Makes clearing location type filters conveniently

add clear filter for item location type

---

assets/terraform/terraform.tf
static/terraform/terraform.tf

People who like pretty fonts and favicons
Uses a valid vert for `i.wellcomecollection.org` and `static.wellcomecollection.org`.
This has been applied and has been seen working in the wild.

use hardcoded cert for static and assets domains

---

catalogue/webapp/components/WorkDetailsProperty/WorkDetailsProperty.js

Fixes #4259 
Keeps the WorkDetails font size at 16px instead of 15px at the small and medium breakpoints.

Override work font-size at small and medium breakpoints

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

Relates to #5510 
I didn't get into conditionally changing the CTA because a single work can have multiple items of which some might be requestable and some not.

Use ButtonOulinedLink for link to Wellcome Library

---

common/views/components/Table/Table.tsx

The `Table` component can accept `string`s or `JSX.Element`s as cell data, but it currently runs all items through `dangerouslySetInnerHTML`. This checks if it's a React element and renders it as is if so.
__before__
__after__

Render React elements in Table if they're valid

---

common/views/components/FeaturedCard/FeaturedCard.js

This is hacky and obviously doesn't make me happy, but Firefox doesn't like maths.

Shunt FeaturedCard shim up a pixel to prevent a white line appearing

---

catalogue/webapp/pages/works.js
common/services/catalogue/api.js
common/views/components/SearchFilters/SearchFilters.js
toggles/webapp/toggles.js

In order to make testing the archive prototypes as simple as possible for participants, the archivesPrototype toggle combined some changes to search functionality, i.e. to include archives in search results.
Now that the testing is over, and we are about to make unfiltered searches live anyway, it makes sense to remove this additional functionality from this toggle.

stop archivesPrototype toggle from affecting search results

---

catalogue/webapp/pages/works.js

This removes code that set the toggle_archivesPrototype cookie to true based on a query parameter. It was just needed for the last round of testing.

remove prototype cookie code

---

common/views/components/ModalFilters/ModalFilters.tsx
common/views/components/SearchFilters/SearchFilters.js
toggles/webapp/toggles.js

Puts the filter prototype (i.e. using a modal behind a button on desktop too) behind its own toggle.
This is currently behind the archivesPrototype toggle but isn't in a state to be released with the rest of the archives work.

puts the filter prototype behind its own toggle

---

catalogue/terraform/stack/data.tf
content/terraform/stack/data.tf

Fixes terraform operations not working because referencing moved state.

Use correct remote state in services

---

README.md
cache/edge_lambdas/Dockerfile
cache/edge_lambdas/deploy.js

This change fixes the deploy step for the edge_lambdas project. The problem was caused by incorrect encoding used when the ZIP file was uploaded. 
This PR also includes documentation for replicating CI steps locally to make future debugging easier.

Fix edge_lambdas deploy step

---

common/views/components/ArchiveTree/ArchiveTree.js

Had accidentally remove max-height on archive tree container, which means users can no longer scroll it independently of the rest of the page. This puts it back

making archive tree scrollable

---

cardigan/stories/components/Footer.js
cardigan/stories/content.js
common/model/opening-hours.ts
common/services/prismic/hardcoded-id.js
common/test/fixtures/components/opening-times.js
common/views/components/Footer/Footer.js
common/views/components/FooterOpeningTimes/FooterOpeningTimes.test.js
common/views/components/FooterOpeningTimes/FooterOpeningTimes.tsx
common/views/components/FooterOpeningTimes/__snapshots__/FooterOpeningTimes.test.js.snap
common/views/components/LandingBody/VisitUsStaticContent.js
common/views/components/VenueClosedPeriods/VenueClosedPeriods.js
common/views/pages/_app.js
content/webapp/pages/whats-on.js

*  Not allow, Footer collection venue opening times names dynamic.
*  Replace name and using id to find openingTimes on whats-on.
@jamesgorrie @gestchild @davidpmccormick  - I have done some regression, seems to be all rendering fine. 
* visit-us 
* footer page
* opening-times page
Let me know if you think i would need to introduce any unit testing in any parts of the code I have implemented.
Effected pages: 
- VisitUsStaticContent
- Footer.js 
- whats-on.js 
- VenueClosedPeriods

 Not allow, Footer collection venue opening times names dynamic.

---

content/webapp/pages/homepage.js

Prevents the homepage from looking bare until we have enough events/installations/events to make the 'This week' section look ok.

Only show 'This week' if there are 3+ cards

---

common/services/prismic/pages.js
common/test/fixtures/pages/page.js
common/test/services/prismic/pages.test.js

People who want pages to not break
Testing that the body exists before trying to parse it.
I feel like typing could/should probably help here too (`body` can be undefined, but this isn't expressed in our GenericFields). Will open a different ticket for that.

Start tests for pages (parsePage:parseOnThisPage)

---

common/styles/components/_wobbly_edge.scss

Prevents the wobbly line animation, if users have specified a preference for reduced motion in system settings, in accordance with [Success Criterion 2.3.3 Animation from Interactions (Level AAA)](https://www.w3.org/TR/WCAG21/#animation-from-interactions)

use prefers-reduce-motion media query to stop wobbly line animation

---

common/styles/base/_layout.scss

Fixing an error on the [pa11y dashboard](https://dash.wellcomecollection.org/pa11y/) regarding color/background contrast on the `noscript` elements.

Add background and color to noscript

---

dash/webapp/pages/toggles.js

I've noticed a few times recently that stale toggle state has caused perceived bugs for some people (myself included!). Of course we can/do check in an Incognito window but thought it would be convenient to have a button to do it for us. It looks like this:

Add a reset-all button for toggles

---

common/utils/works.js

Fixes #5675
We were deciding which partOf item to use as the parent work based on referenceNumber, but it looks like they don't always follow the same pattern.
At the moment there is only ever one item in the partOf array, so we can just get the first one.
If in the future partOf contains more than one item, we’ll need a way to discern which one is correct

Fix breadcrumb

---

common/views/components/PrototypeSearchForm/PrototypeSearchForm.tsx

We only want filters to display once a search has been run.

Only show filters if there's a query

---

common/views/components/BaseTabs/BaseTabs.tsx

There's a flash of content when the `SearchTabs` render both forms before we know JS is available. We can prevent this happening for testing (i.e. behave as if everyone definitely has JS), and improve how we handle this in a separate stream of work (#5696).

Treat tabs as automatically enhanced for searchPrototype

---

common/koa-middleware/tests/withToggles.test.js

update failing tests to allow httpOnly

---

catalogue/webapp/pages/images.tsx
catalogue/webapp/pages/works.js
common/views/components/Paginator/Paginator.js

This was the least required to make sure the controls don't look broken for the prototype on mobile, without changing the appearance in production.

Break sort/pagination controls onto another line where necessary

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

In the searchPrototype, on a work with a 'Selected images from this work' section (e.g. [https://wellcomecollection.org/works/bw87r748](https://wellcomecollection.org/works/bw87r748)), the button still links you to the `/works` route with the `search` query set to `images`. This changes the behaviour of that button, so that it links you to the newly created `/images` route, where the expected results are present.

Link 'Selected images from this work' to images route in searchPrototype

---

catalogue/webapp/pages/images.tsx

We don't want the 'sort by' `Select` to render for image searches (because it doesn't work).

Don't render portal on /images route

---

common/views/components/BaseTabs/BaseTabs.tsx
common/views/components/SearchTabs/SearchTabs.tsx

Taking logic for preventing a flash out of the `BaseTabs` component and into a place where we're already expecting prototype code.

Hide SearchTabs until JS fires

---

updown/webapp/expected-checks.js
updown/webapp/package.json

Closes https://github.com/wellcomecollection/platform/issues/4860
This means we should be alerted if/when wellcomeimages.org redirects break in future. This change is applied.

Add an Updown check for redirects on wellcomeimages.org

---

catalogue/webapp/test/components/__snapshots__/WorkDetails.test.js.snap
common/views/components/Modal/Modal.js
common/views/components/Modal/Modal.test.js

Fixes #5671
The `useWindowSize` hook defaults to the value `'small'`, which means the mobile version of the filters is (momentarily) rendered before being updated to the desktop view (if you're browser's wide enough). The `Modal` component in the mobile filters has an 'open' button that should get focus whenever the modal is closed. But it is also currently getting focus on initial render, which moves the scroll position to the top of the page.
This PR ensures that launch `Modal` buttons only gain focus _after_ the modal has been closed.

Don't focus Modal button on initial render

---

common/views/components/EventDatesLink/EventDatesLink.tsx
content/webapp/pages/event.js

People who like links to work
Making the event date link work
It stopped working with the next update, as the link functionality changed slightly.
This isn't actually a next link, so best we don't use it as such.
You can see it broken here:
https://www-stage.wellcomecollection.org/events/X5aeBhIAAB4Aq3nK

convert EventDatesLink to ts

---

package.json

Lets you `yarn tsc` to check TypeScript compilation for content and catalogue apps. Also runs this in the pre-commit hook to prevent us pushing broken TS.

Add tsc script

---

package.json
yarn.lock

You'll be able to commit poorly linted code that doesn't compile, but you won't be able to push it. Hopefully this will be a good balance of not-getting-in-the-way and not-opening-broken-PRs.
I think you might have to `rm -rf .git/hooks && npm install husky` after you pull this.

Move linting and typescript compilation from pre-commit to pre-push

---

catalogue/webapp/components/WorkCard/WorkCard.tsx

Closes #5759 
Draft because it has `ts-work-card` as the base branch. Will mark it ready for review once that's merged.

Add thumbnails for all work cards if available

---

catalogue/webapp/components/Work/Work.tsx
catalogue/webapp/pages/images.tsx
catalogue/webapp/pages/works.js
common/views/components/PrototypeSearchForm/PrototypeSearchForm.tsx
common/views/components/SearchTabs/SearchTabs.tsx

Be good to see if you guys think this solution is okay to go with. 
There are a couple of alternative solutions. 
* Checking the routing of the pages earlier on and passing it to searchForm
* basic black list utils to allow what should be shown and not shown on components. 
- fix warning issue on console
- remove filters on works details page
closes #5739

* Remove filters from /works/{id} pages in search prototype #5739

---

common/views/components/PrototypePortal/PrototypePortal.tsx

* Fix issue with prototype search sorting by providing state to trigger the render and bind required nodes when using reactPortal 
* Using reactPortal this for providing it to pagination search sorting is a different discussion
closes #5777

Search Sort have to click twice instead of once to trigger the select option

---

common/views/components/IIIFViewer/IIIFViewer.js
common/views/components/IIIFViewer/parts/GridViewer.js
common/views/components/InfoBanner/InfoBanner.tsx

1. Fix issue Flickering screen when displaying the scroll bar on the works viewer #5726
2. Fix issue with info banner display getting cut off in gallery view #5728
closes #5728 
closes #5726

Fix issue Flickering screen when displaying the scroll bar on the works viewer

---

common/views/components/SearchFilters/SearchFiltersMobile.js

When `SearchFiltersMobile` was being rendered, a click event would fire on the open button when the form was submitted (most obviously from the mobile native keyboard submit action, but also reproducible when pressing return in a sufficiently small viewport). This stops that from happening. I can see why a lot of people stopped using the native `<form>` element 🙃 .

Stop filters modal button being triggered by the form submit action

---

catalogue/webapp/components/WorkCard/WorkCard.tsx
common/model/catalogue.ts

Closes #5741 
This hasn't been fully designed, but @GarethOrmerod feels this is good enough to release, ahead of further design iteration on the `WorkCard` component.
Draft until we know for sure that `availableOnline` will be the property in the api.

Add starter 'available online' label

---

catalogue/webapp/components/Work/Work.tsx
catalogue/webapp/pages/images.tsx
common/views/components/WorkHeaderPrototype/WorkHeaderPrototype.tsx

Work detail page to display search ui fix - not use ToggleContext but use GlobalContext from serverProps
* WorkHeadPrototype console error .. returning false when item is not expecting boolean with lang 
* clean up remove toggleContext which is not used in images.tsx

* Work detail page to display search ui fix 

---

cache/edge_lambdas/Dockerfile
cardigan/Dockerfile
catalogue/Dockerfile
common/Dockerfile
content/Dockerfile
pa11y/Dockerfile
toggles/Dockerfile
updown/Dockerfile

This should stop the pull rate limit errors in CI. Right now, you may need to login to ECR in order to build these locally (annoying!) - you do that with:
```
eval $(AWS_PROFILE=platform-dev aws ecr get-login --no-include-email)
```
AWS is apparently going to have a public container registry available "within weeks" so hopefully this won't be the case for long.

Use ECR base images in Dockerfiles

---

package.json

We run `eslint` on any files staged for commit. But since we're now running it in the `pre-push` hook, they're not staged at this point – they've already been committed. So we're not linting anything.
I think the two options are:
1. lint the staged files in the `pre-commit` hook (as we did previously – fairly fast because you're only checking a small number of files, but happens on every commit), or
2. lint all files in the `pre-push` hook (would take a lot longer, but only happen the once)
I think my preference would be for 1., and keeping the TypeScript compilation check in the `pre-push` hook (as per this PR).

Move lint back to pre-commit hook

---

catalogue/webapp/pages/images.tsx

We won't be exposing this with the old form, so instead of trying to fix the 500 caused by `SearchForm`, I've just removed it.

don't use old searchform on images page

---

cache/cloudfront_prod.tf
cache/cloudfront_stage.tf
catalogue/terraform/data.tf
catalogue/terraform/locals.tf
catalogue/terraform/stack/main.tf
content/terraform/stack/main.tf
infrastructure/terraform/modules/alb_listener_rule/main.tf
infrastructure/terraform/modules/alb_listener_rule/variables.tf

Turns out we need to route the data fetching endpoints to the same domain as [they don't respect the `assetPrefix`](https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix) (scroll down to see it's intended behaviour).
This takes any `catalogue/pages` data endpoints (`_next/data/{hash}/{page}.json`) and adds them to the ALB. It also creates a generic cache endpoint which we can optimise later.
We should probably make more use of [dynamic routing](https://nextjs.org/docs/routing/dynamic-routes) (it wasn't available when we wrote this) and can probably. The recommended way to do this is by [using `basePath`](https://nextjs.org/docs/api-reference/next.config.js/basepath) - but we haven't separated our domains so neatly, so it doesn't really work.
(this has not been …

add routing rules and caching behaviours for nextjs data fetching

---

catalogue/webapp/components/SearchTitle/SearchTitle.tsx
catalogue/webapp/pages/images.tsx
catalogue/webapp/pages/works.js
common/views/components/PrototypeSearchForm/PrototypeSearchForm.tsx
common/views/components/SearchTabs/SearchTabs.tsx

* Make tabs work via links to stop janking on render on non js view. #5795 
* Create search title component to be used on works and images.tsx
* update the search tabs to allow to display for non js to display current state.
relating to 
#5740

Allow non js search prototype to display and update on tabs as links 

---

catalogue/Dockerfile
catalogue/webapp/pages/404.tsx
catalogue/webapp/pages/_error.tsx
catalogue/webapp/pages/image.tsx
catalogue/webapp/pages/work.tsx
catalogue/webapp/services/catalogue/common.js
catalogue/webapp/services/catalogue/images.js
catalogue/webapp/services/catalogue/works.js
common/views/components/CataloguePageLayout/CataloguePageLayout.tsx
common/views/components/ErrorPage/ErrorPage.js
common/views/components/GlobalContextProvider/GlobalContextProvider.tsx
common/views/components/PageLayout/PageLayout.tsx
common/views/pages/_app.tsx
content/webapp/pages/404.tsx

Started converting the `image` page to tsx, and realised error pages were in a mess.
* Added the `_error` pages which will catch thrown errors from next and render the `ErrorPage`
* Allow `getServerSideProps` to pass `AppErrorProps` to `_app` which then render the `ErrorPage`
* Allow PageLayout to render without `GlobalContextData` values
* return `notFound` from images API
* handle errors from works API
The next thing to do would be to integrate sentry with the new pages, but I'd like to have more of a think of where the error boundaries are and what errors we alert no. So watch this space.

convert image page to tsx and add error pages

---

common/views/components/BaseTabs/BaseTabs.tsx

The tab panels are now href links so for the non js version we can display it like the javascript version. 
Effected pages 
- images search results 
- library search results 
- collections search page
closes #5810

Non JS search: Make search tab align together instead of a row

---

catalogue/webapp/components/ImageCard/ImageCard.js

Non javascript: search on images visual issues with images overlapping each other
**Current**:
**Fix** : 
non javascript users and seo

Non javascript: currently noscript images on search are not displaying correctly on live

---

common/services/prismic/article-series.js

So that related comics show up on the series page
(until we come up with a more sustainable way of doing this)

check for new webcomic series id in getArticlesSeries

---

common/views/components/ArchiveTree/ArchiveTree.js

Fixes bug where tree control for the initially loaded work is not shown

---

cardigan/.storybook/main.js
cardigan/stories/components/oath/Login.tsx
cardigan/stories/opening-times.js
cardigan/yarn.lock
common/styles/works.scss
common/views/components/PageLayout/PageLayout.tsx
common/views/components/oauth/Login.tsx
identity/Dockerfile
identity/webapp/.dockerignore
identity/webapp/babel.config.js
identity/webapp/jest.config.js
identity/webapp/next-env.d.ts
identity/webapp/next.config.js
identity/webapp/package.json
identity/webapp/pages/_app.tsx
identity/webapp/pages/identity/index.tsx
identity/webapp/postcss.config.js
identity/webapp/styles.scss
identity/webapp/tsconfig.json
package.json

This introduces a new app for the identity work.
It adds a few base things:
* new app in the standard format that we do it
* an index page using our page layout
* a component in the components directory under the `oath` folder
And simplifies some others:
* removes a whole load of deps
* uses next directly without using the app
It'd be good to see how Digirati are using cypress and how we might integrate things.

add base identity app

---

catalogue/webapp/pages/images.tsx
catalogue/webapp/pages/works.tsx
common/views/components/Paginator/Paginator.js
common/views/components/SearchTabs/SearchTabs.tsx

* Fix issue with search tabs href not scrolling to the top but keep scroll state for all platforms
* Add padding around sort and pagination area for search for mobile
* Add feature for mobile pagination total results not allow to show pagination
* Hide total results of pagination of the bottom for mobile images and library
* always make the pagination align to the right side for all platforms
* vertically align pages numbers to pagination icon for all platforms

New search UI improvements

---

common/model/link-props.ts
common/services/catalogue/ts_routes.ts
common/views/components/Buttons/Control/Control.tsx
common/views/components/LayoutPaginatedResults/LayoutPaginatedResults.js
common/views/components/Pagination/Pagination.tsx
common/views/components/Paginator/Paginator.tsx

* Converts pagination components to tsx
* Creates a new `LinkProps` type which is a subset of the `next/link` `LinkProps` so we don't need to typecheck everywhere.

convert pagination to tsx

---

common/services/prismic/events.js
content/webapp/pages/events.js
prismic-model/js/events.js
prismic-model/json/events.json

We can mark events as available online.
As far as I can tell - this is all we will need for any differentiating in interface and works a charm for filtering, initially implemented as `/events?availableOnline=true` mimicking the API.

adds availableOnline to events

---

common/views/components/LandingBody/CollectionsStaticContent.tsx
common/views/components/SearchTabs/SearchTabs.tsx

* ConditionalWrapper 
** if javascript users land on collection page they will be not links but render tabs only. 
** If non javascript users on any search pages - tabs will work as links
* Links will Render for Non javascript or non enhanced users on Collections pages, works and images

Conditional wrapper search tabs on Collections page

---

content/webapp/pages/season.tsx

Fixes #5868 
Anything returned from the nextJS data fetching methods is serialised into JSON, including dates.
A longer terms fix might be turning the Event model into using `string` type and just converting it where we need it.

convert event dates from strings to Date type

---

common/views/components/InfoBanner/InfoBanner.tsx
common/views/components/PrismicHtmlBlock/PrismicHtmlBlock.js

Adds the link resolver to the `PrismicHtmBlock`.
Not sure how we have got away with this for this long.

add linkresolver to PrismicHtmlBlock

---

cardigan/stories/components/SeasonsHeader.js
common/services/prismic/seasons.ts
common/views/components/BannerCard/BannerCard.tsx
common/views/components/SeasonsHeader/README.md
common/views/components/SeasonsHeader/SeasonsHeader.tsx
content/webapp/pages/season.tsx

References #5755 
Creates new Season Header and groups events separately from the rest of the 'Explore more' content

Season page changes

---

common/views/components/BannerCard/BannerCard.tsx

- Promo text length is variable as is screen width, but we never want space under the image. 
- So we make sure the image always covers the height of the promo and crop the image as necessary.

Banner card improvements

---

catalogue/webapp/jest.e2e.config.js
catalogue/webapp/package.json

* Allow to show debug mode when running automated tests locally
* Render tests in mobile or desktop by default 
* Ability to run all supported browsers if required headless or not headless

Adding options for automated tests for debug and mobile

---

common/model/events.js
common/services/prismic/api.js
common/services/prismic/events.js
common/views/components/InfoBox/InfoBox.js
content/webapp/pages/event.js
prismic-model/js/events.js
prismic-model/json/events.json

Ref #5791
People wanting to know how to access an event
Adds any extra information onto an interpretation. An example from [this event](https://wellcomecollection.org/events/X2ipQhMAAExK8Kam) is
> Please note that the audio description won’t be an additional track; instead the host and speaker will describe themselves and any key visual elements they refer to. The event will be live captioned by StageText.

don't hide info box on past events, and add extra info to interpretations

---

common/services/prismic/events.js
content/webapp/pages/whats-on.js
toggles/webapp/toggles.js

Ref #5767 
People wanting to catch up on what was on.
Adds a section to what's on with catch up events.
__All behind a toggle, so we can develop in the open__

add catch up events to whats-on

---

common/views/components/SearchTabs/SearchTabs.tsx

Currently we're exposing the source in the URL. We shouldn't be.

move source from href => as on search tabs

---

common/views/components/PrototypeSearchForm/PrototypeSearchForm.tsx

People wanting to find our search form (including testing).
Adds the [search role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Search_role) to the search form.
I haven't added any labels etc as I worry about duplication and would like to have a more thorough accessibility testing process setup to be changing too much.
As a point it is best practice to label the forms differently if there are more than one `search` landmarks, but the tabs hide the form from the accessibility tree.

add search role to search form

---

prismic-model/js/series.js
prismic-model/json/series.json

Adds format to a series.
We can then flag a series as a `podcast`, or anything else in the future, to live at `/series/{id}`, and have whatever visual treatment applied to it.

add format to series

---

toggles/webapp/toggles.js

There's something wrong with the clickthrough functionality on the viewer.
Turning this toggle off will pass people to the library site to view the item, while I work out what is going on.

turn off open with advisory functionality by default

---

common/test/fixtures/pages/whats-on.js
content/webapp/pages/whats-on.js
toggles/webapp/toggles.js

Fixes #5767
Removes the toggle so live to all

remove catch up events toggle for whats on

---

content/webapp/components/Installation/Installation.js

The current Installation page header doesn't display the override status and also attempts to display a date even when there isn't one. This fixes that.
Before:
After:

Display override status in installation page header

---

package.json

The usage of single ampersands runs commands in parallel but doesn't wait for them all to return / doesn't collect exit codes, so this was passing even if there were errors(!). I imagine this is how the extra stuff got into https://github.com/wellcomecollection/wellcomecollection.org/pull/5907/files
The fix uses [this](https://www.typescriptlang.org/docs/handbook/project-references.html) feature of tsc rather than trying to do the multiple projects with shell commands

Fix tsc:lint command

---

common/model/article-series.js
common/model/article-series.ts
common/model/card.js
common/model/seasons.js
common/model/seasons.ts
common/services/prismic/article-series.js
common/services/prismic/seasons.ts
common/views/components/CardGrid/CardGrid.js
content/webapp/pages/article-series.js
content/webapp/pages/season.tsx
prismic-model/js/series.js
prismic-model/json/series.json

Fixes #5905
Makes it possible to add Series to a Season and displays the relevant promos on each page.
N.B. Using Generic Promo Card, as we don't have one for series

Add series to seasons

---

content/webapp/pages/season.tsx

Takes the season content out of separate sections and displays it as a single list with no heading:

Seasons content

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx
common/views/components/ImageLink/ImageLink.tsx
common/views/components/ItemLink/ItemLink.tsx
common/views/components/WorkLink/WorkLink.tsx

People analysing the image search
Adds the `images_search_result` source to the link. 
Updated to use component links.

add source to images/work links on image modal

---

cardigan/Dockerfile
catalogue/Dockerfile
catalogue/webapp/package.json
catalogue/webapp/pages/works.tsx
catalogue/webapp/services/catalogue/common.ts
catalogue/webapp/services/catalogue/images.ts
catalogue/webapp/services/catalogue/works.ts
common/Dockerfile
common/model/global-alert.js
common/package.json
common/views/components/ArchiveTree/ArchiveTree.tsx
common/views/components/GlobalAlertContext/GlobalAlertContext.tsx
common/views/components/GlobalContextProvider/GlobalContextProvider.tsx
common/views/components/OpeningTimesContext/OpeningTimesContext.tsx
common/views/components/PopupDialogContext/PopupDialogContext.tsx
common/views/components/PrototypeSearchFilters/PrototypeSearchFiltersMobile.tsx
common/views/components/TogglesContext/TogglesContext.ts
content/Dockerfile
identity/Dockerfile
package.json
toggles/webapp/build.ts
toggles/webapp/deploy.ts
toggles/webapp/index.d.ts
toggles/webapp/index.ts
toggles/webapp/package.json
toggles/webapp/toggles.ts
toggles/webapp/tsconfig.json
toggles/webapp/yarn.lock
yarn.lock

I'd been wondering if this was possible and thought I'd have a go at it - this work slurps the IDs out of the toggles file and makes a union type out of them, so that across the app we can be completely type safe with our toggles. One big benefit of this is that we are prevented from leaving behind old toggles - in fact I found an old one while doing this work!
Whilst it does introduce a dependency on `@weco/toggles` for the other webapps, by using `devDependencies` in the toggles app we don't drag along any of the transitive dependencies (typescript, ts-node, and aws-sdk) and so it shouldn't affect bundle size at all, but it did require that the (very small) toggles directory was added to the Docker images that needed it as a dependency.

Totally Type-safe Toggling

---

.buildkite/pipeline.yml

Waiting for deployment sometimes never succeeds - eg https://buildkite.com/wellcomecollection/front-end-wellcomecollection-dot-org/builds/1180#51445ae1-7726-4c5a-950e-a86d1d4221f4 and https://buildkite.com/wellcomecollection/front-end-wellcomecollection-dot-org/builds/1207#b278b54d-57ad-4da8-a1be-5a05f0bd282b.
I'm not totally sure of the reason(s) for this but there were a variety of fixes/changes to this behaviour since 5.5.3 so updating is the first and hopefully only step to resolving it.

Update weco-deploy to latest version

---

catalogue/webapp/components/WorksSearchResult/WorksSearchResult.tsx
common/utils/works.ts

I was accidentally not showing the reference for archive roots, and realised that we shouldn't be showing "part of" for them

Archive label tweaks

---

cardigan/stories/components/BannerCard.js
cardigan/stories/components/SeasonsHeader.js
common/model/seasons.ts
common/services/prismic/fetch-links.js
common/services/prismic/seasons.ts
common/views/components/BannerCard/BannerCard.tsx
common/views/components/SeasonsHeader/SeasonsHeader.tsx
content/webapp/pages/page.js
content/webapp/pages/season.tsx
prismic-model/js/seasons.js
prismic-model/json/seasons.json

Fixes #5865
Adds start and end dates to the seasons custom type in prismic and displays them on the BannerCard and SeasonsHeader.

Season dates

---

common/model/projects.ts
common/model/seasons.ts
common/services/prismic/pages.js
common/services/prismic/projects.ts
common/services/prismic/seasons.ts
common/views/components/CardGrid/CardGrid.js
content/webapp/pages/season.tsx
prismic-model/js/projects.js
prismic-model/json/projects.json

Makes it possible to add Series to a Season and displays the relevant promos on each page.
N.B using page parsing functions etc. until we see how projects evolve.

Add projects to seasons

---

cache/edge_lambdas/redirects.js

The latest comic was mistakenly published as the deprecated webcomic type, this redirects it to the story type version

redirect webcomic to story ‘January diet’

---

.buildkite/pipeline.yml

Deployers
Deploys to prod after a [buildkite block step](https://buildkite.com/docs/pipelines/block-step).

add block step and prod deployment to ci

---

.buildkite/pipeline.deploy-prod.yml
.buildkite/pipeline.deploy-stage.yml
.buildkite/pipeline.yml

People who want to see what's deploying where
Adds slack deployment messages to the buildkite pipeline. It might be better to have them in the deploy tool, but this can be a first step.
We split the deployment up into test / deploy / deploy stage as per the example here.
[You can see a set of pipelines running here](https://buildkite.com/wellcomecollection/front-end-wellcomecollection-dot-org/builds/1329), with the [code here](https://github.com/wellcomecollection/wellcomecollection.org/tree/e5633a0822c13ad19f4ced4800cd7aed78da08b8/.buildkite) - the PR has the actual code filled out.
After this I will work with the team to see what events we need to the channel.

Slack deploy message / split pipelines

---

catalogue/webapp/pages/item.tsx
common/hooks/useSkipInitialEffect.ts
common/views/components/IIIFViewer/IIIFViewer.tsx

**Who is this for?**
ref #5939 
People wanting more accurate analytics, and better perf on page
**What is it doing for them?**
Stops running `Router.replace` on the initial load of the page for page state that only changes once the page has loaded.

don't run router on initial load of item page

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx
catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx
catalogue/webapp/components/WorksSearchResult/WorksSearchResult.tsx
catalogue/webapp/components/WorksSearchResults/WorksSearchResults.tsx
common/views/components/IIIFViewer/IIIFViewer.tsx
common/views/components/ImageLink/ImageLink.tsx
common/views/components/ItemLink/ItemLink.tsx
common/views/components/WorkLink/WorkLink.tsx

ref #5939
* People wanting to know when the pagination has been used to navigate
* People wanting to know what position a work was clicked on from
* Labels the IIIFViewer pagination with `viewer/paginator`. 
* Adds the `resultPosition` to the works search result
Ping @taceybadgerbrook for reference.

add source to item pagination

---

common/package.json
common/services/conversion/track.ts
yarn.lock

Analysts not wanting to have non-expiring session IDs.
Sends across a `sessionId` with the conversion event, that changes if there the previously recorded event was more than 30 minutes before the current.
ping @taceybadgerbrook

add segment session

---

catalogue/webapp/pages/download.tsx
catalogue/webapp/pages/image.tsx
catalogue/webapp/pages/item.tsx
catalogue/webapp/pages/work.tsx
catalogue/webapp/pages/works.tsx

People wanting to know what happened when the API errors
Removes the generic errors message and propagates the error down from the API.
Thanks @alexwlchan for reporting

propegate errors to UI from API

---

common/services/prismic/fetch-links.js

It was reported the promo wasn't coming through.
The fetch links field wasn't filled in.
Ah Prismic.

add event-series.promo to fetch link

---

.buildkite/pipeline.identity.yml

Oopsies - removes the dev branch and adds `master` to stage deployment

fix identity build branches

---

.buildkite/pipeline.identity.yml
.buildkite/pipeline.triggers.yml

Triggers the [ID pipeline](https://buildkite.com/wellcomecollection/experience-identity/) when
* a change has been made to the identity folder
* You force it with a `identity/*` prefix to your branch name
This isn't an end game, as this should build when common changes, but to facilitate the rapid development of Digirati, this will stop the pipeline running whenever there is a change, creating a traffic jam on that pipeline.

trigger identity pipelines with branch names or filepath

---

.buildkite/pipeline.triggers.yml

Seems the builds are running on previous commits. master is running [here](https://github.com/wellcomecollection/wellcomecollection.org/commits/abe5f75c190d3824c8e363aca528a880) - [which you can infer from this](https://buildkite.com/wellcomecollection/experience-identity/builds/42#a8d59441-933a-4211-ba7d-816a4c436a52/121).
Main thing was that the concurrency group running the ID deploy is `experience-deploy`, which it shouldn't be.
This is a bit verbose, but it is the [recommended way of doing this](https://identity.www-stage.wellcomecollection.org/identity). I might have looked into [dynamic pipelines](https://buildkite.com/docs/pipelines/defining-steps#dynamic-pipelines), but I think most of this will become redundant, so it feels Ok.

trigger identity build with build info

---

catalogue/webapp/components/Work/Work.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.tsx
catalogue/webapp/tsconfig.json
common/hooks/useIIIFManifest.ts
common/hooks/useIIIFManifestData.ts
common/tsconfig.json
common/utils/iiif.ts
content/webapp/tsconfig.json
identity/webapp/tsconfig.json
toggles/webapp/tsconfig.json

Devs & perf-people
Consolidating how we use IIIF manifest.
Caching responses so we need not call out each time. Another way to do this would be to cache it on the server side JSON props response, but then we would couple the fetching of the manifest to our application (if wl fails, we fail), which is no good.

consolodate how we use the IIIF manifest of a work

---

common/views/components/Body/Body.tsx

Accidentally made standalone picture slices narrower than they should be here: #5977

standalone should always use Layout12

---

cache/cloudfront_stage.tf
identity/terraform/stack/main.tf

Route requests from www-stage.wellcomecollection.org/identity to the identity service in order to serve the correct pages from that URL.
This change also adds specific CloudFront cache behaviour for the identity URLs.
Note: This change is applied

Add listener path rule and cache behaviour

---

.eslintrc.js
common/babel.js
common/test/setupTests.js
common/utils/numeric.ts
common/views/components/ColorPicker/ColorPicker.tsx
common/views/components/ModalFilters/ModalFilters.tsx
common/views/components/PaletteColorPicker/HueSlider.tsx
common/views/components/PaletteColorPicker/PaletteColorPicker.tsx
common/views/components/PaletteColorPicker/conversions.ts
common/views/components/SearchFiltersDesktop/SearchFiltersDesktop.tsx
common/views/components/SearchFiltersMobile/SearchFiltersMobile.tsx
toggles/webapp/toggles.ts

This is an (arguably) improved UI for colour filtering based on the design [in Zeplin](https://zpl.io/V48dnYJ).
The library we're using doesn't export the plumbing that we want so I replicated it (ish) which makes the UI much better suited to our needs (and doesn't cause CSS import problems).
It looks like this:

Palette-based color picker

---

common/utils/routes.ts
common/utils/utility-types.ts
common/views/components/ItemLink/ItemLink.tsx

When you create the return type of a function, because of [type compatibility](https://www.typescriptlang.org/docs/handbook/type-compatibility.html) - the returned object of the method only needs to be compatible.
That means the below works:
```TS
type Return = { required: string, optional?: string }
type Func = () => Return
const f: Func = () => ({ required: 'yes', saywat: 'wat' })
// because
console.info(f().required) // 'yes'
console.info(f().optional) // undefined
console.info(f().saywat) // Error
```
This utility method converts optional (`?`) parameters in the undefinable ones.
Let's go again
```ts
type ModifiedReturn = OptionalToUndefined<{ required: string, optional?: string }>
type Func = () => ModifiedReturn
const g: Func = () => ({ required: 'yes', saywat: 'wat' }) // Error, …
```

add OptionalToUndefined

---

identity/webapp/.env.dist
identity/webapp/docker-compose.yaml
identity/webapp/package.json
identity/webapp/src/frontend/index.tsx
identity/webapp/src/router.ts
identity/webapp/src/utility/prefix.ts
identity/webapp/src/utility/typed-router.ts
identity/webapp/webpack.frontend.js
yarn.lock

This PR will allow the identity webapp to live at a path prefix when deployed. This is probably `account` so that the app is accessed at wellcome.org/account, but it can be any value, set by the environment variable `CONTEXT_PATH`, and this env var can be undefined in local development.
Duplicate of #6031

Identity app path prefix

---

catalogue/webapp/pages/_app.tsx
common/utils/gtag.ts
common/views/pages/_app.tsx
content/webapp/pages/_app.js
content/webapp/pages/_app.tsx

Adds web vitals to GA (our v4 property).
[Nabbed straight from here](https://github.com/GoogleChrome/web-vitals#send-the-results-to-google-analytics)

add sending webvitals to GA

---

catalogue/webapp/components/Work/Work.tsx
common/views/components/ArchiveHeader/ArchiveHeader.tsx

references #5944
Adds reference number to the archive page header

add reference number to header and rename component

---

common/utils/filters.ts
common/views/components/ModalMoreFilters/ModalMoreFilters.tsx
common/views/components/SearchFiltersDesktop/SearchFiltersDesktop.tsx

Ability to sort aggregation filter on the front end in alphabetical or count.
closes #6057

sort by alphabetical order for languages

---

common/views/components/WorkHeader/WorkHeader.tsx

references #5944
Adds reference number to the WorkHeader - we'll probably want to consolidate WorkHeader and ArchiveHeader into a single component at some point soon (The ArchiveHeader is really a remnant of prototyping).

add reference to WorkHeader

---

identity/webapp/src/frontend/index.tsx
identity/webapp/src/routes/index.ts

Previously, pages in the identity app were not rendering at all on the staging environment due to the context path not being provided at build time. This change makes sure that the webpack bundle does not need the environment variable at build time, by providing it from the Koa server at runtime instead

Ensure identity app does not require context path at buildtime

---

identity/webapp/src/utility/api-caller.ts
identity/webapp/src/utility/configure-auth0.ts

Replaces a call to Auth0's `/userinfo` with a call to the API's `/users/me` endpoint.
Removes an Axios instance made unnecessary by the above, and tidies up some logic in the API caller

Fetch user info from API not Auth0

---

common/views/components/SearchFiltersMobile/SearchFiltersMobile.tsx

Should we change the default `type` in our button component? It risks breaking other things but I think this bug is pretty common, and will keep happening otherwise (I know I never think to change it when I add a button).

Stop filters button from submitting form on mobile

---

common/views/components/GifVideo/GifVideo.js

Safari doesn't show the initial video frame. This wasn't a problem with auto playing videos, but now we have non autoplaying videos it is.
This uses the [Media Fragments](https://www.w3.org/TR/media-frags/) #t= in the src, which results in Safari downloading the first frame

ensure Safari preloads initial frame of video

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
common/views/components/WorkHeader/WorkHeader.tsx

Implements spacing change to works header (point 9 from [Zeplin file](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/60255798189e8faf9f378f12) 
Before:
After:

reduce space under WorkHeader

---

identity/terraform/locals.tf
identity/webapp/src/config.ts
identity/webapp/src/routes/auth.ts

Users logging out.
Making the URL they are redirected to upon logout configurable on a per-deployment basis.

Supply logout redirect URL to identity from terraform

---

common/model/labels.js
common/model/labels.ts
common/views/components/EventPromo/EventPromo.js
common/views/components/Label/Label.js
common/views/components/LabelsList/LabelsList.js

Making the 'Online' indicator that can be on Event cards into a `Label` component, instead of its own snowflake.

Use the LabelsList component for the Online indicator on EventPromos

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx

…because it's being handled in the 'Where to find it' section
Fixes #5555

Don't include locationOfWork in remainingNotes

---

common/views/components/SearchForm/SearchForm.tsx

A misunderstanding on portals.
Tests to follow as I am writing the e2e tests which would capture this.

use portal sortOrder in form submit

---

common/utils/string.ts

Examples we have where this creates issues is `Electronic books` and `Electronic Books` in genres.
Uppercase is completely valid, so we leave it.

don't lowercase generated HTML IDs

---

catalogue/webapp/pages/images.tsx
common/model/catalogue.ts
common/services/catalogue/filters.ts
common/services/catalogue/ts_api.ts
common/views/components/SearchFiltersDesktop/SearchFiltersDesktop.tsx

Nice and easy to add thanks to @jamesgorrie's work in https://github.com/wellcomecollection/wellcomecollection.org/pull/6101

Expose the license filter on image search

---

prismic-model/js/parts/article-body.js
prismic-model/json/articles.json

Adds a contributor field alongside the incorrectly spelt contibutor field.
Once this change is made in Prismic it will allow us to update the application code and then the old field can be removed.

add contributor field

---

common/services/prismic/articles.js

Once the changes in #6176 have been applied in Prismic, we can query the correctly spelt field

query the correct field

---

prismic-model/README.md
prismic-model/js/parts/article-body.js
prismic-model/json/articles.json

#6177 is now [deployed to master](https://buildkite.com/wellcomecollection/experience-deploy-stage/builds/154):
So it is safe to remove the contibutor field from Prismic
Also, have updated the readme for creating/updating custom-types

Remove misspelled field

---

catalogue/webapp/components/WorksSearchResults/WorksSearchResults.tsx
catalogue/webapp/pages/works.tsx
common/views/components/CheckboxRadio/CheckboxRadio.tsx
common/views/components/PageLayout/PageLayout.tsx
common/views/components/Paginator/Paginator.tsx
common/views/components/SearchFiltersDesktop/SearchFiltersDesktop.tsx
playwright/contexts.ts
playwright/test/contexts.ts
playwright/test/roles.ts
playwright/test/view-items.test.ts
playwright/test/works-search.test.ts
playwright/user-stories/images-search.md
prismic-model/json/interpretation-types.json

All of us
Takes the user stories that were collectively written and starts to encode them in tests.
I plan to expand on the user stories and tests to work on how we deal with #6144 as @jamieparkinson and I have experienced, some issues there would really have benefited from some tests to record context that we think has been lost to  ⏳ .
The process is also helping massively with thinking about where the interface is not as intrinsic as it can be. One specific piece being writing selectors that are more user centric, and is something I would like to see continued when writing tests (See [playwright](https://playwright.dev/docs/selectors#prioritize-user-facing-attributes) and [testing library](https://testing-library.com/docs/) docs advocating for this). Where I haven't been able to do …

add user story tests

---

common/views/components/IIIFViewer/parts/IIIFCanvasThumbnail.tsx
toggles/webapp/toggles.ts

Uses a toggle to display canvas labels alongside image numbers on the grid view of the viewer to help inform discussion.

show canvas labels if toggle is on

---

prismic-model/js/parts/article-body.js
prismic-model/json/articles.json

- Makes the initial prismic changes required for this #6191
- Aim is to replace the repeatable text fields with a single text field
- This adds the single text field
- Once this change is made and the application code is changed, we'll be able to remove the repeatable fields

add single text field for discussion transcript

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
common/model/catalogue.ts
common/utils/works.ts
toggles/webapp/toggles.ts

Related to #6137 
People who have access to third-party resources that we link to.
Adding an 'Online resources' section in the 'Where to find it' section of a work page. If an item location has a `title`, I've added that with a linked 'view resource' suffix. If (instead) it has `linkText`, I've linked directly to that (`linktText` tends e.g. to be something like 'View resource').
Getting this information on the page in some form so that we can get a feel for what it tends to look like. This should then help inform the direction the design moves in.
~I've put them as inline links in a `<details>` element initially because there can be quite a lot of them and they can be very similar (identical). Although perhaps it'd be more useful to see them always displayed so's to get a quicker idea of …

Add links to third party item resources behind a toggle

---

prismic-model/js/parts/article-body.js
prismic-model/json/articles.json

Now #6219 is deployed we can remove the redundant part of the model

remove repeatable block from discussion slice

---

content/webapp/pages/page.js

There's definitely a better way to do this, but the template itself needs so much work so I was looking for the least moving parts solution.

use site sections to get text for breadcrumb

---

common/views/components/Body/CollectionsStaticContent.tsx

https://user-images.githubusercontent.com/31692/110918688-59414880-8313-11eb-9327-8d21246d5f67.mov
Fixes links taking you through to the `works` / `images` pages when you're on `collections`.

disable search form links on collections

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx

1. Remove 'Online resources' heading
2. Put each link on its own line (as a list item)
3. Upcase 'View resource' when it appears after a title
Relates to #6137

Tweak third-party resource link styles

---

common/package.json
common/test/utils/iiif.test.ts
common/utils/iiif.ts
common/views/components/ViewerStructuresPrototype/ViewerStructuresPrototype.tsx
yarn.lock

When lots of the works were digitised, structures with multiple pages such as table of contents were created individually, rather than as a single structure with a range of pages.
This means we will often display repetitive links to the essentially the same thing.
Until we can improve the data at source, this function groups structures that have the same label attached to consecutive pages into a single structure.
Before:
After:

Repetitive structures

---

.buildkite/pipeline.identity.yml
.wellcome_project

Developers who want to see the identity-admin deployed.
Updating the build system to deploy to ECR/ECS in the identity account for the identity-admin app.
Depends: https://github.com/wellcomecollection/wellcomecollection.org/pull/6250

Deploy the identity-admin app

---

catalogue/webapp/components/WorkDetails/OnlineResources.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.tsx

Relates to #6137 
This splits the `onlineResources` into two lists – 1. the first three items and 2. the remaining items – then hides the second 'remaining' ones behind a toggle button.
When the items aren't visible, clicking the button will reveal the remaining items and give keyboard focus to the first 'remaining' item.
When the items are visible, clicking the button will hide the 'remaining' items and keep focus on the clicked button.

Show more/less in the onlineResourcesPrototype

---

infrastructure/modules/alb/main.tf

Folk who never want a nice secure connection always
Redirecting any http requests that come into our load balancers to https.

Redirect http listener to https

---

catalogue/webapp/pages/image.tsx

The `images` template doesn't currently include the new viewer iterations (we found out in testing). This puts it behind the same toggles as it is behind for `works`.

Add new item viewer for single images in image.tsx

---

common/views/components/IIIFViewerPrototype/GridViewerPrototype.tsx

People who expect to arrive at the beginning of a page when selecting a thumbnail from the grid view.
That.

Go to start of page from clicking grid thumb

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx

The `onlineResources` toggle is incorrectly hiding the 'Where to find it section' if it's turned on.

Show where to find it section if onlineResources toggle is on

---

catalogue/webapp/components/WorkDetails/OnlineResources.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.tsx

> In this instance, we have two types of digital location: an Online resource and a IIIF Presentation manifest. We currently assume both types are "Available online" - which in a sense they are. However, there's no guarantee that the resource link is a link to a digital surrogate (equivalent to the IIIF Presentation manifest). In this case, the online resource is supplementary information about the item, rather than a digital copy of the item itself.
This pr keeps the IIIF manifest information as 'Available online', and relables any `onlineResources` links as 'Online resources'.

Fix online resources label/position

---

common/views/components/MainViewerPrototype/MainViewerPrototype.tsx

Addresses #5097 
I'm not sure this is a good idea – the maths and the slightly niche conditionals make me feel not that great. But it's a way to address the issue of landscape images appearing low in the viewport.
On first render, and only if the image is landscape:
1. We calculate the rendered height of the image
2. We half the difference between that and the square item it sits inside
3. We scroll that distance, putting the top of the image at the top of the viewport

Center landscape

---

common/hooks/useWindowSize.ts
common/views/components/SearchFilters/SearchFilters.tsx
common/views/themes/default.ts

Ref: #6268
Moves the jank to the mobile version as when we use CSS there are as twice as many form elements in the DOM, which causes loads of issues.

move jank on search form to mobile version

---

common/views/components/AppContext/AppContext.tsx
common/views/components/IIIFViewer/parts/NoScriptViewer.tsx
common/views/components/IIIFViewerPrototype/IIIFViewerPrototype.tsx

Adding a no-js version of the viewer for browsers that are on our 'basic' support list (Opera mini and IE11). This is determined by whether the browser has `IntersectionObserver`, and it's now getting set in the `AppContext` (similar to `isEnhanced`).

Add NoScriptViewer for Basic support browsers

---

common/views/components/IIIFViewerPrototype/IIIFViewerPrototype.tsx
package.json
yarn.lock

`ResizeObserver` isn't an experimental browser feature anymore, but it hasn't made it into TypeScript core yet. After reading[ this issue](https://github.com/Microsoft/TypeScript/issues/28502) it isn't clear to me why it hasn't. It's presumably round the corner, but while we're waiting for that, this adds the types from DefinitelyTyped.

Add resize-observer-types

---

common/views/components/ZoomedImagePrototype/ZoomedImagePrototype.tsx

[We got a buggy zoom report](https://wellcome.slack.com/archives/C294K7D5M/p1617900591317600?thread_ts=1617887047.306500&cid=C294K7D5M).
Positioning of the zoom container solves it.

Fix zoom weirdness

---

common/services/prismic/fetch-links.js
common/views/components/LabelsList/LabelsList.js
content/webapp/pages/page.js

Rendering project formats in the page header for consistency with how we treat other formats.
Fixes #6202

Project format

---

playwright/test/view-items.test.ts

The test for deep zoom visibility is failing intermittently. I think I need to `await` visibility of the selector.

Wait for visibility

---

catalogue/webapp/pages/item.tsx

Fixes #6339
Having `dangerouslySetInnerHTML` within a `<p>` where the first part of the `authService.description` contained a `<p>` itself would result in invalid markup which the browser would fail to render. Putting it in a `<div>` instead means any nested elements should be valid.

Use div for dangerouslySetInnerHTML

---

cache/terraform.tf
catalogue/terraform/data.tf
catalogue/terraform/stack/data.tf
content/terraform/data.tf
content/terraform/stack/data.tf
identity-admin/terraform/data.tf
identity/terraform/data.tf
identity/terraform/stack/data.tf
preview/terraform/data.tf

This isn’t “for” anyone; it’s just a general good practice we’ve adopted elsewhere in the platform. Fetching remote state doesn’t require anything more than read-only permissions, so that’s what we use.
I have some Python bits I can cobble together to find them:
```python
import os
from pprint import pprint
import hcl
def get_file_paths_under(root):
"""Generates the paths to every file under ``root``."""
if not os.path.isdir(root):
raise ValueError(f"Cannot find files under non-existent directory: {root!r}")
for dirpath, _, filenames in os.walk(root):
for f in filenames:
if os.path.isfile(os.path.join(dirpath, f)):
yield os.path.join(dirpath, f)
for f in get_file_paths_under("."):
if not f.endswith(".tf"):
continue
if ".terraform" in f:
continue
if "node_modules" in f:
continue
try:
tf = …
```

Use read-only roles to access remote Terraform state

---

catalogue/webapp/pages/image.tsx

To help people know why they might be getting an error / a work isn't available.

use image API error in response

---

common/utils/iiif.ts

Fixes #6374 
It's not guaranteed that a structure will have anything in its `canvases` array, and we were (reasonably, I think) assuming that they would.

Check structure has canvases

---

common/views/components/FeaturedCard/FeaturedCard.js

☝️  @GarethOrmerod pointed out that the spacing for the `FeaturedCard` should be bigger.

Spacing tweak for FeaturedCard

---

catalogue/webapp/pages/item.tsx
common/hooks/useIIIFManifestData.ts
common/model/iiif.ts
common/utils/iiif.ts
common/views/components/IIIFViewer/parts/IIIFCanvasThumbnail.tsx
common/views/components/IIIFViewer/parts/MainViewer.tsx
common/views/components/IIIFViewerPrototype/IIIFCanvasThumbnailPrototype.tsx
common/views/components/MainViewerPrototype/MainViewerPrototype.tsx
toggles/webapp/toggles.ts

As per [this conversation](https://wellcome.slack.com/archives/CBT40CMKQ/p1618218551345200)
We need to make sure the wc.org /work and /item pages function correctly when the iiif presentation manifests are served from https://iiif.wellcomecollection.org/presentation/v2/<id> rather than http://wellcomelibrary.org/iiif/<id>/manifest
This PR creates a toggle to request the manifests from
http://stage.wellcomelibrary.org/iiif which gets redirected to https://iiif.wellcomecollection.org/presentation/v2/
N.B. The manifests at /v2 are designed to reproduce the slightly off-spec implementation of the current wl.org ones so everything _should_ work. However, I did see a breaking change where manifest.sequences.canvases.thumbnail.service was previously an object and is now an array. This PR also …

Testing new iiif manifest source

---

catalogue/webapp/pages/image.tsx
common/views/components/ArchiveTree/ArchiveTree.tsx

Waiting on #6392 to avoid having to do git magic to revert the change out.
**Before**
**After**

Archive tree padding

---

catalogue/webapp/pages/image.tsx

There's a deeper underlaying issue around how images are merged that we need to solve, but we should definitely not be redirecting to dead-ends.

don't redirect to deadend from images path

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
catalogue/webapp/services/catalogue/works.ts
common/model/catalogue.ts
common/utils/works.ts
common/views/components/IIIFViewer/parts/IIIFCanvasThumbnail.tsx
common/views/components/ItemViewerContext/ItemViewerContext.tsx
toggles/webapp/toggles.ts

Relates to #6247
First pass at getting holdings data onto the work page behind a toggle (no styling or UX):
Also, removes redundant showCanvasLabels toggle and related code

Display holdings

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx

We were sending people to the library website for items with an accessCondition of restricted and they were getting redirected straight back. This stops that happening and this is what they'll see on the item page instead:
N.B. we are also sending people to the library website for items with an accessCondition of permission-required, we'll need to stop doing this too, but want to get an example to test.

don’t use library link for restricted items

---

common/views/components/ImageViewerPrototype/ImageViewerPrototype.tsx

Relates to #6291
People using the item viewer.
Using the default cursor style on the images in the main pane.
We are currently using the `pointer` style, because the image is clickable (launching deep zoom), but this potentially adds more confusion around what affordance is present on the image.

Don't use a pointer on the item viewer images

---

identity-admin/terraform/locals.tf

Anyone who wants to be able to sign into the Account Administration System.
The Terraform which drives the Account Administration System has a hardcoded `stage` in the path to one of its environment variables. This should instead reflect the target environment.

Fixing hardcoded 'stage' in path to parameter

---

identity-admin/terraform/stack/main.tf
infrastructure/modules/alb_listener_rule/main.tf
infrastructure/modules/alb_listener_rule/variables.tf

Folk who want to be able to redirect HTTP -> HTTPS (and specifically for the identity-admin app do that).
Allowing services creating http listeners using a tf module to optionally pass in one for HTTP - if you don't the HTTP -> HTTPS redirect takes precedence.
The identity-admin app is being served out of the identity AWS account and does not have CloudFront to perform the HTTP -> HTTP redirect as the other services here do (the DNS account-admin.wellcomecollection.org record points direct at the ALB). Hence the need to make this change.
Note: This PR is deployed

Make http listener optional in listener module

---

common/icons/components/SinglePage.js
common/icons/index.js
common/icons/svgs/single_page.svg
common/views/components/IIIFViewerPrototype/ViewerTopBarPrototype.tsx
common/views/components/ToolbarSegmentedControl/ToolbarSegmentedControl.tsx

Closes #6147 
Users of of the item viewer
Giving them a new control for toggling between detail/grid view that is more consistent with the rest of the ui.
The intention is to a/b test the presence/absence of labels alongside the icons in the control, but we decided to wait until the a/b test for label presence on the sidebar toggle was complete.

Use new segmented control in viewer

---

cache/edge_lambdas/src/redirects.ts

Splits out and adds missing vanity redirects. We could share code to make this automatic, but creating deps into the cache lambdas didn't feel worth it.

redirect all vanity URLs

---

identity-admin/webapp/package.json
yarn.lock

It was updating to next 10.1, which we should do, but it will need a few fixes, so locking this for now.
This has affected other apps as it's within the workspaces of the root package.

fix version of nextjs in ID admin

---

identity/webapp/src/frontend/Registration/Registration.style.ts
identity/webapp/src/frontend/Registration/Registration.test.tsx
identity/webapp/src/frontend/Registration/Registration.tsx

Unlike Chrome, Firefox and Safari prioritise a link's href over its onclick action

WS-185 Make Cancel action a button not a link

---

catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.tsx

References #6470
- removes the library link for items on the open shelves (as well as items that are restricted, by-appointment or on-exhibition)
- makes  other changes to match the latest Zeplin designs:
- [Access-conditions-longest-example](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/6098f2aa205ca4143eec0ab5)
- [Closed stores](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/6098edbb10d91d112fa91a7d)
- [On Order item_6May](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/6098e92c50c3c0111a306b3a)
- [open shelves + shelfmark](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/6098e78b47fd4610d32247e6)
- [digital and physical item](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/6098e1a684a9503b87c392a8)
- [open shelves …

Remove open shelves library link

---

common/views/components/AudioPlayer/AudioPlayer.tsx
common/views/components/MediaAnnotations/MediaAnnotations.tsx
common/views/components/VideoPlayer/VideoPlayer.tsx

References: wellcomecollection/platform#5032
Specifically [this comment](https://github.com/wellcomecollection/platform/issues/5032#issuecomment-832476907) 
People of want to be able to read the transcript of an audio file
Adding a links to the transcript underneath the audio player

Audio transcript link

---

.buildkite/pipeline.e2e.yml
playwright/test/contexts.ts
playwright/test/helpers/urls.ts

Folk who want to run the playwright tests with stage APIs
Allowing the catalogue-api smoke tests to ensure the current prod deploy of the wellcomecollection.org site will work with what's in stage - thereby indicating it is safe to deploy catalogue-api stage to prod.

Add variable to playwright tests to use stage apis

---

common/services/prismic/exhibitions.js
content/webapp/components/Exhibition/Exhibition.js
content/webapp/pages/exhibition.js

Closes #6435 and closes #6461
A `page` in Prismic can now take an `exhibition` as a parent. An exhibition then queries for this related content at the point of getting the exhibition itself (in the same way we do for Seasons).
We now have two ways of doing related content in exhibitions: 1. attaching it to the exhibition itself (the old way), 2. attaching the exhibition to the child (this new way).
I think if we're happy with the new way, we should go back and update the way the old related content works for exhibitions, too, so that content editors only have to know one system for relating things to each other, and that we don't have a one-off way of doing it in the code.

Exhibition related pages

---

cache/edge_lambdas/src/toggler.ts
common/views/components/IIIFViewer/ViewerTopBar.tsx
toggles/webapp/toggles.ts

A/B test results showed marginally more usage of the show/hide sidebar toggle button when it didn't have a label associated with it. That coupled with the design decision that it would look better without means that we can remove the (visible) labels.
I've also aligned the chevrons to the right of the sidebar area, which was the original design intention that I missed, but we didn't want to change while the a/b test was running (I didn't think this warranted a separate test). [See this thread in Slack for more context](https://wellcome.slack.com/archives/C294K7D5M/p1619695001071600).

Remove chevron labels

---

common/views/components/IIIFViewer/ViewerTopBar.tsx

When changing the alignment of the show/hide sidebar chevrons to be right-aligned, I didn't account for the fact the mobile view uses the same button, but needs to be left-aligned.
__Before:__
__After:__

Fix mobile button alignment

---

common/views/components/IIIFViewer/IIIFViewer.tsx
common/views/components/IIIFViewer/ViewerBottomBar.tsx
common/views/components/IIIFViewer/ViewerTopBar.tsx
playwright/test/selectors/item.ts
playwright/test/view-items.test.ts

Fixes #6506 
- Using the `ToolbarSegmentedControl` component for the page/grid toggle
- Hiding this component when the item info is visible (where it could be confusing, since you can't see the result until you close the info)

Mobile view toolbar segmented control

---

common/services/prismic/parsers.js

For #6461 
People who want SoundCloud embeds to work whether or not they are from a private playlist.
Making the player show up.

Allow for SoundCloud embeds without secret tokens

---

playwright/test/contexts.ts
playwright/test/work.test.ts
playwright/test/workPrototype.test.ts

- Replicates the work tests with the showPhysicalItems toggle turned on (and the required changes to make them pass)
- adds a test for the presence of status

Items prototype tests

---

catalogue/terraform/stack/main.tf
catalogue/webapp/pages/api/works/items.ts
catalogue/webapp/services/catalogue/common.ts
catalogue/webapp/types/environment.d.ts
common/api-routes-middleware/withToggles.ts

- Adds middleware to make Toggles available to the API routes
- uses the stagingApi toggle to switch between  using the catalogue api staging and prod versions

Catalogue stage tests

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
catalogue/webapp/components/WorkDetailsProperty/WorkDetailsProperty.tsx
catalogue/webapp/components/WorkDetailsText/WorkDetailsText.tsx

References #6247
Improves the display of the holdings data based on [zeplin designs](https://app.zeplin.io/project/5aab926b4b6efde01259e959/dashboard?q=holdings)
@GarethOrmerod @DominiqueMarshall We [still need designs for links to digital resources](https://github.com/wellcomecollection/wellcomecollection.org/issues/6247#issuecomment-839934016)

layout changes for holdings

---

catalogue/terraform/stack/main.tf

Trying to apply the new listener path causes errors, e.g. Error creating LB Listener Rule: PriorityInUse: Priority '49994' is currently in use
I _was_ trying to change the priorities of the works_data_listener rules at the same time so, I could use  49996 for the api rule
Instead, this uses a higher priority instead (49998), but since they max out at 49999 is there a better way to do this?

change priority of api_path_listener

---

catalogue/terraform/stack/main.tf

Priority 49998, I tried [here](https://github.com/wellcomecollection/wellcomecollection.org/pull/6519) was also already in use (forgot to check what the rules for the content app were), so I couldn't deploy the change

change listener priority

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx

Fixes wellcomecollection/platform#5177
Displays access conditions for digital items below license info
This does cause a strange spacing bug, which I've spent far too long trying to resolve, so thought I would [raise as a separate issue](https://github.com/wellcomecollection/wellcomecollection.org/issues/6516).

Access conditions digital

---

common/services/prismic/html-serializers.js
common/views/themes/typography.ts

CSS specificity used to favour our `.no-margin` selector over the `.spaced-text * + *` selector because of the source order. But that has changed now we're using `styled-components` to do typography (in the `GlobalStyle` component).
Updating the `spaced-text` selector to not apply to `no-margin` solves the issue.

Use not selector to prevent * + * spacing

---

common/styles/base/_layout.scss
common/styles/content.scss
common/styles/critical.scss
common/styles/works.scss
common/views/components/SectionHeader/SectionHeader.js
common/views/themes/config.ts
common/views/themes/default.ts
common/views/themes/mixins.ts
common/views/themes/root-scope-classes.ts
common/views/themes/utility-classes.ts

Moving our utility classes out of Sass into TypeScript. ~We had a concept of `tweakpoints` (component-level breakpoints) that I deliberately overlooked in order to get to this point, but I'll need to address that before this can be merged~. This PR isn't removing the Sass mixins yet, so the tweakpoints in use (only in the `_header.scss` file) aren't affected by this work.

Js root scope classes

---

catalogue/webapp/components/Work/Work.tsx
common/hooks/useIIIFManifestData.ts
common/views/components/ManifestContext/ManifestContext.js
common/views/components/WorkHeader/WorkHeader.tsx

Fixes bug reported by Natalie:
"I'm seeing something odd with volumes, looking at https://wellcomecollection.org/works/ysmqsfhg
When I first go to that work there's no "6 volumes online" beneath the 'Books' and 'Online' labels.
I view the online work then go back to works page, and the "6 volumes online" has appeared.
Why isn't that information about the volumes showing when I first go to the works page? How can we make it show there on the first view? Thanks."
- We use a hook to get this data when a component mounts. 
- We were tracking the id of works we'd already made requests for, to prevent duplicate requests.
- However, in cases where the request was pending we didn't wait for it to finish before returning the data from the hook.

Volumes bug

---

common/views/themes/base/icons.ts

☝️ 
These were broken in the port from Sass to TypeScript.
__Before__
__After__

Fix icon colour classes

---

common/services/prismic/html-serializers.js
common/views/themes/typography.ts
common/views/themes/utility-classes.ts

Adding `:not(.no-margin)` [here](https://github.com/wellcomecollection/wellcomecollection.org/pull/6525) made the selector too specific, such that it won over the `li + li` selector (so e.g. the bulleted lists on [this page](https://wellcomecollection.org/pages/YDo-nxMAACkAMBKl) are now too spread out).
I could think of four options
1. make the `.no-margin` class `!important`
2. add the `:not(.no-margin)` to all other combinant selectors
3. use a `style` tag on the element where the original issue was spotted
4. use a styled-component for the tag where the original issue was spotted
I don't _hate_ the idea of `1.` because if you don't want no margin, then the class really shouldn't be on there. `2.` seems like it would get us into trouble and be harder to maintain. `3.` and `4.` are …

Use !important instead of not selector

---

catalogue/webapp/components/WorkDetailsProperty/WorkDetailsProperty.tsx

[This change](https://github.com/wellcomecollection/wellcomecollection.org/pull/6566) resulted in spacing issues for the inline headings, which this PR fixes
Before:
After:

fix spacing for inline heading

---

content/webapp/pages/homepage.js

We had a `no-margin` class on the header that was previously being overridden by some margin space classes that we put on the top and bottom. Now the `no-margin` class does what we'd expect as a result of #6566 it makes it apparent that the class doesn't belong on this element at all.
__Before__
__After__

Remove unwanted no-margin class from page header

---

catalogue/webapp/components/WorkDetails/OnlineResources.tsx
common/views/components/ExpandableList/ExpandableList.tsx

The ExpandableList and OnlineResource components focus their button when the page loads and they shouldn't. This fixes that.
N.B. Would be good to make it possible to use the ExpandableList component inside the OnlineResource component. It's not so straight forward because of having links inside the list for the latter and how focus is handled in that case.

don’t focus button on first render

---

common/services/prismic/parsers.js

There is so much work needed in this bit of the codebase, I didn't think coming up with a more robust check was worth it.
This checks to see if there is an attached doc, if not, move on.

only parse contact slice if there is an attached document

---

common/views/components/Modal/Modal.tsx

Scrollers
Allows them to scroll once they return to a page that had a modal open.
e.g. 
- visit https://wellcomecollection.org/works/z8e3hfkn
- use "View" button
- use "Take me back to the item page" link
- try scrolling 😞

unlock scroll when modal is unmounted

---

common/utils/iiif.ts

We were only looking for the first authService in the iiifManifest, which assumed all images had the same conditions.
This meant when we had an item with a mixture of 'restricted' and 'open with advisory' images, the [whole item was being treated as restricted](https://wellcome.slack.com/archives/C8X9YKM5X/p1623244527029200), if that was the first authService we found.
We can only handle showing one authService message in the viewer, so this PR uses the first on that isn't the restricted one, if there is a mix.
This is ok as the restricted image won't show in the viewer. Instead the user sees the following:
On thumbnails:
For the main image:

handle items that have a mix of authServices

---

common/views/components/FindUs/FindUs.tsx

People who want the FindUs section in the Footer and on the /visit-us page to be aligned with the content above.
Doing that.

Remove unwanted no-margin class

---

common/views/components/ButtonInline/ButtonInline.tsx
common/views/components/ButtonInlineLink/ButtonInlineLink.tsx
common/views/components/ButtonOutlined/ButtonOutlined.tsx
common/views/components/ButtonOutlinedLink/ButtonOutlinedLink.tsx
common/views/components/ButtonSolid/ButtonSolid.tsx
common/views/components/ButtonSolidLink/ButtonSolidLink.tsx
common/views/components/CheckboxRadio/CheckboxRadio.tsx
common/views/components/GlobalContextProvider/GlobalContextProvider.tsx
common/views/components/IIIFViewer/ViewerSidebar.tsx
common/views/components/IIIFViewer/ViewerTopBar.tsx
common/views/components/Label/Label.tsx
common/views/components/MessageBar/MessageBar.js
common/views/components/SearchFiltersDesktop/SearchFiltersDesktop.tsx
common/views/components/Tags/Tags.tsx
common/views/components/styled/AlignFont.tsx
common/views/pages/_app-deprecated.js
common/views/pages/_app.tsx
common/views/themes/config.ts
common/views/themes/default.ts
common/views/themes/typography.ts

People looking at using roman/bold weight of Helvetica Neue behind a toggle
Changing the way link styling works (using a combination of `text-decoration-underline`, `text-underline-offset` and `text-decoration-color`) to prevent larger gaps that appear as a result of using `border-bottom` on the webfont when Helvetica isn't available as a system font.
Also allowing the toggles to be accessible within the `<GlobalStyle />`
The webfont has some extra space above each character, causing text in buttons and alongside icons to appear too low down. I've added an `AlignFont` component to apply an eye-balled amount of negative `translateY` to compensate. I think the ideal solution would be to apply the required [ascent-override](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/ascent-ov …

Helvetica regular toggle update

---

common/views/components/PageLayoutDeprecated/PageLayoutDeprecated.js

People who want to be able to log in to their library membership account from the `/collections` page.
Allowing them to do so, behind the `login` toggle.

Add login to /collections page

---

playwright/test/helpers/urls.ts
playwright/test/landing-pages.test.ts

Devs who want confidence that the top-level pages are going to render.
Adding a test for the response status code of each page.

Add tests for top-level landing pages response

---

common/views/pages/_app-deprecated.js
common/views/pages/_app.tsx
common/views/themes/typography.ts
common/views/themes/utility-classes.ts
toggles/webapp/toggles.ts

The recent Helvetica weight changes highlighted the fact that `black` in our code is currently `#010101`, whereas @GarethOrmerod has been designing with a black of `#121212`. This is a fairly subtle change, but potentially improves the reading experience for body copy.
Unfortunately it's not _quite_ enough to override the `black` value in `theme.colors`, because there are a couple of instances where it is used in `GlobalStyles`. I don't think it's too much to work it this way though.
What is currently called `viewerBlack` is what Gareth is proposing as the new black for use everywhere. If, after looking at these changes behind the toggle we're happy to go ahead with them, then we should rename `viewerBlack` to `black`.

Make 'black' the same as 'viewerBlack' behind a newBlack toggle

---

identity/webapp/src/frontend/components/PageWrapper.tsx
identity/webapp/src/routes/assets/index.html.ts

Adds the main navigation to the identity app pages so users can navigate to the rest of the site
Before: 
After:
Also adds favicons:

Account navigation

---

content/webapp/pages/homepage.js

Editors who want to control the homepage
We previosuly had a card that was for the reopneing of the building. It now features our main season. We'd like this functionality to continue being used post-reopening-building-toggles.
Fixes https://github.com/wellcomecollection/wellcomecollection.org/issues/6591
From dev machine

allow cards on homepage with or without building reopening toggle

---

playwright/test/landing-pages.test.ts

Folk who want simple, reliable and accurate e2e tests
On each landing page check for some obvious content rather than a response code. This fixes a bug where the e2e tests could fail if they got a non 200 status code, but the page would load correctly.

Check landing pages for some simple content

---

prismic-model/js/articles.js
prismic-model/js/books.js
prismic-model/js/events.js
prismic-model/js/exhibitions.js
prismic-model/json/articles.json
prismic-model/json/books.json
prismic-model/json/events.json
prismic-model/json/exhibitions.json

Part of #6633
People who want parity between the models stored in this repo and those in prismic.io
Adding the missing `parents` relationship to `articles`, `books`, `events` and `exhibitions`.

Prismic model parents

---

catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx

People who want more meaningful information about item access.
Using the access method from the api, instead of the status.

Use access method when it's available

---

catalogue/webapp/.env.production
content/webapp/.env.production

People who want to be able to login from the `/collections` page, which is served from within the `content` app.
Making a request to the correct url (adding `account` as per [this equivalent commit in the catalogue app](https://github.com/wellcomecollection/wellcomecollection.org/commit/1266748bd2411f8588d9036eddc249ed75fa6515)).

Add production CONTEXT_PATH to Next content app

---

.buildkite/pipeline.e2e-prod.yml
.buildkite/pipeline.e2e-stage.yml
.buildkite/pipeline.e2e.yml

Developers who want e2e tests to be less flaky.
This change enables auto-retrying failed e2e tests in CI (https://buildkite.com/docs/pipelines/command-step#retry-attributes). The nature of these tests is that they are quite heavyweight (running a headless browser),  which can mean that sometimes they fail waiting to complete. This tests is a partial mitigation in that it will hide flakiness beneath a certain level - we may want to look at the tests themselves to resolve flakiness also.
This fix mitigates the problem of test flakiness but does not resolve it.

Auto-retry e2e tests

---

common/views/components/ArchiveTree/ArchiveTree.tsx

Add bottom padding to ArchiveTree styled link

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx

People who want consistent UI across works.
Moving the 'Where to find it' section to the penultimate slice on the page, and ensuring Holdings appear above Where to find it if they're present.

Move Where to find it

---

common/views/components/ContentPage/ContentPage.tsx

People who want to read the whole of the first paragraph of a story.
Letting them do that.
__Before__
__After__

Revert part of 83bfc2 to show first paragraph of stories

---

catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx
toggles/webapp/toggles.ts

People who want physical information about items to be able to be released sooner.
Moving the (less ready) item status information behind a separate toggle.

Use separate toggle for displaying item status info

---

playwright/test/workPrototype.test.ts

people who want the tests to pass
Turning on the showItemStatus toggle for the test, so that when we look for the status is is there

turn on showItemStatus toggle for test

---

common/views/components/ContentPage/ContentPage.tsx

https://github.com/wellcomecollection/wellcomecollection.org/pull/6658 was a bit over-enthusiastic - while it (correctly) reduced the space between the bottom of the collections sections and the newsletter promo, it removed too much elsewhere:
Whether the component underneath the sections has its own spacing is inconsistent, so the easiest fix for this was to live with the large-ish spacing of the newsletter promo (ie how it was before https://github.com/wellcomecollection/wellcomecollection.org/pull/6658)

Put some spacing back in

---

common/views/components/Modal/Modal.tsx
common/views/components/ModalMoreFilters/ModalMoreFilters.tsx

Fixes #6457
People who like things in a modal window to stay contained within the modal window.
Preventing them from falling out of the bottom.
__Before__
__After__

Don't let anything out of the modal

---

common/views/pages/_document.tsx

Fixes #6546
Having discussed this with Sarah Parry from the Digital Accessibility Centre, it seems that having the id for the back to top link on the html element is what is causing the issues with screen readers. She suggested moving the id to an element inside the body, so that's what this PR does.

add id for anchor to element inside the body

---

catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx
playwright/test/workPrototype.test.ts
toggles/webapp/toggles.ts

People who want to figure out what to display about physical items.
Putting everything in its own column to see where the gaps are/what is redundant/what can be collated.
This was the agreed direction post design review – all of this is behind the `showPhysicalItems` toggle. This PR also removes the `showItemStatus` toggle (won't be required in its current form).

Add more  discrete data to physical item table

---

common/views/components/SearchFilters/SearchFilters.tsx

Resolves https://github.com/wellcomecollection/wellcomecollection.org/issues/6606
This replaces the `if`s with a switch/case because typescript can give us exhaustiveness checks on the union type to prevent this kind of bug

Fix colour filter not showing in active filters

---

catalogue/webapp/pages/works.tsx
common/views/components/SearchForm/SearchForm.tsx

Resolves https://github.com/wellcomecollection/wellcomecollection.org/issues/6170
Think this is all that's required? Means that `/works` now looks like this:

Display results/filters even when there is no query

---

common/views/components/IIIFViewer/ViewerTopBar.tsx

Trying and failing to figure out #6520, but not wanting to leave empty-handed, I picked up the associated nit in Slack about spacing around the `x/ y` (checked with @GarethOrmerod that no space was the way to go).
__Before__
__After__

Remove space after slash in viewer x/y

---

content/webapp/pages/stories.js

Prevent last word of stories header text apearing on its own line

---

common/views/components/SearchFiltersMobile/SearchFiltersMobile.tsx

Fixes #5671 again.
The mobile search filters modal doesn't use the `Modal` component, so doesn't share the fix that went in for this and subsequently introduced this regression.
I think there are a few modal-like things that aren't using the `Modal` component. It would be good to fix that.

Don't focus mobile filters button on first render

---

common/views/components/Modal/Modal.tsx

People who don't want to focus the `More filters` button when they press the escape key.
Checking that a modal window is active before running the `closeOnEscape` handler.
Fixes an issue where pressing the escape key with an expanded image open on the `/images` route will scroll you to the top of the page (to get the `More filters` button – which erroneously gains focus – into view).
This PR _doesn't_ focus the image card that represents the expanded image after you press the escape key. I think this would be the preferred keyboard-accessible behaviour. Will open another PR for it.

Fix closeOnEscape logic

---

common/model/card.js

Fixes #6697 
Series isn't a `format` so doesn't appear in a label for a simple `Card` by default. This feels like a bit of a hack to me – is there a nicer solution?
__Edit:__ I started remodelling the `Card` type to just have `labels`, composed from any labels on the item, preceded by a `format` if present, but it started to feel unnecessarily convoluted.

Add 'Serial' label if item is of type 'series'

---

common/views/components/Paginator/Paginator.tsx
common/views/components/SelectContainer/SelectContainer.js
common/views/themes/config.ts
identity/webapp/src/frontend/MyAccount/MyAccount.style.ts
identity/webapp/src/frontend/Registration/Registration.style.ts

Parts of #6656 
- We have inconsistencies in the shade of green between our old and new palette. Updating all greens to #007868.
- Reduce space between label and select
- I can't see the misalignment of the text inside the select box, so was loathe to give it snowflake 'shift-up-one-pixel' treatment. @GarethOrmerod can you let me know what it needs?

Select green UI bugs

---

catalogue/webapp/pages/works.tsx
common/services/prismic/hardcoded-id.js
common/views/components/PageLayoutDeprecated/PageLayoutDeprecated.js

@taceybadgerbrook 
Adding Hotjar to the ~homepage~[ pages listed below.](https://github.com/wellcomecollection/wellcomecollection.org/pull/6687#issuecomment-870584173)
`homepage.js` is a `Class` component, so the hook can't be used in a straightforward manner. I tried creating an HOC but failed. I also had an abortive attempt at converting it to a `FunctionComponent` with `getServerSideProps` instead of `getInitialProps` – [there is much stricter checking](https://github.com/vercel/next.js/issues/11993#issuecomment-617937409) for the former in development and I didn't think this was the time to solve those problems necessarily, so this seemed like the sensible approach in the end (and can still be backed out of easily at the point we want to stop using Hotjar on the homepage). …

Add hotjar to some pages

---

common/views/components/Contributor/Contributor.js
common/views/components/LinkLabels/LinkLabels.js
common/views/components/LinkLabels/LinkLabels.tsx

Fixes #6552
- Only use a description list when we have a heading to populate the `<dt>`, otherwise uses an unordered list
- also converts the component to typescript

Accessibility info rel

---

cardigan/stories/components/DescriptionList/DescriptionList.stories.mdx
cardigan/stories/components/DescriptionList/DescriptionList.stories.tsx
common/views/components/DescriptionList/DescriptionList.tsx
common/views/components/DescriptionList/README.md

Part of #6695
People who want physical items laid out in a description list instead of a table.
Getting the necessary component into Cardigan before putting any real data into it.

Add DescriptionList to Cardigan

---

.buildkite/pipeline.deploy-stage.yml
common/views/components/DropdownButton/DropdownButton.tsx

Fixes #6550
- focusable elements inside dropdowns have their tabindex set to -1 when hidden to prevent users from being able to reach them
- when the drop down is open and users should be able to reach those elements, we were relying on removing the tabindex property to achieve this.
- this only worked for natively tabbable elements and not for controls such as the colour slider
- setting the tabIndex to 0 for elements fixes this problem

Accessibility colour slider

---

common/views/components/Card/Card.tsx

Resolves #6270 
Setting the `CardBody` padding to the following across all breakpoints:
top: `16px`
right: `16px`
bottom: `32px`
left: `16px`

Set card body padding the same at all breakpoints (more at bottom)

---

common/views/components/Paginator/Paginator.tsx
common/views/components/PaletteColorPicker/PaletteColorPicker.tsx
common/views/components/ResetActiveFilters/ResetActiveFilters.tsx

Fixes #6563 - issues with colour filter
- adds text labels to filter buttons, so we aren't relying on colour to covey meaning and gives screenreaders and voice activation users something to work with
- adds aria role=status to elements that are updated so changes get announced by screenreaders
- adds text alternative for colours shown in active filters
Adding the text labels to the filter buttons has design implications @GarethOrmerod:
Before:
After:

Accessibility colour filter

---

catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx
common/views/components/DescriptionList/DescriptionList.tsx

People who want item-level notes, and access notes
Adding an item-level note as a subheading to the item in the `DefinitionList`, and adding the access note within the `DefinitionList`

Item access notes

---

playwright/test/images.test.ts

The [colour filter is larger now because of this accessibility fix](https://github.com/wellcomecollection/wellcomecollection.org/pull/6722).
This was causing an e2e test to fail as it was covering the first search result link, which needed to be activated.
This PR adds a step to dismiss the colour filter once it's been used.

Fix e2e test

---

common/views/components/IIIFViewer/ViewerSidebar.tsx
common/views/components/LinkLabels/LinkLabels.tsx
playwright/test/contexts.ts
playwright/test/selectors/item.ts
playwright/test/view-items.test.ts

People who don't want to have to navigate back to the work to see the reference number of a work
Show the reference number of the work in the item viewer

add reference number to item viewer

---

common/views/components/Card/Card.tsx
common/views/components/EventPromo/EventPromo.js
common/views/components/StoryPromo/StoryPromo.tsx

People who want the `Part of…` labels to feel attached to the bottom of a card (after the increase in `CardBody` bottom padding in #6723 to address #6270).
Moving them outside the `CardBody` into their own `CardPostBody` component with less padding.
__Before__
__After__

Card post body

---

common/utils/get-focusable-elements.js
common/views/components/DropdownButton/DropdownButton.tsx

Noticed that if the page loads with an active colour filter, then it's possible to navigate to the colour filters via the keyboard when they are not visible, so keyboard focus essentially disappears. 
This stops that from happening

Fix tabbing
