wellcomecollection/wellcomecollection.org

cache/edge_lambdas/toggler.js
common/model/exhibitions.js
common/services/prismic/exhibitions.js
common/views/components/CardGrid/CardGrid.js
common/views/components/ExhibitionPromo/ExhibitionPromo.js

☝️ 
References #4418
Rather than writing several regexes to determine the outcome of `shouldRun`, I settled for having it run everywhere except at `/works/*`.

Add A/B test for short exhibition promo titles

---

common/services/prismic/opening-times.js

check data property exists

---

catalogue/webapp/pages/work.js

added an event key to datalayer.push, so it can be use to trigger GTM tag

add event key

---

catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/pages/work.js
common/views/components/FooterNav/FooterNav.js
common/views/components/Header/Header.js
toggles/webapp/toggles.js

remove proven and unused toggles

---

dash/webapp/pages/toggles.js

I'd forgotten this piece of the jigsaw.

Add short title A/B test to dash

---

catalogue/webapp/pages/works.js
common/views/components/Header/Header.js

- Adding 'Collections' back to the main nav
- Adding the works filter back at `/works`

Remove works janeway toggles

---

catalogue/webapp/pages/work.js

simplify the object being sent and stringify it

stringify object

---

cache/README.md
cache/terraform.tf

Bump edge lambda version numbers

---

cardigan/stories/components/PageHeader.js
common/views/components/PageHeader/README.md

Add PageHeader to Cardy

---

dash/webapp/pages/toggles.js

Allows linking to specific toggles.
⚓️

add toggle IDs to headings to allow linking

---

common/views/components/BetaBar/BetaBar.js

Update beta bar text

---

common/styles/components/_image_viewer.scss
common/views/components/ImageViewer/ImageViewerImage.js

Don't zoom on mousewheel

---

common/views/components/IIIFResponsiveImage/IIIFResponsiveImage.js

If it's a lazy image and the user doesn't have JS, we want to show them something.

Add noscript img for lazy images

---

catalogue/webapp/pages/PROGRESS_NOTES.md

Better expectation management by informing readers that wellcomelibrary.org is still where the entire collection can be searched.
Regular users of library collections
Managing expectations and signposting wellcomelibrary.org as source of truth for now

Text update

---

pa11y/webapp/write-report.js

add item page to pa11y dashboard

---

common/styles/components/_header.scss

Fix logo on IE

---

common/views/components/Images/Images.js

show image credit by default (for non js)

---

cardigan/stories/components/BetaMessage.js
common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js

Does the text change part of #4483

text change April -> July

---

catalogue/webapp/components/SearchForm/SearchForm.js
common/services/catalogue/urls.js

To sync up with the work going on here:
https://github.com/wellcometrust/catalogue/pull/56

add new candidate queries

---

content/webapp/pages/stories.js

change promoted article series

---

cache/edge_lambdas/toggler.js
catalogue/webapp/pages/works.js
dash/webapp/pages/toggles.js

Annoying typos that slipped through.
Also adds the A/Bs to the dash <= this would be nice to automate at some stage.

fix typos and add ab tests to dash

---

catalogue/webapp/pages/PROGRESS_NOTES.md

People reading the BETA/progress
People getting wrong end of the stick in signing up to user panel, so i changed some wording

Updated Progress Notes

---

catalogue/webapp/pages/works.js
toggles/webapp/toggles.js

Add e-sound and e-video worktypes to search behind toggle

---

catalogue/webapp/components/Download/ViewerDownload.js
common/views/components/IIIFViewer/IIIFViewer.js

fixes a couple of styling bugs on the viewer

Viewer styling bugs

---

common/views/components/ImageViewer/ImageViewer.js

only fade the main image if page is actually changing

---

common/views/components/Body/Body.js
common/views/components/GifVideo/GifVideo.js

Aligning the `GifVideo` sizing with what we have for images.

Match caption width to video

---

catalogue/webapp/components/Download/Download.js
catalogue/webapp/components/WorkDetails/WorkDetails.js
common/utils/works.js
common/views/components/License/License.js

References #4326 and #4417
Adds the download option for audio and video files

Adds download option for audio and video content

---

catalogue/webapp/components/Download/ViewerDownload.js

stops links in download box from being tabbable when not visible

---

common/views/components/MoreLink/README.md

Us
Making it clearer what the `moreLink` is for

Updated definition

---

catalogue/webapp/pages/PROGRESS_NOTES.md

Progress notes

---

common/views/components/Footer/Footer.js
common/views/components/Header/Header.js
common/views/components/IIIFViewer/IIIFViewer.js
common/views/components/PageLayout/PageLayout.js

Fixes current accessibility issues highlighted by Pa11y:
error: This link points to a named anchor "footer-nav-1" within the document, but no anchor exists with that name.
Context
<a href="#footer-nav-1" id="header-burger-trigger" class="header__burger-trigger js-header-burger-trigger js-trap-start" aria-label="menu"><span></span><span></span><span...</a>
Selector
#header-burger-trigger
error: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 1.64:1. Recommendation: change background to #757575.
Context
<noscript><div class="IIIFViewer-sc-3zejt...</noscript>
Selector
#main > div:nth-child(2) > noscript

Accessibility fixes

---

common/services/prismic/parsers.js
package.json
prismic-model/js/teams.js
prismic-model/json/teams.json

Allow for markup in the Contact model's subtitle field.

Contact card

---

catalogue/webapp/pages/item.js
common/views/components/Footer/Footer.js
common/views/components/Header/Header.js
common/views/components/IIIFViewer/IIIFViewer.js
common/views/components/PageLayout/PageLayout.js

Fixes header to prevent weird scrolling issues.
Prevents horizontal scrolling on non-js version

Viewer scroll issues

---

cache/edge_lambdas/toggler.js
common/views/components/IIIFViewer/IIIFViewer.js
common/views/components/ImageViewer/ImageViewer.js
dash/webapp/pages/toggles.js

Grouping the controls with the pagination performs significantly better on all metrics, so we're ending the A/B test and going with it.

End grouping controls A/B test (B wins)

---

catalogue/webapp/components/Download/ViewerDownload.js

use display none to hide download options

---

content/webapp/content/visit-us-content.js

Adding new images to the `visit-us` page update

Update visit-us-v2 images

---

content/webapp/content/visit-us-content.js

Updated copy for new visit us page.

Make visit us copy changes

---

content/webapp/app.js
content/webapp/content/visit-us-content.js
content/webapp/pages/visit-us.js

Makes the new visit-us template available at `/visit-us`

Make v2 the new v

---

content/webapp/content/visit-us-content.js

Fix image caption

---

content/webapp/content/visit-us-content.js

s/Our building/Getting around our building
Note: the page title will have to be changed for the page in Prismic also.

Update static content

---

common/views/components/FreeSticker/README.md

Us
Gives clearer indication of where the `FreeSticker` is used. Also squashed a typo.

Clarified use of FreeSticker

---

common/views/components/FacilityPromo/FacilityPromo.js
common/views/components/FooterSocial/FooterSocial.js
content/webapp/pages/whats-on.js

A couple of old horizontal space classes slipped through the net.

Update old horizontal space classes

---

common/views/components/HeaderBackground/HeaderBackground.js

Revert header background to cream

---

common/views/components/Image/Image.js
common/views/components/Images/Images.js
common/views/components/WobblyRow/WobblyRow.js
pa11y/webapp/write-report.js

Fixes error on pa11y dashboard and adds some more pages to test

Pa11y fixes

---

catalogue/webapp/components/SearchForm/SearchForm.js

fixes the errors we were getting

value prop on input should not be null

---

common/views/components/Buttons/Button/Button.js

only apply button type attribute on buttons not links

---

content/webapp/pages/stories.js

change promoted article series to The Ethics of Deception

---

toggles/webapp/toggles.js

make toggle wording clearer

---

catalogue/webapp/components/SearchForm/SearchForm.js
common/views/components/TabNav/TabNav.js
toggles/webapp/toggles.js

Display list of date ranges to allow a user to refine results by a date range

Dates aggregate prototype

---

toggles/webapp/toggles.js

remove unused toggle

---

catalogue/webapp/components/SearchForm/SearchForm.js

Make clear dates button less buttony

---

common/views/components/NewsletterSignup/NewsletterSignup.js

Don't give the newsletter button a `type` of button, so it'll still submit the form.

Fix newsletter button

---

catalogue/webapp/components/SearchForm/SearchForm.js

as requested by @Heesoomoon as a talking point for the user research questions

adds an (unworking) unknown dates link to the prototype

---

common/views/components/SearchResults/SearchResults.js

Space bugfix post `Space` component update.
__Before__
__After__

Fix space in SearchResults

---

common/views/components/TabNav/TabNav.js

…to distinguish between aggregate dates and work type nav.

Add a temporary check for 'Audio/Video'

---

catalogue/webapp/pages/works.js
toggles/webapp/toggles.js

Fixes #4657
Exposes unfiltered search results from the API behind a toggle

Whole catalogue

---

content/webapp/content/visit-us-content.js

so we can serve them at appropriate sizes

use the iiif image server for images

---

catalogue/webapp/services/catalogue/works.js
common/views/components/FindUs/FindUs.js
content/webapp/pages/visit-us.js

Noticed some spacing nastiness on the visit-us page
before:
after:

spacing tweaks

---

docs/rfcs/002-public-feedback-on-search-relevancy/README.md

What information we are trying to collect and some ways and principles around how we might want to do it.
Nothing in concrete, all in the air and open for comment.

Search feedback and testing RFC

---

cache/terraform.tf

Bump up the lamda versions (with corrected role)

---

catalogue/webapp/pages/PROGRESS_NOTES.md

Collections users
Letting them know about recent changes to search

Aug 2019 update

---

.github/ISSUE_TEMPLATE/feature.md

Us
Asks important questions in the issue template

Prompting questions for new features

---

catalogue/webapp/services/catalogue/works.js

Show 25 results per page for works search

---

common/views/pages/_app.js

Remove the extra letter spacing behind the Helvetica Regular toggle

---

cardigan/yarn.lock

update packages in cardigan

---

catalogue/webapp/pages/works.js

Don't show works filter on landing page

---

common/views/components/ExhibitionsAndEvents/ExhibitionsAndEvents.js

Move Being Human to the top of the homepgae

---

common/views/components/FilterDrawerExplore/FilterDrawerExplore.js

As agreed with @GarethOrmerod and @Heesoomoon

Re-style grouped work types ('categories') to be more tabby

---

common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
common/views/components/WorkHeader/WorkHeader.js

Make tweaks to multi-manifest work details

---

common/views/components/ExhibitionPromo/ExhibitionPromo.js

Think I've caught them all, now.

Add another bit of space that slipped through the three-types-of-card net

---

common/views/components/NewsletterPromo/NewsletterPromo.js

I missed the small bp Zeplin design first time around.

Newsletter promo tweaks

---

cardigan/stories/components/CompactCard.js

Fix CompactCard

---

cardigan/stories/components/License.js

Fix license info

---

catalogue/webapp/components/SearchForm/SearchForm.js

looks like filters got removed from behind a toggle by accident

put toggle check back

---

cardigan/stories/components/FilterDrawer.js
common/views/components/FilterDrawer/FilterDrawer.js

Removing dummy content and adding an `items` prop – an array of `{|title: string, component: Node|}`.

Prep the filter drawer for real content

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

To be released with https://github.com/wellcometrust/catalogue/pull/183
The fields will be merged, so no data will be lost.

only physical description for works

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

remove single workType label

---

cache/terraform.tf

release the cache

---

content/webapp/pages/books.js
content/webapp/pages/stories.js

text changes from editorial team

---

catalogue/webapp/pages/works.js

Following the work done here: wellcometrust/platform#3863, we need to query with different workTypes in order to surface audio and video

change worktype to query by

---

common/views/components/styled/Space.js
common/views/themes/default.js

Allow us to override responsive spaces (in the same way as for responsive type).

Allow spacing values to be overriden at each breakpoint

---

common/views/components/PopupDialog/PopupDialog.js

Implementing the new space overrides on the `PopupDialog` component.

Add space overrides to PopupDialog

---

catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/pages/work.js
toggles/webapp/toggles.js

References #4661
Displays the new data that's been added to the catalogue API on the works page (behind a toggle)

New catalogue data

---

catalogue/webapp/components/PaletteSimilarityBox/PaletteSimilarityBox.js

🎨 🤖 
🤝 
Update to the palette interface, matching API simplifications

Use new palette API structure 

---

cardigan/stories/components/PopupDialog.js
common/views/components/PopupDialog/PopupDialog.js

Implement font-size overrides for PopupDialog

---

common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js

Restricted images

---

common/utils/convert-image-uri.js

forgot to put all the params back on the image url

don’t forget the url params

---

common/views/components/PopupDialog/PopupDialog.js

Fix popup tabbing better

---

catalogue/webapp/pages/PROGRESS_NOTES.md

update progress notes

---

cardigan/stories/components/Select.js
catalogue/webapp/components/SearchForm/SearchForm.js

Fixes #4817
Simplify language in the relevance sorter

text change

---

catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/pages/works.js
common/views/components/FilterDrawerRefine/FilterDrawerRefine.js

unfiltered search results should bring back non digitised things

---

catalogue/webapp/services/catalogue/works.js

So it comes through on the front end.

include notes

---

catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/components/WorkCard/WorkCard.js
catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/pages/works.js
catalogue/webapp/services/catalogue/works.js
common/services/catalogue/urls.js
common/views/components/CataloguePageLayout/CataloguePageLayout.js
common/views/components/FilterDrawerRefine/FilterDrawerRefine.js
common/views/components/RelevanceRater/RelevanceRater.js
common/views/components/Tracker/Tracker.js
common/views/pages/_app.js

The tracking wasn't sending a track on the first search as it was attached to the rendering of the page, rather than the URL changing.
While going through this and trying the approach of attaching the search event to form submitting, I found some duplicated code that was affecting the way the form was submitted, which I have changed as well. Happy to pull it out if need be, but it was quite buggy.

Fix search tracking

---

common/views/components/Tracker/Tracker.js

I'll try to find a way to be more explicit about the data we track - but for now this will do.

remove isPreview from Tracker

---

common/views/pages/_app.js

The survey has enough participants.
Until we get this component in Prismic (#4819) we'll have to do it like this.

Remove popup dialog

---

content/webapp/pages/stories.js
content/webapp/pages/whats-on.js

Update promoted series and order exhibitions by newest first

Editorial changes

---

cardigan/stories/components/Rating.js
common/views/components/Rating/Rating.js
common/views/components/RelevanceRater/RelevanceRater.js

References #4411
Adds Rating component for use in relevance testing

Rating component

---

common/views/components/Quote/README.md

Experience and Content team
Describes how to use the two quote styles appropriately

Added usage notes to quote component

---

cache/edge_lambdas/toggler.js
catalogue/webapp/pages/works.js

Hello everyone 👋 
This relates to https://github.com/wellcometrust/platform/issues/4010
It is blocked until https://github.com/wellcometrust/catalogue/pull/231 is merged and deployed.

Replace the withNotes test with usingAnd test

---

catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/pages/works.js
common/services/catalogue/search-params.js
common/views/components/FilterDrawerRefine/FilterDrawerRefine.js

Note https://github.com/wellcometrust/wellcomecollection.org/issues/4854
Definitely worth mentioning that toggles should touch as little as possible - worthing thinking of when PRing.

remove unfilteredResults filter except where it is needed

---

common/views/pages/_app.js

Add the pop up back on the site with the new link

Tree test opt in

---

catalogue/webapp/components/StaticWorksContent/StaticWorksContent.js

change search query for quacks

---

common/views/components/Rating/Rating.js
common/views/components/RelevanceRater/RelevanceRater.js

following feedback from Jenn
- remove stars from behind control (just show them)
- remember rating
- styling tweaks

Ratings tweaks

---

cardigan/yarn.lock

es-abstract was unpublished, so breaking the builds:
https://github.com/airbnb/javascript/issues/2104

repackage cardigan due to unpublished packages

---

common/views/pages/_app.js

☝️ 
We've got enough responses.

Take down popup-dialog

---

common/views/components/PopupDialog/PopupDialog.js

Bump popup z-index to clear wobbly line

---

README.md

Developers unfamiliar with developing on `wellcomecollection.org`
Providing simple instructions for how to get started

Add a simple run instruction to README.md

---

router/terraform/humans.txt

let there be humans

---

common/services/prismic/events.js
content/webapp/pages/event.js
prismic-model/js/events.js
prismic-model/json/events.json

Alice made the good point, that they're not all performances, but can be discussions etc - something to bear in mind when remodelling.

s/relaxed performance/relaxed

---

catalogue/webapp/app.js
catalogue/webapp/components/ExpandedImage/ExpandedImage.js
catalogue/webapp/components/ImageCard/ImageCard.js
catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/components/StaticWorksContent/StaticWorksContent.js
catalogue/webapp/pages/images.js
catalogue/webapp/pages/work.js
catalogue/webapp/services/catalogue/works.js
common/services/catalogue/urls.js
common/styles/components/_promo.scss
common/views/components/IIIFImagePreview/IIIFImagePreview.js
common/views/components/Image/Image.js
toggles/webapp/toggles.js

People who want to search primarily for images rather than detailed works.
Providing an easier view into works with the location type `iiif-image`
Resolves https://github.com/wellcometrust/wellcomecollection.org/pull/4898

Image search prototype

---

catalogue/terraform/terraform.tf
catalogue/webapp/components/ExpandedImage/ExpandedImage.js

This is required for #4898 to work - I've also snuck in a CSS fix that I missed in there

Fix images listener rule

---

catalogue/webapp/components/Auth/Auth.js
catalogue/webapp/components/ExpandedImage/ExpandedImage.js
catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/components/WorkItemsStatus/WorkItemsStatus.js
catalogue/webapp/pages/download.js
catalogue/webapp/pages/work.js
catalogue/webapp/services/catalogue/works.js
catalogue/webapp/services/stacks/items.js
catalogue/webapp/services/stacks/requests.js
common/hooks/useAuth.js
common/test/fixtures/catalogueApi/work.js
common/test/utils/works.test.js
common/utils/works.js

Folk who want to see the requests service in production.
Making the display of the requests service non-broken.

Fix requests component display issue

---

common/views/components/IIIFViewer/IIIFViewer.js

viewer topbar styling for iiif-image content

---

common/views/components/IIIFViewer/IIIFViewer.js
common/views/components/IIIFViewer/parts/IIIFCanvasThumbnail.js
common/views/components/IIIFViewer/parts/NoScriptViewer.js
common/views/components/ZoomedImage/ZoomedImage.js

☝️ PR-ing this back into your `viewer-styling` branch in an attempt to avoid too many merge conflicts.

Move NoScriptViewer to its own component

---

cardigan/stories/components/BookPromo.js
cardigan/stories/components/EventSchedule.js
cardigan/stories/components/PageHeader.js
cardigan/stories/components/Promos.js
cardigan/stories/content.js
common/data/facility-promos.js
common/services/data/facility-promos.js
common/services/prismic/parsers.js
common/utils/backgrounds.js
common/views/components/DailyTourPromo/DailyTourPromo.js
common/views/components/VenueHours/VenueHours.js
content/webapp/content/static-books.js
content/webapp/content/visit-us-content.js
content/webapp/pages/homepage.js

updating the hardcoded img urls

update static image urls to use prismic imgix urls

---

cache/terraform.tf

deploy new edge lambda range logic

---

common/views/pages/_app.js

☝️ 
Making way for the next tree test.

Remove editorial survey popup

---

catalogue/webapp/components/SearchForm/SearchForm.js
common/views/components/SelectContainer/README.md
common/views/components/SelectContainer/SelectContainer.js
common/views/components/SelectUncontrolled/README.md
common/views/components/SelectUncontrolled/SelectUncontrolled.js

The rule is that if you have an uncontrolled select, you shouldn't supply a `value` nor `onChange`.
If you want to control a select, you should supply a `value` and `onChange`.
This codifies that.

Default value

---

content/webapp/pages/stories.js

Makes the canonical URL for stories to `/stories`

change stories canonical URL to /stories from /articles

---

catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/pages/works.js
toggles/webapp/toggles.js

Move image search out from behind toggle

---

cache/edge_lambdas/toggler.js
catalogue/webapp/pages/works.js
dash/webapp/pages/toggles.js

Researchers and the data team alike
Makes the scoring tiered approach universal, and adds some enhancements to the test version
ref: https://github.com/wellcometrust/catalogue/pull/331

use InEnglishWithContributors queryType

---

cache/edge_lambdas/toggler.js
cache/terraform.tf
dash/webapp/pages/toggles.js
toggles/webapp/toggles.js

People who want to understand what the toggles do
Makes the english more supreme and with more grammar inserted

use more better English

---

catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/pages/works.js
common/services/catalogue/search-params.js
common/views/components/RadioGroup/RadioGroup.js

People without JS
Me
Makes image search work without JS
Makes me happy as it's slightly more scalable
Fixes #4955

use search param instead of imageSearch

---

content/webapp/pages/stories.js

Move play serial to stories page

---

common/views/components/WobblyEdge/WobblyEdge.js

☝️ (in the abstract, that is just the ramblings of a madman).

Clean up timer when unmounting wobbly edge

---

cache/edge_lambdas/toggler.js
catalogue/webapp/pages/works.js
dash/webapp/pages/toggles.js

See https://github.com/wellcometrust/catalogue/pull/338
Using a new query type.
We will be putting in the work to make this process more smooth in the coming weeks.

use FixedFields queryType

---

.github/ISSUE_TEMPLATE/patch

People creating issues / pull requests and don't find a bug or feature request sufficient to explain what they're doing.
GIves them an option to express that they are making things better, but not fixing a bug or creating a new feature.

Create patch issue template

---

common/views/components/IIIFViewer/IIIFViewer.js
common/views/components/IIIFViewer/parts/GridViewer.js
common/views/components/ViewerTopBar/ViewerTopBar.js
common/views/components/ZoomedImage/ZoomedImage.js

Fix for issues with grid view not quite being entirely shown/hidden when viewer is fullscreen.

Fullscreen height

---

common/views/components/Checkbox/Checkbox.js
common/views/components/NewsletterSignup/NewsletterSignup.js
content/webapp/pages/newsletter.js

References #2703
Layout and text changes to the newsletter signup page
before:
after:

Newsletter signup page

---

common/views/components/NewsletterSignup/NewsletterSignup.js

dotmailer is now dotdigital - updating the url

change url for dotdigital

---

common/views/components/Checkbox/Checkbox.js
common/views/themes/default.js

makes pewter accessible on beige and white

update pewter colour and use for checkbox

---

catalogue/webapp/components/Download/ViewerDownload.js
catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/pages/download.js
common/utils/get-license-info.js
common/views/components/IIIFViewer/IIIFViewer.js

We don't always have humanReadableText, but were assuming we do

Sentry errors

---

catalogue/webapp/components/Download/ViewerDownload.js
catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/pages/download.js
common/utils/get-license-info.js
common/utils/iiif.js

put empty arrays in the data so we can just check the length

---

common/views/components/NewsletterPromo/NewsletterPromo.js

People with old-skool phones
Stops the NewsletterPromo creating a horizontal scrollbar

Only min-width input after medium bp

---

cache/README.md
cache/terraform.tf

Bump edge lambda versions

---

common/views/components/NewsletterPromo/NewsletterPromo.js

Update email placeholder and label

---

common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js

☝️ 
Issue was raised in #4843 but broader CTA conversation is happening in #4529

Don't pluralise single images

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.js
catalogue/webapp/pages/work.js
common/services/catalogue/urls.js
common/views/components/IIIFViewer/IIIFViewer.js

Default to main view instead of grid view

---

preview/terraform/terraform.tf

update tf roles in preview infra

---

common/model/iiif.js
common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
common/views/components/IIIFViewer/IIIFViewer.js
common/views/components/IIIFViewer/parts/NoScriptViewer.js

sometimes the iiifManifest is in a shape we weren't expecting, leading to errors

Fix IIIF sentry errors

---

.gitbook.yml

add gitbook config

---

catalogue/webapp/test/search-params.test.js
common/services/catalogue/search-params.js

Release ephemera

---

common/koa-middleware/withGlobalAlert.js
common/koa-middleware/withOpeningTimes.js

Update globalAlert and opening times every 60 instead of 6 seconds

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.js

use maybeItemLink for link

---

common/data/facility-promos.js

Annoying that it's so manual...

update tour promo to reflect the actual times

---

catalogue/webapp/components/RelatedImages/RelatedImages.js

Related to #4927 ([issue comment](https://github.com/wellcometrust/wellcomecollection.org/issues/4927#issuecomment-584574338))
People who want to know what we mean by 'visually similar'.
Giving them an explainer sentence.

Include visually similar explainer text

---

common/hooks/useFocusTrap.js

Fix event listener incorrectly being added instead of removed

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.js

Relates to #5080 
- Updates the link text
- Links the main image to the `/items` route

Link image and update work page link text

---

common/services/data/facility-promos.js
common/views/components/DailyTourPromo/DailyTourPromo.js

Annoying that you need to do this in so many places

update the daily tour times

---

common/services/data/facility-promos.js
common/views/components/DailyTourPromo/DailyTourPromo.js

Change tour times on facilities promo

---

common/views/components/SearchFilters/SearchFiltersMobile.js

Closes #5086
If there are any filters active, the number of active filters will display within the filters button.

Add active filters count to mobile button

---

common/services/catalogue/api.js

People who want to see asian-manuscripts in the search results
ONLY MERGE ONCE  #5093 HAS BEEN MERGED

release the asian manuscripts

---

common/data/facility-promos.js

Add id to reading room promo

---

cardigan/stories/components/IIIFImagePreview.js
cardigan/stories/components/IIIFPresentationPreview.js
catalogue/webapp/components/DownloadLink/DownloadLink.js
catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/pages/work.js
common/services/catalogue/api.js
common/utils/iiif.js
common/views/components/ExplanatoryText/ExplanatoryText.js
common/views/components/IIIFImagePreview/IIIFImagePreview.js
common/views/components/IIIFImagePreview/README.md
common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
common/views/components/IIIFPresentationPreview/README.md
common/views/components/VideoPlayer/VideoPlayer.js
toggles/webapp/toggles.js

We're not ready to make this available quite yet, until we know how we're going to track the impact it has. 
So reintroducing the the original previews and putting this behind a toggle.

Work 'available online' behind toggle

---

common/utils/iiif.js

check for length of manifests array

---

docs/scenarios/stacks.feature

For product/developers to agree the acceptance criteria for the stacks service.
Providing fundamentals of what to build.

Add stacks feature file

---

common/views/components/Tasl/Tasl.js

People who like their TASL info to be hidden if they have JavaScript.
Hiding their TASL info.

Re-hide TASL if isEnhanced

---

catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/pages/work.js

Peeps who don't like 500s
Fixing the 500s

check for license before trying to render it

---

catalogue/webapp/pages/download.js
common/utils/works.js
common/views/components/IIIFViewer/IIIFViewer.js

updated the DigitalLocationType - showed a couple more places we need to check for the license

Optional license

---

common/__mocks__/catalogue-works-swagger.json
common/jest.config.js
common/package.json
common/services/catalogue/swagger.js
common/test/components/SearchRelevanceBar.test.js
common/test/fixtures/enzyme-helpers.js
common/test/setupTests.js
common/views/components/CataloguePageLayout/CataloguePageLayout.js
common/views/components/SearchRelevanceBar/SearchRelevanceBar.js
flow-typed/npm/enzyme_v3.x.x.js
yarn.lock

People internally who want to give us qualitative feedback on which query is better.
Letting them swap between queries easily so as not to have to fiddle with the toggles etc.
__Behind a toggle__

Query type selector

---

docs/scenarios/stacks.feature

finishing last two features

---

cardigan/terraform/terraform.tf
preview/terraform/cloudfront.tf
preview/terraform/locals.tf
preview/terraform/terraform.tf
preview/terraform/versions.tf

Last bits needing moving to tf0.12

finish tf0.12 upgrade

---

catalogue/webapp/__mocks__/catalogue-work.js

This was meant to be in the other PR, but github was playing up.

add aggregations to work mock

---

common/views/components/InfoBanner/InfoBanner.js
prismic-model/json/events.json
prismic-model/json/global-alert.json

☝️ 
(currently no styles are applied to `h2`s in the `InfoBanner`, and multiple paragraphs aren't spaced apart).

Allow for standard body styling within InfoBanner

---

cache/edge_lambdas/toggler.js
dash/webapp/pages/toggles.js

Remove newsletter A/B from dash

---

cache/edge_lambdas/toggler.js
dash/webapp/pages/toggles.js
toggles/webapp/toggles.js

☝️ 
@taceybadgerbrook this PR doesn't make the A/B test live just yet. That will happen in a second part (hopefully at some point this morning – will let you know).

Promote availableOnline toggle to A/B test

---

.circleci/config.yml
cache/edge_lambdas.tf

Update node version

---

cardigan/.storybook/config.js
cardigan/stories/components/Modal.js
common/views/components/Modal/Modal.js
common/views/components/Modal/README.md

Users
Giving them a modal window which can contain any content (as `children`).
I think there's a chance that this might end up needing to be a bit more configurable (e.g. the width might need to be constrained, the responsive behaviour might want to be changed depending on the circumstances), but I didn't think it made sense to add this potential configurability before we knew how we were going to do it.

Modal component

---

cache/terraform.tf

Bump the edge lamda cache versions

---

content/webapp/content/static-books.js

Update static books on stories landing page

---

catalogue/webapp/pages/api/work.js

Adds an endpoint letting us know if we can render an item from a b number.
This will help us report on things that we can't render that are being viewed on wl.org, which might help inform where we will have issues with the switch over.
It's pretty ephemeral so the codes not that important, but did make me feel as though we could do a little cleaning around how we decide what to render when.

add a function that lets us know if we can render a work

---

.circleci/config.yml

As we're putting the effort into writing them now - let's actually live by them

run common tests in circle

---

.circleci/config.yml

They're recommending we do it, so I am doing it.
https://circleci.com/docs/2.0/build-processing/

upgrade circle to 2.1

---

common/views/components/CookieNotice/CookieNotice.js
common/views/components/PageLayout/PageLayout.js

People who want to know we use cookies
Adds a CookieNotice component as the original one seems to have disappeared...
Cookie notice will disappear for a month once dismissed

Add cookie notice

---

common/views/components/EventsByMonth/EventsByMonth.js
common/views/components/SegmentedControl/SegmentedControl.js
content/webapp/pages/events.js
content/webapp/pages/whats-on.js

stops what's on breaking when there are no events

Fix whats on

---

common/next/next.config.js

Developers who want updated infra
Paves the way to have the new services running alongside the old ones.

Prepare subdomain for infra update

---

content/webapp/pages/stories.js

updated promoted series on stories

---

common/views/components/EventBookingButton/EventBookingButton.js
common/views/components/EventbriteButton/EventbriteButton.js
content/webapp/pages/book.js
content/webapp/pages/event.js

Fixes #5197
Not sure why flow didn't catch these

updating Button props

---

cardigan/stories/components/ResponsiveTable.js
common/views/components/styled/ResponsiveTableREADME.md

Relates to #5193
__Larger screen layout__
__Smaller screen layout__

Add ResponsiveTable component to Cardy

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

☝️ 
Part of the QA on requesting [doc](https://docs.google.com/document/d/1OqgAZ9BsyiqZtcY3ruUHlbSD4UITtr7x1YBBkUmSURQ/edit).

Hide encore link if stacksRequestService is on

---

assets/humans.txt

@DominiqueMarshall @alicerichmond are humans!

Add Dominique and Alice to humans.txt

---

catalogue/webapp/components/Download/Download.js
catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/pages/download.js
common/utils/convert-image-uri.js
common/utils/works.js
common/views/components/IIIFViewer/IIIFViewer.js

Adds pixel dimensions for single image downloads, i.e. works with a iiif-image location

Pixels single image downloads

---

common/views/components/Checkbox/Checkbox.js

Update checkbox in line with new design

---

common/data/facility-promos.js
content/webapp/pages/whats-on.js

Removing inaccurate copy about cafe and shop being open during lockdown

Facility promo urls

---

common/test/components/SearchToolbar.test.js
common/views/components/CataloguePageLayout/CataloguePageLayout.js
common/views/components/SearchFilters/SearchFiltersDesktop.js
common/views/components/SearchToolbar/SearchToolbar.js
toggles/webapp/toggles.js

Decouples searching the entire catalogue toggle from the search toolbar toggle.

remove search toolbar from entire catalogue search toggle

---

catalogue/webapp/pages/works.js
common/views/components/Tracker/Tracker.js

Fixes https://github.com/wellcomecollection/platform/issues/4440

ensure we send a number to the totalResults when tracking 

---

content/webapp/content/static-books.js

This is static on the `/stories` page for now.

Change Rules of Contagion cover

---

catalogue/webapp/pages/works.js
common/views/components/CollectionSearch/CollectionSearch.js
common/views/components/SearchToolbar/SearchToolbar.js
common/views/components/Toggler/Toggler.js

Adds a quick and dirty box behind a toggle to start exposing what we're doing on the API, and start getting the discussions flowing.

add a quick collections search thing so we can see what the API is returning

---

catalogue/webapp/pages/work.js
common/views/components/Collection/Collection.js
common/views/components/CollectionSearch/CollectionSearch.js

Adds a very basic collection tree to the work page behind a toggle to show it at the peer review today.

add basic collection tree to work

---

toggles/webapp/toggles.js

Adds collection search to the toggles page.

add collection search to toggles

---

common/views/components/CollectionSearch/CollectionSearch.js

Otherwise it gets stuck on the first search.
Bah, state.

add query as dep for searching for collections

---

common/views/components/Collection/Collection.js

Adds links from the collection to the works in that collection.
Slight complexity about the work being optional.

add links to works in the collection

---

common/views/components/CheckboxRadio/CheckboxRadio.js

Relates to #4946
Removing hover/focus transitions for consistency ([per suggestion](https://github.com/wellcomecollection/wellcomecollection.org/pull/5260#issuecomment-619995247)).

Remove CheckboxRadio transitions

---

catalogue/webapp/components/SearchForm/SearchForm.js
catalogue/webapp/pages/work.js
catalogue/webapp/pages/works.js
common/views/components/SearchFilters/SearchFilters.js
common/views/components/SearchFilters/SearchFiltersDesktop.js

Add/update SearchFilters Flowtypes

---

common/views/components/Card/Card.js

Enforce the 16:9 image crop for `Card` component

Use 16:9 image crop

---

content/webapp/pages/stories.js

update promoted series on stories

---

catalogue/webapp/pages/item.js
catalogue/webapp/pages/work.js
catalogue/webapp/pages/works.js
catalogue/webapp/services/catalogue/works.js
common/views/components/Collection/Collection.js
common/views/components/CollectionSearch/CollectionSearch.js
toggles/webapp/toggles.js

People testing new features / large API changes
Adds a toggle to change which env of the API the pages use.

add the staging API toggle

---

catalogue/webapp/pages/work.js

People wanting to see that things have been removed
Doesn't 500, 410s. 
https://wellcomecollection.org/works/ka25u4ft

account for API errors on work page

---

catalogue/webapp/components/RequestLocation/RequestLocation.js
common/views/components/ArchiveBreadcrumb/ArchiveBreadcrumb.js

People who want breadcrumbs to work.
Accounting for `work` not necessarily being available.

Don't rely on work being available

---

common/views/components/Footer/Footer.js

Closes #5325
Content changes done in Prismic.

/s/Press/Media office

---

common/views/components/FeaturedCard/FeaturedCard.js
content/webapp/pages/user-panel.js

Prospective user-panel members
Giving them relevant information and a sign up CTA.
__TODO__

User panel

---

content/webapp/pages/user-panel.js

☝️ [as per comment on #5271](https://github.com/wellcomecollection/wellcomecollection.org/issues/5271#issuecomment-653417085)

Update user-panel page copy update

---

content/webapp/pages/user-panel.js

Add airtable info to user panel page

---

common/views/components/ContentPage/ContentPage.js
content/webapp/pages/user-panel.js

Update user-panel image

---

catalogue/webapp/pages/PROGRESS_NOTES.md

Collections users
Informing them of new stuff, and updating the user panel information.

July 2020 update

---

common/views/components/LandingBody/LandingBody.js

fix error - check for promo before rendering it's caption

check for promo

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.js

Hopefully deep-linking to canvases to be added for digitised works, but that will require some pipeline work first

Link to the image page from new image search

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.js

As I've also commented in the code, the way this is done is quite convoluted and not very nice to look at - _but_ hopefully the data it's extracting will be able to come from the API soon, in a more deterministic way which doesn't rely on searching through the array of canvases (!).

Deep link to canvases within digitised works from image search results

---

catalogue/webapp/components/Work/Work.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.js
common/views/components/RelatedArchiveWorks/RelatedArchiveWorks.js
toggles/webapp/toggles.js

Moves improving messaging below prototype content

Move messaging

---

common/views/components/ArchiveTree/ArchiveTree.js

don’t open works in new tab

---

common/services/prismic/events.js
common/test/services/prismic/events.test.js

⬆️ 
For some reason I had this branch sitting around for ages

Adds a test for getting last end time of an event

---

common/views/components/FeaturedCard/FeaturedCard.js

This got lost in a merge conflict somewhere along the line.

Re-do the FeaturedCard shim

---

content/webapp/app.js

Point new [Visit Us Prismic page](https://wellcomecollection.org/landing-pages/XvxzjhQAAJmq1t__) to `/visit-us`.

Update Visit Us vanity url

---

cardigan/stories/components/PageHeader.js
common/views/components/PageHeader/PageHeader.js
content/webapp/pages/book.js

Displays all possible `PageHeader` variants in Cardigan.

Document page headers

---

.circleci/config.yml
common/views/components/PopupDialog/PopupDialog.js
common/views/pages/_app.js

☝️ 
Closes #5405 
__Not to be deployed till 10 August.__

Add DJS survey in PopupDialog

---

common/views/pages/_app.js

text and link changes from marketing team

---

catalogue/webapp/services/catalogue/works.js
common/utils/works.js
common/views/components/ArchiveBreadcrumb/ArchiveBreadcrumb.js
common/views/components/RelatedArchiveWorks/RelatedArchiveWorks.js

Archive breadcrumb with new api

---

catalogue/webapp/services/catalogue/works.js
common/utils/works.js
common/views/components/RelatedArchiveWorks/RelatedArchiveWorks.js

Related archive works with new api

---

common/views/components/ArchiveTree/ArchiveTree.js

only show archive tree on archive works

---

common/views/components/ArchiveBreadcrumb/ArchiveBreadcrumb.js
common/views/components/ArchiveTree/ArchiveTree.js
common/views/components/RelatedArchiveWorks/RelatedArchiveWorks.js
common/views/components/WorkHeader/WorkHeader.js
common/views/components/WorkTitle/WorkTitle.tsx

render html inside work titles

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

☝️ 
__Before__
__After__
As per discussion

Remove overview button

---

common/views/components/ArchiveBreadcrumb/ArchiveBreadcrumb.js

only show breadcrumb on archives

---

common/views/components/ArchiveBreadcrumb/ArchiveBreadcrumb.js

Include the reference nubmer in the WorkTitle to fix spacing

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

Create 'Permanent link' section separate from identifiers

---

common/views/pages/_app.js

Remove PopupDialog for DJS survey

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

Doing this on the frontend for now – order is
1. Arrangement
2. Acquisition
3. Biographical
4. Related material

Order notes fields

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

☝️ 
In keeping with [Zeplin](https://zpl.io/a7MryAW)

Reorder work details

---

common/views/components/SearchFilters/SearchFilters.js
common/views/components/SearchFiltersArchivesPrototype/SearchFiltersArchivesPrototype.tsx

…for user testing with the archives

Add SearchFiltersArchivesPrototype

---

.circleci/config.yml

☝️ 
Trying to fix breaking builds in circle (related to #5436 and #5437).

Use more up-to-date node for edge lambdas

---

common/views/components/SearchFiltersArchivesPrototype/SearchFiltersArchivesPrototype.tsx

Add hacky fix to make sure reset/ok buttons are visible in filters modal

---

catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/pages/download.js
catalogue/webapp/pages/item.js
common/model/iiif.js
common/utils/iiif.js
common/views/components/IIIFViewer/IIIFViewer.js
common/views/components/VideoPlayer/VideoPlayer.js

Disable media downloads

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

People who love images
Show's them images

remove newImages toggle

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

Don't really understand what happened but I think the commit I've cherry picked here is the only thing that got lost in https://github.com/wellcomecollection/wellcomecollection.org/pull/5472/files other than the toggle removal, which was fixed in https://github.com/wellcomecollection/wellcomecollection.org/pull/5497

Reinstate lost changes on WorkDetails

---

catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/components/WorkDetailsSection/WorkDetailsSection.js

put 2 columns back for non archive works

---

common/views/components/DropdownButton/DropdownButton.tsx

only set width if Popper is visible

---

common/services/catalogue/api.js
common/utils/works.js
common/views/components/ArchiveBreadcrumb/ArchiveBreadcrumb.js
common/views/components/ArchiveTree/ArchiveTree.js
common/views/components/WorkHeaderPrototype/WorkHeaderPrototype.tsx

Updates for new api

---

common/model/iiif.js
common/utils/iiif.js

iif manifest service can be a single object or an array of objects

---

common/utils/json-ld.js

check for license property first

---

catalogue/webapp/package.json
common/package.json
yarn.lock

Move next-cookies to common package

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

Anybody searching the codebase for identifier-related code.
Making this comment possible to find.

Fix what looks like a typo: Identifiers/Indentifiers

---

cache/bucket_policy.json
cache/cloudfront_dev.tf
cache/cloudfront_prod.tf
cache/cloudfront_stage.tf
cache/s3.tf
cache/terraform.tf
cardigan/terraform/terraform.tf
dash/terraform/terraform.tf
infrastructure/terraform/ecr.tf
toggles/terraform/terraform.tf

Developers who want better builds.
Updates some infra state to get ready for buildkite.

Consolidate Terraform with buildkite branch

---

.buildkite/pipeline.yml
catalogue/webapp/package.json
content/webapp/package.json

Developers who like camels.
Adding camels 🐫 .

CamelCase deployBundleAnalysis task

---

.buildkite/pipeline.yml
cardigan/Dockerfile
catalogue/Dockerfile
content/Dockerfile

Developers who want faster clearer builds.

Add some comments in Dockerfiles to indicate context, try build parallel

---

toggles/webapp/toggles.js

Turn off hotjar

---

content/webapp/pages/stories.js

Update stories series

---

toggles/webapp/toggles.js

☝️ 
To merge between 9 and 10am tomorrow (2020-09-23).

Switch buildingReopening toggle to true for everyone

---

content/webapp/pages/covid-book-your-ticket.tsx

Remove mention of the shop being open

---

content/webapp/pages/covid-book-your-ticket.tsx
content/webapp/pages/covid-welcome-back.tsx

Covid pages copy/size edits

---

content/webapp/pages/covid-welcome-back.tsx

☝️  as per discussion with @DominiqueMarshall

Add divider before 'Keeping you safe' heading

---

common/views/components/CovidTOC/CovidTOC.tsx
content/webapp/pages/covid-welcome-back.tsx

Covid 'Welcome back' page edits

---

content/webapp/pages/covid-book-your-ticket.tsx
content/webapp/pages/covid-welcome-back.tsx

Remove p tags around uls to make links work right

---

content/webapp/pages/covid-book-your-ticket.tsx

Make copy edits to book-your-ticket page

---

content/webapp/pages/whats-on.js

Remove restaurantCard from whats-on page

---

content/webapp/pages/covid-book-your-ticket.tsx

Add date and link to requesting copy

---

catalogue/webapp/pages/work.tsx
common/model/catalogue.ts

handle more work types

---

common/views/components/ColorPicker/ColorPicker.tsx
common/views/components/SearchFilters/SearchFiltersDesktop.js

Just fixing some leftover bugs on this. A couple of times I saw it totally bork and set the colour to `NaNNaNNaN` but I cannot for the life of me reproduce this, so unfortunately don't think I've fixed that for now...

Colour filter tweaks

---

common/services/catalogue/api.js

People actually wanting to see filtered results
Filters the results

send locationType to API

---

content/webapp/pages/covid-book-your-ticket.tsx

Remove no longer necessary date info

---

common/services/catalogue/api.js

Getting archives to show in search results when we expect them to

change the worktype for archives

---

toggles/webapp/toggles.js

Reorder toggles for screenshotability

---

common/views/components/PageLayout/PageLayout.js
content/webapp/pages/homepage.js
content/webapp/pages/whats-on.js

Strapline update

---

content/webapp/pages/covid-welcome-back.tsx

Update Storing your belongings section

---

common/views/components/SearchFilters/SearchFiltersMobile.js
common/views/components/SearchFiltersArchivesPrototype/SearchFiltersArchivesPrototype.tsx

Adds location filter to mobile (and prototype) filters

---

common/views/components/SearchFilters/SearchFilters.js
common/views/components/SearchFilters/SearchFiltersMobile.js

Adding the number of location filters to the filters button on mobile.

Online in library mobile

---

cache/edge_lambdas/redirects.js
content/webapp/app.js

Sending the google juice to `/collections`.
~~I'm not sure if doing this with Koa is the _right_ way, but it works.~~
__Update__
Now doing this the (right) way we do other redirects.

Redirect 301 from /landing-pages/{collectionsPageId} to /collections

---

catalogue/webapp/components/WorkDetails/WorkDetails.js
common/test/utils/works.test.js
common/utils/works.js

We aren't yet set up to display works that have access conditions on them, so we pass them to the universal viewer on the library site for now.

check for access conditions and link to UV

---

content/webapp/pages/covid-welcome-back.tsx

Add FeaturedImage and edit bullets

---

common/data/facility-promos.js

Update facility promo images

---

content/webapp/pages/covid-book-your-ticket.tsx

☝️ 
Yes, the sooner these pages are in Prismic, the better.

Update book your ticket page copy

---

cache/edge_lambdas/Dockerfile

take out reference to non-existent file

---

common/views/components/DropdownButton/DropdownButton.tsx

Fix DropdownButton in Cardigan

---

content/webapp/pages/covid-book-your-ticket.tsx

Add bullet

---

toggles/webapp/toggles.js

turning on unflitered search and related functionality for all users

---

common/views/components/ArchiveTree/ArchiveTree.js

don’t make api calls for the children of archive items

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

show encore link even when we have a digitised work

---

catalogue/webapp/components/WorkCard/WorkCard.js

render html in WorkCard title

---

.github/ISSUE_TEMPLATE/research.md

Edits connect research with product goal to produce actionable results
Anyone in Digital Engagement who needs research conducted.
Ensuring that metrics and aims of analysis are clearly defined.

Research_issue_template

---

common/views/components/ArchiveTree/ArchiveTree.js

Non js archive tree

---

catalogue/webapp/components/RequestLocation/RequestLocation.js
catalogue/webapp/components/Work/Work.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/test/components/__snapshots__/WorkDetails.test.js.snap
common/hooks/useScreenSize.js
common/hooks/useWindowSize.js
common/test/utils/hooks.test.js
common/test/utils/works.test.js
common/utils/get-focusable-elements.js
common/views/components/ArchiveTree/ArchiveTree.js
common/views/components/Modal/Modal.js
common/views/components/ModalFilters/ModalFilters.tsx
common/views/components/SearchFilters/SearchFilters.js
common/views/components/SearchFilters/SearchFiltersMobile.js

Archive tree small screen

---

common/test/fixtures/components/opening-times.js
common/views/components/FooterOpeningTimes/FooterOpeningTimes.test.js

update test: opening times day is set to a hardcoded date for snapshot

---

.github/ISSUE_TEMPLATE/feature_evaluation.md

This new issue template links analytical outputs to product improvements to produce actionable results. Clarifying metrics and expected results makes for better analysis.
Anyone in Digital Engagement who wants to evaluate the effect of product changes on user behaviour.
Clarifying what the analysis is for helps to identify suitable metrics. Clarifying expected results guards against temptation to tweak analysis to produce desired outcomes.

New_feature_evaluation_issue_template

---

content/webapp/pages/homepage.js

Re-add 'This week' to homepage

---

content/webapp/pages/events.js

Update copy on /events page

---

content/webapp/pages/covid-book-your-ticket.tsx
content/webapp/pages/covid-welcome-back.tsx

Update covid pages copy

---

common/services/prismic/types.ts
common/views/components/InfoBlock/InfoBlock.test.js
common/views/components/InfoBlock/InfoBlock.tsx
common/views/components/InfoBlock/__snapshots__/InfoBlock.test.js.snap

Prevents empty buttons like this from showing up

Only show the ButtonOutlinedLink if there's a url and text

---

.buildkite/pipeline.yml

Devs wanting confidence that things aren't breaking on stage before deploying to prod.
Same as this: https://github.com/wellcomecollection/catalogue/pull/990

add integration pipeline step to build

---

.buildkite/pipeline.yml
docker-compose.yml
updown/webapp/expected-checks.js

Run updown update in CI

---

.buildkite/pipeline.yml
docker-compose.yml
updown/webapp/checks.js
updown/webapp/expected-checks.js
updown/webapp/utils.js

Updown checks 2

---

common/services/prismic/types.ts
common/views/components/ButtonOutlined/ButtonOutlined.tsx
common/views/components/ButtonOutlinedLink/ButtonOutlinedLink.tsx
common/views/components/ButtonSolid/ButtonSolid.tsx
common/views/components/ButtonSolidLink/ButtonSolidLink.tsx

Typescript fixes

---

catalogue/webapp/components/Work/Work.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.js
common/views/components/ModalFilters/ModalFilters.tsx
common/views/components/SearchFilters/SearchFiltersDesktop.js
common/views/components/SearchFilters/SearchFiltersMobile.js
toggles/webapp/toggles.js

Fixes #5626
The default for these toggles has been true since the 12th October, so safe to get rid of them

Redundant toggles

---

cache/terraform.tf

related to work 
#5682 Make reusable system for setting a toggle via the url

update edge_lambda_request_version and edge_lambda_response_version

---

common/views/components/PrototypeSearchFilters/PrototypeSearchFiltersMobile.tsx

☝️ 
Removes 'Dates' filter from behind the images tab, and adds the 'Colours' filter.

Add correct filters for images tab in mobile view

---

common/koa-middleware/tests/withToggles.test.js
common/koa-middleware/withToggles.js

* Update middlewear to allow context to be updated on the first render 
* Update context to also go back to default on first render
* Updated tests

update toggles to allow context to be changed on first time render via qs

---

common/views/components/PrototypeSearchFilters/PrototypeSearchFiltersDesktop.tsx
common/views/components/PrototypeSearchFilters/PrototypeSearchFiltersMobile.tsx

Order should be 'Online' first, 'In the library' second.

Fix ordering of Online/In the library

---

common/views/components/SearchTabs/SearchTabs.tsx

Match text-size/width from searchPrototype wireframe

---

common/views/components/PrototypeSearchFilters/PrototypeSearchFiltersDesktop.tsx
common/views/components/SearchTabs/SearchTabs.tsx

Colour-pick greys from wireframes

---

common/views/components/PrototypeSearchFilters/PrototypeSearchFiltersDesktop.tsx
common/views/components/PrototypeSearchFilters/PrototypeSearchFiltersMobile.tsx

Move the locations filters onto their own line where necessary.

Search prototype ui amends

---

toggles/webapp/toggles.js

remove homepage banner and place the cream banner closure

---

common/views/components/SearchTabs/SearchTabs.tsx

Make explanatory text smaller (again)

---

content/webapp/pages/whats-on.js

Fix no exhibitions

---

catalogue/webapp/components/WorkDetails/WorkDetails.js

For https://github.com/wellcomecollection/platform/issues/4865
I'm on a lousy internet connection so I can't test this locally, but it's pretty simple and 🤞 it should work as these start to appear in the catalogue API. I'll come back and check again once the API is deployed.

Display the ISSN on the work page

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.js
catalogue/webapp/components/VisuallySimilarImagesFromApi/VisuallySimilarImagesFromApi.js
catalogue/webapp/components/Work/Work.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.js
catalogue/webapp/components/WorkSearchResults/WorkSearchResults.js
catalogue/webapp/pages/works.js
catalogue/webapp/test/components/WorkDetails.test.js
common/views/components/ArchiveTree/ArchiveTree.js
common/views/components/CataloguePageLayout/CataloguePageLayout.js
common/views/components/Collection/Collection.js
common/views/components/CollectionSearch/CollectionSearch.js
common/views/components/PrototypeSearchFilters/PrototypeSearchFiltersMobile.tsx
common/views/components/SearchFilters/SearchFilters.js
common/views/components/SearchFilters/SearchFiltersDesktop.js
common/views/components/SearchFilters/SearchFiltersMobile.js
common/views/components/SearchToolbar/SearchToolbar.js
common/views/components/Toggler/Toggler.js
common/views/components/TogglesContext/TogglesContext.ts
common/views/pages/_app.js
content/webapp/pages/homepage.js

TS: TogglesContext

---

common/views/components/AppContext/AppContext.tsx

Convert AppContext to TS

---

cache/cloudfront_prod.tf
cache/cloudfront_stage.tf

add images route to cache

---

package.json

☝️ 
Catch lint errors before we push.

Lint staged ts(x) as well as js

---

common/views/components/CataloguePageLayout/CataloguePageLayout.js

add beta bar back

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx
catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.js

Also converts ExpandedImage to typescript!
Resolves https://github.com/wellcomecollection/wellcomecollection.org/issues/5742

Contributor on image modal

---

catalogue/webapp/components/WorkCard/WorkCard.tsx
catalogue/webapp/components/WorkSearchResults/WorkSearchResults.js

Convert WorkCard to TS

---

catalogue/webapp/components/Work/Work.tsx
common/views/components/MediaObjectBase/MediaObjectBase.tsx
common/views/components/ModalFilters/ModalFilters.tsx
common/views/components/PartNumberIndicator/PartNumberIndicator.tsx

Remove unnecessary Flow comments

---

common/hooks/usePrevious.ts
common/views/components/GlobalInfoBarContext/GlobalInfoBarContext.tsx
common/views/components/InfoBanner/InfoBanner.tsx
common/views/components/PageLayout/PageLayout.js
common/views/pages/_app.js

expose global info bar state

---

toggles/webapp/toggles.js

turn toggle on by default

---

README.md

added command for showing previous releases

---

catalogue/webapp/pages/item.js

don’t add elements with no content

---

common/views/components/PrototypeSearchFilters/PrototypeSearchFiltersDesktop.tsx
common/views/components/SearchTabs/SearchTabs.tsx

Use palette colours for SearchTabs/filters

---

dash/webapp/yarn.lock

Update dash yarn lock

---

common/views/pages/_document.tsx

[A strange set of events](https://github.com/wellcomecollection/wellcomecollection.org/commits/master/common/views/pages/_document.tsx) has led to this being removed.
This puts it back

readd segment include

---

common/views/components/LandingBody/VisitUsStaticContent.tsx

people who don't want to see raw json data on the page

remove stray JSON.stringify

---

catalogue/webapp/components/WorkDetails/WorkDetails.js
common/views/components/WorkHeader/WorkHeader.js

Per feedback in show and tell on Friday.
Part of https://github.com/wellcomecollection/platform/issues/4864

Don't make the list of languages a set of clicky links

---

cache/cloudfront_prod.tf

add next/data route to prod cache

---

prismic-model/js/articles.js
prismic-model/js/events.js
prismic-model/json/articles.json
prismic-model/json/events.json

People who want a single place to add content relationships

move series under content relationships tab

---

cache/cloudfront_prod.tf
cache/cloudfront_stage.tf
common/package.json
common/services/prismic/events.js
content/webapp/package.json
content/webapp/pages/events.js
prismic-model/js/events.js
prismic-model/js/parts/boolean.js
prismic-model/json/events.json
prismic-model/json/places.json
rss/webapp/package.json
yarn.lock

* adds: `isOnline` to events as per #5821 
* adds: `/events?isOnline=true` endpoint

Online events

---

common/hooks/useHotjar.ts

After testing this we needed to use hotjar trigger as archive detail page does not have a url. 
https://help.hotjar.com/hc/en-us/articles/115011867948
We have tested this locally and confirmed with Alice she is getting heat map results.

Horjar HeatMap Archive detail page fix 

---

content/webapp/pages/event.js

Feature video on event page

---

common/services/prismic/article-series.js
prismic-model/js/webcomic-series.js

add comment as to why webcomic-series is deprecated

---

cardigan/Dockerfile
cardigan/package.json
yarn.lock

Turns out when you add `cardigan` to the workspaces you need to add a version or you get a 
> warning Missing version in workspace at "/Users/jamesgorrie/projects/wellcomecollection.org/cardigan", ignoring.
Error, so `yarn install` wasn't working.

add version to cardigan package.json

---

common/views/components/Pagination/Pagination.js
common/views/components/Paginator/Paginator.js

I'll convert these to tsx once the fix is out.

change prop type=>colorScheme in paginator

---

toggles/webapp/toggles.js

Enable new search UI to live

---

seasons/webapp/README.md

Adds a seasons folder that I can add to Vercel and then experiment on.
It felt more open and probable that it might progress into something.
If the context of this isn't clear, ask away.

Spike for seasons

---

catalogue/webapp/components/Download/Download.tsx
catalogue/webapp/components/DownloadLink/DownloadLink.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.tsx
catalogue/webapp/pages/download.tsx
common/model/iiif.js
common/model/next-link-type.ts
common/views/components/IIIFViewer/IIIFViewer.js
common/views/components/VideoPlayer/VideoPlayer.tsx
common/views/components/ViewerTopBar/ViewerTopBar.js

Note to self: Work a little more on how we construct links / routes.

move Download to tsc

---

cardigan/stories/components/BannerCard.js
common/model/articles.js
common/model/articles.ts
common/model/books.js
common/model/books.ts
common/model/events.js
common/model/events.ts
common/model/exhibitions.js
common/model/exhibitions.ts
common/model/seasons.js
common/services/prismic/articles.js
common/services/prismic/books.js
common/services/prismic/events.js
common/services/prismic/exhibitions.js
common/views/components/BannerCard/BannerCard.tsx
common/views/components/BannerCard/README.md
common/views/components/ContentPage/ContentPage.js
common/views/components/DailyTourPromo/DailyTourPromo.js
common/views/components/FeaturedCard/FeaturedCard.js
common/views/components/Label/Label.js
common/views/components/LabelsList/LabelsList.js
content/webapp/components/Exhibition/Exhibition.js
content/webapp/pages/article.js
content/webapp/pages/book.tsx
content/webapp/pages/event.js

relates to #5823
Get's the season promo appearing on it's related content pages

Linked season promo

---

cache/edge_lambdas/redirects.js

redirects for Worry Lines comics

---

common/views/components/BaseTabs/BaseTabs.tsx

Adding prefix to button 
**Issue **
error: Duplicate id attribute value "tab-library-catalogue" found on the web page.
Context
```
<div id="tab-library-catalogue" role="tabpanel" aria-expanded="true" class="BaseTabs__TabPanel-sc-17qe7pr-2 ykSB"><div class="Space-sc-4az8w3-0 S...</div>
Selector
#tab-library-catalogue
error: Duplicate id attribute value "tab-images" found on the web page.
<div id="tab-images" role="tabpanel" hidden="" aria-expanded="false" class="BaseTabs__TabPanel-sc-17qe7pr-2 ykSB"><div class="Space-sc-4az8w3-0 S...</div>
Selector
#tab-images
```

Search tab accessibility issue

---

common/views/components/DropdownButton/DropdownButton.tsx

As we're adding some testing, we're picking up on some fixes.

fix DropdownButton ts problems

---

content/webapp/pages/season.tsx

make sure explore more section shows when it should

---

cache/terraform.tf

Adds new webcomic redirects https://github.com/wellcomecollection/wellcomecollection.org/commit/10452eace82feb4f4eaeb62992338f7808b471e1#diff-74255061993180d579a41c79502079c46c9c256f6c71f7710b918638aa98f1f9

bump cache lambda versions

---

cache/locals.tf
cache/terraform.tf

Me
I always forget where the locals are, so thought moving them to a locals file would stop me wasting valuable seconds.

move locals to locals file in cache TF

---

content/webapp/pages/season.tsx

show 3 items per row

---

cardigan/stories/components/ArchiveTree.js
cardigan/stories/components/Promos.js
common/model/events.js
common/model/events.ts
common/services/prismic/events.js
common/views/components/DailyTourPromo/DailyTourPromo.js
common/views/components/EventPromo/EventPromo.js

References #5765
Adds online indicator to event promos

Event promo online

---

common/views/components/EventPromo/EventPromo.js

fix line length linting issue

---

catalogue/webapp/components/Work/Work.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.tsx
catalogue/webapp/pages/images.tsx
catalogue/webapp/pages/works.tsx
common/views/components/ButtonOutlinedLink/ButtonOutlinedLink.tsx
common/views/components/LandingBody/CollectionsStaticContent.tsx
toggles/webapp/toggles.js

Removes the `searchPrototype` toggle as it's all good and well.

remove search prototype toggle

---

content/webapp/content/static-books.js

change promoted books on stories page

---

catalogue/webapp/pages/item.tsx
common/model/iiif.ts

Gets the clickthrough service working on the viewer again

Fix AuthService type

---

toggles/webapp/toggles.js

ONLY MERGE ONCE #5908 is deployed to prod

set openWithAdvisory toggle default to true

---

toggles/webapp/package.json

Fix Docker build of toggles app

---

common/model/projects.ts
common/services/prismic/link-resolver.js
prismic-model/js/projects.js
prismic-model/json/projects.json

Adds the model for projects to prismic.

add projects to prismic models

---

content/webapp/pages/stories.js

Updates the series on the stories page.

change stories series to The heart of homesickness

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx
catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx
catalogue/webapp/test/e2e/actions/search.ts
catalogue/webapp/test/e2e/selectors/images.ts
catalogue/webapp/test/e2e/selectors/search.ts
catalogue/webapp/test/e2e/works.test.ts
common/text/arial-labels.ts
common/views/components/PrototypeSearchFilters/PrototypeSearchFiltersMobile.tsx
common/views/components/PrototypeSearchForm/PrototypeSearchForm.tsx
common/views/components/SearchForm/SearchForm.js
yarn.lock

* update test selectors
* fix up aria labels
* add arial labels for search form
* update actions in e2e tests

Update aria labels and amends on selectors for e2e

---

.buildkite/pipeline.yml
docker-compose.yml
playwright/Dockerfile
playwright/test/helpers/urls.ts
playwright/test/selectors/search.ts
playwright/test/text/aria-labels.ts
playwright/test/works.test.ts

E2E testers
Dockerisers the e2e tests, allowing us to run them on Buildkite/CI

Playwright tests <=> docker

---

common/services/prismic/pages.js
content/webapp/pages/page.js

display contributors on page template

---

.buildkite/pipeline.yml

As there has been all the necessary fixes done.

bump weco deploy version

---

prismic-model/js/project-formats.js
prismic-model/js/projects.js
prismic-model/json/project-formats.json
prismic-model/json/projects.json

References: #5838
- creating the projects-format type
- adding format to projects type
- adding start and end to projects

Projects model

---

common/views/components/TruncatedText/TruncatedText.tsx

convert TruncatedText to ts

---

catalogue/webapp/components/WorksSearchResult/WorksSearchResult.tsx
catalogue/webapp/services/catalogue/works.ts
toggles/webapp/toggles.ts

We're happy for this to go out - also happy to say that https://github.com/wellcomecollection/wellcomecollection.org/pull/5920 worked really well for finding all the usages of this toggle ✨

Remove toggle for archive context in search results

---

infrastructure/terraform/ecr.tf
infrastructure/terraform/outputs.tf

devs wanting to work on an identity frontend
Adds an ecr image for the identity webapp
ref https://github.com/wellcomecollection/catalogue/issues/1276

create identity ecr image

---

.buildkite/pipeline.deploy-prod.yml
.buildkite/pipeline.deploy-stage.yml

People who don't like too many request errors
Moving away from docker, who likes to tell us [we have made too many requests](https://buildkite.com/wellcomecollection/experience-deploy-prod/builds/10#345a7ef9-ee89-423b-8ec0-4acea32ec93b)

use ecr image for weco-deploy

---

playwright/user-stories/works-search.md

First pass at adding some user stories in.
This first one is from a meeting with  @alicerichmond, @kenoir and  @jtweed.
We hope to synthesise some e2e tests from this.
I will move this to a more appropriately named folder in another PR and amend all the code/build things there to not lose focus on the story.

add searching for works user story

---

.buildkite/pipeline.identity.yml
docker-compose.yml
identity/webapp/pages/_app.tsx
identity/webapp/pages/identity/index.tsx

Add new identity pipeline that builds the new identity app
ref https://github.com/wellcomecollection/catalogue/issues/1276

add ECR container build for identity

---

catalogue/webapp/services/catalogue/works.ts
common/views/components/IIIFViewer/parts/MainViewer.tsx

We fetch the OCR data every time we render the `MainViewer`, which could be 50 times a canvas.
This stops us fetching that so often, leading to MBs of duplicate data not being sent down the pipe.
We could definitely refine this more by sticking it into an API as [this](https://wellcomelibrary.org/iiif/b20086210/contentAsText/22) [13.26kb], only returns this
```
INTRODUCTION COMMENTS ON SOME OF THE MORE IMPORTANT MANUSCRIPTS DESCRIBED IN THIS CATALOGUE A number of the Arabic manuscripts in the Wellcome Collections demand rather more detailed treatment than is possible within the scope of a normal catalogue entry. In order to authenticate the texts and describe them accurately it has often been necessary to make an intensive study of the Wellcome manuscripts with other copies preserved …
```

only fetch OCR data when canvas image changes

---

.buildkite/pipeline.deploy-prod.yml
.buildkite/pipeline.deploy-stage.yml

Staging deploy is hanging on a project name confirmation. This stops that.

add project to build

---

cardigan/stories/components/Discussion.js
common/views/components/Discussion/Discussion.tsx

References #5861
Adds show/hide functionality to transcript

Collapsible transcript

---

common/services/prismic/pages.js

Danny noticed promo cards for books weren't linking properly on the homepage, this fixes that

add bookFields to fetch-links

---

cache/cloudfront_prod.tf
cache/cloudfront_stage.tf
cache/edge_lambdas.tf
cache/locals.tf
cache/terraform.tf
cache/versions.tf

Couldn't work out how to apply this refactor safely so have gone back to duplication for now

Revert/fix TF changes for edge lambdas

---

catalogue/webapp/pages/images.tsx
catalogue/webapp/pages/works.tsx
common/views/components/ModalFilters/ModalFilters.tsx
toggles/webapp/toggles.ts
yarn.lock

This removes the ability to render images from the `works` page, requires https://github.com/wellcomecollection/wellcomecollection.org/pull/6012 to be in action first

Remove images from the works page

---

identity/terraform/locals.tf
identity/terraform/main.tf
identity/terraform/stack/main.tf
identity/terraform/stack/variables.tf

This change updates the identity app infrastructure to hand the correct environment variables and secrets to the task definition for the identity app.
Note: the change is applied.

Include Identity Secrets

---

common/views/components/ItemLink/ItemLink.tsx

The typing should have caught this, but hasn't.
Testing should have caught this but hasn't.
Those PRs will follow soon.

fix item link

---

cache/cloudfront_stage.tf
identity/terraform/locals.tf
identity/terraform/stack/main.tf

Use /account as the path for the identity app.
Note: This is applied.

identity -> account

---

identity/webapp/jest.config.js
identity/webapp/package.json
identity/webapp/src/frontend/Registration/AccountValidated.tsx
identity/webapp/src/routes/auth.ts
identity/webapp/src/routes/index.ts
identity/webapp/src/routes/local/local-auth.ts
identity/webapp/src/utility/prefix.test.ts
identity/webapp/src/utility/prefix.ts
yarn.lock

Add path prefix to all redirects

---

prismic-model/js/pages.js
prismic-model/json/pages.json

Add ability to add a landing page to a page

---

common/utils/utility-types.ts
common/views/components/Body/Body.tsx
common/views/components/ContentPage/ContentPage.tsx
common/views/components/ErrorPage/ErrorPage.js
common/views/components/ImageGallery/ImageGallery.js
content/webapp/components/Exhibition/Exhibition.js
content/webapp/components/Installation/Installation.js
content/webapp/pages/article-series.js
content/webapp/pages/article.js
content/webapp/pages/event-series.js
content/webapp/pages/landing-page.js
content/webapp/pages/page.js
content/webapp/pages/place.js

Content page js to ts and flow Reference

---

catalogue/webapp/pages/item.tsx

Conditionally returns the getServerSideProps on whether there is a `iiif-presentation` or `iiif-image` digital location.
I am going to start encapsulating the rules for this in the tests, as we seems to use a whole array of different rules as to what data we use from where, and without tests it's really hard to tell.

check for iif image digital location on item page

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
catalogue/webapp/pages/works.tsx
common/model/catalogue.ts
common/services/catalogue/routes.js
common/services/catalogue/ts_api.ts
common/services/catalogue/ts_routes.ts
common/test/services/catalogue/routes.test.js
common/utils/filters.ts
common/views/components/Body/CollectionsStaticContent.tsx
common/views/components/ModalMoreFilters/ModalMoreFilters.tsx
common/views/components/ResetActiveFilters/ResetActiveFilters.tsx
common/views/components/SearchFilters/SearchFilters.tsx
common/views/components/SearchFiltersDesktop/SearchFiltersDesktop.tsx
common/views/components/SearchFiltersMobile/SearchFiltersMobile.tsx
common/views/components/SearchForm/SearchForm.tsx
common/views/components/SearchToolbar/SearchToolbar.js

UI multiple contributors for desktop and mobile
Non Javascript
Reset Active Filters update
closes #6065

More Filters:  UI for multiple contributors filters 

---

.github/ISSUE_TEMPLATE/research.md

Produced by Alice and Tacey
This is for anyone opening a research ticket in Github
It helps to structure the work as well as improve readability for anyone who wants to know what the ticket is about.

Combined UR/data analysis

---

common/views/components/CheckboxRadio/CheckboxRadio.tsx
common/views/components/ModalMoreFilters/ModalMoreFilters.tsx
common/views/components/SearchFiltersMobile/SearchFiltersMobile.tsx

* move contributors ordering in mobile and desktop
* update mobile/desktop checkbox ui styling when text is long
* renaming of title text
* overriding styles for checkbox ui

More filters: Bug fixes changes and text changes 

---

catalogue/webapp/components/MultipleManifestList/MultipleManifestList.tsx

add 1 to the manifest link

---

catalogue/webapp/pages/item.tsx

Propagate the manifest through to the paginator

add manifest to paginator props

---

identity/webapp/src/router.ts
identity/webapp/src/routes/api/request-delete.ts

Follows changes in #6107 
Base branch changed for ease of diffing. This will merge to `master`

WS-108 Request account delete endpoint

---

playwright/test/selectors/works.ts

Fixes the tests. We're rewriting these anywho.

remove role from heading selector in test

---

package.json

I always forget what the command is as it's named something that it isn't.

don't call compiling linting

---

common/views/components/Body/Body.tsx

fix spacing under anchor links

---

cache/.terraform.lock.hcl
catalogue/webapp/components/MultipleManifestList/MultipleManifestList.tsx
catalogue/webapp/pages/item.tsx
common/text/arial-labels.ts
common/views/components/IIIFViewer/IIIFViewer.tsx
common/views/components/ItemLink/ItemLink.tsx
common/views/components/ViewerTopBar/ViewerTopBar.tsx
playwright/contexts.ts
playwright/package.json
playwright/test/helpers/urls.ts
playwright/test/roles.ts
playwright/test/text/aria-labels.ts
playwright/test/view-items.test.ts
playwright/user-stories/view-items.md
playwright/user-stories/works-search.md
playwright/yarn.lock

In the light of having a bug when having released the new manifest links, we now have a user story for it, and some e2e tests.
I would like to follow this pattern for when we're updating the viewer as the view has got complex enough now to have to need tests to make sure we capture what is expected.

add user story for multiple manifests

---

common/views/components/CheckboxRadio/CheckboxRadio.tsx

Top aligns checkboxes
**before**
**after**

top align checkboxes

---

README.md

Changed the name to be consistent with everything else.

update build URL

---

identity/webapp/src/routes/auth.ts

Users who would like to end their session.
Additionally ends their session in Auth0, making sure they are prompted for login again next time they view the page.

Logout user from Auth0 during session logout

---

playwright/test/view-items.test.ts

I'll need to rewrite the tests to make sure we account for the mobile version as the interface is different.
This is to just fix the builds for now.

Run view item integration tests on desktop only

---

toggles/webapp/toggles.ts

turn on more filters toggle

---

common/views/components/EventPromo/EventPromo.js
common/views/components/EventScheduleItem/EventScheduleItem.js
common/views/components/Label/Label.js
common/views/components/LabelsList/LabelsList.js
common/views/components/MediaObjectBase/MediaObjectBase.tsx

Addresses 5 of 6 UI tasks on #5956

Card tweaks

---

common/views/components/SearchTabs/SearchTabs.tsx
playwright/test/view-items.test.ts

Hopefully makes the test less flakey

wait for selector and then check visibility on items test

---

common/views/components/Card/Card.tsx

Re-add titles

---

catalogue/webapp/components/WorkDetailsTags/WorkDetailsTags.tsx
common/views/components/Tags/Tags.tsx

Fixes #5943 
**Before**
**After**

remove separator from contributor roles

---

common/model/articles.ts
common/model/editorial-series.js
common/model/editorial-series.ts
common/views/components/StoryPromo/StoryPromo.tsx
content/webapp/pages/stories.js

Convert StoryPromo to TS

---

catalogue/webapp/components/Download/Download.tsx
catalogue/webapp/components/DownloadLink/DownloadLink.tsx
catalogue/webapp/middleware/withQueryType.js
common/model/iiif.ts
common/services/conversion/track.ts
common/utils/iiif.ts
common/utils/works.ts
common/views/components/SearchFiltersDesktop/SearchFiltersDesktop.tsx
common/views/components/VideoPlayer/VideoPlayer.tsx

Annoyingly I thought I had done this as part of [this PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/6127/files)
ref: https://github.com/wellcomecollection/wellcomecollection.org/issues/6147

add tracking to download

---

common/services/prismic/articles.js

Use `contibutor` typo in graph query

---

identity/webapp/package.json
identity/webapp/src/frontend/Registration/AccountCreated.tsx
identity/webapp/src/frontend/Registration/OldRegistration.tsx
identity/webapp/src/frontend/Registration/PageWrapper.tsx
identity/webapp/src/frontend/Registration/Registration.style.ts
identity/webapp/src/frontend/Registration/Registration.test.tsx
identity/webapp/src/frontend/Registration/Registration.tsx
identity/webapp/src/frontend/Registration/useRegisterUser.ts
identity/webapp/src/frontend/index.tsx
identity/webapp/src/frontend/jest-setup.ts
identity/webapp/src/frontend/mocks/handlers.ts
identity/webapp/src/frontend/mocks/server.ts
identity/webapp/src/routes/index.ts
yarn.lock

[Desktop screenshot](https://user-images.githubusercontent.com/1347511/109546338-f7d2db80-7ac1-11eb-8352-3b2f94f7bd73.png)
[Mobile screenshot (simulated)](https://user-images.githubusercontent.com/1347511/109546421-1638d700-7ac2-11eb-86fd-09ee8beb7c2f.png)

WS-161 Rebuild registration UI

---

common/views/components/Tags/Tags.tsx

Picked up while doing a bit of refactoring

use linkprops on tagtype

---

cardigan/stories/components/SegmentedControl.js
common/views/components/SegmentedControl/README.md

☝️ 
Don't know why it wasn't there already.

Add SegmentedControl to Cardigan

---

common/views/components/ImagesLink/ImagesLink.tsx

Tests! I can't wait for these damn tests.

fix images link

---

playwright/test/actions/images.ts
playwright/test/selectors/images.ts
playwright/test/selectors/search.ts
playwright/test/works.test.ts

Fixes some e2e selectors.
Makes me realise that some of these aren't using accessible selectors (the colour picker doesn't offer anything I can see immediately)
Another PR dropping soon to help make the tests reflect this.

fix filters and colour picker selectors in e2e tests

---

common/views/components/TitledTextList/TitledTextList.tsx

So that it aligns left with the rest of the text

remove padding from TitleTextList

---

common/views/components/BaseTabs/BaseTabs.tsx
common/views/components/ButtonSolid/ButtonSolid.tsx
common/views/components/SearchForm/SearchForm.tsx
common/views/components/SearchTabs/SearchTabs.tsx
common/views/components/TextInput/TextInput.tsx

Implements design changes to search (points 2,3 and 4) from [Zeplin file](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/60255798189e8faf9f378f12)
Before:
After:

Search tweaks

---

.buildkite/pipeline.deploy-prod.yml
.buildkite/pipeline.deploy-stage.yml

Ref #6141 
These are now controlled in buildkite.

remove build notifications

---

common/views/components/Modal/Modal.test.js
common/views/components/Modal/Modal.tsx
common/views/components/ModalMoreFilters/ModalMoreFilters.tsx
common/views/components/SearchFiltersDesktop/SearchFiltersDesktop.tsx
playwright/package.json
playwright/test/search-form.test.ts
playwright/test/works-search.test.ts
playwright/yarn.lock

* Removes the `submit` `type`  from the close button of the modal that was causing it to be focussed once you submitted a form
* Adds a test to ensure the input is still focussed once you've submitted the form
* renamed some variables in the modal to help me have more clarity on what was going on
https://user-images.githubusercontent.com/31692/110490852-9c6ba380-80e8-11eb-9af7-fb2cc20b02ec.mov
ref #6144

Only 1 submit button for search form

---

common/services/catalogue/filters.ts

put workType filter before dates filter

---

common/services/prismic/articles.js
common/services/prismic/parsers.js
common/views/components/Body/Body.tsx
common/views/components/Discussion/Discussion.tsx

Fixes #6191
replacing the repeatable fields in the discussion slice with a single text field
References #6216

Podcast changes

---

cache/cloudfront_prod.tf
cache/cloudfront_stage.tf
cache/edge_lambdas/src/redirects.ts
catalogue/webapp/pages/images.tsx
common/model/catalogue.ts
common/services/catalogue/api.js
common/services/catalogue/filters.ts
common/services/catalogue/ts_api.ts
common/views/components/ImagesLink/ImagesLink.tsx

Add image genres & contributors filters

---

common/views/components/ViewerSidebarPrototype/ViewerSidebarPrototype.tsx
common/views/components/ViewerStructuresPrototype/ViewerStructuresPrototype.tsx

Highlighting the selected heading in the sidebar if you're on the relevant page.

Highlight sidebar section

---

common/views/components/IIIFViewerPrototype/IIIFViewerPrototype.tsx

Allow downloads to be visible above thumbnail grid

---

common/views/components/IIIFViewerPrototype/IIIFViewerPrototype.tsx

Use the ImageViewer if the item has an imageUrl

---

common/views/components/IIIFViewerPrototype/GridViewerPrototype.tsx
common/views/components/IIIFViewerPrototype/IIIFCanvasThumbnailPrototype.tsx
common/views/components/IIIFViewerPrototype/IIIFViewerPrototype.tsx

Closes #6243
Bumping up the thumbnails in the grid view:

Larger thumbs

---

identity-admin/terraform/.terraform.lock.hcl
identity-admin/terraform/data.tf
identity-admin/terraform/locals.tf
identity-admin/terraform/main.tf
identity-admin/terraform/provider.tf
identity-admin/terraform/stack/main.tf
identity-admin/terraform/stack/variables.tf
identity-admin/terraform/terraform.tf
infrastructure/identity/dns.tf

Developers who want to see the identity-admin deployed.
Providing infrastructure in the identity account to deploy the identity-admin app.
**Note**: This is deployed
Depends: https://github.com/wellcomecollection/wellcomecollection.org/pull/6249

Setup identity-admin app

---

identity/webapp/src/frontend/Registration/AccountCreated.tsx
identity/webapp/src/frontend/Registration/PasswordInput.tsx
identity/webapp/src/frontend/Registration/Registration.style.ts
identity/webapp/src/frontend/Registration/Registration.test.tsx
identity/webapp/src/frontend/Registration/Registration.tsx
identity/webapp/src/frontend/components/Form.style.ts
identity/webapp/src/frontend/components/PasswordInput/PasswordInput.style.ts
identity/webapp/src/frontend/components/PasswordInput/PasswordInput.tsx
identity/webapp/src/frontend/components/PasswordInput/PasswordRules.tsx
identity/webapp/src/frontend/components/PasswordInput/index.ts
identity/webapp/src/frontend/jest-setup.ts

WS-168 Registration UI tweaks

---

common/views/components/ResetActiveFilters/ResetActiveFilters.tsx

only show the color filter reset if it has a value

---

common/services/catalogue/filters.ts
yarn.lock

Fixes https://github.com/wellcomecollection/wellcomecollection.org/issues/6239

changes filters order

---

common/views/components/IIIFViewerPrototype/IIIFCanvasThumbnailPrototype.tsx

don’t request invalid thumb url

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
catalogue/webapp/components/WorkDetailsTags/WorkDetailsTags.tsx
common/views/components/Tags/Tags.tsx

add separators back to workdetailstags except for contributors

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx
catalogue/webapp/components/MultipleManifestList/MultipleManifestList.tsx
common/text/aria-labels.ts
common/views/components/IIIFSearchWithin/IIIFSearchWithin.tsx
common/views/components/ModalMoreFilters/ModalMoreFilters.tsx
common/views/components/SearchFiltersMobile/SearchFiltersMobile.tsx
common/views/components/SearchForm/SearchForm.tsx
common/views/components/ViewerSidebarPrototype/ViewerSidebarPrototype.tsx

1. Move search out of accordion closes #6280
2. Reword 'Additional information' closes #6281

Make design amends after user testing

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
toggles/webapp/toggles.ts

Move online resources out from behind toggle

---

catalogue/webapp/pages/works.tsx
common/model/catalogue.ts
common/services/catalogue/filters.ts
common/test/fixtures/catalogueApi/works-aggregations.ts
yarn.lock

This comes after [these changes](https://github.com/wellcomecollection/catalogue/pull/1518) due to [this documentation](https://github.com/wellcomecollection/docs/blob/master/adr/api_faceting.md)

Use updated API facet names

---

playwright/user-stories/view-items.md

References #6273
Starting to flesh out some user stories

add some user stories

---

common/services/catalogue/filters.ts

v1 of https://github.com/wellcomecollection/wellcomecollection.org/issues/6188

Custom license labels for image search filtering

---

common/views/components/IIIFSearchWithin/IIIFSearchWithin.tsx
playwright/test/view-items.test.ts

Gets the viewer test passing on mobile devices.
- still a couple of outstanding bits to do

Mobile tests

---

common/views/components/IIIFSearchWithin/IIIFSearchWithin.tsx

close mobile sidebar when search result clicked

---

common/views/components/IIIFViewerPrototype/ViewerSidebarPrototype.tsx
common/views/components/WorkLink/WorkLink.tsx

Fix link in credit info

---

identity-admin/webapp/components/search/UserListItem.tsx

Fix - Import date function from correct path

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
playwright/test/contexts.ts
playwright/test/work.test.ts
playwright/user-stories/work.md

Only display encore link for items that have a physical location

---

playwright/user-stories/view-items.md

Small tweak to make a story slightly more meaningful.

Make suggested story amend

---

common/views/components/IIIFSearchWithin/IIIFSearchWithin.tsx
playwright/test/view-items.test.ts

fix test scenario 9 on mobile

---

common/views/components/IIIFViewerPrototype/IIIFViewerPrototype.tsx
playwright/test/view-items.test.ts

Fixes #6346
People who expect to see deep zoom when they click on the zoom button.
Making sure they actually get to see the deep zoom.

Zoomed image

---

common/styles/base/_typography.scss
common/views/components/FeaturedText/FeaturedText.js
common/views/components/Layout8/Layout8.tsx
common/views/components/PageHeader/PageHeader.js
common/views/components/styled/SectionPageHeader.tsx
content/webapp/pages/stories.js
content/webapp/pages/whats-on.js

Section page header

---

catalogue/webapp/components/Work/Work.tsx

Remove the 'improving info on this page' section

---

toggles/webapp/toggles.ts

Turn the itemViewerPrototypeWithSearch on for everyone

---

common/views/components/IIIFViewerPrototype/IIIFViewerPrototype.tsx

get pixel info for downloads

---

common/services/prismic/projects.ts

Closes #6202
Putting the labels on the cards.

Fetch pagesFormatsFields for card labels

---

catalogue/webapp/pages/image.tsx
catalogue/webapp/pages/item.tsx
common/views/components/IIIFViewerPrototype/ViewerSidebarPrototype.tsx
playwright/test/view-items.test.ts
toggles/webapp/toggles.ts

1 toggle to control the item viewer

---

common/services/catalogue/filters.ts

Fixes https://github.com/wellcomecollection/platform/issues/5127

rename genre filter to type/technique

---

common/views/components/ClearSearch/ClearSearch.tsx
common/views/components/IIIFSearchWithin/IIIFSearchWithin.tsx
common/views/components/SearchForm/SearchForm.tsx

Add ability to clear search term from search within

---

common/views/components/IIIFViewerPrototype/ViewerSidebarPrototype.tsx
common/views/components/ViewerStructuresPrototype/ViewerStructuresPrototype.tsx

Update structured contents list navigation styles

---

.buildkite/pipeline.identity.yml
identity-admin/terraform/locals.tf
identity-admin/terraform/main.tf
identity/terraform/locals.tf
identity/terraform/main.tf

Folk who want the identity work released.
Making it releasable.
**Note:** Deploys to prod are currently manual using the weco-deploy tool, we should automate that later.

Deploy to identity prod env

---

identity/webapp/src/config.ts

This reverts commit 8e262363ddbbdd2a546e1a326c573a986c84d661.

Revert "Use secure session cookies in prod (#6406)"

---

common/icons/components/Collapse.js
common/icons/index.js
common/icons/svgs/collapse.svg
common/test/fixtures/catalogueApi/work.ts
common/views/components/IIIFViewerPrototype/ViewerTopBarPrototype.tsx

Closes #6312
People who want clarity around exiting fullscreen.
Updating the icon and text to be more relevant.

Fullscreen UI

---

identity/webapp/src/config.ts

Set secure cookies to false

---

dash/webapp/pages/toggles.js

…instead of from an unavailable module. Hopefully fixing the build.

Get the abTests from the web

---

cache/cloudfront_prod.tf

Folk who want the account management system to work
Adding the correct cloudfront config to the prod CF.

/account path needs parity with stage

---

catalogue/webapp/components/Download/Download.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.tsx
common/utils/licenses.js
common/views/components/IIIFViewerPrototype/ViewerSidebarPrototype.tsx
playwright/test/view-items.test.ts

Fixes #6409
UK spellers
Putting a 'c' in their licences.

Update some license/licence spelling

---

playwright/package.json
playwright/test/helpers/utils.ts
playwright/test/view-items.test.ts

Fixing e2e tests. I couldn't get `isomorphic-unfetch` to work, so I've added `axios` for now.

Get toggles from the web

---

common/views/components/IIIFViewerPrototype/ViewerSidebarPrototype.tsx

Render html in work titles

---

common/views/components/IIIFViewerPrototype/GridViewerPrototype.tsx

Allow for at least two thumbs per row on smaller screens

---

cache/locals.tf

Bump edge lambda versions for sidebar toggle a/b test

---

common/views/pages/_app.tsx

Send the toggles to ga for ab testing

---

content/webapp/pages/stories.js

Can't wait to allow editorial to do this.

add "How to belong" to stories page

---

common/views/components/FooterNav/FooterNav.tsx

add new site sections to footer (toggle)

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx

**Before**
**After**
**Before**
**After**

remove double 'Credit' in 'Can I use this'

---

common/utils/iiif.ts
common/views/components/IIIFSearchWithin/IIIFSearchWithin.tsx
common/views/components/IIIFViewer/IIIFViewer.tsx
common/views/components/IIIFViewer/parts/IIIFCanvasThumbnail.tsx
common/views/components/IIIFViewer/parts/MainViewer.tsx
common/views/components/IIIFViewerPrototype/IIIFCanvasThumbnailPrototype.tsx
common/views/components/IIIFViewerPrototype/IIIFViewerPrototype.tsx
common/views/components/MainViewerPrototype/MainViewerPrototype.tsx

References #6428
Fixes issues 1,2 and 3
Also fixes [highlighting issue raised on slack](https://wellcome.slack.com/archives/C1PK7TS0L/p1617203762043800?thread_ts=1617194865.037700&cid=C1PK7TS0L)

iiif manifest

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx

put toggle back

---

common/views/components/FooterNav/FooterNav.tsx
common/views/components/Header/Header.tsx

People wanting to know what we're about and get involved
Add this two things to the main navigation

remove site sections toggle

---

common/views/components/ApiToolbar/ApiToolbar.tsx
common/views/components/PageLayout/PageLayout.tsx
toggles/webapp/toggles.ts

Just a little tool based on some feedback from collection info people. The code isn't too clean, but quite easy to manage with no dependencies.

API toolbar

---

common/utils/iiif.ts

The open with advisory functionality for videos is not working ([reported here](https://wellcome.slack.com/archives/CBT40CMKQ/p1620310719138800))

update service profile to match iiif manifest

---

common/model/pages.ts
content/webapp/pages/page.js

should fix your issue @davidpmccormick. Also, didn't think we need to check page.parentPages exists etc. [as far as I can see it'll always be an array](https://github.com/wellcomecollection/wellcomecollection.org/blob/3c76c3880477b782806dfb6a76be6aba30e725e2/common/services/prismic/pages.js#L43)

map doesn’t return a ParentPage type

---

common/views/components/ApiToolbar/ApiToolbar.tsx

add JSON link to api toolbar

---

toggles/webapp/toggles.ts

☝️ 
Makes the homepage look like this (again)

🚨 Don't merge till 17.05.21🚨 Turn on the reopening toggle

---

common/views/components/ButtonInline/ButtonInline.tsx
common/views/components/ButtonSolid/ButtonSolid.tsx
common/views/components/Tags/Tags.tsx

Just noticed a few things while looking at some code.

a few standardisations while looking around the code

---

catalogue/.gitignore
catalogue/terraform/stack/main.tf
catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.tsx
catalogue/webapp/pages/api/items.ts
catalogue/webapp/pages/api/works/items.ts
common/model/catalogue.ts
common/utils/has-own-property.ts

Fixes #6475
Also makes a request to the proxy api and updates the items table with the status of each item

Items proxy api

---

common/model/catalogue.ts
common/views/components/ApiToolbar/ApiToolbar.tsx

People wanting a link to the IIIF resource
Adds it to the API toolbar

add IIIF manifest to API Tollbar

---

common/views/components/styled/CssGridContainer.tsx

A bit of a mixin wound up in the wrong place after the move from Sass to TypeScript.

Don't max-width inner grid

---

docs/cardigan/principles.md

Make support for iOS 8 'Basic'

---

common/views/components/ImageGallery/ImageGallery.js

hide buttons from assistive technology too

---

common/views/components/Header/Header.tsx
common/views/components/SegmentedControl/SegmentedControl.js

remove hidden text

---

cardigan/.storybook/preview-head.html
cardigan/.storybook/preview.js

Anyone writing documentation in Storybook
Letting them write in mdx and use any of our components which will have been pre-wrapped in the context they require to render (instead of requiring that each component is wrapped manually, which is cumbersome and would cause exponential page bloat.

Docs context

---

toggles/webapp/toggles.ts

turn on holdings toggle for everyone

---

cardigan/Dockerfile
catalogue/Dockerfile
catalogue/webapp/components/SignIn/SignIn.tsx
catalogue/webapp/package.json
common/Dockerfile
common/next/next.config.js
common/package.json
common/views/components/CataloguePageLayout/CataloguePageLayout.tsx
common/views/components/PageLayout/PageLayout.tsx
content/Dockerfile
toggles/webapp/toggles.ts

Adds a login link to the catalogue pages, which switches to a my account and logout link when the user is logged in.

Login button

---

common/views/components/GifVideo/GifVideo.js

use ref to get current value of autoPlayDisabled

---

playwright/test/request-items.test.ts

Stub tests for item request scenarios

---

playwright/user-stories/request-items.md

Researchers
Doing the groundwork for testing their item-requesting journeys
Based on stories in #6537 and [screens in Zeplin](https://app.zeplin.io/project/5aab926b4b6efde01259e959/dashboard?sid=60bdef8592fbba14bdbb8a85&tag=Requesting%20-%20member%20sign%20in)

Add user stories for requesting items

---

common/views/components/CataloguePageLayout/CataloguePageLayout.tsx

get toggle from props

---

common/views/components/ArticleCard/ArticleCard.tsx
common/views/components/BookPromo/BookPromo.tsx
common/views/components/Card/Card.tsx
common/views/components/EventPromo/EventPromo.js
common/views/components/ExhibitionPromo/ExhibitionPromo.js
common/views/components/FeaturedCard/FeaturedCard.js
common/views/components/SearchResults/SearchResults.js
common/views/components/SimpleCardGrid/SimpleCardGrid.js
common/views/components/StoryPromo/StoryPromo.tsx

use empty alt attribute for images in promos and cards

---

common/views/components/CardGrid/CardGrid.tsx

People who don't like JSON dumps
Undumps the JSON
## After

remove JSON dump

---

catalogue/webapp/components/SignIn/SignIn.tsx

Remove SignIn from item page

---

common/views/components/PageLayoutDeprecated/PageLayoutDeprecated.js

People who don't want the homepage to 500
Checking for the existence of the `pathname` property on the `url` (it is just the string `/` on the homepage)

Check for pathname key

---

content/webapp/pages/stories.js

Update stories series to Voices of thalidamide

---

common/views/pages/_app.tsx

People who want the webfont to load on the catalogue app.
Looking for the right font name.

Observe the right font names

---

prismic-model/js/guides.js
prismic-model/json/guides.json

add showOnThisPage to guides custom type

---

prismic-model/js/pages.js
prismic-model/json/pages.json

References #6610 - making sure that the prismic custom types match what we have in code
Updates the pages.json to match what is in Prismic

Pages prismic model

---

playwright/test/landing-pages.test.ts

☝️ 
So that we can deploy. I'm going to investigate why they're failing concurrently.

Skip landing page tests

---

identity/webapp/src/frontend/components/PageWrapper.tsx
identity/webapp/src/routes/assets/index.html.ts

Adds navigation and favicons to identity app pages - was already approved but I merged it into the wrong branch.

Account navigation

---

common/services/catalogue/filters.ts

Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/6607

Change the label on the licence filter to "Licenses"

---

catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx
common/views/components/ButtonInlineLink/ButtonInlineLink.tsx
common/views/components/Table/Table.tsx

People who want to see physical item locations and whether they can be requested online.
Giving them more accurate online request information now that we have `accessConditions` `methods` in the api.

Use accessConditions method to determine online requestability

---

common/views/components/ContentPage/ContentPage.tsx
common/views/components/PageHeader/PageHeader.js

Resolves https://github.com/wellcomecollection/wellcomecollection.org/issues/6513

Fix padding/margin of stories page header

---

content/webapp/pages/articles.js

People who want consistent language around stories.
Using the word 'Stories' everywhere.

Change /articles title to 'Stories'

---

catalogue/webapp/components/WorksSearchResults/WorksSearchResults.tsx

Resolves https://github.com/wellcomecollection/wellcomecollection.org/issues/6605

Fix search results left-padding

---

cardigan/stories/global/page-types/page-types.stories.mdx
content/webapp/pages/stories.js

Change stories more link button text

---

common/views/components/ContentPage/ContentPage.tsx
common/views/components/PageHeader/PageHeader.js

People who want less space between the header and first paragraph, but also want to be able to read the first line of the first paragraph.
That.
The space values between two files are coupled. I can't think of a sensible fix for this. The pragmatic solution felt like a comment in each file.

Header spacing

---

prismic-model/js/series.js
prismic-model/json/series.json

Part of #6633 
Undoing changes in #5898 that never made it into Prismic.

Revert series model changes to mirror prismic

---

prismic-model/js/parts/body.js
prismic-model/json/books.json
prismic-model/json/event-series.json
prismic-model/json/events.json
prismic-model/json/exhibitions.json
prismic-model/json/guides.json
prismic-model/json/pages.json
prismic-model/json/places.json
prismic-model/json/projects.json
prismic-model/json/seasons.json
prismic-model/json/series.json
prismic-model/json/webcomics.json

Relates to #6633
Adds landing-pages to the contentList, which is already present in Prismic on the Books model

Prismic book model

---

common/views/components/Body/Body.tsx
common/views/components/ContentPage/ContentPage.tsx

Resolves https://github.com/wellcomecollection/wellcomecollection.org/issues/6450
@gestchild @davidpmccormick I think I may need some help with this to see if it's broken anything, I couldn't find any examples but I also don't really know where to look!

Remove some spacing between page sections

---

common/views/components/Caption/Caption.tsx

remove stray tabindex

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
common/utils/iiif.ts

get audio clickthrough service

---

common/utils/useControlledState.ts
common/views/components/SearchFiltersDesktop/SearchFiltersDesktop.tsx
common/views/components/SearchFiltersMobile/SearchFiltersMobile.tsx

Resolves https://github.com/wellcomecollection/wellcomecollection.org/issues/6419

Fix filter resets

---

identity/liquid-templates/template.html

better mobile styling

---

.buildkite/pipeline.deploy-stage.yml

add a prompt to check landing pages before deploying to prod

add a prompt to check landing pages

---

common/views/components/SearchForm/SearchForm.tsx
playwright/test/search-form.test.ts

Don't autofocus works search form

---

common/views/components/SeasonsHeader/SeasonsHeader.tsx

Resolves https://github.com/wellcomecollection/wellcomecollection.org/issues/6648

Add some vertical spacing to adjust for the WobblyBottom on season headers

---

common/views/components/InfoBox/InfoBox.js

Resolves https://github.com/wellcomecollection/wellcomecollection.org/issues/6643

Equal padding on all sides of InfoBox

---

common/model/people.js
common/model/people.ts
common/services/prismic/fetch-links.js
common/services/prismic/parsers.js
common/views/components/Contributor/Contributor.js
prismic-model/js/people.js
prismic-model/json/people.json

☝️ 
Relates to #6620 (don't want to say it closes it until it has been shown to meet the acceptance criteria of 'General happiness with appearance of pronouns')
Agreed first-pass styling

Add pronouns to Person model

---

common/views/components/EventScheduleItem/EventScheduleItem.js
content/webapp/pages/event.tsx

Accessibility list issue

---

content/webapp/content/static-books.js
content/webapp/pages/books.js

Make non-cms-editable changes to /books and /stories

---

toggles/webapp/toggles.ts

Remove newBlack toggle

---

common/views/components/InfoBanner/InfoBanner.tsx

add aria properties to identify notification banner

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx

Link to api contributors, genres, and subjects instead of free text queries

---

common/views/components/Header/Header.tsx

Display line to the right of the logo in the header

---

catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx

Increasing space between items for legibility.

Physical items list spacing

---

common/views/components/PageLayoutDeprecated/PageLayoutDeprecated.js

☝️ 
[Enough data has been collected for these pages](https://github.com/wellcomecollection/wellcomecollection.org/pull/6687#issuecomment-873920047)

Remove Hotjar from homepage, collections, visit-us, and whats-on

---

catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx
common/model/catalogue.ts

Add item notes to physical item list

---

common/views/components/SearchFiltersDesktop/SearchFiltersDesktop.tsx
common/views/components/SearchFiltersMobile/SearchFiltersMobile.tsx

References #6564
- if the date fields are cleared we want the search results to update

Accessibility filter behaviour

---

playwright/test/images.test.ts

#6729 fixed desktop test but broke mobile test. This makes them both work

fix mobile e2e test

---

common/views/components/SegmentedControl/SegmentedControl.js
content/webapp/pages/whats-on.js

Accessibility segmented control

---

common/views/components/DropdownButton/DropdownButton.tsx

don’t move focus into dropdown

---

common/views/components/PaletteColorPicker/PaletteColorPicker.tsx

add role of status to content that is updated

---

common/views/components/SearchTabs/SearchTabs.tsx

remove unnecessary text

---

common/styles/components/_series-nav.scss
common/styles/critical.scss

Remove series-nav scss

---

common/styles/components/_pre.scss
common/styles/non-critical.scss

Remove pre scss

---

common/views/components/NewsletterSignup/NewsletterSignup.js
common/views/components/TextInput/TextInput.tsx

add div with role=status around error messages

---

common/views/themes/config.ts

Fixes #6741 - Focus element colour contrast

change focus border colour

---

common/styles/components/_async-content.scss
common/views/components/PageHeader/PageHeader.js
common/views/components/SearchResults/AsyncSearchResults.js

Remove async-content scss

---

common/styles/content.scss
common/styles/critical.scss
common/styles/works.scss
common/views/themes/base/index.ts
common/views/themes/base/normalize.ts

Convert normalize to TS

---

common/views/components/Divider/Divider.tsx
common/views/themes/config.ts

Type the palette colours

---

common/views/components/IIIFViewer/ViewerSidebar.tsx

Noticed some accessibility issues with the viewer accordions
This adds keyboard focus styles and aria properties

Accessibility viewer accordion

---

common/views/components/PageLayoutDeprecated/PageLayoutDeprecated.js

Remove Hotjar from everything but events

---

common/views/components/WobblyEdge/WobblyEdge.tsx

Remove comment about non-existent data-attributes

---

common/views/components/BaseTabs/BaseTabs.tsx
common/views/components/Body/CollectionsStaticContent.tsx
common/views/components/SearchForm/SearchForm.tsx
common/views/components/SearchTabs/SearchTabs.tsx

Fixes #6561
The tabs now only act as links on the non javascript enhanced version

Accessibility tabs

---

.github/workflows/bundle-size.yml

This is what this looks like when things change: ![image](https://user-images.githubusercontent.com/4429247/126462125-417b079d-8bd3-46c4-b6b5-f920e306588b.png)
It isn't perfect as it includes various chunks which just have hashed names, but the important thing is that it does tell us the overall size change

Add bundle size action

---

common/views/components/PageLayoutDeprecated/PageLayoutDeprecated.js

Remove Hotjar everywhere

---

common/views/components/Caption/Caption.tsx
common/views/components/Images/Images.js

Align all text in captions to the left

---

content/webapp/package.json

ensures the [rewrites and redirects for the account app](https://github.com/wellcomecollection/wellcomecollection.org/blob/f4ac08e5cdd6e21c622e3d6c827bbe5fe8fd4a16/common/next/next.config.js#L49) are used for local development

add NODE_ENV to content dev script

---

playwright/test/workPrototype.test.ts

Update button text for test

---

common/services/prismic/parsers.js

Check 32:15 crop is an image before using it

---

common/views/components/Header/HeaderPrototype.tsx

People who want the main nav to stay in the same vertical position regardless of whether the login toggle is on or off.

Realign nav in HeaderPrototype

---

common/views/components/Header/HeaderPrototype.tsx

Use available space for nav better

---

common/views/components/Header/HeaderPrototype.tsx

The part of #6825 that is important disregarding the placement of the free sticker.

Make sure login is above other page elements

---

catalogue/webapp/components/PhysicalItemDetails/PhysicalItemDetails.tsx
catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx

Changes in line with Zeplin screens created after review:
desktop: https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/610020ab123c5812c5b64bd0
mobile: https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/6100209bb269de109e81e87a

Physical items tweaks

---

catalogue/webapp/components/PhysicalItemDetails/PhysicalItemDetails.tsx

Fix lines and space between location/shelfmark

---

toggles/webapp/toggles.ts

Turn on physical items toggle for everyone

---

identity/liquid-templates/README.md

Format & update the docs for deploying the universal login page as a first step to deploying in CI/

Update universal-login deployment docs

---

playwright/test/work.test.ts

update encoreLink text

---

common/views/components/PageLayout/PageLayout.tsx
common/views/pages/_app-deprecated.js

IE11 users
Ensures we polyfill the features we need

Polyfill from entries

---

common/hooks/useIsFontsLoaded.ts
common/views/components/BaseTabs/BaseTabs.tsx
common/views/components/SearchForm/SearchForm.tsx
common/views/components/SearchTabs/SearchTabs.tsx

Fixes double render bug and also some other js errors where we were trying to update state on unmounted components
Before:
After:

Double render bug

---

common/views/components/Header/HeaderPrototype.tsx
identity/universal-login/templates/universal-login.html

- Lining up the universal-login template header after changes were made to the `Header` component
- Lining up the login button with the main nav

Align logo/nav/login better

---

common/views/components/BaseTabs/BaseTabs.tsx

People who don't want to see non js content rendered before js kicks in
N.B we need to come up with a better solution in the long term

prevents hidden tabpanel content from display when no js

---

infrastructure/modules/service/main.tf
infrastructure/modules/service/variables.tf
lighthouse/terraform/service.tf

Necessary to get the increased max request body size

Use new nginx for Lighthouse server

---

common/views/components/PageHeader/PageHeader.js

Add space below breadcrumb

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx

Use same location data/layout for holdings as physical items

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
common/views/themes/config.ts

Add/use light turquoise tint for SignInNotice

---

playwright/test/request-items.test.ts

Skip request-items tests to get physical items back on the page

---

infrastructure/modules/service/main.tf
infrastructure/modules/service/variables.tf
lighthouse/terraform/service.tf

In https://github.com/wellcomecollection/wellcomecollection.org/pull/6881 I fell foul of https://github.com/hashicorp/terraform/issues/24142 - this sorts that out with minimum fuss 🤷

Fix catalogue/content terraform

---

catalogue/webapp/components/ConfirmItemRequest/ConfirmItemRequest.tsx
catalogue/webapp/components/PhysicalItemDetails/PhysicalItemDetails.tsx

Using ButtonOutlined instead of ButtonInline for request CTA

---

catalogue/webapp/pages/api/works/items/[workId].tsx

we don’t want to cache responses from the items API

---

identity/webapp/package.json

Just making small changes as I go.

update identity app author

---

catalogue/webapp/services/catalogue/common.ts

People who want to see TEI works

TEI on prefix on index name

---

identity/webapp/ecosystem.config.js
identity/webapp/package.json
yarn.lock

This should make the identity app work; I'm not sure why it works with pm2-dev 🙃

Fix pm2-runtime module resolution

---

common/views/components/Table/Table.tsx

I know it's my comment in the top of the file that caused this, assuming I was a little tired 🧹

fix table stuff

---

common/model/requesting.ts
identity/webapp/src/frontend/MyAccount/MyAccount.tsx

Put title in item requests table

---

content/webapp/pages/stories.js

Make happiness quest the stories serial

---

catalogue/webapp/components/ConfirmItemRequest/ConfirmItemRequest.tsx

Fixes #6977 
* Removes some unused props
* Change react types to fit more with rest of code base

Confirm item request modal copy

---

identity/webapp/src/types/application.ts
identity/webapp/src/utility/api-caller.ts

This makes 500s stop happening

Fix unauthenticated proxy calls

---

catalogue/webapp/components/ConfirmItemRequest/ConfirmItemRequest.tsx

cancel request => cancel

---

identity/webapp/src/frontend/MyAccount/ChangeEmail.test.tsx
identity/webapp/src/frontend/MyAccount/ChangePassword.test.tsx
identity/webapp/src/frontend/MyAccount/DeleteAccount.test.tsx
identity/webapp/src/frontend/MyAccount/MyAccount.test.tsx

Who is this for?
People who want confidence in the registration UI in the Identity app
What is it doing for them?
Fixing the tests in for the MyAccount section

fix failing tests in MyAccount section

---

identity/webapp/src/frontend/Registration/AccountValidated.test.tsx

People who want confidence in the registration UI in the Identity app
Fixing the tests

Registration tests

---

identity/webapp/src/frontend/components/ErrorPage/ErrorPage.test.tsx

Who is this for?
People who want confidence in the UI in the Identity app
What is it doing for them?
Fixing the tests for the Error page

Fix error page test in Identity app

---

.buildkite/pipeline.deployment.yml

Not sure why deployments are failing, this might help

Use latest patch version of weco-deploy

---

.gitignore
common/next/next.config.js

People who are finding it hard to see what's going on as there's loads of errors.
Allows them to deactive APM to remove the error from the console.

allow APM to be deactived

---

common/views/components/IIIFViewer/ImageViewerControls.tsx
common/views/components/IIIFViewer/ZoomedImage.tsx
playwright/test/view-items.test.ts

Developers who want to be confident the item page is working as expected
Adding back test which were (mistakenly) being skipped and fixing ones that were then breaking

E2e tests view items

---

playwright/test/helpers/conditionals.ts
playwright/test/view-items.test.ts

This test should be failing, but we'll skip it for now until it's fixed

[temporary] Skip item download e2e tests on mobile

---

common/views/components/IIIFViewer/ViewerTopBar.tsx

People who want a download button on mobile
Adding it, and running the test that checks it's there.

Download mobile test

---

catalogue/webapp/components/ConfirmItemRequest/ConfirmItemRequest.tsx

Update copy in confirmation modal

---

.dockerignore
catalogue/Dockerfile
catalogue/webapp/next.config.js
common/next/next.config.js
common/package.json
common/views/components/SignIn/SignIn.tsx
content/Dockerfile
content/webapp/next.config.js
identity/Dockerfile
yarn.lock

This is a start at decoupling the apps in order to make builds faster and to make this repo a little less of a monolith - it moves us closer to being able to make the changes in https://github.com/wellcomecollection/wellcomecollection.org/issues/7038, but shouldn't actually change very much as-is (although it does also fix the bundle analysis file naming and deployment).

Slightly improved docker images

---

catalogue/webapp/package.json
common/next/next.config.js
content/webapp/package.json
yarn.lock

As per @davidpmccormick's suggestion on https://github.com/wellcomecollection/wellcomecollection.org/pull/7041
Branched off https://github.com/wellcomecollection/wellcomecollection.org/pull/7041 so there were no conflicts, once https://github.com/wellcomecollection/wellcomecollection.org/pull/7040 is reviewed & merged we can collapse this stack

Remove CSS loaders

---

catalogue/webapp/components/PhysicalItemDetails/PhysicalItemDetails.tsx

run useEffect when user updates

---

catalogue/webapp/components/SignInBar/SignInBar.tsx
common/views/components/SignIn/SignIn.tsx
identity/webapp/pages/account/validated.tsx
identity/webapp/src/routes/auth.ts

Tidy up return to work after login

---

common/views/components/Icon/Icon.tsx

Use title instead of name

---

common/model/guides.js
common/model/guides.ts
common/services/prismic/fetch-links.js
common/services/prismic/pages.js
common/services/prismic/parsers.js
prismic-model/js/parts/body.js
prismic-model/json/books.json
prismic-model/json/event-series.json
prismic-model/json/events.json
prismic-model/json/exhibitions.json
prismic-model/json/guides.json
prismic-model/json/pages.json
prismic-model/json/places.json
prismic-model/json/projects.json
prismic-model/json/seasons.json
prismic-model/json/series.json
prismic-model/json/webcomics.json

Content team
Allowing them to add guides to content lists in the body (required specifically for something linked to from the `/collections` page)

Landing guides

---

common/views/components/PageLayout/PageLayout.tsx

@taceybadgerbrook 
Adding Hotjar for a couple of photo stories for analysis in #7064

Adds hotjar for two photo stories

---

assets/humans.txt

This has already been "deployed" by copying a file over to s3.
https://github.com/wellcomecollection/wellcomecollection.org/issues/7069 will happen next to automate this.

👋 and 🙏 robert kenny

---

catalogue/webapp/app.js
catalogue/webapp/package.json
common/next/next.config.js
common/services/apm/apmConfig.js
content/webapp/app.js
content/webapp/package.json
identity/webapp/package.json
identity/webapp/src/app.ts
yarn.lock

Not sure why I didn't bother doing this before!

Add APM to Node servers

---

identity/webapp/pages/account.tsx
identity/webapp/src/frontend/MyAccount/MyAccount.style.ts

Icon spacing

---

identity/webapp/pages/account/validated.tsx
identity/webapp/src/frontend/Registration/AccountValidated.test.tsx

Fixes #6952
Not sure how bullet proof using the message in the url to determine what to display is, but can't see another way

Verify email

---

content/webapp/pages/book.tsx
content/webapp/pages/homepage.tsx

Linting and removing  Component class

add book server side props

---

catalogue/webapp/babel.config.js
catalogue/webapp/components/ImageCard/ImageCard.tsx
catalogue/webapp/middleware/withQueryType.js
catalogue/webapp/pages/download.tsx
catalogue/webapp/pages/work.tsx
catalogue/webapp/server.js

lint catalogue webapp

---

identity/webapp/generate-schemas.js
identity/webapp/next.config.js
identity/webapp/src/config.ts
identity/webapp/src/frontend/MyAccount/ChangeEmail.tsx
identity/webapp/src/frontend/MyAccount/DeleteAccount.tsx
identity/webapp/src/frontend/MyAccount/MyAccount.style.ts
identity/webapp/src/frontend/components/Layout.style.ts
identity/webapp/src/frontend/components/PageWrapper.tsx
identity/webapp/src/frontend/components/PasswordInput/PasswordInput.test.tsx
identity/webapp/src/frontend/hooks/usePasswordRules.tsx
identity/webapp/src/frontend/hooks/useUpdatePassword.ts
identity/webapp/src/frontend/test-utils.tsx
identity/webapp/src/router.ts
identity/webapp/src/routes/users/item-requests.ts
identity/webapp/src/utility/configure-local-auth.ts
identity/webapp/webpack.frontend.js

A few ignore rules, which are OK, but should be addressed when refactoring etc.
Mostly removing redundant imports.

lint identity app
