wellcomecollection/wellcomecollection.org

catalogue/webapp/components/ImageCard/ImageCard.tsx

Fixes #6742
- adds focus box-shadow around entire image
Before:
After:
N.B the colour of the box shadow will be addressed in issue #6741

add box-shadow to image rather than link

---

.buildkite/pipeline.deploy-stage.yml
.buildkite/pipeline.yml

Folk who don't want to drown in error alerts.
This change makes triggering the stage deploy & prod deploy steps [async in Buildkite](https://buildkite.com/docs/pipelines/trigger-step), practically this makes one pipeline depend on the other for success. We alert when these steps fail in Slack and were seeing "double posting" of errors from multiple pipeline because of this.
This change should reduce the frequency of posts to Slack, while keeping the same level of reporting.

Make triggering stage/prod deploys async in CI

---

common/views/components/Tasl/Tasl.tsx

References #6743
The accessibility issue is that the image information buttons all have duplicate text that don't really describe what they do.
The suggested solution in the accessibility report is to remove the buttons completely and always display the text below the image, which I'm uncomfortable doing without discussion with the wider team.
Until then, I've made the labels more descriptive and unique by using the image title.

make button labels uniquely descriptive

---

catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx
common/model/catalogue.ts

The items API endpoint has changed to return an `ItemsList` this change updates the `PhysicalItems` component to reflect that. 
This change is for folk who want to be able to update item access status for requesting.
Follows https://github.com/wellcomecollection/catalogue-api/pull/164

Update to use new items API format

---

common/services/prismic/hardcoded-id.js
common/views/components/CataloguePageLayout/CataloguePageLayout.tsx
common/views/components/Header/HeaderPrototype.tsx
common/views/components/PageLayout/PageLayout.tsx
common/views/components/PageLayoutDeprecated/PageLayoutDeprecated.js
common/views/components/SignIn/SignIn.tsx
identity/webapp/src/frontend/components/PageWrapper.tsx

People who want to sign into their library account
Moving the login to a consistent location in the header
I duped the `Header` component to create `HeaderPrototype` with the required amends to make this work, so that the amount of toggle logic could be kept to a minimum. Since the Header isn't likely to undergo much if any change while we figure this out, this felt like the right way to go.
Behind the `showLogin` toggle.
__Big__
__Medium__
__Small__

Login button

---

common/views/components/Header/Header.tsx
common/views/components/Header/HeaderPrototype.tsx

change link display property, so focus border aligns nicely

---

common/views/components/Card/Card.tsx
content/webapp/pages/stories.js

People who like `Part of` labels to align horizontally with the rest of the body of a card.
__Before__
__After__
Also increasing the padding at the bottom of the cream section at the top of the stories page at @GarethOrmerod's request

Don't horizontal pad cards in stories header

---

identity-admin/webapp/package.json
package.json

These scripts need to exist in `main` in order for them to be run there to generate bundles to diff

Build scripts in advance of bundle diffing

---

common/views/components/DropdownButton/DropdownButton.tsx

People who want to be able to tab to focusable elements after opening a dropdown.
Making sure the act of opening the dropdown doesn't prevent the elements from being focusable.

Establish focusable elements before acting on them

---

common/views/components/FeaturedCard/FeaturedCard.js
common/views/components/SimpleCardGrid/SimpleCardGrid.js

- Fixing FeaturedCard image aspect ratio to be 16:9
- Shifting label up to prevent gap at tablet size (because labels have changed size recently)
- Making label orange when it's a Season

Seasons aspect ratio

---

common/views/components/BaseTabs/BaseTabs.tsx

Just noticed aria properties on the tab panels in no js world, which makes no sense as they won't act as tabpanels.
This only adds them if isEnhanced is true

Search tabs

---

catalogue/webapp/components/Work/Work.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.tsx
catalogue/webapp/components/WorkDetailsSection/WorkDetailsSection.tsx

The right-hand area of archive pages contains superfluous `container`s and `grid`s which have max-widths that can cause the page to scroll horizontally when there's too much content.
This removes them and makes line-breaking predictable and spacing simpler to reason about.

Fix archive layout

---

common/model/generic-content-fields.js
common/model/generic-content-fields.ts
common/services/prismic/parsers.js
common/views/components/DailyTourPromo/DailyTourPromo.js
content/webapp/components/Exhibition/Exhibition.js
content/webapp/components/Installation/Installation.js
content/webapp/pages/article-series.js
content/webapp/pages/article.js
content/webapp/pages/event-series.js
content/webapp/pages/season.tsx

Fixes #6819
People looking at season pages
Reducing the featured image height. The Zeplin comp used an `18:9` ratio. We don't have this in Prismic, but the `32:15` crop is pretty close.

Add superWidescreenImage crop for Seasons page

---

catalogue/webapp/components/PhysicalItemDetails/PhysicalItemDetails.tsx
catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx

Relates to #6410 
People who want to see physical item location/availability/notes
Improving the layout for them behind the `showPhysicalItems` toggle
I tried various approaches with css grid `auto-fit` and `auto-fill` in conjunction with `minmax` to allow elements in the grid to flow onto another line when there wasn't enough space. But I think the possible inconsistencies in layout both at different breakpoints and between different items meant that having two specific views ('mobile' and 'desktop') felt like it made more sense in the end. This is definitely up for debate, though.
I've included a method to add the (screengrabbed) colours associated with in-venue signage so that we can see it, but it comes with various caveats (see thread in [comment on the …

Physical items layout

---

common/views/components/CataloguePageLayout/CataloguePageLayout.tsx
common/views/components/PageLayout/PageLayout.tsx
common/views/components/PageLayoutDeprecated/PageLayoutDeprecated.js

⬆️ 
It's needed for the [usePrefix function](https://github.com/wellcomecollection/wellcomecollection.org/blob/c7f104edd1ef71858cd09707abc461ab74cabb13/identity/webapp/src/frontend/hooks/usePrefix.ts#L1) which we need to successfully make calls to the identity app api client side

move data-context-path so it is added to both content and catalogue app

---

cardigan/config/decorators.tsx
common/hooks/useIsFontsLoaded.ts
common/views/components/styled/AlignFont.tsx
common/views/pages/_app-deprecated.js
common/views/pages/_app.tsx
common/views/themes/default.ts
common/views/themes/typography.ts
identity/webapp/.storybook/preview.js
identity/webapp/src/frontend/MyAccount/MyAccount.style.ts
identity/webapp/src/frontend/components/Form.style.ts
identity/webapp/src/frontend/components/PageWrapper.tsx
identity/webapp/src/frontend/index.tsx

☝️ 
~It would have been nicer for this hook to set e.g. an `isFontsLoaded` boolean that we could use in the typography styles now that they're styled-components, but the `_app-deprecated.js` is a class component.~ Realised this wouldn't be too much to add for the `_app-deprecated.js`.

Load webfont in identity app

---

catalogue/webapp/components/PhysicalItemDetails/PhysicalItemDetails.tsx
catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx

The colour square is no longer required for the initial release.
__Before__
__After__

Remove colour square from location

---

common/koa-middleware/withCachedValues.js
common/koa-middleware/withGlobalAlert.js
common/koa-middleware/withMemoizedPrismic.js
common/koa-middleware/withMemoizedPrismicValue.js
common/koa-middleware/withOpeningTimes.js
common/koa-middleware/withPopupDialog.js

You may have noticed that `/whats-on` doesn't work until a minute after the application has started, and other pages have missing data until that time.
This doesn't matter in the context of the website because task registration takes longer than that and so hides the problem, but it was causing lighthouse reports to fail. 
The cause of the issue was the use of `setInterval(fetchValue, oneMinute)` - which doesn't run until a minute after startup. As well as fixing this, I made the change to use `memoizedPrismic` for all of its derivative memoized values, rather than re-fetching an API instance for each one.

Use memoized prismic for all cached values

---

catalogue/webapp/pages/_app.tsx

This replicates https://github.com/wellcomecollection/wellcomecollection.org/blob/bae23808de8c91cc5bcb080a15b91bbb2889ec4e/common/views/pages/_app-deprecated.js#L179, it isn't ideal but it gets things working for now

Remove memoizedPrismic from ctx.query in catalogue app

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx

References #6840
This stops the download options showing on works that have an access condition of open with advisory.
This is because they don't work until the user has accepted the consent message, which is only possible on the item page at present.
We may want to look at adding the open with advisory consent on the work page, but until that is discussed, this stops people ending up with an error.
To download such works the user will have to view the item, accept the consent message and then use the download options on the item page.

download options on works that are open with advisory

---

identity-admin/terraform/.terraform.lock.hcl
identity-admin/terraform/locals.tf
identity-admin/terraform/main.tf
identity-admin/terraform/provider.tf
identity-admin/terraform/stack/provider.tf
identity/terraform/.terraform.lock.hcl
identity/terraform/main.tf
identity/terraform/provider.tf
identity/terraform/stack/provider.tf
infrastructure/experience/.terraform.lock.hcl
infrastructure/experience/provider.tf
infrastructure/identity/.terraform.lock.hcl
infrastructure/identity/cert.tf
infrastructure/identity/dns.tf
infrastructure/identity/locals.tf
infrastructure/identity/main.tf
infrastructure/identity/provider.tf
infrastructure/identity/stack/provider.tf

Previously we had a single VPC + subnets for the identity services, but
now we have separate prod/stage VPCs.
Devs who want to plan/apply in this Terraform stack.
Making it work again. Running a plan against `main` gives the following errors:
```
│ Error: Unsupported attribute
│
│   on locals.tf line 25, in locals:
│   25:   vpc_id          = data.terraform_remote_state.infra_shared.outputs.identity_vpc_id
│     ├────────────────
│     │ data.terraform_remote_state.infra_shared.outputs is object with 15 attributes
│
│ This object does not have an attribute named "identity_vpc_id".
╵
╷
│ Error: Unsupported attribute
│
│   on locals.tf line 26, in locals:
│   26:   private_subnets = data.terraform_remote_state.infra_shared.outputs.identity_vpc_private_subnets
│     ├────────────────
│     │ …
```

Use the prod/stage networking for the identity-admin app

---

catalogue/terraform/.terraform.lock.hcl
catalogue/terraform/locals.tf
catalogue/terraform/main.tf
catalogue/terraform/provider.tf
catalogue/terraform/stack/provider.tf
catalogue/terraform/terraform.tf
content/terraform/.terraform.lock.hcl
content/terraform/locals.tf
content/terraform/main.tf
content/terraform/provider.tf
content/terraform/stack/provider.tf
content/terraform/terraform.tf
infrastructure/experience/terraform.tf

Devs wanting to know what resources are associated with which parts of the repo.
Tags all the AWS resources within the content/catalogue webapps.

tag AWS resources in webapps

---

common/views/components/IIIFViewer/GridViewer.tsx
common/views/components/IIIFViewer/MainViewer.tsx

People who want images to be centered in the viewport.
We currently center the images on initial render, but not when you click on a thumbnail from the grid view. This reuses the logic from the former for the latter.

Scroll to center of landscape images on thumbnail click

---

.github/workflows/lighthouse_integration.yml
.github/workflows/lighthouse_integration_paths.txt

Depends on https://github.com/wellcomecollection/wellcomecollection.org/pull/6860
This adds an action to run Lighthouse reports after every deployment, and upload the results to our lighthouse server.

Lighthouse CI integration tests/reports

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
playwright/test/workPrototype.test.ts
toggles/webapp/toggles.ts

Library members who are logged out
Giving them UI to indicate they need to log in in order to request items on a work page
This is currently behind the `showLogin` toggle, and not yet aware of a user's logged-in state (since that is being dealt with in a separate piece of work).

Request logged out

---

common/views/components/IIIFViewer/IIIFViewer.tsx

☝️ 
This is to keep the behaviour consistent with 1. landing on a page and 2. clicking on a thumbnail (#6854)

Center landscape images after main area resizes

---

catalogue/webapp/components/ConfirmItemRequest/ConfirmItemRequest.tsx
catalogue/webapp/components/PhysicalItemDetails/PhysicalItemDetails.tsx
catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.tsx
common/utils/works.ts
playwright/test/request-items.test.ts
toggles/webapp/toggles.ts

Related to #6537
People who want to request items
Giving them UI to confirm their request
This PR mocks the loading state and the request confirmed state, as well as the number of requestable items the user has left on their account. We'll wire this up to the items API and users in subsequent pieces of work.
https://user-images.githubusercontent.com/1394592/128361311-f59e3c8f-295c-46e6-a499-133988960eeb.mp4
I've left out the date-picker for now, because it feels too vague at the moment. And I've used an outlined button for the 'Cancel request' CTA for the time being, because we haven't got a button-styled-like-a-link at the moment.
__TODO:__

Confirm request modal

---

common/views/components/ApmContext/ApmContext.tsx
content/webapp/jest.config.js
content/webapp/test/pages/whats-on.test.js

People who want a fixed build
Adds the `publicRuntimeConfig` to the what's on test. I'm keeping the test as it's got some useful logic, although I am not sure that's the way we want to be testing it. 
Fixes the build

add publicRuntimeConfig to tests

---

content/terraform/data.tf
content/terraform/locals.tf

People who dislike reading comments
Removes a comment and the offending code it referrs to.
The code also happens to point at a ssm param that doesn't exist.

remove nginx ssm param

---

common/views/components/Label/Label.tsx

Fixes a bug introduced by #6919, which causes certain labels to have the same background and font colour
Before:
After:

label font colour bug

---

catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx
identity/webapp/src/frontend/MyAccount/UserInfoContext/UserInfoContext.tsx

The withPrefix function wasn't providing the correct paths for the api on stage and prod and was being used somewhere it shouldn't have been

Fix api calls

---

catalogue/webapp/components/ConfirmItemRequest/ConfirmItemRequest.tsx

Following a successful request to the requesting API the modal that displays success/failure info. to the user was closing when we don't want it to.
This stops that happening.
It also resets the requesting state when closing the modal, as long as the state isn't confirmed. This means the button will still show and allow a user to attempt the request again.

continue to show the modal following a successful request

---

catalogue/webapp/.env.production
common/views/components/PageLayout/PageLayout.tsx

Needed to [expose the context path variable to the browser](https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser), so that the correct api url was always used when on stage/prod
[Explanation of context path](https://github.com/wellcomecollection/wellcomecollection.org/tree/main/identity/webapp#context-path)

expose env variable to the browser

---

common/views/components/DropdownButton/DropdownButton.tsx

People who don't like massive lines of text. This has been run past @DominiqueMarshall and we're all good.
Responds the `DownloadButton` to the `large` break point, making it `50vw` instead of `100vw`.
**before**
**after**
https://user-images.githubusercontent.com/31692/130431516-2daa8eb2-b3aa-460e-ad14-9dd5fe9d713c.mov

respond width size to client size on DownloadButton

---

catalogue/webapp/components/PhysicalItemDetails/PhysicalItemDetails.tsx

Library users who want to find things.
Telling them that an item is on the open shelves and they can find it themselves.

If the location is "open-shelves", display "access: Open shelves"

---

catalogue/webapp/services/catalogue/common.ts
catalogue/webapp/services/catalogue/images.ts
catalogue/webapp/services/catalogue/works.ts
toggles/webapp/toggles.ts

Everyone who's interested in tei in wellcomecollection.org
It's showing tei works in the frontend and, in instances where a sierra or calm record exists for a tei, it will redirect those to tei

Add tei toggle

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
identity/webapp/src/routes/index.ts

This will redirect a user back to the work page when they login from a work page.
Adds a cookie when you use the login link, reads once you're authenticated, and returns you there instead of to the `/account` homepage.
This would probably be better but because "This solution takes a little more work to implement" I am adding this as a contigency so we can do testing.
https://auth0.com/docs/users/redirect-users-after-login#use-state-parameters

hack in redirection back to work pages from account page

---

cache/alarms.tf
cache/terraform.tf

Developers and people who work on wc.org.
Giving them alerts in Slack when the site has a 5xx error.

Add some CloudFront Alarms for 5xx errors

---

infrastructure/experience/ecr.tf
infrastructure/experience/provider.tf

People who like money.
Spending less of it, by not accumulating thousands of unnecessary Docker images in our account.
Closes https://github.com/wellcomecollection/platform/issues/5277

Expire images in uk.ac.wellcome/buildkite after 7 days

---

common/views/components/CheckboxRadio/CheckboxRadio.tsx
common/views/components/Table/Table.tsx
identity/webapp/ecosystem.config.js
identity/webapp/package.json
identity/webapp/src/frontend/MyAccount/MyAccount.style.ts
identity/webapp/src/frontend/components/Form.style.ts
identity/webapp/src/router.ts
identity/webapp/src/routes/assets/index.html.ts
identity/webapp/src/routes/index.ts
identity/webapp/src/types/application.ts
identity/webapp/src/types/weco.ts
identity/webapp/src/utility/typed-router.ts
identity/webapp/webpack.frontend.js

What this does:
- Uses the actual types from `@weco/common`
- Stops using a (duplicate) React from a CDN
- Fixes the `TypedRouter` internal types

Tidying in the identity app

---

catalogue/webapp/components/SignInBar/SignInBar.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.tsx
common/views/components/GlobalContextProvider/GlobalContextProvider.tsx
common/views/components/UserProvider/UserProvider.tsx
common/views/components/styled/LL.js

People who want to know how their sign in is going.
Creates a new `UserProvider`. We do have a `UserInfoProvider`, which is similar but it uses a few patterns that are not like we use elsewhere across the codebase, and we needed a few more states. I didn't refactor it as it's used in the `identity-admin`, which is being decommissioned, and then we can just remove it and use this one.
The `UserProvider` only does any async stuff if the toggle is on, otherwise renders just the children avoiding running this for public users, which it currently does.
Fixes #6975
Creates a signin bar that uses that state.
**No JS**
Nothing, we don't support that yet
**Loading**
**Signed out**
**Something went wrong**
**Signed in** 
Nothing the blue bar goes away
This component doesn't need so many visible …

add new UserProvider and SigninBar

---

.buildkite/pipeline.deployment.yml

For https://github.com/wellcomecollection/platform/issues/5289
People who want to spend less money.
Running build tasks on less expensive instances.

Use nano runners for the weco-deploy tasks

---

common/views/themes/config.ts
common/views/themes/default.ts
common/views/themes/mixins.ts

I found myself doing a lot of work to try and make sure that where ever we use breakpoints, we merge in tweakpoints. An example would [here](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/common/views/themes/default.ts#L124-L146).
Given we never differentiate between them, this pattern seems to simplify things. Is also removes the potential to have duplicate keys which would cause undesired behavior.
I've added `headerLarge: 1040` as I need it for some header work I am doing.

remove tweakpoints

---

common/views/components/PageLayout/PageLayout.tsx

I'd thought since the introduction of the `Fragment` element, we no longer needed to avoid componentising things in the `head`. It doesn't seem to be a problem in the identity app, but it is a problem in the content app (possible change between Next versions?).
This re-adds the favicon stuff directly in the `head` rather than imported from the `Favicons` component.
> title, meta or any other elements (e.g. script) need to be contained as direct children of the Head element, or wrapped into maximum one level of <React.Fragment> or arrays—otherwise the tags won't be correctly picked up on client-side navigations.

Re-inline the favicons in the head

---

CODEOWNERS

We don't need to protect this folder because it doesn't exist in this repository.

Remove /build/ folder from CODEOWNERS

---

common/views/components/SearchForm/SearchForm.tsx

After the react upgrade, we needed to ensure the dispatched event bubbles.
See here: https://github.com/final-form/react-final-form/issues/878
🧋 🍾

when dispatching the submit event on the SearchForm make it bubbles

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
common/test/fixtures/globalContextData.js
toggles/webapp/toggles.ts

Developers who don't want unnecessary code in the codebase
Removing the showHoldingsOnWork toggle, which has [been on by default for everyone since the beginning on June](https://github.com/wellcomecollection/wellcomecollection.org/pull/6572)

remove showHoldingsOnWork toggle

---

common/koa-middleware/withMemoizedPrismic.js
common/services/prismic/api.js
common/views/pages/_app.tsx
content/webapp/app.js
rss/webapp/stories/index.js

People who want to see content from Prismic
Making api calls to a cdn
We have seen `http 429` errors for certain urls, and Primsic have updated their docs to advise using the version of their api at a cdn. https://community.prismic.io/t/what-are-the-api-limits/5789

Serve Prismic from cdn to avoid 429s

---

common/views/components/SpacingComponent/SpacingComponent.tsx

People who want vertically spaced-out components to have the right space between them at the medium breakpoint
Fixing an override bug that meant the medium breakpoint immediately used the large breakpoints sizes.
__Before__
small: `16px`
medium: `32px`
large: `32px`
__After__
small: `16px`
medium: `24px`
large: `32px`

Fix medium spacing-component spacing value

---

common/model/requesting.ts
identity/webapp/src/frontend/MyAccount/MyAccount.style.ts
identity/webapp/src/frontend/MyAccount/MyAccount.tsx

Fixes #6979 
Links the title of each held work to the individual work page (`/works/{workId}`).

Link from account page to works

---

common/views/components/IIIFViewer/IIIFViewer.tsx

People who want to be scrolled to the first canvas right away
Removing an unnecessary effect that can cause incorrect scroll position on first render.
I wasn't able to replicate the [failing mobile test that this is aiming to fix](https://buildkite.com/wellcomecollection/experience-e2e/builds/174#4b5a9865-edd7-46b3-b9b9-88bb45eea8fb) locally, but anecdotally, this would make sense as a fix based on what's visible in the UI and why the test fails.

Change manifest scroll

---

catalogue/webapp/components/PhysicalItemDetails/PhysicalItemDetails.tsx

Fixes #6973
When a user is not logged we show the access method (which is what we do for an unrequestable item).
When the user is logged in and the item is requestable, then we display the request button.

hide request button if user is not logged in

---

cardigan/stories/components/Buttons/Buttons.stories.tsx
common/views/components/ButtonOutlined/ButtonOutlined.tsx

References #6971
Adds an 'isDangerous' prop to the ButtonOutlined component so it can be used for the account page 'Request deletion' button.
This has highlighted some accessibility issues captured in #7059

Outlined button variant

---

catalogue/webapp/components/SearchTitle/SearchTitle.tsx
catalogue/webapp/pages/images.tsx
catalogue/webapp/pages/works.tsx
playwright/test/landing-pages.test.ts

People who want confidence in the catalogue app
Testing the `/works` and `/images` routes, checking that they render with an expected `h1`.
There currently isn't an `h1` on `/works` at all, and it's only rendered on `/images` if there aren't any images to display. This makes sure there's always one present, and hides it with css (but keeps it accessible to screenreaders) where appropriate.

Add render tests for the catalogue app top-level pages

---

catalogue/webapp/__mocks__/catalogue-work.js
catalogue/webapp/__mocks__/collection-tree.js
common/model/catalogue.ts
common/test/fixtures/catalogueApi/images-aggregations.ts
common/test/fixtures/catalogueApi/work.ts
common/test/fixtures/catalogueApi/works-aggregations.ts

Developers who don't want to look at unnecessary code.
Removing some fields from the Work model that will never be populated in API responses. The `collection` and `collectionPath` fields look like they're from a now-abandoned branch of API design, and we binned all the `@context` URLs a few months back: https://github.com/wellcomecollection/platform/issues/5235

Remove the collection, collectionPath and @context fields from the Work model

---

cache/cloudfront_prod.tf
identity/terraform/locals.tf

Adds the identity aliases to the prod CloudFront distro to serve next assets.
I am starting to feel this isn't as scalable.

add identity aliases to prod cache

---

identity/webapp/pages/_app.tsx
identity/webapp/pages/account.tsx

Wraps the identity app in the `GlobalContextProvider`.
As we don't inject the toggles via the query, which is a bad way of doing things, I've just set `enableRequesting` to true on the identity app.
Bit hacky, I'll follow up with some tidy up.

GlobalContext in identity app

---

catalogue/webapp/components/PhysicalItemDetails/PhysicalItemDetails.tsx

increase column width

---

common/views/components/StackingTable/StackingTable.jsx
identity/webapp/pages/account.tsx
identity/webapp/src/frontend/MyAccount/MyAccount.style.ts

References #6971
Adds a new responsive table component (styled as[ designs](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/612de6c97e13d916c5085075)) which stacks cell rows on small screens. 
Uses this component on the account page, so we can fix the following issues in the above ticket and have it look good at all screen sizes.
- Item requests table should handle long titles appropriately (max width on column + text wrapping)
- show item title below work title
Before (small screens):
After (small screens):
Before (large screens):
After (large screens):

Stacking table component

---

catalogue/webapp/components/IIIFViewer/IIIFViewer.tsx
catalogue/webapp/components/IIIFViewer/NoScriptViewer.tsx
common/views/components/Header/Header.tsx
common/views/components/Header/HeaderPrototype.tsx
common/views/themes/config.ts
identity/webapp/src/frontend/components/PageWrapper.tsx

People who want the page background to fill the viewport
Making sure the cream `main` element is at least as high as the body of the page.
This isn't the neatest way of achieving it, but it's pretty straightforward and should be easy to update as and when.

Make cream stretch the whole page

---

common/views/components/ButtonSolid/ButtonSolid.tsx
common/views/themes/config.ts
identity/webapp/src/frontend/MyAccount/DeleteAccount.tsx

People who want consistent button styles
Using our pre-existing solid button with a red variant as the 'delete my account' button.
__Before__
__After__

Add isDangerous prop to solid button

---

content/webapp/pages/page.tsx

As per a discussion with @DominiqueMarshall 
People want to, in priority:
* Explore deeper into a subject (children)
* Explore around a subject (siblings)
This allows for that.

Rearrange children siblings

---

.vscode/settings.json
README.md
content/webapp/pages/page.tsx

Linting seems to be an issue.
I am hesitant to add it to CI, I personally get annoyed with it adding commits, and autosave avoids this.
Because we don't have this in CI -  I've added the autosave to the `.vscode/settings.json`. If any developer doesn't like this workflow, we can remove it and figure something out.
This just mentions  a prettier conflict I saw happening across the codebase.

add linting to readme

---

common/services/prismic/seasons.ts
content/webapp/pages/guides.tsx
content/webapp/pages/season.tsx

We were using `getInitialProps` and returning a `statusCode: 404`, which no longer works. This PR changes these pages to use `getServerSideProps` (like other pages), which can return a `notFound: true`.

Fix some 500s for seasons and guides pages

---

common/services/prismic/exhibitions.js
common/services/prismic/pages.js
common/services/prismic/seasons.ts
content/webapp/pages/guides.tsx
content/webapp/pages/homepage.tsx
content/webapp/pages/stories.tsx
content/webapp/pages/whats-on.js

Some `await`s have snuck in meaning that our well-intentioned `Promise.all()`s are not actually running all of the promises in parallel

Remove unnecessarily stacked promises from prismic-fetching pages

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx

Logged in users
Not giving them a 'Request item' button when the item has a method of `manual-request`

Add manual-request to the list of  unrequestable methods

---

catalogue/webapp/components/PhysicalItemDetails/PhysicalItemDetails.tsx

People who want less confusing UI on a physical item after login
Adding a loading state to the access method

Show access method loading state

---

catalogue/webapp/app.js
common/services/apm/errorMiddleware.js
content/webapp/app.js
identity/webapp/src/app.ts

APM currently traces errors as if they were normal responses - this makes them more explicit and useful. I would be interested in switching some of our monitoring to use APM rather than CloudFront...

Capture errors for APM

---

common/views/components/AppContext/AppContext.tsx
common/views/components/SearchFilters/SearchFilters.tsx

Inspired by
> However, if your effect is mutating the DOM (via a DOM node ref) and the DOM mutation will change the appearance of the DOM node between the time that it is rendered and your effect mutates it, then you don't want to use useEffect. You'll want to use useLayoutEffect. Otherwise the user could see a flicker when your DOM mutations take effect. This is pretty much the only time you want to avoid useEffect and use useLayoutEffect instead.
-- [Kent C. Dodds](https://kentcdodds.com/blog/useeffect-vs-uselayouteffect)
This is pretty much our use case for `isEnhanced`. Saying that, I am not 💯 that this won't have knock on effects. I'd rather have 1 way of doing this however, and measure where it might be an issue.
Fixes https://github.com/wellcomecollection/wellcomecollection.org/pull …

move isEnhanced into useLayoutEffect

---

common/services/prismic/api.js

[Occasionally](https://logging.wellcomecollection.org/app/discover#/?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1w,to:now))&_a=(columns:!(url.full,http.response.status_code),filters:!(),index:apm_static_index_pattern_id,interval:auto,query:(language:kuery,query:'processor.event:%22transaction%22%20AND%20transaction.id:%223bba8a6f6cd489d3%22%20AND%20trace.id:%22ec238fc5daeaa6a80039f560ba863eca%22'),sort:!(!('@timestamp',desc)))) we get 500s from malformed document IDs (likely due to dodgy links) with special characters in - this gets rid of those

URL-encode document IDs

---

common/views/components/WobblyEdge/WobblyEdge.tsx

Fixes #6993
It is overridden by default, but the large breakpoint has different values that also need to be overridden.

Override rotated wobbly line margin

---

common/views/components/GlobalContextProvider/GlobalContextProvider.tsx
common/views/pages/_app.tsx
identity/webapp/pages/_app.tsx
identity/webapp/pages/account.tsx
identity/webapp/src/app.ts
identity/webapp/src/frontend/MyAccount/MyAccount.test.tsx
identity/webapp/src/frontend/components/PageWrapper.tsx

* Moves UserProvider into _app, closer to removing GlobalContextData
* adds serverData to the identity app and account page
* hacks the globalContextData into identity as it's still used in _app, which I have a PR coming soon to remove

add serverData to identity account page

---

content/webapp/pages/book.tsx

There are only two books left that don't have a "contributors" field (and so which might hit this codepath), but neither of them have any author data populated anyway:
- https://wellcomecollection.org/books/W3K21ikAACIAEHQ7
- https://wellcomecollection.org/books/Ww_yXiEAAMsAlUMk
You can see this by running the following query and then inspecting the returned JSON:
curl -H 'Accept: application/json' 'https://wellcomecollection.prismic.io/api/v2/documents/search?ref=YYVAXhIAACEAtYHe&q=%5B%5Bany(document.type%2C+%5B%22books%22%5D)%5D%5D&pageSize=100' > books.json
For https://github.com/wellcomecollection/wellcomecollection.org/issues/7248

Remove the code for reading book fields from the Drupal migration

---

identity/webapp/src/frontend/MyAccount/DeleteAccount.tsx

Don't show a close cross on the modal for account delete (same as for other loading modals).

Hide close cross on delete account modal

---

cardigan/stories/data/iiifManifest-audio.js
cardigan/stories/data/iiifManifest-book.js
cardigan/stories/data/iiifManifest-multi.js
cardigan/stories/data/iiifManifest-pdf.js
cardigan/stories/data/iiifManifest-video.js
common/__mocks__/iiif-manifest.js
common/test/utils/iiif.test.ts
common/utils/convert-image-uri.js

Quoting [Tom Crane in Slack](https://wellcome.slack.com/archives/CBT40CMKQ/p1636534719049200):
> yeah - if you spot a dlcs.io URL in any published API, it's a mistake
So we can remove all our code for handling image URLs like that.
I also took this opportunity to update our mocked IIIF manifests to the latest versions, which no longer use dlcs.io.

Remove the code for handling image URLs from dlcs.io

---

common/test/utils/convert-image-uri.test.ts
common/utils/convert-image-uri.js

Me
Because I think we can and should tidy up this code further, in particular:
* Rewriting it in TypeScript
* Splitting out the IIIF and Prismic pieces – in most circumstances we can unambiguously say whether we're dealing with a IIIF or Prismic URL, so let's call the correct function directly.
The tests add a safety net against possible future refactoring.

Add some tests for convert-image-uri

---

catalogue/webapp/pages/item.tsx

Breaks locally otherwise, and won't have toggles.

add server data to item page

---

cardigan/stories/content.js
prismic-model/src/articles.ts
prismic-model/src/series.ts

Makes deprecated data obsolete. [I'll plough through the other deprecated fields next](https://github.com/wellcomecollection/wellcomecollection.org/issues/7277).

make deprecated wordpress data obsolete

---

identity/webapp/src/frontend/MyAccount/ChangePassword.tsx

The simpler proxying exposed that we were sending the password confirmation too, which API gateway didn't like

Fix "change password"

---

.buildkite/pipeline.yml
catalogue/Dockerfile
content/Dockerfile
identity/Dockerfile

People who work on this repo.
Making the build faster and whizzier (🤞). For https://github.com/wellcomecollection/wellcomecollection.org/issues/7038 and https://github.com/wellcomecollection/platform/issues/5359
- We were deploying dash twice. Let's not do that.
- We weren't running the identity bundle analysis in main. Let's do that. (Although I'm not sure the bundle analysis is working correctly – if you look in [s3://dash.wc.org/bundles](https://console.aws.amazon.com/s3/object/dash.wellcomecollection.org?prefix=bundles%2Fcatalogue.browser.latest.json&region=eu-west-1#), it doesn't look like anything's been uploaded for a long time.)
- Do we actually need that `rename` dependency? I'm not sure.
- ~Standardise on an Alpine-based Node base image, which is \~9x smaller (41MB vs 350MB).~

More build improvements

---

identity/webapp/src/utility/api-caller.ts

They aren't errors in that they are not unexpected

Stop logging proxied 40x statuses as errors

---

catalogue/webapp/pages/works.tsx

From what I can tell, giving Google any kind of sitemap won't have an influence on what they decide to put in the sitelinks below the hit for a search result.
As a variation on a theme from the solution we went with previously, this will make sure the h1 ('Search the collections') is visible on `/works`, which _might_ make them use that instead.

Show h1 on /works in an attempt to stop Google sitelinking confusing anchors

---

common/test/utils/convert-image-uri.test.ts
common/utils/convert-image-uri.js

This fixes the issue with /works in staging.
All the URLs in the catalogue app are coming from `iiif.wc.org`, but that's not the same as them coming from `iiif.wc.org/image` – which is what this function was assuming. Now we explicitly ignore thumbnails and have a test to boot.

Leave IIIF thumbnail URIs alone

---

common/views/components/CookieNotice/CookieNotice.tsx
common/views/components/PageLayout/PageLayout.tsx

Part of #7264 
Data analysts
Sending the page path with the close cookie banner event to make it simpler to analyse where users do/don't close the banner.

Add pathname to cookie banner close button tracking

---

catalogue/webapp/pages/_error.tsx
common/views/pages/_app.tsx

https://github.com/vercel/next.js/discussions/11945#discussioncomment-6790
That describes it best. Basically we can't send any data to _app from the error page as the page is served as soon as the error is hit.
This fixes traces to the correct 500 error when we have one, and 404s render the actual page.
Finding it quite hard to think of how to test page => app interaction...

change how we check for an error page when erroring for missing serverData

---

cardigan/stories/components/CopyUrl/CopyUrl.stories.mdx

Wrong path is now right path.
Built locally and it's working.

-views on path

---

cardigan/stories/content.js
common/model/exhibitions.js
common/model/exhibitions.ts
common/services/prismic/exhibitions.js
prismic-model/src/events.ts
prismic-model/src/exhibitions.ts
prismic-model/src/series.ts

Used to be the way we pulled in promo information ages ago.
Now we just use the Promo.
related to #7277

deprecate description field and a couple others

---

catalogue/webapp/components/ArchiveBreadcrumb/ArchiveBreadcrumb.test.tsx
catalogue/webapp/components/ArchiveBreadcrumb/ArchiveBreadcrumb.tsx

This is particularly relevant for TEI works, which don't always have a reference number, but do use an ArchiveTree to display the structure of the manuscript.
Before:
After:
For https://github.com/wellcomecollection/catalogue-pipeline/issues/1970

Don't show 'undefined' in the archive tree if there's no reference number

---

common/services/prismic/parsers.js
common/views/components/Body/Body.tsx
prismic-model/src/parts/body.ts

It's unused and we now use `showOnThisPage` which works out links automatically.

remove inpageanchor slice

---

content/webapp/pages/book.tsx

Moving the Contributors types into TypeScript would have caught this.
This is how it is done in the other pages, we can revisit this once this is deployed.

pass contributors through as object

---

identity/webapp/src/frontend/MyAccount/MyAccount.style.ts

☝️ 
Fixes #7281 
Uses the pre-existing dark shade of green that we have in the palette, which reaches [AA compliance (4.83:1 contrast ratio)](https://webaim.org/resources/contrastchecker/?fcolor=146A5C&bcolor=D9E1D7). This seemed like an approach that doesn't run the risk of breaking contrast elsewhere.
The background colours aren't part of our system (they're just one-offs for the messaging things), and I guess there might be scope for updating all of these at some point as well.

Use the dark green for accessible contrast

---

common/server-data/index.ts

Nasty Hack, get's the `?toggle=toggle.id` working again for user testing.

Check enable Cookie is valid

---

common/services/prismic/opening-times.js

People who want to know when we are closed
Displaying the exceptional opening times from 4 weeks out instead of 2 weeks out

Display exceptional opening times

---

common/services/prismic/articles.js
prismic-model/src/articles.ts
prismic-model/src/webcomics.ts

Removes `publishDate`.
The data for older articles is still available on the documents and will still be rendered, I've left a note to explain this.
This will stop it being used in Prismic in the future.
The ordering actually didn't work anyway.

remove publishDate

---

cardigan/stories/components/ImagePlaceholder/ImagePlaceholder.stories.tsx
cardigan/stories/content.ts
common/model/articles.ts
common/model/color-selections.js
common/model/color-selections.ts
common/model/editorial-series.ts
prismic-model/src/series.ts

#7363 
Removes `turquoise` as the editors can't select that color.
We could have this as common config somewhere, but we don't share code with the prismic model, so didn't want to cross that dependency line.

change color selection to what editors can select

---

catalogue/webapp/components/IIIFViewer/IIIFViewer.tsx

If a work has a iiifImageLocation and an image service from a iiif manifest, we only want to show the main viewer
People who don't want to see extra images in the viewer
Stopping this from happening

Viewer bug - extra image

---

identity/webapp/src/routes/auth0-auth.ts

By requesting a token for the Identity API audience (https://github.com/wellcomecollection/identity/pull/217), we will be able to use the new authorizer (https://github.com/wellcomecollection/identity/pull/218).
By including the `openid` scope, [we can still use that token](https://auth0.com/docs/security/tokens/access-tokens/get-access-tokens#multiple-audiences) with the existing authorizer! Win-win 🎉

Request the new token format

---

prismic-model/src/organisations.ts

Saw the word deprecated. We now use `SameAs`.
We don't render the URL either. 
A list just in case:
https://gist.github.com/jamesgorrie/735abe06a43a598c3ab690b485b38bdf

remove organisations URL

---

catalogue/webapp/components/ArchiveBreadcrumb/ArchiveBreadcrumb.test.tsx
catalogue/webapp/components/ArchiveBreadcrumb/ArchiveBreadcrumb.tsx

People looking at TEI works on our website.
Putting less "undefined" page jank in their breadcrumb trail. Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/7347
Before:
After:

Don't show 'undefined' if no ref number in a middle crumb

---

common/services/prismic/articles.js
content/webapp/services/prismic/fetch/articles.ts

Quick fix, in short we aren't fetching the linked document fields for the outro on articles.
I really hate this part of Prismic:
https://prismic.io/docs/technologies/fetch-linked-document-fields-javascript
Partialled caused through negelegence, lack of testing, and this is all not typed. I'll move this over in a new PR.
https://prismic.io/docs/technologies/fetch-linked-document-fields-javascript

add outro fetch links to article fetcher

---

identity/webapp/next.config.js
identity/webapp/pages/delete-requested.tsx
identity/webapp/pages/error.tsx
identity/webapp/pages/index.tsx
identity/webapp/pages/registration.tsx
identity/webapp/pages/validated.tsx
identity/webapp/src/frontend/Error/Error.test.tsx
identity/webapp/src/frontend/MyAccount/MyAccount.test.tsx
identity/webapp/src/frontend/Registration/AccountValidated.test.tsx
identity/webapp/src/frontend/Registration/Registration.test.tsx

This is, annoyingly, necessary in order to use Next.js API routes (so they live at `/account/api/...` and can live harmoniously behind the load balancer), which we need in order to use https://github.com/auth0/nextjs-auth0.
While at the moment it introduces slightly confusing inconsistencies between paths in koa vs Next, pretty much 100% of the custom server logic will be removed by the introduction of the aforementioned auth SDK.

Use `basePath` for the /account prefix when in Next-land

---

common/views/components/CataloguePageLayout/CataloguePageLayout.tsx
content/webapp/app.ts
content/webapp/package.json
content/webapp/pages/article.tsx
content/webapp/services/prismic/fetch/articles.ts
content/webapp/services/prismic/fetch/index.ts

* Uses new `linkResolver`
* When you fetch and there is no document, the Prismic client error. We catch the error and return nothing so that we will do better error handling
* When we have a `req` we enable preview
The toolbar is also out of date - I will fix this after.

fix previews with new Prismic client

---

content/webapp/services/prismic/transformers/contributors.ts
content/webapp/services/prismic/transformers/json-ld.ts

This is a legacy of having contributors as a common field, but it not actually being common. caught on #7426

don't look for contributors on seasons

---

.buildkite/expected_200_urls.txt
.buildkite/expected_404_urls.txt
.buildkite/pipeline.deployment.yml
.buildkite/pipeline.yml
.buildkite/scripts/check_urls_with_curl.sh

This PR adds a very primitive set of URL tests for deployments. We iterate through a list of URLs one-by-one and check whether they return a 200 OK/404 Not Found, as expected.
It's meant to make it easy as possible to add URLs, so we get a set of site-level regression tests.

Add some very primitive tests with cURL

---

.buildkite/expected_404_urls.txt
catalogue/webapp/services/catalogue/works.ts
catalogue/webapp/test/services/catalogue/works.test.ts

People who monitor the 500 errors on wc.org.
Squashing one of them, in particular the error you get if you visit:
https://wellcomecollection.org/works/%E2%80%8Cqvku%E2%80%8Czu%E2%80%8C5w?wellcomeImagesUrl=/indexplus/image/L0025863.html
That's a URL that somebody visited earlier today, and among other things that URL has the Unicode zero-width joining space `\u200C`. How did they get there? No idea – but we should return a 404 instead of a 500.
I'd like us to get to the point where we're not serving *any* 500 errors.

Don't return a 500 error/exception if looking up IDs with spaces

---

.buildkite/expected_200_urls.txt
content/webapp/services/prismic/transformers/contributors.ts
content/webapp/services/prismic/types/contributors.ts

Turns out the prismic model is the issue. `.name` can either be `RichText` or `Text`. Once we change the type in the source data, the type system catches these errors.
The implementation around it isn't great, but when reading union `RelationField` types, seems it's all a bit fiddly as it greats a union of the `type` field and the `data` field but doesn't allow you to differentiate on it.
e.g. 
```
if (agent.type === 'organisations') {
agent.data // <= this isn't of type `Organisation['data']`.
}
```

account for richtext or keytext for contributor names

---

.buildkite/expected_404_urls.txt
content/webapp/services/prismic/fetch/articles.ts
content/webapp/services/prismic/fetch/index.ts

I suspect this affects other types of page as well (e.g. event series) but a 500'ing book was where I initially saw this error. Somebody ended up on https://wellcomecollection.org/books/tel%3A%2B4420%207611%202222

Don't throw a 500 error if you look up a missing book

---

cache/cloudfront_prod.tf
cache/cloudfront_stage.tf
content/webapp/services/prismic/fetch/articles.ts
playwright/test/articles.test.ts

Otherwise we'll cache the first request for related stories to /api/articles, and the same list is shown on all articles.
Tentatively closes https://github.com/wellcomecollection/wellcomecollection.org/issues/7461; this is already applied.

Include the 'params' query parameter in the CloudFront cache

---

cache/cloudfront_prod.tf
cache/cloudfront_stage.tf
cache/locals.tf

This just makes them a little easier to reason about. Plus exposed the fact that in some cases, we're caching values for 36.5 days rather than a year. 🙈

Use names for the expiry times in the CloudFront distros

---

content/webapp/components/SearchResults/SearchResults.tsx
content/webapp/components/SeriesNavigation/SeriesNavigation.tsx
content/webapp/pages/article.tsx

If fetching the related stories for an article (which happens client side) failed, then the whole page would error as we were trying to run array methods on non existent arrays.
This should fix that.

Add some typing for ArticleSeriesList

---

common/views/components/CookieNotice/CookieNotice.tsx

People who care about super whizzy-fast web browsing.
Skipping an unnecessary redirect.

Use the wellcome.org URL in the cookie banner, not the old ac.uk URL

---

playwright/test/work.test.ts

To stop the e2e tests for requesting failing: https://buildkite.com/wellcomecollection/experience-e2e/builds/602#8c262486-d2ff-4b63-af43-719cb4f5337a

Don't look for an Encore link when requesting is unavailable

---

catalogue/webapp/pages/download.tsx

If you visit https://wellcomecollection.org/works/rku7vrtb/download?sierraId=b18037343, you get a 500 error. The underlying cause is a missing manifest in DLCS, which returns an HTTP 404 and the text:
> No IIIF resource found for v2/b18037343
which we can't parse as JSON.
There's nothing sensible we can do in this case, so return a 404 to the user.
No user should be landing on these pages, but we have a persistent trickle of them – possibly for pages that no longer exist? Throw them in the 404 bin so other errors can stand out.

Fix a persistent source of 500 errors from DLCS 404'ing manifests

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
catalogue/webapp/components/WorkHeader/WorkHeader.tsx

Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/7517
Before:
After:
This component gets the count by doing an async load of the IIIF manifests, which seems moderately fiddly to mock in tests, so no tests for this.

Fix the pluralisation of '1 volumes available online'

---

catalogue/webapp/services/catalogue/common.ts
catalogue/webapp/services/catalogue/images.ts
catalogue/webapp/services/catalogue/works.ts

We've seen more attempts by people to inject malicious data into our code in URL query parameters, e.g.
https://wellcomecollection.org/works/kusekcbm/images?id=yn3995ya'||lower('')||'
This is currently returning a 500 error; let's cut it off before we make an API query by 404'ing immediately.
See accompanying PR https://github.com/wellcomecollection/catalogue-api/pull/327

Return a 404 for image queries for impossible canonical IDs

---

common/model/seasons.js
common/model/seasons.ts
common/services/prismic/seasons.ts
content/webapp/pages/season.tsx
content/webapp/services/prismic/fetch/index.ts

References #7363
Displays events on season pages, using the new fetch and transform methods

Moving events to content app

---

identity/webapp/pages/api/users/[[...users]].ts

This makes logs from the (proxied) identity API a bit less chatty and liable to divulge tokens

Don't log the world

---

catalogue/webapp/pages/item.tsx

People trying to access restricted material
Preventing an erroneous 'Show the content' button from displaying when we aren't able to show the content.
__before__
__after__

Don't show 'Show content' button when it doesn't make sense

---

common/services/prismic/opening-times.ts
common/views/components/DateRange/DateRange.tsx
common/views/components/HTMLDate/HTMLDate.tsx
common/views/components/HTMLDayDate/HTMLDayDate.tsx
common/views/components/HTMLTime/HTMLTime.tsx
common/views/components/VenueClosedPeriods/VenueClosedPeriods.tsx
content/webapp/components/Body/Body.tsx
content/webapp/components/VenueHours/VenueHours.tsx

References #7525
- Primarily fixes the VenueClosedPeriods component so it's doing what is intended.
The component should display all the upcoming exceptional dates on which a particular venue is closed, but it was also showing the exceptional dates for other venues, if it was also normally closed on that day too.
Before:
After:
Also adds a bit of typing and makes use of components we have elsewhere for displaying dates

Refactor venue components

---

catalogue/webapp/utils/iiif.ts
playwright/test/contexts.ts
playwright/test/view-items.test.ts

People who want to be warned about viewer advisory content.
Showing them a modal.
#7529 was too permissive. In the instance where a work has e.g. three manifests, one that is restricted, one that is open with advisory and one that is open, we still need to show the modal because of the open with advisory content.
TODO:

Don't be too permissive with the viewer

---

cache/modules/cloudfront_policies/response_policies.tf

Slowly increasing up to 1+ years

Increase HTTP Strict Transport Security max-age to 1 week

---

identity/webapp/pages/index.tsx

References #7459
Adds a column to the requests table, on the account page, for displaying the 'Pickup request date'. At the moment that data isn't available, so just uses today's date as a placeholder. This is behind the enablePickUpDate toggle.
[Zeplin design for reference](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/618bd8950b7cb4aac42090b4)

Requesting pickup date

---

content/webapp/pages/whats-on.tsx

Pre-covid times, /whats-on/today used to display a message at the top of the page on a Monday (when the galleries are ordinarily closed), highlighting the fact the cafe and shop were still open.
This message has been commented out since the start of the lockdowns.
While I was refactoring opening times (#7532), I wrapped the code responsible in the buildingClosure toggle.
I thought this made sense at the time, but it doesn't for 2 reasons:
1. We use this toggle to determine whether to display the requesting button on works, and we want to turn this on again before the building is open. (so maybe want to call the toggle something else, but that's another story)
2. Even if the building is open, the shop and cafe may not necessarily be (at least this has happened before), so we may want to …

Don't use buildingClosure toggle

---

catalogue/webapp/components/RequestingDayPicker/RequestingDayPicker.tsx
catalogue/webapp/test/utils/dates.test.ts
catalogue/webapp/utils/dates.ts

People who want the day picker to make days on which the venue is closed, unavailable for selection
- uses the isClosed property introduced in #7532 to determine closed days
- adds tests for the possibility that the venue is closed every day
- updates functions to account for the fact that the venue may be closed every day

Daypicker closed days

---

content/webapp/pages/homepage.tsx
content/webapp/pages/stories.tsx

Chipping away at https://github.com/wellcomecollection/wellcomecollection.org/issues/7363
I can't do any more right now because query parameters get a bit complicated, and that's a separate patch. (More explanation below.)

Use the new fetch/transform methods for articles on two more pages

---

catalogue/webapp/components/RequestingDayPicker/RequestingDayPicker.tsx

We remove the styles that we were importing for the Daypicker in #7559, as it was causing problems.
Since we don't import styles anywhere else, and to reduce http requests, I think it makes sense to add the previously imported styles to a styled component.
Before:
After:

Daypicker styling

---

content/webapp/pages/articles.tsx
content/webapp/pages/books.tsx
content/webapp/pages/exhibitions.tsx
content/webapp/test/utils/query-params.test.ts
content/webapp/utils/query-params.ts

This ensures the right types as we finish converting the codebase to TypeScript, and gets us consistent behaviour on all pages that use pagination. It's a follow-up to my comment on https://github.com/wellcomecollection/wellcomecollection.org/pull/7564#discussion_r785761985

Use a shared function for getting the page from query params

---

content/webapp/components/SearchResults/SearchResults.tsx

☝️ 
We don't know that upcoming serial parts are going to be stories – they could be comics as [here](https://wellcomecollection.org/series/YbNK-hEAACIAZe82)
__Before__
__After__

Don't add story label to unpublished cards

---

catalogue/webapp/components/ItemRequestModal/ItemRequestModal.tsx

Just noticed this string was wasn't delimited properly, so the variable names were showing instead of their values

use template string

---

content/webapp/services/prismic/types/articles.ts

People who want to know if something is part of a serial
Adding the tag back on to the relevant cards and article pages

Include schedule in seriesFetchLinks

---

common/services/prismic/hardcoded-id.ts
common/services/prismic/pages.js
content/webapp/app.ts
content/webapp/pages/homepage.tsx
content/webapp/pages/page.tsx
content/webapp/pages/stories.tsx
content/webapp/pages/whats-on.tsx
content/webapp/services/prismic/fetch/pages.ts

Picking off another bit of https://github.com/wellcomecollection/wellcomecollection.org/issues/7363 and https://github.com/wellcomecollection/wellcomecollection.org/issues/7302, by switching to another typed method for fetching data from Prismic. I've tested it locally on a few pages, and it looks okay.
I also did a bit of other tidying, in particular consolidating a few more Prismic IDs in `hardcoded-id.ts`, so they're easier to find and manage.

Replace the untyped getPage() with the typed fetchPage()

---

content/webapp/pages/article.tsx
playwright/test/articles.test.ts
playwright/test/contexts.ts
playwright/test/mocks/one-schedule-item.ts

As a result of the changes in #7589 an article that is part of a serial that only has one part published will display a link to itself at the end of the article e.g. https://wellcomecollection.org/articles/YXKJQREAACMARPGd
This PR checks that there is more than one article in the schedule to prevent this from happening.

Don't link to self if schedule length === 1

---

.buildkite/expected_200_urls.txt
common/services/prismic/articles.js
common/services/prismic/hardcoded-id.ts
content/webapp/app.ts
content/webapp/services/prismic/fetch/articles.ts
content/webapp/services/prismic/fetch/index.ts
content/webapp/services/prismic/fetch/pages.ts
content/webapp/services/prismic/link-resolver.ts

e.g. compare
https://www-stage.wellcomecollection.org/guides/YL9OAxIAAB8AHsyv
https://www.wellcomecollection.org/guides/YL9OAxIAAB8AHsyv
This was a bug introduced in https://github.com/wellcomecollection/wellcomecollection.org/pull/7590, and caught before we deployed. Specifically, there's a bug lurking in here:
```typescript
const pagesFetcher = fetcher<PagePrismicDocument>('page', fetchLinks);
export const fetchPage = pagesFetcher.getById;
```
When you call that `getById` method, it's doing a check on the content type – if it doesn't match the content type we expect, you get a 404. Because guides and projects are both rendered using the `Page` component (which was calling `fetchPage()`), we'd 404 them out for mismatched content type.
This patch updates the `fetcher` to support multiple …

Fix support for rendering pages whose content type isn't 'page'

---

common/model/exhibitions.js
common/model/exhibitions.ts
common/services/prismic/exhibitions.js
content/webapp/components/Exhibition/Exhibition.tsx
prismic-model/package.json
prismic-model/src/exhibitions.ts

Part of #7597
Allowing them to change the access content information in the yellow box on a per-exhibition basis.
If no `Access content override` is added, 'Large-print guides, transcripts and magnifiers are available in the gallery' will continue to display by default.

Exhibition editable a11y info

---

common/services/prismic/events.js
content/webapp/pages/events.tsx
content/webapp/pages/homepage.tsx
content/webapp/pages/whats-on.tsx
content/webapp/services/prismic/fetch/events.ts
content/webapp/services/prismic/types/events.ts

Continuing to chip away at https://github.com/wellcomecollection/wellcomecollection.org/issues/7363. I can't use this everywhere because one use is within a `useEffect()` and I haven't worked out how to used the typed fetchers in there yet, but this is still a step forward.
I've tested the changed pages locally, and I can see the right data coming through.

Start using the typed fetchers for events on some pages

---

prismic-model/console.ts
prismic-model/deployType.ts
prismic-model/diffCustomTypes.ts
prismic-model/differ.ts
prismic-model/package.json
prismic-model/yarn.lock

Previously, running the Prismic deploy tool would dump the *entire model* into your terminal when asking you to compare the diff. This is less than helpful for spotting changes:
You had to scroll around to find the changes, and then when you did, they're only distinguished by red/green, so it's inaccessible:
I couldn't work out how to write a formatter for the custom library (the format is a bit weird), so I ripped it out and wrote my own differ. It's quite conservative; it works by "subtracting" values that are the same in both objects, and showing you what's left. This is what the output looks like now:
Benefits:
* It's much shorter (so we'll actually read it)
* If you're colourblind, the text above the two JSON blobs will tell you what's going on
* You can see the JSON keys that lead …

Improve the diffs when deploying the Prismic model

---

common/package.json
content/webapp/services/prismic/fetch/articles.ts
content/webapp/services/prismic/fetch/index.ts
yarn.lock

For https://github.com/wellcomecollection/wellcomecollection.org/issues/7363 / https://github.com/wellcomecollection/wellcomecollection.org/issues/7426
I don't actually expect this to work, because it keeps failing with this error:
```
$ yarn build
yarn run v1.22.10
$ next build
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types
info  - Using external babel configuration from /Users/alexwlchan/repos/dotorg/content/webapp/babel.config.js
info  - Creating an optimized production build
Failed to compile.
../../node_modules/prismic-client-beta/dist/index.mjs
Attempted import error: 'asLink' is not exported from '@prismicio/helpers' (imported as 'prismicH').
> Build error occurred
Error: > Build failed because of …
```

Use the nice typed fetchers for articles

---

.buildkite/expected_404_urls.txt
catalogue/webapp/pages/image.tsx
catalogue/webapp/pages/work.tsx
content/webapp/pages/article-series.tsx
content/webapp/pages/article.tsx
content/webapp/pages/book.tsx
content/webapp/pages/event-series.tsx
content/webapp/pages/exhibition.tsx
content/webapp/pages/season.tsx
content/webapp/services/prismic/index.ts

You can get a 500 error by visiting any of those URLs:
https://wellcomecollection.org/article-series
https://wellcomecollection.org/event-series
https://wellcomecollection.org/exhibition
This is because on those pages, we expect to get an ID (e.g. `/pages/YE99nRAAACMAb7YE`), but in these cases we extract the ID from the URL parameters as `id = undefined`. This explodes when you try to pass it to the Prismic predicate.
This patch updates these URLs so that if we spot we're getting something which definitely isn't a Prismic ID, we return a 404 immediately rather than waiting to go to Prismic. As a neat bonus, this should reduce the potential risk of malicious URLs doing something funky in a Prismic query, because they'll never go that far. (We have seen URL paths that have caused the …

Don't throw a 500 error on /article-series, /exhibition or /event-series

---

common/model/siblings-group.js
common/model/siblings-group.ts
common/services/prismic/pages.js
content/webapp/pages/page.tsx
content/webapp/services/prismic/fetch/pages.ts

For #7363 / #7426
This replaces the `getChildren` and `getSiblings` functions, which in turn allow us to bin the `getPages` method (which had otherwise been replaced with the typed fetchers).

Use the typed fetchers for children/siblings of pages

---

common/services/prismic/exhibitions.js
content/webapp/components/ExhibitionsAndEvents/ExhibitionsAndEvents.tsx
content/webapp/components/FeaturedCard/FeaturedCard.tsx
content/webapp/components/LayoutPaginatedResults/LayoutPaginatedResults.tsx
content/webapp/pages/exhibitions.tsx
content/webapp/pages/homepage.tsx
content/webapp/pages/season.tsx
content/webapp/pages/whats-on.tsx
content/webapp/services/prismic/fetch/exhibitions.ts
content/webapp/services/prismic/transformers/exhibitions.ts

For #7363 / #7426
This replaces the getExhibitions function, which allows us to start cleaning up the UiExhibition type also. I'm having weird type checker errors locally, so pushing into CI to see if that fixes it.

Use the new typed fetchers for getExhibitions

---

identity/webapp/pages/validated.tsx
identity/webapp/src/frontend/Registration/AccountValidated.test.tsx

The way we were doing this (a) was bad and (b) didn't work.
The way that the [Auth0-owned endpoint](https://github.com/auth0/nextjs-auth0/blob/70f59193b637ba5c5525359282b3c78b555b286b/src/handlers/profile.ts#L59-L84) does profile refreshes involves meddling with both the Auth0 management API and the user's session. This isn't something we should do ourselves, so this redirecting ping-pong is (imo) probably the most sound way of doing this.

Handle the post-verification profile refresh from the server side

---

catalogue/webapp/components/AudioList/AudioList.tsx
catalogue/webapp/components/AudioPlayer/AudioPlayer.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.tsx
catalogue/webapp/hooks/useIIIFManifestData.ts
catalogue/webapp/pages/item.tsx
catalogue/webapp/utils/iiif.ts
common/views/components/PageLayout/PageLayout.tsx

Part of #7596
People who want to access all available audio for a work
Accounting for the fact that works can have multiple audio parts
This PR doesn't address the display of thumbnail images or pdf transcripts.  [Moving to IIIF v3](https://github.com/wellcomecollection/wellcomecollection.org/issues/7596#issuecomment-1026791303) will better address those issues and reduce the need for us to retrofit complexity into our already-off-spec IIIF version. And is the direction we will presumably want to move in ultimately.
I have started work on the move the v3, but it has grown out of this work, and I don't think there is any need to wait for that before at least displaying the multiple audio parts.
How [Mat Fraser: interview 1](https://wellcomecollection.org/works/b4tj49m4) will appear after …

Multiple audio

---

common/services/prismic/parsers.js

While looking at youtube cookies as part of #7581, it became apparent we should probably be embedding the videos with [privacy-enhanced mode turned on](https://support.google.com/youtube/answer/171780?hl=en-GB#zippy=%2Cturn-on-privacy-enhanced-mode)
This does that.
Essentially, it will reduce (but not completely eliminate) the number of cookies that get set by youtube and most will only be set once a user plays the video and not before.
The effect of turning on privacy-enhanced mode is: 
"The privacy-enhanced mode of the YouTube embedded player prevents the use of views of embedded YouTube content from influencing the viewer's browsing experience on YouTube. This means that the view of a video shown in the privacy-enhanced mode of the embedded player will not be used to personalise the …

embed youtube videos with privacy-enhanced mode

---

infrastructure/experience/ecr.tf
infrastructure/experience/ecr_policy.tf
infrastructure/modules/certificate/provider.tf

We're currently keeping ~1.8TB and spending ~$180 a month on keeping a big collection of Docker images we'll never use. Let's add a lifecycle policy to keep the size of the repos manageable.

Add some policies to reduce the size of our ECR repos

---

common/services/prismic/hardcoded-id.ts
content/webapp/pages/article-series.tsx
content/webapp/pages/article.tsx

The series page for "Worry Lines" is https://wellcomecollection.org/series/X76JKBMAACIAqtZ2, but it's been 404'ing for a while, because the Prismic query for finding articles on the page is wrong – it returns an empty result set, so the page 404s.
It looks like somebody migrated it out of the "webcomic" type, so we no longer need the special casing on the article series page.

Fix the "Worry Lines" series page

---

prismic-model/src/featured-books.ts

Content team
Giving them a custom type to allow for cms-able books on the `/stories` page

Add featured-books to prismic model

---

common/services/prismic/articles.js
content/webapp/pages/article.tsx
content/webapp/services/prismic/transformers/articles.ts
content/webapp/services/prismic/transformers/books.ts
content/webapp/services/prismic/transformers/event-series.ts

We've now refactored the front-end to fetch documents from Prismic using the new typed fetchers; these then call various `parse()` methods in the common library that are Flow-typed JavaScript. These parser methods are the last major use of Flow in the codebase, and I want to get them flipped over to TypeScript.
All that parsing code is heavily interlinked and dependent; trying to convert it all in one go would almost certainly introduce bugs. This is my attempt to start migrating it in little pieces.
I've taken three uses of the old methods in our TypeScript codebase (`parseArticleDoc`, `parseBook` and `parseEventSeries`), and copy/pasted the definition of those functions into TypeScript. It means we get …

Start converting the Prismic transformers to TypeScript

---

catalogue/webapp/test/works.test.ts
catalogue/webapp/utils/works.ts
common/test/fixtures/catalogueApi/work.ts

https://github.com/wellcomecollection/platform/issues/5415
(as part of preliminary work for https://github.com/wellcomecollection/platform/issues/5408)
This change ensures that there is a way to prevent new partOf relationships creating unexpected and explosive hierarchy trees.
The signal as to whether to include it in the hierarchy is whether it has any parts underneath it.  This means that there is no need for an API change specifically to serve this UI (e.g. an "includeInHierarchy" field).

platform-5415: don't return non-archive ancestors

---

content/webapp/services/prismic/transformers/events.ts
content/webapp/services/prismic/transformers/vendored-helpers.ts

This fixes the error on http://www-stage.wellcomecollection.org/articles/W_LXOxcAACwAxC5_
I'm not sure why this wasn't caught by TypeScript. 😕

Handle getting an `undefined` passed to `link()`

---

catalogue/webapp/pages/images.tsx

Devs
Letting them see the `/images` page in development

Add serverData to images page

---

content/webapp/__mocks__/events.ts
content/webapp/components/EventPromo/EventPromo.test.tsx
content/webapp/components/EventPromo/EventPromo.tsx

Part of #7639
Adding a location label to all events to distinguish between those that are in venue only, online only, or both.
- If an event is only in venue, we display the specific location (e.g. 'Reading Room')
- If an event is only online, we display 'Online'
- If an event is both online and in venue, we display 'Online & In our building'

Online and/or in the building

---

common/model/events.ts
common/model/multi-content.ts
content/webapp/services/prismic/transformers/articles.ts
content/webapp/services/prismic/transformers/books.ts
content/webapp/services/prismic/transformers/event-series.ts
content/webapp/services/prismic/transformers/events.ts
content/webapp/services/prismic/transformers/exhibitions.ts
content/webapp/services/prismic/transformers/index.ts
content/webapp/services/prismic/transformers/pages.ts

The reason I'm going after this function first is that it calls `parseBody()` … which calls `parseMultiContent()` … which calls all the type-specific parsers, creating a nice circular loop that keeps everything in JavaScript.
I've also got a local test harness running against a snapshot of Prismic, which is fetching every bit of Prismic content – to catch mistakes before they get deployed. 😅

Create a TypeScript version of parseGenericFields

---

common/services/prismic/parsers.js
content/webapp/services/prismic/transformers/index.ts
content/webapp/services/prismic/types/body.ts

For https://github.com/wellcomecollection/wellcomecollection.org/issues/7363, follows #7673
This breaks the deadlock of JavaScript code where, say, parseArticleDoc calls transformGenericFields, which calls parseMultiContent, which calls parseBody … which calls parseArticleDoc. I copy/pasted the existing implementation of parseBody, tweaked it to make TypeScript happy, and called it done.
I also checked every bit of Prismic content in a local build to see that it wasn't 500'ing.

Create a TypeScript version of parseBody

---

content/webapp/components/SeriesNavigation/SeriesNavigation.tsx

This is broken on series pages where there's only one item in the series so far, e.g. https://wellcomecollection.org/articles/YgP2JxMAACAAKVB5
Once a series has >1 items, we'll display the "Read more" link.
Keen beans who read the very first article in a comic series.
Making the page seem less broken/confusing – they can't "read more" because there isn't anything more to read! Not yet, anyway.
At some point we could give this a nicer design treatment, e.g. saying when the next item will be published, but for now the page is at least a bit less wonky.

Don't show "Read more" if there are no more items

---

common/model/events.ts
content/webapp/__mocks__/events.ts
content/webapp/components/CardGrid/DailyTourPromo.tsx
content/webapp/components/EventPromo/EventPromo.test.tsx
content/webapp/components/EventPromo/EventPromo.tsx
content/webapp/components/EventSchedule/EventScheduleItem.tsx
content/webapp/pages/event.tsx

Part of #7639 and #7681
Now that all Prismic event `places` have been moved to be the first of an event's newly created `locations`, we can stop using `event.place` altogether.
This is like for like – there won't be a difference in what displays on the frontend.

Use event locations in stead of place in templates

---

content/webapp/services/prismic/transformers/exhibitions.ts
content/webapp/services/prismic/transformers/images.ts

I got confused about the function signature when I converted this from
JavaScript.  The original signature was
crop: ?Crop = '16:9'
and it was called on the books page with `crop = null`.  If the `crop`
is null, you get the full image.  I thought I could change that to
crop: Crop | undefined = '16:9'
and then omit the argument on the books page, but I got that wrong --
it caused the book promo to be cropped to 16:9 by default.
Since this function is only used in two places, I've binned the default
and made the use of a 16:9 crop in the one other call explicit.
People who make book covers.
Showing them in their full glory.
See https://wellcome.slack.com/archives/C8X9YKM5X/p1645631512964199

Fix the crop of books in their promo

---

.buildkite/pipeline.e2e-universal.yml
.buildkite/pipeline.yml
docker-compose.yml
infrastructure/experience/ecr.tf
playwright/.dockerignore
playwright/Dockerfile
playwright/get_playwright_image.sh
playwright/test/stories.test.ts

For https://github.com/wellcomecollection/wellcomecollection.org/issues/7706
One of the impediments to deploying to prod is passing the staging end-to-end tests, which take 5–7 minutes, depending on what's already cached locally and how many times we have to retry. Of that, about 2 minutes is spent building a Docker image which almost never changes:
This PR steals an idea from elsewhere in the experience build: it creates an ECR repo for these images, and saves the image there based on the Git commit. The first deploy after you update the e2e tests should be slow, but subsequent deploys will be faster because they're pulling a prebuilt image from ECR. 🤞 
By my reckoning, this will shave **~2 minutes** off every deploy of the front end.

Cache the e2e test image between builds to make them go faster

---

common/model/events.ts
common/services/prismic/parsers.js
content/webapp/services/prismic/transformers/books.ts
content/webapp/services/prismic/transformers/events.test.ts
content/webapp/services/prismic/transformers/events.ts
content/webapp/services/prismic/transformers/exhibitions.ts
content/webapp/services/prismic/transformers/guides.ts
content/webapp/services/prismic/transformers/index.ts
content/webapp/services/prismic/transformers/pages.ts
content/webapp/services/prismic/transformers/seasons.ts
content/webapp/services/prismic/transformers/series.ts

For #7363.
Hopefully this is quite a mild change; mostly what this does is force us to be a bit stricter/more explicit about `null` and `undefined`. In particular, the old `parseTimestamp` method could return `null` in some circumstances, but we weren't really checking it properly – now we have to handle it properly.

Create a TypeScript version of parseTimestamp

---

content/webapp/services/prismic/transformers/index.ts

This adds the [dnt parameter to Vimeo embed urls](https://vimeo.zendesk.com/hc/en-us/articles/360001494447-Player-parameters-overview) and stops Vimeo from setting third-party cookies on our site. This arose while looking at #7581.
"Setting this parameter to "true" will block the player from tracking any session data, including all cookies and analytics."
Since this will affect analytics, it would good to have @taceybadgerbrook approve this before it is merged. Do we use Vimeo analytics?

Increase privacy of vimeo player embeds

---

common/services/prismic/parsers.js
common/services/prismic/types.ts
common/views/components/InfoBlock/InfoBlock.tsx
common/views/components/PopupDialog/PopupDialog.tsx
content/webapp/services/prismic/transformers/body.ts
content/webapp/services/prismic/transformers/card.ts
content/webapp/services/prismic/transformers/index.ts

I'm also trying to get some of the Prismic document models out of the components, and only use transformed types there -- so a few of the links are now being parsed before being passed to the components, not after.
For #7363.

Create a TypeScript version of parseLink

---

prismic-model/.gitignore
prismic-model/README.md
prismic-model/downloadSnapshot.ts
prismic-model/package.json
prismic-model/tryAllContentPages.ts
prismic-model/tryAllPages.ts

This is some tooling I've used for the big Prismic refactor (#7363). It adds two new commands:
1. To download a complete snapshot of our Prismic metadata:
```console
$ yarn downloadSnapshot
...
Downloaded Prismic snapshot to snapshot.master.Yhe_-xMAADOEgW3d
```
2. To check all the pages against a local content app:
```console
$ yarn tryAllContentPages
!!! 500 http://localhost:3000/pages/YOwMVBMAACMATaPW
```
For now I've been running it locally; you can imagine at some point we might want to run this in CI, but since it takes about 10&nbsp;minutes every time (at least from my home computer), I'm wary to add it as a gate to deployments.

Add a script for checking all content pages

---

common/services/prismic/parsers.js
content/webapp/components/ArticleCard/ArticleCard.tsx
content/webapp/components/StoryPromo/StoryPromo.tsx
content/webapp/services/prismic/transformers/body.ts
content/webapp/services/prismic/transformers/books.ts
content/webapp/services/prismic/transformers/card.ts
content/webapp/services/prismic/transformers/contributors.ts
content/webapp/services/prismic/transformers/events.ts
content/webapp/services/prismic/transformers/exhibitions.ts
content/webapp/services/prismic/transformers/guides.ts
content/webapp/services/prismic/transformers/images.ts
content/webapp/services/prismic/transformers/index.ts
content/webapp/services/prismic/transformers/pages.ts
content/webapp/services/prismic/types/card.ts
content/webapp/services/prismic/types/events.ts
content/webapp/services/prismic/types/guides.ts
content/webapp/services/prismic/types/pages.ts

For #7302. This snips a few more bits out of `parsers.js`.
My ultimate goal is that we'll have three functions like:
- `asText()` – returns plain text
- `asHtml()` – returns HTML
- `asHtmlString()` – currently returns out HTMLString type, but at some point it'll return the RichTextField, because that's what various Prismic components want to receive
And all three are better than calling Prismic helper methods directly because they remove nulls/empty values and extra whitespace.

Convert a few more parser methods to TypeScript

---

content/webapp/components/Contributors/Contributor.tsx
content/webapp/components/PrismicImage/PrismicImage.tsx

Follows #7722
While reading some stories (shocking, I know, actually using the site as a reader), I noticed that contributor images were quite slow to load. This is because of a poor interaction between the Next Image component and the way Prismic resizes images, which is explained in the new comment in the PrismicImage component. We're loading unnecessarily large images; larger than if we weren't doing any resizing at all (!).
On my 5K iMac, I was getting 1338px wide images… which are shown at 72px wide.
This patch modifies the PrismicImage component in two ways:
* We'll never ask Prismic for a resized version that's wider than the original image; this is pure waste
* Callers can tell this component that they'll only be using the image up to a certain width; it then constrains resized …

Don't blow up the contributor images unnecessarily

---

content/webapp/services/prismic/transformers/contributors.ts
content/webapp/services/prismic/types/contributors.ts
content/webapp/services/prismic/types/index.ts

I noticed this while investigating the contributor link issue -- because Person and Organisation are slightly divergent types (one uses a string for the title, the other a structured text field), we lose the benefits of the type checker here.  In particular, the `sameAs` type was `any`, but now we know what it is in both branches.

Split the types for transforming contributors

---

.buildkite/expected_200_urls.txt

☝️ 
In order to fix the [failing build](https://buildkite.com/wellcomecollection/experience-deployment/builds/687#16ad4468-a398-40b1-a842-61bb646eff2d).

Remove covid-book-your-ticket url that's no longer live

---

content/webapp/app.ts
content/webapp/package.json
yarn.lock

This is following the instructions from Prismic's migration guide:
https://prismic.io/docs/technologies/prismic-client-v6-migration-guide
We still have a few other versions of old Prismic libraries hanging around (e.g. prismic-reactjs, prismic-dom). Upgrading those is sufficiently complicated as to warrant its own patch.
For #7363 and #7595.

Switch to using a single version of the Prismic client in the content app

---

catalogue/webapp/components/ItemRequestModal/ItemRequestModal.tsx
common/data/microcopy.ts

This is for people who will be requesting items from the collection. The requesting service API can respond with an error under several circumstances. At present we just tell the user that the request failed and ask then to try again. 
Ticket: https://github.com/wellcomecollection/wellcomecollection.org/issues/6916
We want to ensure we are displaying informative error messages to people using the requesting service.
I was able to replicate the error of trying to request an item when I have already reached my limit, this at least demonstrates the process of getting the `error.description` back from the API. In theory, it should work for each error case set by the API. 
I saw [a PR](https://github.com/wellcomecollection/catalogue-api/pull/319) that has been merged in the API to change the …

Bring improved error messages from requesting api 

---

catalogue/webapp/components/Download/Download.tsx
catalogue/webapp/model/iiif.ts
catalogue/webapp/utils/iiif.ts

There are some IIIF presentation manifests that don't have an `@id` on an element in the media sequence, e.g. https://iiif.wellcomecollection.org/presentation/v2/b29696586
```json
"mediaSequences": [
{
"@id": "https://iiif.wellcomecollection.org/iiif/b29696586/xsequence/s0",
"@type": "ixif:MediaSequence",
"label": "XSequence 0",
"elements": [
{
"label": "Arts and Health Witness Seminar: Programme",
"thumbnail": "https://iiif.wellcomecollection.org/thumb/b29696586"
}
]
}
],
```
Our model expects the `@id` to be present, and the Download component explodes if it's `undefined`.  This causes certain pages to fail, e.g. https://wellcomecollection.org/works/akbf645k
This patch filters out sparse media elements, so our downstream components can assume they have all the fields they need.

Filter out IIIF media elements which can't be downloaded

---

content/webapp/services/prismic/transformers/events.ts

This is breaking https://wellcomecollection.org/events/X8j2TxIAACIAk-Fx and one other event page. I spotted it while working on #7765.
We were getting an error in determineDateRange because calling `reduce()` on an empty list is an error, but on further inspection, we don't need this function at all.
Previously the type checker was unable to tell us this, because we called it in one object then unpacked it into another later:
```typescript
function transformEvent(): Event {
const event = { dateRange: determineDateRange() }
// do some stuff
return { ...event }
```
By consolidating everything into the return statement, the type checker tells us this field/function is unused (and several more besides).

Fix a bug in the event transformer

---

toggles/webapp/toggles.ts

This doesn't actually do anything. The way to update a default value of a toggle is to [use a script](https://github.com/wellcomecollection/wellcomecollection.org/tree/main/toggles#deployment).
I'm just changing this to keep it consistent with what is live.

change default value of enableRequesting

---

package.json

☝️ 
This should prevent us from checking in any lint issues.

Treat eslint warnings as errors in staged files

---

catalogue/webapp/components/ItemRequestModal/ItemRequestModal.tsx
common/services/prismic/opening-times.ts
common/services/prismic/transformers/collection-venues.ts
common/utils/json-ld.ts
common/views/components/PageLayout/PageLayout.tsx
content/webapp/components/Body/VisitUsStaticContent.tsx
content/webapp/components/VenueHours/VenueHours.tsx
content/webapp/pages/whats-on.tsx
content/webapp/services/prismic/transformers/index.ts

Last bit of tidying up opening-times.ts
- Renames parseCollectionVenue/s to transformCollectionVenue/s and moves them to their own file, to be more consistent with the content app transformers
- moves (and renames) the function for generating opening hours json-ld to sit with the other json-ld functions.

Opening times

---

catalogue/webapp/components/PhysicalItemDetails/PhysicalItemDetails.tsx
catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.tsx
catalogue/webapp/test/works.test.ts
catalogue/webapp/utils/works.ts
common/views/components/PageLayout/PageLayout.tsx
common/views/components/UserProvider/UserProvider.tsx
playwright/test/request-items.test.ts

Fixes #7778 
The toggle is working intermittently and I think we need to look at this separately.
This PR removes the use of the toggle for the requesting work. We'll lose the ability to turn it of quickly (without code changes and a deploy), but it will fix this issue.

remove enableRequesting toggle

---

common/model/image.ts
common/model/picture.ts
common/views/components/Image/Image.tsx
common/views/components/PageLayout/PageLayout.tsx
content/webapp/components/PrismicImage/PrismicImage.tsx

Fixes #7746
Making sure there's an alt attribute on all images (we thought we'd always get something from Prismic, but turns out it can be `null`)

Use empty string for alt if we get null from Prismic

---

common/server-data/index.ts

It looks like sometimes the `fetch()` method for server data can fail, and so we'd never set a timer to fetch new server data later – that instance of the app would just get stuck on whatever the last value of the data was, and never fetch new toggles/global values.
The logs show us apps where this has happened; in particular [this line in the Prismic fetcher](https://github.com/wellcomecollection/wellcomecollection.org/blob/28a37d84b3e7ccb7613acb16a559e38d6b569af2/common/server-data/prismic.ts#L69):
```typescript
console.error(`Failed to fetch ${keys[i]} from Prismic`, result.reason);
```
If you search our logs for "Failed to fetch", you'll find several instances of it. The longer a task is up, the more likely it is to get a failure which would cause this issue.
Practically speaking, I …

Make sure we always set a new server-data timer

---

catalogue/webapp/components/ArchiveTree/ArchiveTree.tsx
catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx
catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx
catalogue/webapp/components/VisuallySimilarImagesFromApi/VisuallySimilarImagesFromApi.tsx
catalogue/webapp/pages/api/visuallySimilarImages/[imageId].tsx
catalogue/webapp/pages/api/works/[workId].tsx
catalogue/webapp/pages/api/works/items/[workId].tsx
catalogue/webapp/services/catalogue/images.ts
catalogue/webapp/services/catalogue/index.ts
catalogue/webapp/services/catalogue/works.ts

We're seeing a steady trickle of reset connections between the front-end and the catalogue API; since we know we're always going to be talking to the API, let's try holding the connection open rather than recreating it on every request. Fingers crossed this makes it more reliable!
We do fetch catalogue data asynchronously on the front-end, when we find visually similar images on a work – for that, there's a new endpoint `/api/visuallySimilarImages/[imageId]`. My guess is that this will be beneficial for the user (🤞):
* All connections to the catalogue API come from the server, which can use the keep-alive'd connection
* All connections from the browser go to the front-end app, rather than opening separate connections to the front-end and the catalogue API
* We can toss a bunch of code out …

Use a custom agent that keeps the catalogue API connection alive

---

catalogue/webapp/pages/work.tsx

Somewhere between our app code and the user, the redirection path changes from `${workId}` to `/${workId}`.  This breaks redirections on the site, because
https://wellcomecollection.org/works/${redirectedWorkId}
gets redirected to
https://wellcomecollection.org/${redirectedWorkId}
which is a 404 error.
By hard-coding the /works prefix, redirects should work properly.
Me, when I spotted broken redirects in https://wellcome.slack.com/archives/C8X9YKM5X/p1646569642569749
Making redirects work well good proper.

Fix redirects on work pages

---

catalogue/webapp/package.json
catalogue/webapp/services/catalogue/index.ts
yarn.lock

Enabling keep-alive in https://github.com/wellcomecollection/wellcomecollection.org/pull/7770 did not fix the `ECONNRESET`s we've been seeing - that's likely because keep-alive was actually already enabled in Next.js [by default](https://nextjs.org/docs/api-reference/next.config.js/disabling-http-keep-alive).
I suspect that the `ECONNRESET`s are in fact _caused_ by the keep-alive, as there needs to be a socket open for it to be reset. This PR adds a timeout to open sockets which should - as per https://connectreport.com/blog/tuning-http-keep-alive-in-node-js/https://connectreport.com/blog/tuning-http-keep-alive-in-node-js/ - sort this out 🤞

Fix keep-alive behaviour

---

content/webapp/components/ExhibitionPromo/ExhibitionPromo.tsx
content/webapp/components/FeaturedCard/FeaturedCard.tsx
content/webapp/components/LayoutPaginatedResults/LayoutPaginatedResults.tsx
content/webapp/pages/api/exhibitions/index.ts
content/webapp/pages/exhibitions.tsx
content/webapp/pages/homepage.tsx
content/webapp/pages/season.tsx
content/webapp/pages/whats-on.tsx
content/webapp/services/prismic/transformers/exhibitions.ts
content/webapp/types/exhibitions.ts
content/webapp/types/multi-content.ts

Relates to https://github.com/wellcomecollection/wellcomecollection.org/issues/7796
This covers exhibitions.
Where ExhibitionsPromos and exhibition json-ld is rendered, we will now only return the required data from getServerSideProps, rather than the data needed to render the entire exhibition.

Reduce html size exhibitions

---

content/webapp/pages/season.tsx

Relates to https://github.com/wellcomecollection/wellcomecollection.org/issues/7796
This covers the seasons landing page.
We will now only return the required data from getServerSideProps, in order to render the various promos on the season page.

use ‘…ToBasic’ transform methods on seasons page

---

common/model/opening-hours.ts
common/services/prismic/transformers/collection-venues.ts
common/services/prismic/transformers/images.ts
common/services/prismic/transformers/index.ts
content/webapp/components/VenueHours/VenueHours.tsx
content/webapp/services/prismic/transformers/body.ts
content/webapp/services/prismic/transformers/card.ts
content/webapp/services/prismic/transformers/contributors.ts
content/webapp/services/prismic/transformers/images.ts
content/webapp/services/prismic/transformers/index.ts

This does the following:
- moves the transformImage and transformTaslFromString functions to common, so they can be used by transformCollectionVenue.
- adds the correct type to the Venue image property
- updates the VenueHours component to use the contentUrl prop returned by transformImage

Use transform image for venue

---

common/views/components/PrismicHtmlBlock/PrismicHtmlBlock.tsx
content/webapp/components/HTMLSerializers/HTMLSerializers.tsx

There were two issues preventing drop caps from appearing:
*   In the newest version of the Prismic libraries, the `htmlSerializer` property has been replaced with `components`.  Allegedly it supports the old property for back-compatibility, but local testing shows the drop cap serializer was never being called.
*   Remove the assertion that the `key` is 0.  We already check that we're in the first paragraph in `Body.tsx`, and inspecting these keys we see they may not necessarily be zero (in a local build, they're an int that increases on every reload: 85, 166, 247).
This seems to fix drop caps on articles.
Kate, who asked about it in Slack: https://wellcome.slack.com/archives/C1PK7TS0L/p1647427112434309
Making the drop caps work properly.

Fix drop caps on stories

---

common/services/prismic/transformers/collection-venues.ts
content/webapp/components/VenueClosedPeriods/VenueClosedPeriods.tsx
content/webapp/components/VenueHours/VenueHours.tsx

Noticed this while working on #7796
venue is passed down as JSON, so we need to convert the date strings back to Moment objects, similar to [what we do for event dates](https://github.com/wellcomecollection/wellcomecollection.org/blob/195673ec1c4b92f2980b9b4499fab34df7c781d6/content/webapp/services/prismic/transformers/events.ts#L329)
At the moment a page will error if it uses the VenueHours component with a venue that has exceptional dates

convert day strings back to Moments

---

.github/workflows/lighthouse_integration.yml

https://github.com/wellcomecollection/wellcomecollection.org/pull/7671 was a little over-enthusiastic, the LHCI report on deploys is actually useful and was what caught https://github.com/wellcomecollection/wellcomecollection.org/pull/7833

Restore the lighthouse report on deploy

---

common/utils/dates.test.ts
common/utils/dates.ts
common/views/components/DateRange/DateRange.tsx
content/webapp/components/CardGrid/CardGrid.tsx
content/webapp/components/EventDateRange/EventDateRange.tsx
content/webapp/components/EventPromo/EventPromo.tsx
content/webapp/components/EventsByMonth/EventsByMonth.tsx

Developers.
Follows https://github.com/wellcomecollection/wellcomecollection.org/pull/7829. This introduces two helpers `isSameDay(Date, Date)` and `isSameMonth(Date, Date)` which are a stand-in for a similar method `Moment.isSame(Moment, 'day' | 'month')`. Date comparison logic is timezone-agnostic, and so we don't need to be casting to London timezones before we compare here.
This is somewhat tricky to test because we only have one upcoming event at the moment, but I've stared at it quite hard to check I've not broken anything. 🤞
For https://github.com/wellcomecollection/wellcomecollection.org/issues/7831

Don't use Moment for as many date comparisons

---

content/webapp/components/Exhibition/Exhibition.tsx
content/webapp/pages/article-series.tsx
content/webapp/pages/article.tsx
content/webapp/pages/event-series.tsx
content/webapp/pages/event.tsx

Lalita, who noticed in Slack that we're displaying the three *oldest* events in a series, vs the three *newest*. Flipping the ordering in `getPastEvents` does the trick. See https://wellcome.slack.com/archives/C3N7J05TK/p1647884830511289
Additionally, I did some refactoring to reduce the size of this page – we fetch *all* the events for a series, but we only display a handful of them. I've moved that filtering into `getServerSideProps`, so we only send events we're actually going to render. Combining that with Gareth's work on sending "basic" properties makes a substantial difference:
Looking at /event-series/W5Zj_CYAACQALK5B:
<table><tr><th>page</th><th>size</th></tr>
<tr><td>original page</td><td>663KB</td></tr>
<tr><td>using EventBasic</td><td>551KB (–17%)</td></tr>
<tr><td>filtering …

Display the three *newest* events on an event series page

---

content/webapp/components/ArticleCard/ArticleCard.tsx
content/webapp/components/BookPromo/BookPromo.tsx
content/webapp/components/Card/Card.tsx
content/webapp/components/EventPromo/EventPromo.tsx
content/webapp/components/ExhibitionPromo/ExhibitionPromo.tsx
content/webapp/components/FeaturedCard/FeaturedCard.tsx
content/webapp/components/SearchResults/SearchResults.tsx
content/webapp/components/StoryPromo/StoryPromo.tsx

For #6007.  This is an intentional omission, but you can only find it by looking in the Git blame history -- so a well-meaning developer might revert it without realising why we've done it this way.  These comments make this a bit easier to understand and will avoid reversions.
See also #6586, where this change was originally made. It's been rolled back in a few places already, so I've un-rolled it back.
Me.
Helping me remember why this code is written this way.

Add comments explaining why we omit alt text on promos

---

catalogue/webapp/components/IIIFViewer/IIIFViewer.tsx

Fixes #7102
Making sure the manifest number sticks around in the URL so multi-volume works are correctly addressable.

Keep the manifest number in the URL

---

.github/workflows/lighthouse_integration.yml

So somebody looking at a GitHub Actions run can find the results.
Me.
Helping me find the Lighthouse scores.

Link to the Lighthouse URL from the GitHub Actions output

---

playwright/test/articles.test.ts
playwright/test/events.test.ts
playwright/test/helpers/utils.ts
playwright/test/request-items.test.ts
playwright/test/stories.test.ts
playwright/test/view-items.test.ts

☝️ 
In the Playwright tests we add all of the toggle cookies set to their default values, so we can be sure we’re testing what most users are seeing. Up to now, we were also adding the A/B test toggles to these, and we’d been erroneously expecting these to have a default value (which is now making TypeScript complain). I think it makes more sense to remove the A/B test toggles altogether.

Take the ab test cookies out of the playwright tests

---

common/model/image.ts
content/webapp/components/ArticleCard/ArticleCard.tsx
content/webapp/components/Installation/Installation.tsx
content/webapp/pages/season.tsx
content/webapp/services/prismic/transformers/articles.ts
content/webapp/services/prismic/transformers/images.ts
content/webapp/services/prismic/transformers/index.ts
content/webapp/services/prismic/types/index.ts
content/webapp/types/articles.ts
content/webapp/types/generic-content-fields.ts
content/webapp/utils/page-header.tsx

Another piece extracted from https://github.com/wellcomecollection/wellcomecollection.org/pull/7838.
People who want whizzy fast pages.
Reducing the amount of data we send on the page, by not duplicating information about image crops. It's a modest gain, but all gains are good:
<table>
<tr><th>page</th><th>before</th><th>after</th></tr>
<tr><td>/</td><td>291KB</td><td>286KB (–1.7%)</td></tr>
<tr><td>/exhibitions/YLi_BhAAACEAebzp</td><td>294KB</td><td>288KB (–2%)</td></tr>
<tr><td>/articles/YjMIUhEAACAAWeQ_</td><td>246KB</td><td>244KB (–1%)</td></tr>
<tr><td>/articles/Yi8toBIAACIA1p4T</td><td>214KB</td><td>212KB (–1%)</td></tr>
</table>
There are also a couple of easy wins, by removing a few intermediate values we don't need.

Don't send multiple copies of the crop data

---

content/webapp/components/Body/Body.tsx

People who read the website.
Only putting a single drop cap on stories.
Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/7845

Only put a drop cap on the first paragraph

---

common/model/image.ts
common/services/prismic/transformers/images.ts
common/views/components/PageLayout/PageLayout.tsx
content/webapp/components/ArticleCard/ArticleCard.tsx
content/webapp/components/BannerCard/BannerCard.tsx
content/webapp/components/BookPromo/BookPromo.tsx
content/webapp/components/Card/Card.tsx
content/webapp/components/EventCard/EventCard.tsx
content/webapp/components/EventPromo/EventPromo.tsx
content/webapp/components/MediaObject/MediaObject.tsx
content/webapp/components/SearchResults/SearchResults.tsx
content/webapp/components/SimpleCardGrid/SimpleCardGrid.tsx
content/webapp/components/VenueHours/VenueHours.tsx
content/webapp/pages/homepage.tsx
content/webapp/pages/newsletter.tsx
content/webapp/pages/season.tsx
content/webapp/services/prismic/transformers/contributors.ts
content/webapp/services/prismic/transformers/images.ts
content/webapp/types/card.ts
content/webapp/utils/page-header.tsx

The editorial team helpfully write detailed alt text descriptions for all our images, but we're duplicating them across every individual crop of an image -- even though they're often the same.
This patch introduces `simpleCrops` (which don't have custom alt text/tasl) and `richCrops` (which do).  This reduces the size of pages because we send less in `__NEXT_DATA__`:
<table>
<tr><th>page</th><th>before</th><th>after</th></tr>
<tr><td>/</td><td>279KB</td><td>264KB (−5%)</td></tr>
<tr><td>/stories</td><td>651KB</td><td>573KB (−12%)</td></tr>
<tr><td>/articles/YjMIUhEAACAAWeQ_</td><td>244KB</td><td>228KB (−7%)</td></tr>
<tr><td>/series/WleP3iQAACUAYEoN</td><td>1.5MB</td><td>1.3MB (−13%)</td></tr>
</table>
Replaces/closes #7838.
People who use the website.
Making it whizzy fast.

Only send alt/tasl once for images, not for every crop

---

common/views/components/TagsGroup/TagsGroup.tsx
content/webapp/components/Body/Body.tsx
content/webapp/components/SearchResults/AsyncSearchResults.tsx
content/webapp/services/prismic/transformers/body.ts
content/webapp/services/prismic/transformers/index.ts
content/webapp/services/prismic/types/body.ts

For https://github.com/wellcomecollection/wellcomecollection.org/issues/7753
This is continuing to break up the mega-long `transformBody()` method, and stick some types around it so we can keep leaning on the type checker.

Tidy up some of the body transformers

---

catalogue/webapp/components/ItemRequestModal/ItemRequestModal.tsx

People who don't want their holds to expire after 2(ish) days.
Relates to this conversation: https://wellcome.slack.com/archives/C3TQSF63C/p1648052162074989
This is a stop gap measure until we work out how to proceed.

adds 14 days to the default pickup date

---

common/data/microcopy.ts
content/webapp/__mocks__/events.ts
content/webapp/components/EventPromo/EventPromo.test.tsx
content/webapp/components/EventPromo/EventPromo.tsx
playwright/test/helpers/utils.ts

Closes #7818
Note there are past events that occurred at multiple physical locations and in order to handle these the content team created a new location called 'Throughout the building'. Since these will be read as single locations, they will continue to display as 'Throughout the building' on cards, unless they are retroactively updated to include the two or more _actual_ locations at which they occurred.

Event locations

---

content/webapp/components/EventsByMonth/EventsByMonth.tsx
content/webapp/components/EventsByMonth/group-event-utils.test.ts
content/webapp/components/EventsByMonth/group-event-utils.ts
content/webapp/services/prismic/events.test.ts
content/webapp/services/prismic/events.ts

Lalita has [pointed out in Slack](https://wellcome.slack.com/archives/C8X9YKM5X/p1648151459847929) that events are displaying in the wrong order: the April event appears before the March event:
But hold on… this is a filter tab for March events. Why is the April event even showing here?!
The answer is that I broke it, but because we only had a single upcoming event at the time, nobody noticed. The error was introduced in this PR: https://github.com/wellcomecollection/wellcomecollection.org/pull/7832/files#diff-e9bdfcf97955502ca4eebae736c06db00aa9a374235669cee4a0198696ee9b62
I got a list of events, then mapped them to a list of events with months, e.g.
```
[ { event: event1, months: [ { year: 2001, month: 1 } ] }]
[ { event: event2, months: [ { year: 2001, month: 1, year: 2002, month: 2 } …
```

Fix the grouping of events on event pages

---

common/utils/format-date.test.ts
common/utils/format-date.ts

This was a precursor for getting Moment out of this function, but it also uncovered a bug -- because `isBetween()` does an exclusive range (i.e. `a < x < b` rather than `a ≤ x ≤ b`), we'd show "Now on" for an exhibition that was on its final day.  This was caught by the test, and is now fixed.
This is rather important as we have an exhibition closing on Sunday!
People with an inability to plan in advance.
Making sure they know it's their last chance to see an exhibition.

Add some tests for formatDateRangeWithMessage; fix a bug with the last day of exhibitions

---

common/utils/format-date.ts

It's only doing comparisons of dates, which we can do with vanilla Date objects rather than calling out to Moment.
This follows #7863 and passes all the tests in that PR, unmodified.
Part of #7831.

Don't use Moment for formatDateRangeWithMessage

---

catalogue/webapp/components/ImageCard/ImageCard.tsx
common/views/components/StatusIndicator/StatusIndicator.tsx
content/webapp/components/FacilityPromo/FacilityPromo.tsx
content/webapp/data/facility-promos.ts
content/webapp/pages/whats-on.tsx
content/webapp/services/prismic/transformers/json-ld.ts
content/webapp/types/facility-promo.ts

I was getting some warnings about missing return types and use of `any`; this patch fixes them.  In particular, I've added a `FacilityPromo` type for use with the component of the same name, which lets me tidy up some of the facility promo data.
The daily tour promo isn't being used on the what's on page, and the data is duplicated in the DailyTourPromo component.  We can remove it from the what's on page and save a bit of data.

Fix a couple of warnings from the type checker

---

content/webapp/components/PrismicImage/PrismicImage.test.ts
content/webapp/components/PrismicImage/PrismicImage.tsx

Anyone who visits the site and looks at our content. Radius corners on the top left and right of our content cards have a thin black line. It only shows up on images with a light coloured background, as per bug in ticket https://github.com/wellcomecollection/wellcomecollection.org/issues/7626
This error is a little hard to pin down as zooming in, changing browser, sometimes refreshing the page will clear the issue. I had a go with changing css in developer tools when I could see the error and rounding out any vw (viewport width) values seemed to clear the issue. 
I convinced myself that rounding the vw value makes sense as we apply ratio logic to images (where in this case small images are 1/3 - hence us getting a 33.33333 value), but we don't apply that same logic to the background - so …

Trying to fix: Thin black line on radius corners of content cards

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx
catalogue/webapp/components/IIIFViewer/IIIFViewer.tsx
catalogue/webapp/components/IIIFViewer/ViewerSidebar.tsx
catalogue/webapp/pages/download.tsx
catalogue/webapp/utils/works.ts
common/package.json
common/utils/licenses.ts
common/views/components/Tasl/Tasl.tsx

We were using lodash.merge to combine two sources of license data.  The combined data was only being used in the Tasl component, and that component only needed one source of the license data.  This was completely wasteful and adding an unnecessary dependency; we can remove lodash.merge and make the license code easier to follow at the same time.
People who use our website.
Making it a tiny bit more smol.

Tidy up how we do licenses; toss lodash.merge

---

content/webapp/components/Body/Body.tsx
content/webapp/components/FeaturedCard/FeaturedCard.tsx
content/webapp/components/ImageGallery/ImageGallery.tsx
content/webapp/components/MediaObjectList/MediaObjectList.tsx
content/webapp/components/VenueHours/VenueHours.tsx
content/webapp/pages/homepage.tsx
content/webapp/pages/page.tsx
content/webapp/services/prismic/transformers/body.test.ts
content/webapp/services/prismic/transformers/body.ts
content/webapp/services/prismic/transformers/index.ts
content/webapp/types/body.ts
content/webapp/types/card.ts
content/webapp/types/generic-content-fields.ts
content/webapp/utils/page-header.tsx

This introduces a proper type for body slices that get rendered in components, rather than using `any`. This allows us to lean much more heavily on the type checker for these parts, rather than trusting that they're okay. It's the final part of the work to tidy up the body-handling code.
Because this is a potentially disruptive change, I've run the bulk Prismic checker against it locally; I'll update this PR note when it's done.
I also ended up slicing quite a bit out of the homepage and moving it to the server-side while getting this to compile. 🙌 
Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/7753

Introduce proper types for the Body slice, not 'any'

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx

People looking at restricted digitised items, e.g. the audio file on https://wellcomecollection.org/works/ae9m5mbx
Making sure a broken audio player doesn't appear on the page.
I've tested this locally and confirmed that (1) the audio player no longer appears when it's restricted and (2) the audio player still appears when it's open.
For https://github.com/wellcomecollection/wellcomecollection.org/issues/7861

If an item is restricted, don't show it on the page

---

identity/webapp/src/frontend/MyAccount/ChangePassword.test.tsx
identity/webapp/src/frontend/MyAccount/ChangePassword.tsx
identity/webapp/src/frontend/hooks/useUpdatePassword.ts

Anyone who wants to change their password and be told there's a repeated pattern that is not accepted by sierra.
https://github.com/wellcomecollection/wellcomecollection.org/issues/7816
Previously a patron would get an 'unknown error' when these error occurred. I was trying to just catch the full error in Identity and show that in the relevant place, then realised I would need to make sure that happens where ever we render the change password modal. Last week I thought the modal comes from auth0 direct, but we actually handle the rendering of this in experience. I allowed for the specific case of repeated characters being used in the error cases within updatePassword. While I was there I updated the 'unknown error' to something more like what we have already as a default error elsewhere …

Surface repeated character pattern in updated password change modal

---

content/webapp/services/prismic/transformers/events.test.ts
content/webapp/services/prismic/transformers/events.ts

We currently only search for a number after the `/e/` in the eventbrite URL, but eventbrite urls now contain part of the events title also. It's fair to say _anything_ after the `/e/` is the ID, so switching the regex from `[0-9]` to `.` seems reasonable.

Make regex for eventbrite id more permissive

---

content/webapp/pages/event.tsx

Everyone
Moving the more relevant event content closer to the top of the page

Move event contributors below yellow box

---

cardigan/Dockerfile
cardigan/run_yarn.sh

Devs.
Trying to make the experience build a bit faster; the Cardigan build dominates pull request builds and I think we can get a fairly quick win; locally this shaves off about a minute off the build.
I'm sure we can make it faster still, but this change doesn't require as much investigation/thinking.

Run the yarn commands in a single Docker step

---

content/webapp/components/CardGrid/CardGrid.tsx
content/webapp/services/prismic/transformers/projects.ts
content/webapp/types/card.ts
content/webapp/types/projects.ts

Danny.
Making project pages appear on season pages, per [his request in Slack](https://wellcome.slack.com/archives/C8X9YKM5X/p1649662725784829). We're already fetching them in the page's server-side props, but then they were being passed to the CardGrid component, which didn't know how to render them – this should fix that.
I also tweaked the Project model so we get the label telling us what sort of thing this project is (e.g. "Film").

Make sure we show projects on season pages

---

common/views/components/Footer/FooterSocial.tsx

Fans of branding and spelling.
Getting the Tripadvisor brand right.

Don't intercap the name "Tripadvisor" in the footer

---

common/server-data/prismic.ts
common/services/prismic/documents.ts
common/services/prismic/transformers/index.ts
common/services/prismic/types/index.ts
common/views/components/PopupDialog/PopupDialog.tsx
content/webapp/services/prismic/transformers/articles.ts
content/webapp/services/prismic/transformers/body.ts
content/webapp/services/prismic/transformers/books.ts
content/webapp/services/prismic/transformers/card.ts
content/webapp/services/prismic/transformers/contributors.ts
content/webapp/services/prismic/transformers/event-series.ts
content/webapp/services/prismic/transformers/events.ts
content/webapp/services/prismic/transformers/exhibitions.ts
content/webapp/services/prismic/transformers/featured-books.ts
content/webapp/services/prismic/transformers/index.ts
content/webapp/services/prismic/types/index.ts
content/webapp/services/prismic/types/types.test.ts

Just remembered when I was working on #7828, I noticed that the link in the popupDialog component is broken.
It meant moving a few bits from /content to /common so I could use transformLink, which is why there are so many file changes.
Before:
After:

Popup link

---

content/webapp/components/Contributors/Contributor.tsx

Ben.
Picking the correct contributor image. See https://wellcome.slack.com/archives/C8X9YKM5X/p1650539203095679
As best I can tell, this has only ever worked by coincidence – we'd use the default crop of the contributor image, which has always been a square crop. It's only when we got a contributor image which was rectangular that this bug finally became noticeable (although it might affect older pages too).
Verified as working locally.

Make sure we pick the square image for contributors

---

catalogue/webapp/components/Calendar/Calendar.tsx

Relates to #7756
Using the month controls on the calendar could lead to a situation where a user could tab to a date outside the available range. This stops that from happening

Calendar bug

---

content/webapp/components/Contributors/Contributor.tsx

Lalita.
Making sure we display the contributor image on event pages; see https://wellcomecollection.org/events/YkMWAhEAAB8AotED
This is a bug I introduced in #7910 yesterday; we should _prefer_ the square crop if it's available, but we can't rely on it being present.

Use the default contributor image if there's no square crop

---

common/test/fixtures/catalogueApi/work.ts
common/test/fixtures/catalogueApi/works-aggregations.ts
common/views/components/SearchFilters/SearchFiltersDesktop.tsx
playwright/test/works-search.test.ts

There are 3 types of availability, so we're making it into a dropdown - this "just works". To be (vaguely) synchronised with the deployment of https://github.com/wellcomecollection/catalogue-api/pull/395.

Availabilities are now like other filters

---

common/views/components/SearchForm/SearchForm.tsx

Some users want to be able to do a filters-only search, they already have the option of navigating to `/works` but this makes it a bit easier to get there

Search query input is not required

---

catalogue/webapp/components/Work/Work.tsx

☝️
In order to overlay heatmap data on an archive page, we need to use [hotjar events](https://help.hotjar.com/hc/en-us/articles/115011867948) as there's nothing in the URL to distinguish a work from an archive work.

Add 'view_archive' event for heatmap trigger

---

content/webapp/components/EventsByMonth/EventsByMonth.tsx
content/webapp/components/EventsByMonth/group-event-utils.test.ts
content/webapp/components/EventsByMonth/group-event-utils.ts

Lalita.
Making the dates _right order in display the_ on the what's on page: https://wellcome.slack.com/archives/C8X9YKM5X/p1651224877047299
I haven't checked, but this bug was probably a casualty of some of my Moment-esque refactoring. Inevitably, the bit of code I thought I was leaving as-is and didn't test had a bug in it…

Fix the sorting of events on the "What's on" page

---

content/webapp/components/Body/Body.tsx
content/webapp/components/SoundCloudEmbed/SoundCloudEmbed.tsx

This is modelled on the existing VideoEmbed component, and adds the caption that was previously missing.
Alice.
Making her Soundcloud embed look right. See https://wellcome.slack.com/archives/C8X9YKM5X/p1651580465819869

Create a new SoundcloudEmbed component with a caption

---

content/webapp/pages/api/exhibitions-related-content/index.ts

Normally we pass the exhibition we want to get related content for in the `params` query parameter, but something has been hitting the API and not passing that -- then `parsedParams` becomes undefined, and getting the length of it throws a type error.
You can't do anything useful with this endpoint, so just 400 out.

Don't throw a 500 error on /api/exhibitions-related-content

---

identity/webapp/pages/api/registration.ts

☝️ 
Because [the ID will always include a `p`](https://github.com/wellcomecollection/identity/pull/293#issuecomment-1120913520)

Stop the p from being optional in userIdPrefix

---

common/hooks/useHotjar.ts

[Hotjar `trigger` is now `event` ](https://help.hotjar.com/hc/en-us/articles/4405109971095-Events-API-Reference#the-events-api-call) and we need to update our `hj` call in order for the new [continuous heatmaps](https://www.hotjar.com/updates/en/onwards-and-upwards-why-and-when-continuous-heatmaps-are-replacing-manual?role=s_HCWoPasV913%3Bs_iSDiKvEm1499%3Bs_pJcjHVwD740%3Bs_OAVVeiyc1497%3Bs_BBKvqAbk2285%3Bs_mqLymRsT1519) to be filterable by any events that we send.

Update Hotjar events API call

---

common/hooks/useHotjar.ts

There's discrepancy in the Hotjar docs about whether event names should be passed as a [string](https://help.hotjar.com/hc/en-us/articles/4405109971095-Events-API-Reference#the-events-api-call) or as an [array of strings](https://help.hotjar.com/hc/en-us/articles/360034216634-Hotjar-JavaScript-Functions-Reference#event).
I previously picked the wrong one.

Use string instead of array for event

---

identity/webapp/pages/api/users/[[...users]].ts

This should make problems like the cert expiry from earlier easier to detect

Handle identity API proxy errors which don't have a response

---

content/webapp/pages/api/articles/index.ts
content/webapp/pages/api/events/index.ts
content/webapp/pages/api/exhibitions/index.ts

If you look in our CloudFront logs, you see a stack of errors from API endpoints like `/api/events` when you don't pass any parameters; this patch makes them 404 instead of 500.

Less 500 errors from API endpoints

---

content/webapp/components/Exhibition/Exhibition.tsx
content/webapp/components/Installation/Installation.tsx
content/webapp/pages/article.tsx
content/webapp/pages/event.tsx
content/webapp/pages/events.tsx
content/webapp/pages/exhibition.tsx
content/webapp/pages/exhibitions.tsx
content/webapp/pages/homepage.tsx
content/webapp/pages/page.tsx
content/webapp/pages/season.tsx
content/webapp/pages/whats-on.tsx

Easy performance win; it allows us to shake some transformer code out of the client bundle.
We have actually done this once before, but I bundled it in with some unrelated changes to venue handling which caused breakage, so we ended up rolling it all back (because of the way objects get mangled when they pass through server-side props) – but JSON-LD is already JSON, so passing it through the JSON props shouldn't be an issue.

Render JSON-LD on the server side

---

common/views/components/SelectContainer/SelectContainer.tsx

People who want to be able to see all of the letters in a select box
__Before__
__After__

Prevent descenders getting chopped off in Select component

---

content/webapp/app.ts
content/webapp/pages/page.tsx

This makes a couple of improvements to our vanity URLs:
* If you land on a page with a vanity URL, you get redirected to the correct page. This is particularly useful when crossing templates, e.g. https://wellcomecollection.org/pages/XphUbREAACMAgRNP is pretty useless, because that page ID is a placeholder for the homepage.
Although this is also handled by a CloudFront redirection Lambda, there are a few cases (e.g. /visit-us, /collections) where that's not working correctly.
* We use the vanity URLs for the `<link rel="canonical">` in the header of the page, so we get the correct URLs in e.g. Google search results.
This alone isn't especially interesting, but it means we can be sure that if somebody is looking at `/visit-us` or `/collections`, they're doing it through the vanity URL and …

Improve how we use vanity URLs on the site

---

content/webapp/app.ts
content/webapp/components/Body/Body.tsx
content/webapp/pages/collections.tsx
content/webapp/pages/page.tsx
content/webapp/pages/visit-us.tsx

I don't know if we actually want to merge this, but I wanted to play around a bit with Next and routes and do a bit more React work.
This takes the CollectionsStaticContent component off the critical path for pages, and only loads it if you hit `/collections` (which thanks to #7973, you'll land on even if you're at `/pages/$collectionsPageId`). This should mean we don't have to load the Collections search form (or filters, or tabs, or anything else) if you're not specifically on a collections page.
I've checked both these pages are still loading their static content correctly.

Split out the collections/visit us static content

---

.stylelintrc
cardigan/stories/components/CaptionedImage/CaptionedImage.stories.mdx
cardigan/stories/components/CaptionedImage/CaptionedImage.stories.tsx
common/views/components/Images/Images.tsx
common/views/components/Picture/Picture.tsx
common/views/components/Tasl/Tasl.tsx
common/views/themes/utility-classes.ts
content/webapp/components/Body/Body.tsx
content/webapp/components/CaptionedImage/CaptionedImage.tsx
content/webapp/components/DeprecatedImageList/DeprecatedImageList.tsx
content/webapp/components/GifVideo/GifVideo.tsx
content/webapp/components/ImageGallery/ImageGallery.tsx
content/webapp/components/PrismicImageWithTasl/PrismicImageWithTasl.tsx

Relates to #7932
- Puts the CaptionedImage component in it's own file
- Converts it to a functional component
- Makes use of the [aspect-ratio CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio) to simplify the component (we'd previously been [calculating image widths and changing CSS properties with javascript](https://github.com/wellcomecollection/wellcomecollection.org/pull/3414) in order to achieve the required layout)
- Creates a PrismicImageWithTasl component to use inside CaptionedImage

Captioned image refactor

---

cardigan/stories/components/PageHeader/PageHeader.stories.tsx
content/webapp/components/BookImage/BookImage.tsx
content/webapp/components/BookPromo/BookPromo.tsx
content/webapp/pages/book.tsx

Relates to #7932
Using PrismicImage for book images and have tweaked the BookImage component, so we can use it in both the BookPromo component and on the book page, rather than replicating styles in both places.

Book images

---

content/webapp/components/CaptionedImage/CaptionedImage.tsx

The [CaptionedImage refactor](https://github.com/wellcomecollection/wellcomecollection.org/pull/7963) makes use of the CSS aspect-ratio property to simplify and improve the performance of the component. However, it changes the display of captioned images quite dramatically for [browser that don't support the property](https://caniuse.com/mdn-css_properties_aspect-ratio)
This PR provides a better experience for users of those browsers, by making it behave much more like browsers that do support it, i.e. displaying the images at a reasonable size.
Before:
After:

fallback for browsers that don’t support aspect-ratio

---

common/views/components/CookieNotice/CookieNotice.tsx

Another small optimisation I noticed -- we want to remember a user has accepted cookies for the next month, but we don't need the exact timezone accuracy provided by Moment.  Using the built-in Date object is plenty good enough for this purpose.

Don't use Moment for cookie preferences

---

common/views/themes/inter-typography.ts
content/webapp/components/PageHeaderStandfirst/PageHeaderStandfirst.tsx

Fixing the font size media query that still needs to respond to `px` even though the font values are in `rem`.
Standfirst should be the same font size as body copy, so undoing that change also.

Fix inter media query

---

catalogue/webapp/components/Work/Work.tsx

☝️ 
Hotjar not giving us enough useful insight for archives quick enough so turning off for at least as long as we need to collect data on the learning resource pages

Remove hotjar from archive pages

---

cache/.terraform.lock.hcl
cache/README.md
cache/edge_lambdas/README.md
cache/edge_lambdas/src/redirects.ts
cache/locals.tf
docker-compose.yml

After I was mucking around in vanity URLs, we ended up with a redirect loop:
```mermaid
graph TD
A(/pages/Wuw2MSIAACtd3Ste) -->|edge Lambda| vanity
vanity["/youth"] -->|edge Lambda| B(/pages/Wuw2MSIAACtd3Ssg)
B -->|front-end app| vanity
```  
- Wuw…Ssg is the ID of the page in Prismic
- Wuw…Ste doesn't seem to exist
I've left the non-existent page ID in place, in case it's significant, and removed the redirect in the Edge Lambda from /youth to the page ID. This seems to get the page working, which is what we want.
I've also added more instructions about how to manage these Lambdas.

Don't try to redirect /youth inside the Edge Lambda

---

common/test/utils/convert-image-uri.test.ts
common/utils/convert-image-uri.ts
common/utils/json-ld.ts
common/views/components/Image/Image.tsx
common/views/components/JsonLd/JsonLd.tsx
common/views/components/PageLayout/PageLayout.tsx
common/views/components/Picture/Picture.tsx
content/webapp/components/BannerCard/BannerCard.tsx

Small optimisation I've been sitting on for a while.
We had a method `convertImageUri` which took an image URI and a desired size, and would:
1. Infer whether it’s a Prismic or IIIF image
2. Call the appropriate helper function to create a right-sized image URI
But step 1 is somewhat redundant – we can always tell from context whether an image URI will be from Prismic or IIIF, and call the appropriate helper. We already call the dedicated helper for IIIF images without doing any inference on the URL; this patch does the same for Prismic images.

Tidy up the convert-image-uri helper

---

common/views/themes/utility-classes.ts

Specifies a background colour and colour for the noscript tag, which should stop pa11y complaining

Keep pa11y happy

---

catalogue/webapp/components/ItemRequestModal/ConfirmedDialog.tsx
identity/webapp/pages/index.tsx

I've used the word 'pickup' because it is how it appears in the column headings. I'd probably have plumped for 'pick-up' otherwise.

Success date

---

catalogue/webapp/test/components/ItemRequestModal.test.tsx

Fixes the breaking test on main

render component on specific date, so test data remains valid

---

prismic-model/src/events.ts

Relates to #7983
I was hoping that I'd just be able to add another field to capture the Eventbrite link for online version of the event.
However, after chatting to @dannybirchall it seems we'll want all the same fields that are exposed under the reservation tab in Prismic to be available for the online version as the details may differ between the two types.
This basically replicates the fields in the model, with an online prefix and puts them behind a seperate tab in the Prismic UI, so it's easier for content editors to distinguish between the two.

Creates another tab in Prismic for adding an online reservation

---

catalogue/webapp/components/ImageCard/ImageCard.test.tsx
common/utils/convert-image-uri.ts
common/views/components/JsonLd/JsonLd.tsx
common/views/components/Picture/Picture.tsx

Devs.
Making sure they don't break components unexpectedly.
This salvages the usable bits of https://github.com/wellcomecollection/wellcomecollection.org/pull/7987, and adds a regression test for the component that actually broke – a IIIF info URL was being passed in and not converted properly.

Add a regression test for the ImageCard component

---

common/views/themes/inter-typography.ts

☝️ 
Using `em`s instead of `rem`s means that the letter spacing will remain proportional when the font-size changes at different breakpoints.

Use em for letter-spacing

---

common/views/themes/base/fonts.ts

[Strange A in Inter](https://wellcome.slack.com/archives/C8X9YKM5X/p1653423700761289) e.g. in the title of [this page](https://wellcomecollection.org/works/va2vy7wb).
[Issue in Google fonts](https://github.com/google/fonts/issues/2602)
Using the font downloaded direct from [the designer's site](https://rsms.me/inter/) rather than using the [conversion tool](https://google-webfonts-helper.herokuapp.com/fonts/inter?subsets=cyrillic,cyrillic-ext,greek,greek-ext,latin,latin-ext,vietnamese) (which operates on Google fonts) solves the issue. The conversion tool allowed for subsetting character sets, but since we need all of them I don't think fact we can no longer do this is a problem.
__Before__
__After__

Use Inter direct from rsms.me/inter

---

content/webapp/components/Exhibition/Exhibition.tsx
content/webapp/components/SearchResults/SearchResults.tsx
content/webapp/pages/api/exhibitions-related-content/index.ts
content/webapp/services/prismic/transformers/exhibitions.ts
content/webapp/types/exhibitions.ts

Content team ([from Slack](https://wellcome.slack.com/archives/C8X9YKM5X/p1653472879466709))
Allowing them to add story series as related items on an exhibition page

Allow story series in the 'About this exhibition' section

---

.buildkite/pipeline.deployment.yml
.buildkite/pipeline.yml
pa11y/README.md

People who look at the pa11y dashboard.
Tentatively fixing https://github.com/wellcomecollection/wellcomecollection.org/issues/3728. Gareth mentioned in standup that our pa11y dashboard is always one deploy behind, because we run it as part of the merge to main – before we deploy. By moving it to run after a prod deploy is complete, I think we'll get more up-to-date results?

Deploy pa11y after a prod deploy

---

common/utils/dates.ts
content/webapp/components/EventCard/EventCard.tsx
content/webapp/services/prismic/transformers/exhibitions.ts

Related to #8030
Historically it didn't make sense to show past events as related content for exhibitions. But now some events are made available online, we still want those to show up even if they happened in the past IRL.
We fetch these client-side and as a result, the dates are formatted as strings initially. This PR adds a function to make sure that we're using dates where we rely on the `Date` API.
I think we might want to update the[ `DateTimeRange` type](https://github.com/wellcomecollection/wellcomecollection.org/blob/12d01bcc9e1044f0fb4e3d9be138391413d25ac9/content/webapp/types/events.ts#L12-L15) to reflect that these _could_ be strings, but I imagine that will require a larger PR to fix all the issues that would ensue.

Allow past events to display on exhibitions if they're available online

---

catalogue/webapp/components/LibraryMembersBar/LibraryMembersBar.tsx
catalogue/webapp/components/PhysicalItemDetails/PhysicalItemDetails.tsx
common/data/microcopy.ts
toggles/webapp/toggles.ts

Fixes #8010
- ~Replaces the "sign into your library account to request items" message, with "requesting is currently unavailable". (This will show regardless of whether the user is logged in or not)~
- ~Adds a note to say when requesting will be available again.~
When switched on the toggle:
- Removes the 'Request item' button
- Replaces the "sign into your library account to request items" message, with a message to say requesting is unavailable until a specific date. (This will show regardless of whether the user is logged in or not)

Requesting toggle

---

common/services/prismic/index.test.ts
common/services/prismic/index.ts
common/views/components/ApiToolbar/ApiToolbar.tsx
content/webapp/pages/article-series.tsx
content/webapp/pages/article.tsx
content/webapp/pages/book.tsx
content/webapp/pages/event-series.tsx
content/webapp/pages/exhibition.tsx
content/webapp/pages/season.tsx

Content editors. Also me.
Making it easier to find where a page is defined in the Prismic web editor, by adding an inferred link to the API toolbar.
This has several shortcomings:
* Some pages won't have it, in particular ones where we infer the page ID (the homepage, /visit-us, /collections, /stories)
* It's not 100% guaranteed to be a working URL – it's using a crude heuristic, not anything we get from Prismic itself. In particular I think it might fail for unpublished pages, but those are probably near the top of the list of entries in Prismic.
* Is it part of the API? Ehhhhhh… but this component is not exactly designed or curated; it's a collection of quick wins to make staff's lives easier rather than a properly-designed component, and this doesn't make it better or worse.

Link to Prismic pages from the API toolbar

---

content/webapp/components/EventCard/EventCard.tsx

When an event is listed as being related to an exhibition and we're displaying it because it is available online, we need to let people know that's why. If it is past, the dates and the status aren't useful to people under these circumstances.
__Before__
__After__

Show appropriate info on compact event cards

---

cache/edge_lambdas/Dockerfile
cardigan/Dockerfile
catalogue/Dockerfile
common/Dockerfile
content/Dockerfile
dash/Dockerfile
identity/Dockerfile
lighthouse/server/Dockerfile
pa11y/Dockerfile
prismic-model/Dockerfile
toggles/Dockerfile
updown/Dockerfile

I also took the opportunity to consolidate onto a single image for each major version of Node, and switch to -slim images which are much smaller.
For https://github.com/wellcomecollection/platform/issues/5545, which includes a discussion of the benefits.

Use Node images from ECR Public, not our vendored repos

---

prismic-model/src/events.ts

Relates to #7983
Adds a new field for specifying if online tickets are fully booked and changes the label of the current isFullyBooked field

update events model

---

common/views/components/Label/Label.tsx

Part of #8041 
Design QA on the labels to reduce padding from 6 to 4 px after the switch from Helvetica to Inter

Reduce label padding

---

.buildkite/expected_200_urls.txt
content/webapp/pages/articles.tsx

Devs.
Making sure we don't alarm on somebody doing this. They won't get particularly insightful results, but nor will they pop an alarm for us to triage:

Don't throw a 500 error if somebody paginates off the end of /articles

---

content/webapp/components/Body/Body.tsx
content/webapp/pages/stories.tsx

Part of #8041 
https://user-images.githubusercontent.com/1394592/171401161-9df42dc5-d464-460f-8700-98fb17100b5a.mp4
Using the `PageHeader` component on the Stories page, and removing top padding from body sections that have a white background.

Rationalise page header spacing

---

content/webapp/services/prismic/transformers/exhibitions.test.ts
content/webapp/services/prismic/transformers/exhibitions.ts

The downstream code expects this to be of type `ImagePromo`; a lot of these fields aren't on ImagePromo, and it's missing the caption which is used to populate the metadata for social media cards.
We already have the promo from transformGenericContentFields(), so let that value through rather than replacing it.
Fixes https://github.com/wellcomecollection/wellcomecollection.org/issues/8044

Don't overwrite the promo field in the Exhibition transformer

---

catalogue/webapp/app.ts
catalogue/webapp/pages/concept.tsx
catalogue/webapp/services/catalogue/concepts.ts
common/model/catalogue.ts
common/services/catalogue/ts_api.ts
toggles/webapp/toggles.ts

Devs.
Establishing the bare bones of a page for individual concepts. Right now it just spews JSON onto the page, so nobody can mistake it for something actually designed, and then we can start to finesse it into Gareth's designs.
Mostly this is about the internal mechanics for the front-end app:
* Creating a toggle for concepts
* Talking to the catalogue API
* Creating a basic route for per-concept pages
I got this by copy/pasting the similar code for work pages.

Add a concepts toggle and a bare-bones page

---

cache/modules/wc_org_cloudfront/distribution.tf
cache/modules/wc_org_cloudfront/waf.tf
catalogue/terraform/stack/main.tf
catalogue/webapp/app.ts

For https://github.com/wellcomecollection/platform/issues/5539
People working on concepts.
Letting them see the shiny new pages.

Make sure concepts pages are routed to the catalogue app

---

content/webapp/components/Body/CollectionsStaticContent.tsx

Removing top padding from 'landing-page' rows with white backgrounds has caused the search box on `/collections` to be too close to the rest of the page content. Wrapping the search box in a `SpacingSection` tidies this up.
__Before__
__After__

Add space below search tabs

---

.buildkite/urls/expected_200_urls.txt

https://github.com/wellcomecollection/wellcomecollection.org/pull/8068 would not in fact have caught our incident with images not loading, because it wouldn't have looked at the images search page - this fixes that and adds checks for a few more catalogue URLs.

Check more URLs

---

playwright/package.json
playwright/test/contexts.ts
playwright/test/helpers/utils.ts
playwright/test/stories.test.ts
playwright/test/view-items.test.ts
playwright/tsconfig.json
playwright/yarn.lock

https://github.com/playwright-community/jest-playwright is not compatible with jest 28 - it's also deprecated, so I'll have a go at ripping it out too. The changes to tsconfig required a few changes here as well.

Fix e2e tests

---

identity/webapp/pages/registration.tsx
identity/webapp/src/frontend/Registration/RegistrationInformation.tsx

Part of #7808 and #7812
Removing the `withPageAuthRequiredSSR` wrapper because a user isn't signed in at this part of the journey.
Adding the prospective user's email (that they entered in the previous signup screen) to the `sessionToken` (JWT) and reading it out from there. Also using the validity of this token to determine whether or not you're allowed to stay on the page, or be redirected away.

Update registration page

---

content/webapp/pages/page.tsx
content/webapp/services/prismic/transformers/pages.ts

Devs.
Kate spotted we weren't rendering the description on the Visual Stories page (now fixed): https://wellcome.slack.com/archives/C3N7J05TK/p1655712995336529
The issue is fixable in Prismic so that's what we've done; this should make it slightly easier to spot what's happening if/when the issue recurs. I don't want to open a broader discussion about a small detail of promos right now.

Small improvements to dev experience with page promo text

---

identity/terraform/locals.tf

Initially, David and I so that we can be sure weco frontend identity is using the same secret as the action in identity api. Hopefully, ultimately, this is something for anyone who wants to be able to register. 
Providing the `process.env` variable we need for decoding the token
```
Terraform will perform the following actions:
~ resource "aws_iam_role_policy" "allow_read_secrets" {
id     = "identity-18012021-prod_execution_role:terraform-[redacted]"
name   = "terraform-[redacted]"
~ policy = jsonencode(
~ {
~ Statement = [
~ {
~ Resource = [
+ "arn:aws:ssm:eu-west-1:[redacted]:parameter/aws/reference/secretsmanager/identity/prod/redirect_action_secret",
"arn:aws:ssm:eu-west-1:[redacted]:parameter/aws/reference/secretsmanager/identity/prod/account_management_system/session_keys",
]
},
~ …
```

update terraform to provide variable to identity frontend

---

cardigan/stories/components/Cards/Cards.stories.tsx
cardigan/stories/components/PageHeader/PageHeader.stories.tsx
cardigan/stories/components/SeasonsHeader/SeasonsHeader.stories.tsx
cardigan/stories/components/WobblyBottom/WobblyBottom.stories.tsx
common/views/components/HeightRestrictedPrismicImage/HeightRestrictedPrismicImage.tsx
common/views/components/Iframe/Iframe.tsx
common/views/components/PrismicImage/PrismicImage.tsx
content/webapp/components/ArticleCard/ArticleCard.tsx
content/webapp/components/BookImage/BookImage.tsx
content/webapp/components/BookPromo/BookPromo.tsx
content/webapp/components/CaptionedImage/CaptionedImage.tsx
content/webapp/components/Card/Card.tsx
content/webapp/components/CompactCard/CompactCard.test.tsx
content/webapp/components/ContentPage/ContentPage.tsx
content/webapp/components/Contributors/Contributor.tsx
content/webapp/components/EventCard/EventCard.tsx
content/webapp/components/EventPromo/EventPromo.tsx
content/webapp/components/ExhibitionPromo/ExhibitionPromo.tsx
content/webapp/components/FacilityPromo/FacilityPromo.tsx
content/webapp/components/FeaturedCard/FeaturedCard.tsx
content/webapp/components/MediaObject/MediaObject.tsx
content/webapp/components/MediaObjectBase/MediaObjectBase.test.tsx
content/webapp/components/SearchResults/SearchResults.tsx
content/webapp/components/StoryPromo/StoryPromo.tsx
content/webapp/components/VenueHours/VenueHours.tsx
content/webapp/pages/book.tsx
content/webapp/pages/page.tsx
content/webapp/pages/season.tsx
content/webapp/utils/page-header.tsx

Fixes #8026
- Makes the quality prop of the PrismicImage components compulsory and one of three named values.
- Uses the low quality for the small promo/card images as it greatly reduces the page weight of listing pages.
- All other image qualities remain as they were previously

Image quality

---

assets/terraform/.terraform.lock.hcl
cardigan/terraform/.terraform.lock.hcl
cardigan/terraform/terraform.tf
dash/terraform/.terraform.lock.hcl
dash/terraform/terraform.tf
infrastructure/modules/s3_website/s3.tf
static/terraform/.terraform.lock.hcl
static/terraform/terraform.tf
toggles/terraform/.terraform.lock.hcl
toggles/terraform/terraform.tf

For https://github.com/wellcomecollection/platform/issues/5557. These are all no-op changes in Terraform.

Remove the deprecated template provider from the s3_website provider

---

cache/edge_lambdas/src/redirects.ts
cache/modules/cloudfront_policies/locals.tf
catalogue/webapp/pages/images.tsx
common/model/catalogue.ts
common/services/catalogue/api.ts
common/services/catalogue/filters.ts
common/services/catalogue/ts_api.ts
common/views/components/ImagesLink/ImagesLink.tsx
content/webapp/pages/collections.tsx

Users.
Allowing them to filter by subjects in the front-end. The filters/aggregations are plumbed into the API and are unlikely to change, so we can add it to the front-end as a useful feature.
It's also part of the (future) onward journey for concepts. If a researcher lands on a concept page and sees a sample of images associated with that subject, they can click through to the images search to see the full list.
For https://github.com/wellcomecollection/platform/issues/5556

Add subjects to the front-end image search

---

common/services/prismic/transformers/index.test.ts
common/services/prismic/transformers/index.ts
common/services/prismic/types/index.ts

Tracing through the code, the problem is that when we fetch the project, we don't fetch a `data` field on the document.  This causes transformLink() to discard the entire link, and then the card doesn't go anywhere.
I don't think we need to check there's data behind the document here -- we only use the ID and type to create the link, so knowing that the link isn't broken should be sufficient.
(The alternative is updating the fetcher to get the `data` field, but since we'd instantly discard it that seems wasteful.)
Danny.
Making the top homepage card clickable.

Fix a broken link on the homepage

---

.buildkite/pipeline.e2e-universal.yml
playwright/.dockerignore
playwright/test/contexts.ts

Wonder how many commits I've made with this claim now! See the big comment in the PR for context. The exposure of the `CI` environment variable to the container I've added here should mean that test output is more readable in Buildkite, too.
Linking the issue in the comment here for any other adventurers out there https://github.com/microsoft/playwright/issues/12182

Hopefully fix e2e tests

---

content/webapp/components/Card/Card.tsx

Part of #8083 
When cards have a background colour, having the 'Part of' attached to the bottom looks intentional. But when the cards are transparent, having the 'Part of' as far below the body content as whatever happens to be size of the largest bit of card body content in the row (plus some arbitrary margin) can look strange and disconnected (especially if there's a large disparity in body content lengths).
If the cards are on a transparent background, we put the 'Part of' directly below the body content instead. This affects two areas of the site:
- bottom of the homepage:
- top of the stories page:

Don't flex the card body if it's on a transparent back ground

---

common/views/components/Breadcrumb/Breadcrumb.tsx

Closes #8083 
Using a pipe (`|`) character rather than a css border for the breadcrumb divider, and using equivalent font size/spacing as for the contributor information below.

Use same space/size/pipe logic for part of as for contributor info

---

common/data/microcopy.ts
content/webapp/components/ExhibitionPromo/ExhibitionPromo.tsx
content/webapp/pages/exhibitions.tsx
content/webapp/types/exhibitions.ts

Relates to #8019 and applies the changes discussed with @DominiqueMarshall 
Namely:
- Splitting the exhibitions into 2 distinct groups with headers and a strapline for past exhibitions
- removing the background from past exhibition cards
- removing the 'past' status from past exhibition cards
N.B I'm unable to remove the bold from the page header without affecting all page headers on the site.

Exhibitions current past

---

content/webapp/components/CardGrid/CardGrid.tsx

While I was catching up with the guides workshop I was looking at the /guides page we already have and noticed the cards weren't displaying.
Before:
After:

render cards for guide type

---

identity/webapp/jest.config.js
identity/webapp/pages/api/registration.test.ts
identity/webapp/pages/api/registration.ts
identity/webapp/pages/registration.tsx
identity/webapp/src/utility/auth.ts
identity/webapp/src/utility/jwt-codec.ts

Current status: early draft. This needs some comments and tidy-up and maybe some testing; for now I wanted to get an end-to-end flow working. I can see it hitting the identity API endpoint and returning a known error which should be fixed once https://github.com/wellcomecollection/identity/pull/348/ is deployed, so I think it's close to working.
New members!
Making sure they can complete the sign-up flow.

Call the registration API from the identity web app

---

catalogue/webapp/components/ItemRequestModal/RequestDialog.tsx
catalogue/webapp/components/ItemRequestModal/useAvailableDates.ts
catalogue/webapp/utils/dates.ts
common/utils/format-date.ts

Fixes #8095
There were a couple of things happening here:
- we were using the selected pick up date to create a Moment with a London timezone. This was problematic because if the user was in a different timezone it could erroneously change the date.
- the function to determine if the selected date was a valid date to choose was taking timezones into account, when it shouldn't have, it just needs to compare the day, which it now does.

Date picker bug

---

identity/webapp/src/app.ts

Us.
Making sure we don't log PII about library users into the Kibana logging cluster.
This is an issue for registration, where information about users is being passed around in JWTs that can easily be decoded to reveal email addresses and IP addresses, possibly more. You can see an example of one such log in Slack here: https://wellcome.slack.com/archives/CUA669WHH/p1656593517407499?thread_ts=1656593455.081159&cid=CUA669WHH
As the comment explains, this new logger will redact all query parameters in logs, so we won't routinely be logging sensitive tokens to Kibana.

Redact all query parameters from the identity app in logs

---

identity/webapp/pages/index.tsx
identity/webapp/pages/success.tsx

The comment on the index page explains how this works; I haven't found a good way to refresh the user metadata in Auth0 without a log-in, and at this point I'd rather get _something_ working than keep plugging away at what's a relatively small part of the process.
The copy on the success page will need reviewing properly, but I think this is good enough to prove the concept.
(I haven't been able to test this because going through the login page on staging kicks you to `www-stage.wc.org`, so this will need to be tested in staging – but I think it looks plausible.)

Log out the user post-registration; kick them to a success page

---

common/services/catalogue/filters.ts
common/views/components/PaletteColorPicker/PaletteColorPicker.tsx

Previously, if a user selected a colour filter in the UI, it would be labelled as simply "Colour", which is completely unhelpful for colour-blind users.  Now, we show either the name from our pre-selected palette or the hex code of the colour they picked.
This is the picker UI it's meant to match:

Use the name of the colour in the colour filter label

---

catalogue/webapp/app.ts
catalogue/webapp/pages/concepts.tsx

Spun out of #8061.
People testing the concepts prototype.
Giving them a list of concepts to click on.
If you have the `conceptsPages` toggle, this page will give you a mostly random selection of concepts pages to go and look at.

Add a very rudimentary "list of concepts" page

---

identity/terraform/.terraform.lock.hcl
identity/terraform/stack/main.tf
infrastructure/modules/service/main.tf
infrastructure/modules/service/variables.tf

For https://github.com/wellcomecollection/wellcomecollection.org/issues/8121
This uses the custom Docker image defined in https://github.com/wellcomecollection/platform-infrastructure/pull/312. It's already deployed in staging and tested as working.

Redact PII in nginx logs from the identity web app

---

content/webapp/components/HTMLSerializers/HTMLSerializers.tsx

Among other things, this will let us link directly to specific policies on https://wellcomecollection.org/pages/Wvmu3yAAAIUQ4C7F
People working on membership.
Giving them a way to link directly to the Library T&Cs on that page.

Add an 'id' attribute to <h3> links

---

cache/send_slack_alert_for_5xx_errors.js

There are some endpoints containing PII that aren't under the `/account/api` prefix, in particular the `/account/success?email=[email address]` endpoint that we direct users to after they complete the sign-up process.
We'll still be able to find the exact query parameters from the CloudFront logs if we need them; this just means we're less likely to drop PII in Slack.

Redact all query params under the `/account` prefix

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx

People testing the prototype concept pages.
Making them easier to find.
I know we've talked about Gareth giving them a different visual treatment; for now I just stuck "new" on the front so they stand out a bit.

Link to the per-subject pages from works pages if you have the toggle

---

prismic-model/src/parts/body.ts

Prep for using the new AudioPlayer within a podcast article's `body`.

Add audioPlayer to Prismic body

---

cardigan/stories/components/Cards/Cards.stories.tsx
cardigan/stories/components/PageHeader/PageHeader.stories.tsx
cardigan/stories/components/SeasonsHeader/SeasonsHeader.stories.tsx
cardigan/stories/components/WobblyBottom/WobblyBottom.stories.tsx
common/views/components/Iframe/Iframe.tsx
common/views/components/PrismicImage/PrismicImage.tsx
content/webapp/components/FeaturedCard/FeaturedCard.tsx
content/webapp/components/StoryPromo/StoryPromo.tsx
content/webapp/pages/book.tsx
content/webapp/pages/page.tsx
content/webapp/pages/season.tsx
content/webapp/utils/page-header.tsx

[The current low image quality value, used primarily for promo cards, is causing lots of artifacting](https://wellcome.slack.com/archives/C8X9YKM5X/p1657615604603809), which is obvious on high resolution screens.
We previously had three quality options for Prismic images 'low', 'medium' and 'high'.
This PR removes the medium option and increases the value of the low option, to 50, as recommended by Ben Gilbert.
As noted in the Slack conversation above, we should be mindful of penalising people for who data may be expensive/internet connection poor in order to satisfy people with the best screens, especially as we want to grow our global audience.
With that in mind ,the above changes will add approximately 170kB to the homepage and between 688kB and 970kB to the events/past/ listing pages …

image quality tweaks

---

cache/modules/wc_org_cloudfront/waf.tf

See https://wellcome.slack.com/archives/C3TQSF63C/p1657805460169469 for higher-level reasoning behind this.
This enables Bot Control in count-only mode as per the [rec in the docs](https://docs.aws.amazon.com/waf/latest/developerguide/waf-bot-control-deploying.html), and only for the catalogue endpoints.

Enable count-only Bot Control

---

cache/edge_lambdas/src/redirects.ts
identity/webapp/pages/api/auth/signup.ts

This creates a simple flow:
```mermaid
graph LR
L1[user visits /signup] --> L2[redirected to /account/api/auth/signup]
L2 --> L3[Auth0 signup page]
```
Arguably we could skip directly from `/signup` straight to the Auth0 signup page; I added the intermediate step for consistency with `/account/api/auth/login` and  `/account/api/auth/logout`. It uses a very similar approach to [those routes](https://github.com/wellcomecollection/wellcomecollection.org/blob/94ad82232480e34ea3e1377b879cba637a021ff5/identity/webapp/pages/api/auth/%5B...auth0%5D.ts) and so it felt sensible to keep them together.

Redirect /signup to a sign-up page

---

identity/webapp/src/app.ts

Currently we're getting logs like
> -x- GET /account/error?client_id=[redacted]&connection=%5Bredacted%5D&lang=%5Bredacted%5D&error=%5Bredacted%5D&error_description=%5Bredacted%5D&tracking=%5Bredacted%5D 200 503ms 131.09kb
which should be
> -x- GET /account/error?client_id=[redacted]&connection=[redacted]&lang=[redacted]&error=[redacted]&error_description=[redacted]&tracking=[redacted] 200 503ms 131.09kb
but _somebody_ forgot that `str.replace()` only replaces the first instance
of the original value; you need a regex if you want everything replaced.
Devs.
Making logs more readable.

Remember to prettyify all redacted query params

---

content/webapp/components/Discussion/Discussion.tsx

Don't include title in button text

---

cache/locals.tf

This enables the redirect for `/signup` to a sign-up page.
This is already deployed.

Update the edge Lambda for the prod front-end

---

identity/webapp/pages/success.tsx
toggles/webapp/deploy.ts
toggles/webapp/toggles.ts

If you have this toggle enabled, you can see `/account/success`. That's it – it's not protecting the sign-up link or sign-up form or anything we'd want to protect, so we might as well remove it rather than update the default value. (Although I have updated it to true until this gets merged and deployed.)

Remove the self-registration toggle

---

identity/webapp/pages/validated.tsx
identity/webapp/src/frontend/Registration/AccountValidated.test.tsx

For https://github.com/wellcomecollection/wellcomecollection.org/issues/8178
It now says:
<blockquote><h3>Email verified</h3>
<p>Thank you for verifying your email address.</p>
<p>
You can now request up to 15 items from our closed
stores in the library.
</p>
<p>
If you want to access subscription databases, e-journals
and e-books, you need to bring a form of personal
identification (ID) and proof of address to the
admissions desk in the library.
</p></blockquote>
This is based on the copy from the success page and removes the reference to emailing in your proof of ID.
I'm going to merge this once it goes green so we can get _something_ live ASAP.

Do an initial pass on the email verification copy

---

common/views/components/SearchForm/SearchForm.tsx
common/views/components/SelectContainer/SelectContainer.tsx

Fixes #8177
- Makes `select` fill all available horizontal space (makes alignment more predictable)
- Position the chevron `absolute`
- Add extra space between `Sort by:` filter and pagination (required now because of making `select` full-width)

Select icon placement

---

content/webapp/pages/whats-on.tsx

Center clock icon on the what's on page

---

identity/webapp/copy.tsx
identity/webapp/pages/delete-requested.tsx
identity/webapp/pages/registration.tsx
identity/webapp/pages/success.tsx
identity/webapp/pages/validated.tsx

For https://github.com/wellcomecollection/wellcomecollection.org/issues/8160
This is similar to the microcopy file for the rest of the site, but I wanted to keep it separate because this contains large blobs of HTML.
This is just a lift-and-shift; I'll make the changes I want to make separately.

Consolidate all the identity web app copy in a single file

---

prismic-model/src/exhibition-guides.ts

based on chat with Danny and Alice a better name for this field is 'tombstone'. 
An example of tombstone (previously creator) can be seen in the below screenshot where you see 'Phil Nobel 2020'. [More examples of the kind of thing that goes in that space](https://alicerichmond.github.io/digital-guide-prototype/joy/transandcapsjoy.html)

update creator to tombstone 

---

prismic-model/src/exhibition-guides.ts

Looks like the [description field of the exhibition-guides, got mistakenly overwritten](https://github.com/wellcomecollection/wellcomecollection.org/pull/8201/files). 
The [structuredText function now takes an object, following Alex's recent change](https://github.com/wellcomecollection/wellcomecollection.org/pull/8200/files). 
This is causing the diffCustomTypes script and hence the build to fail.

Fix the build

---

common/views/components/NewsletterPromo/NewsletterPromo.tsx
content/webapp/routeHandlers/handleNewsletterSignup.ts

This simplifies the `/newsletter-signup` endpoint, and also hints at a way forward for https://github.com/wellcomecollection/wellcomecollection.org/issues/8166. Currently that endpoint takes:
* an email address
* a single mailing list ID
and subscribes the user to that list, and that list alone. Now it returns a simple `result: ok|error` response, we could adapt it to take a list of multiple mailing list IDs, and use that on the newsletter page. We already have most of the machinery in place, and we could consolidate on a single approach to newsletter sign-ups.
See discussion in Slack: https://wellcome.slack.com/archives/CUA669WHH/p1658499405551999

Send a synthetic 'result: ok|error' page on newsletter signup, not the full Dotdigital response

---

common/data/dotdigital.ts
common/views/components/NewsletterPromo/NewsletterPromo.tsx
content/webapp/components/NewsletterSignup/NewsletterSignup.tsx
content/webapp/routeHandlers/handleNewsletterSignup.ts

For https://github.com/wellcomecollection/wellcomecollection.org/issues/8166
This doesn't change any of the behaviour; it's some refactoring in advance of actually fixing it properly.
My thinking is that we send a _list_ of newsletter IDs to the `/newsletter-signup` endpoint, e.g.
```json
{
"email": "henry@example.com",
"addressBookIds": [1234, 2345, 3456]
}
```
The endpoint subscribes you to all of them, and returns `ok|error` depending on whether they all succeeded.
But this refactoring doesn't rely on that; even if we go a different approach I think these clean-ups are useful.

Tidy up some newsletter signup code

---

content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx

Part of #8147
Adding a button to show more of an audio transcript.
- First paragraph will be shown and the rest revealed on click
- The button won't display if there's only one paragraph
- All paragraphs will be displayed initially and hidden when JS fires to ensure all text is always available
Styles are still tbd in #8147 – this PR is really only addressing the show/hide logic

Start 'Read full transcript' button

---

cache/send_slack_alert_for_5xx_errors.js

Devs.
Trying to stave off alert fatigue.
* It now tells us what proportion of requests are errors, e.g. `5 errors / 5K requests`. This is useful in diagnosing the severity of an issue; 5/50 errors is much worse than 5/50M.
* It now includes the status code if it isn't 500.
* It now links to the raw CloudFront logs in S3, if we want to dig in further.

Make the 5xx CloudFront alert Lambda more useful

---

cache/send_slack_alert_for_5xx_errors.js

It turns out sending a newline in your URI will cause API Gateway to return a 503 Bad Gateway error, but there's nothing we can do about that. Since _somebody_ is doing that by appending data-uri SVGs to their requests, it's spamming our Slack channel.
Make the bot not do that.
Because this is completely unhelpful:

Filter for "interesting" errors in the CloudFront logs

---

prismic-model/diffCustomTypes.ts

In particular, it may fail to load a local model for reasons other than "the model doesn't exist" – e.g. if there's a syntax error in the file. Make the error more accurate.

Make some small improvements to diffCustomTypes

---

content/webapp/components/CardGrid/CardGrid.tsx
content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx
content/webapp/components/ExhibitionGuidePromo/ExhibitionGuidePromo.tsx
content/webapp/components/LayoutPaginatedResults/LayoutPaginatedResults.tsx
content/webapp/pages/exhibition-guide.tsx
content/webapp/pages/exhibition-guides.tsx
content/webapp/services/prismic/transformers/exhibition-guides.test.ts
content/webapp/services/prismic/transformers/exhibition-guides.ts
content/webapp/services/prismic/transformers/json-ld.ts
content/webapp/services/prismic/types/exhibition-guides.ts
content/webapp/types/card.ts
content/webapp/types/exhibition-guides.ts
content/webapp/types/multi-content.ts

**This renders content from `exhibition-guide` type in Prismic at `/guides/exhibitions` and `guides/exhibitions/id`**
This PR takes fetches and transforms further for https://github.com/wellcomecollection/wellcomecollection.org/issues/8162
Showing `exhibition/guides` using frontend components, not just json. Prismic is not allowing me to number the components in the Prismic UI, so I've had to put something temporary in to number the components (aka stops/sections).
Also using `ExhibitionCaption` component for one guide.
**Note: Alice's prototype and Dom's designs call for stripping down of the header/breadcrumb menu. This PR doesn't address that, right now it just uses components we have already made.**

Feat/exhibition guide UI

---

content/webapp/types/card.ts

☝️ 
Interesting to note that an empty string in the `src` of a `next/image` caused it to break, so our fallback (`|| ''`) isn't really any use. I think we should probably use the background pattern that we use elsewhere as a default placeholder 1. so that the site continues to work if we hit this again and 2. so we have more of an idea what's gone wrong when we do. For debate/another PR though.

Revert a change that broke next/image rendering inside cards

---

content/webapp/components/ContentPage/ContentPage.tsx
content/webapp/pages/page.tsx

The `<WeAreGoodToGo>` component is 27KB of icon that only appears on a single page; currently we load it for everything in the content app. This is inefficient; let's move it into the Page component.

Only load the COVID icons on pages, not all <ContentPage>

---

catalogue/webapp/components/WorkHeader/WorkHeader.tsx
catalogue/webapp/components/WorksSearchResult/WorksSearchResult.tsx
common/model/catalogue.ts
common/test/fixtures/catalogueApi/work.ts

Users/researchers
For [#5582](https://github.com/wellcomecollection/platform/issues/5582), only displays one main contributor

Filter and keep label for first main contributor only in Search Result

---

content/webapp/components/ContentPage/ContentPage.tsx
content/webapp/components/SeriesNavigation/SeriesNavigation.tsx

The fix in #8185 was a bit short-sighted and only dealt with one component that can appear after the body of an article.
This change ensures that there will always be the desired amount of padding at the end of the cream section of an article.

Better fix for elements being flush against the cream/white border 

---

content/webapp/pages/exhibition-guide.tsx

Building on #8162
This renders links to the four guide types at /guides/exhibitions/{id}:
It renders the type of guide for each stop at /guides/exhibitions/{id}/{type}:
_Note this is only really working for 'captions-and-transcripts' currently. The others are next on the todo list._
Renders a 404 for an invalid type.
N.B. There is obviously still styling work to do subsequently.

Exhibition guide landing page

---

content/webapp/pages/exhibition-guide.tsx
content/webapp/services/prismic/transformers/exhibition-guides.ts

Building on #8162
This renders the appropriate content for a guide based on the type in the url, e.g.
**There are a few todos and so some tidying up needed, but thought it would be good to get in and we could maybe split the remaining work.**

render video and audio where appropriate

---

cardigan/stories/components/Header/Header.stories.mdx
cardigan/stories/components/Header/Header.stories.tsx
common/views/components/Header/Header.tsx

The exhibition guides area has a requirement for a less busy header with only one link and no option to login to a library account.
This PR lets the `Header` optionally accept `customNavLinks` and adds a `showLibraryLogin` prop defaulted to `true`.

Allow header to have custom nav links and no library login

---

content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx
content/webapp/pages/exhibition-guide.tsx
content/webapp/services/prismic/transformers/exhibition-guides.ts
content/webapp/types/exhibition-guides.ts

Use the stop numbers added in Prismic.
For another PR: Add some placeholder text in the Prismic number field so that it's (hopefully) more obvious that you can enter numbers in the borderless field to the right of the thing that you expect to be the number field.

Update guide stop numbers

---

content/webapp/pages/exhibition-guide.tsx

Builds on #8233
Just making the pages look and behave a bit more like the prototype
- adds links for changing type/exhibition
- adds some basic layout

Exhibition guide pages

---

catalogue/webapp/pages/image.tsx
common/model/catalogue.ts
common/views/components/ApiToolbar/ApiToolbar.tsx

The Editorial team.
Making it slightly less painful to create TASL strings for images from the catalogue.

Add an API toolbar link for tzitzit

---

catalogue/webapp/components/WorkDetails/OnlineResources.tsx

Users
Closes #6380 , makes the clickable link less verbose

Link only view resource if long title

---

cardigan/stories/global/typography/typography.stories.mdx
cardigan/stories/global/typography/typography.stories.tsx

This was a change we made in the apps a little while ago but didn't port it across to the [type-scale section of Cardigan](https://cardigan.wellcomecollection.org/?path=/docs/global-typography--scale), meaning font-sizes are output in `px` where they should be `rem`.
__Before__
__After__

Output rem for the font-size in Cardigan

---

content/webapp/pages/whats-on.tsx

I noticed we had `dateRange: any[]` on this page, which is a warning in VS Code.
I started tugging on the thread, discovered the types aren't quite right, found a place we could reuse an existing helper, and generally tidied it up a little.

Tidy up the datetime-types on the "What's on" page

---

common/data/errors.tsx

`ul`s are only allowed to contain `li`s (and `script`s and `template`s apparently). Moving the markup around a bit to keep it valid and adding a [`body-text` class](https://github.com/wellcomecollection/wellcomecollection.org/blob/6ab5fb1e754d7e853352c7601b3eb69607ad14ca/common/views/themes/typography.ts#L228-L290) to the root of each section of error text so that they follow our styling for e.g. bullets and links.

Tidy error message markup/style

---

common/model/catalogue.ts
common/views/components/ApiToolbar/ApiToolbar.tsx

This is still a bit of a WIP as I'm figuring out all the types; please do comment anything that could help make this better, or be done differently.
Editorial team
- Adds the tzitzit tools for digitised images (making it easier to get copyright information for digitised images, so Stories editors spend less time copy/pasting.)
- Will now hide the link when the licence is INC (in copyright)
- Closes #8246

Add tzitzit to METS images, hide link if license is INC

---

common/views/components/AudioPlayer/AudioPlayer.tsx
common/views/themes/config.ts
content/webapp/pages/exhibition-guide.tsx

Part of #8261
- Rearranging the AudioPlayer a bit to make sure it fits at as many grid widths as possible
- I've stopped using the `Control` component for the buttons in order to closer match the designs – this is obviously a bit messy for now, but I think we need to build some new things and then reassess what can be consolidated back into a design system in future
- Buttons in the header area will need updating to have a white background (not currently possible with our buttons)

Exhibition guides audio listing

---

common/views/components/AudioPlayer/AudioPlayer.tsx

A suggestion from @GarethOrmerod to make the playrate radio buttons less visually busy (which will help to reduce clutter when we have multiple players side-by-side e.g. on listing pages)
__Before__
__After__

Make player rate radios less busy

---

identity/webapp/pages/api/auth/[...auth0].ts

Auth0 is returning 400 errors, but our lack of error handling meant we were always re-raising these as 500 errors.  This causes unnecessary alerts in #wc-platform-alerts and hides real errors.
Devs.
Making the alerts more meaningful.

Shut up errors to /callback?code=<nonsense>

---

identity/webapp/src/app.ts
identity/webapp/src/utility/logging.test.ts
identity/webapp/src/utility/logging.ts

Devs reading app logs.
Making the URLs more accurate. Here's an [example of what the logs look like](https://logging.wellcomecollection.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-15T06:00:17.208Z',to:'2022-08-15T06:15:13.822Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'94746ad0-81c5-11eb-b41a-c9fd641654c0',key:ecs_cluster,negate:!f,params:(query:experience-frontend-prod),type:phrase),query:(match_phrase:(ecs_cluster:experience-frontend-prod))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'94746ad0-81c5-11eb-b41a-c9fd641654c0',key:service_name,negate:!f,params:(query:identity-18012021-prod),type:phrase),query:(match_phrase:(service_name:identity-18012021-prod)))),index:'94746ad0-81 …

Fix the way we redact query parameters in logs

---

identity/webapp/pages/registration.tsx

If we got a session token we couldn't decode on the registration endpoint, we'd throw an error which got raised as a 500 Internal Server Error. This is wrong -- we know what the issue is, we got passed bad data by the user -- so to prevent it showing up in our alerts, raise the correct error code.
I believe this was the source of the `/registration` errors over the weekend.

Return a 400, not a 500, for a bad session_token on registration

---

content/webapp/components/ExhibitionGuideLinksPromo/ExhibitionGuideLinksPromo.tsx

Makes the promo image/title link to the guide (without a type selected)

add link to guide with no type

---

identity/terraform/locals.tf

For https://github.com/wellcomecollection/identity/issues/372
This change is already applied. I sequenced it like so:
* The old ECS services were reading from parameters using `account_management_system`
* Create dual copies of the parameters, so we had both `account_management_system` and `identity_web_app`
* Update the ECS services to read from `identity_web_app` (this patch); wait for them to deploy
* Remove the parameters for `account_management_system`

Look for secrets/parameters called identity_web_app

---

playwright/url-checker/check-url.ts
playwright/url-checker/cli.ts

- Cachebusting
- Ignore aborted requests
- Close pages before exiting

Speculative URL checker improvements

---

identity/webapp/README.md
identity/webapp/package.json
identity/webapp/src/index.ts

Devs.
Making it easier to run the identity web app locally. Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/8288; accompanies https://github.com/wellcomecollection/identity/pull/375

Fetch credentials for the identity web app on `yarn start:dev`

---

identity/webapp/pages/validated.tsx

In my local testing, this seems to fix the issue -- if I hit the post-email verification page and then refresh my account page, the banner telling me to verify my email is gone.
I've tested this locally and confirmed that:
* My account page doesn't update if I omit the line
* My account page does update if I include the line
so tentatively I think this works, although it feels far too simple. 🤷‍♀️

Update the account page after somebody verifies their email

---

cardigan/stories/components/DateRange/DateRange.stories.tsx
cardigan/stories/content.ts
common/views/components/WobblyEdge/WobblyEdge.tsx

People who want meaningful visual diffing
Reducing the randomness from various bits of our storybook stories so they're visually consistent across builds
- The same number of words/paragraphs (as well as the same words) in components
- Using a fixed date for something that was previously using the current time as a base
- Ignoring the `WobblyEdge` component which has deliberate randomness built in
Next step – turn the visual diffing back on in Chromatic and see if any stories are still different between builds (might need to push twice to establish a new baseline).

Less random storybook

---

common/views/components/AppContext/AppContext.tsx
common/views/components/AudioPlayer/AudioPlayer.tsx

People who don't want to update their playback rate for every audio player
Updating their preference throughout the app
Is this a good idea/the right way to do it? I'm not sure.

Use AppContext for storing audioPlaybackRate

---

content/webapp/package.json
content/webapp/pages/exhibition-guide.tsx

Guide users. Based on ticket https://github.com/wellcomecollection/wellcomecollection.org/issues/8188
**1. Sets a user preference cookie based on chosen guide type.**
When a user selects a guide type, we create a preference cookie `WC_userPreferenceGuideType` and set it to that guide type. When that same user visits any exhibition guide, we send them directly to their preferred type based on that cookie, and we append the url with a parameter indicating the preference is set. 
**2. Sets a user preference cookie based on QR code.** 
If a user visits from a QR code, based on a url like `http://localhost:3002/guides/exhibitions/Ytk2IREAACcA--2o/audio-without-descriptions?usingQRCode=true`, we set `WC_userPreferenceGuideType` based on the guide type in that url.
In both cases:
- we use the …

Setting a user preference cookie for guide type

---

catalogue/webapp/pages/works.tsx
common/views/pages/_app.tsx
yarn.lock

For some reason, the linter that runs on pre-commit is being extra strict today, and warning me about:
* The lack of a return type on `getServerSideProps` in `works.tsx`
* An `any` type in `_app.tsx`
In both cases, we can specify the types explicitly, so let's do that – with the bonus that we can remove some circular and magic type logic of the form "it returns whatever it returns".
Me.
Allowing me to commit code. Also unblocking #8307.

Fix the types in works.tsx and _app.tsx

---

content/webapp/pages/exhibition-guide.tsx

People using the guides
It should now read the user preference cookie and redirect any other exhibition guides, based on that user preference cookie

Use contextUrl not req.url

---

content/webapp/pages/exhibition-guide.tsx

Anyone who wants to set a guide type preference and be redirected to that type.
Console logs for devs to debug this issue.
Hopefully this will make sure the redirect based on context url and cookie redirects the user to their preferred guide type.

Debugging redirect for user preference cookie

---

cache/modules/cloudfront_policies/cache_policies.tf
cache/modules/cloudfront_policies/locals.tf
cache/modules/cloudfront_policies/request_policies.tf

People wanting to have their preference cookie read in guide types
This should mean we can read the `WC_userPreferenceGuideType` on the client side within server context.
```
Terraform will perform the following actions:
~ resource "aws_cloudfront_cache_policy" "weco_apps" {
id          = "b2c915f......"
name        = "weco-apps"
~ parameters_in_cache_key_and_forwarded_to_origin {
~ cookies_config {
~ cookies {
~ items = [
+ "WC_*",
]
}
}
}
}
~ resource "aws_cloudfront_origin_request_policy" "host_query_and_toggles" {
id      = "7d466a9...."
name    = "host-query-and-toggles"
~ cookies_config {
~ cookies {
~ items = [
+ "WC_*",
]
}
}
}
Plan: 0 to add, 2 to change, 0 to destroy.
```

Add WC_ cookies to allow lists cloudfront 

---

catalogue/webapp/components/Download/Download.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.tsx
catalogue/webapp/components/WorkDetailsText/WorkDetailsText.test.tsx
catalogue/webapp/components/WorkDetailsText/WorkDetailsText.tsx
catalogue/webapp/pages/download.tsx

Initially this is set to true, to mimic the existing behaviour -- but now this choice is configurable and explicit when we use the component. Currently it looks like we allow raw HTML in *any* field, which probably isn't what we want.
This opens the door to marking some fields as "should not contain HTML" in a future patch.
For https://github.com/wellcomecollection/platform/issues/5579; follows #8311

Add a allowRawHtml parameter to <WorkDetailsText>

---

common/views/components/AudioPlayer/AudioPlayer.tsx
content/webapp/pages/exhibition-guide.tsx

Part of #8290
- Only stops with numbers will render (and be counted) above
- Play button colour/border changed to green
- Global alert banner won't display on pages with `/guides/exhibitions` in the URL (updated on Prismic)
- Updated the header to read "Listen to audio" for `audio-with-descriptions` and `audio-without-descriptions` to prevent the illusion of choice when we (at least currently) only have audio without descriptions.
- Grid alignment fixes

Audio guide UI fixes

---

common/views/components/Iframe/Iframe.tsx

It looks like there's sometimes a visual diff within the YouTube embed, but since we have little to no control over how this looks, we probably shouldn't require that it looks the same.

Ignore visual changes in iframes 

---

cache/cloudfront_prod.tf

This is part of https://github.com/wellcomecollection/wellcomecollection.org/issues/8273

Remove blog.wellcomecollection.org as a prod alias

---

catalogue/webapp/components/Calendar/calendar-utils.ts
catalogue/webapp/components/IIIFViewer/Padlock.tsx
catalogue/webapp/components/License/License.tsx
catalogue/webapp/pages/_app.tsx
common/views/components/SelectUncontrolled/SelectUncontrolled.tsx
content/webapp/pages/api/articles/index.ts
dash/webapp/pages/pa11y.tsx
dash/webapp/pages/toggles.tsx
identity/webapp/copy.tsx
identity/webapp/src/frontend/hooks/useSendVerificationEmail.tsx
playwright/test/helpers/safeWaitForNavigation.ts
toggles/webapp/deploy.ts
toggles/webapp/s3-utils.ts
toggles/webapp/setDefaultValueFor.ts
updown/checks.ts
updown/expected-checks.ts
updown/utils.ts

The pre-commit checks on my laptop have become way more aggressive recently, treating warnings as errors. They're not wrong, but it's mildly annoying to encounter when I'm in the middle of committing code.
This patch fixes a bunch of the easiest warnings; there's plenty more but this takes us in the right direction.
Before:
```
$ yarn run eslint --fix --max-warnings=0 .
✖ 210 problems (11 errors, 199 warnings)
```
After:
```
$ yarn run eslint --fix --max-warnings=0 .
✖ 190 problems (10 errors, 180 warnings)
```

Fix a bunch of eslint warnings

---

content/webapp/services/prismic/transformers/article-series.ts
content/webapp/services/prismic/transformers/articles.ts
content/webapp/services/prismic/transformers/contributors.ts
content/webapp/services/prismic/transformers/event-series.ts
content/webapp/services/prismic/transformers/events.ts
content/webapp/services/prismic/transformers/exhibitions.ts
content/webapp/services/prismic/transformers/json-ld.ts
content/webapp/services/prismic/transformers/series.ts
content/webapp/services/prismic/types/images.ts
content/webapp/types/articles.ts
content/webapp/types/contributors.ts
content/webapp/types/event-series.ts
content/webapp/types/events.ts
content/webapp/types/exhibitions.ts
content/webapp/types/series.ts

People using the site.
Making it be more smol. In particular, we send less Prismic data on the homepage and other pages using the Basic types.
I tested on the homepage in a local build:
<table>
<tr><th></th><th>size of HTML file</th><th>delta</th></tr>
<tr><td>before any changes</td><td>321.0 kB</td><td></td></tr>
<tr><td>with SeriesBasic</td><td>291.8 kB</td><td>&minus;29.2 kB (~9%)</td></tr>
<tr><td>with EventSeriesBasic </td><td>285.3 kB</td><td>&minus;35.7 kB (~11%)
<tr><td>with ContributorBasic </td><td>282.3 kB</td><td>&minus;38.7 kB (~12%)
</td></tr>
</td></tr>
</table>
The bulk of the win seems to be in SeriesBasic, which previously included a lot of information about the contributors and some promo text.
We could keep cutting further, but you're into diminishing returns and the …

Reduce the size of the JSON bundle we send to pages

---

playwright/test/selectors/images.ts

Filtering by brown this time.
The first item in the results [when filtering by black](https://github.com/wellcomecollection/wellcomecollection.org/pull/8336/files), was an image that is part of a work, and so the regex check on the url when following the 'view image' link failed 
When filtering by brown, the first item in the results is a stand alone image so the regex passes.

Fixes e2e test (hopefully)

---

content/webapp/services/prismic/transformers/article-series.ts

Previously we were only calling `transformArticleToArticleBasic` if the series didn't have an associated colour, which meant we were sending way more information than we needed.  This ensures we always send a trimmed-down version of articles on series.
This makes the stories homepage dramatically smaller:
<table><tr><td>Before</td><td>562.2 kB</td></tr><tr><td>After</td><td>397.4 kB</td></tr></table>

Always transform to article basic, even in colour

---

catalogue/webapp/pages/download.tsx
common/services/catalogue/sierra.test.ts
common/services/catalogue/sierra.ts

Previously we'd send a download request to DLCS, regardless of what was passed as the sierraId field.  This could cause 500 errors, if we passed something that DLCS couldn't handle, e.g.
/works/amuh57db/download?sierraId=../etc/passwd
This has been the source of several 500 errors in the #wc-platform-alerts channel recently, from somebody trying to break into the server.
By filtering for strings that look like plausible Sierra IDs here, we reduce the number of obviously bad queries we send to DLCS and cut out a source of 500 errors.
Follows #8332.

Guard against bad Sierra IDs on the download page

---

toggles/webapp/deploy.test.ts
toggles/webapp/deploy.ts
toggles/webapp/index.ts
toggles/webapp/toggles.ts

As I've been explaining it to a few people recently, I've noticed there's a bit of confusing naming.  In particular, if you look in `toggles.ts`, here's a toggle definition:
```typescript
{
id: 'exhibitionGuides',
title: 'Exhibition guides',
description: 'View pages related to exhibition guides',
defaultValue: false,
},
```
Here's what the toggle looks like in the published JSON:
```json
{
"id": "exhibitionGuides",
"description": "View pages related to exhibition guides",
"title": "Exhibition guides",
"defaultValue": false
}
```
You might think you can update the default value by updating the value in `toggles.ts` and running `yarn deploy` -- but no!
If you wanted to update the default value, you can never change it through `toggles.ts` – that value is set on the toggle's initial …

Tidy up the naming of default/initial values of toggles

---

toggles/webapp/toggles.ts

Us to be able to deploy toggles 😅 
Fixed changed key name from `defaultValue` to `initialValue`

Change to initialValue

---

common/views/pages/_app.tsx

Everyone who wants to see the new colour palette
Getting the toggle value from server data makes the toggle work, it previously returned undefined when using the context.

Get toggle value from serverData

---

catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx
catalogue/webapp/components/VisuallySimilarImagesFromApi/VisuallySimilarImagesFromApi.tsx

Users
Allows them to browse through images, going back and forth when clicking related images. Currently it only keeps displaying the same image until the user leaves `/images`. Would also allow for sharing `/images` with a modal opened if the user wanted it.
Closes #8350

Images routing with modals

---

catalogue/webapp/components/LibraryMembersBar/LibraryMembersBar.tsx
playwright/test/work.test.ts

When we last turned on the disableRequesting toggle, it caused a test to fail and prevents us from deploying.
The test is looking for the presence of some specific text in the banner that appears on the work page when requesting is disabled. The problem is, the text is likely to change depending on the reason for disabling the requesting functionality.
This PR changes the test to look for the presence of a data-test-id, that wraps the text, instead.

Stop test failing if disableRequesting toggle is turned on

---

content/webapp/__mocks__/whats-on.ts
content/webapp/pages/whats-on.tsx

We only need a list of exhibitions/events to render the page; pagination is handled by per-type pages.
Quick win spun out of #8363.

Don't send PaginatedResults on the whats-on page

---

prismic-model/package.json
prismic-model/tryAllContentPages.ts
prismic-model/yarn.lock

This gives you a progress bar in the output, which is useful for checking that it is checking pages, and an estimate of when it will finish.
e.g.
$ ts-node tryAllContentPages
|##########| 2102/2107 99% [elapsed: 03:27, left: 00:02, 10.14 iters/s]
!!! 404 http://localhost:3000/series/YxDE0hEAACMAdaCf
!!! 404 http://localhost:3000/exhibition-guides/YvJ4UhAAAPgZztMl
!!! 404 http://localhost:3000/exhibition-guides/YvUALRAAACMA2h8V
!!! 404 http://localhost:3000/exhibition-guides/Ytk2IREAACcA--2o
!!! 500 http://localhost:3000/pages/Wvl1wiAAADMJ3zNe
!!! 500 http://localhost:3000/pages/WwQHTSAAANBfDYXU
!!! 404 http://localhost:3000/series/X8D9qxIAACIAcKSf
!!! 404 http://localhost:3000/exhibition-resources/W5KUFCYAACYAG-T4
!!! 500 http://localhost:3000/pages/Wuw19yIAAK1Z3Smm
✨  Done in 209.94s. …

Use tqdm for tryAllContentPages

---

prismic-model/lintPrismicData.ts

For https://wellcome.slack.com/archives/C8X9YKM5X/p1662107045936069
The Editorial team.
Helping us identify broken links to interpretation types that should be removed to avoid mysterious black squares appearing on the site.

Add a Prismic lint for broken interpretation type links

---

catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx
catalogue/webapp/components/VisuallySimilarImagesFromApi/VisuallySimilarImagesFromApi.tsx

Users
Reverting the changes (#8350, [original PR here](https://github.com/wellcomecollection/wellcomecollection.org/pull/8351/files)) brings back the navigational "bug", but it wasn't a good fix. It introduced a new bug, clearing query parameters like filters. The ticket will be brought back and different options explored, but as this not good behaviour, better to revert for now to the old one.

Revert images routing changes

---

catalogue/webapp/components/ItemRequestModal/useAvailableDates.ts
common/model/opening-hours.ts
common/services/prismic/opening-times.ts
common/services/prismic/transformers/collection-venues.ts
common/test/fixtures/components/galleries-venue.ts
common/test/fixtures/components/library-venue.ts
common/test/fixtures/components/restaurant-venue.ts
common/test/services/prismic/opening-times.test.ts
common/utils/dates.test.ts
common/utils/dates.ts
common/utils/format-date.test.ts
common/utils/json-ld.ts
content/webapp/components/VenueClosedPeriods/VenueClosedPeriods.tsx
content/webapp/components/VenueHours/VenueHours.tsx

For https://github.com/wellcomecollection/wellcomecollection.org/issues/8364 and https://github.com/wellcomecollection/wellcomecollection.org/issues/7831
To sort out passing `Date` values to/from our props, we're going to use a superjson plugin for serialising JSON. It doesn't know how to serialise the `Moment` values we pass in the opening times, so I've modified the opening times model to use a `Date` object instead.
I've tried to be as conservative as I can, because date logic is so fiddly – but the existing suite of tests were super helpful in catching my mistakes. 💪 
I think this is mergeable as a standalone patch, and it opens the door to sorting out the superjson plugin in a new PR.
I've checked the opening times in the footer and on /opening-times, and both look correct.

Don't use Moment in the opening-times model

---

content/webapp/utils/page-header.tsx

If you look at where this function is used, we never pass a value for the `isPicture` parameter, so it's always `undefined`.  Let's remove it and save ourselves a few bytes.
✂️ ✂️ ✂️

Remove an unused parameter in getFeaturedMedia

---

common/model/image.ts
common/services/prismic/transformers/images.ts
content/webapp/components/StoryPromo/StoryPromo.tsx
content/webapp/pages/stories.tsx
content/webapp/services/prismic/transformers/articles.ts
content/webapp/services/prismic/transformers/exhibitions.ts
content/webapp/services/prismic/transformers/images.ts
content/webapp/services/prismic/transformers/index.ts

Spotted while poking at page weight in #8378; they're irrelevant to that patch, but making empty values `undefined` means they won't be sent as part of the page props.
<table><tr><th></th><th>before</th><th>after</th></tr>
<tr><td>homepage</td><td>244.92 kB</td><td>229.64 kB (&minus;6.5%)</td></tr>
<tr><td>/stories</td><td>388.88 kB</td><td>313.19 kB (&minus;20%)</td></tr>
<tr><td>/articles/Yp3GthEAACIAwRi9</td><td>201.79 kB</td><td>199.56 kB (&minus;1.5%)</td></tr>
</table>

Omit some transformed fields we don't need

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
common/utils/format-date.test.ts
common/utils/format-date.ts

It's definitely overkill: durations have no awareness of timezones and don't need any complicated datetime logic.
For https://github.com/wellcomecollection/wellcomecollection.org/issues/7831.

Don't use Moment to format duration on a works page

---

prismic-model/lintPrismicData.ts

Devs.
Helping them to quantify the number of errors they're seeing.

Report the number of errors (or not) in the Prismic lint output

---

content/webapp/components/EventSchedule/EventSchedule.tsx
content/webapp/services/prismic/events.ts
content/webapp/services/prismic/transformers/events.test.ts

For #7831.
This removes some calls to `london()` that I believe are now superfluous; in particular, because we can now get `Date` values passed reliably through props to client-side components, we can trust that `d: Date` is actually a `Date`, and not a string that's snuck past.

Remove some uses of `london()` from the event components

---

catalogue/webapp/test/utils/dates.test.ts
common/test/services/prismic/opening-times.test.ts

For https://github.com/wellcomecollection/wellcomecollection.org/issues/7831.
There are a bunch of places where our tests are using `Moment` when they should/can be using a `Date`, so let's do that.

Remove some uses of `london()` from tests

---

common/utils/dates.test.ts
common/utils/dates.ts
content/webapp/pages/whats-on.tsx
content/webapp/services/prismic/events.ts
content/webapp/services/prismic/types/predicates.ts

For https://github.com/wellcomecollection/wellcomecollection.org/issues/7831.
I wrote some tests for the old implementation, saw them passing, then I wrote the new implementation without modifying the tests.

Modify getNextWeekendDateRange to use vanilla Date, not Moment

---

content/webapp/pages/api/multi-content/index.ts
content/webapp/services/prismic/fetch/multi-content.ts

The problem is that using vanilla JSON serialisation on Prismic objects will obliterate the `Date` type.
We've fixed this in the page props with a superjson plugin, which adds information about types to the JSON – and then I thought I could delete all the code which "fixes" the types downstream. e.g. where we call `new Date(date)` on a value which should already be a date.
This exposed a case where the types are still being mishandled, which is the client-side API and fetchers. Putting superjson in the middle seems to fix it in local testing.
I looked at adding this to the URL checker, but it passes the current page, so I don't think it adds much.

Serialise the multi-content API responses with superjson

---

content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx
content/webapp/pages/exhibition-guide.tsx

Exhibition guide users and editors https://github.com/wellcomecollection/wellcomecollection.org/issues/8359
Allowing us to have urls to link to individual stops within an exhibition guide page i.e. in audio (with or without description) and bsl we link to the title of the audio and video, in captions and transcripts we link to `standAlone` section titles, context titles, and tombstone titles. The url contains the id of the particular stop/section, the id outputs as `#the-title-of-the-stop-or-thing`.
Some examples:
**weco.org/guides/exhibitions/YvJ4UhAAAPgZztMl/audio-without-descriptions#weeping---joy-in-the-passions--humorously-delineated** brings you to that 'stop'
**weco.org/guides/exhibitions/YvJ4UhAAAPgZztMl/captions-and-transcripts#projection-and-fear** brings you to the projection …

Feat/ Exhibition guide anchor links

---

catalogue/webapp/components/Download/Download.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.tsx
catalogue/webapp/components/WorkDetailsText/WorkDetailsText.test.tsx
catalogue/webapp/components/WorkDetailsText/WorkDetailsText.tsx
catalogue/webapp/pages/download.tsx
common/utils/licenses.tsx

For https://github.com/wellcomecollection/platform/issues/5579
People who like accurate data.
Allowing the presentation of `alternativeTitles` that include angle brackets in the title. I've checked all the instances of it in a recent catalogue snapshot, and it's used for dates, e.g. `The Jolly Journal <2001–2002>`, so we don't need to render this field as HTML.
I also have half an eye towards the dev interface of `<WorkDetailsText>` here – it feels like we want to minimise the places we're render strings as raw HTML, so I've:
* made it more explicit that you're doing something 🔥 **dangerous** 🔥 
* allow passing React elements as the contents when it's something that comes from the front-end codebase, in particular the license and credit text

Don't treat alternative titles and other fields as HTML

---

common/services/prismic/opening-times.ts
common/services/prismic/transformers/collection-venues.ts
common/utils/dates.test.ts
common/utils/dates.ts
common/utils/format-date.test.ts
common/utils/format-date.ts
common/views/components/PageLayout/PageLayout.tsx
content/webapp/pages/exhibitions.tsx
content/webapp/services/prismic/transformers/articles.ts
content/webapp/services/prismic/types/predicates.ts

For https://github.com/wellcomecollection/wellcomecollection.org/issues/7831
I have a suspicion that our date formatting is one of the things keeping Moment in the codebase, because we use it a lot – but I don't think we need it any more; anywhere we format a date now is actually getting a vanilla `Date`.
We have tests around date formatting that I added a while back, and I've added additional tests that timestamps are formatted for London specifically (including when London clocks don't match UTC).
I also discovered we can use `date.toLocaleString` and pass a timezone – so I _think_ we can totally expunge Moment from our date formatting, which might shake it out of the content app entirely. 🤞 
~There's a bit more to do in the catalogue app, but I'm hoping this takes a big chunk out.~
I'd …

Don't use moment for formatting dates

---

content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx
content/webapp/pages/exhibition-guide.tsx

Any guide users
In one case of `title` the type was an object, not a string. I have forced that title to be a string when feeding it to the dasherize function, this fixes the captions guide type pages which were 500'ing.

Fix usage of dasherize and make captions guide type work again

---

common/services/prismic/documents.ts
common/services/prismic/transformers/collection-venues.test.ts
common/services/prismic/transformers/collection-venues.ts

The problem is that the type checker can't derive a better type for `data[lowercaseDay][0]` than `any`, so it thinks the `{start,end}DateTime` values are fine to be passed to `formatTime`, when we need to cast them to `Date` objects first.
Adding some tests and intermediate types fixes the appearance of opening times in the footer.
🙈

Fix the appearance of dates in the footer

---

cardigan/stories/components/Calendar/Calendar.stories.tsx
catalogue/webapp/components/Calendar/Calendar.tsx
catalogue/webapp/components/Calendar/CalendarSelect.tsx
catalogue/webapp/components/ItemRequestModal/RequestDialog.tsx
catalogue/webapp/components/ItemRequestModal/useAvailableDates.ts
catalogue/webapp/test/components/ItemRequestModal.test.tsx
catalogue/webapp/test/utils/dates.test.ts
catalogue/webapp/utils/dates.ts

For https://github.com/wellcomecollection/wellcomecollection.org/issues/7831
This bins all the uses of Moment in `@weco/catalogue/utils/date` in favour of vanilla Date values. I mostly didn't touch the tests, apart from replacing the input/output values.

No more Moment in `@weco/catalogue/utils/date`

---

content/webapp/components/EventsByMonth/group-event-utils.test.ts
content/webapp/components/EventsByMonth/group-event-utils.ts

The bug was introduced in https://github.com/wellcomecollection/wellcomecollection.org/pull/8389, when I changed `isSameMonth()` to use UTC instead of the user's local timezone.
This means that the first of the month created by `firstOf(yearMonth)` was actually getting offset back into the previous month, I think – I've added a test based on the behaviour prior to that change, verified it broke in the unpatched code, and works in the patched code. I've also checked the "What's on" page in a local copy of the app, and it looks correct.

Make sure September appears in the /whats-on page

---

content/webapp/components/EventDateRange/EventDateRange.tsx
content/webapp/components/EventsByMonth/EventsByMonth.tsx
content/webapp/components/EventsByMonth/group-event-utils.test.ts
content/webapp/components/EventsByMonth/group-event-utils.ts
content/webapp/types/events.ts

The existing implementation was quite difficult to follow -- it was broken down into lots of small functions, and it was tricky to see how they interacted.
It had some quite tricksy behaviour around things like 0-indexed months (which we don't use anywhere else) and the ordering of events.  This is one of those times you wonder how the previous version ever worked correctly (and based on a quick test, maybe it didn't).
This patch replaces it with a hopefully simpler and more readable implementation:
1. Work out the min/max bounds for the list of events
2. Work out what month that covers
3. For each month, work out (a) what events should be included and (b) what order they should appear in
A lot of the intermediate functions are gone, and internally events are grouped by their English …

Refactor the way events get grouped in "What's On"

---

catalogue/terraform/stack/main.tf

I'm hoping this will stem the 502 errors we're seeing, which seem to occur when a task runs out of memory, crashes, and drops any requests it was currently processing.
I've already applied this change.

Increase the memory of the catalogue ECS task

---

content/webapp/pages/event-series.tsx
content/webapp/pages/events.tsx
content/webapp/pages/whats-on.tsx
content/webapp/services/prismic/transformers/contributors.ts
content/webapp/services/prismic/transformers/events.ts
content/webapp/services/prismic/transformers/json-ld.ts
content/webapp/types/contributors.ts
content/webapp/types/events.ts

While looking at #8416, I noticed that we're sending a full set of contributor data as part of the `EventBasic` model on the `/whats-on` page, even though we don't use it to render the page. We only use the contributor on events to render the JSON-LD, which is already rendered server-side where we have the full `Event` model.
Running locally, this takes the `/whats-on` page from 324.75&nbsp;kB to 308.63&nbsp;kB; about a 5% reduction. It should also reduce the size of the homepage, when it actually has events.

Don't send contributor information on EventBasic; image data on ContributorBasic

---

common/package.json
common/services/prismic/opening-times.ts
yarn.lock

We only use it in one place, and we can easily replace it with a bit of vanilla TypeScript.
This is something I spotted while poking around in this opening-times code.

Remove our lodash.groupBy dependency

---

content/webapp/components/SeriesNavigation/SeriesNavigation.tsx
content/webapp/pages/api/articles/index.ts
content/webapp/pages/api/events/index.ts
content/webapp/pages/api/exhibitions-related-content/index.ts
content/webapp/pages/api/exhibitions/index.ts
content/webapp/pages/article.tsx
content/webapp/services/prismic/fetch/articles.ts
content/webapp/services/prismic/fetch/index.ts

If you look at a page with related content (e.g. https://wellcomecollection.org/articles/YdQ6AhAAAJMQ5mEg), we fetch the related content asynchronously through the content API (e.g. `/api/articles`). This means it bypasses the superjson handling we use in `getServerSideProps`, and all your `Date` values are strings. This breaks as soon as you try to treat a string date as a `Date`, and the page returns a 404. Sadness.
This patch:
* Uses superjson to serialise and deserialise content in these APIs, so `Date` values will be preserved (cf #8396)
* Only sends an `ArticleBasic` through the articles API, not the full article – this cuts the response from 281KB to 14KB, a 20x reduction (!)
I've tested it locally, and the broken article is no longer breaking.

Remember to serialise API results using superjson

---

common/views/components/SegmentedControl/SegmentedControl.tsx

Fixes #8349 
This is the most straightforward fix to make the component usable. I think the UX for the mobile version of this component could probably do with revisiting though – the thing that looks like a dropdown could probably just behave like the other dropdowns we use on the site, rather than taking over the entire screen. Opened #8362 to track this.

Make SegmentedControl list items visible above mobile header

---

content/webapp/components/EventsByMonth/EventsByMonth.tsx

People without JS
Giving them anchor links within the what's on page so they can jump to the appropriate month
This used to display YYYY-MM – we don't have obvious access to that format anymore, but I don't think it's important. I've changed it to be the name of the month (without the year, because that seemed superfluous) and I think that's probably ok(/preferable).

Re-add what's on anchors for no-JS

---

catalogue/webapp/components/IIIFImage/IIIFImage.tsx
catalogue/webapp/components/ImageCard/ImageCard.tsx
catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx
catalogue/webapp/pages/concept.tsx

Devs - blocked by broken e2e in staging
Fixes e2e test that fails
```
React does not recognize the `bgColor` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `bgcolor` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

Change property name to fix test

---

playwright/test/images.test.ts

Devs
Fixes [images test failing ](https://buildkite.com/wellcomecollection/wc-dot-org-end-to-end-tests/builds/1666#01833687-9022-40d6-9457-ec800d5811ba) by closing the color filter modal in a different way

Fix images test

---

catalogue/webapp/components/WorksSearchResult/WorksSearchResultV2.styles.tsx
catalogue/webapp/components/WorksSearchResult/WorksSearchResultV2.tsx
catalogue/webapp/components/WorksSearchResults/WorksSearchResultsV2.tsx
catalogue/webapp/pages/concept.tsx
common/views/components/TabNav/TabNavV2.tsx

Devs/Designer
Made changes/fixes on Concept page based on updated design and debugging. Examples below, see mainly tabs, spacing, font-size, image preview:
Buxton before
Buxton after
---
GB Before
GB After

Concept style changes/fixes

---

catalogue/webapp/pages/images.tsx

Users
Gets them more results on a page, based on a request from Jonathan

Have 30 images results instead of 25

---

playwright/url-checker/check-url.ts
playwright/url-checker/ignore.ts

We saw some errors last week that the URL checker missed, because Next.js was helpfully catching them for us and re-logging a more descriptive error. This approach is more likely to introduce false positives which we'll need to override, but that's OK.

Detect more errors in the URL checker

---

content/webapp/components/Body/Body.tsx

People who expect content from the CMS to be visible on the website
Re-adding text that was removed from landing pages
The original change was intended to prevent outputting empty `contentList` slices that were wrapped in a `SpacingComponent` which led to extra space being created on the page. I'll create a separate ticket to fix that (properly) again.

Reinstate text slices on landing pages

---

catalogue/webapp/components/ItemRequestModal/ItemRequestModal.tsx
catalogue/webapp/components/ItemRequestModal/format-date.test.ts
catalogue/webapp/components/ItemRequestModal/format-date.ts

UTC months are 0-indexed, not 1-indexed.  This was causing requests to be placed for the previous month. Tentative fix for https://github.com/wellcomecollection/wellcomecollection.org/issues/8457
I'm on a train; I don't have reliable enough Internet to test properly, but even if this isn't the whole issue it's definitely wrong.
People requesting items.
Making sure requests are placed for the right month.

Check we're actually formatting months correctly

---

catalogue/webapp/utils/dates.ts
common/utils/dates.test.ts
common/utils/dates.ts

Making sure the correct dates are removed from the date picker.
Sunday doesn't appear in the screenshot below because it is a 'regular closed day', and Monday doesn't appear because it's an 'exceptional closed day'.
Handling this date logic makes me feel uneasy. Would date-fns be a better option (lighter touch than Moment, but far better tested than our homegrown versions).

Set date hours to zero to make sure we're comparing like with like

---

catalogue/webapp/components/ItemRequestModal/useAvailableDates.ts
catalogue/webapp/test/utils/dates.test.ts
catalogue/webapp/utils/dates.ts

Up till now, we haven't taken any e.g. bank holidays into account when determining the next available pick-up date for requested items.
With this change, if a request is made after 10am on a Friday and the following Monday is a bank holiday, the next available pick-up date will be the following Wednesday (at present, it would be the Tuesday).

Account for exceptional closures in requesting date logic

---

cardigan/stories/components/Pagination/Pagination.stories.tsx
common/views/components/Buttons/Control/Control.tsx
common/views/components/Pagination/Pagination.tsx
common/views/components/Paginator/Paginator.tsx
content/webapp/components/CardGrid/CardGrid.tsx
content/webapp/components/LayoutPaginatedResults/LayoutPaginatedResults.tsx
content/webapp/pages/exhibitions.tsx

Users
Allows pagination to be keyboard navigable.
Also aligned how it looked across the site and var names they were using. Eventually we'll need to look into pagination bit more deeply ([see comments on ticket](https://github.com/wellcomecollection/wellcomecollection.org/issues/8394))
Paginator
Pagination before/after
Closes #8394

Align pagination

---

content/webapp/components/Body/Body.tsx

We're currently mapping over body slices and conditionally not displaying `contentList`s in the body if they appear on a landing page (because they have a different design treatment there). But we _are_ still wrapping everything in the map inside a `SpacingComponent`, which means we're outputting as many `SpacingComponent`s as there are `contentList`s, which results in extra space at the bottom of landing pages.
This comes after #8447 reverting a previous attempt to fix this, which had inadvertently also removed text slices from landing pages.
It's a bit repetitive, but I thought it was clearer to do it this way than using e.g. the `ConditionalWrapper`

Don't output empty spacing components on landing pages

---

catalogue/webapp/components/PhysicalItemDetails/PhysicalItemDetails.tsx

I've deployed this to stage and checked that:
* If I request an item, that item is immediately marked as "requested" on the page
* If I request an item then switch to another item in the same hierarchy, the new item is marked as "available" without me reloading the page
* If I request an item, switch to another item, then switch back, the item I've already requested shows up as "You have requested this item"
Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/8448

Allow users to request multiple items from within a hierarchy without reloading the page

---

playwright/test/works-search.test.ts

Everyone
Fixes e2e tests.
This role was changed as the div was replaced by a `nav`, which already indicates it's a navigation element. We're just specifying it's a pagination nav.

Change pagination aria-label in tests

---

common/services/prismic/transformers/collection-venues.ts
common/services/prismic/transformers/index.ts
content/webapp/services/prismic/transformers/books.ts
content/webapp/services/prismic/transformers/events.test.ts
content/webapp/services/prismic/transformers/events.ts
content/webapp/services/prismic/transformers/exhibitions.ts
content/webapp/services/prismic/transformers/guides.ts
content/webapp/services/prismic/transformers/index.ts
content/webapp/services/prismic/transformers/pages.ts
content/webapp/services/prismic/transformers/seasons.ts
content/webapp/services/prismic/transformers/series.ts

Follows https://github.com/wellcomecollection/wellcomecollection.org/pull/8449
Future devs, aka me.
Explaining why the `transformTimestamp` method is important – I thought it was equivalent to `new Date(…)`, which is why I didn't move it out of `@weco/content` when I was doing refactoring.

Create a shared definition of transformTimestamp

---

catalogue/webapp/components/Calendar/Calendar.tsx
catalogue/webapp/utils/dates.ts
common/utils/dates.test.ts
common/utils/dates.ts

Devs.
We only use `isSameDayOrBefore` to decide what dates a user can pick for requesting items, and there we want a London comparison (both in the visual calendar and the dropdown picker).
This patch doesn't change the behaviour of `isSameDayOrBefore` at all, but does make it very explicit that's what we want:
* I've removed the `mode` argument, because it should only ever be `London`
* I've added more tests that it's doing a London comparison, not a UTC comparison
* I've written a function comment that explains this is doing London comparisons
Follows https://github.com/wellcomecollection/wellcomecollection.org/pull/8455, where we added this `mode` argument. I suspect we can also remove it from `isSameDay()`, but I don't want to change too much at once.
For …

Be super-duper explicit that isSameDayOrBefore is London-only

---

catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx

Users
Gets the work id from the source, previously wasn't fetching it at all. Only happens when using Gallery (so when more than 2 images in results, and with JS activated). Did not see it because we usually access the work's page from the modal, which had the correct link. But [as flagged here](https://wellcome.slack.com/archives/C8X9YKM5X/p1663338896261959), opening the link in a new tab gave us a 404.

Fetch workId from correct source

---

catalogue/webapp/test/utils/dates.test.ts
catalogue/webapp/utils/dates.ts

(Sorry, I saw the initial email from Cassandra before seeing Natalie had sent it to David.)
The existing logic was quite complicated, and had a bug. I discovered this by writing a series of new test cases based on #8215, and realising we were dropping a day somewhere.
In particular, we were double-counting the retrieval day.  In particular, this logic inside `determineNextAvailableDate`:
determineNextAvailableDate {
…
// If a request is made before 10am, the next _potential_ pick-up date is the
// next day otherwise, it is two days' time.
const isBeforeTen = hourInLondon < 10;
const nextAvailableDate = addDays(date, isBeforeTen ? 1 : 2);
findNextPickUpDay(nextAvailableDate, …)
}
findNextPickUpDay(date) {
…
// If the library is closed on this day, we want to set the pick-up day to be
// …

Fix a bug in the "next available date" over the weekend

---

catalogue/webapp/components/ArchiveTree/ArchiveTree.test.tsx
catalogue/webapp/components/ArchiveTree/ArchiveTree.tsx
common/package.json
yarn.lock

Spotted upon code read. We're calling `flattenDeep` to flatten an array `(string | string[])[]`, but we're constructing the array ourselves – we can skip needing to flatten it later.
(Specifically, I realised the bundle size increase in #8494 is because I accidentally added a lodash import – so I had a quick search for other uses of lodash that could come out.)

Remove an unnecessary use of lodash.flattenDeep

---

cardigan/stories/components/DateRange/DateRange.stories.mdx
cardigan/stories/components/DateRange/DateRange.stories.tsx
common/views/components/DateRange/DateRange.test.tsx
common/views/components/DateRange/DateRange.tsx

For https://github.com/wellcomecollection/wellcomecollection.org/issues/7831
We use `isSameDay()` in the DateRange component, and I wasn't sure if we want London or UTC. I wrote some additional documentation and tests, and that made it clear to me that we want a London-based comparison (although admittedly it's an edge case).
* We only render the times if the start/end are on the same day
* The times are rendered in a London timezone
There are two tests for the edge cases where this would cause weirdness if we don't do a London isSameDay() comparison:
* same London day, different UTC day
* different London day, same UTC day
The component itself is only a one-line change; the rest of the patch is the context that convinced me it was the right change to make.

Clarify that we want isSameDay(…, 'London') in the DateRange component

---

content/webapp/components/EventPromo/EventPromo.test.tsx

They're passing and they look reasonable; this looks like debugging code that got checked in accidentally.
Devs.
Making sure the tests help us find bugs.

Re-enable some skipped EventPromo tests

---

catalogue/webapp/pages/concept.tsx
catalogue/webapp/pages/images.tsx
catalogue/webapp/pages/works.tsx
catalogue/webapp/services/catalogue/images.ts
catalogue/webapp/services/catalogue/works.ts
common/services/catalogue/api.ts
common/utils/routes.ts
common/views/components/ImagesLink/ImagesLink.tsx
common/views/components/WorksLink/WorksLink.tsx
playwright/test/concept.test.ts
playwright/test/contexts.ts
playwright/test/selectors/concepts.ts

Replaces https://github.com/wellcomecollection/wellcomecollection.org/pull/8493
This is a simpler change with better testing.
* When you search for works/images, all the query parameter encoding happens inside `getWorks()` and `getImages()`. This means we get the correct results on concept pages with concept labels that need to be quoted (i.e. that contain commas).
* We already have functions for creating links to works/image search results with the correct query parameter encoding, but we weren't calling them from the concept pages. Now we are.
* The link from "Works by a subject" were linking to a subject search; now they link to a contributor search.
* I've added some e2e tests for the flow on the per-concept pages, which also gives us a nice set of examples to test with.

Make sure we quote parameters properly when searching for works/images on a concept page

---

common/views/components/Header/DesktopSignIn.tsx
common/views/components/Pagination/Pagination.tsx
common/views/components/PopupDialog/PopupDialog.tsx
common/views/components/SegmentedControl/SegmentedControl.tsx
content/webapp/pages/event.tsx

Follows https://github.com/wellcomecollection/wellcomecollection.org/pull/8432
One of the things I tried to do is avoid string interpolation in a way that means the formatter would split `font('intr', 6)` (or similar) across multiple lines, because that's way less readable IMO. This fixes a couple of other instances of that.
The other changes in SegmentedControl are because the pre-commit hook wouldn't let me commit until I fixed all the outstanding warnings.

Split a couple of classNames so the font() is on one line

---

catalogue/webapp/pages/images.tsx
catalogue/webapp/pages/works.tsx
catalogue/webapp/services/catalogue/index.ts
common/model/catalogue.ts
common/views/components/ApiToolbar/ApiToolbar.tsx
common/views/components/PageLayout/PageLayout.tsx

Jonathan and I have just had a confusing incident where we seemed to be getting mismatched results between the front-end and the API, because the front-end knew to quote the values, and we didn't.
This adds a link to the catalogue API query from the API toolbar, which should make this sort of thing easier to reason about – we can easily see what queries the front-end is making.
Developers.
Making it easier to debug the collections search.

Link to the raw catalogue API query in the API toolbar

---

content/webapp/services/prismic/transformers/articles.ts

Anyone reading articles 
Adjusting the `isArticleOrSerial` boolean to use format when it is available, and only use labels for Serial when format is not available.

make sure we only use labels if we have to

---

catalogue/webapp/services/catalogue/works.ts
common/services/catalogue/api.ts
playwright/test/works-search.test.ts

In particular this toIsoDateString got accidentally deleted when I was tidying up the filters for concept pages.
Anybody who wants to filter by date: https://wellcome.slack.com/archives/C8X9YKM5X/p1663763975934799
Fixing the bug I introduced in https://github.com/wellcomecollection/wellcomecollection.org/pull/8508

Fix the broken date filters on the works search

---

catalogue/webapp/pages/works.tsx

* Log a warning in the console
* `description` is empty for 500 errors, so use the label instead

Provide better logs when we forward a catalogue API error

---

common/views/components/DateRange/DateRange.tsx
content/webapp/pages/event.tsx

People who like correct grammar
Allows for space between comma and time in event (erased by flex)
Closes #8499

Fix Spacing issue: missing comma on date range

---

common/views/components/ApiToolbar/ApiToolbar.tsx

All editors who want to be able to copy any anchor links (`id=x`) on a page. Part of https://github.com/wellcomecollection/wellcomecollection.org/issues/8463
When the API Toolbar is active and you click ⚓️, any h2, h3 and h4 ids are extracted from page and appended to the current URL. A spreadsheet-friendly single-column list of these urls are copied to the clipboard, the editorial team can then paste this list of urls. 
~TODO~: 
- ~Trying to put this in a csv format so it pastes into a spreadsheet more easily~
- ~Some sanitising to be done to remove empty ids from the array of urls~

Feature: Add the ability to copy anchor links on a page

---

common/utils/grammar.ts
content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx
content/webapp/pages/exhibition-guide.tsx

Anyone generating anchor links for h2, h3, h4 titles/stops/tombstones for Exhibition Guides. For https://github.com/wellcomecollection/wellcomecollection.org/issues/8463
We want to make sure we don't end up with really long `#hash` in an anchor link url. `dasherize` was helpful in generating a readable hash for the ids, but we wanted to shorten them as titles are potentially quite long. I've created a new function `dasherizeShorten`, so as not to break functionality of current `dasherize` function elsewhere, this will limit us to getting the first four full words for the id. The upshot is this _should_ make anchor links predictable and shorter.

Add a dasherizeShorten function to shorten length of id anchor hashes

---

common/views/themes/mixins.ts
common/views/themes/utility-classes.ts

Devs.
Keeping the codebase clean by removing some unused classes. I searched the codebase for all these classes; if they weren't used I removed them. Most of them are pretty simple and would fall under the axe of #8420 anyway.
(I’m trying to work out how something works on the Stories homepage, so I’ve been reading the rendered CSS. I spotted some unused classes as part of that. :D)

Remove a bunch of utility classes that we aren't using

---

common/views/components/ApiToolbar/ApiToolbar.tsx
content/webapp/pages/exhibition-guide.tsx

Anyone using the API Toolbar to extract anchor links for audio and BSL guides
We previously only selected ids from H2, H3 and H4. Audio and BSL guide ids are contained within divs. ~This change extracts ids from divs that have a class that contains 'exhibition', this is to ensure we grab the divs that are within an Exhibition Guide page. It will return the div ids for audio and BSL guides and create the links and push them to the clipboard.~
This change will grab the apiToolbar id and extract the data-toolbar value and create an anchor link and push them to to the clipboard.

Extract ids from divs for audio and BSL guides

---

catalogue/webapp/pages/works.tsx
catalogue/webapp/services/catalogue/index.ts

To aid in future debugging. Unlike the previous patch, this will work for works as well as images.

When a catalogue API query fails, log the URL also

---

catalogue/webapp/components/PhysicalItemDetails/PhysicalItemDetails.tsx

Running locally on a fairly powerful iMac, this takes the time to expand the list of 235 items in the original ticket from ~45 seconds to less than a second -- because they're all manual requests, so we never need to create this modal component.
It'll still be slow if all the items are orderable online.  Fixing that feels like it needs a more substantial refactor, possibly to only create a single instance of that component.
For https://github.com/wellcomecollection/wellcomecollection.org/issues/8539
Users.
Making items load faster.

Defer creating the 'Request item' button/modal until we know we'll need it

---

content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx

Fixes #8482 
As discussed in the issue, this changes the font used for the Tombstone title to Inter, which has support for more glyphs
Before:
After:

Change title font to Inter

---

common/utils/dates.ts
content/webapp/components/StatusIndicator/StatusIndicator.test.tsx
content/webapp/components/StatusIndicator/StatusIndicator.tsx

Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/8503; for https://github.com/wellcomecollection/wellcomecollection.org/issues/7831
People who like accurate dates.
Making sure the StatusIndicator component displays the correct date at the boundary of exhibitions – dates are entered in Prismic in a London timezone, not UTC, so we need to do those comparisons in London time when deciding if an exhibition is future/open/closed.

Make sure the StatusIndicator component uses London date comparisons, not UTC

---

cache/send_slack_alert_for_5xx_errors.tf

Anyone in the alerts channel.
Avoiding Lambda errors when there are too many CloudFront events to process in 30 seconds.
(Maybe? Guessing, but this can't hurt.)

Bump the timeout on the CloudFront monitoring Lambda

---

content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx

All exhibition guide users. For https://github.com/wellcomecollection/wellcomecollection.org/issues/8480
Changing font size to make sure transcripts and captions have the same font size on desktop and mobile. 
before:
after:

Fix: adjust font size for transcriptions to make them the same as captions

---

prismic-model/downloadSnapshot.ts
prismic-model/lintPrismicData.ts
prismic-model/sliceAnalysis.ts
prismic-model/tryAllContentPages.ts

Devs.
Making this code easier to manage, and faster. Now `sliceAnalysis` will download a snapshot from Prismic once, then future analysis is on the locally cached copy until something changes in Prismic.

Reduce some repetition in the prismic-model scripts

---

common/views/components/MoreLink/MoreLink.tsx
common/views/components/Number/Number.tsx
common/views/components/SectionHeader/SectionHeader.tsx
common/views/components/WatchLabel/WatchLabel.tsx
common/views/themes/config.ts
content/webapp/components/Body/Body.tsx
content/webapp/components/Card/Card.tsx

A11y
Makes things readable, some of these are, to me, temp fixes (see new buttons colours, we should maybe check if a different green or a different beige background could be best as they don't fit the ratio and are probably common occurrences), so I'll make notes in finding longer term solutions.

Tweak components to have AA contrast

---

catalogue/webapp/pages/concept.tsx
common/model/catalogue.ts
common/views/components/ApiToolbar/ApiToolbar.tsx

Me
Making it easier for us to follow what's happening on the concepts pages. In particular, I now get:
* A link to the concepts API JSON
* A list of identifiers on the concept
Because it's hard to follow discussions about the source of the concepts data when I can't see where the data is coming from.
This continues a pattern I started in #8491, where individual pages know what their API toolbar links should be, rather than having the API toolbar hold all that context, and potentially have to refetch data that's already available on the page.
e.g. we already know what the concept data is, so we reuse that to build the toolbar rather than querying the concepts API a second time.
This is slightly more efficient and avoids bloating the API toolbar code.

Add some concepts information to the API toolbar

---

content/webapp/pages/article.tsx
content/webapp/services/prismic/transformers/articles.ts

Anyone who reads articles
Increases space between `|` and reading time text. Uses the phrase 'Average reading time' to step away from being ableist in our terminology, and changes min to minutes.

Reading time - changes based on feedback

---

content/webapp/pages/exhibition-guide.tsx

Fixes #8484 
__Before__
__After__

Don't show number of stops on C&T page type

---

common/data/vanity-urls.ts
content/webapp/app.ts

Devs and Editorial.
Moving the vanity URLs into the 'data' directory; this is the sort of thing that would be useful to review and manage outside the main application code.
This is a first step towards https://github.com/wellcomecollection/wellcomecollection.org/issues/8562

Move vanity URLs to the 'data' directory

---

prismic-model/src/parts/captioned-image.ts

Image editors
Preparing the model to allow them to round corners of an image programmatically (with css) rather than generating the image with rounded corners by hand.
An example of what is being done by hand currently:
from [this story](https://wellcomecollection.org/articles/YtgEcBEAACcA9ov3).
The latter approach will become problematic if/when the image doesn't appear on a cream background (or if the shade of the background changes).

Add option to round image corners to model

---

common/data/vanity-urls.ts

Visitors and https://github.com/wellcomecollection/wellcomecollection.org/issues/8562
Making a link they might be able to type in.

Add a vanity URL for colonial-roots statement

---

common/model/captioned-image.ts
content/webapp/components/CaptionedImage/CaptionedImage.tsx
content/webapp/components/ImageGallery/ImageGallery.tsx
content/webapp/services/prismic/transformers/images.ts

Image editors
Makes the Prismic toggle for rounding corners work on the front end.
__Prismic__
__Website
__

Add rounded corner styles to captioned images

---

common/views/components/OpeningTimes/OpeningTimes.test.tsx
common/views/components/OpeningTimes/OpeningTimes.tsx
content/webapp/components/VenueHours/VenueHours.tsx

Pop quiz! What day are we open late?
<table><tr><td>
<tr><td>
<tr><td>Before</td><td>After</td></tr></table>
While looking at the opening times for next week's rail strikes, I finally decided to fix a bugbear I’ve had for a while – we don't line up our opening times, which makes it hard to compare across days. Before it was a hard-to-read mess, now I can see that Thursdays are late opening and everything closes at the same time today.
Follows #8571.

Line up the hours in the opening

---

catalogue/webapp/types/styled-components.d.ts
common/types/styled-components.d.ts
content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx
content/webapp/components/ImagePlaceholder/ImagePlaceholder.tsx
content/webapp/pages/exhibition-guide.tsx
content/webapp/types/styled-components.d.ts
identity/webapp/types/styled-components.d.ts

Devs
Ensures the types in the theme are being checked. Solution based on this [SO suggestion](https://stackoverflow.com/questions/71074649/styled-components-w-typescript-missing-type-for-theme-variable). 
This brought to light a lot of errors on media queries so [`align-media-queries`](https://github.com/wellcomecollection/wellcomecollection.org/pull/8575) needs to be approved first.
Related to #8566

Styled component to extend theme types

---

common/services/catalogue/filters.ts
common/test/services/catalogue/filters.test.ts
common/views/components/ModalMoreFilters/ModalMoreFilters.tsx
common/views/components/SearchFilters/SearchFiltersDesktop.tsx
common/views/components/SearchFilters/SearchFiltersMobile.tsx

Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/8495, closes #8494 as superseded.
* Make the filter code easier to read
* Don't show quote marks around filters that need quoting; if we pass a label/value separately, we can still put the quoted value in the URL but not mess up the UI
* Don't show filters with 0 results, which makes no sense

Fix a couple of wrinkles in the filter UI

---

content/webapp/components/EventDatesLink/EventDatesLink.tsx
content/webapp/pages/event.tsx

Readers.
Not implying the existence of extra events. e.g. when I saw this header last night, I thought it meant there were multiple instances of this event and the header was just showing me the first:
but no, there's just a single date:
This change means we no longer show "See all dates" on event pages that just have a single date.
This is similar to how we only show "See all dates" on event promo cards that have multiple dates:

Don't show "See all dates" if there are no more dates to see

---

content/webapp/pages/exhibition-guide.tsx

At the moment we show all stops for a guide, regardless of whether they have content necessary for the type being viewed.
The options are to 1) not show these stops 2) show these stops but inform the user there is no content for the stop.
After discussion with @DominiqueMarshall we've decided to implement option 1, but may revisit this at a later date.
Before:
After:

Don’t show stops if they don’t have the necessary content

---

content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx

Fixes #8483
I've removed the spaced-text classes that were causing the space under the title to be applied. It doesn't seem to have affected anything else.
Before:
After:

remove spaced-text classes

---

content/webapp/pages/event.tsx

Users.
* Saving them from reading N copies of a slightly different "contact us if you have questions about access" message on long events
* Ensuring we always point to "ask us about access" even if we've not specified anything explicitly
Note: this will need the Editorial team to remove the hard-coded text from all of the event descriptions.
<table>
<tr><td>Before</td><td>After</td></tr>
<tr><td>
</td><td><img width="434" alt="Screenshot 2022-10-03 at 16 24 19" src="https://user-images.githubusercontent.com/301220/193615644-960e17c2-0256-462b-b040-fe696d71f38b.png"></td></tr></table>

Add a hard-coded message about event access

---

content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx

Users of the exhibition guides, for https://github.com/wellcomecollection/wellcomecollection.org/issues/8481
@alicerichmond has flagged that the grey lines are not part of the design. They were visible in firefox but I could also see them in chrome.
Before:
After:

removing keyline

---

common/utils/dates.ts
content/webapp/components/EventDateRange/EventDateRange.test.tsx
content/webapp/components/EventDateRange/EventDateRange.tsx

Devs and https://github.com/wellcomecollection/wellcomecollection.org/issues/7831
Explaining what this function is trying to do, and adding some tests so we're less likely to break it in future.
I've also moved it alongside the only component where it's used, so we don't try to use it in an unplanned scenario. The only change in this lift-and-shift is to replace `new Date()` with `today()`, so we can mock the current date in tests.

Add some tests and commentary for getEarliestFutureDateRange

---

common/views/components/PrismicImage/PrismicImage.tsx
content/webapp/components/Contributors/Contributor.tsx

Alice and the rest of Editorial.
Contributor images should always be black-and-white, but occasionally they're not, see https://wellcomecollection.org/events/YvTvQxAAACMA2dO4
This applies `filter: saturate(0%)` to desaturate any colourful contributor images that slip through.

Automatically desaturate contributor images

---

content/webapp/components/ExhibitionGuideLinksPromo/ExhibitionGuideLinksPromo.tsx
content/webapp/pages/exhibition-guide.tsx
content/webapp/services/prismic/transformers/exhibition-guides.ts
content/webapp/types/exhibition-guides.ts

This filters the type links (BSL, captions etc.) in the exhibition guide promos, so that they are only included if there is content of that type attached to the guide. See https://wellcome.slack.com/archives/CUA669WHH/p1664982249431029
Before:
After:

Filter exhibition guide links

---

common/views/components/Footer/FooterNav.tsx

a11y
Removes duplicate IDs in footer navigation, these weren't useful names either so I removed them.

Remove unused id causing duplicate a11y issues

---

common/views/themes/utility-classes.ts
content/webapp/components/LayoutPaginatedResults/LayoutPaginatedResults.tsx
content/webapp/pages/article-series.tsx
content/webapp/pages/exhibitions.tsx

Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/7633
Our most dedicated and devoted readers!
Allowing them to read every article in especially long series, e.g. Body Squabbles https://wellcomecollection.org/series/WleP3iQAACUAYEoN
I modelled it on the articles page, sticking two pagination buttons at the bottom of the list:
I considered putting an indicator of total count somewhere on the page, e.g. "1 – 20 of 120", but I couldn't find a good place to put it and this doesn't seem worth our currently limited design resource. It closes a functional gap; if it needs improving we can come back and give it more time later.

Add pagination buttons to article series

---

pa11y/webapp/deploy.js
pa11y/webapp/write-report.js

Devs.
Raphaëlle and I noticed that the pa11y report is being cached by CloudFront, so results can be delayed after a deployment. This adds an invalidation after the report is uploaded to S3, so results should appear immediately.

Run a CloudFront invalidation after pa11y deployments

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
catalogue/webapp/pages/concept.tsx
playwright/test/concept.test.ts
toggles/webapp/toggles.ts

Devs/Clean code likers
Removing traces of the ConceptPages toggle as we don't think we'll need it moving forward.

Remove concept toggle

---

content/webapp/pages/exhibition-guide.tsx

Users of exhibition guides and hopefully covers bug flagged by Danny and Alice 
https://github.com/wellcomecollection/wellcomecollection.org/issues/8485
Making use of the title if we have it, otherwise using the standalone title. I think this gives us the behaviour we want, but I'll check with Alice and Danny.
Before:
After:

 use title if we have it for a stop, otherwise use standalone title

---

content/webapp/services/prismic/transformers/articles.ts

Editorial, and anyone reading articles https://github.com/wellcomecollection/wellcomecollection.org/issues/8601
Adding in photo story, long read and prose poem to the included readingTime for articles

Add more formats to the 'showReadingTime' function

---

catalogue/webapp/services/catalogue/index.ts

Otherwise the logs are filled with complete nonsense like:
> Received error from catalogue API query https://api.wellcomecollection.org/catalogue/v2/works?query=ddos%C3%83%C2%A7%C3%82%C2%BD%C3%A2%C2%80%C2%98%C3%83%C2%A9%C3%82%C2%A1%C3%82%C2%B5%C3%83%C2%A7%C3%82%C2%AB%C3%82%C2%AF%C3%83%C2%A5%C3%85%C2%BD%C3%A2%C2%80%C2%B9%C3%83%C2%A5%C3%85%C2%A0%C3%A2%C2%80%C2%BA%C3%83%C2%A6%C3%82%C2%B5%C3%A2%C2%80%C2%B9%C3%83%C2%A8%C3%82%C2%AF%C3%A2%C2%80%C2%A2%C3%83%C2%A3%C3%A2%C2%82%C2%AC%C3%82%C2%90%C3%83%C2%A7%C3%82%C2%BD%C3%A2%C2%80%C2%98%C3%83%C2%A7%C3%82%C2%AB%C3%A2%C2%84%C2%A2gpk3688.com%C3%83%C2%A3%C3%A2%C2%82%C2%AC%C3%A2%C2%80%C2%98%C3%83%C2%A3%C3%A2%C2%82%C2%AC%C3%82%C2%90cc%C3%83%C2%A6%C3%A2%C2%80%C2%9D%C3%82%C2%BB%C3%83%C2%A5%C3%A2%C2%80%C2%A1%C3%82%C2%BB%C3%83%C2%A6%C3%82%C2%BA%C3%82%C2%90%C3% …

Filter out HTTP 414 errors from logs

---

cardigan/stories/components/Divider/Divider.stories.mdx
cardigan/stories/components/Divider/Divider.stories.tsx
cardigan/stories/global/palette/palette.stories.tsx
catalogue/webapp/components/Download/Download.tsx
catalogue/webapp/components/Work/Work.tsx
catalogue/webapp/components/WorkDetailsSection/WorkDetailsSection.tsx
common/views/components/Divider/Divider.tsx
common/views/components/Divider/README.md
common/views/components/Footer/Footer.tsx
content/webapp/components/EventPromo/EventPromo.tsx
content/webapp/components/LayoutPaginatedResults/LayoutPaginatedResults.tsx
content/webapp/components/Outro/Outro.tsx
content/webapp/components/VenueHours/VenueHours.tsx
identity/webapp/copy.tsx
identity/webapp/src/frontend/Registration/RegistrationInformation.tsx

Simplifies the Divider component, setting a default color and height. Prior to this change, you had to specify the type and color for the component to display properly, but it was using the same props 90% of the time.
I've also tweaked the story a little bit to explain. 
Closes #8630

Simplify Divider component

---

catalogue/webapp/components/CataloguePageLayout/CataloguePageLayout.tsx
catalogue/webapp/pages/works.tsx
common/data/cookies.ts
common/package.json
common/server-data/toggles.ts
common/services/conversion/track.ts
common/views/components/ApiToolbar/ApiToolbar.tsx
common/views/components/CookieNotice/CookieNotice.tsx
common/views/components/InfoBanner/InfoBanner.tsx
common/views/components/PageLayout/PageLayout.tsx
common/views/components/PopupDialog/PopupDialog.tsx
content/webapp/package.json
content/webapp/pages/guides/exhibitions/[id]/[type].tsx
yarn.lock

Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/8656
Devs.
Rationalising our cookie management on a single library (`cookies-next`). I've tested all these interactions and they're still working correctly.
The dashboard is still using `next-cookies`, but it's a standalone app stuck on Node.js 12 and it's not compiling properly, so I'm going to defer sorting that out until we dive in and do some other work on the dashboard to bring it up-to-date.

Consolidate on a single packaging for managing cookies

---

prismic-model/sliceAnalysis.ts

Before:
```
Slice count [
[ 'infoBlock', 104 ],
[ 'quote', 171 ],
[ 'embed', 205 ],
...
```
After:
```
=== Slice count ==
...
104	infoBlock
171	quote
205	embed
```
Devs.
Making the slice analysis tool easier to use.

Improve the tabular output of sliceAnalysis

---

common/data/vanity-urls.ts
content/webapp/pages/covid-welcome-back.tsx
content/webapp/pages/page.tsx

These icons are only loaded on a single page; better to move them out into a separate file, as we do for large content on "visit us" and "what's on" -- this cuts ~4% off the size of the initial bundle for all other pages.
Users.
Saving them a few bytes.

Move the "COVID welcome back" icons off the main page

---

.buildkite/urls/expected_404_urls.txt
content/webapp/pages/article-series.tsx

This was a bug that became possible in #7633, when we added pagination for article series.  The `transformArticleSeries()` method expects a non-empty list of articles; when we only got the first page, it was enough to check if the series is empty.  Now we can get higher pages, we need to additionally check if the selected page is empty.
Devs.
Fixing some alerts we got last night.

Don't 500 if somebody requests too many pages in an article series

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx

Add some missing spaces to the credit line on works

---

catalogue/webapp/package.json
identity/webapp/package.json
playwright/package.json
playwright/yarn.lock
toggles/webapp/package.json
yarn.lock

Devs
I was experiencing [this issue ](https://stackoverflow.com/questions/72488958/false-expression-non-string-value-passed-to-ts-resolvetypereferencedirective) and applying the suggested fix did work. 
> TS 4.7 upgrades the [resolution mode](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#resolution-mode) (see the last line). Given that the ts-node and ts-node-dev are using the old resolution mode internally, updating them to the later version, to be exact ts-node@>=10.8.0 and ts-node-dev@>=2, fixes this problem.
We moved our TS version a few days ago.
```
- "typescript": "^4.1.5",
+  "typescript": "^4.8.4",
```

Upgrade ts-node package

---

toggles/webapp/toggles.ts

Maintenance
After a chat with Jonathan we came to the conclusion that starting to build the new image search within `/images` wouldn't make sense, everything is too interconnected, so we'll build it behind the Search toggle instead.

Remove altImageSearch toggle

---

common/views/components/BaseTabs/BaseTabs.tsx

The tabs at `/works` have blue text on iOS (default since version 15 apparently). Setting a specific palette colour so that it renders the same on all browsers.
__Before__
__After__

Set color for tab buttons

---

common/views/components/CookieNotice/CookieNotice.tsx

users 
Makes the closing icon more visible

Make Cookie notice closing icon white

---

common/views/components/AudioPlayer/AudioPlayer.tsx

Screen reader users.
Making the audio player experience a bit less awkward.
* Playback rate buttons are now read as "1 of 4", not "1 of however many on the page"
* We only say "playback rate" once, and we include the "x"
* We don't double up the playback rate as you skip through it
* Fix some weird behaviour on the play/pause button
Screen recordings below.
<table><tr><th>Before</th><th>After</th></tr>
<tr><td><video src="https://user-images.githubusercontent.com/301220/196169282-e457acde-42fb-4cb2-afea-a391947e110b.mp4"></td><td>
<video src="https://user-images.githubusercontent.com/301220/196169090-2e70b8e7-e982-47c2-b3ab-a9b2d987cc74.mp4"></td></tr></table>

Accessibility fixes on the audio player

---

content/webapp/components/ComicPreviousNext/ComicPreviousNext.tsx

Fixing the comic navigation when titles are longer than they have been to date.
__Before__
__After__
Smaller font size so title more likely to appear in full
Fixed widths so trucation will work if the title can't appear on a single line

Fix comic nav truncation

---

common/services/prismic/opening-times.ts
common/test/services/prismic/opening-times.test.ts
content/webapp/components/VenueHours/VenueHours.tsx

For me, other devs, and https://github.com/wellcomecollection/wellcomecollection.org/issues/7831
Adding some comments explaining how the individual functions for managing opening times are meant to work. This is among the gnarliest code we've got, and I find it pretty tricky to follow or even work out what it's doing. This is just adding comments and renaming functions, so the behaviour should be unchanged – but hopefully easier to read for the next person who comes along.

Add function comments to the opening-times code

---

catalogue/webapp/components/IIIFViewer/IIIFViewer.tsx
catalogue/webapp/services/iiif/transformers/manifest.ts
catalogue/webapp/types/manifest.ts

The new transformer function wasn't returning the manifest id, which was stopping a label from displaying on works that were part of a collection.
The label is contained on the parent manifest and we needed the id to find it.

Stop the build from breaking

---

content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx

All guide users, based on Dom flagging things don't look like the design https://github.com/wellcomecollection/wellcomecollection.org/issues/8616
It changes Tombstone Title to be wellcome bold font, as per design. It adjust the sizing of this title and implements inter bold on the Tombstone text. I've put my reasoning for the chosen font sizing below. I have also adjust the size of the Tombstone section, and spacing between Tombstone Title and the yellow border to be closer to the design.
I showed this to Dom, and so far so good, but I'll obviously get it into staging so Dom can have a look proper.
I have [worked out](https://nekocalc.com/px-to-rem-converter) the closest rem match from [cardigan](https://cardigan.wellcomecollection.org/?path=/docs/global-typography--scale) to the designs …

Improve font sizing and spacing in exhibition guides

---

content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx

Anyone using guides
I had another chat with Dom and due to us viewing on large screen size the tombstone titles were coming out as being way too big, we sat and talked through the scale options and decided on this
before
after

Adjusting tombstone title

---

catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx
catalogue/webapp/pages/search/collections.tsx
catalogue/webapp/pages/search/events.tsx
catalogue/webapp/pages/search/exhibitions.tsx
catalogue/webapp/pages/search/images.tsx
catalogue/webapp/pages/search/index.tsx
catalogue/webapp/pages/search/stories.tsx
common/views/pages/_app.tsx

closes issue #8689 
- search page structures added
- utilised the `getLayout` pattern to have a reusable layout, taking the responsibility away from the page, in regards to rendering content that is not relevant to it
- rebased and merged work to have a functioning `/search/images` page

Search page layout concept

---

content/webapp/pages/article.tsx

Anyone reading articles
I had put 'average reading time' as uppercase, as there will be contributor and/or artist details before the reading time, this should be lowercase to match.

Update casing of reading time in articles (small pr)

---

dash/webapp/pages/pa11y.tsx

Now Raphaëlle has got the dashboard building again (see #8706), I can knock out a few ideas I've been sitting on.
*   Sort the results so any errors appear at the top of the list, to save having to scroll.
*   Make the page titles link to the page, which is more convenient than copy-pasting the URL.
*   Tidy up the error/warning/notice counts.  We only show the count if it's non-trivial (hidden if there are zero issues of this type; hidden if there's only a single issue), and we include a label to say "1 error" "2 warnings".  This is partly for colour-blind devs who can't distinguish the red/orange/blue, partly for new devs who don't know what the colours mean.
*   If there are no issues, say so in a pleasing green box rather than the 0/0/0.
*   Tweak padding and line wrap in the issue …

Make the pa11y dashboard a bit easier to use

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx
common/views/themes/config.ts
pa11y/webapp/package.json

Devs
pa11y wasn't updating correctly since I'd removed some needed command lines in package.json. 
I'm also following the suggestion to tweak `neutral.600`:
So: `neutral.600` on `warmNeutral.200` annoyingly has a ratio of `4.497:1`, which gets flagged in pa11y as it wants `4.5:1`. The suggestion is to replace #6b6b6b with #6a6a6a, which I'm happy to go with since the goal is to use the `warmNeutrals` as background colours.
It's really, really close in looks; I suggest we amend if needed in the future, but as the luminosity stays the same as before (42%), I believe it still matches what we were trying to achieve.

Readd missing pa11y commands, change neutral.600 slightly

---

catalogue/webapp/components/WorksSearchResult/WorksSearchResult.tsx

e.g. I spotted this on my phone:

Add non-breaking spaces so labels and values appear on the same line

---

dash/webapp/pages/pa11y.tsx

In the current version of the pa11y dashboard, you have to scroll through the whole list to check there are no issues – unless you know errors rise to the top, but that's not obvious.
This groups all the successes at the bottom of the page in a section titled "No issues reported on the following pages", so when everything is working it'll be super quick to review the dashboard. The whole thing is now visible without scrolling:
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

Group successes on the pa11y dashboard

---

.buildkite/pipeline.yml
dash/README.md
dash/webapp/components/Header.tsx
dash/webapp/next.config.js
dash/webapp/pages/toggles.tsx

Devs
Dashboard wasn't exporting `pa11y`'s `index.html` in the right place (same for `toggle`'s), so I've added some config that ensured the files were being deployed in the correct repos + added a `README.md` file.
I've also uncommented dash being deployed in our pipeline. I believe it was commented when it was broken, we now want it back.

Ensure dashboard updates properly 

---

common/utils/dates.ts
content/webapp/components/VenueHours/VenueHours.test.tsx
content/webapp/components/VenueHours/VenueHours.tsx

Site visitors.
Making it easier to see what our unusual opening hours are, and how they deviate from our regular hours.
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td>
</td>
<td>
</td></tr></table>
This was inspired by the way Chris Burns’ internal email about opening times was using red boxes/text to highlight deviations from our regular hours, and some other recent work to make all the opening times line up nicely.
Plus I’m giving away one of my tricks – I've added a comment explaining how I can make the site time travel.

Improve the way unusual opening hours are presented

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx
catalogue/webapp/components/VisuallySimilarImagesFromApi/VisuallySimilarImagesFromApi.tsx
catalogue/webapp/pages/image.tsx
catalogue/webapp/services/catalogue/images.ts
playwright/test/images.test.ts

A recent refactor in ExpandedImage moved the conditional around and introduced what looks like a bug:
```diff
diff --git a/catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx b/catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx
index 48ca44a89..51b990cf1 100644
--- a/catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx
+++ b/catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx
@@ -207,12 +207,12 @@ const ExpandedImage: FunctionComponent<Props> = ({
</ImageWrapper>
)}
<InfoWrapper>
-        <Space v={{ size: 'l', properties: ['margin-bottom'] }}>
-          <h2
-            className={`${font('intb', 3)} no-margin`}
-            dangerouslySetInnerHTML={{ __html: displayTitle }}
-          />
-          {displayContributor && (
+        {displayContributor && …
```

Fix image titles in the expanded image modal

---

catalogue/webapp/components/IIIFViewer/IIIFViewer.tsx

Fixing broken e2e tests. Without this dependency, the `currentManifestLabel` will stick on whatever is rendered first, rather than updating when a user navigates to a different volume.

Include transformedManifest as a dep for the currentManifestLabel

---

catalogue/webapp/pages/search/catalogue.tsx
catalogue/webapp/pages/search/images.tsx

Us not wanting people to have access to search pages
Re-adds the toggle check in the serverSideProps, it was removed by accident in a prior PR.

return notFound if searchPage toggles not activated

---

content/webapp/pages/homepage.tsx
content/webapp/services/prismic/transformers/card.ts
content/webapp/types/card.ts

Danny has pointed out that "In Plain Sight" is appearing twice on the homepage -- once as the top item in the header, once in the list of current exhibitions and events.
This PR adds a filter so if we're featuring an event/exhibition in the top spot, it won't appear again in the list.
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

Don't show exhibitions twice on the homepage

---

common/views/components/PaletteColorPicker/PaletteColorPicker.tsx
playwright/test/selectors/images.ts

Failing E2Es
The selector was `color={hexValue}`, but we moved away from having `color` printed in the DOM. I added a unique ID alongside, and used that as a selector in the test instead.

Change selector for colorswatch tests

---

catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx
catalogue/webapp/pages/search/images.tsx
catalogue/webapp/pages/search/works.tsx

New search page 
As discussed, moving # results to the page content itself
Change Catalogue's URL back ("Catalogue" is label, `works` is URL)

Move results to page content, change works url

---

common/utils/array.ts
content/webapp/pages/api/articles/index.ts
content/webapp/pages/api/events/index.ts
content/webapp/pages/api/exhibitions-related-content/index.ts
content/webapp/pages/api/exhibitions/index.ts
content/webapp/pages/api/multi-content/index.ts

I could be persuaded to make this a 400, but honestly I just want to make the alerts shut up.
Note that because this is blowing up when we call `JSON.parse()`, this isn't affecting Prismic, just our alerts.

Reject queries which are non-JSON or non-strings

---

catalogue/webapp/components/IIIFViewer/IIIFViewer.tsx
catalogue/webapp/components/IIIFViewer/MultipleManifestList.tsx
catalogue/webapp/test/utils/iiif.test.ts
catalogue/webapp/utils/iiif/v3/index.ts
playwright/test/contexts.ts
playwright/test/view-items.test.ts

Fixes #8792 
__Before__
__After__
This will also be fixed at the manifest level in due course (the label will consistently appear _after_ the title in the array), at which point this can be refactored away.
TODO:

Check we're using the intended string as the label for multi-volume content

---

content/webapp/pages/api/multi-content/index.ts

This should fix the failing e2e tests.

The multi-content API doesn't use JSON query parameters

---

content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx
pa11y/README.md
pa11y/webapp/write-report.js

Devs.
Making sure we can see accessibility issues on exhibition guides. I've run it locally and uploaded the report to the pa11y dashboard; a bunch of stuff isn't working. 😬 
I've fixed the low-hanging fruit, but there's more stuff to fix I can't get to tonight.

Test the exhibition guides in pa11y

---

identity/terraform/provider.tf
identity/terraform/stack/main.tf

I was poking around in the ECS console; it's massively over provisioned for the amount of traffic it gets.

Reduce the resources in the identity web app

---

catalogue/webapp/components/IIIFViewer/ViewerSidebar.tsx

Fixes #8815 
Currently any work that has a parent manifest containing items will display a 'Volumes' section in the viewer sidebar. This worked with IIIFv2, but seems like there's more hierarchy in IIIFv3 and the presence of a parent manifest doesn't necessarily mean that an item is part of a multi-part work. For that, there's a `multi-part` `SpecificationBehavior`.
__Before__
__After__

Only show Volumes for multi-volume works

---

.buildkite/urls/expected_200_urls.txt
pa11y/Dockerfile
pa11y/webapp/deploy.js
pa11y/webapp/write-report.js

This is some low-hanging fruit to improve pa11y after yesterday's retro.
* If the deployment failed (e.g. the report file doesn't exist), the pa11y job would still succeed in Buildkite! Don't do that.
* Bump to a newer version of Node.
* Add comments reminding people to cross-post new URLs between e2e tests and pa11y. Ideally they'd be the same, but that got a bit fiddly (see #8817) so I'm going to do this as a stopgap. I've also brought the two lists back into sync.
* I've added a `baseUrl` to the list of URLs in pa11y, so we could swap it out for another URL… eventually. 👀

Small improvements to pa11y

---

common/utils/dates.ts
common/views/components/SpacingComponent/SpacingComponent.tsx
content/webapp/components/EventsByMonth/group-event-utils.test.ts
content/webapp/components/EventsByMonth/group-event-utils.ts

The temporal overlords of the universe.
Respecting their wisdom and authority.

Fix a bug where the "What's on" page is still showing October

---

common/services/prismic/opening-times.ts
common/test/services/prismic/opening-times.test.ts

This reverses a decision in https://github.com/wellcomecollection/wellcomecollection.org/pull/4437
This makes it easier for visitors to get a complete sense of our dates, it behaves consistently with other opening times (e.g. bank holidays), and it avoids confusion about why each venue has different hours.
We can revisit this in future if it becomes a problem again (e.g. don't show unusual hours against a venue if has no unusual hours in the period), but let's deal with that when it arises, rather than try to build a complete solution now. This is enough for this weekend.
See https://wellcome.slack.com/archives/CUA669WHH/p1667561232988349

Always backfill the opening-times, even if the date is other

---

playwright/url-checker/ignore.ts

Our e2e tests keep failing because we can't load GTM, and it goes away if you wait long enough -- I strongly suspect GTM is applying some rate limiting that's making the URL checker flaky.
Devs.
Making our e2e tests not flake.
🍨

Ignore errors from the GTM tracking pixel in our e2e tests

---

.buildkite/pipeline.e2e-universal.yml

This isn't great, tests shouldn't be flaky, but it's what we're already doing and hopefully means "the tests are failing" is a bit more of a signal.

Retry the URL checker in the e2e tests

---

content/webapp/services/prismic/types/series.ts
content/webapp/utils/colors.ts

🧹 🧹 🧹 
Raphaëlle has fixed all these colours in Prismic, so we can delete the code for the legacy colour palette.
I remember her doing it, and I ran a quick tally of colours in the Prismic snapshot to double check:
```
11 accent.purple
14 accent.green
16 accent.blue
18 null
19 accent.salmon
```

Remove support for legacy colours on article series

---

content/webapp/__mocks__/events.ts
content/webapp/components/CardGrid/DailyTourPromo.tsx
content/webapp/components/EventDateRange/EventDateRange.tsx
content/webapp/components/EventPromo/EventPromo.tsx
content/webapp/components/Exhibition/Exhibition.tsx
content/webapp/components/FeaturedCard/FeaturedCard.tsx
content/webapp/pages/event-series.tsx
content/webapp/pages/events.tsx
content/webapp/pages/homepage.tsx
content/webapp/pages/season.tsx
content/webapp/pages/whats-on.tsx
content/webapp/services/prismic/events.ts
content/webapp/services/prismic/transformers/body.ts
content/webapp/services/prismic/transformers/events.ts
content/webapp/services/prismic/transformers/multi-content.ts
content/webapp/services/prismic/types/events.ts
content/webapp/types/body.ts
content/webapp/types/card.ts
content/webapp/types/events.ts
content/webapp/types/exhibitions.ts

For https://github.com/wellcomecollection/wellcomecollection.org/issues/8830
The crux of that issue is that we don't have access to detailed schedule information on EventBasic, which is what we use to render those promo cards.
We could get that by modifying the fetch links (which #8850 is prep for), but we don't need to drag the entire schedule onto EventBasic – that's way too much data! So my plan is to have a mini-schedule on EventBasic – `EventTime[]` (times, is booked, is fully booked online) – which we then use to render the cards if it's a multi-day event. Hopefully this will be clearer when I actually implement it.
This PR is a no-op refactoring to the event transformer as prep work for this – in particular it diverges the `Event` and `EventBasic` types, which turns out to expose a …

Tweak some of the event transformer code

---

content/webapp/pages/article-series.tsx
content/webapp/services/prismic/fetch-links.ts
content/webapp/services/prismic/fetch/events.ts
content/webapp/services/prismic/fetch/exhibitions.ts
content/webapp/services/prismic/fetch/multi-content.ts
content/webapp/services/prismic/fetch/pages.ts
content/webapp/services/prismic/types/articles.ts
content/webapp/services/prismic/types/books.ts
content/webapp/services/prismic/types/card.ts
content/webapp/services/prismic/types/collection-venues.ts
content/webapp/services/prismic/types/events.ts
content/webapp/services/prismic/types/guides.ts
content/webapp/services/prismic/types/index.ts
content/webapp/services/prismic/types/pages.ts
content/webapp/services/prismic/types/places.ts
content/webapp/services/prismic/types/project-format.ts
content/webapp/services/prismic/types/teams.ts

For https://github.com/wellcomecollection/wellcomecollection.org/issues/8846
In most cases these variables are either like-for-like, or the new variable is a strict superset of the fields in the old variable. There are a couple I couldn't work out, and I've added a comment.
Mostly this is meant to reduce confusion about where these come from, because there's now only one source (and variable naming convention) for fetch links.

Consolidate the fetchLinks variables

---

pa11y/webapp/write-report.js

The [deploy of the pa11y report is failing](https://buildkite.com/wellcomecollection/wc-dot-org-deployment/builds/1622#01846100-a3be-40a8-9c46-eb86ac8a0633) because the generation of the report is timing out. I couldn't see any obvious reason why, so have increased the timeout, which will hopefully fix the problem.
I've also added another page to test and prevented some warnings about max listeners and uncaught errors

Pa11y dashboard

---

catalogue/webapp/pages/search/works.tsx

users of the new sort
making sure that sorting the search results does what it's supposed to do when javascript is on
this was potentially affected when I added the code to remove empty query parameters

made sure the select dropdown does what is expected

---

catalogue/terraform/stack/main.tf

Addressing this in prod:
_(already applied)_

Bump catalogue CPU

---

catalogue/webapp/components/IIIFSearchWithin/IIIFSearchWithin.tsx

The search api for the iiif viewer used to return combined hits for a single canvas, whereas it now returns the hits individually. [Old](https://iiif.wellcomecollection.org/search/v0/b31362758?q=darwin) versus [new](https://iiif.wellcomecollection.org/search/v1/b31362758?q=darwin).
This means we can display the matching characters directly in the results rather than having to work out what to display.

use hit.match to display the matching characters

---

common/views/components/SubNavigation/SubNavigation.styles.tsx
common/views/components/TabNav/TabNav.styles.tsx

Those that are interacting with the new TabNav component
changing the scrollbar from always being present, to only being present if you require the scroll behaviour
closes #8874

Fixed the scrollbar always being present

---

content/webapp/components/EventsByMonth/group-event-utils.test.ts
content/webapp/components/EventsByMonth/group-event-utils.ts
content/webapp/services/prismic/events.test.ts
content/webapp/services/prismic/events.ts
content/webapp/services/prismic/types/predicates.test.ts
content/webapp/services/prismic/types/predicates.ts

This fixes a couple of bugs, some long-standing, some recently introduced:
* Last night's bug was caused by a mismatch between the What's On page and the Prismic event predicates.
The What's On page expects to only display events that start sometime in the future (otherwise it would put the Past label on the card, which looks weird) – but the Prismic predicates were fetching any event that ended sometime that day.
We had an event that ended at 7:30pm, which is why the outage lasted from 7:30 to midnight, when the predicate changed.
The fix is to modify the predicate so it also fetches events that end sometime after **now**, not sometime the same day.
* We're in the middle of a multi-day festival from 17th to 19th, but it's not showing on the What's On page – it's being filtered out, …

Fix the listing of events on the What's On and Past Event pages

---

cardigan/stories/components/TextInput/TextInput.stories.tsx
catalogue/webapp/components/IIIFSearchWithin/IIIFSearchWithin.tsx
common/views/components/SearchForm/SearchForm.tsx
common/views/components/TextInput/TextInput.tsx
identity/webapp/src/frontend/components/PasswordInput/PasswordInput.tsx

Designs
After tweaking the search input in https://github.com/wellcomecollection/wellcomecollection.org/issues/8820, I noticed the clear input button is too close to the search button, so we should change the alignment a little bit so it looks better. 
But I decided to refactor those further as it opened a can of worms (padding, font-size). I removed the buttons from within the input in the cases I could find. Please let me know if I may have missed some (**particularly as I'm struggling to run identity pages locally**)
Before
After
Before
After
Closes #8878

Realign button and search fields in older components

---

common/services/prismic/opening-times.ts

Hard-coding the variable value in the comment was daft, so I've removed it. I've also pulled up the magic number into a top-level constant, and added a comment about why it's set to its current value.
Future devs.
Not leaving misleading comments.

Fix a comment around exceptional opening times

---

cache/locals.tf
cache/send_slack_alert_for_5xx_errors.js

While debugging with Raphaëlle this morning, she said that her first point of debugging would be to click the prominent link 'see logs' in the Slack alert – even though that takes you to the raw CloudFront log file, which isn't very useful!
That link was originally meant to help debug the alert, but it's misleading and poor alert design.  It should be taking you somewhere useful!
This patch improves the alert by adding a link to a canned Kibana logging search for the front-end apps, which should contain more useful context. This canned search:
*   pre-filters to the front-end apps
*   adds a query that excludes a lot of logs that aren't interesting for debugging, e.g. 200 responses and the health checker
This is the first log in the alert, so people can debug app errors more quickly. …

Include a link to application logs in the Slack alerts

---

content/webapp/pages/whats-on.tsx

Design
Fixes missing margins in https://wellcomecollection.org/whats-on
There was an extra container that I'm not sure was useful, I cleaned up some classes - do let me know if these should stay in there, it just didn't look like it did to me.
Before
After

What's on: Remove extra grid container

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx
catalogue/webapp/components/VisuallySimilarImagesFromApi/VisuallySimilarImagesFromApi.tsx

Safari users
A few of us looked into it and it was a discovery in "[Safari likes to read into max-width/height auto its own way](https://stackoverflow.com/questions/10760243/safari-image-size-auto-height-css)". There might be a better fix but because we have such diverse aspect ratios in our images, this code was to allow for all of them to display nicely in the expanded model. In the meantime, this is the fix I'm suggesting. It's not perfect in Safari (there's a lot of spacing as the parent still adopts a square shape), but at least the image is true to its ratio.
I also found that the main image in the modal would be warped on mobile, so fixed it there too.
Before
After
--------
Before
After
Closes #8896

Apply object-fit for Safari

---

catalogue/terraform/stack/main.tf

This fixes a redirect loop we were seeing, and is already applied on stage and prod

Add an ALB listener for search/* app props routes

---

content/webapp/pages/event.tsx
content/webapp/services/prismic/events.test.ts
content/webapp/services/prismic/events.ts

An event time has two toggles to decide whether it's fully booked: one for in-person, and one for online.  We were only looking at the in-person toggle when deciding whether to show the "Fully booked" banner on the event; we should look at both.
I've had a quick look for other uses of `isFullyBooked`, but I can't see any other obvious instances of this mistake.
People looking at our events.
Not deterring them from an event they could still attend online.
See https://wellcome.slack.com/archives/C8X9YKM5X/p1669717891523899

Look at the onlineIsFullyBooked field for "Fully booked"

---

catalogue/webapp/components/SearchNoResults/SearchNoResults.tsx
catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx
catalogue/webapp/pages/search/events.tsx
catalogue/webapp/pages/search/exhibitions.tsx
catalogue/webapp/pages/search/images.tsx
catalogue/webapp/pages/search/index.tsx
catalogue/webapp/pages/search/stories.tsx
catalogue/webapp/pages/search/works.tsx
catalogue/webapp/services/prismic/fetch/articles.ts
catalogue/webapp/services/prismic/fetch/events.ts
catalogue/webapp/services/prismic/fetch/exhibitions.ts
catalogue/webapp/services/prismic/fetch/index.ts
catalogue/webapp/services/prismic/types/index.ts
catalogue/webapp/types/search.ts
catalogue/webapp/utils/search.ts
common/utils/grammar.ts

Devs and new search
- Aligns all three search pages in terms of how to render different states
- Images and Works don't display default results when the query is empty anymore
- We don't use `SearchNoResults` anymore when the query is empty, it's solely for when a query returns no results again.
- `hasFilters` for `SearchNoResults` now looks at all filters (not sure why it was only looking at specific ones - maybe this change wasn't necessary?)
- Moved each pages' H1 to `SearchPageLayout`
- Added `<link rel="next/prev" ... />` to `/search/works`. Probably should be added to stories too but only did it quickly here as part of the alignment, I think the rest depends on Pagination for Prismic content working.
Closes #8862 , #8863 , #8864

Align stories, works and images and set an empty default state

---

catalogue/webapp/pages/search/stories.tsx
catalogue/webapp/services/prismic/fetch/articles.ts
catalogue/webapp/services/prismic/fetch/events.ts
catalogue/webapp/services/prismic/fetch/exhibitions.ts
catalogue/webapp/services/prismic/fetch/index.ts
catalogue/webapp/services/prismic/types/index.ts

Anyone searching for stories at `search/stories`.
This covers https://github.com/wellcomecollection/wellcomecollection.org/issues/8819. It also covers https://github.com/wellcomecollection/wellcomecollection.org/issues/8860 because I have made Prismic GraphQL query results work with the `SearchPagination` component, meaning we don't need to create another pagination component to work with Prismic results.
Users can paginate through `search/stories` results.
Works and Images API responses both allow us to use previous and next pages to ensure that the `SearchPagination` component can be used to paginate through pages using the query parameters in the url e.g `https://wellcomecollection.org/search/stories?query=cats&page=2`. 
The Prismic GraphQL API response format is different, we don't …

Search: Stories pagination

---

catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx
catalogue/webapp/pages/search/events.tsx
catalogue/webapp/pages/search/exhibitions.tsx
toggles/webapp/toggles.ts

Devs
Allows us to keep working on the Events & Exhibitions sections for the new Search hub, separately from the other sections that will go out first.
Also add them to the SubNavigation item if the toggle is enabled.
Closes #8917

Events & Exhibitions toggle

---

common/views/components/Iframe/Iframe.tsx
common/views/components/VideoEmbed/VideoEmbed.tsx

Closes #8916
People who don't want to download unnecessary YouTube iframes
Showing them a poster frame button which loads in the iframe when pressed
We lose some YouTube chrome (copy link, watch on youtube etc.) but think this is a reasonable tradeoff for the page size savings (especially on e.g. guides [BSL pages](https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau/bsl) where there are 20+ videos which will likely be being visited on data plans or wellcome wifi)
**Before**
**After**

Defer load of youtube embed until user action

---

catalogue/webapp/components/IIIFClickthrough/IIIFClickthrough.tsx

☝️ 
Should fix `error: Iframe element requires a non-empty title attribute that identifies the frame.`

Include a title in the IframeAuthMessage for accessibility

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx
catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx
catalogue/webapp/components/VisuallySimilarImagesFromApi/VisuallySimilarImagesFromApi.tsx
common/services/conversion/track.ts
common/views/components/DownloadLink/DownloadLink.tsx
common/views/pages/_app.tsx

Reporting
- Makes `trackSegmentEvent` more flexible, allowing for `similary` OR `conversion` index.
- Tracks VSI journey (open modal/click on VSI/close modal).
Relates to #8841 and #8885

Make segment tracking allow for different indexes and track VSI

---

common/views/components/ErrorPage/ErrorPage.tsx

Devs/staff.
Making it easier to debug issues caused by an experimental toggle. If you have toggles enabled, you now get a yellow bar telling you about them on any error pages:
If a member of staff sends that screenshot to devs (which they often do), it makes it easier for us to reproduce the error and we don't have to remember to ask about toggles.
The main use case for this is the **stagingApi** toggle, because the staging catalogue API doesn't have the same uptime guarantees as the prod API – it's been broken recently, and we've had several confused staff asking why the collections search isn't working.

Highlight any selected toggles when you hit an error

---

common/services/conversion/track.ts
common/utils/cookies.ts
common/views/components/ErrorPage/ErrorPage.tsx

Part of #8911 
This adds any `toggle_` cookies to what we `track` with segment, as part of the [`properties` object](https://segment.com/docs/connections/spec/track/#properties)

Segment toggles

---

catalogue/webapp/components/Work/Work.tsx
catalogue/webapp/components/WorkTabbedNav/WorkTabbedNav.tsx
catalogue/webapp/pages/item.tsx
common/views/components/SubNavigation/SubNavigation.tsx
toggles/webapp/toggles.ts

Relates to #8910 and fixes #8909
- Adds tabbed navigation to the works page and item page behind a toggle.
- This will allow us to explore if/how this should work - e.g. what should happen in the case of audio/video.
- In combination with #8958, we'll be able to check @taceybadgerbrook can track what she needs and will be able to change the toggle to function as an A/B test when required
Work page:
Item page:

Works tabs toggle

---

content/webapp/pages/guides/exhibitions/[id]/[type].tsx

Add some space around buttons on guide page header for small screens

---

content/webapp/pages/guides/exhibitions/[id]/[type].tsx
content/webapp/pages/guides/exhibitions/[id]/index.tsx
content/webapp/pages/guides/exhibitions/index.tsx
toggles/webapp/toggles.ts

The first part of #8967.
* The stories landing toggle isn't used anywhere; we removed it from the display components in #8727
* The exhibition guides are now live for everyone; we can remove the conditional code
Once this is deployed, I'll follow up with a second PR to remove the exhibition guides toggle.

Remove some old toggle-related code

---

prismic-model/src/series.ts

☝️ 
For #8399 we need to be able to query for multiple `series` that contain comics. Currently there isn't a way to determine what type of thing a `series` contains. Adding a `format` would allow editors to mark a series as containing comics and enable the right stuff to be queried.
Once this was complete, there would also be a task to add the comic format to existing comic series in Prismic.

Add format to article-series in Prismic model

---

toggles/README.md
toggles/webapp/toggles.ts

For https://github.com/wellcomecollection/wellcomecollection.org/issues/8967
I've removed all the conditionals in the code (`if (!toggles.exhibitionGuides) { dontShowPage() }`) and deployed that version of the site, so there should be nothing looking at this toggle.

Remove the toggle for exhibitions guide

---

catalogue/terraform/stack/main.tf
common/services/prismic/fetch/index.ts
content/terraform/stack/main.tf

This should stem the intermittent errors we've been seeing in https://github.com/wellcomecollection/wellcomecollection.org/issues/8309

Use an API key to fetch Prismic content

---

catalogue/webapp/services/prismic/transformers/index.ts

The old code was causing us to show information on a story with a trailing pipe, e.g. '2 November 2017 | ', because the contributor information is a defined empty string. This patch will make `contributors` undefined if there aren't any, so we don't display the trailing pipe.
Normally I'd add a test for this, but since all this GraphQL code will be tossed when we get stories from Elasticsearch, I'm not so fussed.
Closes #8973

Skip showing empty contributors on a search story card

---

catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx

We weren't wrapping the `query` value from the URL query parameters in an object properly, so it was being iterated over incorrectly to produce URLs like
/search/stories?0=m&1=e&2=n&3=s&4=t&5=r&6=u&7=a&8=t&9=i&10=o&11=n
The clue is the default value, e.g. on L82 we had
url: { pathname: '/search/images', query: query || {} },
Here `query` is a raw query parameter from the URL; it cannot possibly be the same type as the default value `{}`.  Wrapping it in an object makes the canonical URLs work properly.
This was causing the weird behaviour I was seeing with Mobile Safari URLs – when you use the "Copy URL" action, it looks at the canonical URL, which was being created incorrectly from this code.

Fix a bug in canonical URLs for search pages

---

catalogue/webapp/services/catalogue/works.ts

This fixes a bug where the image modal will hang if the source work for an image has been redirected.
This is the issue I reported in #wc-platform-feedback on Friday afternoon, see https://wellcome.slack.com/archives/C8X9YKM5X/p1670599613843669:
> I'm not quite sure what's going on, but if I click on the first result in https://wellcomecollection.org/images?query=V0017955, I just get the loading modal
The alternative fix is to remove the `/api/works` proxy and have clients call the catalogue API directly, and get the redirect that way, but that felt like a more invasive change for a small bug.
(The even better change would be to support states for images in the pipeline (https://github.com/wellcomecollection/platform/issues/5470) – I think this occurred because a METS work got linked over …

Handle redirects when fetching works client-side

---

common/views/components/Pagination/Pagination.tsx
playwright/test/works-search.test.ts

e2es failing
It was looking for `aria-label="pagination"` to navigate, but these might now differ based on which page they are in, so I added a static ID instead and am using that as a selector.

Fix E2Es: Use id for tests in pagination

---

common/views/components/Pagination/Pagination.tsx
content/webapp/components/LayoutPaginatedResults/LayoutPaginatedResults.tsx
playwright/test/works-search.test.ts

broken e2es
The previous PR fixed only part of the problem, we need to change the ID to match the pagination that's visible on mobile.
Also noticed a missing prop for alignment so added it in.

Change id to always select pagination visible on mobile too

---

catalogue/webapp/pages/works.tsx
playwright/test/works-search.test.ts

devs in 🙏 fixing e2es 🙏  AND users wanting to use pagination on `/works` 😱 
So, YAY for tests! Both pagination components were hidden on mobile on `/works`, so we would've had zero pagination on mobile.  I've gone through everywhere other pages and they ALL now have at least one pagination component on mobile, it was only missing in this file, which is the one that was tested.
I'll add "Test more for pagination" to my January to do list. Thanks all for your patience with this one..!

Display bottom pagination for works in mobile

---

catalogue/webapp/components/Work/Work.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.tsx

This updates and renames the getItemLinkState function which due to #8955 only needs to return a boolean.
It also moves the logic into Work.tsx so it can also be used to wrap the tabbed nav and only show it when we have digitised items, as the 'view item' link wouldn't work. N.B. We may want to keep the 'catalogue details' tab for consistency, but if we come to that conclusion it will be an easy change.

Only show tabbed nav on works with digitised items

---

common/utils/grammar.test.ts
common/utils/grammar.ts
common/views/components/ModalMoreFilters/ModalMoreFilters.tsx

<table>
<tr>
<td>1156915 results </td>
</tr>
<tr>
<th>After</th>
<td>1,156,915 results</td>
</tr>
</table>
This matches [the Wellcome style guide](https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/18DwJCSD1tjue3OkGDPy/functional-digital-content-style-guide/wellcome-style-guide-april-2022-version) and is just a bit nicer to read imo.

Use commas when counting the number of results on a search page

---

common/views/components/ButtonSolid/ButtonSolid.tsx

I think this fixes the issues with Chromatic on main, maybe? I think we were getting an `undefined` or `null` somewhere in there, looks better now: https://www.chromatic.com/component?appId=62f13cdbd0ff140768a8d87b&csfId=components-tagsgroup&buildNumber=1861&k=63a198b2d80c3ca5a33d8a99-1200-interactive-true&h=5&b=-3

Try putting an empty string here, does this make borders happy?

---

common/views/components/Breadcrumb/Breadcrumb.tsx
common/views/components/PageHeader/PageHeader.tsx
content/webapp/components/LayoutPaginatedResults/LayoutPaginatedResults.tsx
content/webapp/pages/article-series-many.tsx
content/webapp/pages/articles.tsx
content/webapp/pages/books.tsx
content/webapp/pages/event.tsx
content/webapp/pages/events.tsx
content/webapp/pages/guides.tsx
content/webapp/pages/page.tsx

For https://github.com/wellcomecollection/wellcomecollection.org/issues/8771
* We always have 'Home' as the first entry in the breadcrumb, which fixes accessibility issues around an empty div
* Screen readers will now skip the vertical lines when reading the breadcrumb
* Remove some old code that's no longer used

Improvements to the breadcrumb

---

common/views/components/InfoBanner/InfoBanner.tsx

<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

Make sure the 'X' in the global banner is black on iOS

---

content/webapp/components/StatusIndicator/StatusIndicator.tsx

This makes the function behave more like we'd expect, and also fixes a flaky test.
Previously the function compared exact timestamps, e.g.
Mo Tu We Th Fr Sa Su Mo
^ now
^end date @ 5pm
The function would show "Final week" after we passed the time of the end date, e.g. on Monday at 4:59 it would say "Now on" and at 5:01 it would switch to "Final week".  Now it switches at midnight on Tuesday.
By doing per-day comparisons instead of looking at the exact h/m/s, we reduce the risk of a flaky test that can fail when we call `today()` a second apart, and get two slightly different timestamps.

Tweak how we check for "is in final week"

---

common/views/components/InfoBanner/InfoBanner.tsx

Me 😄 devs for simplified component
I noticed the alignment was a bit off on desktop, especially when the copy is only one line. So thought I'd take a quick look! Also simplified the code a little. It doesn't change too much visually, but adding mobile screenshots to prove it.
---
**Before:**
---
**After:**

Tweak InfoBanner CSS and simplify component

---

catalogue/webapp/components/CalendarSelect/CalendarSelect.tsx
catalogue/webapp/components/ItemRequestModal/useAvailableDates.ts
catalogue/webapp/components/RequestingDayPicker/RequestingDayPicker.tsx
catalogue/webapp/package.json
catalogue/webapp/test/utils/dates.test.ts
catalogue/webapp/utils/dates.ts
common/model/opening-hours.ts
yarn.lock

Follows https://github.com/wellcomecollection/wellcomecollection.org/pull/9043, fixes #9042
The bug occurs inside `isLibraryOpen()`, where we want to check if the library is open on a day of the week (given the regular opening hours).
We were calling `Date.getDay()` and comparing that to the regular opening days, but that function is locale-sensitive, and returns the day **in the user's timezone**, not in London. This causes issues when they're not the same.
This patch replaces it with `formatDayName()`, which works independently of the user's timezone.  It also allows us to pass around named days of the week, rather than day numbers, which imo is a bit clearer.

Don't rely on the user's locale to know what day it is

---

content/webapp/components/ContentPage/ContentPage.tsx

Closes #9026 (for now)
People who want more relevant content to display in mobile Safari reader view
Closing the `<article>` tag sooner, to exclude the (client-side-fetched) related content.
This appears to have the effect of including the desired content in reader view, although it also includes the blurb paragraph before any related content.
It seems Readability – the project reader view is based on – picks up on [certain classes](https://stackoverflow.com/a/15418461) to guess whether content is relevant or not. With this in mind, I tried adding e.g. `class="sidebar"` to the related content, but this only had the effect of prevent _any_ content from appearing in reader view altogether.
My only not-very-well-tested theory is that something in the client-side-fetching of content …

Improve safari mobile reader content

---

common/views/components/Footer/Footer.tsx

Fixes #9027 
People who want to be able to read zoomed content on their phone
Allowing the social icons in the footer to wrap if needed, preventing a horizontal scrollbar from being added (which was shunting text off the screen to the left).

Allow social icons to wrap when zoomed in

---

catalogue/webapp/components/Download/Download.tsx
catalogue/webapp/components/IIIFViewer/IIIFViewer.tsx
catalogue/webapp/components/IIIFViewer/ViewerTopBar.tsx
catalogue/webapp/components/ItemViewerContext/ItemViewerContext.tsx
catalogue/webapp/pages/download.tsx

Relates to #8907
Removes the license and credit information from the Downloads modal, [as discussed in 8907](https://github.com/wellcomecollection/wellcomecollection.org/issues/8907#issuecomment-1369662239)
Before:
After:

don’t display license/credit info in download modal

---

catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx
catalogue/webapp/components/StoriesGrid/StoriesGrid.tsx
catalogue/webapp/components/WorksSearchResults/WorksSearchResults.tsx
catalogue/webapp/pages/concept.tsx
catalogue/webapp/pages/images.tsx
catalogue/webapp/pages/search/images.tsx
catalogue/webapp/pages/search/index.tsx
catalogue/webapp/pages/search/stories.tsx
catalogue/webapp/pages/search/works.tsx
catalogue/webapp/pages/works.tsx

New search
- Integrates and styles the overview page.
- Create a StoryGrid component that we can use both in `/search` and `/search/stories` (just set `isDetailed` or not for the longer version with more information).
- Simplified what we send to `ImageEndpointSearchResults` and `WorksSearchResults` as only the list of results is required.
Closes #8741

Search overview (Front end)

---

catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx

Everyone
There's an issue in the CSS compiler and the title colour was overwritten. This makes it black - and readable - again.
Closes #9065

Specify color for image modal title

---

common/views/components/ApiToolbar/ApiToolbar.tsx

~Renames the iiif link on the api toolbar to iiif v2 and adds a iiif v3 link alongside it:~
Links to the iiif manifest version 3 from the toolbar instead of version 2

add link to v3 manifest on API toolbar

---

.buildkite/urls/expected_200_urls.txt
catalogue/webapp/pages/item.tsx

Previously we were only replacing the final part of the URL, so `/works/$oldId/items` would be redirected to `/works/$oldId/$newId`.

Fix broken redirects on item pages

---

catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx
catalogue/webapp/pages/search/stories.tsx
common/views/components/ButtonSolidLink/ButtonSolidLink.tsx
common/views/components/SearchBar/SearchBar.tsx

new search
- I went to other way with #9061 . The `isNewStyle` styles haven't been officialised and should be part of a bigger design decision. As you also need a visual/non-colour-change related feedback that the button is being hovered on, I went with our decision to use underline as hover behaviour, making the Search button underline.
- Aligned copy in Sort dropdown to match the microcopy.
Closes #9061

Align buttons in search + sort copy

---

catalogue/webapp/components/SearchNoResults/SearchNoResults.tsx
catalogue/webapp/pages/search/works.tsx

Users using search
- The message had lost its "please try again" part when it didn't have filters, re-added that
- Made sure dates were considered "selected" filters for the message (currently ignored)
Notes: `/works` only looks at dates as a filter, and `/images` at color only, in order to display "with the filters you have selected". I'm unsure why, we've changed that in the new search. I haven't fixed it as part of this ticket as we'll remove these pages shortly. But they've at least retrieved the "please try again" part of the message.
Closes #9062

Fix No results message

---

common/services/conversion/track.ts
common/views/pages/_app.tsx

Fixes #8961
The correct page data was only being sent when the page was rendered from the server and not when client side routing was involved.
This was because the useEffect inside useOnPageLoad didn't have pageProps as a dependency and so, "...your code will reference stale values from previous renders" ([Conditionally firing an effect](https://reactjs.org/docs/hooks-reference.html#conditionally-firing-an-effect)).
Instead of using useOnPageLoad, I've moved the page tracking code into its own useEffect with pageProps.pageview as the dependency. This seems to fix the issue and satisfies the [criteria](https://github.com/wellcomecollection/wellcomecollection.org/issues/8961#issuecomment-1339176821) @jamieparkinson outlined.
N.B.   pageProps.pageview is updated by getServerSideProps which …

Ensure correct data is sent with page view tracking

---

common/services/catalogue/filters.ts

British spelling!
- Changes "Licenses" to "Licences" on the UI as [flagged by Natalie](https://wellcome.slack.com/archives/C3TQSF63C/p1673432148251449?thread_ts=1673354994.931719&cid=C3TQSF63C). I remember having discussed this a few weeks back and making that change for the image modal, so doing this to align.
Closes #9067

Licences to use UK spelling for UI

---

content/webapp/pages/guides/exhibitions/[id]/[type].tsx

Part of #9038 
adds the Hotjar tracking script to all /guides/exhibitions/{id}/{type} pages which, in conjunction with a heatmap set up through the Hotjar interface, should allow us to see scroll depth for the audio-guides, bsl videos, and captions and transcripts.

Add hotjar to exhibition guide [type] pages

---

common/views/components/DropdownButton/DropdownButton.tsx
common/views/components/SearchFilters/SearchFiltersDesktop.tsx

New search - testing behaviour
Allows us to see if we prefer disabling dropdowns if no options are available VS hiding them completely.
You could test with something like `/search/works?query=musical&workType=c` or with a search term that returns nothing:
**Note:** This is just to start behaviour to start with, if we decide we'd like to go ahead with it, I'll style the disabled state differently. There is currently a design review for this component, so all those changes could be done at the same time.
Closes #9080

Disable filter dropdowns if no options are available

---

catalogue/webapp/components/ItemViewerContext/ItemViewerContext.tsx
catalogue/webapp/components/WorkDetails/WorkDetails.tsx
catalogue/webapp/services/catalogue/works.ts
common/model/catalogue.ts
common/test/fixtures/catalogueApi/work.ts

These go between place of publication/creation and physical description, as per Jonathan's instructions on the original ticket.
Looking at the example work listed in the ticket:
Closes https://github.com/wellcomecollection/platform/issues/5600

Add publication fields for serials to the work page

---

catalogue/webapp/components/StoriesGrid/StoriesGrid.tsx
catalogue/webapp/pages/search/index.tsx
catalogue/webapp/pages/search/stories.tsx
catalogue/webapp/services/prismic/transformers/index.ts
catalogue/webapp/services/prismic/types/event.ts
catalogue/webapp/services/prismic/types/exhibition.ts
catalogue/webapp/services/prismic/types/index.ts
catalogue/webapp/services/prismic/types/story.ts
catalogue/webapp/test/prismic/index.test.ts
common/model/image.ts

New search/faster results
- Uses `PrismicImage`, which ensures we only load the size of image we actually need.
- Modifies hover behaviour to match `/articles`'s
Closes #9059

WIP: Use PrismicImage in StoriesGrid

---

common/views/components/PaletteColorPicker/PaletteColorPicker.tsx

Devs
Fixes console warning:
```
Warning: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
```

Colour filter console warning fix

---

common/views/components/Tasl/Tasl.tsx
content/webapp/components/CaptionedImage/CaptionedImage.tsx

☝️ 
We were using strings with spaces for ids which isn't valid html.
**edit** ~~just seen that this won't be good enough because we also have multiple images on the same page with the same id (using the same title/source/copyright as the base).~~
**edit 2** ~~I've now dasherized the captions of `CaptionedImage`s and concatenated that onto the end of the dasherized title to ensure uniqueness.~~
**edit 3** At Ben's very sensible suggestion, I'm now using the guaranteed-to-be-unique image filename as the suffix.

Dasherize TASL ids

---

common/views/components/TextInput/TextInput.tsx
identity/webapp/src/frontend/components/PasswordInput/PasswordInput.tsx

☝️ 
We weren't using it as a prop in the styled-component and it is invalid to have `value` as an attribute on a div.

Take invalid 'value' prop off TextInputWrap (div)

---

catalogue/webapp/components/IIIFViewer/MultipleManifestList.tsx
common/views/components/Footer/FooterNav.tsx
playwright/test/view-items.test.ts

`role="navigation"` isn't valid on a `ul` (who knew). But the fix to wrap the `ul`s in a `nav` makes sense and more obviously semantic.

Use nav instead of role='navigation'

---

catalogue/webapp/package.json
common/package.json
common/utils/format-date.test.ts

Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/9048
These tests confirm that the existing code is working: if you take your laptop to San Francisco or Singapore or São Paulo, all the formatting code will show the same dates, as they are in London, not in your locale.

Add some tests for formatting dates in different user locales

---

cache/send_slack_alert_for_5xx_errors.js

To reduce noise in the #wc-platform-alerts channel.

Don't send error alerts for PHP endpoints

---

common/views/components/CookieNotice/CookieNotice.tsx
common/views/components/Icon/Icon.tsx

Valid html-ers
- preventing `h2` from appearing inside a `span`
- preventing a `div` from appearing inside a `button`

Ensure children are allowed elements within parents

---

common/views/components/PageLayout/PageLayout.tsx

☝️ 
It's not valid to occur after the first 1024 bytes apparently.

Move charset meta earlier in the document

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx

I was mixing up Python (where an empty list of string is False) and JS (where an empty list of string is true), so when we got nothing back from the API, it would show a heading with nothing under it.
Closes https://github.com/wellcomecollection/platform/issues/5600

Only show headings for former frequency/designation if they're populated

---

common/views/components/FindUs/FindUs.tsx

Valid HTML fans
Removing spaces from the telephone number in the `tel:` `href`

Remove spaces from tel in href

---

common/views/components/Modal/Modal.tsx

Users using filters
- The theory is that this property was causing the search to refresh as the referenced component was unmounted, causing some sort of racing condition with the rendered query. It's not a property we absolutely need so it's simpler to remove it. 
([more info on the property here](https://reactcommunity.org/react-transition-group/transition#Transition-prop-unmountOnExit))
Fixes #9116

Remove property causing race condition(?)

---

common/views/components/DropdownButton/DropdownButton.tsx
common/views/components/SearchFilters/SearchFiltersDesktop.tsx
common/views/themes/config.ts

design
the current filters in `/works` have a border that is the same colour as their background. When some buttons become disabled, their change in border colour make them seem bigger. I've put in a temp workaround to change the default border to white (matching the new button design in which there is no visible border). 
Also[ adding the "cleaning up" TODO as part of the post-new search cleaning list.](https://github.com/wellcomecollection/wellcomecollection.org/issues/9034)

Add a white border to filters dropdown as their current one is invisible

---

common/views/components/SearchFilters/SearchFiltersDesktop.tsx

New search
Debugging a [new search issue](https://github.com/wellcomecollection/wellcomecollection.org/pull/9121) brought to light another bug.
This was caused by the fact that in the new search, both the modal filters and the filters under the searchbar have the same id and are attached to the same form. 
There was logic in place that ensured that the form ID would not be assigned to the "desktop" filters if the modal was open, but not the other way around, which was the issue.
Because even when not displaying, the modal is rendered, which meant that fields were doubled, creating invalid URLs like `https://www-stage.wellcomecollection.org/search/works?query=human&workType=k&production.dates.from=%2C&production.dates.to=%2C`
Two empty date fields meant it was sending `[,]`  (`%2C` = `,` ) …

Search: Only assign form ID if the modal is open

---

catalogue/webapp/components/Sort/Sort.tsx

New sort component
- Removes `page=` from the query parameters when you change how you want to sort your results. This mimics the current search behaviour.
This was flagged in [new search feedback document](https://docs.google.com/document/d/1UHaHXMRSioQNesUMYUHdjlHRtAipDva_caCplhGpOxI/edit#) (functionality bugs n.2)

Reset pagination on sort

---

catalogue/webapp/pages/concept.tsx
catalogue/webapp/pages/search/index.tsx
common/views/components/MoreLink/MoreLink.tsx

New search, devs
- Makes query optional so the "All images" button doesn't link to `/search/images?query=`
- Switch to using `MoreLink` component, which just came to my attention.
- I used it in concepts too so I made the switch there and got rid of `leadingColor` which was a leftover from when we thought Concepts would have different colour themes.

Fix search query bug and use MoreLink component

---

common/views/themes/base/container.ts

People who want valid html
Removing an `@include` rule that we forgot to remove in the port to styled-components.
Removing the includes alone left the scrollbar on a white background below the cards (not what we want). Taking out the `::-webkit-scrollbar` background and the `::-webkit-scrollbar-thumb` `border-color` gets us back to parity with the current styles.

Remove sass (@include)

---

common/views/components/WobblyEdge/WobblyEdge.tsx
common/views/themes/base/normalize.ts

Valid HTML fans
Making sure there are the right amount of commas in the `clip-path` declarations

Put commas in the right place for clip-path polygon

---

common/views/components/PrismicImage/PrismicImage.tsx

Valid html-ers
Preventing `desaturate="1"` appearing in the rendered `img` markup.
I'm not too sure why this rejig works, but it does (and gets rid of the need to juggle between `boolean` and `1`| `0` for the prop.

Desaturate img

---

content/webapp/components/ImageGallery/ImageGallery.tsx

People looking at comics on their phones
Serving them the appropriately sized image (previously missing from the recently-updated `sizes`.

Serve the right sized image on mobile

---

common/views/components/SearchFilters/SearchFiltersDesktop.tsx

new search
- After discussing with Dom, lowering font-size in "More filters"
- Removing double `<ul>` (I think due to a conflicted merge in the past)
- Change var name to reflect it's boolean status.
Before
After

Lower new search's filters' font size

---

catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx
catalogue/webapp/pages/search/stories.tsx
catalogue/webapp/pages/search/works.tsx

New search
- Stories was adding the default sort values to the URL whenever a search was being done.
- Changed it to work like `/works` and `/search/works`, added a comment to explain.

Have stories sort mimic works and current behaviour

---

catalogue/webapp/__mocks__/tabbable.js
common/__mocks__/tabbable.js
common/package.json
common/views/components/Modal/Modal.tsx
identity/webapp/__mocks__/tabbable.js
yarn.lock

Filtering users
There's a bug currently that sometimes makes the filtering experience frustrating in that it doesn't select the filter that was clicked and scrolls back to the previously selected one. This seems to happen to filters who are below the "scroll line" and the theory is this `FocusLock` doesn't recognise them as part of the focusable zone.
I've updated the package we used from v8 -> v10 and added the `preventScroll` [option](https://github.com/focus-trap/focus-trap-react#focustrapoptions), which seems to fix it, I tried to replicate it as much as possible and it looks alright.
⚠️ to fix the tests, I've added config files to `__mocks__` folders based on the [recommendations in the package instructions](https://github.com/focus-trap/tabbable#testing-in-jsdom). Being new-ish to …

Add preventScroll option to FocusLock to prevent scrolling in modal

---

cache/send_slack_alert_for_5xx_errors.js

This moves the URI decoding up to the CloudFront log parsing, and now we filter out all logs which include a `%A` or `%a` anywhere.

Filter out all alerts that include a percent-encoded newline

---

common/utils/grammar.test.ts
common/utils/grammar.ts
common/views/components/Pagination/Pagination.test.tsx
common/views/components/Pagination/Pagination.tsx

Before/after:
A tiny little thing, but I noticed it while using the search and I think it makes the numbers more readable.
I also threw in a bunch of tests for the Pagination component which renders these buttons.

Add comma-separated numbers to the pagination component

---

catalogue/webapp/services/prismic/transformers/index.ts
catalogue/webapp/test/prismic/index.test.ts

Local & staging instances
Noticed that they were always linking to production, might've been for when we couldn't run the apps concurrently but I don't think it's what we want anymore. I know of `linkResolver` and I might look into it more as part of my [`getCrop` alignment ](https://github.com/wellcomecollection/wellcomecollection.org/issues/9127)as well.

Remove origin from story URL

---

common/data/microcopy.tsx
content/webapp/pages/stories.tsx

People who don't want a `TODO` on the frontend
Using the comic strapline text for the comic page description as well.

Use pageDescription for comic strapline

---

content/webapp/pages/api/events/index.ts
content/webapp/pages/event.tsx
content/webapp/services/prismic/fetch/events.ts

We want exactly two fields here: an id and title.  We don't need to fetch a full event, or more than one; fetching a single EventBasic will make a (small) reduction in the amount of data here.
Also, I can never remember what example to look at to debug this code, so add an example link.
Another tidy while reading code for https://github.com/wellcomecollection/wellcomecollection.org/issues/9090

Only fetch an EventBasic for client-side events

---

common/views/components/ButtonSolid/ButtonSolid.tsx

Ongoing search design
- Saves space by reducing padding on the right-hand side of the icon (or left side is `isIconAfter` is `false`) in the dropdown button + looks better
Before
After
This does cause the All Filters icon to be a bit snug, but we need to address the fact that our icons are not all the same size within their container, as a separate topic I'll bring up in the FE meeting

Tweak padding on the right hand side of the dropdown button

---

catalogue/webapp/components/IIIFImage/IIIFImage.tsx
catalogue/webapp/components/ImageCard/ImageCard.tsx
catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx

Users of the image search
The previous implementation made the user download every possible size of an image, regardless of what space was available. This change fixes that.

Properly sized images from the image grid

---

common/views/components/PageLayout/PageLayout.tsx
common/views/pages/_document.tsx

People who like valid HTML who hadn't accounted for the fact that Next can add elements to the head at various places.
Moving the `charset` to the first place where the `<Head>` is being included in the DOM, above the GA scripts.

Move charset again

---

catalogue/webapp/pages/images.tsx
catalogue/webapp/pages/search/images.tsx
catalogue/webapp/pages/search/works.tsx

On all these pages, we know we get a defined list of works/images as a result, so we can ditch all the optional types.
Spotted while reading other code for https://github.com/wellcomecollection/wellcomecollection.org/issues/9091

Remove some unnecessary optional types

---

.buildkite/urls/expected_200_urls.txt
pa11y/webapp/write-report.js

Automation testing
adding the newly created pages to the list of URLs that Pa11y will check.
closes #9053 
**please do not merge until the toggle for the new search page is defaulted to true**

add new search URLs to pa11y

---

catalogue/webapp/pages/concept.tsx

People who like readable numbers
Formats them in the concept page using the helper Alex created in https://github.com/wellcomecollection/wellcomecollection.org/pull/9169

Ensure numbers are formatted in Concept page

---

common/views/components/Modal/Modal.tsx
common/views/components/ModalMoreFilters/ModalMoreFilters.tsx
common/views/components/SearchFilters/SearchFiltersMobile.tsx

Design tweaks
- Removes "Series" as a filter option from the modal on mobile. This was already done on the desktop modal.
- Tweak modals' header and footer padding on desktop so they looks more centered and aligned.
- New style has extra `min-width` value as it looked strange without on certain queries that removed the need for two columns.
Before
After
The current search modal looks about the same as it currently does, sans "Series" as a filter

Small visual changes to the search modal 

---

.buildkite/urls/expected_200_urls.txt
common/views/components/SearchFilters/SearchFiltersDesktop.tsx
pa11y/webapp/write-report.js

Users
The filters weren't wrapping on the current search, creating a horizontal scroll on smaller screens. This ensures that it does wrap the way it used to, and cleans up some conditions.
It's getting quite complex in there because we have two versions of filters running at the same time, we'll be cleaning up all of this as soon as `/works` and `/images` are deleted.

Ensure filters wrap in current search

---

catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx
common/views/components/PaletteColorPicker/PaletteColorPicker.tsx
common/views/components/SearchBar/SearchBar.tsx
playwright/test/selectors/images.ts

Users of AT
addressing the issues flagged in pa11y related to the new search page
- search page submit form button was not semantically a submit button, this was solved by both adding the type of submit to it, and also wrapping the search bar inside of the form element.
- the PaletteColourPicket was assigning each swatch button a unique ID, which got duplicated due to the colour swatch being present in both the filter bar and the filter modal. The ID had no apparent functional value, so I replaced it with `data-test-id` and updated the selector in the test files.
closes #9180

Pa11y search changes

---

common/views/components/SearchFilters/SearchFiltersMobile.tsx

maintenance
`<FocusTrap>` is already set in the [`<Modal>` component](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/common/views/components/Modal/Modal.tsx#L305), so no need to wrap it in another one. It removes the console warning that brought this to attention (as it was conflicting with the first one's use of `ref`).
Closes #9181

Remove extra FocusTrap

---

prismic-model/lintPrismicData.ts

Editorial
Finds all Prismic articles that (1) don't have a promo image (2) don't have a promo image with a square layout
Closes #9191

Add a script to find articles without useable promo images

---

catalogue/webapp/components/IIIFViewer/IIIFViewer.tsx
common/services/catalogue/routes.ts
common/views/components/ImageLink/ImageLink.tsx
common/views/components/ItemLink/ItemLink.tsx

I don't understand why this works, but making the internal routing more consistent is no bad thing and seems to fix the infinite redirect.
(I wonder if it was saying "go to /works/$workId/items?canvas=5", which I expect to be rendered by route `/item.tsx`, and because it was being rendered by `/works/[workId]/items.tsx` instead, it was going into a whole new page/loop)

Fix the infinite loop on the items page

---

prismic-model/package.json

maintenance
Just noticed (linting error) license was declared twice (on line 4 as well)

Remove double license in package.json

---

catalogue/terraform/stack/main.tf

This prevents an infinite redirect on e.g. https://www-stage.wellcomecollection.org/works/re9cyhkt/items?canvas=5, in which Next.js can't load the getServerSideProps from items.json, and tries to reload the page.

Add the new items route to the ALB routing

---

content/webapp/components/ExhibitionGuideLinks/ExhibitionGuideLinks.tsx

Previously we were only adding the AD symbol on "Listen to audio w/wayfinding", but we want it on "Listen to audio" as well.
See screenshots in https://wellcome.slack.com/archives/C8X9YKM5X/p1675419084995139

Add the "Audio described" icon to the audio exhibition guides

---

.buildkite/pipeline.yml
.github/workflows/lighthouse_integration.yml
.github/workflows/performance.yml
playwright/test/view-items.test.ts
playwright/test/works-search.test.ts

This shuffles a couple of `wait`s around in an attempt to make the e2e tests more reliable. It’s not perfect, but it seems to fix the persistent run of failures we've had recently.

Make e2e tests reliable

---

catalogue/webapp/components/IIIFViewer/ViewerSidebar.tsx
catalogue/webapp/components/IIIFViewer/ViewerTopBar.tsx
common/views/components/WorkLink/WorkLink.tsx

Relates to [tidying up after the a/b test](https://github.com/wellcomecollection/wellcomecollection.org/issues/9032#issuecomment-1413846268)
This removes the itemWorkLink toggle and related code.

remove code wrapped in ItemWorkLink toggle

---

cache/edge_lambdas/src/toggler.ts
toggles/webapp/toggles.ts

Relates to [tidying up after the a/b test](https://github.com/wellcomecollection/wellcomecollection.org/issues/9032#issuecomment-1413846268)
This stops us setting the cookie in the cloudfront edge lambda and removes the test from the [toggles dash](https://dash.wellcomecollection.org/toggles/index.html)

remove itemWorkLink from toggler

---

content/webapp/pages/guides/exhibitions/[id]/[type].tsx

There's a particular reason why this logic is so conservative, and I think it's documented in Slack, but it should be in the code too.
Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/9198

Explain why we require a QR code before redirecting users on exhibition guides

---

catalogue/webapp/pages/search/index.tsx

Yesterday we were getting errors from this page in both prod and stage, which occur consistently:
https://wellcomecollection.org/search?query=drinks
This appeared to users as a completely broken page, not just our regular 500:
The app logs had the following error:
```
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
```
which gave me a clue that maybe we were going down an error path which doesn't have an HTTP status code, like here: https://github.com/wellcomecollection/wellcomecollection.org/blob/b2bd4fc575abde6550338254d748a9042a570188/catalogue/webapp/pages/search/index.tsx#L259
This PR adds some logging to that branch, which I deployed to stage so we can work out what's going on. It does fail, with the following error:
> Error: Internal server error: …

Don't fail as badly if there's an unexpected error during search

---

catalogue/webapp/components/Work/Work.tsx
catalogue/webapp/pages/concepts/[conceptId].tsx
catalogue/webapp/pages/works/[workId]/images.tsx
catalogue/webapp/pages/works/[workId]/index.tsx
catalogue/webapp/pages/works/[workId]/items.tsx
catalogue/webapp/services/catalogue/works.ts
common/model/catalogue.ts
common/views/components/ApiToolbar/index.tsx
common/views/components/PageLayout/PageLayout.tsx
content/webapp/components/Exhibition/Exhibition.tsx
content/webapp/components/Installation/Installation.tsx
content/webapp/pages/articles/[articleId].tsx
content/webapp/pages/books/[bookId].tsx
content/webapp/pages/event-series/[eventSeriesId].tsx
content/webapp/pages/events/[eventId].tsx
content/webapp/pages/guides/exhibitions/[id]/[type].tsx
content/webapp/pages/guides/exhibitions/[id]/index.tsx
content/webapp/pages/pages/[pageId].tsx
content/webapp/pages/seasons/[seasonId].tsx
content/webapp/pages/series/[seriesId].tsx
content/webapp/pages/stories/index.tsx
content/webapp/pages/whats-on.tsx

The API toolbar links all broke after we switched to absolute routing, because the API toolbar had a bunch of implicit knowledge of how the routes work; now every page gives the API toolbar a list of links to display – this should be less brittle.
Other benefits:
* On the work/image/item pages, we can pass the API response we've already received – the browser doesn't need to make a second request to get that information again
* When we link to the catalogue API URL for works/images, we can use the exact URL that was used to render the page (which doesn't always match what the API toolbar was using)
* The API toolbar should be smaller overall, because e.g. stories aren't getting the API toolbar code for works pages
Closes https://github.com/wellcomecollection/platform/issues/5657

Fix the API toolbar links

---

common/services/catalogue/filters.ts

e.g. "Great Britain (14989)" ~> "Great Britain (14,989)"

Add a comma to counts in filter labels

---

catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx

new search
- Renames Overview to All but in the UI only. I find it's clearer to keep it as `overview` in the codebase for other purposes
- Removes it from under the Collection section
Part of #9236

Search; Rename Overview to All and remove from under Collections

---

catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx
catalogue/webapp/components/SearchNoResults/SearchNoResults.tsx
catalogue/webapp/components/WorksSearchResults/WorksSearchResults.tsx
common/views/components/SubNavigation/SubNavigation.tsx
playwright/test/contexts.ts
playwright/test/new-images-search.test.ts
playwright/test/new-works-search.test.ts
playwright/test/search.test.ts

- duplicated the existing searches for works/images and pointed them to the new search pages
- added a few more search use cases for the overview and also the cross section navigation behaviour
- added `data-test-id` attributes for elements that need to be selected for testing purposes
closes #9193

test suites for the new search pages

---

catalogue/webapp/pages/search/images.tsx
catalogue/webapp/pages/search/works.tsx
common/views/components/ModalMoreFilters/ModalMoreFilters.tsx
common/views/components/SearchFilters/SearchFilters.tsx
common/views/components/SearchFilters/SearchFiltersDesktop.tsx
common/views/components/SearchFilters/SearchFiltersMobile.tsx

New search
If there are no results, the Color and Date filters should also be disabled (unless one of them is in use)
- in Desktop filter button
- in Desktop modal
- in Mobile modal (not sure why there are two different ones to be honest - something to look into?)
I checked it worked for:
- New search on desktop with Javascript
- New search on desktop without Javascript
- New search on mobile with Javascript
- New search on mobile without Javascript
- New search's modal box with Javascript
- New search's modal box without Javascript (doesn't exist)
And I've checked it didn't affect functionalities in the current searches as well.
Part of #9236

Disable all filters on NoResult in search

---

catalogue/webapp/components/WorkTabbedNav/WorkTabbedNav.tsx
common/views/components/ImageLink/ImageLink.tsx
common/views/components/WorkLink/WorkLink.tsx

These are leftovers from when we refactored our routing last week; among other things they're forcing clients to fetch the whole page again, which means the source is being dropped when navigating between pages.
Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/9257; I've run locally and verified that (1) the `source` is being dropped before this fix and (2) we get proper client-side routing with `source` after this fix.

Fix a couple of paths in Next routing

---

content/webapp/components/Card/Card.tsx

Previously this hover was always black, even on a dark background, but the text was white -- now the hover is white to match.
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

Fix the underline hover colour of card links on dark backgrounds

---

common/views/themes/base/layout.ts

Valid html-ers
Checking for support for the `has()` selector before attempting to use it (hoping it will solve an html css parsing validation error as well).

Check for :has() support

---

playwright/test/new-works-search.test.ts
playwright/test/works-search.test.ts

[Broken mobile e2es](https://buildkite.com/wellcomecollection/wc-dot-org-end-to-end-tests/builds/2384#018650ec-e306-4d26-8bdd-cbbe704a7849)
Waits for navigation before reading the page title on mobile. It was happening too fast and was reading the search page title instead.
I don't think this breaks the bugfix that was put in two weeks ago, as we wait for navigation at a different step than on desktop.

Fix mobile e2es for Works searches

---

common/views/components/ModalMoreFilters/ModalMoreFilters.tsx
common/views/components/SearchFilters/SearchFiltersDesktop.tsx
common/views/components/SearchFilters/SearchFiltersMobile.tsx

Devs and general good react behaviour
Because of "[the Glasgow problem](https://github.com/wellcomecollection/wellcomecollection.org/issues/9109)", some keys in rendered arrays were being repeated, making for bad practice in React. We decided to go with adding in the index (which is [a last resort solution](https://reactjs.org/docs/lists-and-keys.html#keys)), but left TODOs to remove them when #9109 is fixed.
I find this also outlines how repetitive our components are, which is something I hope we can streamline once we delete the old search for good.

Add index in key name as a temporary fix

---

common/views/components/SelectContainer/SelectContainer.tsx

Design
Matches Sort and Filters' looks more closely
Before
After

Change sort CSS to align it more with the filters look

---

common/views/components/Pagination/Pagination.tsx

The rough structure of this icon is:
```html
<ChevronWrapper>                  
<Wrapper className="icon">      
<svg class="icon_svg">
<svg xmlns="http://www.w3.org/2000/svg" …>
```
In the screenshots below, `ChevronWrapper` has a green background and `Wrapper className="icon"` has a yellow background.
Notice how, when `Wrapper className="icon"` has `position: relative`, iOS Safari doesn't size the element correctly relative to the parent, even though it sets explicit `width/height` styles. There are other examples on the web of people having issues with `position: relative` and iOS Safari, e.g. https://stackoverflow.com/q/15407636/1558022
I looked at the `SelectContainer` component, which is using the same chevron icon for its dropdown arrow (but rotated through 90 degrees). And inside …

Add `position: absolute` to make the pagination button look right on iOS

---

common/views/components/ButtonSolid/ButtonSolid.tsx
common/views/components/DropdownButton/DropdownButton.tsx
common/views/components/SearchFilters/SearchFilters.Desktop.DynamicFilters.tsx

Search
- Change disabled button styles to blend in better 
- Change identifier from class to data-attribute (keeping classes for styling only)
Before
After
Closes #9285

Disabled styles

---

identity/webapp/pages/api/registration.test.ts
identity/webapp/pages/api/registration.ts
identity/webapp/pages/registration.tsx

Not much to see here - realised that the token is already telling us where to redirect to, so we can use the issuer to construct the redirect URL rather than relying on our "own" information. Kinda twinned with https://github.com/wellcomecollection/identity/pull/393

Registration tweaks

---

catalogue/webapp/pages/images.tsx
catalogue/webapp/pages/search/images.tsx
catalogue/webapp/pages/search/index.tsx
catalogue/webapp/pages/search/works.tsx
catalogue/webapp/pages/works.tsx
catalogue/webapp/pages/works/[workId]/items.tsx
common/services/conversion/track.ts

* I've removed `pathname` as a variable we send to Segment; it's an internal property of our codebase and not something we should be relying on. More detail in the commit message. Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/9240
* I've added a type to check all our values of `pageview.name`, which encodes our analytics expectations in the type system. It's not perfect, but I think it will force us to be more intentional about the changes we make. Closes #9277.

Tidy up the analytics we send to Segment; lean on the type system more

---

content/webapp/pages/homepage.tsx
playwright/test/homepage.test.ts

Their documentation just says "add it to the homepage", not "add it to every page".
For https://github.com/wellcomecollection/wellcomecollection.org/issues/9289. I’ll leave the ticket open ~when this is deployed, and pass it back to Jenn to let Comms & Marketing know about the change~ until we've confirmed this is Comms & Marketing.

Add domain name verification for Meta/Facebook advertising

---

common/views/components/CookieNotice/CookieNotice.tsx

Another tiny step towards https://github.com/wellcomecollection/wellcomecollection.org/issues/8420
I've checked it locally; it seems to look the same in both local/live.

Replace some one-line classes with styled-components in CookieNotice

---

catalogue/webapp/pages/search/events.tsx
catalogue/webapp/pages/search/exhibitions.tsx
catalogue/webapp/pages/search/images.tsx
catalogue/webapp/pages/search/index.tsx
catalogue/webapp/pages/search/stories.tsx
catalogue/webapp/pages/search/works.tsx
common/services/conversion/track.ts
common/utils/cookies.ts
common/views/components/ErrorPage/ErrorPage.tsx
common/views/components/Header/Header.tsx
toggles/webapp/toggles.ts

Users who want to search + maintenance
- We were using the wrong function to check if the toggle was active. So
-- We changed that to use `useToggles()` as we should
-- Renamed the other function to signal we should think twice before using it
- Also cleaned up `searchPage` toggle as we probably won't completely hide it again (using redirect changes instead to "rollback")

Cleanup search toggles

---

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
catalogue/webapp/pages/works/[workId]/items.tsx

Following a discussion in Slack; we inadvertently broke this in the move from IIIF v2 to IIIF v3, because we made downloads conditional on the presence of a PDF.

We can allow people to download any video that's available online

---

common/views/components/ApiToolbar/index.tsx

This will make it clearer what's going on, and avoid people thinking the tzitzit button is toggled off or broken for some other reason.
I think this was a decision made by devs at some point, and tzitzit itself doesn't support creating attribution strings for in-copyright images -- we may need to tweak this.
See https://wellcome.slack.com/archives/C8X9YKM5X/p1676638166994149

Add a note if images are no-tzitzit because copyright

---

common/utils/numeric.test.ts

(I was writing a similar function in Ruby this weekend and got the logic a bit wrong; our implementation works but let's make sure it stays that way)

Add a couple of tests for the clamp function in numeric.ts

---

catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx

People who want tests to pass
Making the image search results always have the same `data-test-id` regardless of whether it counts as a 'small gallery' or not.

Use image-search-results-container for small gallery image search results

---

catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx
playwright/test/new-images-search.test.ts
playwright/test/search.test.ts

☝️ 
Since we're already inside a `data-test-id="image-search-container"`, the list-items are going to be images (so don't require further `data-test-id`s themselves.

Simplify the image list item selector

---

catalogue/webapp/services/prismic/transformers/index.ts

Search
Doesn't break the page when people find a result that doesn't have a promo caption.
This follows the model currently in use in `/stories`
Closes #9346

Allow for undefined promo captions

---

catalogue/webapp/pages/works/[workId]/images.tsx
catalogue/webapp/pages/works/[workId]/items.tsx
playwright/test/api-toolbar.test.ts
playwright/test/contexts.ts

*   The API toolbar link on /images was linking to /works/[workId]/images,
but it should be /works/[workId]/images?id=[imageId]
*   Ensure we can test image URLs in Playwright, in particular when we
add the cachebust parameter
*   Pass the proper contributors to tzitzit URLs on images
Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/9345

Fix the API toolbar tzitzit links; add some Playwright tests

---

catalogue/webapp/pages/search/stories.tsx
catalogue/webapp/services/prismic/fetch/articles.ts

Users
We're getting errors on certain queries (like https://wellcomecollection.org/search?query=t%3A%22PP.PRE.D.1.1%09%22)
We aren't handling them much at all + Prismic are not giving us much detail as to what's wrong/how to change our query, just getting `Internal Server Error`. So until we use our own API, we'll just return no result should this happen.

Return No Result should Prismic return an error

---

common/views/components/Header/Header.tsx
common/views/components/Header/HeaderSearch.tsx

everyone that is looking at the global search bar
explicitly looking at how event listeners have changed now.
it would appear that during the update, there will be a need to evaluate _how_ we toggle certain phases, the main issue that I saw with this, was that the button to cause the toggle was included in the elements that are valid for closing the toggle.
This was exposed in reacts anti-side effect change.
So the logic in the useEffect states, 
if the document is clicked (current element is excluded from calculations), check if the global search is currently displayed, then check to see if the button clicked was the toggle button, if so... ignore it (so that we don't have the toggle logic run twice, the toggle is controlled by the header), if anything else is clicked (once again, not …

Fix global event listener toggle

---

common/services/app/google-analytics.tsx

Relates to #9224
We used to send the toggles JSON blob to Universal Analytics and I replicated this behaviour for GA4. However, It turns out [GA4 now limits event parameter values to 100 characters](https://support.google.com/analytics/answer/9267744?hl=en) and so the value is being truncated.
This PR changes the event parameter value to a concatenated string of only the toggles we care about, i.e. those we may want to use for A/B tests whose values are true.
N.B. There is a danger we may still end up sending strings that are too long, so I'm going to update the toggle deployment script to warn if this is the case.
This isn't ideal but I think it is a practical solution, as we should never have too many toggles operating at once and this will encourage us to remove outdated ones.

limit the toggle data we send to GA4

---

content/webapp/pages/stories/index.tsx

☝️
We query for the 100 most recent comic articles, group them by series id and stop when we get three, then (since the comic series is attached to the comic article) we display the three most recent comic series _which are guaranteed to have at least one article_ on the stories landing page.
This removes the flakey requirement for the editorial team to add a `delist` tag to comic series when they don't yet contain any comics.

Work out most recent comic series from query for individual comics

---

common/views/components/ErrorPage/ErrorPage.tsx

People who don't want to see errors on the 404 page
Stopping this from happening:

prevent hydration error

---

common/views/components/Header/Header.tsx
common/views/components/PageLayout/PageLayout.tsx

Fixes #8717
The no javascript version of the burger menu relies on the footer being present on the page, as we then use an anchor link to take people to the navigation links in the footer.
This is a problem on certain pages where we remove the footer, e.g. exhibition guide and item pages.
Instead of removing the footer completely on these pages I've wrapped it in a noscript tag, so it is still available in the no javascript scenario.
I've also pointed the link to "/" instead of the footer nav, when javascript is available, to stop pa11y complaining that the named anchor doesn't exist.

Nojs footer

---

common/views/pages/_document.tsx

Fixes #9321
We [manually added a charset meta tag](https://github.com/wellcomecollection/wellcomecollection.org/pull/9105) to ensure it occurred in the first 1024 bytes of the document, in order to be valid html.
[Next.js now places this tag at the top of <Head /> itself](https://github.com/vercel/next.js/issues/26534#issuecomment-1031008721), so this is no longer necessary.
I've confirmed this works locally with the manual tag removed:

Remove manual charset meta tag
