wellcomecollection/wellcomecollection.org

- seasons/webapp/README.md
This spike yielded no results as it wasn't implemented.
> remove seasons

- catalogue/terraform/stack/main.tf
- catalogue/webapp/app.js
- common/next/next.config.js
- common/services/apm/apmConfig.js
- common/services/apm/initApm.js
- content/terraform/stack/main.tf
- content/webapp/app.js
- identity/terraform/locals.tf
- identity/terraform/stack/main.tf
- identity/webapp/next.config.js
- identity/webapp/src/app.ts
Turned out server-side APM needs to provide an API key - I've actually tested it this time rather than guessing!
> Actually fix APM

- catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx
> Render html in ExpandedImage modal titles

- common/views/components/Discussion/Discussion.tsx
Fixes #7031
__before__
__after__
_
> Simplify discussion component to prevent overflowing copy

- common/services/prismic/api.js
We are seeing sporadic ECONNRESET errors from Prismic that do not appear to be correlated to any particular requests or content. It seems possible that this is due to us using a _lot_ of TCP connections, so this custom agent keeps connections alive and allows a lot of open sockets.
> Possible fix for Prismic errors

- content/webapp/pages/stories.tsx
> Change featured serial to Lithium mania

- content/webapp/pages/whats-on.tsx
A code change
https://github.com/wellcomecollection/wellcomecollection.org/compare/fix/whats-on_ts?expand=1#diff-7b8f403372c6e80d526c764f28f5bcfa392f1afa800f5a355a815e5bb9a83590R426
Otherwise general conversion with `getInitialProps` => `getServersideProps`.
Last page to be converted.
> convert whats-on to typescript

- common/views/components/CardGrid/CardGrid.tsx
> add more space above CTA

- cache/edge_lambdas/src/toggler.ts
> add error type to toggler

- common/services/prismic/hardcoded-id.js
- common/views/components/FooterNav/FooterNav.tsx
> Add contact us to the footer

- identity/webapp/src/router.ts
- identity/webapp/src/types/schemas/request-item.ts
Fixes [issue where item requests fail](https://wellcome.slack.com/archives/CUA669WHH/p1636108866116000)
> Requesting failure

- identity/webapp/src/router.ts
> fix update user functionality

- common/package.json
- common/services/eventbrite/event-embed.js
- common/services/prismic/exhibitions.js
- common/services/prismic/pages.js
Developers who worry about code.
Making them have less stuff to worry about.
> Remove a couple of unused functions from Drupal/exhibitions

- identity/webapp/pages/account.tsx
People who don't want to see a 404 page after requesting that their account is deleted.
> use correct path for deletion request logout

- common/views/components/ArchiveBreadcrumb/ArchiveBreadcrumb.tsx
People who don't have Helvetica Neue on their machines
Making sure they get the webfont instead of Times New Roman
> Remove prototype helvetica neue hack

- identity/webapp/src/router.ts
- identity/webapp/src/utility/api-caller.ts
> Fix proxied request bodies

- prismic-model/src/series.ts
> remove unused dep from series prismic model

- .github/workflows/performance.yml
> Only run Lighthouse for a couple of pages in PRs

- identity/webapp/pages/account/delete-requested.tsx
- identity/webapp/pages/account/error.tsx
- identity/webapp/pages/account/registration.tsx
- identity/webapp/pages/account/validated.tsx
- identity/webapp/src/frontend/Error/Error.test.tsx
- identity/webapp/src/frontend/Registration/AccountValidated.test.tsx
- identity/webapp/src/frontend/Registration/Registration.test.tsx
- package.json
> Verify header size

- common/views/components/CookieNotice/CookieNotice.tsx
Part of #7264
User researchers
Letting them know when someone has dismissed the cookie banner
> Cookie banner

- common/views/components/PageLayout/PageLayout.tsx
> Add Hotjar to digital guide pages

- playwright/package.json
- playwright/tsconfig.json
- playwright/yarn.lock
> upgrade jest-playwright-preset

- cardigan/stories/components/CopyUrl/CopyUrl.stories.mdx
Fixes the path to the readme file.
> update CopyUrl README path

- common/views/components/SearchResults/AsyncSearchResults.tsx
- common/views/components/SelectUncontrolled/SelectUncontrolled.tsx
- content/webapp/components/SeriesNavigation/SeriesNavigation.js
- content/webapp/pages/article.tsx
Continues chipping away at https://github.com/wellcomecollection/wellcomecollection.org/issues/7302
> Move a few more components to TypeScript/specific apps

- common/services/prismic/exhibitions.js
- common/services/prismic/hardcoded-id.ts
- common/services/prismic/parsers.js
> Delete a bit of unused code in parsers.js; yet more TypeScript

- prismic-model/contentHasSlice.ts
- prismic-model/package.json
Gives general analysis as a starting point to see fi we can remove slices.
Might be a useful tool for editorial or product at some stage, but useful for me for now.
> add slice counter to slice analysis

- content/webapp/components/SeriesNavigation/SeriesNavigation.tsx
For https://github.com/wellcomecollection/wellcomecollection.org/issues/7302
The event types were a bit fiddly, but I looked at where this component is used and it looks like we never actually pass in events here.
> Convert SeriesNavigation to TypeScript

- cardigan/stories/components/Cards/Cards.stories.mdx
- content/webapp/components/StoryPromo/README.md
> fix StoryPromo paths

- catalogue/webapp/services/catalogue/common.ts
- catalogue/webapp/services/catalogue/images.ts
- catalogue/webapp/services/catalogue/works.ts
- toggles/webapp/toggles.ts
For everyone
Get rid of a toggle that no longer has any effect
> Remove tei toggle

- toggles/webapp/s3-utils.ts
- toggles/webapp/setDefaultValueFor.ts
This was the there to ensure I wasn't overriding things when testing.
> remove `test-` from s3 key in toggles

- content/webapp/components/ExhibitionPromo/ExhibitionPromo.tsx
Introduced by not seeing this
https://github.com/wellcomecollection/wellcomecollection.org/pull/7372/files#diff-4355557fe4f2ae131a420f9c23f4d2e0beefb782d4e807bc186791b4ec3d3ed4L86-L87
## After
> hide dates on permanent exhibitions

- common/views/components/FeaturedCard/FeaturedCard.tsx
Seems like quite a complicated component that could use some 👀 at simplifying.
No actual code changes. Would have moved it to content, but `Body` relies on it, so I'll move over there.
#7302
> convert FeaturedCard to tsx

- prismic-model/src/pages.ts
> remove text dep from pages prismic model

- assets/humans.txt
> 👋 Alice FC

- identity/webapp/pages/account/validated.tsx
Fixes #7358
Logged out:
Logged in:
> Change button text based on userState

- common/views/components/GlobalContextProvider/GlobalContextProvider.tsx
> opening times hack

- identity/webapp/pages/account.tsx
- identity/webapp/pages/account/delete-requested.tsx
- identity/webapp/pages/account/error.tsx
- identity/webapp/pages/account/registration.tsx
- identity/webapp/pages/account/validated.tsx
- identity/webapp/src/frontend/MyAccount/MyAccount.style.ts
- identity/webapp/src/frontend/Registration/AccountCreated.tsx
- identity/webapp/src/frontend/components/Layout.style.ts
Fixes #7279
and updates other pages so spacing and fonts are consistent
> Email verification

- common/model/article-series.js
- common/model/article-series.ts
- common/model/books.js
- common/model/books.ts
- common/model/event-series.js
- common/model/event-series.ts
- common/model/events.js
- common/model/events.ts
- common/model/pages.js
- common/model/pages.ts
- common/services/prismic/article-series.js
- common/services/prismic/books.js
- common/services/prismic/event-series.js
- common/services/prismic/events.js
- common/services/prismic/pages.js
- common/services/prismic/seasons.ts
- content/webapp/services/prismic/articles.ts
- content/webapp/services/prismic/background-textures.ts
- content/webapp/services/prismic/body.ts
- content/webapp/services/prismic/books.ts
- content/webapp/services/prismic/event-series.ts
- content/webapp/services/prismic/events.ts
- content/webapp/services/prismic/exhibitions.ts
- content/webapp/services/prismic/pages.ts
- content/webapp/services/prismic/places.ts
- content/webapp/services/prismic/types.ts
This allows me to access the document directly when in the content app.
> Prismic document all the things

- content/webapp/components/Body/Body.tsx
- content/webapp/pages/stories.tsx
> fix path to FeaturedCard

- cardigan/stories/content.ts
- common/model/organization.js
- common/model/people.js
- common/model/people.ts
- common/services/prismic/fetch-links.js
- common/services/prismic/parsers.js
- common/utils/json-ld.js
- content/webapp/content/static-books.js
> remove twitterHandle

- content/webapp/components/Installation/Installation.tsx
There seems to be a few subtle differences between exhibitions and installations that I imagine aren't doing much that might be worth digging into (e.g. Why are the contributors done differently)?
This fixes @dannybirchall's immediate issue.
> add seasons to installation

- content/webapp/services/prismic/link-resolver.test.ts
- content/webapp/services/prismic/link-resolver.ts
* tests linkResolver
* types the routes we can get back
> linkResolver tests and path typing

- content/webapp/components/StoryPromo/StoryPromo.tsx
> Stops serial tag showing on story promos where it shouldn't

- content/webapp/pages/api/articles/index.ts
- content/webapp/pages/api/series/[id].ts
- content/webapp/services/prismic/fetch/index.ts
Looks nicer and works for API routes.
> slightly nicer implementation for enableAutoPreviewsFromReq

- content/webapp/components/Contributors/Contributor.tsx
> Only show 1 contributor image

- identity/webapp/next.config.js
I didn't know that `basePath` didn't get applied to assets - hopefully this will fix it, it's very hard to test so not totally sure
> Fix asset paths

- .buildkite/expected_200_urls.txt
- content/webapp/components/ContentPage/ContentPage.tsx
- content/webapp/services/prismic/transformers/contributors.ts
- content/webapp/test/services/prismic/transformers/contributors.test.ts
For https://wellcomecollection.org/guides/YL9OAxIAAB8AHsyv
> Fix another 500 error with missing contributors from Prismic

- content/webapp/services/prismic/transformers/index.test.ts
- content/webapp/services/prismic/transformers/index.ts
- content/webapp/services/prismic/types/index.ts
Return empty promo is there isn't one.
> return empty promo is there isn't one

- .buildkite/expected_404_urls.txt
Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/7417
> Check that case-insensitive article lookups are a 404

- content/webapp/services/prismic/types/articles.ts
Fixes Alice's issue here: https://wellcome.slack.com/archives/C294K7D5M/p1638872908163600
I'll write a test in a separate patch.
> Remember to fetch the contributors when loading articles

- playwright/test/articles.test.ts
- playwright/test/contexts.ts
This test fails if you run it against current stage/prod, but passes if I run it against my local branch with the fix from https://github.com/wellcomecollection/wellcomecollection.org/pull/7445
> Add a Playwright test that we're including contributors on articles

- common/next/next.config.js
- common/views/components/Header/DesktopSignIn.tsx
- common/views/components/Header/MobileSignIn.tsx
Missed these when I was updating URLs
> Fix logout links in header

- identity/webapp/pages/registration.tsx
- identity/webapp/pages/validated.tsx
- identity/webapp/src/frontend/Registration/AccountValidated.test.tsx
> link to the account page

- .buildkite/expected_200_urls.txt
- content/webapp/services/prismic/types/index.ts
Fixes the 500 error on https://wellcomecollection.org/articles/XLSV-BEAALNzvQVz
> Fix a 500 on webcomics link

- common/server-data/index.ts
We're seeing a bunch of errors in the application logs like:
Could not read /app/catalogue/webapp/.server-data/toggles.json SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at read (/app/catalogue/webapp/.next/server/chunks/164.js:46:17)
at async getServerData (/app/catalogue/webapp/.next/server/chunks/164.js:85:23)
at async getServerSideProps (/app/catalogue/webapp/.next/server/pages/work.js:3906:22)
at async Object.renderToHTML (/app/node_modules/next/server/render.tsx:733:13)
at async doRender (/app/node_modules/next/server/next-server.ts:1669:27)
at async /app/node_modules/next/server/next-server.ts:1783:21
at async /app/node_modules/next/server/response-cache.ts:94:25
This probably coincides with a write to the file -- we're reading it as another process has it …
> Write server data to a temp file, then rename

- catalogue/webapp/components/IIIFViewer/MainViewer.tsx
- catalogue/webapp/services/catalogue/works.ts
- playwright/test/contexts.ts
- playwright/test/view-items.test.ts
> Viewer alt text

- .buildkite/pipeline.yml
- cardigan/stories/components/BookPromo/BookPromo.stories.mdx
- cardigan/stories/components/BookPromo/BookPromo.stories.tsx
We keep breaking the build; I'm hoping that running Cardigan builds on pull requests will help us catch them before they land in main.
> Fix Cardigan, and test it in PRs

- prismic-model/README.md
Developers who don't want to break the website
Providing guidance on the order in which to deploy changes to Prismic custom types and the queries to those custom types
> update readme following discussion at incident retro

- .buildkite/expected_200_urls.txt
- content/webapp/services/prismic/types/articles.ts
For https://github.com/wellcomecollection/wellcomecollection.org/issues/7473. This should fix https://wellcomecollection.org/articles/W_LXOxcAACwAxC5_
> Remember to fetch the event links when viewing an article

- common/model/user.ts
- common/views/components/UserProvider/UserProvider.tsx
- identity/webapp/config.js
- identity/webapp/src/utility/auth0.ts
This will stop the app from crashing for anyone who was logged in before my last PR was merged
> Fix for broken sessions

- infrastructure/modules/service/main.tf
This is already applied (and it works)
> Use new nginx module/image

- assets/humans.txt
> Move James to alumni

- content/webapp/content/static-books.ts
Fixes the book promo image
Before:
After:
> don’t crop the cover image

- .buildkite/expected_404_urls.txt
- content/webapp/app.ts
Pretty sure this is most of the 500 errors we're currently serving.
> If somebody tries to look up a non-Prismic ID, return a 404 sans query

- catalogue/webapp/model/iiif.ts
- catalogue/webapp/pages/item.tsx
- catalogue/webapp/utils/iiif.ts
While trying to debug https://github.com/wellcomecollection/wellcomecollection.org/issues/7499
> Add a couple of missing types in the IIIF viewer

- catalogue/webapp/components/LibraryMembersBar/LibraryMembersBar.tsx
- catalogue/webapp/components/PhysicalItemDetails/PhysicalItemDetails.tsx
- catalogue/webapp/components/SignInBar/SignInBar.tsx
- catalogue/webapp/components/WorkDetails/WorkDetails.tsx
- toggles/webapp/toggles.ts
Resolves https://github.com/wellcomecollection/wellcomecollection.org/issues/7496
Toggle is not yet enabled by default.
> Add building closure toggle + changes

- toggles/webapp/toggles.ts
To be merged and deployed later today
> Default buildingClosure to true

- catalogue/webapp/model/iiif.ts
- catalogue/webapp/pages/item.tsx
- catalogue/webapp/utils/iiif.ts
This fixes the issue with thumbnails not appearing, but I'm not sure why yet.
> Revert "Merge pull request #7500 from wellcomecollection/more-iiif-types"

- common/model/seasons.js
- common/model/seasons.ts
- common/services/prismic/seasons.ts
- content/webapp/pages/homepage.tsx
- content/webapp/pages/season.tsx
References #7363
Displays articles on season pages, using the new fetch and transform methods
> Moving articles to content app

- common/services/prismic/parsers.js
- content/webapp/services/prismic/transformers/contributors.ts
> Re-add default contributor image

- catalogue/webapp/app.ts
> Remove redirects that were used for cognito

- catalogue/webapp/utils/iiif.ts
People who want to see digitised unrestricted items in the viewer.
Preventing an unnecessary modal appearing.
> Handle service without authService

- common/services/prismic/opening-times.ts
- common/test/services/prismic/opening-times.test.ts
References #7525 
adds test for getExceptionalVenueDays function
> Opening times tests 2

- cardigan/stories/components/VenueClosedPeriods/VenueClosedPeriods.stories.mdx
- cardigan/stories/components/VenueClosedPeriods/VenueClosedPeriods.stories.tsx
- content/webapp/components/Body/Body.tsx
- content/webapp/components/VenueClosedPeriods/README.md
- content/webapp/components/VenueClosedPeriods/VenueClosedPeriods.tsx
references #7525 
Adds the VenueClosedPeriods component to cardigan and moves the component to the content app
> Cardigan venue closed periods

- content/webapp/pages/stories.tsx
> Update stories serial to Assistive Vision

- playwright/test/view-items.test.ts
> Don't only run Scenario 11

- catalogue/webapp/components/ItemRequestModal/ItemRequestModal.tsx
> Make requesting button work again

- common/views/components/Header/Header.tsx
- common/views/components/Header/HeaderPrototype.tsx
- content/webapp/pages/whats-on.tsx
- playwright/test/landing-pages.test.ts
Danny in Slack, but also for https://github.com/wellcomecollection/wellcomecollection.org/issues/5348
Look at the beautiful curls:
> Use curly quotes everywhere for "What's on"

- common/services/prismic/html-serializers.tsx
- common/services/prismic/parsers.js
- common/views/components/FeaturedText/FeaturedText.tsx
- common/views/components/PrismicHtmlBlock/PrismicHtmlBlock.tsx
- content/webapp/components/Body/Body.tsx
- content/webapp/components/HTMLSerializers/HTMLSerializers.tsx
- content/webapp/pages/stories.tsx
- content/webapp/pages/whats-on.tsx
Continuing to chip away at #7302 and #6927
> Convert html-serializers to TypeScript; move it into the content app

- content/webapp/pages/homepage.tsx
- content/webapp/pages/stories.tsx
For https://github.com/wellcomecollection/wellcomecollection.org/pull/7564/files/79548135faf2d3d2d669fafd983f09402c89e332#r786094167
> Use relative paths to be consistent with the rest of the code

- content/webapp/pages/articles.tsx
> Use fetch/transform for articles page

- content/webapp/content/static-books.ts
Per Helen's request in Slack: https://wellcome.slack.com/archives/C8X9YKM5X/p1642499094008100
> Update the featured books on the Stories landing page

- content/webapp/services/prismic/fetch/articles.ts
> Add the orderings and graphQuery used in getArticles to fetchArticles

- playwright/test/articles.test.ts
> Fix the titles used in the e2e tests for related stories

- catalogue/webapp/components/ItemRequestModal/ItemRequestModal.tsx
- playwright/test/request-items.test.ts
For item (5) on https://github.com/wellcomecollection/wellcomecollection.org/issues/7261
> Change "items remaining" to "items requested"

- cache/modules/cloudfront_policies/response_policies.tf
As per https://github.com/wellcomecollection/wellcomecollection.org/issues/7348
> Bump HSTS max-age to 1 month

- common/services/prismic/pages.js
- content/webapp/pages/stories.tsx
- content/webapp/pages/whats-on.tsx
- content/webapp/services/prismic/transformers/pages.ts
For https://github.com/wellcomecollection/wellcomecollection.org/issues/6927 and https://github.com/wellcomecollection/wellcomecollection.org/issues/7302
> Convert getPageFeaturedText to TypeScript; move it into the content app

- content/webapp/pages/article.tsx
- playwright/test/articles.test.ts
People who want an appropriate piece of related content on a story
Reinstating the behaviour we wanted, but must have been without for some time
If we're reading a serial (i.e. a series with a schedule), the related content at the end of it will be the next part (or the first part if the one we're reading is the final part).
> Article siblings

- common/data/microcopy.ts
Made accurate list of what's open, added acute e to cafe
visitors who wish to know what's open
providing accurate information
> Updated homepage description

- .buildkite/expected_404_urls.txt
- common/data/microcopy.ts
- common/services/prismic/hardcoded-id.ts
- content/webapp/components/CardGrid/DailyTourPromo.tsx
- content/webapp/components/ContentPage/ContentPage.tsx
- content/webapp/services/prismic/fetch/books.ts
- content/webapp/services/prismic/fetch/index.ts
I'm still banging my head against https://github.com/wellcomecollection/wellcomecollection.org/issues/7363; in the meantime these nice things fell out.
> Continue to clean up various small things

- prismic-model/src/exhibitions.ts
> Update exhibitions model

- catalogue/webapp/components/ItemRequestModal/ItemRequestModal.tsx
- catalogue/webapp/test/components/ItemRequestModal.test.tsx
- catalogue/webapp/test/utils/dates.test.ts
- common/test/fixtures/prismicData/prismic-data.ts
Fixes #7456
- adds tests for the ItemRequestModal component, based on the success criteria in #7266
> Day picker tests

- content/webapp/pages/stories.tsx
- playwright/test/stories.test.ts
I broke this in https://github.com/wellcomecollection/wellcomecollection.org/pull/7625, and we don't have a test for it. That article-series stuff is tricksy!
Now we have a fix and a test. ✨
> Fix the cards for the featured serial on /stories

- content/webapp/data/static-books.ts
> Update static books for stories page

- common/services/prismic/parsers.js
- common/test/services/prismic/parsers.test.ts
Danny.
Making his YouTube embeds be less Tory.
https://wellcome.slack.com/archives/C8X9YKM5X/p1645025721218349
> Fix YouTube embeds when there's already a query param in the URL

- common/model/exhibitions.js
- common/services/prismic/articles.js
- common/services/prismic/events.js
- common/services/prismic/exhibitions.js
- content/webapp/components/CardGrid/CardGrid.test.tsx
- content/webapp/services/prismic/transformers/articles.ts
- content/webapp/services/prismic/transformers/events.ts
- content/webapp/services/prismic/transformers/exhibitions.ts
- content/webapp/services/prismic/transformers/pages.ts
- content/webapp/services/prismic/types/exhibitions.ts
For https://github.com/wellcomecollection/wellcomecollection.org/issues/7363; follows #7656.
A couple more functions inlined and converted to TypeScript. Mostly these are copied directly from the JavaScript versions and with minimal tweaks to make them compile; I'll leave comments for more substantial changes.
> Use more TypeScript for transformers

- content/webapp/services/prismic/transformers/events.ts
- content/webapp/services/prismic/transformers/index.ts
- content/webapp/services/prismic/types/index.ts
This fixes three of the pages that are currently alerting, because I made a mistake while refactoring for https://github.com/wellcomecollection/wellcomecollection.org/issues/7363
> Various fixes for the broken front-end pages

- prismic-model/src/events.ts
Part of #7639 
Changing the `events` type to allow for multiple places per event
> Add locations group to events type

- content/webapp/services/prismic/transformers/events.ts
- content/webapp/services/prismic/types/events.ts
> Add parsed locations (places) to events

- content/webapp/services/prismic/transformers/events.ts
This fixes the broken page on staging: https://www-stage.wellcomecollection.org/articles/W_LXOxcAACwAxC5_
> Handle the case where 'data.locations' is undefined

- cache/modules/cloudfront_policies/response_policies.tf
Final bit of https://github.com/wellcomecollection/wellcomecollection.org/issues/7348
> Bump the HSTS max-age to 2 years

- common/services/prismic/events.js
- common/services/prismic/parsers.js
- common/services/prismic/types.js
- common/services/prismic/types.ts
- common/views/components/Table/Table.tsx
- content/webapp/services/prismic/fetch/guides.ts
- content/webapp/services/prismic/transformers/body.ts
- content/webapp/services/prismic/transformers/events.ts
- content/webapp/services/prismic/transformers/exhibitions.ts
- content/webapp/services/prismic/transformers/index.ts
- content/webapp/services/prismic/transformers/places.ts
- content/webapp/services/prismic/types/body.ts
- content/webapp/services/prismic/types/places.ts
I tried deleting all the parsing code in one go, and then I was back to this mysterious old error:
```
../../node_modules/prismic-client-beta/dist/index.mjs
Attempted import error: 'asLink' is not exported from '@prismicio/helpers' (imported as 'prismicH').
```
So instead, here's just a bit more of the Prismic code flipped over. 🎉
> Keep converting more transformer code to TS

- common/services/prismic/events.js
- common/services/prismic/exhibitions.js
- common/services/prismic/parsers.js
- common/views/components/Contact/Contact.tsx
- content/webapp/components/Body/Body.tsx
- content/webapp/components/ImageGallery/ImageGallery.tsx
- content/webapp/services/prismic/transformers/body.test.ts
- content/webapp/services/prismic/transformers/body.ts
- content/webapp/services/prismic/transformers/events.test.ts
- content/webapp/services/prismic/transformers/events.ts
- content/webapp/services/prismic/transformers/images.ts
- content/webapp/services/prismic/transformers/index.ts
- content/webapp/services/prismic/types/body.ts
- content/webapp/services/prismic/types/teams.ts
I'm also gradually tidying up the transformBody method per Jamie's suggestion.
> Yet more transformers into TypeScript

- content/webapp/services/prismic/transformers/events.ts
- content/webapp/services/prismic/transformers/exhibitions.ts
> Fix place transformation on events/exhibitions

- common/services/prismic/parsers.js
- common/views/components/DeprecatedImageList/DeprecatedImageList.tsx
- content/webapp/services/prismic/transformers/body.test.ts
- content/webapp/services/prismic/transformers/body.ts
- content/webapp/services/prismic/transformers/books.ts
- content/webapp/services/prismic/transformers/exhibitions.ts
- content/webapp/services/prismic/transformers/images.ts
- content/webapp/services/prismic/transformers/index.ts
- content/webapp/services/prismic/types/body.ts
- content/webapp/services/prismic/types/index.ts
I've run this through the local test harness from #7687 and checked all the pages work.
> Tuesday lunchtime TypeScript transformers

- content/webapp/services/prismic/transformers/card.ts
> use transformImage

- content/webapp/services/prismic/types/index.ts
This fixes a broken page here: https://www-stage.wellcomecollection.org/articles/W9m2QxcAAF8AFvE5
> Remember to check for undefined-ness in this function

- content/webapp/services/prismic/fetch/events.ts
- content/webapp/services/prismic/transformers/events.ts
> Stop 500ing

- content/webapp/services/prismic/transformers/body.ts
- content/webapp/services/prismic/types/body.ts
- content/webapp/services/prismic/types/index.ts
People who want to see the gifVideo component on stories: https://wellcome.slack.com/archives/C8X9YKM5X/p1645693022212509
and wants them to auto play
> Gif video bug

- content/webapp/services/prismic/transformers/events.ts
- content/webapp/services/prismic/types/articles.ts
- content/webapp/services/prismic/types/events.ts
> Tidy up from the hotfix for today's 500 error

- common/services/prismic/opening-times.ts
- common/test/services/prismic/opening-times.test.ts
Relates to #7547
Adding some more tests
> Opening times tests

- common/services/prismic/parsers.js
- content/webapp/services/prismic/transformers/body.ts
- content/webapp/services/prismic/transformers/exhibitions.ts
- content/webapp/services/prismic/transformers/images.ts
- content/webapp/services/prismic/transformers/index.ts
- content/webapp/types/contributors.ts
For https://github.com/wellcomecollection/wellcomecollection.org/issues/7363, follows #7110. Another fairly small change.
> Flip a few more functions from parsers.js into TypeScript

- assets/humans.txt
I've also combined the access/collections teams here as while the divide of work is clear, the divide of people is not (and is liable to change)
> Add Mel to humans.txt

- identity/webapp/pages/validated.tsx
This is the 3rd attempt to do this after the initial implementation, https://github.com/wellcomecollection/wellcomecollection.org/pull/7624 and https://github.com/wellcomecollection/wellcomecollection.org/pull/7631. I've tested it locally, but I'd tested the others too - so we'll see what happens 🙃
> Post-verification session refresh

- .buildkite/pipeline.yml
- content/webapp/__mocks__/whats-on.ts
- content/webapp/components/CardGrid/CardGrid.test.tsx
- content/webapp/components/CardGrid/CardGrid.tsx
- content/webapp/components/Contributors/Contributors.test.tsx
- content/webapp/components/Contributors/Contributors.tsx
- content/webapp/package.json
- content/webapp/services/prismic/transformers/body.test.ts
- content/webapp/services/prismic/transformers/events.test.ts
- content/webapp/services/prismic/types/link-resolver.test.ts
- content/webapp/test/services/prismic/transformers/contributors.test.ts
> Make sure the content tests run and pass in CI

- content/webapp/pages/api/exhibitions-related-content/index.ts
- content/webapp/services/prismic/fetch/exhibitions.ts
This will fix the string of 500 errors currently dropping in Slack. 🙈
> Make sure we fetch related content on exhibitions correctly

- common/data/microcopy.ts
- common/views/components/ErrorPage/ErrorPage.tsx
Making it easier for them to customise the top-level messages.
> Allow content team to set error microcopy

- content/webapp/components/EventSchedule/EventSchedule.tsx
- content/webapp/components/Exhibition/Exhibition.tsx
- content/webapp/pages/event-series.tsx
- content/webapp/pages/event.tsx
- content/webapp/pages/events.tsx
- content/webapp/pages/homepage.tsx
- content/webapp/pages/season.tsx
- content/webapp/pages/whats-on.tsx
- content/webapp/services/prismic/events.ts
- content/webapp/services/prismic/fetch/events.ts
- content/webapp/services/prismic/fetch/multi-content.ts
- content/webapp/services/prismic/transformers/events.ts
- content/webapp/services/prismic/transformers/exhibitions.ts
Fixes Nic's issue here: https://wellcome.slack.com/archives/C8X9YKM5X/p1646171091804779
> Fix the handling of dates which are fetched client-side

- catalogue/webapp/components/ItemRequestModal/ItemRequestModal.tsx
- catalogue/webapp/components/RequestingDayPicker/RequestingDayPicker.tsx
references #7458
sends neededBy as part of body in hold request
> Add date to item request

- common/model/requesting.ts
- identity/webapp/pages/index.tsx
Fixes #7459
Finishes this work off, so that we display an actual pickup date if there is one (and the enablePickUpDate toggle is on)
> use real pickupDate if there is one

- common/views/components/Iframe/Iframe.tsx
- common/views/components/InfoBlock/InfoBlock.tsx
- common/views/components/Quote/Quote.tsx
- content/webapp/services/prismic/transformers/body.ts
- content/webapp/services/prismic/transformers/index.ts
- content/webapp/services/prismic/types/body.ts
For https://github.com/wellcomecollection/wellcomecollection.org/issues/7753
> Continue to tidy up some body transformers

- content/webapp/components/Contributors/Contributors.test.tsx
> Remove unused arguments from dedupeAndPluraliseRoles

- content/webapp/services/prismic/transformers/events.ts
> Add return type to getLastEndTime

- common/utils/domain.ts
- common/views/components/BaseTabs/BaseTabs.tsx
- common/views/components/styled/CssGridContainer.tsx
- content/webapp/components/StoryPromo/StoryPromo.tsx
- content/webapp/pages/event-series.tsx
- content/webapp/pages/homepage.tsx
Implementing suggestions from #7738
> Post lint nits

- catalogue/webapp/pages/download.tsx
- catalogue/webapp/pages/image.tsx
- catalogue/webapp/pages/item.tsx
- catalogue/webapp/pages/progress.tsx
- catalogue/webapp/pages/works.tsx
- common/data/microcopy.ts
- common/utils/dates.test.ts
- common/utils/dates.ts
- common/utils/format-date.ts
- content/webapp/components/EventSchedule/EventScheduleItem.tsx
- content/webapp/pages/event.tsx
- content/webapp/services/prismic/transformers/events.test.ts
- content/webapp/services/prismic/transformers/events.ts
Moment is one of the biggest dependencies in our current bundle; this gets rid of a few unnecessary uses of it. I don't think it'll make a meaningful difference to bundle size yet, but it starts to loosen its tendrils in our codebase.
> Bin a couple of unnecessary calls to london(…)

- prismic-model/README.md
> add some detail about updating Prismic models/rolling back

- common/views/components/HeaderBackground/HeaderBackground.tsx
- content/webapp/pages/event.tsx
- content/webapp/pages/newsletter.tsx
> Pull in background texture URLs as named variables, not strings

- catalogue/webapp/components/ItemRequestModal/ItemRequestModal.tsx
> Prevent 'cancel' button submitting request

- content/webapp/services/prismic/transformers/events.ts
☝️ 
Fixes [this](https://wellcome.slack.com/archives/C8X9YKM5X/p1646840809317689)
> Don't spread string

- content/webapp/services/prismic/events.ts
- content/webapp/services/prismic/transformers/exhibitions.ts
> Use vanilla JavaScript Date objects for comparisons, rather than Moment

- catalogue/webapp/components/WorkDetails/WorkDetails.tsx
- common/views/components/ModalMoreFilters/ModalMoreFilters.tsx
> Series snagging

- catalogue/webapp/pages/item.tsx
Shut up alerting while https://github.com/wellcomecollection/platform/issues/5443 is being sorted
> Don't 500 for missing manifests

- common/views/components/DateRange/DateRange.tsx
- content/webapp/components/EventsByMonth/EventsByMonth.tsx
Developers.
One of my background projects is to see if we can reduce (or remove!) our dependency on Moment, which is quite a large part of our bundle.
For date comparison logic, we definitely don't need it. This patch has a couple of small improvements to the readability of the parts I want to change, so that when I come in and de-Moment this code the change will be fairly slight.
> Tidy up some of the date-handling logic

- common/services/prismic/transformers/collection-venues.ts
- common/utils/dates.ts
- common/utils/format-date.test.ts
- common/utils/format-date.ts
- content/webapp/pages/event.tsx
- content/webapp/services/prismic/events.ts
- content/webapp/types/events.ts
This salvages the useful bits from #7835, without the new dependency and expanded bundle size.
> Tidy up a couple of date-related things

- catalogue/webapp/components/VisuallySimilarImagesFromApi/VisuallySimilarImagesFromApi.tsx
- common/test/fixtures/components/compact-card.ts
- common/views/components/Image/Image.tsx
- content/webapp/components/CardGrid/DailyTourPromo.tsx
- content/webapp/components/CompactCard/CompactCard.test.tsx
- content/webapp/components/MediaObject/MediaObject.test.tsx
- content/webapp/components/MediaObjectBase/MediaObjectBase.test.tsx
- content/webapp/pages/events.tsx
Stuff I spotted while experimenting in #7838 that should go in easily.
> A couple of miscellaneous code tidies

- cardigan/stories/components/SeasonsHeader/SeasonsHeader.stories.tsx
- cardigan/stories/content.ts
- common/test/fixtures/components/cafe-venue.ts
- common/test/fixtures/components/galleries-venue.ts
- common/test/fixtures/components/library-venue.ts
- content/webapp/__mocks__/whats-on.ts
- content/webapp/pages/page.tsx
This fixes the failing test we're seeing in main (https://buildkite.com/wellcomecollection/experience-deployment/builds/797#f8266a36-8be1-4f22-8683-5a95243bfb95), and deletes _even more code_.
> Fix a broken page by removing a bunch of old crop fields

- content/webapp/services/prismic/transformers/series.ts
> Don't cast to Moment unnecessarily on series

- common/data/microcopy.ts
- identity/webapp/pages/api/auth/[...auth0].ts
- identity/webapp/pages/error.tsx
- identity/webapp/src/frontend/components/CustomError.tsx
Related to #7580 
[See comment on the issue for context](https://github.com/wellcomecollection/wellcomecollection.org/issues/7580#issuecomment-1080509027)
> Customise auth0 handleAuth callback

- catalogue/webapp/components/ItemRequestModal/RequestDialog.tsx
> Don't send pickup date if toggle is not enabled

- catalogue/webapp/components/ItemRequestModal/ItemRequestModal.tsx
Following on from https://github.com/wellcomecollection/catalogue-api/pull/369
> Rename neededBy -> pickupDate

- common/views/components/VideoEmbed/VideoEmbed.tsx
- content/webapp/components/SearchResults/SearchResults.tsx
- content/webapp/services/prismic/transformers/body.test.ts
- content/webapp/services/prismic/transformers/body.ts
- content/webapp/services/prismic/transformers/index.ts
- content/webapp/services/prismic/types/body.ts
- content/webapp/types/multi-content.ts
For https://github.com/wellcomecollection/wellcomecollection.org/issues/7753
The Body types are a bit of a mess and will need a more radical rethink.
> Continue tidying up the body transformers

- cardigan/stories/components/TagsGroup/TagsGroup.stories.tsx
- common/icons/components/SoundCloud.tsx
- common/icons/index.ts
- common/views/components/Footer/FooterSocial.tsx
> Fix the capitalisation of "SoundCloud" in the footer

- catalogue/webapp/pages/item.tsx
Reverts wellcomecollection/wellcomecollection.org#7827
Resolves https://github.com/wellcomecollection/platform/issues/5443
> Revert "Don't 500 for missing manifests"

- cache/edge_lambdas/src/toggler.ts
- common/views/pages/_app.tsx
- toggles/webapp/toggles.ts
> Promote everyone to secure ga cookies

- common/services/prismic/hardcoded-id.ts
Ben.
Putting a new series on the homepage. See https://wellcome.slack.com/archives/C8X9YKM5X/p1650385122387729
> Update the featured stories ID to "Apocalypse How?"

- catalogue/webapp/components/Calendar/Calendar.tsx
- catalogue/webapp/package.json
- catalogue/webapp/test/components/Calendar.test.tsx
- catalogue/webapp/test/components/ItemRequestModal.test.tsx
- identity/webapp/package.json
- yarn.lock
Relates to #7756
Adds some tests for the Calendar component and how it is used for selecting a date in ItemRequestModal
> More request tests

- playwright/test/selectors/search.ts
- playwright/test/text/aria-labels.ts
Now we’re using the Modal component rather than a bespoke implementation for the filters on mobile we need to change the selector for the close button
> Fixes mobile images.test

- catalogue/webapp/components/Work/Work.tsx
> Add hotjar to archive pages

- catalogue/webapp/components/Calendar/Calendar.tsx
- catalogue/webapp/components/Calendar/CalendarStyles.tsx
- catalogue/webapp/components/ItemRequestModal/RequestDialog.tsx
- catalogue/webapp/components/ItemRequestModal/common.tsx
- catalogue/webapp/test/components/ItemRequestModal.test.tsx
- common/data/microcopy.ts
References #7756 
Improving accessibility:
- provides keyboard users with instructions on how to navigate the calendar
- prevents keyboard users from picking an unavailable date
- notifies keyboard and screen reader users if they try to select an unavailable date
- notifies keyboard and screen reader users if they try to navigate outside of the available date range
- makes some of the language less verbose, so it is easier to understand
> Datepicker accessibility improvements

- catalogue/webapp/components/Calendar/Calendar.tsx
⬆️ 
Makes screens readers read out the day as well as the date when navigating the Calendar
> add day to aria label as it is useful information

- identity/webapp/pages/registration.tsx
We don't need this. It had been taken out already but has crept back in as the result of a merge when I was splitting everything up.
> Don't deal with redirectUri

- common/views/components/PageLayout/PageLayout.tsx
> Update hotjar tracking urls

- common/utils/dates.ts
⬆️ 
Is causing the bug described here: https://wellcome.slack.com/archives/C8X9YKM5X/p1650973496628519
> make sure isDayPast returns what we expect

- identity/webapp/pages/api/registration.ts
- identity/webapp/pages/registration.tsx
Redirecting users to an error page if something doesn't work, and logging the error.
> Registration api updates

- common/utils/dates.ts
- content/webapp/components/EventPromo/EventPromo.tsx
- content/webapp/pages/event.tsx
- content/webapp/services/prismic/events.test.ts
- content/webapp/services/prismic/events.ts
- content/webapp/types/events.ts
Relates to #7928
- I believe the isDayPast function _is_ doing what it's meant to now, as it behaves the same way as [the function it replaced](https://github.com/wellcomecollection/wellcomecollection.org/commit/7ad8e9726e0e770f834a4a70932748344ca13886#diff-fbdf0bc0afc5fe29004a01730ffe0c73da3765dafa942ce142b2625a8c818869L36), so have removed the outdated comment
- I've tweaked the isEventFullyBooked function, so it now only returns true if upcoming dates are fully booked, and not if all dates are past (and renamed the function to upcomingDatesFullyBooked)
- removed isPast checks where we call upcomingDatesFullyBooked, as they are no longer needed
- added some test for upcomingDatesFullyBooked
The one thing I'm not sure of is if we need the isDayPast function at all, as far as I can see we …
> Is day past and related stuff

- catalogue/webapp/components/RequestingDayPicker/RequestingDayPicker.tsx
⬆️ 
relates to #7756
save some Kb for people who don't use it
> use dynamic import for calendar component

- catalogue/webapp/pages/images.tsx
Not sure why this behaviour was different to works
> Allow image searches without a query

- catalogue/webapp/components/Work/Work.tsx
> Add comment about removing hotjar when we can

- identity/webapp/pages/api/registration.ts
Part of #7808 
Companion to https://github.com/wellcomecollection/identity/pull/293
> Make put request to (to be created) identity backend endpoint

- common/views/components/Tasl/Tasl.tsx
Part of https://github.com/wellcomecollection/wellcomecollection.org/issues/7951
The type checker.
Being more explicit.
> Add some missing types in the Tasl component

- common/server-data/index.ts
Devs.
Making it easier to work out where 500 errors are coming from. 
For https://github.com/wellcomecollection/wellcomecollection.org/issues/7954
> Add a warning log for null values in the server data

- common/views/components/ApiToolbar/ApiToolbar.tsx
People who like the API toolbar to tell the truth
Fixing it
> Fix stale API toolbar data

- cardigan/stories/components/Calendar/Calendar.stories.tsx
- catalogue/webapp/components/Calendar/CalendarSelect.tsx
- catalogue/webapp/components/ItemRequestModal/RequestDialog.tsx
- catalogue/webapp/components/RequestingDayPicker/RequestingDayPicker.tsx
- catalogue/webapp/test/components/ItemRequestModal.test.tsx
- common/utils/array.ts
- common/views/components/Select/Select.tsx
- common/views/components/SelectContainer/SelectContainer.tsx
Using a `<select>` for the pick-up date functionality in order to bypass the need for an in-depth accessibility test.
> Date select

- catalogue/webapp/components/Calendar/CalendarSelect.tsx
- catalogue/webapp/components/ItemRequestModal/RequestDialog.tsx
- catalogue/webapp/test/components/ItemRequestModal.test.tsx
People who want requests to work
Formatting the date correctly so that the request can be confirmed
> Use the correct date format

- cardigan/stories/components/Cards/Cards.stories.tsx
- cardigan/stories/components/PageHeader/PageHeader.stories.tsx
- cardigan/stories/components/SeasonsHeader/SeasonsHeader.stories.tsx
- cardigan/stories/components/WobblyBottom/WobblyBottom.stories.tsx
- common/views/components/Iframe/Iframe.tsx
- common/views/components/PageHeader/PageHeader.tsx
- content/webapp/components/Card/Card.tsx
- content/webapp/components/EventPromo/EventPromo.tsx
- content/webapp/components/ExhibitionPromo/ExhibitionPromo.tsx
- content/webapp/components/FacilityPromo/FacilityPromo.tsx
- content/webapp/components/FeaturedCard/FeaturedCard.tsx
- content/webapp/components/SeasonsHeader/SeasonsHeader.tsx
- content/webapp/components/SimpleCardGrid/SimpleCardGrid.tsx
- content/webapp/components/VenueHours/VenueHours.tsx
- content/webapp/pages/page.tsx
- content/webapp/pages/season.tsx
- content/webapp/utils/page-header.tsx
Relates to #7932 and #7962
Using the PrismicImage component instead of the UiImage component
> replacing UiImage with PrismicImage

- common/test/utils/convert-image-uri.test.ts
- common/utils/convert-image-uri.ts
- common/utils/json-ld.ts
- common/views/components/Image/Image.tsx
- common/views/components/JsonLd/JsonLd.tsx
- common/views/components/PageLayout/PageLayout.tsx
- common/views/components/Picture/Picture.tsx
- content/webapp/components/BannerCard/BannerCard.tsx
Reverts wellcomecollection/wellcomecollection.org#7987
> Revert "Tidy up the convert-image-uri helper"

- common/services/prismic/hardcoded-id.ts
> Update the featured stories ID to "The Roots of a Scientist"

- common/views/themes/inter-typography.ts
> Font size tweaks

- catalogue/webapp/components/ArchiveTree/ArchiveTree.tsx
> Add ga events to  ArchiveTree chevron/link clicks

- common/views/components/SelectContainer/SelectContainer.tsx
Doing what the TODO says to do
> Remove Helvetica Select hack

- content/webapp/pages/collections.tsx
> Remove some logs we don't need

- common/views/components/ButtonInline/ButtonInline.tsx
> Equal top/bottom ButtonInline padding for Inter

- .buildkite/expected_200_urls.txt
- content/webapp/app.ts
People looking at the links on https://wellcomecollection.org/youth
Making them be less mysterious.
> Use case-sensitive routing to fix the RawMinds page

- cache/modules/wc_org_cloudfront/distribution.tf
- cache/modules/wc_org_cloudfront/waf.tf
> Put some rate-limiting in front of wellcomecollection.org

- cache/modules/wc_org_cloudfront/waf.tf
> Improve specificity of WAF rules

- common/views/components/FindUs/FindUs.tsx
- common/views/components/Footer/Footer.tsx
- common/views/components/Layout10/Layout10.tsx
- common/views/components/PageHeader/PageHeader.tsx
- content/webapp/components/Body/VisitUsStaticContent.tsx
- content/webapp/components/SimpleCardGrid/SimpleCardGrid.tsx
- content/webapp/pages/homepage.tsx
- content/webapp/pages/whats-on.tsx
Part of #8041 
Addressing issues in [these Zeplin screens](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/6294cb459ed99b11b4e00e30)
> Spacing amends

- common/views/components/PageLayout/PageLayout.tsx
☝️ 
Tracking was required for #7810 which is now complete
> Turn off hotjar on learning resource pages

- common/model/organization.ts
- common/views/components/FindUs/FindUs.tsx
> Move hard-coded org data to dedicated microcopy

- assets/deploy_assets.sh
- assets/googlea25c86e91ccc343b.html
- cache/modules/wc_org_cloudfront/distribution.tf
Tacey.
Helping her get into Google Search Console: https://wellcome.slack.com/archives/C3TQSF63C/p1655464291878209
> Add proof that we own our domain for Google Search Console

- cache/.terraform.lock.hcl
- cache/s3_lambdas.tf
For https://github.com/wellcomecollection/platform/issues/5557
> Replace a template_file resource with the templatefile function

- identity/webapp/pages/registration.tsx
> Add sanity check logs and prevent redirect if there isn't a valid token

- catalogue/webapp/package.json
- common/package.json
- common/views/pages/_app.tsx
- common/views/themes/utility-classes.ts
- yarn.lock
> Remove lazy sizes

- identity/webapp/src/frontend/Registration/RegistrationInformation.tsx
Based on https://github.com/wellcomecollection/wellcomecollection.org/issues/7814
> Remove text from the top of the "apply for a membership" page

- common/views/components/AudioPlayer/AudioPlayer.tsx
Part of #8110
@taceybadgerbrook 
Adding tracking to the play/pause, mute/unmute and play-rate buttons.
We opted to re-use the `Audio` category we've already created in GA, and extend it with new `action`s.
Also added an `idPrefix` prop to the AudioPlayer in order to help distinguish between e.g. audio on works pages and audio guides when reporting.
__Actions__
1. `action: "set speed to ${speed}x"` (where speed is one of `0.5`, `1`, `1.5` and `2`)
2. `action: "mute audio"`,
3. `action: "unmute audio"`
4. `action: "play audio"` (already exists)
5. `action: "pause audio"`
__TODO__ (separate PR):
~Track how much of each piece of audio was played.~
> Add some tracking to the AudioPlayer

- common/services/prismic/hardcoded-id.ts
> Make Hoard the featured serial

- prismic-model/src/parts/article-body.ts
Extension of #8148 – required for the new AudioPlayer
> Add audioPlayer slice to article-body

- common/views/components/AudioPlayer/AudioPlayer.tsx
- content/webapp/components/Body/Body.tsx
- content/webapp/services/prismic/transformers/body.ts
- content/webapp/services/prismic/types/body.ts
- content/webapp/types/body.ts
> Render audio player

- common/views/themes/config.ts
- content/webapp/components/Card/Card.tsx
> Make cards have a min height

- identity/webapp/pages/success.tsx
> Tweak application success page copy

- prismic-model/lintPrismicData.ts
- prismic-model/package.json
This is a very quick first pass at https://github.com/wellcomecollection/wellcomecollection.org/issues/7730, because I noticed we have a bad URL in a post publishing tomorrow.
> Add a script for running linting rules against Prismic

- cache/edge_lambdas.tf
- cache/edge_lambdas/src/redirector.test.ts
- cache/edge_lambdas/src/redirector.ts
- cache/edge_lambdas/yarn.lock
e.g. when somebody hits `www-stage.wc.org/signup`, they should be redirected to the sign-up page on staging, not prod
> Preserve the domain in redirects

- identity/webapp/pages/validated.tsx
Based on Dom's updated text in https://github.com/wellcomecollection/wellcomecollection.org/issues/8178
> Update email verification copy

- content/webapp/components/SeriesNavigation/SeriesNavigation.tsx
> Pad read more button away from white/cream border

- common/views/components/PageHeader/PageHeader.tsx
> Re-add some space below breadcrumbs

- identity/webapp/copy.tsx
For https://github.com/wellcomecollection/wellcomecollection.org/issues/8160 and https://github.com/wellcomecollection/wellcomecollection.org/issues/8178
> More markups to the user-facing sign-up copy

- cardigan/stories/components/ExhibitionCaptions/ExhibitionCaptions.stories.mdx
- cardigan/stories/components/ExhibitionCaptions/ExhibitionCaptions.stories.tsx
- content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx
- content/webapp/components/ExhibitionCaptions/README.md
> Start ExhibitionCaptions component

- content/webapp/components/DateAndStatusIndicator/DateAndStatusIndicator.tsx
- content/webapp/components/FeaturedText/FeaturedText.tsx
- content/webapp/routeHandlers/handleNewsletterSignup.ts
Fixing some warnings from VS Code.
> Add a couple of missing type annotations

- playwright/test/landing-pages.test.ts
> Modify landing page tests to wait for content

- catalogue/webapp/components/ItemRequestModal/RequestDialog.tsx
- catalogue/webapp/test/utils/dates.test.ts
- catalogue/webapp/utils/dates.ts
> Make the next available pick-up date the next open day plus one

- cache/send_slack_alert_for_5xx_errors.js
People in the platform-alerts channel.
Hiding errors we don't care about.
> Dont alert on known 500

- catalogue/webapp/components/ItemRequestModal/ConfirmedDialog.tsx
- catalogue/webapp/components/ItemRequestModal/RequestDialog.tsx
- catalogue/webapp/test/components/ItemRequestModal.test.tsx
- content/webapp/components/EventPromo/EventPromo.test.tsx
- identity/webapp/pages/index.tsx
- toggles/webapp/toggles.ts
> Remove enablePickUpDate toggle

- assets/humans.txt
Hannah has checked that Raphaëlle is happy to be credited here.
> Add Raphaëlle 🎉

- content/webapp/components/EventSchedule/EventScheduleItem.tsx
- content/webapp/components/VenueClosedPeriods/VenueClosedPeriods.tsx
See https://wellcome.slack.com/archives/C8X9YKM5X/p1659954374729619
e.g. https://wellcomecollection.org/events/W5fKOiYAACYAMt8T
> Don't show "booking opens / just turn up" for past events

- .buildkite/pipeline.yml
- docker-compose.yml
Workflow/devs, action based off [incident with date-picker](https://github.com/wellcomecollection/docs/blob/main/incident_retros/2022-08-09_date-picker.md)
[How to run command manually](https://github.com/wellcomecollection/wellcomecollection.org/tree/main/toggles#deployment)
> Remove toggle deploy

- README.md
☝️ 
This was a polite request, and seems only fair.
> Thank Chromatic for giving us open-source privileges

- prismic-model/src/exhibition-guides.ts
- prismic-model/src/parts/number.ts
> Reorder exhibition guide fields with more field descriptions

- catalogue/webapp/pages/images.tsx
- catalogue/webapp/pages/works.tsx
- catalogue/webapp/services/catalogue/images.ts
🙈 
Closes https://github.com/wellcomecollection/platform/issues/5593
> Return 25 images per page in search results

- prismic-model/src/exhibition-guides.ts
Implements [the changes discussed](https://github.com/wellcomecollection/wellcomecollection.org/issues/8292#issuecomment-1223943357)
> add fields to exhibition-guides model

- prismic-model/src/exhibition-guides.ts
> exhibition model update

- catalogue/webapp/hooks/useScrollVelocity.ts
- catalogue/webapp/test/components/ItemRequestModal.test.tsx
- common/data/hardcoded-ids.ts
- common/hooks/useValidation.ts
- common/server-data/__mocks__/index.ts
- common/services/catalogue/routes.ts
- common/services/prismic/transformers/collection-venues.ts
- common/views/components/Footer/FooterSocial.tsx
- common/views/components/Footer/FooterWellcomeLogo.tsx
- common/views/components/Iframe/Iframe.tsx
- common/views/components/LoadingIndicator/LoadingIndicator.tsx
- common/views/components/Message/Message.tsx
- common/views/components/PrismicHtmlBlock/PrismicHtmlBlock.tsx
- common/views/components/PrismicImage/PrismicImage.tsx
- content/webapp/components/Body/Body.tsx
- content/webapp/components/Body/GridFactory.tsx
- content/webapp/components/CardGrid/DailyTourPromo.tsx
- content/webapp/components/EventDateRange/EventDateRange.tsx
- content/webapp/components/EventSchedule/EventBookingButton.tsx
- content/webapp/components/GifVideo/GifVideo.tsx
- content/webapp/components/SearchResults/AsyncSearchResults.tsx
- dash/webapp/pages/index.tsx
- identity/webapp/src/frontend/Registration/useRegisterUser.ts
- identity/webapp/src/frontend/hooks/useRequestDelete.ts
- identity/webapp/src/frontend/hooks/useUpdatePassword.ts
- identity/webapp/src/frontend/hooks/useUpdateUser.ts
- package.json
- playwright/test/works-search.test.ts
Follows https://github.com/wellcomecollection/wellcomecollection.org/pull/8324
Before:
```console
$ yarn run eslint --fix --max-warnings=0 .
✖ 190 problems (10 errors, 180 warnings)
```
After:
```console
$ yarn run eslint --fix --max-warnings=0 .
✖ 165 problems (9 errors, 156 warnings)
```
> Fix a bunch more warnings from eslint

- playwright/test/selectors/images.ts
[Fixes the failing test discussed in Slack](https://wellcome.slack.com/archives/CUA669WHH/p1661510580619449)  by filtering by a different colour. The first result will then have visually similar images
> Fixes the e2e tests

- common/data/microcopy.ts
> update wording for disabled requesting message

- common/data/microcopy.ts
Library users 
Updating to copy provided by LE&E
> update microcopy for requesting

- catalogue/webapp/hooks/useIIIFManifestData.ts
☝️ 
There are changes from #7637 that appear to have been deployed, but we're not seeing the network requests we expect. Adding a log for sanity check.
> Log iiifManifest and iiifManifestV3 to see if it gets to stage

- .buildkite/pipeline.deployment.yml
For https://github.com/wellcomecollection/platform/issues/5597
> Bump to weco-deploy 5.7

- prismic-model/downloadSnapshot.ts
Devs.
Making it easier to see how long a snapshot download will take – I was showing it to Raphaëlle, and seeing it count up:
```
Downloading page 1...
Downloading page 2...
Downloading page 3...
```
isn't helpful in knowing how long it will take!
> Add a progress bar for Prismic snapshot downloads

- cardigan/stories/components/TabNav/TabNav.stories.tsx
- catalogue/webapp/components/WorksSearchResults/WorksSearchResultsV2.tsx
- catalogue/webapp/pages/concept.tsx
- common/views/themes/config.ts
For us, anyone who wants to access a Concept page with new Colours toggle activated
Fixes the merge issue where a colour wasn't found. Also fixes a typo in a class name.
> Remove newPalette yellow and just use yellow. Fix class name

- catalogue/webapp/pages/concept.tsx
People working on Concept pages
A few styles needed to be changed to match the new palette, and I've also learned more about the classes I could use for styling, so removed custom styles.
> Align Concepts styles with all the changes of the last month

- catalogue/webapp/pages/concept.tsx
- common/views/components/TabNav/TabNavV2.tsx
Mostly me at this point, but anyone who'll work on tweaking those pages.
More work done on making it easily readable, re-animate TabNav's selected status.
I'll stop the small PRs after this, but want it to be better than it currently is for next week..!
> More tweaks to concept page

- content/webapp/components/EventsByMonth/group-event-utils.ts
- content/webapp/package.json
Me.
Assuaging my guilt over the +15kB bundle addition in https://github.com/wellcomecollection/wellcomecollection.org/pull/8378
> Remove the lodash.sortBy dependency in the content app

- content/webapp/pages/book.tsx
- content/webapp/pages/books.tsx
See https://wellcome.slack.com/archives/C8X9YKM5X/p1662126830889919
> Put books in the stories section of the site

- catalogue/webapp/test/utils/dates.test.ts
- common/utils/dates.test.ts
- common/utils/dates.ts
For https://github.com/wellcomecollection/wellcomecollection.org/issues/7831, broken out of #8405 for ease of reviewing
> Add more helpers and tests for @weco/catalogue/utils/dates

- common/views/themes/newConfig.ts
People working on new palette
Tweaked two colours based on conversations with Dom and Jonathan
> tweak new palette colours

- content/webapp/components/Body/Body.tsx
Users
Fixes bugs where class wasn't assigned properly and made some titles hard to read (found in Collections)
> Fix class not declared properly

- prismic-model/src/stories-landing.ts
> create a new stories-landing type in Prismic

- catalogue/webapp/pages/concept.tsx
- common/views/themes/newConfig.ts
- common/views/themes/typography.ts
- content/webapp/components/HTMLSerializers/HTMLSerializers.tsx
Design
Tweaked cream colour as discussed and removed green underline on links (black one instead)
> Change cream and remove green link underline

- cardigan/stories/components/Cards/Cards.stories.tsx
- cardigan/stories/components/PageHeader/PageHeader.stories.tsx
- catalogue/webapp/components/ArchiveTree/ArchiveTree.tsx
- catalogue/webapp/components/Download/Download.tsx
- catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx
- catalogue/webapp/pages/item.tsx
- common/views/components/Pagination/Pagination.tsx
- common/views/components/SearchFilters/SearchFiltersMobile.tsx
- content/webapp/components/Exhibition/Exhibition.tsx
- content/webapp/components/ExhibitionPromo/ExhibitionPromo.tsx
- content/webapp/pages/event.tsx
> Remove a couple of doubled-up properties

- playwright/test/works-search.test.ts
Everyone
Fixes broken mobile tests where it was trying to target a visually hidden element.
> Target unhidden pagination element on mobile

- prismic-model/src/parts/article-body.ts
> Add 'frames' label to the editorialImageGallery (to create responsive comics)

- catalogue/webapp/components/WorkDetails/WorkDetails.tsx
For https://github.com/wellcomecollection/platform/issues/5603
> Link contributor tags to concept pages if available

- common/views/components/TabNav/TabNav.styles.tsx
- common/views/components/TabNav/TabNavV2.tsx
Our team
Tracks clicks on unselected Tabs within TabNav2. Also tracks when navigating with the keyboard.
> Track Tabs with GA

- common/data/microcopy.ts
People who want to know what exhibition guides are for
Telling them what exhibition guides are for
> added description text for exhibition guides

- catalogue/webapp/components/WorkDetails/WorkDetails.tsx
- catalogue/webapp/components/WorksSearchResult/WorksSearchResultV2.styles.tsx
- catalogue/webapp/components/WorksSearchResult/WorksSearchResultV2.tsx
- catalogue/webapp/pages/concept.tsx
- catalogue/webapp/pages/images.tsx
- catalogue/webapp/pages/works.tsx
- common/data/microcopy.ts
- common/views/components/BetaMessage/BetaMessage.tsx
- common/views/components/LinkLabels/LinkLabels.tsx
Our users, design
Final (?) tweaks to design for MVP.
A description is added to explain what Concept pages are for.
> Concept CSS tweaks, add missing content

- common/server-data/index.ts
- common/server-data/prismic.ts
Last night, the site went down for about a minute.  If you look in the logs, you see the following error:
TypeError: Cannot read property 'results' of null
at simplifyCollectionVenues
This is an error we've seen before, and the previous fix was wrong.
We fetch certain data from Prismic on a fixed interval (aka "server data"). It gets saved to a JSON file on the server's disk, and read from the file on every request, rather than going back to Prismic.
If there's an error fetching the data from Prismic (e.g. a timeout), we'd write `null` into the JSON file.  This causes problems on the next request, and all subsequent requests until we get new Prismic data.
This gives a plausible explanation for last night's partial outage:
1.  A single instance of the content app has an error fetching …
> Make sure the site doesn't crash when we get bad server-data

- catalogue/webapp/components/WorksSearchResult/WorksSearchResultV2.tsx
- catalogue/webapp/pages/concept.tsx
Us, applying final touches
Some tweaks [requested by Jonathan](https://wellcome.slack.com/archives/C02ANCYL90E/p1663932751160909?thread_ts=1663852254.145319&cid=C02ANCYL90E)
> Concept: Tweaks to Beta Message and remove Date heading

- playwright/test/view-items.test.ts
Us
Fixes e2e, forgot to add the added characters to the tests
> Fix heading tests

- cardigan/stories/global/spacing/spacing.stories.tsx
- catalogue/webapp/components/IIIFImage/IIIFImage.tsx
- catalogue/webapp/components/ImageCard/ImageCard.tsx
- catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx
- common/views/components/Dot/Dot.tsx
- common/views/components/Label/Label.tsx
- common/views/components/Number/Number.tsx
- common/views/components/PageHeader/PageHeader.tsx
- common/views/components/WobblyEdge/WobblyEdge.tsx
- content/webapp/components/Body/Body.tsx
- content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx
- content/webapp/components/FeaturedCard/FeaturedCard.tsx
- content/webapp/components/StatusIndicator/StatusIndicator.tsx
- content/webapp/pages/event.tsx
Devs
Some types should have been PaletteColor and not string, so changing that to help us moving forward.
> Use PaletteColor type where useful

- content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx
Anyone using guides. https://github.com/wellcomecollection/wellcomecollection.org/issues/8487
Applying the lightYellow colour as per our colour palette and Dom's lovely designs.
> updating yellow to lightYellow

- cardigan/stories/global/palette/palette.stories.tsx
Us and better typing
[Based on this comment](https://github.com/wellcomecollection/wellcomecollection.org/pull/8506#pullrequestreview-1121545644)
It seems that types that are too nested aren't coming up as errors when of the wrong type, so we're being a lot more specific!
If there's a better way to do this please let me know, still learning on types 🤓 
Closes #8567
> Subtype HSL/RGB and expect certain outputs

- content/webapp/pages/stories.tsx
Forgot to display the description text
> Display the section description on the Stories landing page

- common/test/fixtures/components/galleries-venue.ts
- common/utils/format-date.test.ts
- common/utils/format-date.ts
- common/views/components/Dot/Dot.tsx
- common/views/components/Footer/Footer.tsx
- common/views/components/OpeningTimes/OpeningTimes.tsx
- content/webapp/components/VenueHours/VenueHours.tsx
Devs.
Helping them see what this code does. You can see it from the tests, but IMO it's useful to have the intended behaviour described explicitly.
> Add some commentary around how dates are formatted

- content/webapp/pages/exhibition-guide.tsx
> don’t show undefined in the title

- content/webapp/services/prismic/types/series.ts
- content/webapp/utils/colors.ts
- prismic-model/src/series.ts
Editors
Allows selection of new colours for series' themes.
> Change series color options for new palette

- package.json
For any engineers who want to run through all of our unit and playwright tests before merging their PRs.
There is now one command that will run all tests `yarn e2e`
> E2E Test scripts

- common/views/components/Picture/Picture.tsx
Devs.
Giving us less code to maintain.
> Remove the unused PictureFromImages component

- content/webapp/pages/stories.tsx
- content/webapp/services/prismic/transformers/stories-landing.ts
- content/webapp/types/stories-landing.ts
Editorial.
Making it super easy for them to find the stories landing page.
> Link to the Stories landing page in the API toolbar

- cardigan/stories/docs/principles.stories.mdx
Fixes #7933 
Updates the browser support list based on recent analytics data
> Update browser support list

- catalogue/webapp/components/IIIFViewer/NoScriptViewer.tsx
- catalogue/webapp/components/IIIFViewer/ViewerTopBar.tsx
- common/views/themes/utility-classes.ts
- identity/webapp/src/frontend/MyAccount/MyAccount.style.ts
Another few bits of https://github.com/wellcomecollection/wellcomecollection.org/issues/8420
> Continue to chip away at some utility classes

- catalogue/webapp/components/CalendarSelect/CalendarSelect.tsx
- common/services/prismic/opening-times.ts
- common/utils/dates.ts
- common/utils/format-date.test.ts
- common/utils/format-date.ts
- content/webapp/components/EventDateRange/EventDateRange.tsx
- content/webapp/components/EventSchedule/EventSchedule.tsx
- content/webapp/components/EventSchedule/EventScheduleItem.tsx
- content/webapp/components/ExhibitionPromo/ExhibitionPromo.tsx
- content/webapp/components/FeaturedCard/FeaturedCard.tsx
- content/webapp/components/VenueHours/VenueHours.tsx
- content/webapp/pages/whats-on.tsx
- content/webapp/services/prismic/events.ts
Devs.
Tightening up some of this code; reusing components for consistency. For https://github.com/wellcomecollection/wellcomecollection.org/issues/7831
> Miscellaneous code tidies in EventSchedule and other components

- common/views/components/InfoBanner/InfoBanner.tsx
- common/views/components/PrismicImage/PrismicImage.tsx
- common/views/themes/utility-classes.ts
- content/webapp/components/Quote/Quote.tsx
Gradually chipping away at https://github.com/wellcomecollection/wellcomecollection.org/issues/8420
> Miscellaneous code tidies in CSS utility classes and the desaturated contributors

- common/views/components/Footer/FooterNav.tsx
- common/views/components/Header/Header.tsx
a11y failings
Add an ID to the first item of the Footer Internal Nav to allow Javascript-less users to access a menu when they click on the burger menu.
> Re-add an ID to the first nav item in footer

- playwright/test/works-search.test.ts
Broken e2e tests
Changes the intended click target after changes to the component were made
> Change h2 target to h3

- common/views/components/Footer/Footer.tsx
- common/views/components/Footer/FooterNav.tsx
Design
Makes a few changes to the order of the menu and the look of the footer on mobile
Closes #8636
> Tweaks to new footer

- catalogue/webapp/pages/images.tsx
- catalogue/webapp/pages/works.tsx
- common/views/components/ClearSearch/ClearSearch.tsx
- common/views/components/Header/Header.tsx
- common/views/components/SearchFilters/ResetActiveFilters.tsx
- common/views/components/WobblyBottom/WobblyBottom.tsx
- common/views/themes/utility-classes.ts
- content/webapp/components/Body/VisitUsStaticContent.tsx
- content/webapp/components/CaptionedImage/CaptionedImage.tsx
- content/webapp/components/Card/Card.tsx
- content/webapp/components/EventPromo/EventPromo.tsx
- content/webapp/components/ExhibitionGuideLinksPromo/ExhibitionGuideLinksPromo.tsx
- content/webapp/components/ExhibitionGuidePromo/ExhibitionGuidePromo.tsx
- content/webapp/components/ExhibitionPromo/ExhibitionPromo.tsx
- content/webapp/components/FacilityPromo/FacilityPromo.tsx
- content/webapp/components/ImageWithTasl/ImageWithTasl.tsx
- content/webapp/components/InfoBox/InfoBox.tsx
- content/webapp/components/SeasonsHeader/SeasonsHeader.tsx
- content/webapp/components/StoryPromo/StoryPromo.tsx
Chipping away at https://github.com/wellcomecollection/wellcomecollection.org/issues/8420
> Continue tidying single-line utility classes

- catalogue/webapp/app.ts
- catalogue/webapp/pages/search.tsx
- toggles/webapp/toggles.ts
Devs
Allows us to start working on a future search page behind a toggle
> Extremely basic Search page behind a toggle

- cache/.terraform.lock.hcl
- cache/modules/wc_org_cloudfront/distribution.tf
- cache/modules/wc_org_cloudfront/waf.tf
- catalogue/terraform/.terraform.lock.hcl
- catalogue/terraform/provider.tf
- catalogue/terraform/stack/main.tf
Devs
Adding the new search page to the config and setting rules for it
> Added rules and config for Search page

- toggles/webapp/toggles.ts
Devs
Allows a new toggle to be activated for #8665
> Add image search v2 toggle

- content/webapp/components/CaptionedImage/CaptionedImage.tsx
> Limit image zoom to exhibition guides for now

- content/webapp/pages/article.tsx
- toggles/webapp/toggles.ts
Closes #8648
Making reading time visible for everyone when it's available.
> Remove readingTime toggle

- content/webapp/components/ZoomedPrismicImage/ZoomedPrismicImage.tsx
- toggles/webapp/toggles.ts
> Bring zoom for guides out from behind toggle

- catalogue/webapp/components/IIIFViewer/ViewerBottomBar.tsx
- catalogue/webapp/components/Work/Work.tsx
- catalogue/webapp/components/WorkDetails/OnlineResources.tsx
- common/views/components/BaseTabs/BaseTabs.tsx
- common/views/components/JsonLd/JsonLd.tsx
- common/views/components/LabelsList/LabelsList.tsx
- common/views/components/MessageBar/MessageBar.tsx
- common/views/components/NewsletterPromo/NewsletterPromo.tsx
- common/views/components/Picture/Picture.tsx
- common/views/components/SegmentedControl/SegmentedControl.tsx
- common/views/themes/mixins.ts
- common/views/themes/utility-classes.ts
- content/webapp/components/Card/Card.tsx
- content/webapp/components/EventPromo/EventPromo.tsx
- content/webapp/components/EventSchedule/EventBookingButton.tsx
- content/webapp/components/ExhibitionGuidePromo/ExhibitionGuidePromo.tsx
- content/webapp/components/ExhibitionPromo/ExhibitionPromo.tsx
- content/webapp/components/GifVideo/GifVideo.tsx
- content/webapp/components/StoryPromo/StoryPromo.tsx
- identity/webapp/src/frontend/components/PasswordInput/PasswordInput.style.ts
> Continue to chip away at one-line utility classes

- catalogue/webapp/pages/works.tsx
- common/views/components/LabelsList/LabelsList.tsx
- common/views/components/SearchFilters/SearchFiltersMobile.tsx
- common/views/themes/utility-classes.ts
- content/webapp/components/OnThisPageAnchors/OnThisPageAnchors.tsx
- content/webapp/components/TitledTextList/TitledTextList.tsx
- content/webapp/components/VenueHours/VenueHours.tsx
- content/webapp/pages/book.tsx
- identity/webapp/src/frontend/components/PasswordInput/PasswordInput.style.ts
> Continue tidying up utility classes and component styles

- cardigan/stories/components/IIIFViewer/IIIFViewer.stories.tsx
- catalogue/webapp/components/Download/Download.tsx
- catalogue/webapp/components/IIIFViewer/IIIFViewer.tsx
- catalogue/webapp/components/IIIFViewer/ViewerTopBar.tsx
- catalogue/webapp/components/ItemViewerContext/ItemViewerContext.tsx
- catalogue/webapp/components/WorkDetails/WorkDetails.tsx
- catalogue/webapp/hooks/useTransformedIIIFImage.ts
- catalogue/webapp/hooks/useTransformedManifest.ts
- catalogue/webapp/pages/download.tsx
- catalogue/webapp/pages/item.tsx
- catalogue/webapp/services/iiif/fetch/image.ts
- catalogue/webapp/services/iiif/transformers/image.ts
- catalogue/webapp/services/iiif/transformers/manifest.ts
- catalogue/webapp/services/iiif/types/image/v2/index.ts
- catalogue/webapp/types/image.ts
- catalogue/webapp/types/manifest.ts
Fixes #8696 
Some refactoring of how we create download links, before moving it over to use iiif3 in #8697
- create and uses fetch and transform functions for iiif-image json
- removes some duplicate props on the TransformedManifest
- adds some comments which hopefully makes it clearer how the download links are created
> Iiif3 downloads

- dash/Dockerfile
- dash/webapp/babel.config.js
- dash/webapp/components/Header.tsx
- dash/webapp/next-env.d.ts
- dash/webapp/package.json
- dash/webapp/pages/index.tsx
- dash/webapp/pages/pa11y.tsx
- dash/webapp/pages/toggles.tsx
- dash/webapp/tsconfig.json
- dash/webapp/yarn.lock
- pa11y/webapp/package.json
- pa11y/webapp/write-report.js
Devs/Team
Added a concept page and an item viewer page for pa11y checks; ended up updating packages in dash as well + fixing some type errors in all dash pages.
Once this is approved I'll test deploying the changes properly.
Closes #8704
> Updated dash packages and added pages to pa11y checks

- catalogue/webapp/pages/search/exhibitions.tsx
- catalogue/webapp/pages/search/index.tsx
- common/views/pages/_app.tsx
development team
unblock e2e tests that are broken due to a11y test case being affected
> restructured _app.js implementation to not cause unknown side-effects

- pa11y/webapp/deploy.js
- toggles/webapp/s3-utils.ts
- toggles/webapp/setDefaultValueFor.ts
Anyone wanting to consult those dashboards!
Clears cache once the changes are deployed successfully
> Move invalidations within success

- catalogue/webapp/services/iiif/transformers/manifest.ts
- catalogue/webapp/utils/iiif/v3/index.ts
> Get title from IIIFV3 manifest

- catalogue/webapp/services/iiif/transformers/manifest.ts
> Count number of canvases with a type of 'Manifest' instead of all items

- common/views/components/AppContext/AppContext.tsx
- common/views/components/Header/Header.tsx
- common/views/components/Header/MobileSignIn.tsx
- common/views/components/styled/CssGridContainer.tsx
- common/views/themes/base/container.ts
- common/views/themes/base/layout.ts
- common/views/themes/config.ts
- common/views/themes/default.ts
- common/views/themes/grid/grid-base.ts
- common/views/themes/grid/grid-scroll.ts
- common/views/themes/grid/grid-size.ts
- common/views/themes/grid/grid-theme.ts
- common/views/themes/mixins.ts
- common/views/themes/utility-classes.ts
Devs
Avoids confusion at to how to declare media queries across the code
Closes #8749
> Remove respondTo and respondBetween and move it to themeValues

- catalogue/webapp/components/IIIFViewer/IIIFViewer.tsx
☝️ 
This should really _really_ fix the e2e tests.
> Keep parentManifest as a dependency as well

- catalogue/webapp/components/Work/Work.tsx
Design
Fixes missing space on Work header
> Specify spacing is vertical in work

- catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx
- catalogue/webapp/pages/search/catalogue.tsx
- catalogue/webapp/pages/search/images.tsx
- common/views/components/SearchBar/SearchBar.tsx
- common/views/components/SearchPagination/SearchPagination.tsx
Users of the new search pages
Gives them the functionality to navigate pages
> Implement pagination component onto image page and catalogue search pages

- catalogue/webapp/services/iiif/transformers/manifest.ts
- catalogue/webapp/types/manifest.ts
- catalogue/webapp/utils/iiif/v2/index.ts
- catalogue/webapp/utils/iiif/v3/index.ts
Fixes #8732
Using the iiif3 manifest for the search service
> Search within iiif3

- content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx
> Increase contrast of buttons inside context (beige) sections

- dash/webapp/pages/pa11y.tsx
This makes it easier to see at a glance whether we have lots of distinct errors, or one error lots of times.
> Group similar issues on the pa11y dashboard

- common/views/components/AudioPlayer/AudioPlayer.tsx
☝️ 
Fixes #8809
I haven't been able to get ngrok/localtunnel working so mobile testing will have to wait till the changes are at least on stage, but I believe this will at the very least keep pa11y happy
> Use hidden text inside button instead of aria-label

- assets/humans.txt
> Adding Adi

- common/views/components/SearchBar/SearchBar.tsx
Any user of the search page
allowing for an easy way to clear the search query
> add clear search query button

- catalogue/webapp/pages/search/stories.tsx
new Search
Displays title for search results cards (following the new data structure)
> Displays title for search results cards

- playwright/test/images.test.ts
Failing e2es
Image modal test was still using an old selector, changed it to the new one
> Change selector for author

- content/webapp/components/OnThisPageAnchors/OnThisPageAnchors.tsx
__Before__
__After__
I'm obviously not the best person to pick colours, but this was as close to the feel of the existing component as I could get while making sure there was enough contrast using the colours available in the palette.
> Use colors from palette with enough contrast

- catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx
- catalogue/webapp/pages/search/images.tsx
- catalogue/webapp/pages/search/works.tsx
- common/views/components/ButtonSolid/ButtonSolidV2.tsx
- common/views/components/SearchBar/SearchBar.tsx
- common/views/components/SearchPagination/SearchPagination.tsx
- common/views/components/Select/Select.tsx
- common/views/components/SelectContainer/SelectContainer.tsx
- common/views/components/TextInput/TextInputV2.tsx
Users of the new Search subpages
accessible sort component, and a support for no javascript
closes #8734
> Search page sort

- common/data/vanity-urls.ts
- content/webapp/app.ts
per Danny's request in Slack
this turned out to be a little more involved because all our existing vanity URLs are for `/pages/:id`, but it wasn't hard
> Add a vanity URL for "In Plain Sight"

- catalogue/webapp/components/ItemRequestModal/ConfirmedDialog.tsx
See screenshot in https://github.com/wellcomecollection/wellcomecollection.org/issues/8448, booooooo.
> Add a non-breaking space to the phrase 'level 3'

- catalogue/webapp/components/WorkDetails/WorkDetails.tsx
- content/webapp/components/ContentPage/ContentPage.tsx
- content/webapp/components/Contributors/Contributors.tsx
Spotted while reading some code.
> Add a note about a legacy wellcomelibrary.org link, plus a few cleanups

- common/views/components/SearchBar/SearchBar.tsx
Search
Noticed in one of the merges we'd lost this bit, so re-adding it!
> Re-add clear button in search input

- catalogue/webapp/pages/concept.tsx
- catalogue/webapp/pages/search/events.tsx
- catalogue/webapp/pages/search/exhibitions.tsx
- catalogue/webapp/pages/search/index.tsx
- catalogue/webapp/pages/search/stories.tsx
- content/webapp/pages/article-series.tsx
- content/webapp/pages/article.tsx
- content/webapp/pages/book.tsx
- content/webapp/pages/event.tsx
- content/webapp/pages/exhibition.tsx
Analytics
Tracks more pages:
```
- /search
- /search/images
- /search/works
- /search/events
- /search/exhibitions
- /search/stories
- /events/[id]
- /exhibitions/[id]
- /series/[id]
- /articles/[id]
- /books/[id]
- /concepts/[id]
```
Some of the properties passed are subject to change.
Closes #8841
> Add pageview to an array of pages

- common/services/prismic/opening-times.ts
- common/test/services/prismic/opening-times.test.ts
⬆️ 
From this slack conversation:
https://wellcome.slack.com/archives/C8X9YKM5X/p1668445435662709
> show exceptional opening times 42 days in advance

- catalogue/webapp/pages/item.tsx
- catalogue/webapp/services/iiif/fetch/canvasOcr.ts
- catalogue/webapp/services/iiif/transformers/manifest.ts
- catalogue/webapp/types/manifest.ts
Relates to #8606
Gets collection manifests from the iiif v3 manifest
> iiif3 manifests

- catalogue/webapp/services/iiif/fetch/canvasOcr.ts
☝️ 
Fixes this https://www-stage.wellcomecollection.org/works/ng6jw4nx/items
> Make canvas optional in fetchCanvasOcr

- .buildkite/urls/expected_200_urls.txt
- pa11y/webapp/write-report.js
> Adding a page with a content warning to the url checker/pa11y

- catalogue/webapp/pages/search/images.tsx
- catalogue/webapp/pages/search/works.tsx
- common/views/components/CheckboxRadio/CheckboxRadio.tsx
- common/views/components/ModalMoreFilters/ModalMoreFilters.tsx
- common/views/components/PaletteColorPicker/PaletteColorPicker.tsx
- common/views/components/SearchFilters/SearchFilters.tsx
- common/views/components/SearchFilters/SearchFiltersDesktop.tsx
- common/views/components/SearchFilters/SearchFiltersMobile.tsx
- common/views/components/SearchForm/SearchForm.tsx
anyone that enjoys filtering their search results
Allow users of the new search pages to filter their search results
closes #8714
> Import current filter bar into new search

- catalogue/webapp/pages/item.tsx
☝️ 
[Context from Slack](https://wellcome.slack.com/archives/CQ720BG02/p1668547131131719)
> Don't 500 if we don't understand the manifest value

- catalogue/webapp/services/iiif/transformers/manifest.ts
- catalogue/webapp/utils/iiif/v2/index.ts
- catalogue/webapp/utils/iiif/v3/index.ts
> Use iiif3 for determining if there's a pdf download

- catalogue/terraform/provider.tf
- catalogue/terraform/stack/main.tf
- content/terraform/provider.tf
- content/terraform/stack/main.tf
- identity/terraform/stack/main.tf
- infrastructure/modules/service/main.tf
- infrastructure/modules/service/variables.tf
- lighthouse/terraform/.terraform.lock.hcl
- lighthouse/terraform/database.tf
- lighthouse/terraform/provider.tf
For https://github.com/wellcomecollection/platform/issues/5631
> Remove the remaining references to weco-deploy

- cache/modules/wc_org_cloudfront/waf.tf
People who want to know why our e2e tests are being blocked
Showing them what's going on
> Enable metrics and sampling for WAF rules

- cache/cloudfront_prod.tf
- cache/cloudfront_stage.tf
- cache/locals.tf
- cache/modules/wc_org_cloudfront/variables.tf
- cache/modules/wc_org_cloudfront/waf.tf
- cache/terraform.tf
Also removes the Bot Control rule, because it wasn't being used and costs money
> Allow requests from our CI NAT gateway

- catalogue/webapp/components/IIIFClickthrough/IIIFClickthrough.tsx
- catalogue/webapp/components/WorkDetails/WorkDetails.tsx
- catalogue/webapp/hooks/useShowClickthrough.ts
- catalogue/webapp/pages/item.tsx
- catalogue/webapp/services/iiif/transformers/manifest.ts
- catalogue/webapp/test/utils/iiif.test.ts
- catalogue/webapp/types/manifest.ts
- catalogue/webapp/utils/iiif/v2/index.ts
- catalogue/webapp/utils/iiif/v3/index.ts
- common/__mocks__/iiif-manifest-v3.ts
> Getting auth service related data from iiif v3 manifest

- catalogue/webapp/services/iiif/transformers/manifest.ts
- catalogue/webapp/utils/iiif/v3/index.ts
⬆️ 
Fixes the e2e tests that are currently failing
> check restricted service for tokenService too

- content/webapp/__mocks__/whats-on.ts
- content/webapp/pages/event.tsx
- content/webapp/services/prismic/events.test.ts
- content/webapp/services/prismic/events.ts
- content/webapp/services/prismic/transformers/events.test.ts
- content/webapp/services/prismic/transformers/events.ts
- content/webapp/types/events.ts
- content/webapp/utils/event-series.test.ts
Following a suggestion from Paul in https://github.com/wellcomecollection/wellcomecollection.org/pull/8937
> Restructure the isFullyBooked variable

- content/webapp/components/ExhibitionGuideLinksPromo/ExhibitionGuideLinksPromo.tsx
- content/webapp/pages/guides/exhibitions/[id]/[type].tsx
For https://github.com/wellcomecollection/wellcomecollection.org/issues/8928
> Update the copy on exhibition guide pages

- assets/humans.txt
For https://github.com/wellcomecollection/platform/issues/5639
> Removing Mel 😢

- catalogue/webapp/components/WorkDetails/WorkDetails.tsx
> show content advisory on works only for audio and video content

- catalogue/webapp/utils/works.ts
Nothing big or special, just sanding off a few rough edges I spotted.
> Make some assorted type tidies in the work utils

- common/views/components/AudioPlayer/AudioPlayer.tsx
> Don't show volume slider if it won't work

- content/webapp/components/LayoutPaginatedResults/LayoutPaginatedResults.tsx
- content/webapp/pages/articles.tsx
- content/webapp/pages/books.tsx
- content/webapp/pages/events.tsx
- content/webapp/pages/guides.tsx
- content/webapp/pages/guides/exhibitions/index.tsx
Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/8989
> Remove the "Free admission" message from the Past events page

- catalogue/webapp/components/IIIFViewer/ViewerStructures.tsx
- catalogue/webapp/components/WorkDetailsList/WorkDetailsList.tsx
- catalogue/webapp/components/WorksSearchResults/WorksSearchResults.tsx
- common/views/components/ApiToolbar/ApiToolbar.tsx
- common/views/components/ModalMoreFilters/ModalMoreFilters.tsx
- common/views/components/OpeningTimes/OpeningTimes.tsx
- common/views/components/SegmentedControl/SegmentedControl.tsx
- common/views/components/ToolbarSegmentedControl/ToolbarSegmentedControl.tsx
- content/webapp/components/ExhibitionGuideLinks/ExhibitionGuideLinks.tsx
- content/webapp/components/NewsletterSignup/NewsletterSignup.tsx
- content/webapp/components/VenueHours/VenueHours.tsx
- identity/webapp/src/frontend/components/PasswordInput/PasswordInput.style.ts
- identity/webapp/src/frontend/components/PasswordInput/PasswordRules.tsx
> Continue to chip away at our one-line styles

- common/views/components/Breadcrumb/Breadcrumb.tsx
- common/views/components/RadioGroup/RadioGroup.tsx
- common/views/components/SectionHeader/SectionHeader.tsx
- common/views/themes/utility-classes.ts
- content/webapp/components/SeasonsHeader/SeasonsHeader.tsx
> Continue trimming the one-line classes

- cache/modules/wc_org_cloudfront/waf.tf
Previously, the allowlist only applied to the AWS-managed IP reputation list, meaning that requests from Wellcome Collection CI were still being blocked by rate limiting - this PR moves that allowlist to a top-level rule, meaning we should never block our own requests.
> Move WAF IP allowlist to the top level

- catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx
- catalogue/webapp/pages/images.tsx
- catalogue/webapp/pages/search/images.tsx
- catalogue/webapp/pages/search/works.tsx
- catalogue/webapp/pages/works.tsx
- common/views/components/ButtonSolid/ButtonSolid.tsx
- common/views/components/DropdownButton/DropdownButton.tsx
- common/views/components/Modal/Modal.test.tsx
- common/views/components/Modal/Modal.tsx
- common/views/components/ModalMoreFilters/ModalMoreFilters.tsx
- common/views/components/PaletteColorPicker/PaletteColorPicker.tsx
- common/views/components/SearchFilters/SearchFilters.tsx
- common/views/components/SearchFilters/SearchFiltersDesktop.tsx
- common/views/components/SearchTabs/SearchTabs.tsx
Users of the new search pages
Gives them a shiny new filter bar to use and mess around with!
> Theming the new filter bar

- catalogue/webapp/components/Work/Work.tsx
> don't showTabbedNav for items without digitalLocations

- cache/locals.tf
> bump request and response versions

- .github/workflows/performance.yml
- cache/edge_lambdas/src/redirects.ts
Which is linked from Stories: https://wellcomecollection.org/articles/WZHSlSoAAJH9hMCI
> Add a redirect for wc.org/eat-me

- catalogue/webapp/components/CalendarSelect/CalendarSelect.tsx
- catalogue/webapp/components/ItemRequestModal/RequestDialog.tsx
- catalogue/webapp/components/ItemRequestModal/useAvailableDates.ts
- catalogue/webapp/test/utils/dates.test.ts
- catalogue/webapp/utils/dates.ts
- common/model/opening-hours.ts
- common/services/prismic/transformers/collection-venues.ts
- common/utils/format-date.ts
This is some refactoring ahead of https://github.com/wellcomecollection/wellcomecollection.org/issues/9042
It doesn't affect the behaviour of the code at all, just tidies a few things up before the actual fix.
> Refactoring of date stuff

- catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx
- common/data/microcopy.tsx
- common/views/components/SearchBar/SearchBar.tsx
SEO and accessibility
better and clearer descriptions and titles that are consistent with the rest of the platform
also clearer and better placeholder text for the new search pages
closes #8934
> modify search page meta data

- common/views/components/PrismicImage/PrismicImage.tsx
- content/webapp/components/ImageGallery/ImageGallery.tsx
Fixes #8971 (hopefully)
Users
Giving them appropriately sized comic frame images
> Use more appropriate image component for comic gallery images

- content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx
> Send event when 'read full transcript' button pressed

- catalogue/webapp/services/prismic/fetch/articles.ts
- catalogue/webapp/services/prismic/transformers/index.ts
- catalogue/webapp/services/prismic/types/event.ts
- catalogue/webapp/services/prismic/types/exhibition.ts
- catalogue/webapp/services/prismic/types/index.ts
- catalogue/webapp/services/prismic/types/story.ts
- catalogue/webapp/test/prismic/index.test.ts
Devs
I noticed the types weren't quite right as [this line](https://github.com/wellcomecollection/wellcomecollection.org/blob/f80cfc4f19d2d33762e0f0ee3bfbd2d174224144/catalogue/webapp/test/prismic/index.test.ts#L71) had a type warning/error.
I've gone through them and believe they're all set, now. Someone with further knowledge of Prismic might have flags to put up, but it all seems to work nicely and no warnings pop up anymore.
> Change Prismic types for search

- common/services/app/google-analytics.tsx
> Remove invalid async attribute from inline script tag

- content/webapp/pages/event.tsx
Removing a few unnecessary parameters and duplicate conditionals; spotted while looking at https://github.com/wellcomecollection/wellcomecollection.org/issues/9090
> Small code tidies on the /event page

- catalogue/webapp/next.config.js
- common/next/next.config.js
- content/webapp/next.config.js
- package.json
- scripts/run-concurrently.sh
developers who are trying to work between apps at the same time
allowing them to navigate across apps with ease
still in progress, and still needs a lot of testing for use cases and suitability.
To get this running, you just need to run `yarn run-concurrently`, please note that all three apps will be running simultaneously, this includes identity, please do reach out to a team member with regards to the first setup of the identity app
closes #8993
> base setup for the concurrent running of the apps

- catalogue/webapp/components/VisuallySimilarImagesFromApi/VisuallySimilarImagesFromApi.tsx
- common/views/components/PaletteColorPicker/PaletteColorPicker.tsx
General design
- Fixes issues flagged in [new search feedback document](https://docs.google.com/document/d/1UHaHXMRSioQNesUMYUHdjlHRtAipDva_caCplhGpOxI/edit#)
- Colours filter in iOS should be black - not blue
- Visually Similar images title is white - should be black
> Fix text colours

- common/views/components/ButtonSolidLink/ButtonSolidLink.tsx
Spotted while reviewing https://github.com/wellcomecollection/wellcomecollection.org/pull/9128
> Tidy up a type in ButtonSolid

- catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx
- catalogue/webapp/components/StoriesGrid/StoriesGrid.tsx
- catalogue/webapp/components/WorksSearchResult/WorksSearchResult.styles.tsx
- catalogue/webapp/components/WorksSearchResult/WorksSearchResult.tsx
- common/views/components/ClearSearch/ClearSearch.tsx
- common/views/components/SubNavigation/SubNavigation.tsx
mobile users that use assistive technology
semantic fixes
> iOS accessibility for new search

- catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx
- catalogue/webapp/package.json
- common/views/components/ClearSearch/ClearSearch.tsx
- yarn.lock
developers and maintainers of the code
knowing that we will be upgrading towards Next13 in the future, ensuring that we are using libraries that are well maintained and compatible with newer versions of react is essential
closes #8919
> changed from an abandoned library into a maintained one

- toggles/webapp/toggles.ts
new search
This has already been deployed, this keeps the toggles up to date.
> Search toggle defaults to active by default

- catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx
- playwright/test/selectors/images.ts
Platform
unblocks deployment due to a broken e2e test
> added missing element attribute so it can be found in PlayWright

- content/webapp/components/CompactCard/CompactCard.tsx
- content/webapp/components/MediaObject/MediaObject.tsx
- content/webapp/components/MediaObjectBase/MediaObjectBase.tsx
- content/webapp/components/MediaObjectList/MediaObjectList.tsx
Spotted on code read, small improvement.
> Reduce the amount of repetition in the CompactCard component

- catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx
- catalogue/webapp/components/IIIFImage/IIIFImage.tsx
- catalogue/webapp/components/ImageCard/ImageCard.tsx
- catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx
- catalogue/webapp/pages/search/images.tsx
- common/views/components/PaletteColorPicker/PaletteColorPicker.tsx
also: removing unnecessary height value
closes #9070
> refactor IIIFImage logic

- infrastructure/modules/service/main.tf
> Bump ECS module versions to access updated firelens container

- common/views/components/SpacingSection/SpacingSection.tsx
- content/webapp/components/BookImage/BookImage.tsx
- content/webapp/components/FacilityPromo/FacilityPromo.tsx
- content/webapp/pages/stories/index.tsx
A few more things spotted while reading code.
> Tidy up a few more components

- common/views/components/BorderlessClickable/BorderlessClickable.tsx
A small improvement I spotted while reading some code.
> Reduce some repetition in BorderlessClickable

- cache/.terraform.lock.hcl
- cache/edge_lambdas.tf
- cache/locals.tf
- cache/s3_cloudfront_logs.tf
- cache/s3_lambdas.tf
- cache/terraform.tf
- cache/versions.tf
It's a no-op plan, and fixes all the deprecation warnings.
> Fix some deprecation warnings in the CloudFront Terraform

- catalogue/webapp/pages/images.tsx
Not to be merged until https://github.com/wellcomecollection/catalogue-api/pull/616 is deployed
> Pass through error messages from the images endpoint, as we do for works

- catalogue/webapp/components/IIIFSearchWithin/IIIFSearchWithin.tsx
- catalogue/webapp/components/IIIFViewer/ViewerSidebar.tsx
- common/views/components/Iframe/Iframe.tsx
- common/views/components/SegmentedControl/SegmentedControl.tsx
- common/views/themes/utility-classes.ts
- content/webapp/components/Card/Card.tsx
- content/webapp/components/EventPromo/EventPromo.tsx
- content/webapp/components/ExhibitionPromo/ExhibitionPromo.tsx
- content/webapp/components/FacilityPromo/FacilityPromo.tsx
- content/webapp/components/FeaturedCard/FeaturedCard.tsx
> Remove the `no-padding` one-line class

- common/views/themes/utility-classes.ts
- content/webapp/pages/stories/index.tsx
> Inline the one-line class touch-scroll in the one place where it's used

- common/views/components/SegmentedControl/SegmentedControl.tsx
- common/views/themes/utility-classes.ts
> Inline the one-line class transition-bg in the one place where it's used

- content/webapp/components/Exhibition/Exhibition.tsx
- content/webapp/components/Installation/Installation.tsx
- content/webapp/pages/exhibitions/[exhibitionId].tsx
Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/9219
> Fix the canonical URL on the Installation component

- content/webapp/components/LayoutPaginatedResults/LayoutPaginatedResults.tsx
- content/webapp/pages/books/index.tsx
Before: Home
After: Home | Stories
> Add a breadcrumb trail to the /books page

- catalogue/webapp/components/Download/Download.tsx
- catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx
- catalogue/webapp/components/ItemRequestModal/RequestDialog.tsx
- common/views/themes/utility-classes.ts
Chipping away at https://github.com/wellcomecollection/wellcomecollection.org/issues/8420
> Get rid of the one-line inline-block class

- catalogue/webapp/components/MediaAnnotations/MediaAnnotations.tsx
- catalogue/webapp/services/iiif/transformers/manifest.ts
- catalogue/webapp/utils/iiif/v3/index.ts
Nothing major, but I spotted a few places where we're checking for `undefined` even though we know the value is filled.
> Clean up some types in the IIIF transformer utilities

- assets/humans.txt
Moved Tom to alumni section. Also moved Christy to the DE Office.
All humans
Letting them know who we are
> 😭 Initiate alumni status for Tom Scott 😭

- playwright/playwright.config.ts
per discussion in retro this week
> Disable WebKit in our e2e tests

- playwright/test/search.test.ts
Devs
As we added the # of results in the buttons, it won't be an exact match, so this reflects it.
> Fix search button tests

- content/webapp/next-env.d.ts
- content/webapp/package.json
- content/webapp/test/pages/whats-on.test.tsx
- identity/webapp/next-env.d.ts
- identity/webapp/src/frontend/Error/Error.test.tsx
- identity/webapp/tsconfig.json
developers trying to deploy
fixes a failing test case due to a missing mock
> add next-router-mock to content

- playwright/test/new-images-search.test.ts
- playwright/test/search.test.ts
the team 
unblocking the e2e tests for mobile, by the new search tests added
> proper support for mobile tests added

- .buildkite/urls/expected_200_urls.txt
- content/webapp/app.ts
- content/webapp/pages/guides/[pageId].tsx
- content/webapp/pages/projects/[pageId].tsx
Developers
making use of file base routing to simplify app.ts
> changed the routing logic for the affected paths

- common/views/themes/base/layout.ts
> Already reviewed: Check for :has() support

- scripts/run-concurrently.sh
developers who wish to run e2e tests locally
a more in-house and complete solution, that clears the local build cache before rebuilding
> improved the concurrent running apps script

- common/views/components/ModalMoreFilters/ModalMoreFilters.tsx
- common/views/components/SearchFilters/SearchFiltersDesktop.tsx
> Lowercase F in "All Filters"

- .gitignore
- catalogue/webapp/next-env.d.ts
- content/webapp/next-env.d.ts
- dash/webapp/next-env.d.ts
- identity/webapp/next-env.d.ts
developers
following the instructions found [here](https://nextjs.org/docs/basic-features/typescript)
> A file named next-env.d.ts will be created at the root of your project. This file ensures Next.js types are picked up by the TypeScript compiler. You should not remove it or edit it as it can change at any time. **This file should not be committed and should be ignored by version control (e.g. inside your .gitignore file)**.
> remove next-env.d.ts from being tracked by git

- catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx
- catalogue/webapp/pages/concepts/[conceptId].tsx
- catalogue/webapp/pages/search/index.tsx
- common/views/components/Header/HeaderSearch.tsx
new Search + aligned concept
- Changes copy according to ticket
Closes #9284
> Search copy changes

- playwright/test/concept.test.ts
> Fix e2es: Change h2 to new copy

- catalogue/webapp/components/Sort/Sort.tsx
- catalogue/webapp/pages/search/stories.tsx
- common/utils/search.ts
Search
- Remove alphabetical order from stories (is not working properly)
- Remove alphabetical case in helper function
- Change order of publication dates to match works'
I didn't remove all references in helper function comments (`common/utils/search.ts`) as I still think it helps explain how it works.
For #9285
> Remove alphabetical sorting and change order of publication

- playwright/playwright.config.ts
> allow more workers in the e2e tests

- catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx
- playwright/test/images.test.ts
- playwright/test/landing-pages.test.ts
Reverts wellcomecollection/wellcomecollection.org#9314
> Revert "delete old images tests, change page title for search pages"

- .buildkite/urls/expected_200_urls.txt
- cache/send_slack_alert_for_5xx_errors.js
- cardigan/stories/components/BackToResults/BackToResults.stories.tsx
- cardigan/stories/components/Tags/Tags.stories.tsx
- common/services/catalogue/routes.ts
- common/test/services/catalogue/routes.test.ts
- common/views/components/ImagesLink/ImagesLink.tsx
- common/views/components/Pagination/Pagination.test.tsx
- common/views/components/SearchContext/SearchContext.tsx
- common/views/components/SearchForm/SearchForm.tsx
- common/views/components/SearchTabs/SearchTabs.tsx
- common/views/components/WorksLink/WorksLink.tsx
- playwright/test/concept.test.ts
- playwright/test/contexts.ts
- playwright/test/helpers/urls.ts
- playwright/test/search-form.test.ts
- playwright/test/works-search.test.ts
- updown/expected-checks.ts
Reverts wellcomecollection/wellcomecollection.org#9311
> Revert "Replace old search URLs with new ones, amend tests"

- cache/locals.tf
New search
Applies the new rules to production
> Apply redirects on prod

- toggles/README.md
Devs
Updates the Toggle Readme instructions on how to add toggles/set them to true for everyone
Do flag if anything else needs updating.
> Change toggles readme instructions

- cache/edge_lambdas/src/redirects.ts
Redirected exhibition page
Hopefully makes it work this time
> Add missing slashes

- cache/locals.tf
Content team
"old" The Archive of an Unseen exhibition page to redirect to "new" one
> Apply new redirect on prod

- catalogue/webapp/pages/search/images.tsx
- catalogue/webapp/pages/search/works.tsx
Users in search
Hides filters when there are no results. See #9320 for more info
Closes #9320
> Hide filters if there are no results

- common/views/components/FindUs/FindUs.tsx
> Add accessibility link to the footer

- common/views/components/FindUs/FindUs.tsx
☝️ 
Per [this comment](https://github.com/wellcomecollection/wellcomecollection.org/pull/9343#issuecomment-1440440053)
> Put Getting Here and Accessibility in a list/match spacing with nav

- catalogue/webapp/services/prismic/transformers/index.ts
Search
Went too fast[ in my last PR](https://github.com/wellcomecollection/wellcomecollection.org/commit/73f32628f8835f521bd6cf721502b3d13f47a0f3) and removed a `?` that should've been there, so re-adding it or it will cause broken pages.
> Add missing optional

- catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx
- playwright/test/selectors/search.ts
> Replace extraneous roles with data-test-ids

- cardigan/.storybook/manager-head.html
> Fix cardy favicon

- cardigan/stories/components/Header/Header.stories.tsx
- common/views/components/Header/Header.tsx
- common/views/components/PageLayout/PageLayout.tsx
- content/webapp/pages/guides/exhibitions/[id]/[type].tsx
- content/webapp/pages/guides/exhibitions/[id]/index.tsx
- content/webapp/pages/guides/exhibitions/index.tsx
> Remove search from exhibition guides pages

- common/views/components/Header/Header.styles.ts
- common/views/components/Header/Header.tsx
- toggles/webapp/toggles.ts
Maintenance
Removes checks for the search toggle as it's always on now and we're happy with it
Part of #9034
> Remove header search toggle checks

- common/services/app/google-analytics.tsx
Fixes an error we were getting on 404 pages:
> check for toggles property

- .buildkite/pipeline.yml
developers trying to deploy
allowing for devs too deploy from main branch
> point pipeline deploy to correct branch

- .github/workflows/performance.yml
- cardigan/stories/components/LinkLabels/LinkLabels.stories.mdx
- cardigan/stories/components/LinkLabels/LinkLabels.stories.tsx
This is next on my list for refactoring and removing single-line classes, but I want a safety net first.
> Add some more Cardigan stories for the varieties of LinkLabel

- catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx
- catalogue/webapp/pages/api/works/items/[workId].tsx
Some people are having issues viewing the physical item details on https://wellcomecollection.org/works/cb284fcw
I'm not sure what's up, but this should help us debug the issue.
> Slightly improve the logging for error cases for physical item details

- content/webapp/components/SearchResults/SearchResults.tsx
- playwright/test/helpers/urls.ts
- playwright/test/media-office.test.ts
☝️ 
Adding a test to make sure the asyncSearchResults puts something on the page (after #9391)
> Make sure the press releases render

- catalogue/webapp/components/WorkDetails/WorkDetails.tsx
- catalogue/webapp/components/WorkDetailsSection/WorkDetailsSection.tsx
- catalogue/webapp/components/WorkDetailsText/WorkDetailsText.tsx
- catalogue/webapp/components/WorkHeader/WorkHeader.tsx
☝️ 
Closes #9373
Closes #9374
__TODO:__
~- [ ] centre digitised item when present~ (this deserves its own PR)
> Add consistent dividers for works in single column (unless archive)

- content/webapp/components/Contributors/Contributor.tsx
- content/webapp/components/Exhibition/Exhibition.tsx
- content/webapp/components/HTMLSerializers/HTMLSerializers.tsx
- content/webapp/components/Installation/Installation.tsx
- content/webapp/components/TitledTextList/TitledTextList.tsx
- content/webapp/pages/articles/[articleId].tsx
- content/webapp/pages/books/[bookId].tsx
- content/webapp/pages/homepage.tsx
Chipping away at https://github.com/wellcomecollection/wellcomecollection.org/issues/8420
> Remove some uses of the no-margin one-line class, and other style tidies

- common/utils/is-empty-object.ts
- content/webapp/app.ts
- content/webapp/components/EventPromo/EventPromo.test.tsx
- content/webapp/components/Installation/Installation.tsx
maintenance
quick linting fixes
> Various small adjustments

- catalogue/webapp/components/WorkDetailsProperty/WorkDetailsProperty.tsx
- catalogue/webapp/components/WorkDetailsText/WorkDetailsText.tsx
I've pulled a couple of the more complex conditionals into styled-components, and deleted some one-line classes `flex` and `no-margin` to boot.
> Tidy up the WorkDetailsProperty component

- cache/locals.tf
> Update locals.tf after deploying toggler lambda

- catalogue/webapp/components/SearchFilters/SearchFilters.Desktop.DynamicFilters.tsx
Users
Improve understanding and access to all filters
closes [#5667](https://github.com/wellcomecollection/platform/issues/5667)
> always display the all filters button

- catalogue/webapp/package.json
- common/package.json
- dash/webapp/package.json
- identity/webapp/package.json
- package.json
upgrades types/react, made a separate PR for this to prevent version conflicts
> bumps @types/react to 18.0.31

- dash/terraform/.terraform.lock.hcl
- infrastructure/modules/s3_website/cloudfront.tf
- lighthouse/terraform/.terraform.lock.hcl
For https://github.com/wellcomecollection/platform/issues/5664
> Upgrade to v4.x of the AWS Terraform provider (plus other Terraform tidies)

- identity/webapp/babel.config.js
- identity/webapp/jest.config.js
- identity/webapp/package.json
- identity/webapp/pages/index.tsx
- identity/webapp/src/frontend/jest-setup.ts
- yarn.lock
Reverts wellcomecollection/wellcomecollection.org#9489
It appears that this change may have removed the ability to sign in on staging.
the console logs out an error 204, and investigation needs to be made
> Revert "Bump @auth0/nextjs-auth0 from 1.9.3 to 2.4.0 in /identity/webapp"

- common/views/themes/utility-classes.ts
- content/webapp/components/ImageGallery/ImageGallery.tsx
> Replace the single-line 'absolute' class with a few styled-components

- .github/workflows/performance.yml
- infrastructure/experience/.terraform.lock.hcl
- infrastructure/experience/config.tf
For https://github.com/wellcomecollection/platform/issues/5664
> Upgrade Terraform to the 4.x version of the AWS provider

- common/views/components/AudioPlayer/AudioPlayer.tsx
- common/views/components/DropdownButton/DropdownButton.tsx
- common/views/components/Modal/Modal.tsx
- common/views/themes/base/wellcome-normalize.ts
- common/views/themes/config.ts
- common/views/themes/utility-classes.ts
Maintenance and #8420 continuation/information.
Went through all classes in `utility-classes` with other FE devs and made decisions. Many tickets were created off the back of that, all of them listed as TODOs in the file itself.
I've cleaned up some classes as well, see commits for individual details.
We know that there are other utility classes in other files, such as `typography.ts`, but will attack these as part of a wider design system review.
> Document and cleanup utility classes

- common/views/components/PageHeader/PageHeader.tsx
- common/views/components/SearchForm/SearchForm.tsx
- common/views/themes/utility-classes.ts
- content/webapp/components/BookPromo/BookPromo.tsx
- content/webapp/components/ImageGallery/ImageGallery.tsx
> Replace the single-line .relative class with inline-styles everywhere

- common/views/components/ApiToolbar/index.tsx
- common/views/components/WatchLabel/WatchLabel.tsx
- content/webapp/components/EventDateRange/EventDateRange.tsx
- content/webapp/components/EventPromo/EventPromo.tsx
- content/webapp/components/EventSchedule/EventBookingButton.tsx
- content/webapp/components/EventSchedule/EventSchedule.tsx
- content/webapp/components/EventSchedule/EventScheduleItem.tsx
- content/webapp/components/EventbriteButtons/EventbriteButtons.tsx
- content/webapp/pages/books/[bookId].tsx
- content/webapp/pages/events/[eventId].tsx
- content/webapp/pages/guides/exhibitions/[id]/[type].tsx
- content/webapp/pages/guides/exhibitions/[id]/index.tsx
- content/webapp/pages/guides/exhibitions/index.tsx
Chipping away at https://github.com/wellcomecollection/wellcomecollection.org/issues/8420
> Various code tidies: fix some event weirdness and clean up some one-line flex classes

- common/views/components/ButtonSolidLink/ButtonSolidLink.tsx
- content/webapp/pages/events/[eventId].tsx
☝️ 
part of #9471 
Fairly sure these were the last ones to have slipped the net.
> Add data-gtm-triggers to ButtonSolidLink

- catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx
- catalogue/webapp/components/WorkDetailsSection/WorkDetailsSection.tsx
- common/views/components/Tasl/Tasl.tsx
- content/webapp/components/BookPromo/BookPromo.tsx
- content/webapp/components/DateAndStatusIndicator/DateAndStatusIndicator.tsx
- content/webapp/components/FeaturedText/FeaturedText.tsx
- content/webapp/components/MediaObjectBase/MediaObjectBase.tsx
- content/webapp/components/PageHeaderStandfirst/PageHeaderStandfirst.tsx
I've been gradually building these up locally as I read different files, putting them all in one PR so I can get back to a clean working tree.
> Make a bunch of miscellaneous code tidies

- common/views/themes/default.ts
Me wanting Chromatic to build
Hopefully does the above.
> Change spelling in hopes of launching chromatic build

- catalogue/webapp/components/WorkDetailsText/WorkDetailsText.tsx
users of the site that don't want font ligatures in works details
closes #9477
> remove font-ligatures from works detail text

- catalogue/webapp/components/WorkLink/index.tsx
- catalogue/webapp/components/WorksSearchResult/WorksSearchResult.styles.tsx
- catalogue/webapp/components/WorksSearchResult/WorksSearchResult.tsx
- catalogue/webapp/components/WorksSearchResults/WorksSearchResults.tsx
- yarn.lock
Related to [9544](https://github.com/wellcomecollection/wellcomecollection.org/pull/9544)
- Does what https://github.com/wellcomecollection/wellcomecollection.org/pull/9544 aims to do, but offering the alternative to use css selectors instead of passing in properties for styling. This is for @AMBacelar to decide/confirm it still does what it should.
> Remove legacyBehaviour from link

- catalogue/webapp/components/WorkLink/index.tsx
- catalogue/webapp/components/WorksSearchResult/WorksSearchResult.styles.tsx
- catalogue/webapp/components/WorksSearchResult/WorksSearchResult.tsx
- catalogue/webapp/components/WorksSearchResults/WorksSearchResults.tsx
- yarn.lock
Reverts wellcomecollection/wellcomecollection.org#9621
> Revert "Remove legacyBehaviour from link"

- cardigan/stories/components/Cards/Cards.stories.tsx
> Test Chromatic delays in Cards

- cardigan/stories/content.ts
> Don't lie about image height

- catalogue/webapp/components/CopyUrl/CopyUrl.tsx
- catalogue/webapp/components/IIIFClickthrough/IIIFClickthrough.tsx
- catalogue/webapp/components/WorkDetails/WorkDetails.tsx
- catalogue/webapp/pages/works/[workId]/items.tsx
- common/views/components/NewsletterPromo/NewsletterPromo.tsx
- content/webapp/components/NewsletterSignup/NewsletterSignup.tsx
Data analysts 
Include `data-gtm-trigger` attributes for the more obvious outstanding things we want to track in GTM
> Add triggers for straightforward tracking

- common/views/components/Pagination/Pagination.tsx
Users of the search sections of the website, and would like to quickly jump to a page without messing with the URL
This PR provides those users with an input field in the pagination component
closes #9508
> Implement text box for jump to page

- catalogue/webapp/components/SearchFilters/SearchFilters.Desktop.DynamicFilters.tsx
**I'd invite anyone reviewing this to run it locally and test it, I've done my own tests, but this was a peculiar one and could use extra checks on a different screen as that's how we found out about it in the first place.**
All search users
Any filter that is preselected (in the URL query) but not displayed on desktop (because of a smaller screen), won't get submitted on the next form submit when filtering further.
1. On the widest screen, filter with a language on https://wellcomecollection.org/search/works
2. Resize your screen so some filters still display but the Language ones disappears
3. Select a Location
4. See the language disappear from your search.
5. This happens only on desktop because of the behaviour of filters only displaying a limited amount based on screen size. The …
> Allow all filters to stay in form but hidden if filters wrapper too long

- assets/humans.txt
Added Georgia to Digital Platform 😇 
All humans
Letting them know who we are
> added Georgia to wc humans

- common/views/components/PageLayout/PageLayout.tsx
Following @rcantin-w’s review comment on https://github.com/wellcomecollection/wellcomecollection.org/pull/9661 – this seems to work, so let's write it down.
> Add a comment about <Script>

- pa11y/webapp/write-report.js
[We don't use these any more](https://github.com/wellcomecollection/wellcomecollection.org/issues/6065)
> remove redundant query params from test url

- common/views/components/UserProvider/UserProvider.tsx
- identity/webapp/babel.config.js
- identity/webapp/jest.config.js
- identity/webapp/package.json
- identity/webapp/pages/index.tsx
- identity/webapp/src/frontend/jest-setup.ts
- yarn.lock
Implemented the fix as given in https://github.com/auth0/nextjs-auth0/pull/791
https://github.com/auth0/nextjs-auth0/pull/791
> Bump @auth0/nextjs-auth0 to 2.4.0

- assets/humans.txt
> Adding Ezra

- cardigan/stories/components/BookPromo/BookPromo.stories.tsx
- cardigan/stories/components/Cards/Cards.stories.tsx
- cardigan/stories/components/PageHeader/PageHeader.stories.tsx
Chromatic
A pixel difference was found again, so bringing it back up to `0.2`.
> Bring back diffThreshold to 0.2

- common/views/components/SegmentedControl/SegmentedControl.tsx
> Add visually-hidden 'close' text for segmented control close button

- content/webapp/components/EventSchedule/EventBookingButton.tsx
> Add attribute for click_to_book trigger

- common/views/components/SegmentedControl/SegmentedControl.tsx
Fixes #7780 
People who want a clean pa11y dashboard.
Recommend turning on whitespace only changes to review.
Next up – rewrite this component as a FunctionComponent so we end up scratching our heads less when things don't work the way we expect them to.
> Make sure there's JS before we put the buttons on the page

- catalogue/webapp/components/IIIFViewer/ViewerStructures.tsx
- content/webapp/pages/articles/[articleId].tsx
In particular styled-components seems unhappy about dynamically created components; components created inside other components.  Moving these to the top-level of their respective files seems to fix it.
> Fix some warnings from styled-components about nesting

- catalogue/webapp/pages/search/stories.tsx
- common/data/segment-values.ts
If nothing else this is an absolutely perfect example of why Typescript is so useful!
> Fix types for stories search, resolving API toolbar issue

- common/views/components/NewsletterPromo/NewsletterPromo.tsx
☝️ 
Discovered this when working on #9638
It feels less shameful? So I renamed the wrapper.
> Base NewsletterPromo button height on input height

- cache/edge_lambdas/src/toggler.ts
- content/webapp/pages/stories/index.tsx
- toggles/webapp/toggles.ts
> Stick with A condition after comics A/B test

- common/views/components/SegmentedControl/SegmentedControl.tsx
- content/webapp/components/EventsByMonth/EventsByMonth.tsx
Devs (for context, I did this because the component was relatively hard to reason about for something fairly straightforward in terms of what it does, and it did a good job of hiding an accessibility issue from us as a result).
Bringing the SegmentedControl up to date
- Makes it a function component
- Removes (non-utility) classes
> Segmented control updates

- catalogue/webapp/pages/concepts/[conceptId].tsx
- content/webapp/components/EventsByMonth/EventsByMonth.tsx
Follows #9733; other code tidies that didn't fit into that bugfix.
> Small cleanups and tidies in the EventsByMonth component

- content/webapp/services/prismic/fetch/index.ts
- content/webapp/services/prismic/fetch/multi-content.ts
Fixes press releases on the press page.
> Also use the shared client-side fetcher for multicontent

- catalogue/webapp/components/IIIFViewer/ViewerSidebar.tsx
- catalogue/webapp/components/VisuallySimilarImagesFromApi/VisuallySimilarImagesFromApi.tsx
- catalogue/webapp/components/WorkHeader/WorkHeader.tsx
- common/views/components/Header/Header.tsx
- common/views/components/NewsletterPromo/NewsletterPromo.tsx
- content/webapp/components/Body/VisitUsStaticContent.tsx
- content/webapp/components/EventCard/EventCard.tsx
- content/webapp/components/EventPromo/EventPromo.tsx
- content/webapp/components/EventSchedule/EventScheduleItem.tsx
- content/webapp/components/ExhibitionGuidePromo/ExhibitionGuidePromo.tsx
- content/webapp/components/FeaturedCard/FeaturedCard.tsx
- content/webapp/pages/events/[eventId].tsx
- identity/webapp/src/frontend/MyAccount/ChangeEmail.tsx
General maintenance
Simplifies font declaration when it doesn't need to be inside a string.
> Simplify classnames when just font

- common/views/components/SegmentedControl/SegmentedControl.tsx
- content/webapp/components/EventsByMonth/EventsByMonth.tsx
This is hopefully the final bit of refactoring/clean-up in these components today. 🤞
> Improve the readability of the EventsByMonth and SegmentedControl components

- cardigan/stories/components/Cards/Cards.stories.tsx
maintenance
Forgotten some comments when I was testing the `delay` parameter, this just cleans it up.
> Remove delay comments

- common/views/components/SegmentedControl/SegmentedControl.tsx
- content/webapp/components/EventsByMonth/EventsByMonth.tsx
People who want the ui to reflect the url
Displaying the appropriate events if there is a date hash on the What's On page
> Set activeId in SegmentedControl

- common/views/components/SegmentedControl/SegmentedControl.tsx
- common/views/themes/utility-classes.ts
Maintenance and alignment
Part of #8420 , decided with the team and approved by Dom, going with square corners to match the new inputs and buttons. The class was only used in the one component.
> Remove rounded-diagonal class and styles

- cache/locals.tf
Content team
Applies requested redirect to production (see ticket)
Closes #9765
> Apply lambda 119 for new redirect

- common/views/components/Pagination/Pagination.tsx
users of the platform that want to jump to a page
not break the form by sending multiple page fields to the form
> only focused input field submits to the form

- catalogue/webapp/pages/search/stories.tsx
Following on from https://github.com/wellcomecollection/content-api/pull/49
> Use the updated stories sort key for publication date

- common/views/themes/utility-classes.ts
- content/webapp/components/BannerCard/BannerCard.tsx
- content/webapp/components/BookPromo/BookPromo.tsx
- content/webapp/components/Card/Card.tsx
- content/webapp/components/EventPromo/EventPromo.tsx
- content/webapp/components/ExhibitionGuidePromo/ExhibitionGuidePromo.tsx
- content/webapp/components/ExhibitionPromo/ExhibitionPromo.tsx
- content/webapp/components/FacilityPromo/FacilityPromo.tsx
- content/webapp/components/FeaturedCard/FeaturedCard.tsx
- content/webapp/components/StoryPromo/StoryPromo.tsx
Maintenance
- Removes utility class. 
- Created `CardTitle` as 90% of them had the same properties
I tested everywhere I could think of and behaviour is unchanged.
Related to #9561
> Refactor promo-link usage

- content/webapp/services/prismic/types/filters.ts
This matches the new version in getExhibitionFilters, and imo is a bit easier to read.
> Use a switch statement in getEventFilters

- playwright/test/view-items.test.ts
Not the one that is failing in buildkite, but was consistently failing locally for me without this change
> trying to make test less flaky

- common/next/next.config.js
fixing the redirects issue by implementing rewrites
> initial commit

- content/webapp/pages/visual-stories/index.tsx
- toggles/README.md
- toggles/webapp/toggles.ts
folks wanting to see the visual stories prototype
Allowing us to see and share a visual stories prototype
The toggle has been deployed already.
Closes #9842
> Created visual stories toggle

- content/webapp/components/VisualStories/VisualStories.data.tsx
- content/webapp/components/VisualStories/VisualStories.styles.tsx
- content/webapp/components/VisualStories/VisualStories.v1.tsx
- content/webapp/components/VisualStories/VisualStories.v2.tsx
- content/webapp/components/VisualStories/index.tsx
- content/webapp/pages/visual-stories/v1.tsx
- content/webapp/pages/visual-stories/v2.tsx
Myself and @davidpmccormick
Allows us to work together but separately on visual story prototypes.
> Basic structure for coworking on VS prototypes

- .buildkite/pipeline.e2e-universal.yml
> Don't retry the end-to-end tests automatically

- catalogue/webapp/components/IIIFViewer/ViewerTopBar.tsx
> show downloads if there is no iiifManifest

- content/webapp/components/VisualStories/VisualStories.styles.tsx
- content/webapp/components/VisualStories/VisualStories.v2.tsx
Visual Stories
Changes in line with our catchup this morning.
> VS: V2, align adjustments and cleanup TODOs

- .buildkite/scripts/trigger-e2e.sh
For people who want to live dangerously
> Allow failure of e2e tests

- playwright/test/view-items.test.ts
Follow up to https://github.com/wellcomecollection/wellcomecollection.org/pull/9897
This test was [failing in mobile tests](https://buildkite.com/wellcomecollection/wc-dot-org-end-to-end-tests/builds/2951#01888af7-0fbc-44a1-a94a-d87319094be6), only in prod (passed staging 🤷‍♀️ )
> E2E: Comment out more tests

- content/webapp/components/VisualStories/VisualStories.styles.tsx
- content/webapp/components/VisualStories/VisualStories.v1.tsx
- content/webapp/components/VisualStories/VisualStories.v2.tsx
Visual Stories
Based on various chats [we came to the decision not to have a yellow box for this section](https://github.com/wellcomecollection/wellcomecollection.org/issues/9903#issuecomment-1578411040), _for now_.
> Remove yellow box

- README.md
Devs/new joiners
Adds more details to README based on recent-ish addition of `yarn run-concurrently` and `stylelint`
> Changes to main README based on recent changes

- common/data/hardcoded-ids.ts
Content
There is a new version of this page, Content will archive the older one once this is through.
[Slack convo here](https://wellcome.slack.com/archives/C3N7J05TK/p1686131844613639)
> Change Getting Here URL

- content/webapp/components/Body/Body.tsx
- content/webapp/services/prismic/transformers/body.ts
- content/webapp/services/prismic/types/body.ts
- content/webapp/types/body.ts
- prismic-model/src/parts/body.ts
- prismic-model/src/parts/table.ts
Reverts wellcomecollection/wellcomecollection.org#9939
> Revert "Remove table slice"

- common/views/components/styled/SpacingComponent.tsx
Devs
Giving them one less class to maintain
> Remove unnecessary spacing-component class

- catalogue/webapp/components/IIIFViewer/IIIFViewer.tsx
Fixes [Safari bug discussed in Slack](https://wellcome.slack.com/archives/C8X9YKM5X/p1686817618588549)
- We need to reset the MainAreaWidth and MainAreaHeight in the viewer when the available space for it changes.
- This can happen when the browser is resized or if the sidebar is collapsed/expanded.
- When the  MainAreaWidth and MainAreaHeight change we reload the viewer, so that it fills the available space.
- We use the ResizeObserver on the mainAreaRef.current, which takes care of both these scenarios.
- However, in Safari when 'Show scroll bars' was set to always in the system settings this would cause the viewer would constantly reload itself as the resize observer seemed to get stuck in an infinite loop
- instead of using the resizeObserver on the MainArea, we now reset the …
> Fixing infinite loading bug in Safari

- catalogue/webapp/pages/api/works/[workId].tsx
- catalogue/webapp/pages/api/works/items/[workId].tsx
- dash/webapp/pages/toggles.tsx
- toggles/webapp/deploy.test.ts
- toggles/webapp/deploy.ts
- toggles/webapp/toggles.ts
For https://github.com/wellcomecollection/wellcomecollection.org/issues/9847
Anybody looking at the list of toggles.
Making it easier to see whether a given toggle is a permanent fixture or for a temporary test.
> Add headings to distinguish between permanent/experimental toggles

- catalogue/webapp/components/WorkDetails/WorkDetails.tsx
Artists whose work is being taken credit for by us right now!
Relates to #9964 
Hides it for those works, this is a total hack and we'll create a ticket right away to think of a better solution and remove the hack ASAP.
> Hack to hide "can i use this" for certain works

- catalogue/webapp/components/IIIFSearchWithin/IIIFSearchWithin.tsx
- catalogue/webapp/components/IIIFViewer/GridViewer.tsx
- catalogue/webapp/components/IIIFViewer/IIIFCanvasThumbnail.tsx
- catalogue/webapp/components/IIIFViewer/NoScriptViewer.tsx
> Invalid markup thumbnails

- content/webapp/services/prismic/transformers/body.ts
- content/webapp/services/prismic/types/body.ts
Future devs
Explains the gist of what I found out when working on #9925 and possibly helps future devs navigate these specific slices.
Added a wishful to do for one day when we have time on our hands or figure out how to automate this migration with Prismic.
> Add comments to explain quote/quotev2 and add a TODO

- playwright/url-checker/check-url.ts
Explicitly wait for the async event handler to finish before closing the page
> Fix race condition in URL checker

- catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx
- catalogue/webapp/components/VisuallySimilarImagesFromApi/VisuallySimilarImagesFromApi.tsx
Users of the image search modal that like to search through similar images
gives them a working url history so that they can traverse their browser history with the modal open
#8350
> Set up image modal routing

- cache/edge_lambdas/src/redirector.test.ts
- cache/edge_lambdas/src/redirects.ts
Reverts wellcomecollection/wellcomecollection.org#9959
> Revert "set redirect for the global search from identity app"

- prismic-model/README.md
- prismic-model/src/parts/visual-story-body.ts
- prismic-model/src/visual-stories.ts
Visual Story/Prismic devs
Relates to #9975, following its definition of done:
- Updated the Readme with a new section on creating new types and deleting existing ones 
- Created a WIP Visual Story custom type
> Updated README for new types and a WIP visual story type

- content/webapp/services/prismic/fetch/exhibitions.test.ts
Tests
From what I understood from the comments, we need to stay on top of new exhibitions and add them here? It makes the tests fail currently, so there it is.
> Add new exhibition to test results

- prismic-model/src/parts/visual-story-body.ts
Editors
Adding a Text and icons (side-by-side) slice
Relates to #9977
> Text and icons slice

- catalogue/webapp/utils/iiif/v3/index.ts
> Fix viewer error

- common/views/components/AudioPlayer/AudioPlayer.PlayRate.tsx
- common/views/components/AudioPlayer/AudioPlayer.Scrubber.tsx
- common/views/components/AudioPlayer/AudioPlayer.Volume.tsx
- common/views/components/AudioPlayer/AudioPlayer.formatters.tsx
- common/views/components/AudioPlayer/AudioPlayer.tsx
Devs
The file was getting quite complex, so I thought I'd go the way of bigger components and split it in subfiles to facilitate readability and understanding.
I've not really changed anything apart from renaming `formatTime` to `formatPlayerTime` as there is another `formatTime` in utils that has to do with dates.
> Split AudioPlayer in subfiles

- catalogue/webapp/components/StoriesGrid/index.tsx
- catalogue/webapp/pages/search/index.tsx
Users of the stories/search pages.
providing consistent UI across devices
> stories section on search overview should be scrolling on mobile

- content/webapp/components/ContentPage/ContentPage.tsx
Polly experiment
Change heading as requested by Dom, add audio to [History of condoms](https://wellcomecollection.org/articles/W88vXBIAAOEyzwO_) 
Also just added it for [Nymphomania and hypersexuality in women and men](https://wellcomecollection.org/articles/W_v8XxQAACgA_WKS)
> Polly: Change heading, add one audio

- prismic-model/src/parts/visual-story-body.ts
> Add standfirst to visual-stories body

- prismic-model/src/parts/visual-story-body.ts
> Add heading3 to TextAndImageOrIcons slices

- content/webapp/components/ContentPage/ContentPage.tsx
Polly experiment
Adds audio to:
- [The side effects of lithium mining](https://wellcomecollection.org/articles/YTdnPhIAACIAGuF3)
- [Drugs in Victorian Britain](https://wellcomecollection.org/articles/W87wthIAACQizfap)
- [Race, religion and the Black Madonna](https://wellcomecollection.org/articles/WpmW_yUAAKUUF6mV)
Added the missing ones and the why, just to keep better track, still working on those but I'd like to merge to get feedback on the Black Madonna one, where there is a lot of copy in image captions that aren't part of the audio.
> Polly; Add more text to speech instances

- content/webapp/components/ContentPage/ContentPage.tsx
Polly experiment
Relates to #10031 
Added missing articles and updated the first two that were added to they're built on the same model.
- Quotes slices are read with Amy's newscaster voice
- Quotes in rich text are read as is, same as the rest of the text.
- Text in single quotes is also read as is, there is no added emphasis.
> Polly; Added missing audios

- cache/modules/cloudfront_policies/cache_policies.tf
- cache/modules/cloudfront_policies/outputs.tf
- cache/modules/wc_org_cloudfront/distribution.tf
Should fix issues with image inconsistencies
> Props routes should use every query param as a cache key

- common/views/components/Contact/Contact.V2.tsx
Design
[Based on feedback in Slack](https://wellcome.slack.com/archives/C054304EVL5/p1690963431805379) after changing the icons to the proper SVGs.
> Contact V2: Remove labels and tidy up

- content/webapp/utils/reading-time.ts
☝️ 
[Flagged in Slack](https://wellcome.slack.com/archives/C8X9YKM5X/p1691404728539129)
__before__
__after__
> Don't show reading time if it's 0 minutes

- catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx
- catalogue/webapp/components/MediaAnnotations/MediaAnnotations.tsx
- catalogue/webapp/components/Work/Work.tsx
- catalogue/webapp/pages/search/images.tsx
- catalogue/webapp/pages/works/[workId]/images.tsx
- content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx
- content/webapp/pages/exhibitions/[exhibitionId].tsx
- content/webapp/pages/guides/exhibitions/[id]/index.tsx
- content/webapp/pages/index.tsx
- content/webapp/pages/stories/[contentType].tsx
- content/webapp/services/prismic/transformers/json-ld.ts
- content/webapp/utils/event-series.ts
- content/webapp/utils/page-header.tsx
Good functioning
Spotted a few incomplete paths, they seemed to work fine but sometimes this does seem to break builds, so thought I'd find them all and complete them.
> Add missing parts of path in imports

- cache/modules/lambda/variables.tf
- cache/terraform.tf
- catalogue/terraform/locals.tf
- catalogue/terraform/main.tf
- catalogue/terraform/stack/data.tf
- catalogue/terraform/stack/locals.tf
- catalogue/terraform/stack/variables.tf
- content/terraform/locals.tf
- content/terraform/main.tf
- content/terraform/stack/data.tf
- content/terraform/stack/locals.tf
- content/terraform/stack/variables.tf
- identity/terraform/locals.tf
- identity/terraform/main.tf
- identity/terraform/stack/data.tf
- identity/terraform/stack/locals.tf
- identity/terraform/stack/variables.tf
- infrastructure/experience/locals.tf
- infrastructure/experience/terraform.tf
for https://github.com/wellcomecollection/aws-account-infrastructure/issues/2
> Fix the locations of the remote state of the AWS account Terraform

- content/webapp/components/EventSchedule/EventBookingButton.tsx
- content/webapp/components/EventbriteButtons/EventbriteButtons.tsx
- content/webapp/services/prismic/transformers/events.test.ts
- content/webapp/services/prismic/transformers/events.ts
Reverts wellcomecollection/wellcomecollection.org#10083
Just noticed that Jenn asked for a hold on this in the ticket, so reverting
> Revert "Add aff parameter to Eventbrite URLs"

- catalogue/webapp/components/IIIFViewer/Thumbnails.tsx
- playwright/test/view-items.test.ts
Devs and testing
Relates to #9898
We had commented out some e2es that flaked out repeatedly (and sometimes passed, so it didn't seem to be because they _should_ be failing). Now that we have e2es in PRs, I'm curious to try them out again.
> Uncomment commented e2es

- content/webapp/components/ZoomedPrismicImage/ZoomedPrismicImage.tsx
☝️ 
[Slack conversation](https://wellcome.slack.com/archives/C054304EVL5/p1692283448312589?thread_ts=1692282112.333929&cid=C054304EVL5)
> Only track zoom in on Prismic images

- prismic-model/src/exhibitions.ts
relates to #10161
Now I'm rendering the content I've realised these changes should be made
> rename and add fields

- assets/humans.txt
> Remove Dom from humans.txt

- content/webapp/components/ContentPage/ContentPage.tsx
- toggles/webapp/toggles.ts
Maintenance, end of experiment
Relates to #10172 
This should cover it all, I'll deploy the toggle removal once approved.
> Remove polly integration and toggle

- content/webapp/services/prismic/transformers/exhibitions.ts
Fixes https://wellcome.slack.com/archives/CQ720BG02/p1694769819296629
> check for pdfs before mapping

- playwright/test/search-images.test.ts
- playwright/test/search.test.ts
E2es
Fixes them, we found out that there might be a need for an extra "wait for results" needed + the first image in the GREEN filter is broken, which was causing tests to fail, so we're going with Red.
[View Slack convo](https://wellcome.slack.com/archives/C3TQSF63C/p1694767658604469)
> Fix search tests

- common/views/components/AudioPlayer/AudioPlayer.tsx
- common/views/components/VideoEmbed/VideoEmbed.tsx
- content/webapp/components/SoundCloudEmbed/SoundCloudEmbed.tsx
Users
Ensures the button doesn't show for nothing!
> Better conditional to display transcript CTA

- content/webapp/services/prismic/transformers/json-ld.ts
- content/webapp/services/prismic/transformers/multi-content.ts
- content/webapp/utils/json-ld.ts
For https://github.com/wellcomecollection/platform/issues/5734
> Clarify a couple of outstanding TODO comments

- content/webapp/components/WorkDetails/WorkDetails.tsx
Licence/credit work
Relates to #10220 and #10223 
Final format as agreed on with Jenn.
I'll remove the toggle once this is in production.
> Remove former credit section

- assets/humans.txt
> Remove Danny, Jenn, Jonathan, Alex

- cardigan/stories/components/ArchiveTree/ArchiveTree.stories.tsx
- cardigan/stories/components/Map/Map.stories.tsx
- common/services/prismic/link-resolver.ts
- content/webapp/components/Body/Body.tsx
- content/webapp/components/Exhibition/Exhibition.tsx
- content/webapp/components/IIIFViewer/ViewerTopBar.tsx
- content/webapp/components/ImageGallery/ImageGallery.tsx
- content/webapp/pages/guides/exhibitions/index.tsx
- content/webapp/pages/visual-stories/index.tsx
- content/webapp/pages/visual-stories/v1.tsx
- content/webapp/pages/visual-stories/v2.tsx
- content/webapp/services/wellcome/content/types/api.ts
- prismic-model/src/interpretation-types.ts
Maintenance
Removes TODOs that aren't needed anymore. A few files needed some linting as well.
> Remove dead TODOs and lint

- .eslintrc.js
Devs
Using the system that should be running on everyone's setup to add empty new lines to the end of files
> Handle adding newlines to end of files with eslint

- assets/humans.txt
> added Jason to humans.txt :)

- content/webapp/__mocks__/events.ts
- content/webapp/__mocks__/whats-on.ts
- content/webapp/components/CardGrid/DailyTourPromo.tsx
- content/webapp/components/IIIFViewer/Padlock.tsx
- content/webapp/services/prismic/transformers/body.test.ts
- content/webapp/services/wellcome/catalogue/fixtures/works-aggregations.ts
- content/webapp/test/services/prismic/transformers/contributors.test.ts
- content/webapp/test/works.test.ts
Maintenance
Fixes some type errors in tests... Few questions though:
- How much do we care about keeping them up to date?
- Would it be nice to have them centralised? Cardigan also has mock events, articles, etc. Could be useful for them to be shared?
- If we do care - how do we get them to flag so we remember to update them?
I couldn't fix all of them because honestly I didn't understand all of them, there are 5 files still erroring, which is why I'm asking the above as well.
> Fix some types in tests

- common/services/prismic/opening-times.ts
Maintenance
Addresses TODO; confirmed with Editorial this is what we wanted and documented it.
https://wellcome.slack.com/archives/C3N7J05TK/p1696865822958259
> Confirm opening hours timings

- common/server-data/toggles.ts
- dash/webapp/pages/toggles.tsx
- toggles/webapp/toggles.ts
Fixes #10204
Adds 'stage' as a possible toggle type - these will only work on stage, otherwise they are filtered out.
Adds 'stage' toggles to the toggles dashboard
> Staging toggles

- assets/humans.txt
> Remove Adi from humans.txt

- content/webapp/pages/visual-stories/[visualStoryId].tsx
- content/webapp/services/prismic/transformers/visual-stories.ts
- content/webapp/types/visual-stories.ts
Users
Relates to #10300 
Returns relevant values to create breadcrumbs if they are needed.
> Visual story breadcrumbs

- playwright/test/visual-stories.test.ts
devs, e2es
We're changing the test as part of #10323 and we're still changing the data as part of #10328 so as it's breaking the e2e, we're just removing it for now
> Remove VS test for now

- content/webapp/components/Exhibition/Exhibition.tsx
- content/webapp/components/styled/AccessResources.ts
- content/webapp/pages/events/[eventId]/index.tsx
- content/webapp/services/prismic/fetch/events.ts
> Event visual story link

- dash/webapp/pages/index.tsx
- dash/webapp/pages/prismic-linting.tsx
Making SC6 work
Make props transient (forgotten from #10352)
> Fix dash types

- content/webapp/services/wellcome/catalogue/filters.test.ts
- content/webapp/services/wellcome/catalogue/filters.ts
Everyone
Fixing the problem where matType and language codes are appearing in filters.
https://wellcome.slack.com/archives/C8X9YKM5X/p1699029157427519
> Fix: Worktype (and language) codes showing

- cardigan/stories/global/palette/palette.stories.tsx
> Include 'focus' subsection in palette config so that it doesn't break in Cardigan

- .buildkite/pipeline.yml
- updown/README.md
- updown/expected-checks.ts
- updown/yarn.lock
Devs
Update yarn lock (current one is 2yrs old)
Add a concept page to updown checks
Update readme for which command line to run
> Add a concept page and update readme

- toggles/webapp/toggles.ts
Devs to work on #10455 
Relates to #10454 
Adds the toggle
> Add events search toggle

- playwright/test/events.test.ts
> events e2e refactor

- updown/expected-checks.ts
Relates to #10079 
Adds visual story page to updown checks
> Add a visual story to updown

- .buildkite/urls/expected_200_urls.txt
Relates to #10079 
Adds a visual story page to URL checker e2e test.
> Add visual story to URL checker

- toggles/webapp/toggles.ts
Devs
@agnesgaroux and I thought it was just for the Catalogue Api based on the description but it also covers the Content Api.
Already deployed.
> Change stagingApi toggle description

- cache/modules/wc_org_cloudfront/waf.tf
I didn't run a plan for https://github.com/wellcomecollection/wellcomecollection.org/pull/10482 so got this wrong. Already applied.
> Fix terraform types

- assets/humans.txt
Humans.
Updating the humans.txt to reflect which humans are where :)
> Move Robert Kenny from Alumni to current

- content/webapp/services/prismic/types/images.mocks.ts
- content/webapp/test/services/prismic/transformers/contributors.test.ts
Maintenance
Prismic Images have two new fields so added them in mocks so they wouldn't error...  #10289 would be very useful to do for maintenance ease, but here we go in the meantime.
> Add new fields to mock Images

- .buildkite/e2e_on_pull_requests/deploy_to_e2e_environment.sh
- .buildkite/e2e_on_pull_requests/pipeline.e2e-pull-requests.yml
- .buildkite/e2e_on_pull_requests/set_desired_task_count.sh
- .buildkite/pipeline.yml
- .buildkite/scripts/deploy_all_apps.sh
- docker-compose.yml
Stage deployment pipeline
This issue: https://github.com/wellcomecollection/wellcomecollection.org/issues/10168
Terraform was applied but the changes to the deployment pipeline were not
https://github.com/wellcomecollection/wellcomecollection.org/pull/10169/files
> remove catalogue from deploy_all_apps script

- playwright/url-checker/check-url.ts
This might fix the flaky URL checker tests, which are failing when they try to read a request after the page has been closed. We already had logic for preventing this, but it wasn't being used in all cases.
> Always close the page safely when exiting the URL checker

- common/data/microcopy.tsx
- common/views/components/Header/Header.tsx
- common/views/components/SearchForm/SearchForm.tsx
- content/webapp/components/SearchPageLayout/SearchNavigation.tsx
Events search
- Add missing label in `microcopy`
- Rename array as it's no longer placeholders but proper labels.
> Add missing search label for events

- assets/humans.txt
Humans who want to know who's worked on this project.
Letting them know who worked on the project :)
> Add Jonathan Cates to humans.txt

- identity/webapp/package.json
- identity/webapp/pages/api/users/[[...users]].ts
- identity/webapp/src/utility/auth0.ts
- yarn.lock
Reverts wellcomecollection/wellcomecollection.org#10367
I can't change my email and password. Should've checked before it was doable in staging, my bad, will revert, test and try again.
> Revert "Bump @auth0/nextjs-auth0 from 2.7.0 to 3.2.0 in /identity/webapp"

- common/utils/cookie-consent.ts
- common/views/pages/_document.tsx
Devs trying to understand behaviour in staging
Adds logs.
> Consent cookie logging

- content/webapp/components/ConceptLink/index.tsx
- content/webapp/components/SearchPagesLink/Works.tsx
- content/webapp/components/WorkDetails/index.tsx
- content/webapp/pages/concepts/[conceptId].tsx
- content/webapp/pages/search/works.tsx
relates to #10650
adds the sourcePath value to more links
> Tracking sourcePath

- content/webapp/components/WorkDetails/WorkDetails.DownloadList.tsx
- content/webapp/types/compressed-manifest.ts
- content/webapp/types/manifest.ts
- content/webapp/utils/iiif/v3/index.ts
For #10607 
If the file size is available we can display it
> Born digital file size

- common/data/segment-values.ts
- common/services/conversion/track.ts
- content/webapp/components/ConceptLink/index.tsx
- content/webapp/components/ExpandedImage/ExpandedImage.tsx
- content/webapp/components/ImageCard/ImageCard.tsx
- content/webapp/components/ImageLink/index.tsx
- content/webapp/components/ItemLink/index.tsx
- content/webapp/components/SearchPagesLink/Works.tsx
- content/webapp/components/WorkDetails/index.tsx
- content/webapp/components/WorkLink/index.tsx
- content/webapp/components/WorksSearchResult/WorksSearchResult.tsx
- content/webapp/pages/concepts/[conceptId].tsx
- content/webapp/pages/search/works.tsx
Relates to #10642
After discussing with @taceybadgerbrook we're appending the path to the source
> remove sourcePath property and append the string to the source

- content/webapp/components/ExhibitionGuideLinks/ExhibitionGuideLinks.tsx
Updates the text for captions and transcripts link, as requested by Helen:
https://wellcome.slack.com/archives/C8X9YKM5X/p1709129153298469
> update text for captions and transcripts

- common/services/app/civic-uk/scripts.tsx
Civic UK integration
The test apiKey doesn't work (`Sorry, this API key is not valid.\nPlease contact Civic at queries@civicuk.com.\`) so let's use our new one!
> Apply new license settings Civic UK

- common/data/segment-values.ts
- content/webapp/components/WorkDetails/index.tsx
⬆️ 
As requested by @taceybadgerbrook : https://github.com/wellcomecollection/wellcomecollection.org/pull/10671#issuecomment-1969184262
> Append path to item page link source property

- content/webapp/components/IIIFSearchWithin/IIIFSearchWithin.tsx
- playwright/test/view-items.test.ts
Make e2es Relevant Again
Change what we're testing on based on what we want to know. Top pagination seems flakey at best and we've tried everything we could think about - there are other ways to test them. Follows up #10646 which will be closed as this is a lot simpler.
> View items e2e; Change what we're testing on problematic tests

- content/webapp/components/IIIFSearchWithin/IIIFSearchWithin.tsx
- content/webapp/components/IIIFViewer/ViewerSidebar.tsx
- content/webapp/components/Tabs/Tabs.Navigate.tsx
- content/webapp/components/ToolbarSegmentedControl/ToolbarSegmentedControl.tsx
- playwright/test/helpers/search.ts
- playwright/test/helpers/utils.ts
- playwright/test/search.test.ts
- playwright/test/view-items.test.ts
Maintenance
This is just some tidying I did as part of #10646, which we'll close and decided we'd fix a different way. I wanted to keep these in but as they're not related to the actual fixing of the flakiness, I thought I'd submit a separate PR for them. See different commits for what was done.
~~The change in `/IIIFSearchWithin.tsx`: That test-id isn't currently used, but will be in my next PR, so no change is needed elsewhere for it, but now it works with `getByTestId()`~~ this actually ended up getting removed in child PR #10677 but don't worry about it either way
> Playwright tidy

- .github/workflows/chromatic.yml
- common/services/app/civic-uk/index.ts
Cookie work
Noticed this miss; the value is a string, so this condition would resolve `"false"` to `true` . It doesn't affect generic users as they wouldn't have it and therefore it would've been `undefined`, which resolves to false. It's just annoying for those of us who do have it and want to test properly 😄  (and we can't use `useToggles()` here as this should support server side calls as well)
> Have cookieWork check actually work

- cache/modules/cloudfront_policies/locals.tf
Future devs
Missed [this good suggestion in a previous PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/10682#pullrequestreview-1911437211), so adding now. Lmk if not clear enough.
> Add comment to explain CookieControl

- toggles/webapp/toggles.ts
This has been [deployed](https://toggles.wellcomecollection.org/toggles.json) and is available for use as `toggle_sliceMachine`
> Add slice machine toggle

- common/services/app/civic-uk/scripts.tsx
- common/views/pages/_app.tsx
Cookie work and ticket #10673 
[Designs can be found here](https://www.figma.com/file/N76hkJsMkSb2O6ToyQPxax/Cookie-journeys-update?node-id=1718%3A84945&mode=dev) but are more for inspiration than perfect copying in this context.
I'll add comments in the codebase to explain some interesting bits. This is still just a work in progress and is not the final version of what we'll end up with.
Taster screenshots (ignore the lack of Essential only button, it's a point to discuss):
> Configure Civic UK branding and text 

- cardigan/stories/components/PageHeader/PageHeader.stories.tsx
- common/server-data/__mocks__/index.ts
- common/test/fixtures/prismicData/prismic-data.ts
- content/webapp/components/Body/Body.tsx
- content/webapp/components/InfoBox/InfoBox.tsx
- content/webapp/components/ModalMoreFilters/index.tsx
- content/webapp/services/prismic/transformers/body.test.ts
- content/webapp/test/services/prismic/transformers/contributors.test.ts
Maintenance
Just noticed some TS/linting errors and fixed some.
Adding delays on `PageHeader` stories as it flagged pixel changes in images.
> Fix some types in tests and removed unused imports

- dash/Dockerfile
- dash/README.md
- dash/webapp/components/Header.tsx
- dash/webapp/next.config.js
- dash/webapp/package.json
- dash/webapp/pages/index.tsx
- dash/webapp/pages/pa11y.tsx
- dash/webapp/pages/prismic-linting.tsx
- dash/webapp/pages/toggles.tsx
- dash/webapp/yarn.lock
Reverts wellcomecollection/wellcomecollection.org#10708
It's erroring [when building the dash](https://buildkite.com/wellcomecollection/wc-dot-org-build-plus-test/builds/13511#_) and I don't want to block deployments so will try to fix.
> Revert "Upgrade dash to node 18"

- content/webapp/components/EventsSearchResults/index.tsx
Errors in channel and e2e
I'd done one test for events search behind the toggle, but maybe should've waited as we're still working on it in a breakable way. This comments out the code causing the errors for now, I'll work on more after lunch.
> Hide locations whilst working on API changes

- common/data/microcopy.tsx
A couple of text changes [as requested](https://wellcome.slack.com/archives/C8X9YKM5X/p1711448205054019)
> text changes to guide links

- playwright/test/visual-stories.test.ts
Relates to #10755
The test was expecting the old link text, so have updated it to match the new text
> update link text in test

- common/views/components/Control/index.tsx
- content/webapp/components/AudioPlayer/AudioPlayer.Volume.tsx
- content/webapp/components/AudioPlayer/AudioPlayer.tsx
- content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.Stop.tsx
- content/webapp/components/PaletteColorPicker/PaletteColorPicker.tsx
General maintenance, a11y
I noticed some errors in the console flagged by styled-components. I'll add some comments where useful.
> Fix various SC and HTML props

- common/package.json
- common/server-data/index.ts
- common/services/prismic/fetch/index.ts
- common/slicemachine.config.json
- content/webapp/services/wellcome/catalogue/concepts.ts
- content/webapp/services/wellcome/catalogue/images.ts
- content/webapp/services/wellcome/catalogue/index.ts
- content/webapp/services/wellcome/catalogue/works.ts
- content/webapp/services/wellcome/content/index.ts
- content/webapp/services/wellcome/index.ts
- package.json
- prismic-model/tsconfig.json
- yarn.lock
Relates to #10664
Adds slice machine dependencies and config and fixes some typescript errors that became apparent
> Add slice machine 1

- content/webapp/components/CaptionedImage/CaptionedImage.tsx
- content/webapp/components/FeaturedCard/FeaturedCard.tsx
- content/webapp/services/prismic/transformers/body.ts
- content/webapp/types/body.ts
- content/webapp/types/card.ts
Relates to #10664 
Makes transformed types more specific
> Add slice machine 2

- common/data/microcopy.tsx
[Lalita requested the change in Slack](https://wellcome.slack.com/archives/C3N7J05TK/p1713170299180789?thread_ts=1712831942.778189&cid=C3N7J05TK)
> Edit events search meta description

- common/data/microcopy.tsx
Alignement and SEO https://github.com/wellcomecollection/wellcomecollection.org/issues/10777
Aligns things as bit better - see ticket.
> Change search microcopy

- cardigan/package.json
- cardigan/stories/data/content.ts
- cardigan/stories/data/images.ts
- cardigan/stories/data/text.ts
- yarn.lock
Maintenance
- Updates `faker` and changed the requires values. Replaced random text with Lorem Ipsum, we don't need to be flagged when it changes, it should always be the same anyway (if you hate the fact that the same text is repeated anywhere, we can bring it back)
> Upgrade faker and replace its values

- cardigan/package.json
- cardigan/stories/data/content.ts
- cardigan/stories/data/images.ts
- cardigan/stories/data/text.ts
- yarn.lock
Maintenance
This just replicates https://github.com/wellcomecollection/wellcomecollection.org/pull/10813. Forgot I'd done it as part of a more complicated branch and couldn't just merge it into `main`.
> Update faker and remove random words

- cardigan/package.json
- common/views/slices/TextAndImage/index.tsx
- yarn.lock
Maintenance
Trialling upgrading Chromatic package to see if it helps with [some errors we've been having](https://github.com/wellcomecollection/wellcomecollection.org/actions/runs/9000400527/job/24724480532?pr=10850).
> Upgrade chromatic

- common/customtypes/exhibition-guides/index.json
- common/prismicio-types.d.ts
- common/views/slices/AudioPlayer/model.json
- common/views/slices/CollectionVenue/mocks.json
- common/views/slices/CollectionVenue/model.json
- common/views/slices/Contact/model.json
- common/views/slices/ContentList/model.json
- common/views/slices/EditorialImage/model.json
- common/views/slices/EditorialImageGallery/model.json
- common/views/slices/Embed/model.json
- common/views/slices/GifVideo/model.json
- common/views/slices/Iframe/model.json
- common/views/slices/InfoBlock/model.json
- common/views/slices/Map/model.json
- common/views/slices/Quote/model.json
- common/views/slices/SearchResults/model.json
- common/views/slices/Standfirst/model.json
- common/views/slices/TagList/model.json
- common/views/slices/Text/model.json
- common/views/slices/TextAndIcons/model.json
- common/views/slices/TextAndImage/model.json
- common/views/slices/TitledTextList/model.json
This is what's in Prismic production currently
> New content type models

- common/model/opening-hours.ts
- common/views/slices/CollectionVenue/index.tsx
- content/webapp/components/Body/Body.tsx
- content/webapp/components/VenueHours/VenueHours.tsx
- content/webapp/services/prismic/transformers/body.ts
People who like to know the names of the places that have opening hours
Adding missing names (and pictures) after Slice Machine content migration
For #10856
> Featured collection venues

- content/webapp/components/Body/Body.tsx
Additional to #10850 necessary until everyone's moved to Slice Machine
> Show image galleries as standalone in non Slice Machine land

- common/views/components/CookieNotice/CookieNotice.tsx
Users who want to find the policy these next weeks
See ticket https://github.com/wellcomecollection/wellcomecollection.org/issues/10880
> Change link to cookie policy

- common/koa-middleware/prismicEnv.ts
- common/services/prismic/fetch/index.ts
- content/webapp/app.ts
- content/webapp/services/prismic/fetch/index.ts
Reverts wellcomecollection/wellcomecollection.org#10908
> Revert "Improve prismic stage/prod setup"

- prismic-model/README.md
Relates to [#10789](https://github.com/wellcomecollection/wellcomecollection.org/issues/10789)
> Add instructions for running slice machine and using diff script

- content/webapp/components/EventSchedule/EventScheduleItem.tsx
⬆️ 
For https://github.com/wellcomecollection/wellcomecollection.org/issues/10934
> Don’t show any message if the parent is ticketed

- common/prismicio-types.d.ts
- common/views/slices/GuideTextItem/index.tsx
- common/views/slices/GuideTextItem/mocks.json
- common/views/slices/GuideTextItem/model.json
- content/webapp/components/GuideTextItem/GuideTextItem.tsx
- content/webapp/services/prismic/transformers/exhibition-texts.ts
renders the content of the field added in #10937
> Render exhibition text field

- content/webapp/components/CardGrid/CardGrid.tsx
- content/webapp/pages/events/[eventId]/visual-stories.tsx
- content/webapp/pages/exhibitions/[exhibitionId]/visual-stories.tsx
- content/webapp/pages/visual-stories/[visualStoryId].tsx
- content/webapp/services/prismic/fetch/visual-stories.ts
- content/webapp/services/prismic/types/index.ts
- content/webapp/types/card.ts
- content/webapp/types/multi-content.ts
- content/webapp/types/visual-stories.ts
For #10884
~We'll need the promo fields to be filled in in Prismic before putting this live~ - done
> Add related visual stories links

- content/webapp/services/prismic/transformers/exhibition-guides.ts
just noticed the link to the audio guide isn't displaying, this fixes that
> Fix exhibition guide landing page

- prismic-model/diffCustomTypes.ts
- prismic-model/utils/prismic.ts
> Diff local and remote slices as well as custom types

- common/data/microcopy.tsx
- content/webapp/components/Exhibition/Exhibition.tsx
- content/webapp/components/IIIFViewer/NoScriptImage.tsx
- content/webapp/components/SearchFilters/SearchFilters.Desktop.CheckboxFilter.tsx
- content/webapp/components/SearchFilters/SearchFilters.Desktop.DynamicFilters.tsx
- content/webapp/components/SearchFilters/SearchFilters.Desktop.Modal.tsx
- content/webapp/components/SearchFilters/SearchFilters.Mobile.tsx
- content/webapp/components/Tabs/Tabs.styles.tsx
- content/webapp/pages/api/works/items/[workId].tsx
- content/webapp/pages/concepts/[conceptId].tsx
- content/webapp/services/prismic/transformers/body.ts
- playwright/test/visual-stories.test.ts
I went through some of our TODOs and removed some/fixed some. I split the commits so they'd be easy to follow.
Read through and see if you're happy!
Less TODO pollution ✨ 
Missed opportunities, but flag them here if so.
> TODOs addressing

- toggles/webapp/toggles.ts
Ability to deploy changes to EG behind toggle for easier design review
N/A
N/A
N/A
> Add new toggle for exhibition guide work

- README.md
> Update design tools in README (Figma, not Sketch/Zeplin)

- .github/workflows/tsc.yml
> Playwright tsc

- dash/webapp/pages/toggles.tsx
I wanted to try it ([og PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/11103)) but it won't work for what I realise are obvious security reasons. I could dig into how to make it work but I think the ole copy/paste method works well enough and it's not worth the time. If anyone else is inspired - go for it!
I've tested by deploying the dashboard locally.
N/A
N/A
> Dash: Remove local toggle option

- prismic-model/README.md
Removes some outdated information. The [script compares slices](https://github.com/wellcomecollection/wellcomecollection.org/pull/10970) now
n/a
n/a
n/a
> remove outdated text

- cache/README.md
No documentation really could be found so document now updated after successfully doing the Jason DG redirections
> Add redirect instructions in README

- .github/workflows/prismic-linting.yml
- prismic-model/lintPrismicData.ts
Pass as flag (as declared) and fix duplicate. Pluralise renders the number as well!
Follow up from #11200 (Relates to https://github.com/wellcomecollection/wellcomecollection.org/issues/11202)
You can run it locally or look at the latest result in #bot-test
Actually works!
N/A
> Fix command line and amend message sent to Slack

- .github/ISSUE_TEMPLATE/feature_request.md
Try adding project to template directly
Once it's merged in I think
No orphan tickets
N/A
> Add projects to template

- content/webapp/components/WorkDetails/WorkDetails.AvailableOnline.tsx
- content/webapp/components/WorkDetails/index.tsx
- playwright/test/helpers/contexts.ts
- toggles/webapp/toggles.ts
Relates to #11076 
Removes toggle and its related conditions.
[Would recommend viewing without whitespace changes](https://github.com/wellcomecollection/wellcomecollection.org/pull/11250/files?diff=split&w=1).
Run locally and ensure that everything renders as expected.
Born Digital work: `works/g7zn5j4n`
Everything still renders as expected and we have one less toggle. Huzzah.
N/A
> Remove showBornDigitalToggle conditions

- assets/humans.txt
Added myself and Flora to Digital Platform section :)
> Add new joiners to humans.txt

- cardigan_new/package.json
> Bump Next version to fix some dependabot flagged vulnerabilities

- content/webapp/pages/stories/index.tsx
points the 'more comics' link to the correct place
> correct url

- cache/locals.tf
> bump lambdas

- .github/dependabot.yml
⬆️ 
Relates to [#11230](https://github.com/wellcomecollection/wellcomecollection.org/issues/11230)
> Stop dependabot ignoring slicemachine 

- .github/dependabot.yml
- cardigan/package.json
- common/package.json
- content/webapp/package.json
- dash/webapp/package.json
- identity/webapp/package.json
- identity/webapp/src/app.ts
- identity/webapp/src/frontend/components/PageWrapper.tsx
- yarn.lock
For [#11228](https://github.com/wellcomecollection/wellcomecollection.org/issues/11228)
Upgrades our apps to Next 14.2.10
`yarn` all the things
`rm -rf node_modules && yarn`
Try building/running the following locally:
- dash
- cardigan
- content
- identity
Nothing breaks
I've built and run everything and it all seems to work fine
> Upgrade next

- toggles/webapp/toggles.ts
> Add recommendedStories toggle

- infrastructure/experience/terraform.tf
[See equivalent Content API PR for info](https://github.com/wellcomecollection/content-api/pull/188)
Thanks @gestchild !
> Terraform: Wrap role_arn in assume_role

- cardigan/stories/data/content.ts
- content/webapp/components/FeaturedCard/FeaturedCard.styles.ts
- content/webapp/components/FeaturedCard/index.tsx
#11484 
Adjusts cards as per mockup (in ticket)
Run locally and go on /whats-on
Can also be seen in [this branch's built Cardigan](https://62f13cdbd0ff140768a8d87b-mjvhsycfkq.chromatic.com/?path=/story/components-cards-featuredcard--basic&args=type:exhibition)
N/A
> Add description to featured exhibition cards

- assets/humans.txt
> moved georgia to DP :')

- toggles/webapp/toggles.ts
#11486 
Will deploy once merged
> Add toggle for new search page look

- assets/humans.txt
> Add Mankeet to humans

- .github/dependabot.yml
- common/package.json
- yarn.lock
Added a separate ticket for openseadragon https://github.com/wellcomecollection/wellcomecollection.org/issues/11563
And for prismicio https://github.com/wellcomecollection/wellcomecollection.org/issues/11568
Ignoring more things that depend on our versions of next/react
Run locally, run tests
More interesting mega Dependabot PR
> Ignore more packages updates

- content/terraform/stack/main.tf
Follows https://github.com/wellcomecollection/platform-infrastructure/pull/462
Part of https://github.com/wellcomecollection/platform/issues/5919
This change implements the nginx frontend change intended to improve performance under load.
Less outages, better performing services under load.
This will change resource utilisation on the production boxes, so it should be tested in stage, and trialled in production to ensure that this is not harmful.
> Update nginx image

- content/webapp/components/ImageGallery/ImageGallery.test.tsx
- content/webapp/components/ImageGallery/index.tsx
- content/webapp/services/wellcome/index.ts
Had a really small copy change based on work done in content API, thought I'd throw the pluralising in as well.
> Small copy changes

- common/services/conversion/track.ts
- common/views/pages/_app.tsx
- content/webapp/pages/about-us/cookie-policy.tsx
Reverts wellcomecollection/wellcomecollection.org#11644
#11374 
Deploying this should fix the broken e2es in prod
> Revert "Load cookie banner on cookie policy page but hide it"

- content/webapp/pages/search/index.tsx
#11621 
Adds triggers to unblock Mankeet's work. He asked for the tag to be what's on the link, but maybe I should add a "-link" suffix?
Are they printed in the DOM?
Tracking now possible
N/A
> Add triggers for the catalogue links in all search

- toggles/webapp/toggles.ts
> Add dateFilter toggle

- toggles/webapp/toggles.ts
For #11786
Adds a toggle to work on the new UI/UX for the audio player
n/a
n/a
n/a
> Add audioPlayer toggle

- assets/humans.txt
Adds Daniel Sim to humans.txt
😏
Success is 7 bytes long if encoded with UTF-8
Possibly not
> Add Daniel Sim to humans.txt

- content/webapp/pages/search/events.tsx
- toggles/webapp/toggles.ts
https://github.com/wellcomecollection/wellcomecollection.org/issues/11811
Has been publicly available since 03/04
I'll update the dashboard after merging.
> Remove the date filter toggle 

- assets/humans.txt
> Move humans around

- .github/ISSUE_TEMPLATE/feature_qa.md
Updating the Feature QA template to remove outdated browser support list and turn QA steps into checkboxes
n/a
Increased willingness to fill in template and to test on browsers
n/a
> Update Feature QA template

- .github/workflows/chromatic.yml
- .github/workflows/performance.yml
- .github/workflows/tsc.yml
https://github.com/wellcomecollection/wellcomecollection.org/security/code-scanning/24 Performance
https://github.com/wellcomecollection/wellcomecollection.org/security/code-scanning/25 Chromatic
https://github.com/wellcomecollection/wellcomecollection.org/security/code-scanning/26 Typescript
Do they run properly? (See PR tests below 🤷‍♀️ )
Security warnings addressed
N/A
> Add minimal permissions to workflows

- content/webapp/components/AudioPlayerNew/AudioPlayer.PlayRate.tsx
- content/webapp/components/AudioPlayerNew/index.tsx
For #11898 
Mobile spacing amends for the AudioPlayer (from [Figma](https://www.figma.com/design/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?node-id=2907-10959&m=dev))
> Audio player mobile qa amends

- toggles/webapp/toggles.ts
For #11767 
Adds a toggle for the work to site behind
> add toggle for related content on works

- cache/locals.tf
Follows up https://github.com/wellcomecollection/wellcomecollection.org/pull/11952
> Latest lambdas 153/151

- common/services/conversion/track.ts
- content/webapp/components/ContentSearchResult/index.tsx
- content/webapp/components/DownloadLink/index.tsx
- content/webapp/components/EventsSearchResults/index.tsx
- content/webapp/components/ImageCard/index.tsx
- content/webapp/components/ImageEndpointSearchResults/index.tsx
- content/webapp/components/SearchNoResults/index.tsx
- content/webapp/components/StoriesGrid/index.tsx
- content/webapp/components/VisuallySimilarImagesFromApi/index.tsx
- content/webapp/components/WorksSearchResult/index.tsx
- content/webapp/pages/search/index.tsx
For #11707 
Adding the necessary attributes and dataLayer events required to allow us to track things that we are currently tracking in Segment in GA instead.
Not sure any testing is required, but if you want to you can preview the events in GTM and check relevant GA tags are firing based on what we [decided here](https://github.com/wellcomecollection/wellcomecollection.org/issues/11707#issuecomment-2916594989)
in GA
> Segment to ga

- content/webapp/components/RelatedWorks/RelatedWorks.helpers.tsx
- content/webapp/components/RelatedWorks/index.tsx
- content/webapp/pages/works/[workId]/index.tsx
Thought it might be better to be intentional about the data we're passing to the component. It doesn't need the whole `work` object and clarifies what's required for that component.
Should behave just like in prod
Clearer component usage, less data passed around.
N/A
> Be more intentional about the data passed to the `RW` component

- content/webapp/pages/concepts/[conceptId].tsx
This updates the hotjar embed introduced in https://github.com/wellcomecollection/wellcomecollection.org/pull/11991 to fit more pleasingly into the page and react responsively to viewport size.
https://github.com/user-attachments/assets/8da9cb91-12f0-4b45-8b3c-80662d596ecd
Pretty pages, happy users.
Risks should be minimal an only impact pages that include the hotjar embed.
> Responsive hotjar embed placeholder

- .github/workflows/chromatic.yml
- .github/workflows/performance.yml
- .github/workflows/prismic-linting.yml
- .github/workflows/tsc.yml
Free runner is causing us issues and queues the actions without running them. It's happened last week as well and resolved itself the following day and started again over the weekend.
As it's a blocker, I'm creating this PR to address, we can always revert tomorrow (? I'm guessing it'd be best, @kenoir ?)
[Slack convo](https://wellcome.slack.com/archives/CUA669WHH/p1750668106216649)
> Move all runners to paid runner

- playwright/test/concept.test.ts
https://wellcome.slack.com/archives/CQ720BG02/p1754297418778489
Songs started failing the tests over the weekend, I think because its results might've changed..?
> Concept; Test statistics instead of songs

- toggles/webapp/toggles.ts
Ground work! 
https://github.com/wellcomecollection/wellcomecollection.org/issues/12214
> New toggle for collections landing

- dash/webapp/pages/toggles.tsx
- dash/webapp/yarn.lock
- toggles/webapp/toggles.ts
This is a toggle for the medium term so although no quite permanent we're better off moving it off the experimental bit. 
It's also for internal use so I put it higher to make it easier to find.
It's already deployed
> Move toggle around the dash and make permanent

- toggles/README.md
Documents this feature: https://github.com/wellcomecollection/wellcomecollection.org/pull/11868
> Add info regarding query params in toggles dash

- common/views/components/FeaturedWorkLink/index.tsx
- content/webapp/views/components/SourcedDescription/index.tsx
Addresses QA comments in #12068
Visit a page with FeaturedWorkLink.Hover variants and check the opacity transitions in and out. Also check that once a card is visible, it won't move position when you hover a different part of the link until it has first become invisible.
Works as designed.
> Hover card QA
