wellcomecollection/wellcomecollection.org

catalogue/webapp/components/IIIFImage/IIIFImage.tsx
maintenance
Noticed a typo in `maxwidth` and while fixing, I noticed it didn't seem required. It was added [here to account for changes to Next Image](https://github.com/wellcomecollection/wellcomecollection.org/pull/9280/files#diff-eaffb8859af039e0029ba83905edfb31490e0f82267388453ccc5115f131dd9fR19), but `img` has `height: auto` already so that was a double. I tested in the image gallery and it didn't seem like required styling, so am removing.
=> Remove unused css

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
We should be conditionally showing the available online section, but the check for audio was always returning true.
At some point the value of audio changed so we now need to check the length of the sounds property it contains.
=> Conditionally show available online section

content/webapp/pages/api/events/index.ts, content/webapp/pages/api/exhibitions-related-content/index.ts, content/webapp/pages/api/exhibitions/index.ts
☝️ 
After #9391 because our current api route implementation using `superjson` (which enables serialization/deserialization of, among other things, `Dates`) has stopped working recently.
=> Use serialize instead of stringify from superjson

catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx, catalogue/webapp/pages/search/images.tsx, catalogue/webapp/pages/search/works.tsx
This allows somebody to jump directly from a search page to the underlying catalogue API query, which is useful for debugging.
This is done with half an eye towards https://github.com/wellcomecollection/wellcomecollection.org/issues/8339 – I suspect some of our queries are passing unnecessary fields in the `include` parameter and getting more data than we need.
=> Add API toolbar links for catalogue API queries in the new search

catalogue/webapp/components/CalendarSelect/CalendarSelect.tsx, catalogue/webapp/components/RequestingDayPicker/RequestingDayPicker.tsx, catalogue/webapp/utils/dates.ts, common/services/prismic/opening-times.ts, common/utils/array.ts, common/utils/dates.test.ts, common/utils/dates.ts, content/webapp/components/EventsByMonth/group-event-utils.test.ts, content/webapp/components/EventsByMonth/group-event-utils.ts, content/webapp/services/prismic/transformers/events.ts
Spotted on code read.
* Be consistent about `startDate`/`endDate` as parameter names in all this code
* [Simplify the map/filter in CalendarSelect](https://github.com/wellcomecollection/wellcomecollection.org/commit/45e670a8505c6bb472b81cb2cccdf0fcc2de6fd5) (see the commit message for longer explanation)
=> Tidy up parameter names/iteration order in some date picker code

common/views/components/Pagination/Pagination.tsx, playwright/test/search-works.test.ts
e2e tests
- Added a test to check Sorting dealt with the navigation correctly
- Fixed mobile tests for filters (older TODOs)
- Change `data-test-id` to `data-testid` because that's what Playwright and testing library support (see [PR convo here](https://github.com/wellcomecollection/wellcomecollection.org/pull/9393#discussion_r1126624648))
=> Search works tests

cardigan/stories/components/Contributors/Contributors.stories.tsx, content/webapp/components/Contributors/Contributors.tsx
Cardigan
Had an a11y flag where the heading was displaying as empty. The `isNotUndefined` check means an empty string is true (only checks for `undefined`), so I just removed that prop from the story completely. 
It does mean that an empty string (`''`) will display an empty h2 though, but as it seems to [have been done on purpose](https://github.com/wellcomecollection/wellcomecollection.org/commit/a3030801f13dadaafda379be81fbb877c116e185) ([PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/8834)), I wonder if there is more to consider? Should we change the check to be something like;
```
{Boolean(titleOverride)
? titleOverride
: getContributorsTitle(roles, titlePrefix)}
```
=> Cardigan Contributors: Fix missing heading

catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx
Everyone ⭐ 
React strict mode flagged a race condition/use effect issue with the navigation (only locally, [read more here](https://wellcome.slack.com/archives/C3TQSF63C/p1678274886701909?thread_ts=1678272840.419089&cid=C3TQSF63C)). `pageLayoutMetadata` gets updated at the same time as `updateUrl` is fired, so it was sending in the previous URL value. 
I don't think we need to use the URL set by the state as `updateUrl` is only used on `onSubmit`, which will always be on the current page, so I changed it to use `router.pathname` instead, which fixes the issue.
=> Use useRouter pathname instead of depending on state

toggles/webapp/toggles.ts
This will turn on the comic section on the stories landing page for everyone who hasn't already opted in.
=> Make storiesLandingComics toggle default to true

catalogue/webapp/components/PhysicalItems/PhysicalItems.tsx
Fixes #9400
We can get in a race condition between the useItemsState hook and the useAbortSignalEffect hook, which meant sometimes the itemsState could be reset to 'stale' after it had been set to 'up-to-date' and this would prevent the status and access from displaying.
As far as I can reason, we only need to run the useItemState hook on first render and removing items from the dependency array fixes the issue.
=> Only run the useItemState hook on initial render

catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx, catalogue/webapp/components/WorkTabbedNav/WorkTabbedNav.tsx, common/views/components/SubNavigation/SubNavigation.styles.tsx, common/views/components/SubNavigation/SubNavigation.tsx
Maintenance
Color variants were leftovers from `TabNav`, which looks really similar but does need other colours ([see concept images section](https://wellcomecollection.org/concepts/n4fvtc49)). `SubNavigation` in itself only ever uses yellow, there is no plan (AFAIK) to use something else, so a bit of a cleanup.
=> Remove variants in subnavigation

common/views/components/HeightRestrictedPrismicImage/HeightRestrictedPrismicImage.tsx, common/views/components/PrismicImage/PrismicImage.tsx
People who want TASL info icons to line up in the right place
Amending the image positioning (and removing magic negative bottom margin)
=> Make images display: block

common/views/components/WatchLabel/WatchLabel.tsx, content/webapp/components/ArticleCard/ArticleCard.tsx, content/webapp/components/ArticleScheduleItemCard/index.tsx, content/webapp/components/FeaturedCard/FeaturedCard.tsx, content/webapp/components/ImagePlaceholder/ImagePlaceholder.tsx, content/webapp/components/MediaObjectBase/MediaObjectBase.tsx, content/webapp/components/SearchResults/SearchResults.tsx, content/webapp/components/SeriesNavigation/SeriesNavigation.tsx, content/webapp/components/StoryPromo/StoryPromo.tsx, content/webapp/pages/articles/[articleId].tsx, content/webapp/pages/series/[seriesId].tsx, content/webapp/services/prismic/transformers/article-series.test.ts, content/webapp/services/prismic/transformers/article-series.ts, content/webapp/types/articles.test.ts, content/webapp/types/articles.ts
This makes a couple of changes to the way we handle article series pages, e.g. https://wellcomecollection.org/series/Y_OGkRQAACgAq4ui
* It removes the confusing `transformArticleSeries`, which was both difficult to follow and had a misleading return type – it claimed to return `ArticleBasic[]`, but actually it returned `(ArticleBasic | ArticleScheduleItem)[]`.
Instead, we now construct two lists inside the getServerSideProps for article series pages:
```typescript
articles: ArticleBasic[];
scheduledItems: ArticleScheduleItem[];
```
This means we can simplify how we render them on the page – we display all the articles, then all the scheduled items.
It also makes some of our assumptions about how these pages behave explicit – for example, Prismic returns articles in descending publication …
=> Simplify and tidy up the way we render article series

common/services/app/google-analytics.tsx, common/views/pages/_document.tsx
Relates to #9417, where I'm setting up tracking pageviews for visitors without javascript.
This PR adds a key value pair containing the GA user Id (taken from the _ga cookie) to the iframe source in the Google Tag Manager code, which then can be accessed as a Datalayer variable in Google Tag Manager and means we can send it with the event to Google Analytics.
Without this every pageview event would be seen as a new session.
=> add GA id to GTM iframe source

common/views/components/Caption/Caption.tsx
=> Wrap figcaption to make Firefox read img alt first

catalogue/webapp/components/ItemRequestModal/RequestDialog.tsx, common/views/themes/utility-classes.ts, content/webapp/components/EventSchedule/EventScheduleItem.tsx
Another snip at https://github.com/wellcomecollection/wellcomecollection.org/issues/8420
We were only using the `no-margin-l` variant, so there wasn't much to clean up.
=> Remove the width-dependent no-margin classes

common/views/components/RadioGroup/RadioGroup.tsx
Continuing to chip away at https://github.com/wellcomecollection/wellcomecollection.org/issues/8420
=> Switch to styled-components instead of one-line classes in RadioGroup

common/utils/array.ts
Spotted when I tried to use this function and TypeScript got very confused!
=> Fix the type of the result on isUndefined

catalogue/webapp/components/ArchiveTree/ArchiveTree.tsx, catalogue/webapp/components/WorkDetails/ExplanatoryText.tsx, common/views/components/AppContext/AppContext.tsx, common/views/components/ButtonSolid/ButtonSolid.tsx, common/views/components/CheckboxRadio/CheckboxRadio.tsx, common/views/components/Modal/Modal.tsx, common/views/components/PopupDialog/PopupDialog.tsx, common/views/components/SearchTabs/SearchTabs.BaseTabs.tsx, common/views/components/SearchTabs/SearchTabs.tsx, common/views/components/SelectContainer/SelectContainer.tsx, common/views/pages/_document.tsx, common/views/themes/typography.ts
We are currently using JS to determine whether you're using a keyboard and applying visual focus styles accordingly.
`:focus-visible` is [well supported](https://caniuse.com/?search=focus-visible) and means we can achieve the same results without JS.
Explainer: [When is :focus-visible visible](https://bitsofco.de/when-is-focus-visible-visible/)
=> Focus visible

common/views/components/DropdownButton/DropdownButton.tsx, common/views/components/Header/DesktopSignIn.tsx
I noticed that the aria-label was being populated by the id prop and this didn't make any sense when being read out by a screen reader, so I've added a more descriptive ariaLabel prop
=> make the sign in button description more descriptive

common/server-data/toggles.ts, common/services/app/google-analytics.tsx, common/views/themes/default.ts, content/webapp/pages/stories/index.tsx, toggles/webapp/index.ts
Relates to #9473
- This makes it possible to send a value of false for a test toggle to GA and Segment
- The false value will now only be false if it is explicitly set to false
- If the toggle is undefined no data will be sent
This also implements sending the data to GA, i'll open a new PR for sending the data with the segment tracking code
=> Toggle false should not be considered the same as undefined for test toggles

common/utils/cookies.ts, common/views/components/ErrorPage/ErrorPage.tsx
Fixes #9473 (along with #9476)
Sends toggles to Segment when their value is false, prefixed with '!'
=> send false toggles to Segment

catalogue/webapp/components/Work/Work.tsx, catalogue/webapp/package.json, common/package.json, content/webapp/package.json, identity/webapp/package.json, playwright/yarn.lock, yarn.lock
upgrade typescript to 5.0.2 while fixing the errors that would come from attempting to build catalogue
=> bump typescript to 5.0.2 for webapps

cardigan/config/decorators.tsx, catalogue/webapp/components/ArchiveBreadcrumb/ArchiveBreadcrumb.tsx, catalogue/webapp/components/IIIFClickthrough/IIIFClickthrough.tsx, catalogue/webapp/components/IIIFViewer/ViewerSidebar.tsx, catalogue/webapp/components/WorkDetails/ExplanatoryText.tsx, common/views/components/AppContext/AppContext.tsx, common/views/components/GlobalInfoBarContext/GlobalInfoBarContext.tsx, common/views/components/Layout/Layout.tsx, common/views/components/Layout10/Layout10.tsx, common/views/components/Layout12/Layout12.tsx, common/views/components/Layout6/Layout6.tsx, common/views/components/Layout8/Layout8.tsx, common/views/components/MessageBar/MessageBar.tsx, common/views/components/Modal/Modal.tsx, common/views/components/OutboundLinkTracker/OutboundLinkTracker.tsx, common/views/components/PageLayout/PageLayout.tsx, common/views/components/SpacingSection/SpacingSection.tsx, common/views/components/WobblyBottom/WobblyBottom.tsx, common/views/components/WobblyEdgedContainer/WobblyEdgedContainer.tsx, common/views/components/WobblyRow/WobblyRow.tsx, content/webapp/components/Body/Body.tsx, content/webapp/components/Body/VisitUsStaticContent.tsx, content/webapp/components/Contributors/Contributor.tsx, content/webapp/components/InfoBox/InfoBox.tsx
This is a convention we established when we had to add explicit children to all our types during the Next 13 upgrade; this backfills the change to all our components where we already had explicit children.
Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/9437
=> Replace a bunch of explicit children properties with PropsWithChildren

catalogue/webapp/components/ArchiveTree/ArchiveTree.tsx
Who is this for?
People who don't want to accidentally break tracking by e.g. changing a component or class name
What is it doing for them?
Adding data-gtm-trigger attribute hooks for long-lived GA4 events so their purpose is clear.
=> Changes for gtm tree_link

catalogue/webapp/pages/search/stories.tsx
devs, analytics
- Add a link to the content API query response in the API toolbar
- Realised I was only looking at the Prismic API for errors and pageview properties, so adding a check on the Content API for those.
Closes #9578
=> Stories search; add API toolbar link to content API, check for new query errors

common/views/components/Tasl/Tasl.tsx, content/webapp/components/ImageWithTasl/ImageWithTasl.tsx
It had a bunch of `getSomething()` functions which returned a `ReactElement | undefined`; our style everywhere else has been to use FunctionComponent for this sort of thing.
It's a fairly minimal change but makes it more stylistically consistent with our other code.
cf https://github.com/wellcomecollection/wellcomecollection.org/pull/9552
=> Tidy up some stuff in the Tasl component

common/views/components/TextWithDot/Dot.tsx
=> The DotEl component doesn't need wrapping in a FunctionComponent

catalogue/webapp/pages/search/index.tsx
Search
Currently on `/search`, we just get a "no result" if Prismic API returns no result, even if you're actually pointing to the Content API. Prismic API will always return no result if that's the case, so that needed changing.
This doesn't happen in `/search/stories`
=> Stories toggle; Check if either queries have a result

catalogue/webapp/pages/search/stories.tsx
Search/Content API devs
Adds relevance as the default sorting option only if the toggle is activated.
I know Relevance asc/desc doesn't make much sense but it's only in Javascriptless pages (we need two different dropdowns for sort and sortOrder), that's the way we have it for works as well.
Closes #9580
=> Add relevance as a sort option if Content API toggle is activated

catalogue/webapp/pages/search/index.tsx
Content API results
Changes the default sort order on "All" search to be relevance.
=> Change default sort for All

.github/workflows/chromatic.yml, cardigan/package.json, yarn.lock
Chromatic users
[Chromatic has been acting up on snapshots](https://wellcome.slack.com/archives/C3TQSF63C/p1681290481847349), we're hoping this will batch update them.
The `yarn.lock` update is, hopefully, extra insurance that it will get picked up.
=> Temporarily remove turbosnap

catalogue/webapp/components/VideoPlayer/VideoPlayer.tsx
I was looking to replicate our UA tracking with GA4 in the `VideoPlayer` component that is in use for works, without having to use Tag Manager – some long-lived tracking still feels like it maybe makes more sense to live in code, e.g. when sending along data that would otherwise need to be read from the DOM with a Tag Manager custom variable. This is debatable, and I guess we should decide for sure what, if any, events we want to continue to send from the codebase.
Seems like this would be the way to do it, using the `gtag` function that the analytics script attaches to the `window` (we'd have to decide on a format for the event names):
```
gtag('event', 'Engagement', {
event_category: 'Video',
seconds_played: secondsPlayedRef.current,
});
```
When looking at this, I realised that we're …
=> Send correct secondsPlayed with video engagement tracking

common/package.json, common/views/components/StackingTable/StackingTable.tsx, dash/webapp/package.json, identity/webapp/package.json, package.json, yarn.lock
Devs
Upgraded types/react to `18.0.35` in one repo earlier and it seems to have caused some errors (maybe?) so tried aligning it across and fixing the error it flagged, which seems to work.
=> fix bundle size diff; Align types/react and fix error

.github/workflows/chromatic.yml, cardigan/package.json
Chromatic users
Forces all components to rerun, this should ensure we don't get minimal change alerts 🤞
=> Force rebuild on Chromatic components

content/webapp/components/Exhibition/Exhibition.tsx
Exhibitions pages
For #9565
Changed hardcoded `h2` on Exhibition pages from "About this exhibition" to "Related stories" as requested by Digital Editorial
=> changed hardcoded h2 on exhibitions page to 'Related stories'

content/webapp/services/prismic/transformers/contributors.ts, prismic-model/lintPrismicData.ts, prismic-model/src/organisations.ts, prismic-model/src/people.ts
The contributor model in Prismic has a `sameAs` field which is used to link to the contributor elsewhere on the web, e.g. a person's social media or an organisation's website. The `sameAs` object has two fields: `link` and `title`. We need both of them to display the link on the page.
We had an [issue earlier today](https://wellcome.slack.com/archives/C8X9YKM5X/p1681723088499609) where a link to an organisation's website was being hidden, because it wasn't obvious that we need both of them in the Prismic editing interface.
This PR addresses this issue in three ways:
* The title on the Organisation model was labelled as "Title (override)" in the Prismic UI, which implies it's optional. I've renamed it to "Title" and added placeholders with examples of usage, which include "(required)" as a …
=> Improve a few aspects of the sameAs field on contributors

.github/workflows/chromatic.yml, cardigan/package.json
Chromatic users
Re-sets Turbosnap, we don't want all snapshots to run if no modifications have been done.
=> Re-set Turbosnap

identity/webapp/pages/registration.tsx
☝️ 
I'd previously thought this was all handled on Auth0 side and we'd need to fire a trigger when someone signing up arrived at a callback URL from Auth0, but because of the way we have to create the signup process at a URL we host ourselves (`/registration`), we can add the tracking to the 'Create library account' button, which is easier.
=> Add create_library_account trigger

cardigan/stories/components/BackToResults/BackToResults.stories.tsx, common/views/components/BackToResults/BackToResults.tsx
Fixes #9618 
Also adds a `back_to_search_restuls` trigger.
=> Only show 'back to search results' if you've arrived at the page from an internal search

.eslintrc.js, common/babel.js, package.json, yarn.lock
Maintenance
After [merging an update](https://github.com/wellcomecollection/wellcomecollection.org/pull/9566) to `babel-plugin-styled-components`, I wanted to make sure [the settings in our config](https://github.com/wellcomecollection/wellcomecollection.org/blob/78fe69e7c2e81885132577137f7e83d9a76edf46/common/babel.js) were still useful. I believe, following this, that `preprocess` can be removed. There's no reference to it in their documentation, and it was  a feature that they tested [and then removed](https://styled-components.com/releases#v3.2.4%20/%20v3.2.5).
Wanting to commit this file gave me errors which led me to find out that `babel-eslint`, which we'd been using as a parser, [had been deprecated for a bit](https://www.npmjs.com/package/babel-eslint). so I updated it to favour …
=> Update babel eslint parser and remove unused option

.github/workflows/performance.yml, catalogue/terraform/stack/main.tf, playwright/test/search-works.test.ts
Tentative fix for https://github.com/wellcomecollection/wellcomecollection.org/issues/9452, which involves modifying the load balancer config. I've also added an end-to-end test, so we'll catch this if we break it in future.
Nobody could reproduce the issue locally, so I guess the problem was somewhere in the deployment infrastructure. As a quick reminder, here's what our stack looks like:
```mermaid
graph LR
DNS["DNS records<br/>in Route 53"] --> CF[CloudFront distribution]
CF --> ALB["EC2 Load Balancer (ALB)"]
ALB --> ECS["ECS service<br/>(apps running in<br/>Docker containers)"]
classDef interestingNode fill:#a2eeed,stroke:#1dbebb
class DNS,CF,ALB,ECS interestingNode
```
The load balancers have their own DNS names: prod-1800364202.eu-west-1.elb.amazonaws.com and …
=> Fix the "back to search results" link

prismic-model/lintPrismicData.ts
Content/FE
Checks _all_ missing image ratios ([see Slack conversation here](https://wellcome.slack.com/archives/C8X9YKM5X/p1681973407064909)). Tbh these are now all fixed so shouldn't be an issue anymore, but who knows, there might be a bug down the line. Up to us to keep this improved version or throw away the whole check.
=> Check all promo ratios in prismic linting

common/views/components/ButtonSolid/ButtonSolid.tsx
I was poking around in here yesterday while doing some React profiling, and VSCode was whinging that `event` is untyped.
=> Add a missing type to handleClick

common/views/components/PageLayout/PageLayout.tsx
For some reason Next doesn't include these in the rendered <head>; changing them to a regular <script> like we do elsewhere (e.g. GA snippets) gets these rendering correctly.
=> Don't use <Script> inside the <Head>

common/services/app/google-analytics.tsx, common/views/pages/_document.tsx
Undoing work that was done as part of #9417
We're not going to try and track non javascript users
=> don’t attach gaUserId to iframe source

catalogue/webapp/components/WorkDetails/WorkDetails.tsx, catalogue/webapp/components/WorkDetailsText/WorkDetailsText.tsx
The API sometimes returns data with newlines in the data, but whitespace isn't typically significant in HTML.
This fixes the work details so any newlines from the API data will be preserved.
=> Make sure we render newlines in the lettering field (and other fields)

cache/edge_lambdas/yarn.lock, cache/locals.tf
Users with bookmarks
When fixing the missing `partOf.title` filter, I realised I hadn't listed it as a valid params in the `/works` to `/search/works` redirect, so here it now is. ([works in staging](https://www-stage.wellcomecollection.org/works?partOf.title=VLeBooks) now)
=> Apply new version to get partOf in works redirect

common/data/microcopy.tsx, content/webapp/components/Exhibition/Exhibition.tsx, content/webapp/components/Installation/Installation.tsx
Digital Editorial 
Users looking for Accessibility information on exhibition and events pages
For #9617 
A request was made for accessibility copy to be adjusted to be consistent across events, exhibitions, and installation pages within the yellow box . Users now see the same information across yellow boxes on accessibility 
Correct text displays on all exhibitions, events, and installations
To do this I:
- adjusted copy on both exhibitions, events, and installation yellow boxes
- imported the ```createScreenreaderLabel``` component into ```Exhibition.tsx``` and ```Installation.tsx``` to ensure the telephone number on the exhibitions page would also be read out correctly by screen readers
=> Edited accessibility information in yellow box 

playwright/test/search-works.test.ts
Currently, only one playwright test is being executed on main.  This reinstates the missing ones.
=> reinstate hidden tests

common/services/prismic/opening-times.ts, common/utils/dates.ts, content/webapp/services/prismic/transformers/events.ts, content/webapp/utils/event-series.ts
This removes the default comparison mode from isSameDay.  I've updated all the calls that were relying on the default, so this doesn't change any behaviour, but it makes it easier to see where we're still using a UTC comparison of "same day".
I think eventually we should be doing London comparisons everywhere, but I'm not touching that right now – this is just making it more visible where we aren't using London-based logic.
Another bit of cleanup following https://github.com/wellcomecollection/wellcomecollection.org/issues/9666
=> Require an explicit comparison mode in isSameDay()

cardigan/stories/components/BookPromo/BookPromo.stories.tsx, cardigan/stories/components/Cards/Cards.stories.tsx, cardigan/stories/components/PageHeader/PageHeader.stories.tsx
Chromatic
Lowers the difference threshold to `0.1` as Chromatic support said it seemed sufficient based on their tests.
Adding it to PageHeader: Article as it's come up often as being different.
Our decided strategy for now is to apply that threshold (basic one being at `0.063`) when similar "differences" come up. Only happens on images that never change, so I believe it's still a Chromatic issue but could also have to do with the way we compress images.
If the lowering of it makes them detect a difference again, we can bring it back to `0.2` as that still detected 4px wide differences, which already has more value.
=> Lower threshold and add it to PageHeader Article

common/utils/dates.test.ts
This is copy-pasted from the tests for isSameDay with a UTC comparison, so pass unmodified.
(I was reading the implementation of isSameDay for London and briefly got confused and thought it had a bug; it doesn't, but we should be covering these test cases anyway.)
=> Add some tests for isSameDay => false in London time

catalogue/webapp/pages/concepts/[conceptId].tsx, common/views/components/TabNav/TabNav.tsx
Fixes #9665
@taceybadgerbrook 
Sending a Segment event when someone uses the tabs on the concept page:
=> Send a Segment event when the tabs are used on a concept page

catalogue/webapp/components/ConceptLink/index.tsx, catalogue/webapp/components/ImageLink/index.tsx, catalogue/webapp/components/ImagesLink/index.tsx, catalogue/webapp/components/ItemLink/index.tsx, catalogue/webapp/components/Work/Work.tsx, catalogue/webapp/components/WorkDetails/WorkDetails.tsx, catalogue/webapp/components/WorkLink/index.tsx, catalogue/webapp/components/WorksLink/index.tsx, catalogue/webapp/pages/works/[workId]/download.tsx, common/data/segment-sources.ts, common/data/segment-values.ts, common/services/conversion/track.ts
We have several different components for creating links, which require a `source` parameter (e.g. WorkLink, ItemLink, ImagesLink). This `source` parameter is used for tracking in Segment, and we use the type system to enforce that this parameter only comes from a fixed list of values. However, these types are spread across multiple files.
This patch makes a few changes to make this easier to manage:
* The types are now defined in a single file `segment-values.ts`. This is a similar approach to what we've done with e.g. microcopy – it pulls all these magic strings into one place, so they can be reviewed and discussed as a single entity.
* There's a new ConceptLink component for tracking clicks to concept pages – we think, for example, that genre pages will be pretty popular, and this lays …
=> Tidy up the Download component; add a ConceptLink component; consolidate Segment values

catalogue/webapp/components/WorkDetails/WorkDetails.tsx, catalogue/webapp/components/WorksLink/index.tsx, catalogue/webapp/services/wellcome/catalogue/types/index.ts, common/data/segment-values.ts
Users looking to explore language-related searches from individual works pages. 
It allows them to make a filtered language search directly from the listed languages on the works page, as they can currently do with Type/Technique, Series, and Contributors.
--
for #9651 
On individual works pages, languages are a list of buttons/links that take you to a filtered language search. 
Languages was previously listed with ```<WorkDetailsList>``` (not <...Text> as mentioned in commit a3a2781 and now uses the ```<WorkDetailsTags>``` component to display buttons - comparison here:
To avoid the error  _"Type 'undefined' is not assignable to type 'string'"_. after first PR/failed buildkite checks, i adjusted the Language type in ```types > index.ts```
```typescript
type Language = {
id: string; …
```
=> Languages on work pages are buttons leading to language filtered search

catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx, catalogue/webapp/components/Work/Work.tsx, catalogue/webapp/components/WorkDetails/WorkDetails.tsx, catalogue/webapp/components/WorkHeader/WorkHeader.tsx, catalogue/webapp/hooks/useTransformedManifest.ts, catalogue/webapp/pages/works/[workId]/download.tsx, catalogue/webapp/pages/works/[workId]/items.tsx, catalogue/webapp/services/iiif/fetch/manifest.ts, toggles/webapp/toggles.ts
For https://github.com/wellcomecollection/wellcomecollection.org/issues/9690
This is a bit of a hack and won't work everywhere (e.g. in the URLs in the API toolbar), but I consider that a reasonable sacrifice – it'll all get backed out again soon.
This is one way in which I think the coupling of API model and front-end model is hurting us; I'd prefer to have two separate models and a transformation step in between (like we do for Prismic), and then I'd inject this change there, but that's too big a refactor for this temporary toggle. (And something we should discuss collectively first!)
=> Add a toggle for fetching manifests from iiif-test.wc.org

common/views/components/ButtonSolid/ButtonSolid.tsx, common/views/components/SearchBar/SearchBar.tsx
Fixes #9638 
This was the only place we had the `size="large"` button, so I've removed `large` as an option altogether. Don't know if we want to make the remaining options 'small' and 'large' rather than 'small' and 'medium', but probably one for another PR if so.
I think we may be able to do something similar to this in the `NewsletterPromo` where the button is made bigger thanks to a `ShameButtonWrap`.
=> Make search button same height as input

common/next/next.config.js
I see this warning every time I build, but I think this makes it happy.
=> Fix the warning about an empty string in assetPrefix

catalogue/webapp/test/fixtures/iiif/manifests/b16641097.ts, catalogue/webapp/test/fixtures/iiif/manifests/b3223756x.ts, catalogue/webapp/test/utils/iiif.test.ts, catalogue/webapp/utils/iiif/v3/index.ts
This is one of the changes with the new IIIF manifests from DLCS: previously every video would have a "Choice" in the body, because DLCS was offering both MP4 and WebM options.
It now only offers MP4, so some videos no longer have a "Choice" -- the only option is the single MP4.  But we can't remove the "Choice" handling entirely, because some videos still have a "Choice", e.g. for multiple resolutions.
Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/9724
=> Fix our handling of IIIF videos without a "Choice" in the body

playwright/test/concept.test.ts, playwright/test/selectors/concepts.ts
Having settled on the new tab order in concepts pages, I forgot to update this pair of tests that expected the old tab order.
This is a quick solution (moving the click to the other side of the pair in the same format as before).
At some point, I'd like to update those existing tests to use the POM I defined for the genre ones.
=> Reordered tabs quickfix

common/hooks/useAVTracking.ts
☝️ 
When the `audio_` and `video_progress` events fire, it adds the percent progressed to a cache and these progress events won't fire again even if you scrub back in the video and pass the same percentage threshold again. But currently we don't reset this cache when you get to the end of a piece of audio or video (and this is out of step with how the built in video events work).
This PR resets the cache when the `complete` event fires.
=> Clear cachedSteps after an a/v complete event

playwright/test/concept.test.ts, playwright/test/selectors/concepts.ts
Get rid of the new test that is failing on mobile.
I've eyeballed it using test:debug:mobile, and it is working as I expected, so I don't know why it's failing.
It's a new test that I added this morning because I thought it might be neat to ensure that the expected default tabs are shown at startup, but I think this is essentially covered by the All Works link tests anyway.
=> Reordered tabs quickfix mobile

content/webapp/services/prismic/fetch/index.ts
We have failing e2e tests because when somebody calls this client-side fetcher, the component is being given the literal JSON string instead of the parsed JSON object – previously we passed the string into a superjson call, which would parse it into an object, but now we need to do that ourselves.
=> This should return parsed JSON, not the literal string

common/views/components/SegmentedControl/SegmentedControl.tsx, content/webapp/components/EventsByMonth/EventsByMonth.tsx, content/webapp/pages/guides/index.tsx
This is another case of SegmentedControl (and EventsByMonth) being a bit of a weird component, and that hiding a bug.
Rather than using some React state with `useState()`, we were passing in a callback to fire whenever the state value was updated.  Something like:
```typescript
class EventsByMonth extends Component<Props, State> {
state = {
activeId: undefined,
}
render(): JSX.Element {
...
<SegmentedControl
id="monthControls"
activeId={groups[0]?.id}
onActiveIdChange={activeId => this.setState({ activeId })
/>
...
```
Inside SegmentedControl, it was using some regular React state with `useState`, and we had to call `onActiveIdChange` manually.  The intention was probably something like:
```typescript
const SegmentedControl = ({ id, activeId }) => {
...
const [activeIdInternal, …
```
=> Use a vanilla bit of React state in SegmentedControl; fix events on What's On

content/webapp/services/prismic/fetch/exhibitions.ts, content/webapp/services/prismic/fetch/index.ts
When I replaced response.text() with response.json() for the shared fetcher, I didn't realise exhibitions had its own fetcher.  It shouldn't; making it use the common one fixes the (hopefully final) e2e issue.
=> Use a single function for client-side fetching

identity/webapp/src/frontend/MyAccount/ChangeEmail.test.tsx, identity/webapp/src/frontend/MyAccount/ChangePassword.test.tsx, identity/webapp/src/frontend/MyAccount/DeleteAccount.test.tsx, identity/webapp/src/frontend/MyAccount/MyAccount.test.tsx, identity/webapp/src/frontend/components/PasswordInput/PasswordInput.test.tsx
Devs and tests
Noticed `identity` tests[ were logging a lot of errors like](https://buildkite.com/wellcomecollection/wc-dot-org-build-plus-test/builds/11156#0187e751-c8e4-44dd-a4eb-9beea4d0e50b);
```
Warning: An update to PasswordInput inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/* fire events that update state */
});
/* assert on the output */
This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
```
which 1) makes it hard to follow what's happening and 2) [wrapping in `act` ensures test behave closer to a browser](https://legacy.reactjs.org/docs/testing-recipes.html#act) when the state is being changed, so I …
=> Wrap state changes in tests in act()

common/next/next.config.js
SWC = "Spot Warning in Console"
It doesn't actually mean that, but it's what happened – I spotted a warning in the console, googled how to fix it, discovered a neat compiler option for even whizzier builds.
=> Add another compiler option to make more use of SWC

common/views/components/Breadcrumb/Breadcrumb.tsx
On the Press page, there's a warning about duplicate keys, because the breadcrumb goes:
Home | About us | (Part of) About us
and so we have two breadcrumb entries with a key `About us`.
Arguably this points to a data issue, but in the meantime we can make React happy by including the prefix in this key to distinguish them.
=> Fix a React warning about duplicate keys in the breadcrumb

.github/workflows/performance.yml, prismic-model/lintPrismicData.ts
The InfoSec team ran an automated security scan of the website this weekend, and part of the report includes a list of external links that weren't scanned (because it was scoped to wellcomecollection.org only).
I skimmed the list, and noticed a handful of preview.wellcomecollection.org links in there – looks like there are a few places where they've been copy/pasted into Prismic. Adding a lint to find them will allow us to clean them up.
(And may also cause preview.wc.org to drop down in Google, because it'll stop being linked from anywhere.)
=> Add a Prismic lint to detect preview.wellcomecollection.org links

common/views/components/SegmentedControl/SegmentedControl.tsx, content/webapp/components/EventsByMonth/EventsByMonth.tsx
☝️ 
Should clear up the pa11y dashboard
This fell through the net when we were refactoring the SegmentedControl and EventsByMonth ([Slack](https://wellcome.slack.com/archives/CUA669WHH/p1683621408922809))
=> Make sure all events by month display if there's no JS

common/utils/dates.ts, content/webapp/components/DateList/index.tsx, content/webapp/components/EventDateList/index.tsx, content/webapp/components/EventStatus/index.tsx, content/webapp/pages/events/[eventId].tsx
The `[eventId].tsx` file is on the large side; this extracts the DateList and EventStatus components as-is into separate files.
The specific motivation for this is that I've spotted a (small) bug in the DateList component: events will still appear as "Full" even after they're finished, for example tomorrow's event:
We're using `isDayPast(endOfEvent)` when I think we want `isPast(endOfEvent)`.
This patch **doesn't** contain a fix for this bug, it just extracts the components into standalone files. I wanted them in the `components` folder so they'd be easier to test, but it's tricky to review any changes to the components at the same time as moving them. This patch leaves them as-is, and I'll do a separate patch for the bugfix.
=> Extract a couple of components from the event page

identity/webapp/src/frontend/MyAccount/ChangeEmail.test.tsx, identity/webapp/src/frontend/MyAccount/ChangePassword.test.tsx, identity/webapp/src/frontend/MyAccount/DeleteAccount.test.tsx, identity/webapp/src/frontend/MyAccount/MyAccount.test.tsx
Tentatively closes https://github.com/wellcomecollection/wellcomecollection.org/pull/9764
The problem is in a test which checks the error message when somebody is trying to update their email address, and doesn't enter anything. The old test is asserting that we send a custom `<div role="alert">` with the error message `"Enter a valid email address"`. This test has become flaky recently, but I don't think the issue is a new one.
---
While running Raphaëlle's patch on my old and slow machine (🐌), I noticed an unusual behaviour – despite clearing the email address input field:
```typescript
await act(async () => {
await userEvent.click(emailAddressInput);
await userEvent.clear(emailAddressInput);
});
```
I was getting a failure on the assertion on the following line:
```typescript …
```
=> Fix the flaky identity tests

catalogue/webapp/test/fixtures/iiif/manifests/b28462270.ts, catalogue/webapp/test/fixtures/iiif/manifests/index.ts, catalogue/webapp/types/manifest.ts, catalogue/webapp/utils/iiif/v3/canvas.test.ts, catalogue/webapp/utils/iiif/v3/canvas.ts
Follows #9728; for #9727.
Some context: there are two types of thumbnail in IIIF:
- a manifest thumbnail (for the whole thing, which we show on the works page)
- a canvas thumbnail (for an individual canvas, which we show on the grid viewer)
Before the DLCS upgrades:
- digitised images would have canvas thumbnails which were IIIF image services
- digitised PDFs wouldn't have any canvas thumbnails; they'd rely on the manifest thumbnail which was a picture of the first page. We were never showing PDFs in the grid viewer, so they didn't need thumbnails
We aren't showing PDFs in the grid viewer… yet… but they do now have thumbnails, as prep for born-digital. This thumbnail is just a static image, not a IIIF image, so they're throwing a client-side error. This patch updates `getThumbnailImage` …
=> Allow looking up canvas thumbnails for digitised PDFs

cache/edge_lambdas/src/redirects.ts
Content team
Redirects readable URL to the relevant page.
I'll prepare a separate PR for the application to production.
Related to #9765
=> Add LBE festival redirect

common/views/themes/utility-classes.ts
☝️ 
Closes #9559 
I ran pa11y locally against urls where I thought this might be a problem and nothing showed up. Not to say they won't when it goes live (at least we'd get to see where they are if that's the case).
=> Remove noscript styles

catalogue/webapp/pages/works/[workId]/items.tsx, catalogue/webapp/services/wellcome/catalogue/works.ts
While testing some stuff for the new IIIF manifests, I noticed that we're loading a lot of work fields for the item page, even though only a handful of them are used.  These fields can be quite large, e.g. the page I'm testing has a large archive tree which is completely wasted.
Only fetching the fields we need should reduce the size of these pages.
I spotted this while looking at https://github.com/wellcomecollection/wellcomecollection.org/issues/9786; for that example it reduces the size of the initial page load by **40%**.
=> Reduce the amount of data we fetch on item pages

catalogue/webapp/components/WorksSearchResult/WorksSearchResult.styles.tsx, common/views/components/FindUs/FindUs.tsx, common/views/components/SegmentedControl/SegmentedControl.tsx, common/views/themes/utility-classes.ts, content/webapp/components/BookPromo/BookPromo.tsx, content/webapp/components/Card/Card.tsx, content/webapp/components/FeaturedCard/FeaturedCard.tsx
Maintenance
- Removes `.plain-link` utility class. The logic behind it (apart from "away with utility classes" ) is to aim to align OR expose discrepancies in link/hover behaviours. The current mindset is to have links in copy be underlined by default and have the underline disappear on hover. Most of these go a different way, but aren't considered copy text (e.g. Book Promo blocks)
- Everywhere where it was used that made sense I moved the styles within the component itself.
- I've addressed all instances in the ticket itself, not _fixing_ anything but might be a good one to show to someone helping us set up a design system? (@DominiqueMarshall @jennpb I could create a separate ticket with those instances if that's useful? )
For more details, ticket is:
Closes #9557
=> Remove plain-link utility class

common/package.json, content/webapp/package.json, content/webapp/services/prismic/transformers/articles.ts, content/webapp/utils/reading-time.test.ts, content/webapp/utils/reading-time.ts
* Include quotes in the reading time calculate
* Round up the number of minutes, rather than to the nearest integer
* Move the code out into a separate file; add proper types
=> Tweak how we calculate reading time on articles

catalogue/webapp/utils/iiif/v3/index.ts
This is somewhat speculative fix for https://github.com/wellcomecollection/wellcomecollection.org/issues/9786
The auth URLs in the new manifests have iiif-test.wc.org as their hostname, so they're not being matched properly here. In the long term, I think we should probably find a less fragile way to do this, but in the meantime I think this will get things working correctly again.
=> Match on auth URLs from iiif-test.wc.org

cardigan/.storybook/manager-head.html, cardigan/stories/global/typography/typography.stories.mdx, cardigan/stories/global/typography/typography.stories.tsx
☝️ 
This is to replace the [Type scale table currently in GitBook](https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/SreoRFZHSJqTwnKOTN2h/foundations/design-tokens#type-scale) with contains out of date information. Using a story from Storybook should ensure it stays up to date.
=> Add a simpler type scale table for embedding in GitBook

cardigan/stories/components/Buttons/Buttons.stories.tsx, catalogue/webapp/components/IIIFSearchWithin/IIIFSearchWithin.tsx, catalogue/webapp/components/IIIFViewer/IIIFCanvasThumbnail.tsx, catalogue/webapp/components/IIIFViewer/ViewerSidebar.tsx, catalogue/webapp/components/IIIFViewer/ViewerStructures.tsx, catalogue/webapp/components/IIIFViewer/ViewerTopBar.tsx, catalogue/webapp/components/PaletteColorPicker/PaletteColorPicker.tsx, catalogue/webapp/components/WorkDetails/ExplanatoryText.tsx, catalogue/webapp/components/WorkDetails/OnlineResources.tsx, common/views/components/ApiToolbar/index.tsx, common/views/components/AudioPlayer/AudioPlayer.tsx, common/views/components/ButtonSolid/ButtonSolid.tsx, common/views/components/ClearSearch/ClearSearch.tsx, common/views/components/CookieNotice/CookieNotice.tsx, common/views/components/ExpandableList/ExpandableList.tsx, common/views/components/Footer/index.tsx, common/views/components/Iframe/Iframe.tsx, common/views/components/InfoBanner/InfoBanner.tsx, common/views/components/Pagination/Pagination.tsx, common/views/components/PopupDialog/PopupDialog.tsx, common/views/components/SearchTabs/SearchTabs.BaseTabs.tsx, common/views/components/SegmentedControl/SegmentedControl.tsx, common/views/components/TabNav/TabNav.styles.tsx, common/views/components/Tasl/Tasl.tsx, common/views/components/ToolbarSegmentedControl/ToolbarSegmentedControl.tsx, common/views/components/VideoEmbed/VideoEmbed.tsx, common/views/themes/base/wellcome-normalize.ts, common/views/themes/utility-classes.ts, content/webapp/components/GifVideo/GifVideo.tsx, content/webapp/components/ZoomedPrismicImage/ZoomedPrismicImage.tsx
Maintenance
As part of removing utility classes, we decided `plain-button` was actually containing styles that should be set on all `buttons` in `wellcome-normalize`. This then
- Deletes the class
- Removes instances where it's used
- Remove duplicate styling properties.
Closes #9541
=> .plain-button refactor

common/views/components/Iframe/Iframe.tsx, common/views/components/SegmentedControl/SegmentedControl.tsx, common/views/themes/utility-classes.ts
Maintenance
In line with removal of utility classes. This one felt pretty anti-a11y to us from the get go and we thought we should analyze what it was used for.. Turns out I couldn't see any difference. In the `IFrame` one, the span isn't focusable..? As for the `SegmentedControl`, the exact same styles are already set on the `a` element further up the tree. So this class wasn't doing anything and I'm just removing it.
Closes #9558
=> Remove no-visible-focus class

common/views/components/TabNav/TabNav.tsx, playwright/test/pages/concept.ts
Accessibility
This was flagged as repetitive (the `role` being `tablist/tab` already, the user _knows_ it's a tab) in the 2021 a11y report for the old search tabs. As we copy/pasted that in the new `TabNav` component, I'm changing it there.
Closes #8918
=> Remove repetitive Tabs reference

cardigan/.storybook/manager-head.html, cardigan/stories/global/spacing/gitbook.spacing.stories.mdx, cardigan/stories/global/spacing/spacing.stories.tsx, cardigan/stories/global/typography/gitbook.typography.stories.mdx, cardigan/stories/global/typography/typography.stories.mdx
Closes #9807
Adding a spacing table for use in GitBook (to replace the static values there currently)
Instead of hiding stories on an ad hoc basis, I figured it would make more sense to have a dedicated 'GitBook' section in Storybook that doesn't show up in the sidebar (but that we can still embed).
=> Make gitbook specific section for spacing/typography

cardigan/stories/global/typography/typography.stories.tsx
☝️ 
This is the table that displays in GitBook. Adding the column header at @DominiqueMarshall's request.
=> Include default table header background

cache/modules/cloudfront_policies/cache_policies.tf, cache/modules/cloudfront_policies/locals.tf, catalogue/webapp/pages/search/index.tsx, catalogue/webapp/pages/search/works.tsx, catalogue/webapp/services/wellcome/catalogue/types/api.ts
Maintenance
See ticket for more details, @harrisonpim has confirmed this hasn't been used and isn't considered to be in the future. It's been copy/pasted in from the old search (and then questioned).
I'm not sure if anything needs applying in Terraform for the policy change and tried, but am not as comfortable making the Scala changes in `catalogue-api`, if anyone could assist? Happy to do it with some guidance. (@jamieparkinson / @alexwlchan / @paul-butcher )
Part of #9047
=> Remove _queryType references

cardigan/stories/global/palette/gitbook.palette.stories.mdx, cardigan/stories/global/palette/palette.stories.tsx
Closes #9808
A table in Storybook to embed in Gitbook to replace [the static one](https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/SreoRFZHSJqTwnKOTN2h/foundations/design-tokens#3.-colour) that is out of date.
=> Add colour table for gitbook

content/webapp/components/DateList/DateList.test.tsx, content/webapp/components/EventDateList/EventDateList.test.tsx, content/webapp/components/EventDateList/index.tsx
Follows https://github.com/wellcomecollection/wellcomecollection.org/pull/9772
Currently when you have a schedule on a page, DateList uses `isDayPast` to determine whether to show "Past" for a scheduled item – this means that an event may continue to show as "Available" or "Full" even after it's finished, until the end of that day.
This patch changes it to use `isPast`, so as soon as the event finishes it will switch to showing "Past" in the schedule. I've also added a couple of tests for the component.
=> Fix a bug in DateList on event pages

content/webapp/components/EventSchedule/EventScheduleItem.tsx
When an event is at more than one location, we separate each location with a pipe
=> Allow multiple locations to appear on EventScheduleItems

catalogue/webapp/components/IIIFSearchWithin/IIIFSearchWithin.tsx, catalogue/webapp/components/IIIFViewer/ViewerStructures.tsx, catalogue/webapp/components/PaletteColorPicker/PaletteColorPicker.tsx, common/views/components/Buttons/Control/Control.tsx, common/views/components/CookieNotice/CookieNotice.tsx, common/views/components/InfoBanner/InfoBanner.tsx, common/views/components/SearchTabs/SearchTabs.BaseTabs.tsx, common/views/components/VideoEmbed/VideoEmbed.tsx, common/views/themes/base/wellcome-normalize.ts, content/webapp/components/TitledTextList/TitledTextList.tsx, dash/webapp/pages/toggles.tsx
Part of #9810 (zoom-in cursor on  IIIF images coming in separate PR)
People who want buttons to have a pointer cursor by default
Adding the property declaration to `button`s in `wellcome-normalize.ts` (and removing the now redundant declarations)
=> Add cursor:pointer to all buttons (remove dup declarations)

catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx, catalogue/webapp/components/IIIFSearchWithin/IIIFSearchWithin.tsx, catalogue/webapp/components/IIIFViewer/GridViewer.tsx, catalogue/webapp/components/IIIFViewer/IIIFViewer.tsx, catalogue/webapp/components/IIIFViewer/ImageViewer.tsx, catalogue/webapp/components/IIIFViewer/ImageViewerControls.tsx, catalogue/webapp/components/IIIFViewer/MainViewer.tsx, catalogue/webapp/components/IIIFViewer/MultipleManifestList.tsx, catalogue/webapp/components/IIIFViewer/NoScriptViewer.tsx, catalogue/webapp/components/IIIFViewer/ViewerStructures.tsx, catalogue/webapp/components/IIIFViewer/ViewerTopBar.tsx, catalogue/webapp/components/IIIFViewer/ZoomedImage.tsx, catalogue/webapp/components/ItemLink/index.tsx, catalogue/webapp/components/ItemViewerContext/ItemViewerContext.tsx, catalogue/webapp/components/WorkDetails/WorkDetails.tsx, catalogue/webapp/components/WorkTabbedNav/WorkTabbedNav.tsx, catalogue/webapp/pages/works/[workId]/download.tsx, catalogue/webapp/pages/works/[workId]/items.tsx, common/data/segment-values.ts, common/views/components/ClearSearch/ClearSearch.tsx
Fixes #9650
There are quite a few file changes, but most of the magic happens in **IIIFSearchWithin.tsx** and **ItemLink/index.tsx**. The rest are the result of var name changes and a change to the parameters the the itemLink function accepts.
This PR changes the form in the IIIFSearchWithin component to update the item page url with the search query, rather than just holding it in state. This means searching within an item results in a page view, that will be tracked via Segment, with a source of 'search_within_submit':
Other bonuses include:
- changing the volume now causes the search to be redone for the volume being viewed. Previously, if a user switched volumes after conducting a search, the old results would remain and the search result links wouldn't work.
- clearing the text input …
=> Search within refactor

catalogue/webapp/components/IIIFSearchWithin/IIIFSearchWithin.tsx, catalogue/webapp/components/IIIFViewer/GridViewer.tsx, catalogue/webapp/components/IIIFViewer/MultipleManifestList.tsx, catalogue/webapp/components/IIIFViewer/ViewerStructures.tsx
The next/links should replace the current history state instead of adding a new URL into the browser’s history stack.
The expected behaviour when using the browser back button is to go to the previous page, not the previous state of the viewer on the item page.
=> Amend next links

.buildkite/pipeline.deployment.yml
I've added this to the task that triggers the e2es rather than the e2es themselves because:
* it keeps everything in one file
* we still want the different flavours of e2e to run concurrently, but I was too lazy to work out how concurrency gates work https://buildkite.com/docs/pipelines/controlling-concurrency
Potentially we could still get flakiness if something else triggers an e2e test mid-deployment (e.g. an API deployment), but let's cross that bridge when we come to it.
=> Try adding a concurrency group to the e2e tests

common/package.json, identity/webapp/package.json, yarn.lock
Quoting the [latest release of next-transpile-modules "The End"](https://github.com/martpie/next-transpile-modules/releases/tag/the-end):
> All features of next-transpile-modules are now natively integrated in Next.js 13.1: next-transpile-modules is now officially deprecated, and the repository will be archived soon.
We're already running Next.js 13.2, and we've already set up the `transpilePackages` setting suggested in the migration guide.
Closes #9704
=> Remove our dependency on next-transpile-modules

cache/edge_lambdas/src/origin.ts, cache/edge_lambdas/src/redirector.ts, cache/edge_lambdas/src/rejection.test.ts, cache/edge_lambdas/src/rejection.ts
This implements a basic spam detection heuristic for our search traffic. The comments in the code explain the rules in more detail, but the tl;dr is:
* 🚮 if you're using a query parameter we obviously don't use
* 🚮 if you claim to be a bot and then use spammy keywords like "crypto" or "casino"
* 🚮 if there are a suspiciously high number of Chinese chars in your query (higher threshold for people than bots)
Combined, these three measures would filter our ~75% of the search traffic from the last fortnight. 
This PR just implements the heuristic as a pure function; it doesn't wire it up to anything yet – I’ll handle that in a separate patch.
=> Implement a basic spam detection heuristic

common/utils/dates.ts, content/webapp/services/prismic/events.test.ts, content/webapp/services/prismic/events.ts
This changes the behaviour of `isEventPast` slightly, to avoid confusion on the same day as an event but after the event has finished.
This function is used on event schedule items to determine whether to show booking information below a scheduled event, e.g. "Just turn up" or a link to Eventbrite tickets.  But it wouldn't mark an event as past until the end of that day, meaning an event could still be showing "Just turn up" even after it's over!
e.g. an event finishes at 2pm, and somebody looks at the site at 3pm. Because `isEventPast` looks to see if the day of the event has passed, it says "false" and the page shows "Just turn up".  This is misleading! There's nothing to turn up to!
Now it marks events as past as soon as the event ends, avoiding the possibility of confusion.
(It also …
=> An event is past as soon as it's done, not the next day

catalogue/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx, playwright/test/search-images.test.ts, playwright/test/search.test.ts
a11y, html semantics
The results were wrapped in a `ul` but its children were divs containing more `ul`s. It doesn't need to be a list at that level and was flagged by Lighthouse.
=> Remove unnecessary `ul` wrapper in Image grid

.buildkite/scripts/trigger-e2e.sh
In my previous change, I added a concurrency group to the e2e trigger -- so the e2es wouldn't be triggered at the same time as a running deploy, but they could run at the same time as a deploy.  I think adding the concurrency group here should fix that.
These illustrations show what I think was happening; steps in the concurrency group are in yellow. Time moves down the page.
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Add the concurrency group to _actually_ running the e2es

.buildkite/scripts/trigger-e2e.sh
Reverts wellcomecollection/wellcomecollection.org#9875
This is breaking the builds; see https://buildkite.com/wellcomecollection/wc-dot-org-deployment/builds/2448#018870f9-4ac8-4ae3-b96d-66d76817aa06
> 422 Concurrency cannot be set for steps that trigger builds
I think it's the right idea, but wrong implementation.
=> Revert "Add the concurrency group to _actually_ running the e2es"

.buildkite/pipeline.deployment.yml, .buildkite/scripts/deploy_all_apps.sh
It took me a while to wrap my head around this, but I think I get it now.
This implements the "concurrency gate" pattern described in Buildkite's support blog here: https://buildkite.com/blog/concurrency-gates
I'm not going to explain it in the PR description, because there's a comment in the Buildkite YAML and that's the thing we'll have to follow in six months time when we're scratching our heads at this code. If I need to clarify stuff, I'll update that comment rather than this description.
This is an offshoot of the work to get e2es running on pull requests: https://github.com/wellcomecollection/wellcomecollection.org/issues/9876
=> Add a "concurrency gate" around front-end deployments

cache/cloudfront_e2e.tf, cache/dns.tf, cache/modules/wc_org_cloudfront/outputs.tf, cache/terraform.tf, catalogue/terraform/locals.tf, catalogue/terraform/main.tf, catalogue/terraform/stack/main.tf, content/terraform/locals.tf, content/terraform/main.tf, content/terraform/stack/main.tf, identity/terraform/locals.tf, identity/terraform/main.tf, identity/terraform/stack/main.tf, infrastructure/experience/main.tf, infrastructure/experience/outputs.tf, infrastructure/modules/service/main.tf, infrastructure/modules/service/variables.tf
Follows #9880; part of #9876
This creates a new version of the site which is available at https://www-e2e.wellcomecollection.org/ – an environment designed for use with our end-to-end tests. It has the same setup as stage/prod, including:
* ECS app configuration
* EC2 load balancers
* CloudFront and edge Lambdas
It's an environment that we can deploy stuff into quickly for testing, and have it mirror our real setup. The intention is eventually that we'll be able to deploy directly from PRs into this environment, and run end-to-end tests against it.
Nothing is deploying into this environment yet, so we can merge this before I go on leave, and nothing should break.
* The stage/e2e environments get half the resources of the apps in our prod environment, and I'd be inclined to cut that event …
=> Create a third environment for running our apps

content/webapp/utils/event-series.test.ts, content/webapp/utils/event-series.ts
I was reading the event series code as part of https://github.com/wellcomecollection/wellcomecollection.org/issues/9874, and I was struggling to follow how it works (even though I think I wrote the current implementation!).
There are some subtleties in how `isUpcoming` work which aren't adequately covered in the tests, because we test it at a distance. I've tried to:
* Add a couple of tests for that function to show how it works by example
* Use named variables for the example dates so it's clearer what's expected (e.g. `mondayAt7am` / `mondayAt9am`)
There shouldn't be any changes to the actual behaviour, just more tests.
=> Make the tests for event-series utils a bit more readable, add more test cases

.buildkite/pipeline.yml
Raphaëlle noticed that the 'deploy dash' is the longest deploy task in a build on main; almost 30s longer than any other deploy step.  Most of the time is spent in the "Building Docker Compose Service: dash" step, which includes the following line:
No pre-built image found from a previous 'build' step for this
service and config file. Building image...
I think the reason the other apps can deploy faster is because they already have prebuilt images; dash has no such luck.  Adding a step where we build dash at the same time as we build the other images should speed up this step.
For https://github.com/wellcomecollection/wellcomecollection.org/issues/9890
=> Build dash when we build the other Docker images in Buildkite

.buildkite/scripts/trigger-e2e.sh, playwright/test/view-items.test.ts
We had a lot of issues on the week of 29/05, where end to end tests were repeatedly failing. A lot is being done to improve and fix them, but in the meantime we chose to comment out the tests that caused the most issues.[ I've created a follow-up ticket so we remember to uncomment them](https://github.com/wellcomecollection/wellcomecollection.org/issues/9898).
I've also removed the `soft_fail: true` we'd hoped would help ([from this PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/9892/files)), but now that we're hoping all tests pass, am removing it.
Hopefully makes e2es test flags useful again for the time being.
=> E2E: Comment out usual failing tests

catalogue/webapp/components/WorkDetails/WorkDetails.tsx
[Issue](https://github.com/wellcomecollection/wellcomecollection.org/issues/9899)
Archivists? 
Making the accession number visible on the work details page, so that the work's provenance details can be more easily provided to anyone who requests
=> Add accession number to identifiers section if present

common/views/components/styled/SpacingComponent.tsx, common/views/themes/config.ts, common/views/themes/typography.ts
People who want consistent spacing regardless of how the page has been built in Prismic
Checking if back-to-back text slices have been added and if so, using the spacing rules we created for text, rather than the spacing rules we created between components
=> Account for back-to-back Prismic text block spacing

common/views/components/styled/SpacingComponent.tsx
Website design/users
To account for Content's new way of creating paragraph blocks (one Text per paragraph), [a little `has()` magic was done](https://github.com/wellcomecollection/wellcomecollection.org/commit/d68500fce9825d05f8ee1a00f5ed6264c6dd5661), which fixed it. It didn't account for other pages that also used `spacing-component` with `spaced-text`, such as works, which meant that the margins were a bit out of whack. 
I believe this fix does what we want, as we only want pages created with Prismic to have that styling, where `.body-text` is used in conjunction with `.spaced-text`. Need to ensure the logic is sound with the review, though. Maybe we actually want to add a class to specifically target this instead?
[See Slack …
=> Spacing for Body slices only

content/webapp/pages/stories/index.tsx
This shouldn't really ever happen but if it does, even briefly, it would previously break the stories landing page. I've also done a slight refactor to bail out of some loops as soon as we have enough series to render.
=> Handle the case that a comic doesn't have series

content/webapp/components/SoundCloudEmbed/SoundCloudEmbed.tsx, content/webapp/services/prismic/fetch/articles.ts, prismic-model/sliceAnalysis.ts, prismic-model/src/parts/article-body.ts, prismic-model/src/parts/body.ts
Maintenance
We have a few legacy slices that we can get rid of ([see analysis](https://docs.google.com/presentation/d/1RytMltnIDQ44BXEa8JR_2-hXslaLEogo49jopO3qLuY/edit#slide=id.g2501fc7a4df_0_0)). This brings it down from a total 27 to 22!
This PR deals with `vimeoVideoEmbed`, `instagramEmbed`, `twitterEmbed` and `soundcloudEmbed`.
[Danny has agreed to these four being removed](https://wellcome.slack.com/archives/C3N7J05TK/p1686302036964129) as there are no instance of them anywhere on the website.
They have all replaced by `Embed` a while ago (even though Vimeo doesn't seem styled nicely, it works). Currently, only YouTube and SoundCloud items are being rendered by `Embed`.
**Added later on** 
I've also removed `youtubeVideoEmbed` as it was labelled as Deprecated for a very long time. …
=> Remove unused embeds from Prismic slice offer

common/utils/setCacheControl.ts
setting a Cache-Control header seems to do the trick, as opposed to deleting the header
=> Set Cache-Control timing

.github/workflows/chromatic.yml
Devs
When adding/modifying a story, Chromatic should build so we can see it. Currently only builds if we edit a component directly.
=> Remove cardigan from ignore list

common/utils/grammar.ts, common/views/components/styled/SpacingComponent.tsx, content/webapp/components/Body/Body.tsx
For #9918 
We currently don't have a good way of targeting neighbouring slices from Prismic and applying any specific styles at their intersection (for example, we might want to add dividing lines when two specific distinct components appear next to each other).
This PR adds a class and a data-slice attribute that exposes the slice type from Prismic onto the `SpacingComponent` (that wraps each slice). We can then override the `SpacingComponent` spacing where necessary and add any other intra-component styles.
This also means we don't need to use the `has()` selector anymore (which isn't yet supported in Firefox, and will never be supported in IE).
=> Add sliceType to SpacingComponent as class/data-slice

catalogue/webapp/components/IIIFViewer/MultipleManifestList.tsx, catalogue/webapp/components/IIIFViewer/ViewerSidebar.tsx, catalogue/webapp/services/iiif/transformers/manifest.ts, catalogue/webapp/utils/iiif/v3/index.ts
For #9901
The structure of this [multi volume work](https://wellcomecollection.org/works/z9gxzppu/items?manifest=4) is slightly different to others we have encountered.
Instead of the manifest (type: 'Collection') having an array of items type: Manifest, it had an array of items which were also type: 'Collection'. These Collections then contained arrays of items of type: Manifest.
We only ever looked for manifests on the initial items array, so never found the nested manifest items.
I don't know whether we need to present this additional structure in the UI, but for now I have included all the manifests together under the volumes section:
This also fixes the volume count being displayed on the work page.
Before:
After:
=> Volumes copies

common/views/components/DropdownButton/DropdownButton.tsx
an extra consideration. The previous work sorted it out on the initial load.
But did not run when the children elements got updated, even though `focusables` list gets updated.
=> set dropdown children to tabIndex -1 on mount

catalogue/webapp/pages/search/images.tsx, catalogue/webapp/pages/search/works.tsx
We were sending a source of 'unknown' for pagination links on search results pages. Now we send a source of 'search/paginator'
=> add correct source for paginator links

.buildkite/pipeline.yml, catalogue/Dockerfile, content/Dockerfile, dash/webapp/pages/index.tsx, identity/Dockerfile
I don't think we're actually using the output of these tasks (or somebody might have noticed that the dashboard links have been stale for ages), and I think we can get a decent speedup in CI by removing them.
=> Remove the bundleAnalysis tasks from CI; don't install the awscli

catalogue/webapp/utils/spam-detector.ts
We're seeing some 503 timeouts from the API, when somebody tries to search for something that looks suspiciously like poorly-encoded Chinese text. Let's bin it.
=> Expand the range of characters we consider 'suspicious'

catalogue/webapp/components/IIIFViewer/IIIFViewer.tsx, catalogue/webapp/pages/works/[workId]/items.tsx
For #9380
Makes the NoScriptViewer available to use when javascript is disabled. Previously item pages would show no content in this scenario.
Before:
After:
The NoScriptViewer allows for pagination through thumbnails and main images. However, at the moment
it [can't cope with items that have a clickthrough service](https://github.com/wellcomecollection/wellcomecollection.org/issues/9428). In this case it will be unable to load the images:
It also can't yet cope with multi volume items and will only display the first volume.
=> Nojs viewer

catalogue/webapp/components/IIIFViewer/MainViewer.tsx
Fixes #9815
Takes the image rotation into account, so that search term highlights are always in the correct place:
=> Rotate highlights

catalogue/webapp/pages/search/index.tsx, common/views/components/BackToResults/BackToResults.tsx
Users of the overview page when searching should be able to return back to the search page when they click on a work.
now, the question is if I should expand this logic and feature to stories pages?
simply ensuring the search result page (Overview) updates the SearchContext was enough for the stories page to acknowledge that there was a search happening.
=> Overview page should set link to search context

content/webapp/components/EventSchedule/EventSchedule.tsx, content/webapp/pages/events/[eventId].tsx, content/webapp/services/prismic/events.ts
For https://github.com/wellcomecollection/wellcomecollection.org/issues/9949
There's a Slack discussion about this design, including screenshots: https://wellcome.slack.com/archives/CUA669WHH/p1687161340728489
=> Split the list of scheduled items into Events/Past Events

catalogue/webapp/components/ExpandedImage/ExpandedImage.tsx, catalogue/webapp/components/Work/Work.tsx, catalogue/webapp/components/WorkDetails/WorkDetails.tsx, catalogue/webapp/components/WorkHeader/WorkHeader.tsx, catalogue/webapp/hooks/useTransformedManifest.ts, catalogue/webapp/pages/works/[workId]/download.tsx, catalogue/webapp/pages/works/[workId]/items.tsx, catalogue/webapp/services/iiif/fetch/manifest.ts, toggles/webapp/toggles.ts
This is for #9723 – we no longer need this toggle because the DLCS upgrade is done, and it seems to be causing errors for a few users who still have the toggle enabled. Removing it should fix these issues.
=> Remove the old iiif-test.wc.org toggle

prismic-model/deployType.ts, prismic-model/deployTypes.ts, prismic-model/package.json
Devs who play with Prismic models
Relates to #9953 
1. Allows for all types to be run through at the same time instead of having to manually do them one by one
2. Adds a prompt when an update happens to encourage the dev to go save a doc in Prismic, as that's needed to have the changes be taken into account.
Looks like this if two types have a change, user gets asked to approve one at a time:
When only some get approved and others not:
Individual updates still work but user gets prompted:
=> Add `deployTypes` script for all types at the same time

content/webapp/utils/event-series.test.ts, content/webapp/utils/event-series.ts
The naming here is a bit misleading -- we want upcoming or in-progress events to show under the 'Events' header, because if an event isn't upcoming it moves straight to 'Past events'.
This is causing issues for the Land Bodies Ecology Festival, which is already showing Day 1 under 'Past events' even though it's still happening today.
See Slack discussion: https://wellcome.slack.com/archives/C8X9YKM5X/p1687427559655459
=> An event is upcoming if it hasn't finished yet

catalogue/webapp/package.json, catalogue/webapp/utils/iiif/v3/index.ts, yarn.lock
The only thing that's being modified in the reduce() loop is the accumulator `acc`; we don't need to clone the `structures` variable here, as it's an immutable array.
=> Remove an unnecessary use of lodash.clonedeep

content/webapp/pages/event-series/[eventSeriesId].tsx, content/webapp/utils/event-series.ts
Issue #9960
Users looking at our Event Series pages
For example, [Land Body Ecologies Festival](https://wellcomecollection.org/event-series/ZFt3UBQAAMFmEIya)
Using plainer language and making the text more scannable. 
| Current | Changed to | 
| ------------- | ------------- |
| What's next | Coming up  |
| No events scheduled at the moment, check back soon... | No upcoming events | 
| What we've done before | Past events |
=> Tidy up of headings on event series

cache/edge_lambdas/src/redirector.test.ts, cache/edge_lambdas/src/redirects.ts, common/next/next.config.js
users of the app who wish to do a global search from the account pages
correctly redirects the user out of the sub route.
Note, this does not occur with the other apps because they do not use the subroutes in production.
https://github.com/wellcomecollection/platform/issues/5673
=> set redirect for the global search from identity app

common/views/components/Caption/Caption.tsx, prismic-model/src/parts/captioned-image.ts
Editors have been requesting this as they often have too much copy for captioned images and it makes it difficult to read when it's just in one paragraphs.
It's currently possible to create break-lines, but that's a hack, might as well make this officially multi-line!
I'll deploy the prismic model changes once this is approved and merged in.
=> Make captioned image captions multiline

prismic-model/src/parts/body.ts
Editorial and general confusion
There is a Collection Venue Content Type, and a Collection Venue Slice. Everytime we talk about them we get confused, so I'm opting for a name change on the UI; it makes it clearer and also makes its _purpose_ clearer. The ID remaining the same, this should be inconsequential.
=> Rename Collection venue slice on UI

identity/webapp/next.config.js
users of the app that wish to do a global search from inside the identity app
allows for the proper redirect to exists, that causes minimal side effects.
the identity app is not visible/accessible to the cache lambdas
=> redirect from inside the identity app

prismic-model/src/parts/body.ts
Maintenance, Editorial
Relates to #9993 
- Renames slice on UI for clarity of purpose
- Remove unused features from model
- Remove Sharp-S from some component names (we think it was to indicate they were in beta?)
=> Titled Text List slice changes

cache/modules/cloudfront_policies/locals.tf, catalogue/webapp/components/ImagesLink/index.tsx, catalogue/webapp/components/Sort/Sort.tsx, catalogue/webapp/pages/search/images.tsx, common/views/components/Select/Select.tsx, common/views/components/SelectContainer/SelectContainer.tsx
Image foragers, seeking to chronologically sort their search
Part of [#5668](https://github.com/wellcomecollection/platform/issues/5668)
Add sorting to image search, with the options "Relevance", "Oldest to newest", "Newest to oldest".
Sorting drop down matches existing `/stories` and `/works` with transparent pill. Screenshots below.
=> Sorting to image search, with options "Relevance", "Oldest to newest", "Newest to oldest"

catalogue/webapp/components/SearchPageLayout/SearchPageLayout.tsx, common/views/components/ErrorPage/ErrorPage.tsx, common/views/components/Header/Header.tsx, common/views/components/PageLayout/PageLayout.tsx, content/webapp/pages/index.tsx, content/webapp/pages/visual-stories/index.tsx, content/webapp/pages/visual-stories/v1.tsx, content/webapp/pages/visual-stories/v2.tsx, content/webapp/services/prismic/transformers/guides.ts, content/webapp/services/prismic/transformers/pages.ts, content/webapp/types/guides.ts, content/webapp/types/pages.ts
Maintenance
While working on #9987 I noticed that the `SiteSection` type [was out of date](https://wellcome.slack.com/archives/C3TQSF63C/p1688132628103479), so I added missing sections.
I haven't removed the ones I think are out of date as I'd like to do that as part of the audit instead, although I'll take opinions on `Identity` being one since it doesn't seem to ever be in any form of the main menu?
I've then applied the type across instead of string, which means in-existing sections will now be flagged as.
=> use SiteSection type across platform and update it

catalogue/webapp/pages/concepts/[conceptId].tsx, catalogue/webapp/pages/search/index.tsx, common/utils/search.ts
This refactoring fell out of https://github.com/wellcomecollection/wellcomecollection.org/issues/8339 – I was mucking about with aggregations and it was a bit annoying to have to tell the concept page "here is the type of aggregation, even though you never use it".
As a bonus, the `getQueryResults` method we're using will drop a log if any of the API requests we make to populate the concept page fail.
(It does reduce the data we send to the page, but that's incidental and extremely slight – maybe a kilobyte or two at most. The big gains will come in the next PR.)
=> Simplify the data we pass to concept pages

catalogue/webapp/services/wellcome/catalogue/filters.ts, catalogue/webapp/services/wellcome/catalogue/fixtures/images-aggregations.ts, catalogue/webapp/services/wellcome/catalogue/fixtures/works-aggregations.ts, catalogue/webapp/services/wellcome/catalogue/types/aggregations.ts, catalogue/webapp/services/wellcome/catalogue/types/index.ts, catalogue/webapp/services/wellcome/content/types/api.ts, catalogue/webapp/services/wellcome/content/types/index.ts
We only need the aggregations to build the filters. Passing the full Catalogue/Content result list here is unnecessary, and creates a brittle type dependency – these filters can say what pieces they need, and that's it.
This is another bit of refactoring in advance of https://github.com/wellcomecollection/wellcomecollection.org/issues/8339.
=> Simplify the types we pass to the filters

common/views/components/SelectContainer/SelectContainer.tsx
Windows users of `/search/images`
for #10003 
I've inserted some styling for `<option>` within `SelectContainer>` that only affects Windows OS users, by enabling them to see the full dropdown menu when navigating `<Sort>` components within a `darkBg` container. 
I've also reverted the `background-color` value from only having `'transparent'` to also including `'black'` (it used to be `'white'` but this caused the pill to be white, which doesn't macth the `/images` theme to use in `darkBg` to match its theme more consistently, without (hopefully) introducing any errors from `'transparent'` only. 
This matches styling on Windows across `/stories` and `/works`. Again, does not affect other users across MacOS, iOS, or Android who all override dropdown styling. 
How this PR looks on Windows. …
=> Windows dropdown pill styling fix for /images darkBg

prismic-model/src/parts/body.ts, prismic-model/src/parts/visual-story-body.ts
Adding a 'Text and image (side-by-side)' slice in the Visual Stories Content Type
=> Add text-and-image slice

prismic-model/src/parts/visual-story-body.ts
Making the text-and-image non-repeating so that it will be consistent with the upcoming text-and-icons slice (on account of Prismic not being able to handle nested repeating fields in a straightforward way).
We don't need content to be grouped in e.g. a `ul`, and we have already solved the problem of adding dividing lines between back-to-back slices of a certain type, so this should be ok from the front end's perspective.
=> Make text-and-image non-repeat

prismic-model/src/parts/body.ts, prismic-model/src/parts/visual-story-body.ts
Devs
Making a slice `description` a named prop instead of a third argument
=> Make description a SliceProp

content/webapp/services/prismic/transformers/exhibitions.ts
Content team ([Slack thread](https://wellcome.slack.com/archives/C8X9YKM5X/p1688562645075639))
Letting them add `event-series` items to the 'About this exhibition' section of an exhibition page
=> Allow event-series in exhibitionOfs

catalogue/webapp/components/IIIFSearchWithin/IIIFSearchWithin.tsx, catalogue/webapp/components/IIIFViewer/GridViewer.tsx, catalogue/webapp/components/IIIFViewer/IIIFViewer.tsx, catalogue/webapp/components/IIIFViewer/ImageViewer.tsx, catalogue/webapp/components/IIIFViewer/MainViewer.tsx, catalogue/webapp/components/IIIFViewer/MultipleManifestList.tsx, catalogue/webapp/components/IIIFViewer/NoScriptViewer.tsx, catalogue/webapp/components/IIIFViewer/ViewerSidebar.tsx, catalogue/webapp/components/IIIFViewer/ViewerStructures.tsx, catalogue/webapp/components/IIIFViewer/ViewerTopBar.tsx, catalogue/webapp/components/IIIFViewer/ZoomedImage.tsx, catalogue/webapp/components/IIIFViewer/index.tsx, catalogue/webapp/pages/works/[workId]/images.tsx, catalogue/webapp/pages/works/[workId]/items.tsx
This is a small piece spun out of #10004, complicated enough to justify its own review, part of https://github.com/wellcomecollection/wellcomecollection.org/issues/8339
Our component architecture looks something like this:
```mermaid
graph LR
I[items.tsx page] --> V[IIIFViewer component]
V --> S[ViewerSidebar component]
V --> T[ViewerTopBar component]
V --> B[ViewerBottomBar component]
```
Right now we're getting the Work object at the top level, extracting some of the IIIF location information from the Work, then passing both the work and the IIIF location down into the components… which get the IIIF information from the Work again.
This is inefficient, and liable to cause confusion – it would be better to extract the specific bits of location information we need right at the top level, …
=> Simplify the data we pass into the IIIF components

common/views/components/Footer/index.tsx, common/views/components/Header/Header.tsx
SEO, a11y, semantics
Makes the container use the header and footer html elements for all they bring to the table for the reasons above.
=> Add header and footer html elements

content/webapp/components/TextAndImageOrIcons/TextAndImageOrIcons.tsx
New slice
Enforces a max of 6 icons on the UI.
Relates to #9977
=> Only display first 6 icons

content/webapp/components/ContentPage/ContentPage.tsx, toggles/webapp/toggles.ts
Polly experiment
Displays an audio player on specified articles (currently only on [A brief history of tattoos](https://wellcomecollection.org/articles/W9m2QxcAAF8AFvE5)). See #10031 for more information.
The toggle has already been deployed.
Since it's behind a toggle I see no harm in merging right away and allowing the team to see the current status. It would allow the team to hear what it sounds like, see what we'd like to tweak, before I go ahead and create 9 more. Also allows a design opinion, and possibly tracking tests.
=> Polly experiment

catalogue/webapp/services/wellcome/catalogue/filters.ts
Stories searchers
Via #10028 part of wider initiative for [stories search #5681](https://github.com/wellcomecollection/platform/issues/5681)
Adds UI to enable users to filter stories by contributor. The highest 20 contributors to the individual search range are displayed in the dropdown. Screenshots below. 
---
=> Filter stories by contributor

cache/modules/cloudfront_policies/locals.tf
Allows `/stories`' contributor filter to work correctly
=> added 'contributors.contributor' to cache

catalogue/webapp/services/wellcome/catalogue/filters.ts
`/search/stories` Format button - incorrectly named 'Format'
Has been corrected to 'Formats' for consistency across search
=> /stories "Format" button renamed "Formats" for consistency

catalogue/webapp/pages/search/stories.tsx
For #10048 - allows users to see 25 results on `/stories`
Increases the results / `pageSize` from 6 to 25, as it is on `/works`
=> changed /stories pageSize to 25

content/webapp/components/SearchResults/AsyncSearchResults.tsx, content/webapp/services/prismic/fetch/books.ts, content/webapp/services/prismic/transformers/body.ts
Everyone
[After talking with Alex on Slack](https://wellcome.slack.com/archives/CUA669WHH/p1689858851451629), I tried a different approach that fixes it.
I fell into a deep rabbit hole though, there's a lot of (seemingly) complex things happening around this component. Not all types are allowed, it gets reordered _somewhere_, there are probably more instances like this one to fix... But I thought I'd start with this ticket only and see what happens with the Content API.
Relates to #10051, closes #10052 as it's a better solution.
=> Allow events in content lists for books

prismic-model/src/parts/article-body.ts
Editors
Adds InfoBlock as an available slice for Stories/Articles.
Relates to #10065
=> Added infoblock slice to article body

catalogue/webapp/pages/search/index.tsx
This is causing a bug on the search page where it sees the variable as defined, so it assumes there are results and renders an empty list of work results.
=> Don't include `works: {}` in the props if there are no search results

common/views/components/LabelsList/LabelsList.tsx, common/views/components/styled/Space.tsx, common/views/themes/default.ts
Devs who want to author space as a [`gap`](https://developer.mozilla.org/en-US/docs/Web/CSS/gap) to avoid having to apply negative space on parent elements.
Adding `column-gap` and `row-gap` as allowable `h` and `v` properties in the `Space` component (so that we can keep our responsive spacing hierarchy with these new properties).
=> Add (flex) gap properties as option for Space component

cardigan/stories/components/PageHeader/PageHeader.stories.tsx, common/services/prismic/content-types.ts, common/views/themes/typography.ts, content/webapp/components/Body/Body.tsx, content/webapp/components/ContentPage/ContentPage.tsx, content/webapp/components/HTMLSerializers/HTMLSerializers.tsx, content/webapp/components/TextAndImageOrIcons/TextAndImageOrIcons.tsx, content/webapp/components/VisualStories/VisualStories.v1.tsx, content/webapp/pages/articles/[articleId].tsx, content/webapp/pages/visual-stories/[visualStoryId].tsx, content/webapp/services/prismic/fetch/visual-stories.ts, content/webapp/services/prismic/transformers/body.ts, content/webapp/services/prismic/transformers/json-ld.ts, content/webapp/services/prismic/transformers/visual-stories.ts, content/webapp/services/prismic/types/body.ts, content/webapp/services/prismic/types/visual-stories.ts, content/webapp/types/body.ts, content/webapp/types/visual-stories.ts
Wiring a `[visualStoryId]` page up to Prismic.
__TODO:__
Relates to #9974
=> Prismic visual story

common/views/components/PopupDialog/PopupDialog.tsx
People who want the popup dialog to display once you click the button
Switching the state of the isActive boolean check (I don't know how this ever worked, or what changed)
=> Get the boolean right

catalogue/webapp/pages/search/images.tsx, catalogue/webapp/pages/search/index.tsx, catalogue/webapp/pages/search/stories.tsx, catalogue/webapp/pages/search/works.tsx
Analysts
Adds a `looksLikeSpam="true"` property to pageviews that are considered to be spam.
Relates to #10091
=> Add a `looksLikeSpam` property on pageviews considered as such

prismic-model/src/parts/body.ts, prismic-model/src/parts/textAndIcons.ts, prismic-model/src/parts/visual-story-body.ts
Part of [#9849](https://github.com/wellcomecollection/wellcomecollection.org/issues/9849)
=> Add textAndIcons to (non-article) body

content/webapp/pages/events/[eventId].tsx
Requested via #10040 
Clarified on [Slack](https://wellcome.slack.com/archives/C3N7J05TK/p1691496054206989). 
Removes the "For..." audience age guidance that derives from a description line related to an Audience label in Prismic. The line only exists on 16+, 18+, and 14-19 labelled events. Removing this retains the label but will no longer display at the bottom of the page layout. 
Age guidance is already made clear in the content body of the event. 
Current state
New state
=> removed "For..." audience section from bottom of page layout

prismic-model/src/articles.ts
Editorial team - articles and stories
Part of #10037 
Removes the outro from articles where present. Stops older articles containing out of date / broken links. Removes outro from the prismic-model
=> removed outro from prismic-model

catalogue/webapp/components/IIIFViewer/IIIFViewer.tsx, catalogue/webapp/components/IIIFViewer/MultipleManifestList.tsx, catalogue/webapp/components/IIIFViewer/Paginators.tsx, catalogue/webapp/components/IIIFViewer/Thumbnails.tsx, catalogue/webapp/components/IIIFViewer/ViewerSidebar.tsx, catalogue/webapp/pages/works/[workId]/items.tsx
For #9966
If a volume has a parent manifest we now fetch it server side so the non javascript version of the item page can display links to the other volumes and the label of the current volume:
=> No js multi volume

content/webapp/components/SearchResults/SearchResults.tsx, content/webapp/types/exhibitions.ts
Part of #9849
Making sure an image associated with an exhibition in a content list slice will render.
__Before__
__After__
=> Render image in exhibition contentList compact cards

content/webapp/components/Exhibition/Exhibition.tsx, content/webapp/services/prismic/transformers/exhibitions.ts, content/webapp/types/exhibitions.ts
Relates to #10041
This is a bit of tidy up, before adding new fields for rendering the resource links we now want.
It stops us rendering anything that is added to the current field under the resource tab:
This is not being used anywhere. I'll remove this field in another PR.
=> Remove resources from exhibitions

common/views/components/NewsletterPromo/NewsletterPromo.tsx, content/webapp/pages/api/newsletter-signup.ts
Marketing
Relates to #10071 
I wasn't able to test this form locally and thought #10126 would do it but had failed to notice how differently the forms worked (Promo vs SignUp). Again, I wasn't able to test locally (if anyone knows how please let me know!), but I followed [what the API documentation said](https://developer.dotdigital.com/reference/add-contact-to-address-book).
=> Add marketingPermissions to Newsletter Promo API

content/webapp/components/SearchResults/SearchResults.tsx, content/webapp/services/prismic/fetch/event-series.ts, content/webapp/services/prismic/fetch/events.ts, content/webapp/services/prismic/transformers/card.ts, content/webapp/services/prismic/transformers/multi-content.ts, content/webapp/services/prismic/types/multi-content.ts, content/webapp/types/multi-content.ts
☝️ 
part of #9849 
Context: we noticed the content team were trying to make things that looked like Compact Cards by using the (now defunct) Media Object List in Prismic. I thought they should already have been able to do this by using a `Card` type and linking to it from within a `content list` in the `body` slice. But we were only getting `cardFetchLinks` inside `pages` and not `events` or `event-series`.
__Before__
__After__
=> Allow card as a contentList type for events and event-series

content/webapp/components/EventCard/EventCard.tsx
People who like images in compact cards.
Getting the image from the right place. E.g. [this exhibition page](https://wellcomecollection.org/exhibitions/Y8VNbhEAAPJM-oki)
__Before__
__After__
=> Look for event card image in the right place

content/webapp/components/ZoomedPrismicImage/ZoomedPrismicImage.tsx
☝️ 
Noticed we don't currently have a way to track usage of the image zoom button in tag manager. Now that we're going to be adding zoomable images to visual stories, it will be good to get a handle on whether this is functionality people are using.
=> Add data-gtm-trigger for tracking image zoom in GTM

playwright/test/concept.test.ts
E2Es
They started breaking this morning ([see Slack convo](https://wellcome.slack.com/archives/C02ANCYL90E/p1692262571556779)), I'm thinking something has changed in the pipeline or in the data we have and Joanna Stephens didn't have works ABOUT her anymore. I flagged it in the channel but am changing the tests to Florence Nightingale in the meantime, it serves the same purpose and I'm thinking she's not likely to have no works about or by her in the future.
=> Change Joanna Stephens to Florence Nightingale in concept tests

content/webapp/pages/events/[eventId].tsx, content/webapp/services/prismic/fetch/articles.ts, content/webapp/services/prismic/fetch/events.ts, content/webapp/services/prismic/fetch/stories-landing.ts, prismic-model/src/articles.ts
Maintenance, devs
Relates to #10148 
I went through `fetchArticles`, `fetchEvents`, and `fetchStoriesLanding`'s graphQueries and aimed to minimise what was being fetched. I went through everywhere it was used and it seems to be all good, looking the same as prod does.
Of course I could've missed something, so code review/local testing is useful here. I think split view is probably the more useful way to look at code changes.
I'm not sure why so much was being fetched, maybe it used to be used in the event's individual pages? Having all the slices mentioned if what could cause the site to break down if process wasn't followed, but they didn't actually seem to be _used_ anywhere.
I used [Prismic's documentation](https://prismic.io/docs/graphquery-rest-api#fields-in-a-group) as well as our …
=> GraphQuery tidy ups/minimalising

content/webapp/components/CaptionedImage/CaptionedImage.tsx
☝️ 
__before__
__after__
From [Slack conversation](https://wellcome.slack.com/archives/C8X9YKM5X/p1692796022655459)
=> Don't apply border radius to caption container

content/webapp/pages/event-series/[eventSeriesId].tsx, content/webapp/utils/event-series.test.ts, content/webapp/utils/event-series.ts
For #10131 
People who want to be able to see all past event-series events
Paginating them by 20
An event-series with more than 20 past events is 'Exploring research': `/event-series/W5Zj_CYAACQALK5B`
Previously, we were getting event-series events and then working out which were past and which were upcoming using our own logic. Now, we're querying Prismic using date filters (so the logic that was being tested is no longer in use, so I got rid of it). This does mean there's an extra query (promisified) to Prismic for these pages.
=> All past event series

content/webapp/services/prismic/fetch-links.ts, content/webapp/services/prismic/fetch/exhibitions.ts
Relates to #10041 
#10121 stopped us rendering the resource fields on an exhibition.
This PR stops removes the fetch-links related to those fields, before we remove them from Prismic.
=> remove fetch-links related to exhibition resources

prismic-model/src/exhibitions.ts, prismic-model/src/visual-stories.ts
Relates to #10041
This replaces the fields in the Resources tab for an exhibition with the fields we need to render the access content as per the new designs: https://github.com/wellcomecollection/wellcomecollection.org/issues/9978
MUST DEPLOY #10160 FIRST
=> Replace resources from model

content/webapp/components/IIIFViewer/IIIFViewer.tsx, content/webapp/components/IIIFViewer/MultipleManifestList.tsx, content/webapp/components/IIIFViewer/ViewerSidebar.tsx, content/webapp/components/ItemViewerContext/ItemViewerContext.tsx, content/webapp/pages/works/[workId]/download.tsx, content/webapp/pages/works/[workId]/items.tsx, content/webapp/services/wellcome/catalogue/types/work.ts, content/webapp/utils/iiif/v3/index.ts
I'm seeing a lot of warnings in the catalogue app logs about "page data is too large". I suspect this may be related to the weekend's outages; even if it isn't, this is a useful optimisation and will make the site load faster.
There are three changes here:
1. **Only send the subset of manifest fields we use on the download page.** Previously we were sending the entire IIIF manifest, but we only use four fields – in particular we don't need the list of individual images/canvases, which can be very large. Now we only send the fields we're using on that page.
Using `/works/rbtxk55p/download` as an example:
* Before = 307.34 kB
* After  =  15.43 kB
That's a ~95% saving in the size of the Next.js props.
2. **Don't send the list of parent manifests if we aren't going to render them.** Currently …
=> Pick some low-hanging fruit to reduce the size of our Next.js props

content/webapp/pages/works/[workId]/download.tsx, content/webapp/utils/works.ts
This is another easy win for page weight and trims the size of download pages with a lot of works in the archive tree.
Taking `/works/huyu25aj/download` as an extreme example:
* Before = 473.53 kB
* After  =   9.73 kB
That's a ~98% reduction in the size of the Next.js props.
=> We only need to send a WorkBasic on download pages

content/webapp/utils/spam-detector.test.ts, content/webapp/utils/spam-detector.ts
Honestly this is a total guess, but I saw some ultra-long queries that are evading our current spam filter and thought maybe making it more aggressive might be helpful as a way to reduce load on the API.
=> Expand the range of characters we consider 'unusual' for spam purposes

content/webapp/pages/search/works.tsx, toggles/webapp/toggles.ts
It seems like the ongoing site flakiness is caused by expensive queries overloading the Elasticsearch cluster; the hope is that having a way to disable aggregations might alleviate some of the load.
=> Add a toggle for disabling aggregations in search

content/webapp/utils/spam-detector.test.ts, content/webapp/utils/spam-detector.ts
* Reduce the number of "unusual" characters required from 25 to 20
* Immediately reject any query that contains emoji
=> Make our spam detection more aggressive

.buildkite/e2e_on_pull_requests/check_if_we_need_to_ask.sh
We can see problems with the e2e tests if Buildkite starts the build (locking in all the environment variables) before the user opens a pull request.  This can cause weird errors in the "check if we need to ask e2es" step in Buildkite, which is resolved if you push a new commit.
The particular error you see in Buildkite is:
jq: error (at <stdin>:4): Cannot index string with string "name"
This error occurs when we call the GitHub API, looking for the "skip e2es" tag on the pull request.  In particular, we're calling the API with the variable `BUILDKITE_PULL_REQUEST=false`, and that's not a valid PR identifier, so the GitHub API returns an error that we fail to parse.
This issue occurs when Buildkite starts a build before the PR is created:
```mermaid
gantt
dateFormat X
axisFormat "" …
```
=> Don't fail checking if we need to ask about e2es

common/data/microcopy.tsx, common/services/prismic/link-resolver.ts, content/webapp/components/Exhibition/Exhibition.tsx, content/webapp/pages/exhibitions/[exhibitionId].tsx, content/webapp/services/prismic/fetch/exhibitions.ts, content/webapp/services/prismic/fetch/visual-stories.ts, content/webapp/services/prismic/transformers/exhibitions.test.ts, content/webapp/services/prismic/transformers/exhibitions.ts, content/webapp/services/prismic/types/exhibitions.ts, content/webapp/types/exhibitions.ts
For #10041 
Uses new Prismic fields to render access resources on exhibition pages:
N.B I'm going to look at the alignment of the download icon in another PR as it's an existing problem that happens elsewhere too.
=> Transform exhibition

prismic-model/.gitignore, prismic-model/README.md, prismic-model/contentAnalysis.ts, prismic-model/sliceAnalysis.ts, prismic-model/src/articles.ts, prismic-model/src/books.ts, prismic-model/src/event-series.ts, prismic-model/src/events.ts, prismic-model/src/exhibitions.ts, prismic-model/src/guides.ts, prismic-model/src/pages.ts, prismic-model/src/parts/bodies/article-body.ts, prismic-model/src/parts/bodies/body.ts, prismic-model/src/parts/bodies/index.ts, prismic-model/src/parts/bodies/visual-story-body.ts, prismic-model/src/parts/textAndIcons.ts, prismic-model/src/places.ts, prismic-model/src/projects.ts, prismic-model/src/seasons.ts, prismic-model/src/series.ts, prismic-model/src/visual-stories.ts, prismic-model/src/webcomics.ts
Relates to #10122
- Gets content types straight from Prismic instead of using the snapshots one - this way it lists them even if there is 0 instances.
- Gets visual stories body slices too. I moved all the "body" files to one folder and added a comment requesting to add it to the analysis script if ever there was a new one. I couldn't find how to get them from Prismic as they are custom, if anyone has a better idea, do let me know as I know this is a bit of a plaster!
I also decided to align `sliceAnalysis` with `contentAnalysis` and add the capacity for a URL being added to the output + a report. I find this really useful when doing audits and thought others might too.
=> Fix analysis scripts (prismic-model)

content/webapp/components/VisuallySimilarImagesFromApi/VisuallySimilarImagesFromApi.tsx, content/webapp/services/wellcome/catalogue/images.ts, content/webapp/services/wellcome/catalogue/types/index.ts, content/webapp/services/wellcome/content/types/index.ts
Fixing failing e2e tests because of a change in catalogue API
The catalogue API returns `withSimilarFeatures` images. `visuallySimilar` query params is not supported anymore
=> replaces visuallySimilar with withSimilarFeatures to match API

common/model/opening-hours.ts, common/services/prismic/opening-times.ts, common/test/services/prismic/opening-times.test.ts
This is a straight-up readability improvement: we have a bunch of values in these tests which feature a lot of repetition and boilerplate.
This patch tries to make the tests more readable in two ways:
*   Ditch some of the boilerplate, so there's less repetition. There are lots of places where the boilerplate isn't interesting to what we're testing, so we can remove it.
*   Using named variables to make it more obvious when the same value appears in multiple places.  This should make it easier to see what the test is doing also -- you can read a list of variable names rather than JavaScript objects.
I've been staring at these tests as part of https://github.com/wellcomecollection/wellcomecollection.org/issues/9874, and got confused in several places – these readability improvements should …
=> Improve the readability of the opening-times tests

prismic-model/src/parts/gif-video-slice.ts
This is a comment I wrote when I was partway through writing the helper functions for the Prismic model definitions, reminding me to create a helper for `mediaLink()`.  I did that, so this comment can be removed.
=> Remove a dead TODO comment in the Prismic model code

cardigan/stories/content.ts
Maintenance
There were a few type/linting errors in our example content used in cardigan, I decided to go in and fix them.
It fixes BannerCard (which had missing content) and adds location information to Event Cards.
=> Fix content examples in cardigan

content/webapp/services/prismic/transformers/events.ts
This loop runs to produce the event times which are shown on event cards (in particular those associated with an EventBasic).  It only kicks in for events that have a `schedule`, which means multi-part events.
There are two cases we see here:
1.  An event running over one or more days that has multiple scheduled items, e.g. a weekend festival with talks at Sat 2pm, Sat 4pm and Sun 2pm.  In this case we'd show something like 'Sat–Sun' on the event card.
2.  An event which repeats on multiple, distinct dates, e.g. the relaxed openings for an exhibition that occur on 1 Jan, 2 Feb, 3 Mar. In this case we'd show something like '1 Jan … see 2 more dates' on the event card.
This line is checking whether we're in case 1 or 2 -- that is, whether the schedule for this event covers sub-events …
=> We can use a London comparison here, not UTC

common/services/prismic/opening-times.ts
In this function, we're building up a list of all the dates when we have exceptional opening hours, e.g. if we had two venues
library.exceptionalOpeningHours = [3 Jan, 2 Jan, 1 Jan]
gallery.exceptionalOpeningHours = [3 Jan, 4 Jan, 5 Feb]
then this would return
[1 Jan, 2 Jan, 3 Jan, 4 Jan, 5 Feb]
I expect these dates to be consistent for each batch that's entered (e.g. if somebody enters five dates, they'll have the same UTC offset), so we're comparing like-for-like in this function.
This means that if somebody enters the same override date in library and gallery, I expect it would be an _identical_ date, not merely a different time on the same day.
In practice this means we could actually replace this with the even stronger check (ignoring any weirdness around comparing dates in JS): …
=> Convert another use of isSameDay to use London comparisons, not UTC

content/webapp/components/VenueClosedPeriods/VenueClosedPeriods.tsx
The `firstDate` value is always defined, so this condition will always be true -- we can skip conditioning and just render the `HTMLDayDate` immediately.
This is a tiny thing I spotted while looking at https://github.com/wellcomecollection/wellcomecollection.org/issues/9874 – I'm not changing the VenueClosedPeriods component directly, but it calls a bunch of opening-times functions that I'm looking at, and I spotted this.
=> Remove an unnecessary conditional in VenueClosedPeriods

common/services/prismic/opening-times.ts
Penultimate change for https://github.com/wellcomecollection/wellcomecollection.org/issues/9874
As in https://github.com/wellcomecollection/wellcomecollection.org/commit/a5eac3dc6a6c55acbc6f8980beaff32a190ad88c, I think we could actually replace this with the stronger assertion:
```javascript
addDays(date.overrideDate, -1) === lastDayOfGroup
```
because any time these days are consecutive, they'll have been entered as part of the same batch and I'd expect them to have the same time of day.  As such, within this function I'm pretty sure UTC and London will always behave in the same way.
(And all the tests pass unmodified.)
=> Use London comparisons in groupConsecutiveExceptionalDays, not UTC

common/services/prismic/opening-times.ts, common/test/services/prismic/opening-times.test.ts, content/webapp/components/VenueHours/VenueHours.tsx
In this part of the code, we've got a complete list of all the days in the exceptional opening period, and we're trying to work out which opening hours to use in that time.
e.g. if we have exceptional hours on Mon/Weds/Fri, then this function is looking at Mon/Tues/Wed/Thurs/Fri:
* Mon = use the exceptional hours
* Tues = use the normal hours
* Wed = use the exceptional hours
* Thurs = use the normal hours
* Fri = use the exceptional hours
What's happening in this code is we're going through the days in this period one-by-one, and looking to find if there are exceptional hours for this day.  As with previous PRs, it should be sufficient to do
```javascript
day.overrideDate === date
```
here because all the dates come from Prismic in the same format.
Using `isSameDay` is a bit safer, but …
=> Get rid of the last use of a UTC comparison in isSameDay

common/services/prismic/opening-times.ts, common/utils/dates.test.ts, common/utils/dates.ts, common/views/components/DateRange/DateRange.tsx, content/webapp/components/StatusIndicator/StatusIndicator.tsx, content/webapp/services/prismic/transformers/events.ts, content/webapp/utils/dates.ts
Now that the codebase is exclusively using London-based date comparisons for `isSameDay`, we can remove the UTC implementation of `isSameDay`. This also allows us to remove `isSameMonth`, which was only used in that function.
Closes #9874 (finally!)
=> Remove the UTC implementation from isSameDay

common/views/components/Footer/index.tsx
For #8327 
Users encountering a status page
Cleans the footer to only show the opening times link when user visits an error page - was agreed it was not the best solution to render serverData on error pages to show venue opening times in full.
Currently shows:
Proposed:
=> Error page footer opening times adjustment

content/webapp/components/WorkDetails/WorkDetails.tsx
Credits/Licence work
Relates to #10220 and #10223 
- Removes "double" Licence section under image
- Hardcodes "Source: Wellcome Collection"
- Adds Provider section which repeats information from "Where to find this"
=> Changes to the new credit section

cache/send_slack_alert_for_5xx_errors.js
=> Don't send Slack alerts for 502/503 errors from our staging site

common/utils/string.ts, content/webapp/components/IIIFSearchWithin/IIIFSearchWithin.tsx, content/webapp/components/IIIFViewer/ViewerSidebar.tsx, content/webapp/components/ItemViewerContext/ItemViewerContext.tsx, content/webapp/components/WorkDetails/WorkDetails.tsx, content/webapp/pages/works/[workId]/download.tsx, content/webapp/pages/works/[workId]/items.tsx, content/webapp/services/wellcome/catalogue/types/index.ts, content/webapp/services/wellcome/catalogue/types/work.ts, playwright/test/view-items.test.ts
Credit/licence work
Relates to #10226 
- Adds provider
- Changes format of "Credit" to align with Work page's
- Tweaks test (test-id wasn't used anymore but was still declared)
- Changes label to "Licence and re-use" to align with Work page
- Also to Alex's suggestion in another PR, I've made a `removeTrailingFullStop` util as the same regex was used four times.
A few examples:
=> Change Item viewer licence/credit section

content/webapp/components/WorkDetails/WorkDetails.tsx
Maintenance
Relates to #10253 
Allows the information to display again after we've worked on making it more relevant.
=> Remove condition that hid Licence and reuse from certain works

playwright/test/view-items.test.ts
E2es
Hopefully allowing the tests in the file to run in parallel, with multiple workers, (default is to run in order _within a file_, with 1 worker) and allowing one retry, we should stop having flaky results. [See Slack conversation](https://wellcome.slack.com/archives/CQ720BG02/p1695980030258699).
I've started to try with splitting it into 4 files but (1) I don't like to looks of it 😄 and (2) they were still being considered slow when trialling it locally.
=> Configure test file differently to help with timeouts

content/webapp/components/TextAndImageOrIcons/TextAndImageOrIcons.tsx
Editorial/VS
Filters out null icons, as they can be added indefinitely without having an image attached to them. [This caused a 500 error](https://wellcome.slack.com/archives/C054304EVL5/p1696329024771009). If this would be better done differently/somewhere else, please do suggest!
I've also removed a Fragment I didn't think was useful which makes the changes look more than they are.
=> Filter out null icons in TextAndImageOrIcons

common/server-data/Context.tsx, common/server-data/index.ts, common/server-data/toggles.ts, common/services/app/google-analytics.tsx, common/views/themes/default.ts, content/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx, content/webapp/components/VisuallySimilarImagesFromApi/VisuallySimilarImagesFromApi.tsx, content/webapp/pages/search/works.tsx, content/webapp/pages/visual-stories/[visualStoryId].tsx, content/webapp/pages/visual-stories/index.tsx, content/webapp/pages/visual-stories/v1.tsx, content/webapp/pages/visual-stories/v2.tsx, content/webapp/services/wellcome/catalogue/images.ts, content/webapp/services/wellcome/index.ts, toggles/webapp/deploy.ts, toggles/webapp/index.ts, toggles/webapp/toggles.ts
Fixes #10188
This changes the toggle data we have on the ServerDataContext to include a type as well as a value (type already existed as part of the toggle.json, but they weren't included in the ServerDataContext before as we had no need of it).
We now use the type to ensure we only send toggles of type 'test' to GA.
The useToggles hook has been updated so it continues to return the value of the toggle. If using toggles server side though, we now need to use the .value property of the toggle.
NB. I think this change will also help with this ticket #10204
=> Toggles for GA

common/views/components/ButtonSolid/ButtonSolid.tsx, common/views/components/CheckboxRadio/CheckboxRadio.tsx, common/views/components/PopupDialog/PopupDialog.tsx, common/views/components/TextInput/TextInput.tsx, common/views/themes/config.ts, common/views/themes/typography.ts, content/webapp/components/IIIFViewer/ViewerSidebar.tsx, content/webapp/components/SearchTabs/SearchTabs.BaseTabs.tsx, content/webapp/components/SelectContainer/SelectContainer.tsx
For #10237 
Windows high-contrast users
Ensuring that keyboard focus remains visible when high-contrast mode is turned on
Screen recording of keyboard focus in high-contrast mode:
https://github.com/wellcomecollection/wellcomecollection.org/assets/1394592/7de3bb50-2f9c-4bda-bd90-31e3457f16a8
There are some inconsistencies in how we're handling keyboard focus at present, and some redundancy in the code as a result, but @j-jaworski has been looking at updating/rationalising keyboard focus states across everything and I think we should tidy everything up when we do that piece of work.
=> High contrast focus

common/views/components/ApiToolbar/index.tsx, playwright/test/api-toolbar.test.ts
Maintenance
Removes TODO; [I've checked with Editorial ](https://wellcome.slack.com/archives/C3N7J05TK/p1696934242259069)and Alice has confirmed they do use In Copyright images sometimes, but it's something to do carefully. Updating comment and label to reflect this.
=> Tzitzit; Remove todo and update comment

content/webapp/components/Body/Body.tsx, content/webapp/components/FeaturedCard/FeaturedCard.tsx
For #10228 
Making sure FeaturedCards have the correct heading level (h2/h3) depending on context.
=> Fix FeaturedCard heading levels

content/webapp/services/prismic/fetch/exhibitions.ts
Users? 🤷‍♀️ 
I mean this was a typo for 2 years and there were no complains, so I hesitated in just removing it. We don't have a lot of permanent exhibitions(?), I think it's just Being Human (current) and Medicine Man (past), so hard to test, but this code should ensure that they are always displayed. 
If the order wasn't specified, considering that we have 63 exhibitions, it might mean it doesn't make it in the first 20 pages and therefore isn't shown in `/exhibitions`. So we put it to the top to start with. 
It's then placed after temporary exhibitions [with this function](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/content/webapp/services/prismic/transformers/exhibitions.ts#L200) so the order makes more sense to the user.
=> Fix typo to ensure permanent exhibitions are always shown

content/webapp/components/FacilityPromo/FacilityPromo.tsx, content/webapp/components/WorksSearchResult/WorksSearchResult.tsx
For #10268
Screenreader users
Removing alt text from search result and facility promo images which should be considered decorative
=> Listing image alt

cache/send_slack_alert_for_5xx_errors.js
Already applied
Prevents 502/503 errors in staging from being send to the alert channel
=> changes the alert suppression check to host includes www-stage

content/webapp/components/TextAndImageOrIcons/TextAndImageOrIcons.tsx
People looking at Visual Stories
Spacing text using the same system we use elsewhere, which prevents excess space appearing at the bottom of the component
__before__
__after__
=> Space ps in TextAndImageOrIcons with margin-top

content/webapp/components/AudioPlayer/AudioPlayer.Volume.tsx, content/webapp/components/AudioPlayer/AudioPlayer.tsx
part of #10231
Adds the title of the track to the audio play pause buttons.
Some screen reader users may list the buttons on the page as a means of navigation and this makes them distinguishable from each other.
Voiceover before:
Voiceover after:
=> Add title to play and mute buttons

common/utils/get-focusable-elements.ts, common/views/components/DropdownButton/DropdownButton.tsx
Relates to #10235 and #10236
This fixes the issue where keyboard users couldn't tab into the links inside a dropdown menu, e.g. login, downloads
Only changing the tabIndex of focusable elements when the 'isActive' state changes fixed the inconsistent behaviour we were seeing.
However, this uncovered an issue for Download links in the viewer, whereby the whole item link could not be reached by keyboard, while the others could.
This is because when the viewed canvas changes the first 2 links are updated, while the 'whole item' link isn't. When the getFocusableElements function runs after this has happened it misses out the 'whole item' link because it has a tabIndex=-1.
I think generally the getFocusableElements should behave that way, just not in this case, so I updated the function to …
=> Accessibility tabbing

cardigan/stories/components/Buttons/Buttons.stories.mdx, cardigan/stories/components/Buttons/Buttons.stories.tsx
Design and devs
The dropdown button example was "Filters" which led to confusion as that's not what our filters look like. They _use_ DropdownFilter under the hood, but with the added `isPill` property and a different colour scheme. We are looking to change these styles in the future, but in the meantime I wanted to update our storybook documentation.
I've added all types of filters under a new story as well.
=> Change Dropdown button example to Download and add Filter dropdowns

content/webapp/pages/search/stories.tsx
Fixes #10286 
Returns the correct message when filters are selected in stories, but the search returns no results. 
Correct messaging - proposed
Current messaging - as is now
=> Corrected message for no results filtered stories search

playwright/test/contexts.ts, playwright/test/visual-stories.test.ts
Devs
Ensures the redirects work fine. We don't have much to go on at this point, it's using test Prismic documents, so would be nice to change eventually but reckon we want this tested as we're building.
=> Add test for visual story redirects

content/webapp/pages/index.tsx
Relates to https://wellcome.slack.com/archives/C8X9YKM5X/p1697534223218419
For some reason we were checking that there were more than 2 events and exhibitions before displaying them, we now show any number.
=> Show any exhibitions and events for the current week on the homepage

common/views/components/DropdownButton/DropdownButton.tsx
For #10269
Implements the suggestion of having the keyboard focus trapped inside a dropdown menu when it is open
This will be wherever we use the DropdownButton, e.g. Downloads, and not just on the search filters where the issue was identified
=> Focus trap dropdown

prismic-model/src/visual-stories.ts
Maintenance/changes
Related to #10308 
Now we've [added the new field and changed the references to it](https://github.com/wellcomecollection/wellcomecollection.org/pull/10319/files), we can remove the old one from the prismic model.
=> Remove related exhibition field in visual stories prismic model

cardigan/stories/components/TextInput/TextInput.stories.tsx, common/views/components/NewsletterPromo/NewsletterPromo.tsx, content/webapp/components/NewsletterSignup/NewsletterSignup.tsx, identity/webapp/src/frontend/MyAccount/ChangeEmail.test.tsx, identity/webapp/src/frontend/MyAccount/ChangeEmail.tsx
Users
Giving an example email address format if the address entered isn't valid
Wording taken direct from [gov.uk design system guidelines](https://design-system.service.gov.uk/patterns/email-addresses/#error-messages) as that was a source referenced with regards to this by the accessibility consultant
=> Include email address format example in error message

updown/expected-checks.ts
Fixes updown check fail when requesting deleted work 
This work was deleted today as part of the Brought to Life images take-down
=> replaces deleted work id with existing one

common/services/prismic/link-resolver.ts, content/webapp/pages/visual-stories/[visualStoryId].tsx, content/webapp/services/prismic/transformers/json-ld.ts, playwright/test/visual-stories.test.ts
Users/Visual stories
Relates to #10323 
We decided to remove the redirects and just use a canonical link instead. See the ticket for more information about how it should work moving forward and I've committed them separately with (hopefully) useful commit names.
Typescript kind of got me in `common/services/prismic/link-resolver.ts` and if anyone has a cleverer way about it please let me know, I kind of got stuck.
The ticket mentioned changing the test but after [commenting it out here](https://github.com/wellcomecollection/wellcomecollection.org/pull/10331) as we started having [issues](https://wellcome.slack.com/archives/CQ720BG02/p1697624078434609), I'm thinking it's better to wait until we have real content as using test content is a dangerous idea, they change all the time.
I'm …
=> Remove visual stories redirections and use canonical link instead

common/services/prismic/link-resolver.ts, content/webapp/pages/events/[eventId]/visual-stories.tsx, content/webapp/pages/exhibitions/[exhibitionId]/visual-stories.tsx, content/webapp/services/prismic/fetch/exhibitions.ts, content/webapp/services/prismic/transformers/visual-stories.ts, content/webapp/services/prismic/types/visual-stories.ts, prismic-model/src/visual-stories.ts
Devs and naming conventions
Relates to #10335 
Follows our naming convention and nicer to use in the codebase!
Again I have both fields coexisting, I'll remove the older one after this is in prod.
=> Rename relatedDocument again

content/webapp/pages/events/[eventId]/visual-stories.tsx, content/webapp/pages/exhibitions/[exhibitionId]/visual-stories.tsx, content/webapp/pages/search/works.tsx, content/webapp/pages/visual-stories/[visualStoryId].tsx, toggles/webapp/toggles.ts
Maintenance, visual stories
Relates to both #10316 and #10320
- Cleans up aggregation specific toggles as all seems well now. Filters can still be turned off with the permanent aggregation toggle, just not to an individual level.
- Removes visual story toggle, we're happy enough with it.
- Remove references to those toggles.
=> Remove aggregations and visual stories toggle and references to

content/webapp/components/WorkDetails/WorkDetails.Text.tsx
Everyone
#9643 included [a line](https://github.com/wellcomecollection/wellcomecollection.org/blob/8e0782cb62fae98923e3b51c3e4af8b0b49204ed/catalogue/webapp/components/WorkDetailsText/WorkDetailsText.tsx#L22) to make any newlines from the API be honoured on the front end, but when there are also e.g. `<p>` tags in the API response, this introduces extra space as well. After discussion we agreed that we're better off going back and introducing html (e.g. `<p>`s) in the data in places where we expect there to be spaces on the front end, rather than trying to solve it with css.
__before__
__after__
=> Revert space hack in #9643

.editorconfig, .vscode/settings.json
Devs
Only having one place to manage editor configuration settings
=> Move .editorconfig settings into .vscode dir

playwright/test/contexts.ts
Maintenance
Forgot to do it as part of #10320. The toggle has been removed. This is unused at the moment but will be useful for #10338
=> Remove VS cookie in test as toggle was removed.

content/webapp/pages/events/[eventId]/visual-stories.tsx, content/webapp/pages/exhibitions/[exhibitionId]/visual-stories.tsx, content/webapp/services/prismic/fetch/index.ts, content/webapp/services/prismic/fetch/visual-stories.ts
Visual stories
Relates to #10344
Visual stories on `/exhibitions/[exhibitionId]/visual-stories` and their event equivalent would display a 404 if they were delisted. The same issue would happen with Prismic previews. We needed to allow the serverSide query for this to fetch delisted VS as well so they display.
This does affect the generic `getByType` (from `content/webapp/services/prismic/fetch/index.ts`), but as it's defaulted to `true`, it shouldn't bother anything unless we strongly dislike having specific code on what is meant to be generic.
=> Allow queries to fetch delisted visual stories

prismic-model/src/visual-stories.ts
Maintenance
Relates to #10335
Cleans it up. Will deploy and merge once the PR changing the references to this field has made its way to prod.
=> Remove deprecated related-document

content/webapp/components/IIIFViewer/ZoomedImage.tsx
For #10299 
NVDA screen-reader users
Allowing them to pan the image using arrow keys as is possible for other keyboard users
I don't know if the `aria-description` is either
1. overkill (sighted users don't get this information)
2. not enough (we should _also_ give sighted users this information)
=> Allow nvda users to pan image with keyboard

updown/checks.ts, updown/expected-checks.ts
Updown
A non-existent url was added to the updown checks, triggering alerts when it 404'd 
This is removing it
Already applied to updown through `yarn checks`
=> removes a broken url from checks + sets credentials in script

content/webapp/services/prismic/transformers/exhibitions.ts, content/webapp/types/exhibitions.ts
Access documents
- Empty document blocks would display an empty PDF block. This will filter them out.
=> Filter out empty access document blocks

content/webapp/components/Pagination/Pagination.test.tsx, content/webapp/components/Pagination/Pagination.tsx, content/webapp/pages/search/images.tsx, content/webapp/pages/search/stories.tsx, content/webapp/pages/search/works.tsx, content/webapp/pages/series/[seriesId].tsx, playwright/test/search-works.test.ts
Relates to:
#10209: I've changed the previous next links from buttons to links, as that's what they are and it means that they work without javascript. Also, removed the disabled prop, as it's no longer applicable, and the isLoading prop as it wasn't being passed in anywhere and is no longer required.
#10307: I've added an optional formId prop to the Paginator. If supplied the page input will work as it did before, to submit the relevant form. If not supplied then the input gets wrapped in it's own form tag, so it will submit to the current url.
=> Paginator fixes

.github/.dependabot
Devs and maintenance
- Sets Dependabot to run monthly (instead of the weekly we had earlier this year) 
- If I got it right, this should also ignore patch versions as to not overwhelm us with PRs - if you'd rather we also get them feel free to shout!
=> Suggested Dependabot config

common/utils/search.ts, content/webapp/components/SearchPageLayout/SearchNavigation.tsx, content/webapp/pages/search/images.tsx, content/webapp/pages/search/index.tsx, content/webapp/pages/search/stories.tsx, content/webapp/pages/search/works.tsx, content/webapp/pages/series/[seriesId].tsx
Maintenance
I just noticed repetition in the form ID in search while I had to fix merge conflicts, turns out we declare it a few times in the same file, and it's the same ID in about 5 files, so I thought we could declare it only once and safeguard against future typos in tests etc.? 
And `[series]` doesn't need a search id so I removed it from there and it works really well with the new fix 🙌
=> Search form ID; one source of truth

common/data/errors.tsx, common/views/components/ErrorPage/ErrorPage.tsx
Users
Relates to #10385 
Displays a custom message if the error is 410 Gone to avoid confusion.
Example URL: https://wellcomecollection.org/works/vxx96d62
=> Add a custom message for 410 Gone

content/webapp/components/IIIFViewer/GridViewer.tsx, content/webapp/components/IIIFViewer/IIIFViewer.tsx
Maintenance
Relates to #10381 
Props were expected but never used in GridViewer, so removing references to them everywhere.
=> Tidy up GridViewer

content/webapp/services/wellcome/catalogue/filters.test.ts, content/webapp/services/wellcome/catalogue/filters.ts
Me
https://github.com/wellcomecollection/wellcomecollection.org/issues/10350
This fixes one of the problems caused by the fact that Aggregations use unique ids, but filters use labels, exemplified here: https://wellcomecollection.org/search/works?query=glasgow&contributors.agent.label=%22University+of+Glasgow.+Library%22
Because multiple entries with the same label exist in the dropdown, it gets selected twice.  It might also fix other problems mentioned [here](https://wellcome.slack.com/archives/C3TQSF63C/p1698424449041649)
Until now, the ordering of filter options has come directly from the API, this is no longer sufficient, given the merging of counts that happens here.  It also led to [a slightly odd sorting behaviour WRT absent selected …
=> Ensure filters are unique by label

cache/send_slack_alert_for_5xx_errors.js
Naughty bots
Not alerting on Slack when they hit urls such as this: 
https://www-e2e.wellcomecollection.org/uapjs/jsinvoke/?action=invoke
=> no slack alert for e2e tests endpoint

common/views/components/TextInput/TextInput.tsx
Users
Removing the red 'error' border around an e.g. email input once the text in the field is valid
To see the current problem, go to the homepage, type e.g. 'a' in the newsletter promo at the bottom of the page. Tab/click away from the field and see an error message about address format. Click back into the field and make it e.g. 'a@b' – the error message correctly disappears, but the red error border remains.
(spotted when working on #10234)
=> Hide error border when input becomes valid

common/views/components/CookieNotice/CookieNotice.tsx, common/views/components/StackingTable/StackingTable.tsx, content/webapp/components/FeaturedCard/FeaturedCard.tsx, content/webapp/components/LibraryMembersBar/LibraryMembersBar.tsx, content/webapp/components/Map/Map.tsx, content/webapp/components/WorksSearchResults/WorksSearchResults.tsx, content/webapp/pages/whats-on/index.tsx, identity/webapp/copy.tsx, identity/webapp/src/frontend/jest-setup.ts, playwright/test/actions/search.ts, playwright/test/helpers/search.ts, playwright/test/search-form.test.ts, playwright/test/search-works.test.ts, playwright/test/selectors/search.ts, playwright/test/work.test.ts
Devs & e2es
Relates to #10409 
After having had a lot of issues with the e2es being flaky or outright not passing because of race conditions, we've decided to go over them and rewrite them.
The goal of this PR will focus on `search-works` test. So far, the tests in it are taking 3-7 seconds less to run(!).
- [Playwright's auto-retrying assertions](https://playwright.dev/docs/test-assertions#auto-retrying-assertions) should be used as much as possible instead of `waitForTimeout`, `waitForSelector` or `waitForNavigation`, which we currently use a lot but are [deprecated or discouraged](https://playwright.dev/docs/api/class-frame#frame-wait-for-timeout). They would be the key to fix race condition issues.
- When testing sorting, filtering or pagination, we can't depend on the URL change nor …
=> Refactor `search-works` test file

prismic-model/lintPrismicData.ts
Devs
Relates to #10304 
As it's not our responsibility to fix prismic linting, it shouldn't show as failed - it makes our PRs look like they're not passing.
[See Slack Convo](https://wellcome.slack.com/archives/C3N7J05TK/p1699979055854609?thread_ts=1699978697.464199&cid=C3N7J05TK)
I think that's what was needed?
=> Stop lint task failing when error found

common/utils/backgrounds.ts, common/views/components/PrismicImage/PrismicImage.tsx
Users/images/transparent pngs
We currently had a grey background on all `PrismicImage`s, I believe this acts as a placeholder while the image loads. This means that transparent images have a background, but I guess we didn't really use them at the time so didn't notice. We now do in the `TextAndIcons` components.
I've replaced it with `placeholder="blur"` and a base64 image that is just white with 50% opacity. We can revisit this ( @j-jaworski, we can have a call and decide on something together if this is a bit meh), but in the meantime it allows for transparency as the placeholder is only while the image loads.
Before
https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/99c012cd-668b-42da-896b-94f65fbb29a3
After …
=> Prismic images: Remove grey background

content/webapp/services/prismic/transformers/card.ts
Users
Relates to #10416 
A few weeks back, [Ben raised](https://wellcome.slack.com/archives/C8X9YKM5X/p1699027709068399) that, on the homepage, exhibitions that were featured were listed again in the content list underneath. As [the comment in code](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/content/webapp/pages/index.tsx#L141) still says this shouldn't be the case, we knew this was not on purpose.
I believe it was introduced in [a higher level PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/10125/files?diff=split&w=1#r1293369060), so I reverted that line back to what it used to be. It was changed because: 
> I can't be sure why this was as it was – I think it was probably a mistake. And it was the reason why id would be undefined here and …
=> Revert a change to stop featured exhibition displaying twice

content/webapp/pages/articles/[articleId].tsx, content/webapp/pages/books/[bookId].tsx, content/webapp/pages/concepts/[conceptId].tsx, content/webapp/pages/event-series/[eventSeriesId].tsx, content/webapp/pages/events/[eventId]/index.tsx, content/webapp/pages/exhibitions/[exhibitionId]/index.tsx, content/webapp/pages/exhibitions/index.tsx, content/webapp/pages/guides/exhibitions/[id]/[type].tsx, content/webapp/pages/guides/exhibitions/[id]/index.tsx, content/webapp/pages/pages/[pageId].tsx, content/webapp/pages/seasons/[seasonId].tsx, content/webapp/pages/series/[seriesId].tsx, content/webapp/pages/stories/[contentType].tsx, content/webapp/pages/visual-stories/[visualStoryId].tsx
Users/Maintenance
We got a lot of [errors in the alerts channel](https://wellcome.slack.com/archives/CQ720BG02/p1700412843533299) regarding an non-existing event that also had characters in its URL that broke a query. I realised that our `[eventId]` page was lacking the `looksLikePrismicId` check that other pages had that would fail the page before it tried to do things with the Id. 
Then I decided to check our other pages and tried to structure `getServerSideProps` the same so we're a bit more aligned and we had less chances of forgetting some checks in the future.
Basically the changes are;
- Moving some steps to  _after_ we've checked the `id` was valid (instead of automatically doing them every time)
- Using `isNotUndefined` to make sure the document exists
- Returning 404 at the end …
=> Ensure all dynamic pages have same error handling

common/services/prismic/link-resolver.ts, content/webapp/pages/events/[eventId]/visual-stories.tsx, content/webapp/pages/exhibitions/[exhibitionId]/visual-stories.tsx, content/webapp/pages/visual-stories/[visualStoryId].tsx
Editorial/Maintenance
Relates to #10408
The check for link-resolver wasn't good enough. There is always a relatedDocument (` { link_type: 'Document' }`) so the check needs to look at if it has an ID, like we do elsewhere in the codebase.
Also because of the work I did earlier to [align all error handling server side](https://github.com/wellcomecollection/wellcomecollection.org/pull/10444), I noticed I'd missed it there so did that too.
=> Align VS serverside checks and fix preview URLs

common/data/README.md
Developers
Taking them to the right file, rather than a 404 page.
=> Update link to microcopy file

common/services/prismic/transformers/images.ts, common/services/prismic/types/index.ts, content/webapp/services/prismic/types/index.ts, content/webapp/services/wellcome/content/types/api.ts
Devs, TS
From `7.3.0`, Prismic's type for FilledImage has two new keys that aren't documented for at all yet.
This breaks our tests and anything using mock data, and we don't want to add random data in those fields as it's unclear what they are for. So we chose to Omit them. I thought about Picking instead but I think for now it's quite readable... Opinions welcomed.
See https://github.com/prismicio/prismic-client/pull/326
[See Slack convo](https://wellcome.slack.com/archives/C02ANCYL90E/p1701096253351109)
=> Account for new fields in Prismic filled image type

common/views/components/StackingTable/StackingTable.tsx
Design/styling
Relates to #10460 
Re-styles the StackingTable in the request item section to how it used to be. I removed a prop I shouldn't have when [migrating to styled components 6](https://github.com/wellcomecollection/wellcomecollection.org/pull/10352/files#), so it just needed to be passed in again. `width` was also removed but re-added. 
Current bug
Old version and back to
=> Readd missing prop from Th in stacking table

common/data/microcopy.tsx, content/webapp/components/WorkDetails/WorkDetails.AvailableOnline.tsx, content/webapp/pages/works/[workId]/images.tsx, content/webapp/pages/works/[workId]/items.tsx, content/webapp/utils/iiif/v3/index.ts
Relates to #10467
It appears that iiif-manifests for born digital items can exist without the items property, e.g. https://iiif.wellcomecollection.org/presentation/collections/archives/SA/SRH/B/41/2
I'm not sure this should be the case, but for now i've made it optional so that works/items pages won't error/break, if we fetch these manifests
=> Born digital iiif-manifest

playwright/test/api-toolbar.test.ts
e2e maintenance
Relates to #10409 
I know we're having chats about what we actually want to test next week but these tests still seemed sensible.
- Flattens tests
- use `getByText` and `getByRole` selectors which matches our goals
- TIL: Using `expect([locator]).toBeVisible()` as it fails way faster than just waiting for the selector ("By default, the timeout for assertions is set to 5 seconds"). Locally it fails in 7 seconds if the locator is wrong, if we skip this step it still fails as the locator can't be found, but that takes 30 seconds.
=> Refactor api-toolbar tests

pa11y/Dockerfile, pa11y/webapp/package.json, pa11y/webapp/yarn.lock
Devs
[I'd moved to the latest version of pa11y ](https://github.com/wellcomecollection/wellcomecollection.org/commit/dcc545437fe0600cfba33fa1ffc8bc6b73a0ab25)(`6.2.3`) as it tested against WCAG 2.1, but it caused issues in Docker with the dependencies. [I tried a fix](https://github.com/wellcomecollection/wellcomecollection.org/pull/10483/files); updating the packages was a good thing, but there was still an issue with Puppeteer and installing Chromium. 
[It looks like they'll be updating their dependencies](https://github.com/pa11y/pa11y/issues/677#issuecomment-1752037654) (crucially, puppeteer, which currently runs on v9 but exists up to v21). I've subscribed to that ticket and their [`7.0.0` ticket](https://github.com/pa11y/pa11y/pull/681) as well and we can see when it gets released …
=> Revert to pa11y 5.1.0 as there's flaky dependencies issue with 6

common/services/prismic/transformers/images.ts, common/services/prismic/types/index.ts, content/webapp/services/prismic/types/index.ts, content/webapp/services/wellcome/content/events.ts, content/webapp/services/wellcome/content/types/api.ts
After working on https://github.com/wellcomecollection/content-api/pull/79, we've decided to keep the new fields that Prismic recently added (`edit: object` and `id: string`) and just pass everything in to keep it to the default state instead of picking what we wanted. These fields return data now (were just null a few weeks back, guess they were working on it?), and we're going to have conversations down the line as to what the Content Api should return. In the meantime, I'm making sure our mock data matches what it will return and limiting our manipulation of the data.
=> Revert to default Prismic FilledImage type

playwright/test/search-images.test.ts
This makes the e2e test decoupled from the query, as the search will only ever return one thing (rather than all the images belonging to the work)
=> Fix e2e: use image ID for search

cache/modules/wc_org_cloudfront/waf.tf
This change is intended to block a wider array of malicious requests to wellcomecollection.org in order to reduce unnecessary alarms and increase protection to the underlaying services.
We add `AWSManagedRulesSQLiRuleSet`, `AWSManagedRulesCommonRuleSet` and `AWSManagedRulesKnownBadInputsRuleSet`, to block requests that match recognised OWASP vulnerabilities and include potential (useless) SQL injection attacks that we've seen in alerts.
Targeting the prod stack:
`terraform plan -target module.prod_wc_org_cloudfront_distribution`
Output:
```
~ resource "aws_wafv2_web_acl" "wc_org" {
id          = "316ddf50-ea9e-4555-826d-e0a4d1380ead"
name        = "weco-cloudfront-acl-prod"
tags        = {}
- rule {
- name     = "managed-ip-blocking" -> null
- priority = 1 -> null
- override_action {
- …
```
=> Add core & sql managed rules to WAF

playwright/get_playwright_image.sh
Deployment pipeline
Switching the deprecated `ecr get-login` for `ecr get-login-password`
=> use get-login-password to log into ecr

README.md, infrastructure/experience/.terraform.lock.hcl, infrastructure/experience/ecr.tf, infrastructure/experience/outputs.tf
Follows https://github.com/wellcomecollection/wellcomecollection.org/pull/10518, we don't need the ECR repository any more.
This infrastructure has been deleted via `terraform apply`.
This removes redundant infrastructure and reduces cost.
=> Remove ECR repository for catalogue app, small docs tweak

identity/webapp/package.json, playwright/README.md
This change is for new people working on this app who might need to run the `playwright` tests.
We make the AWS profile used in dev mode `identity-developer` rather than `identity-dev` to match the name in the profile [provided in the documentation](https://github.com/wellcomecollection/aws-account-infrastructure/blob/main/accounts/credentials.ini), and update the `README.md` to make it clear you may want to start both apps.
This change contains some commits from https://github.com/wellcomecollection/wellcomecollection.org/pull/10520 as this was discovered in the process of writing that PR, either change can be merged first.
> [!NOTE] 
> The `run-concurrently.sh` script requires you to log into aws every time, without checking if you've already got a valid profile. A further extension may …
=> Tweak how identity starts, update playwright docs 

playwright/Dockerfile, playwright/package.json, playwright/yarn.lock
People working on the playwright tests.
This change upgrade playwright from `1.30.0` to `1.40.1` in order to [get `or` on locators](https://playwright.dev/docs/api/class-locator#locator-or) to help in [another PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/10520), but also to keep us up to date in this small part.
=> Upgrade playwright to get or on locator

playwright/Dockerfile
This change updates the base os for the playwright image to use whatever is the default base rather than focal. The Buildkite stack has been updated, so hopefully now this will run without error.
At time of writing the base image is jammy:
```console
root@1b3df8063781:/# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
There is an added benefit of moving away from focal which has reached [end of long term support (LTS) for security …
=> Switch focal for jammy in playwright test image

playwright/test/helpers/search.ts
e2es
[See Slack conversation](https://wellcome.slack.com/archives/C3TQSF63C/p1704204194038399) where we discuss how search pages could benefit from more leeway on load times.
=> Use a slowExpect on search helpers

common/utils/convert-image-uri.ts, content/webapp/components/IIIFViewer/IIIFViewerImage.tsx, content/webapp/components/IIIFViewer/MainViewer.tsx, content/webapp/components/IIIFViewer/ZoomedImage.tsx, content/webapp/test/utils/convert-iiif-uri.test.ts, content/webapp/utils/convert-iiif-uri.ts
This may be a silly idea, hence the draft PR, but I'd be interested in people's thoughts
We had an inquiry over the weekend (16th - 17th Dec, 2023) about [a work which is not displaying it's images](https://wellcomecollection.org/works/qvnz25jg/items). The [image url](https://iiif.wellcomecollection.org/image/b18023010_0001.JP2/full/1338%2C/0/default.jpg)s are returning '401 Unauthorized'.
[A slack discussion about this issue](https://wellcome.slack.com/archives/CBT40CMKQ/p1702897123155509) explains that this is because "a bunch of Genetics Books" have some restrictions in place which ultimately means their images have a maxUnauthorised value set to 1000. Because we try and request images that are larger than this, those requests fail as unauthorised.
This is a policy rather than a …
=> Unauthorised images in viewer

common/views/components/ErrorPage/ErrorPage.tsx
Editors and the people they share these links with
See related tickets #7761 and #10481
The ErrorPage component looks if the host contains `preview.` and the navigator userAgent includes `Safari` (and not `Chrome`, since [Chrome's userAgent can very well contain "Safari"](https://github.com/tamimibrahim17/List-of-user-agents/blob/master/Chrome.txt). If both conditions are met, an error message displays at the top of the Error Message (which is a 404, which I didn't think needed to be hidden).
I can't really test it locally as it depends on the host name, but I believe it'll work nicely + code review to double check my thinking!
=> Display message for previews on Safari

cache/modules/wc_org_cloudfront/waf.tf
People who like the website to keep working without using a huge number of tasks
Hopefully blocking bot requests, which make up the vast majority of the recent increase in traffic
See https://docs.aws.amazon.com/waf/latest/developerguide/waf-bot-control.html
=> Add Bot Control to WAF rules

content/webapp/components/PaletteColorPicker/PaletteColorPicker.tsx, playwright/test/helpers/search.ts, playwright/test/search-images.test.ts
People who like non flaky tests
- Use `selectAndWaitForColourFilter` because it does what all those lines were doing. Added a step in this function to close the colour filter dropdown on desktop as it was getting in the way of selecting the 1st search result. 
- removed `data-test-id` on the `PaletteColorPicker`, now unused
- not checking that the 1st result item is visible: we click on it later on so it'll fail there if the item is not visible
=> Refactor search images e2e test first block

content/webapp/components/Tabs/Tabs.Switch.tsx
Maintenance
Researched it a bit further and I think I had it wrong. I think [this is long term tracking](https://github.com/wellcomecollection/wellcomecollection.org/issues/9665) and was meant to be there.
=> Remove unnecessary TODO

common/views/components/PageHeader/PageHeader.tsx, content/webapp/pages/articles/[articleId].tsx
Maintenance
Relates to #10288 
See ticket for more info but tl;dr the TODO is 5 years old and that prop is only used once for a specific purpose so we opted to make that clear.
=> Clarify usage of TitleTopper by renaming it and removing TODO

content/webapp/__mocks__/iiif-manifest-v3.ts, content/webapp/components/Work/Work.tsx, content/webapp/services/iiif/transformers/manifest.ts, content/webapp/test/utils/iiif.test.ts, content/webapp/types/manifest.ts, content/webapp/utils/iiif/v3/index.ts, toggles/webapp/toggles.ts
Relates to [#10493](https://github.com/wellcomecollection/wellcomecollection.org/issues/10493)
This adds a property of bornDigitalStatus to a transformedManifest, which we can use to make decisions about the UI.
For now, I'm just displaying the status at the top of the work page (behind a toggle).
=> determine if a manifest contains born digital

content/webapp/components/ExpandedImage/ExpandedImage.tsx, content/webapp/components/IIIFSearchWithin/IIIFSearchWithin.tsx, content/webapp/text/aria-labels.ts, playwright/test/view-items.test.ts
Maintenance
Half of this was an opinion, so open to reverting some changes.
If I understood/remember correctly, `aria-labels` files are used to make it easier for anyone to edit copy on the website, but a lot of it isn't used anymore. I just wonder if anyone but devs actually update that copy and if there is still value in having it in a separate file?
- Remove the copy that wasn't used anywhere
- Kept the ones that are used more than once across the site.
- If they were only used once I moved it directly in the component but as that goes against the original goal I'd be up for putting them back. Maybe we move it all to `microcopy`?
=> Remove doubled up microcopy

common/views/components/Modal/Modal.tsx, content/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx, playwright/test/search-images.test.ts
Those of us working on e2es.
Refactors Tests 2 and 3 - looking specifically at how the Image Modal renders image data. 
- uses the new `clickImageSearchResultItem` function
- hones directly into the `Modal` to test displaying of contributor and title info
- instructs the `search-images` tests to run in parallel to speed up testing
=> Refactor of Test(2) and Test(3)

toggles/README.md
Folk trying to understand toggles.
Tweak some of the toggle documentation to fix broken links, remove some unnecessary detail.
=> Toggle documentation tweaks

content/webapp/components/Work/Work.tsx
Follows on from #10549
Some works don't have digital locations and so won't have a born digital status. in which case we don't want to show the message.
E.g.
=> only show born digital message if appropriate

content/webapp/components/IIIFViewer/ViewerStructures.tsx, content/webapp/test/utils/iiif.test.ts, content/webapp/utils/iiif/v3/index.ts
Relates to #10494
Specifically addressing: "for a Manifest that represents an object comprising multiple files, arranged in a directory structure, a navigable representation of that structure will be displayed."
While playing with some of the iiif-manifests with born digital material I noticed that we only present this structure one level deep. I don't _think_ it's been an issue with the current content on the site (a book index tends to only be one level deep). But it may have been.
Example from a manifest with born digital items:
Before:
After:
=> Viewer structures

content/webapp/components/IIIFViewer/ViewerStructures.tsx, content/webapp/services/iiif/transformers/manifest.ts
I noticed while working on #10553, that some of the links in the viewer contents panel were being rendered twice. This fixes that.
Before:
After:
We now group the ranges when transforming the manifest, rather than in the component.
=> group ranges when transforming the manifest rather than in the component

content/webapp/services/prismic/fetch/exhibitions.test.ts
The test was failing because a new exhibition has been published.
It should be in the results but the test wasn't expecting it. I've added it as a quick fix, but this will happen the next time a new Exhibition is published so we may want to think about improving the test somehow.
=> Fix test: adds another exhibition to the expected result

dash/webapp/pages/index.tsx
Maintenance, we went for removing all of them and finding alternatives only if someone raises it, but they've been dead a while.
Makes it less frustrating than being offered links that go nowhere.
=> Remove dead dashboard links

content/webapp/components/Exhibition/Exhibition.tsx, content/webapp/services/prismic/transformers/exhibitions.test.ts, content/webapp/services/prismic/transformers/exhibitions.ts, content/webapp/services/prismic/types/exhibitions.ts, content/webapp/types/exhibitions.ts, prismic-model/src/exhibitions.ts
Editorial and maintenance
- Short title is only used for breadcrumbs, taking precedence over the title if its filled. This was [for longer named exhibitions](https://github.com/wellcomecollection/wellcomecollection.org/issues/1716). I believe it's a bit unclear to Editorial and they tend to fill it in with just the same name. I wanted to make that clearer so they'd know in the future. I also changed it to a paragraph because I had to put the helper text in the placeholder sadly, and as an h1 it was way too big. I don't think it needed to be an h1 anyway as it's just used in breadcrumbs. I think it's from when [an A/B test was done to use the shortTitle on cards](https://github.com/wellcomecollection/wellcomecollection.org/issues/4418), which was then rolled back.
Current usage:
Future …
=> Exhibition model; Add information for shortTitle and remove bsl/audio desc

prismic-model/src/exhibitions.ts
Prismic maintenance
- Will remove those unused fields from the model.
I'll run the changes once its parent PR is in prod and this one gets merged in `main`.
=> Remove unused fields from model

cardigan/stories/components/EventSchedule/EventSchedule.stories.tsx, cardigan/stories/content.ts, content/webapp/__mocks__/events.ts, content/webapp/pages/events/[eventId]/index.tsx, content/webapp/services/prismic/fetch/events.ts, content/webapp/services/prismic/transformers/events.ts, content/webapp/services/prismic/types/events.ts, content/webapp/types/events.ts
Maintenance, Editorial
Relates to #10592 
- Removes fetching of field in graphQuery as well as where it's transformed and used.
- Does NOT remove it from the Prismic model, this will happen once this is in production, to avoid erroring on live.
=> Remove fetching and transforming of isRelaxedPerformance

content/webapp/__mocks__/events.ts, content/webapp/components/EventPromo/EventPromo.test.tsx, content/webapp/services/prismic/fetch/events.ts
Good functioning of FE!
Relates to #10596 
Adds missing fields from graphquery, this is stopping "Fully booked" from displaying on the cards when relevant. Probably due to the graphquery cleanup I did months ago, so thanks to @agnesgaroux for finding that bug!
=> Add missing fully booked fields in event graphquery

CODEOWNERS
Maintenance
`buildkite-admins` is not a team anymore, so I removed the lines that did nothing. If we want it back, we can re-add it once we've recreated the team if it feels useful.
=> Remove old code owner rules

common/data/errors.tsx
This change is for users who see errors during a prolonged period where we may want to provide more context.
The added link is to [our status page](https://status.wellcomecollection.org/).
This change adds an item to the checklist of things a user can do if they are getting a 5xx error, in order to provide more information about when a problem may be resolved to users.
=> Add a link to our status page from the 5xx error

content/webapp/app.ts
This change is part of https://github.com/wellcomecollection/wellcomecollection.org/issues/10545 and adds a healthcheck endpoint to the content app so we can really check the health of the app before it is deployed. At present the healthcheck terminates at the nginx container so during deployment (and normal running) we don't check if the app has properly started.
See https://github.com/wellcomecollection/platform-infrastructure/blob/main/images/dockerfiles/nginx/frontend.nginx.conf#L24
> [!NOTE]
> This will require a further change to remove the nginx config that fields the healthcheck request there.  
No downtime during deployments resulting in a better experience for visitors to the site, and fewer errors that we cannot effectively respond to in the alerts channel. Deployments that …
=> Adds a simple healthcheck endpoint to the content app

content/webapp/components/EventsSearchResults/index.tsx
Nice looking-ness
Related to #10611 
Biggest change you'll see today. Just ensures that if there is only 1-2 events in the results they don't take up 100% of the space when available ([learning about `auto-fill` vs `auto-fit`](https://css-tricks.com/auto-sizing-columns-css-grid-auto-fill-vs-auto-fit/#aa-fill-or-fit-whats-the-difference)).
before
after
=> Events results; Change grid fill property

identity/webapp/src/app.ts
This change is part of https://github.com/wellcomecollection/wellcomecollection.org/issues/10545 and adds a healthcheck endpoint to the content app so we can really check the health of the app before it is deployed. At present the healthcheck terminates at the nginx container so during deployment (and normal running) we don't check if the app has properly started.
Same change for the content app: https://github.com/wellcomecollection/wellcomecollection.org/pull/10612
See https://github.com/wellcomecollection/platform-infrastructure/blob/main/images/dockerfiles/nginx/frontend.nginx.conf#L24
> [!NOTE]
> This will require a further change to remove the nginx config that fields the healthcheck request there.  
No downtime during deployments resulting in a better experience for visitors to the …
=> Adds a simple healthcheck endpoint to the identity app

content/webapp/components/WorkDetails/WorkDetails.AvailableOnline.tsx
For #10584
Stops audio players, video players or view item links appearing on the work page when we are showing the DownloadList.
=> Don’t show audio/video player or item link when showing the DownloadList

cache/modules/wc_org_cloudfront/waf.tf
Users of our site who want to be able to visit it without issue, and developers who don't want to be alerted about bad behaving bots.
https://wellcome.slack.com/archives/CQ720BG02/p1706520543358799
Logs of recent issue: https://logging.wellcomecollection.org/app/r/s/rTkEb
See Sunday 28th of Jan deluge of requests:
We've been seeing problematic traffic from ByteSpider for a while, causing an outage at the start of 2024, and now getting round our WAF rules to cause smaller problems.
This change blocks this bot specifically by matching on user-agent rather than relying on the other WAF rules.
https://github.com/wellcomecollection/wellcomecollection.org/assets/953792/ddec4ea6-6da3-4b5c-b0b5-c130635022da
=> Block bytespider bot by user-agent header

content/webapp/components/EventPromo/EventPromo.tsx, content/webapp/components/EventsSearchResults/index.tsx, content/webapp/pages/events/[eventId]/index.tsx, content/webapp/services/prismic/events.test.ts, content/webapp/services/prismic/events.ts, content/webapp/services/prismic/transformers/events.ts, content/webapp/services/wellcome/content/types/api.ts
Relates to #10587 
- `upcomingDatesFullyBooked` only needs the event times really, so simplified that
- Made it so an event would be marked as fully booked if necessary on the events search cards
- Modified `transformEventTimes` to allow for the different `isFullyBooked` format from Content API and Prismic API
Worth noting for testing purposes that as Content reindexes happen every 15minutes, it may take 15 minutes for content changes to display on the UI. It's always been the case (incl with articles), but I hadn't really needed a quick refresh as when testing with Fully Booked status, so FYI! 
[If needed, a Test event can be found here in Prismic](https://wellcomecollection.prismic.io/documents~b=working&c=published&l=en-gb/ZbKOnBIAACQAlnWs/?section=Event), or search for "Hybrid event" …
=> Display "fully booked" when relevant on events search cards

content/terraform/.terraform.lock.hcl, content/terraform/stack/main.tf, identity/terraform/.terraform.lock.hcl, identity/terraform/stack/main.tf, infrastructure/modules/service/main.tf, infrastructure/modules/service/variables.tf
This change uses the updated nginx container images from https://github.com/wellcomecollection/platform-infrastructure/pull/413, in order to allow the healthcheck endpoints added in:
- https://github.com/wellcomecollection/wellcomecollection.org/pull/10617
- https://github.com/wellcomecollection/wellcomecollection.org/pull/10612
To serve traffic and really confirm if the application container has started.
Tested in stage: https://wellcome.slack.com/archives/C3TQSF63C/p1706545489494719
See https://github.com/wellcomecollection/wellcomecollection.org/issues/10545 for the motivation for this change.
=> Use updated container image for nginx in content & identity

.vscode/settings.json
Maintenance/devs
[The default value for this config](https://code.visualstudio.com/Docs/languages/javascript) has changed. `"explicit"` is the same as `true` , and it updates automatically every time I update the software, so might as well change it for real in the repo. I know it happens to Agnès too, do flag if this goes against what you've got but it should be this moving forward.
From the docs:
> As of today, the following enums are supported:
explicit (default): Triggers Code Actions when explicitly saved. **Same as true.**
[...]
=> Change default value for shared VSCode config

cache/cloudfront_e2e.tf, cache/cloudfront_prod.tf, cache/cloudfront_stage.tf, cache/modules/wc_org_cloudfront/distribution.tf, cache/modules/wc_org_cloudfront/variables.tf, cache/secrets.tf, content/terraform/data.tf, content/terraform/locals.tf, content/terraform/main.tf, content/terraform/stack/main.tf, content/terraform/stack/variables.tf, identity/terraform/data.tf, identity/terraform/locals.tf, identity/terraform/main.tf, identity/terraform/stack/main.tf, identity/terraform/stack/variables.tf, infrastructure/modules/alb_listener_rule/main.tf, infrastructure/modules/alb_listener_rule/variables.tf
We've recently had issues with requests which appear to come from a client with the "bytespider" user-agent causing load issues and outages for the site. 
Following https://github.com/wellcomecollection/wellcomecollection.org/pull/10619, we discovered that requests from this user-agent seem to be circumventing the CDN and being made at the load-balancer directly. This change protects the load-balancer from requests that do not come through the CDN by following [this AWS recommendation](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/restrict-access-to-load-balancer.html) to have a shared secret between CloudFormation & the ALB that is required to be set in a particular header for requests to succeed.
This change implements the AWS recommendation in terraform.
The …
=> Protect the load-balancer from bots

content/webapp/__mocks__/whats-on.ts, content/webapp/components/InfoBox/InfoBox.tsx, content/webapp/pages/whats-on/index.tsx, content/webapp/test/pages/whats-on.test.tsx
Users who are interested in What's on today... on Mondays.
Relates to #10629 
- Makes it more obvious when the galleries are closed. We used to have a message there that was commented out during the covid closures, so we modernised it a little.
- Also removes exhibitions from being listed out (only in the Today tab and only when the galleries are closed) as that could cause further confusion.
- I also fixed the types in the test that were flagged as incorrect and tweaked the test a bit to be a bit clearer. I wanted to add a test either here or on the e2e about hiding the Events/Exhibitions on Monday, but the Jest ones don't get the Prismic data (which we need for opening hours) and the e2es ones can't mock the date yet ([It's been …
=> Clarify closures on Today in What's on

cache/secrets.tf, preview/terraform/.terraform.lock.hcl, preview/terraform/cloudfront.tf, preview/terraform/locals.tf
Follows https://github.com/wellcomecollection/wellcomecollection.org/pull/10626 and adds the shared secret to the preview cloudfront distro. 
Missing this caused https://preview.wellcomecollection.org/ to stop working. The secret header was added manually in the console in the preview cloudfront distribution for expediency. This change brings that manual change into terraform state.
As such the terraform plan is a no-op:
This change extends the instructions for rotating the secret by adding an extra step to pay attention to the cache stack state update and start sending the new secret.
=> Adds the shared header to the preview cloudfront distro

toggles/webapp/toggles.ts
Devs and Cookies epic
It would be good to do this work under a toggle; it'll allow us to actually test in prod that our removal of tracking really work, for example.
I added it as part of another PR (#10639) which adds a button in the footer which toggles consent for analytics.
=> Add new toggle for consent work

cache/modules/wc_org_cloudfront/waf.tf
Folk who want simpler configuration.
This change removes the bytespider specific rule, as this traffic has been mitigated by https://github.com/wellcomecollection/wellcomecollection.org/pull/10631. This rule does not appear to be matching any traffic (it's probably covered by other rules).
TLDR: This check was not impactful, this bot traffic was skipping the CDN and going straight to the ALB.
=> Remove bytespider WAF rule

common/package.json, common/utils/cookie-consent.ts, common/views/pages/_document.tsx, yarn.lock
Allow `getCookies()` server side.
Fix `getCookies()` returning `undefined` server-side. No idea why it works locally but breaks in staging but this issue does seem to explain the issue we've been having: https://github.com/andreizanik/cookies-next/issues/57
=> Upgrade cookies-next

common/services/conversion/track.ts, content/webapp/components/ConceptLink/index.tsx, content/webapp/components/ExpandedImage/ExpandedImage.tsx, content/webapp/components/ImageLink/index.tsx, content/webapp/components/ItemLink/index.tsx, content/webapp/components/SearchPagesLink/Works.tsx, content/webapp/components/WorkDetails/index.tsx, content/webapp/components/WorkLink/index.tsx
For #10642 
Adds a sourcePath property to page view events so it is possible to see where the user came from, e.g.
@taceybadgerbrook I know you suggested appending the path to the current source, but this felt cleaner and I think gives you what you need.
=> Tracking page path

common/server-data/index.ts, common/server-data/types.ts, common/views/pages/_document.tsx
Server side cookie fetching
Since `_document` has access to toggles through `pageProps` (as each page sends it through `serverData`), and `toggles` are cookies, I thought I'd do the same for our _consent_ cookies.
To be honest I'm not super sure why the current method doesn't work as, again, it works locally and it's once in staging that it fails, so we'll have to test it there. Because toggles work fine in staging, I'm hoping this works there too.  Maybe it's because it prefers `getServerData` as a server action to `getInitialProps` which also runs client side (although `_document` only runs server side)? 
I'm leaving a `console.log` in; if it doesn't work at least I can see if it's at the `getCookies` stage and if it might just be the library having issues...
=> Send consent through serverData

common/utils/cookie-consent.ts
Cookie work
We think the cookie might need a `WC_` prefix to be recognised in staging due to [our cloudfront policy](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/cache/modules/cloudfront_policies/locals.tf#L1)
=> Change cookie consent to add WC_ prefix

common/views/pages/_app.tsx
People wanting to play behind the cookie work toggle
The reload causes an infinite loop in staging, and as it's not something we really want to happen and it still needs discussing, am removing it.
=> Remove reload on consent change and leave a TODO for the future

cache/modules/cloudfront_policies/locals.tf
Cookie work, this is Civic UK's consent cookie
That list is the cookies we allow through in our cache policy and we needed his one for good functioning of cookie consent.
Already applied
=> Add CookieControl to list of allowed cookies

common/services/app/google-analytics.tsx, common/views/pages/_document.tsx
Cookie work and consent-non-given users
As discussed in standup, I'm removing this as without JS we can't know if we have consent or not from our users and therefore shouldn't be adding this script in?
After reading [this article](https://www.analyticsmania.com/post/google-tag-manager-noscript/), it also seems it's a pretty limited version of the regular script. They recommend using it if
> - You plan to track visitors who have disabled JavaScript on their browsers.
> - Or you wish to [verify the ownership of the website in the Google Search Console](https://support.google.com/webmasters/answer/35179?hl=en) by choosing the “Verify with Google Tag Manager” option.
> - Or you don’t plan to do the aforementioned activities right now, but maybe it will become a priority in the future.
I don't …
=> Remove noscript GTM script

cache/modules/wc_org_cloudfront/outputs.tf, cache/outputs.tf, preview/terraform/cloudfront.tf, preview/terraform/locals.tf
This change is for people who want less bot traffic.
See: https://github.com/wellcomecollection/platform-infrastructure/issues/423
We can see the "bytespider" traffic drop off as we apply this change.
Here we extend the prod WAF for wellcomecollection.org to cover preview.wellcomecollection.org that is fronting the same ECS service.
> [!NOTE]
> This change is applied.
=> Associate prod WAF with preview Cloudfront distro

content/webapp/utils/iiif/v3/index.ts
As [reported in Slack](https://wellcome.slack.com/archives/C8X9YKM5X/p1709720458072779) 
"In some cases, we have items that are both copies and volumes" and these were displaying a blank screen on the items page.
[We ran into this before](https://github.com/wellcomecollection/wellcomecollection.org/issues/9901) and [fixed it](https://github.com/wellcomecollection/wellcomecollection.org/pull/9934), but looks like I broke it again with the recent refactoring.
This fixes it again
=> Show volumes of nested collections

common/views/components/PageLayout/PageLayout.tsx
polyfill.io has recently changed ownership. [Fastly have a branch for trustworthy and reliable access](https://community.fastly.com/t/new-options-for-polyfill-io-users/2540) so we can use that.
We should also work out which, if any, of the things we're currently polyfilling we still require based on our current browser support list (opened #10697).
=> Use safer polyfill

cardigan/stories/components/Cards/Cards.stories.tsx, cardigan/stories/components/PageHeader/PageHeader.stories.tsx
Our UI tests that keep failing (see #10690)
This PR is mergeable if we'd like to test it out, but mostly serves as a starting point for yet another Chromatic config chat.
This is not the best fix, it's defo a plaster, but I identified the main failing stories and added `diffThreshold` ([docs](https://www.chromatic.com/docs/threshold/)) which we've done in the past to the main offenders. I've added a [delay](https://www.chromatic.com/docs/delay) to Cards because I wonder if the image needs time to load and has a slight difference because of it? So that one is more of a test and if it works maybe we want it on everything that has an image?
[This tool](https://6262c53f521620003ac2ff49-ukmsdlppcb.chromatic.com/?path=/story/stories-diff-threshold-check--test-yours-out) helps finding what …
=> Chromatic plaster; Add more diffThresholds and delays

dash/Dockerfile, dash/README.md, dash/webapp/components/Header.tsx, dash/webapp/next.config.js, dash/webapp/package.json, dash/webapp/pages/index.tsx, dash/webapp/pages/pa11y.tsx, dash/webapp/pages/prismic-linting.tsx, dash/webapp/pages/toggles.tsx, dash/webapp/yarn.lock
Maintenance
- Move to use `node:18-bookworm-slim` as per https://github.com/wellcomecollection/wellcomecollection.org/pull/10526#issue-2049077105
- Upgrades to a few minor version packages 
- Upgraded to next 14;
- Removed `export` task as `build` now creates the output folder (bc I added it to the config as per [migration docs](https://nextjs.org/docs/app/building-your-application/upgrading/version-14#v14-summary))
- Set [trailingSlash](https://nextjs.org/docs/pages/api-reference/next-config-js/trailingSlash) to match the existing output structure as `exportPathMap` is deprecated.
- Updated README
- Some changes in the components and pages that were mostly to test our linting and make it a bit more readable (Header). We don't ever really touch these so it doesn't really matter, but might …
=> Upgrade dash to node 18

common/views/pages/_document.tsx
Fixes an issue with people not being able to see their holds.
Why this worked up until now is a bit of a mystery, but the [Next docs indicate](https://github.com/vercel/next.js/pull/20869/files) that the `process.env` isn't a regular JS object and, as such, can't be destructured.
=> Don't destructure the process object

common/views/components/CivicUK/index.tsx
People who want more cookies, part of #10717
Allows all the cookies we have in https://github.com/wellcomecollection/wellcomecollection.org/blob/main/common/data/cookies.ts, we need them allowed in general and I need `WC_analyticsDebug` to test Segment sends everything well/doesn't in live environments.
Adding `isPreview` for us and Editorial, although I don't think it's the full answer to the current preview issues as cookie toggle would need to be on for those affected and it wouldn't be the external stakeholders' case.
=> Add more necessary cookies

common/koa-middleware/withCachedValues.ts, common/koa-middleware/withPrismicPreviewStatus.ts, common/package.json, common/views/components/CivicUK/index.tsx, common/views/pages/_app.tsx, content/webapp/app.ts, yarn.lock
Reverts wellcomecollection/wellcomecollection.org#10721
Doesn't seem to be working in staging; I think we need to keep allowing `isPreview`? More testing required.
=> Revert "Trial Prismic's next preview tool"

content/webapp/services/wellcome/common/filters.ts, content/webapp/services/wellcome/content/types/api.ts, content/webapp/services/wellcome/index.ts
Good functioning of is available online filter, #10668  (follows #10704)
We were wrongly assuming which bucket would have the `true` value, which would've never worked unless there were always more `false` than `true` results! So went back to the drawing board with @agnesgaroux to structure the boolean buckets further in the API content, which can be seen in the added `type` here. This way we can find the desired one first and use it for the `count`.
Twinned with https://github.com/wellcomecollection/content-api/pull/117
=> `IsAvailableOnline` event filter; Find true bucket to get count

.github/dependabot.yml
This change is for developers who want to keep their application up to date and pay attention to necessary security updates.
This change re-adds Dependabot configuration, but introduces [grouping](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) so that like updates are grouped together in single PR to make them easier to deal with.
=> Re-add dependabot configuration

prismic-model/src/parts/bodies/visual-story-body.ts, prismic-model/src/parts/text-and-icons.ts
Relates to #10750, see [Slack convo ](https://wellcome.slack.com/archives/CUA669WHH/p1710853645244199)
Adds list-items to the WYSIWYG in Text and Icons and Text and Image
=> Add list-item as an option for TextAnd slices

content/webapp/components/EventPromo/EventPromo.test.tsx, content/webapp/components/EventPromo/EventPromo.tsx
General tidy
I was rereading [the rules for location](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/content/webapp/components/EventPromo/EventPromo.tsx#L35) because of https://github.com/wellcomecollection/content-api/issues/103 and noticed that actually, "Throughout our building" would still show up even though the last rule says:
> If an event has a single Prismic location, 'Throughout the building', we display 'In our building'
I went into Prismic and actually that `Place` ([those places](https://wellcomecollection.prismic.io/documents/working?k=places&s=throughout&l=en-gb)) is now called "Throughout **our** building" and has been for at least two years. It _used to be_ "Throughout **the** building" but we can see in Prismic history that was changed. As the …
=> Change condition for "throughout our building"

common/data/microcopy.tsx, common/views/components/Header/Header.tsx, common/views/components/SearchForm/SearchForm.tsx, content/webapp/components/SearchPageLayout/SearchNavigation.tsx
Events in search work #10779 
Changes the copy if toggle is ON to indicate events are now searchable.
We need to amend the copy when we can though, [I've created a ticket here](https://github.com/wellcomecollection/wellcomecollection.org/pull/10771) to do that, when Lauren is back we can do that change quickly.
=> Change searchbar label based on toggle

common/services/conversion/track.ts, common/views/pages/_app.tsx
Data analysts
Adding custom dimension information into the dataLayer
This was information that we had access to before we moved to GA4. Seems like we no longer sent it anywhere after the switch over.
This was specifically for getting the `partOf` information (e.g. when an article is part of a series). The change also required a change in how we query that information in GTM.
@taceybadgerbrook when this goes in you should be able to see an array of ids indicating which (if any) series an article is part of
=> Make gaDimensions available in the dataLayer

common/data/microcopy.tsx, content/webapp/components/SearchPageLayout/SearchPageLayout.tsx
Good metadata and useful titles.
Just realised we skipped this part when adding this new page - Added a title and a [metadescription](https://wellcome.slack.com/archives/C3N7J05TK/p1712831942778189).
=> Events search metadata and title

.buildkite/pipeline.deployment.yml, .buildkite/pipeline.yml, pa11y/webapp/package.json, pa11y/webapp/yarn.lock
Pa11y to work again, relates to #10766 
Upgrades to [v8](https://github.com/pa11y/pa11y/releases/tag/8.0.0) and uncomment out its task.
I ran the task that used to fail in this PR [here](https://buildkite.com/wellcomecollection/wc-dot-org-build-plus-test/builds/13729#018ec862-29e1-4d0a-84e1-a8f26a1f27c0) and it worked well.
Not sure why single quotes got changed to double quotes, but all other buildkite yml files use double quote so works for me.
=> Upgrade to pa11y8 (+ upgrade puppeteer)

common/views/components/CivicUK/index.tsx, common/views/components/Footer/Footer.Nav.tsx, content/webapp/pages/guides/exhibitions/[id]/[type].tsx, content/webapp/pages/guides/exhibitions/[id]/index.tsx, content/webapp/pages/guides/exhibitions/index.tsx, identity/webapp/src/frontend/components/PageWrapper.tsx
Relates to #10597, #10707 and #10714
[Designs](https://www.figma.com/proto/5bZXZ08XyU8IOgyjd9ZsGe/Cookies-update?page-id=2%3A27&type=design&node-id=2312-2634&viewport=-9008%2C-1515%2C0.5&t=OF2Vu1merfAKJ8Hc-1&scaling=min-zoom&starting-point-node-id=2312%3A2634)
- Adds properties to Civic UK config to try and match our designs as much as possible
- Moves Manage Cookies button to its official place in the footer
- Adds footer to Exhibition Guide pages and Identity pages; this ensures the user can control their cookie preferences from a wider array of pages. We are leaving item viewer pages footerless, though.
All of it should still be behind the toggle (except the footer being re-added, that's done for everyone)
=> Style Civic UK banner and Manage Cookies button

cardigan/stories/components/Pagination/Pagination.stories.mdx, cardigan/stories/components/Pagination/Pagination.stories.tsx, content/webapp/components/Pagination/Pagination.tsx, content/webapp/pages/search/events.tsx, content/webapp/pages/search/images.tsx, content/webapp/pages/search/stories.tsx, content/webapp/pages/search/works.tsx, playwright/test/helpers/search.ts, playwright/test/search-works.test.ts
#10684 
https://github.com/wellcomecollection/wellcomecollection.org/issues/10575
https://github.com/wellcomecollection/wellcomecollection.org/issues/10355
https://github.com/wellcomecollection/wellcomecollection.org/issues/10470
The current component was not well implemented and has caused a lot of buggy behaviours. We decided to simplify it as per #10684  
- No longer has an input field to change the page (if our colleagues still want to do it they can still do it through query params)
- Tweaked Storybook to be more interactive/useful.
- Changed tests so they'd still work
=> Simplify pagination and tweak story

common/koa-middleware/withCachedValues.ts, common/koa-middleware/withPrismicPreviewStatus.ts, common/views/components/CivicUK/index.tsx, common/views/pages/_app.tsx, content/webapp/app.ts
Reverts wellcomecollection/wellcomecollection.org#10740 - apologies for the amount of reverts, but we've now tested Prismic's Next Preview toolbar in _production_, and it _does_ work, but... what also happens is that the script loads for _all users_ (in order to get the shareable link to work), which causes performance issues, loads jQuery for all and flags an a11y miss in pa11y (no title on the iframe element). [Having read through an issue that was raised 5 years ago,](https://github.com/prismicio/prismic-toolbar/issues/43) it's been a thing for a long time and it doesn't look like it'll be fixed any time soon, so we've decided to revert back to our previous solution.
[Slack chat here for decision making](https://wellcome.slack.com/archives/CUA669WHH/p1712828009443009) and [here for how …
=> Revert "Trial Prismic's next preview tool, part II"

content/webapp/components/Table/Tables.styles.tsx, content/webapp/components/styled/AccessResources.ts
#10770 and #10803
- Table arrows were misaligned because it was within `spaced-text` and a margin-top was applied to the second arrow.
- Felt like too small a change for a PR so worked on #10770 as well; changed the padding-right to match the size of the arrow icon so the copy would never go over/under. [Screen recording here](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/740ff062-fb9e-4f1b-a3ad-d5baf3310322).
=> Fix arrow in table and access resources spacing

common/views/components/Footer/Footer.Nav.tsx, content/webapp/components/Table/Tables.styles.tsx
#10803 and #10706 
- Fixes alignment of table arrows (when within `.spaced-text`, its styles need to be overwritten more specifically)
- Adds "Cookie policy" link in footer (behind toggle only). This meant I had to change the styles a little bit, which I just did by removing some margin between links. That style will apply immediately, toggle or not. It still looks a bit strange at a very small range of window size, but nothing too bad.
**Before**
**After**
**Still happens a little bit between 960px and 995px.**
=> Add cookies link behind toggle and fix table alignment

content/webapp/package.json, yarn.lock
Security
We got a warning about a [critical security issue](https://github.com/wellcomecollection/wellcomecollection.org/security/dependabot/177) to do with our version of `formidable`, which we have as a `types/supertest` dependency (for `supertest`). We were 4 versions behind on `types/supertest`, but I'm trialling just removing the whole thing as we don't seem to be using it. Testing beforehand.
=> Remove supertest to remove critical security issue

content/webapp/hooks/useTransformedManifest.ts
Fixes #10765
When we switch between works we go and fetch the iiif manifest it points to and replace the previous one held in state.
However, if we switch to a work that doesn't have a manifest then we don't do anything and the previous one persists, leading to this bug.
We now remove the manifest from the state if the work doesn't point to one.
=> Remove manifest when a work doesn't have one

toggles/webapp/toggles.ts
Devs working on using the items' availability slots from the itemsAPI instead of calculating them in the browser
Enabling dev work and testing while keeping the website working as usual 
NOT DEPLOYED 
Edit: deployed 2024-04-26
=> add toggle for availabilitySlots from itemsAPI

prismic-model/README.md, prismic-model/sliceAnalysis.ts
Devs who want to know more about our slice usage
- Modify the count to be X slices in X content types [list of content types it's used in]
- Adds a slice count in each object so we know how often the slice is used within the content type node
- Always print URL as it's super useful for seeing _how_ we use them
- Remove search by label as it's too generic (would return everything that uses "Standalone", regardless of slice type. Plus we're deleting labels soon.
- Edits README file to reflect those changes.
Specific slice search
`yarn sliceAnalysis --type=editorialImage`
Generic search
`yarn sliceAnalysis`
I've not touched this, but the overall count still precedes any listings;
=> Modify sliceAnalysis script to be more useful

common/data/microcopy.tsx, common/views/components/Header/Header.tsx, common/views/components/SearchForm/SearchForm.tsx, content/webapp/components/SearchPageLayout/SearchNavigation.tsx, content/webapp/pages/search/events.tsx, content/webapp/pages/search/index.tsx, playwright/test/helpers/contexts.ts, playwright/test/search.test.ts, toggles/webapp/toggles.ts
Maintenance and related to #10816 
- Removes toggle from toggles list (changes to be deployed to dash once it's merged to `main`)
- Removes references to the toggle from within the codebase
- Simplifies test as cookie doesn't need to be added to function.
=> Remove event toggles and related TODOs

content/webapp/pages/search/images.tsx
#10836 
It had been done [in the past](https://github.com/wellcomecollection/wellcomecollection.org/pull/9237), looked quickly to see where/why it got lost, seems to be when the new image search was created or possibly before (so at least two years back). Anyway, re-adding it so it's clearer for our users that get to page 334 :)
=> Image search: Display error description if provided

content/webapp/components/IIIFItem/IIIFItem.tsx, content/webapp/components/VideoPlayer/VideoPlayer.tsx, content/webapp/components/Work/Work.tsx, content/webapp/components/WorkDetails/index.tsx
We render the audio player on the works page if we have a ContentResource of type 'Sound' in the IIIF Manifest.
It turns out [some of our IIIF manifests have ContentResources with a type of 'Audio'](https://iiif.wellcomecollection.org/presentation/v3/b17276342) (although this isn't supposed to be a valid value)
I've amended the type to make 'Audio' a possible value and now look for this too, when determining if we should display the AudioPlayer
[See conversation on Slack](https://wellcome.slack.com/archives/C8X9YKM5X/p1714637016038419)
=> Audio player not rendering for certain works

common/views/components/ApiToolbar/index.tsx, common/views/components/CookieNotice/CookieNotice.tsx, common/views/components/InfoBanners/InfoBanner.tsx, common/views/components/InfoBanners/WebsiteIssuesBanner.tsx, common/views/components/PopupDialog/PopupDialog.tsx, content/webapp/components/ExhibitionGuideLinks/ExhibitionGuideLinks.tsx, dash/webapp/pages/toggles.tsx
Security [#9774](https://github.com/wellcomecollection/wellcomecollection.org/issues/9774)
Adds `Secure` attribute to our cookies (`WC_` and `toggles_`). [More about the Secure attribute](https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/06-Session_Management_Testing/02-Testing_for_Cookies_Attributes#secure-attribute).
=> Add secure attribute to our cookies

playwright/test/article.test.ts
e2es
Following the content migration, images seem to have lost their suffix in URL which indicate what crop, width and height to use. For now, we're manually recropping them, but it means the expected URL for this particular image has slightly changed. For the e2e to pass, this change was necessary.
=> change expected URL for meta image

.buildkite/pipeline.yml
This test is now out of date as it compares the Prismic types to our old model files
We no longer use these files since the move to slice machine
We will reinstate this test to compare the models to the new type files, see: #10860
=> temporarily remove prismic diff test

content/webapp/components/Work/Work.tsx, content/webapp/components/WorkDetails/index.tsx
@paul-butcher noticed that when the bornDigital toggle was set to false, works with bornDigital items were mistakenly display a link to the items page.
=> Born digital tweaks

content/webapp/components/WorkDetails/index.tsx
We were sometimes mistakenly showing the 'Available online section' when there  was nothing to display inside it.
See: https://wellcome.slack.com/archives/C3TQSF63C/p1715759922441179
This stops that
=> Only show available online section when there is something to display in it

common/views/slices/Text/index.tsx
Allowing text slices to show up in the real-time view
=> Use options instead of context so slice-simulator works

common/views/slices/EditorialImage/index.tsx
For #10865 
Everyone
Making images take varying amounts of horizontal space based on their aspect ratios
Landscape images can take up a maximum of 12 columns
Square images can take up a maximum of 10 columns
Portrait images can take up a maximum of 8 columns
Note: images will continue to be constrained by their height to ensure that they always fit within the viewport, so they may not get to their maximum possible width depending on the user's browser.
=> Automatically size images based on their aspect ratios

content/webapp/components/EventSchedule/EventScheduleItem.tsx
People coming to events
Making sure they have the right information about event availability.
=> Show early registration info inside event schedule

common/customtypes/stories-landing/index.json, common/prismicio-types.d.ts
Relates to #10867 
Allows the deprecated webcomics type to be added to the content list on the stories landing page.
It seems [Helen managed to do this somehow without this](https://wellcome.slack.com/archives/C8X9YKM5X/p1715676681291539). I've no idea how, but this seems like a sensible addition.
=> Allow webcomics type to be added to stories landing

content/webapp/services/prismic/fetch/stories-landing.ts, content/webapp/services/prismic/transformers/stories-landing.ts
Relates to #10867
- Makes sure we fetch the data for webcomics (and series) if they are added to the content list of the stories landing page
- Makes sure we render the card for a webcomic correctly
=> Webcomics on stories landing

common/data/cookies.ts, common/data/hardcoded-ids.ts, content/webapp/pages/cookie-policy.tsx
Ease of maintenance of the cookie policy page; taking it off dev hands.
#10891 
> [!NOTE] 
> A quick reminder, [we used to have a Table slice](https://github.com/wellcomecollection/wellcomecollection.org/pull/9943/files), but it was not intuitive at all to use (pipe delimited CSV style) and unused, so we removed it and I don't think this warrants bringing it back. Therefore, the Cookie Policy page had to be hard-coded as it had tables throughout the body. We'd like to not have to deploy for any copy change and this is a suggestion in how we could do that. If it does not fit our standards or we don't want to open the door to hacks, please flag so!
I created a Prismic page called Cookie Policy ([editable here](https://wellcomecollection.prismic.io/builder/pages/ZlCaVRAAACQAD2uX?s=published&f …
=> Make Cookie Policy a Prismic page with inserted content

cache/modules/wc_org_cloudfront/distribution.tf
Content-editors who want to preview content, @davidpmccormick who wants to be done with the prismic migration.
This change removes the security polify for this path to allow the slice machine preview to work.
The security policy adds an `x-frame-options: DENY` header which prevents browsers from rendering content in an iFrame. We add a special exception for /slice-machine paths so prismic can use this path however it likes.
=> Create a new CloudFront distro behaviour for /slice-machine*

common/server-data/index.ts, common/services/app/civic-uk.ts, common/services/conversion/track.ts, common/views/components/CivicUK/index.tsx, common/views/components/VideoEmbed/VideoEmbed.tsx, content/webapp/hooks/useHotjar.ts, content/webapp/pages/cookie-policy.tsx
Cookies work #10888 
- Makes `getConsent` function more generic
- Adds a `hasAnalyticsConsent` condition to loading the Youtube script needed for GA4
- `frameBorder` on iframe is deprecated, so replacing it with style as recommended.
- **Unrelated cheeky add**: Forgot TODOs in Cookie Policy page from #10890 so addressed them here. Mostly just made the metadata come from Prismic.
=> Cookies: `getConsentStatus` function more generic, add condition to YT script

common/server-data/prismic.ts
Someone who wants to add Prismic collection-venues that are not to be displayed on wc.org, eg. DeepStore 
Instead of fetching all Prismic documents of type `collection-venue` we specifically fetch only the ones that are for public consumption (library, café, shop and galleries)
This is necessary because DeepStore is about to be added as a `collection-venue` in Prismic as part of the offsite requesting work, but we do not want this venue to show up on the website.
=> explicitly fetch only collection-venues that appears on the website

common/data/cookies.ts, common/views/components/CivicUK/index.tsx, common/views/components/VideoEmbed/VideoEmbed.tsx, content/webapp/components/Table/Tables.styles.tsx, content/webapp/components/Table/index.tsx, content/webapp/pages/cookie-policy.tsx
Cookies work #10895 and #10717
- Simplify tables on Cookie Policy page. Headers moved to same place as content as they differ.
- Adds information to 3rd parties sections in CivicUK Config. Most opt-out links [still need to be verified](https://wellcome.slack.com/archives/CUA669WHH/p1716547320671559).
- Allows new prop on `Table` so text is smaller/kind of more readable.
- Add condition to Youtube script that ensures it only loads on Youtube videos. We do not use, but we do allow Vimeo, so have to consider them.
=> Cookie policy lists update, third-parties config tweaked

common/server-data/__mocks__/index.ts, common/server-data/index.ts, common/server-data/types.ts, common/services/app/google-analytics.tsx, common/views/pages/_document.tsx
Cookie work, missed bits for the marketing consent.
- Pass in marketing consent server-side as well as analytics
- Set up `gtag` to consider the marketing consent status.
=> Cookies: pass marketing consent value to `serverData` and `gtag`

playwright/test/homepage.test.ts
e2e  #10830 
- Checks homepage and visit-us have the CivicUK banner, but that Cookie Policy does not.
- Checks banner only displays when `CookieControl` has not been set or has expired.
- If anyone would like anything else checked, lmk! I was thinking maybe check how scripts behave based on consent, but was struggling a bit to find out _how_ to do it. Could take the time after release to dig though, and create a different PR for it if the appetite is there.
=> Add an e2e for the cookie banner

content/webapp/components/ItemRequestModal/RequestDialog.tsx
Users who click the "Request item" button super fast when the work page loads
It sometimes takes a little bit longer to fetch and set an item's availableDates than it takes to render the "Request item" button. In this case, the `RequestingDayPicker` dropdown would show the date but the form would have its value as undefined. This, in turn, would make the "Confirm request" button unresponsive, since you can't confirm a request without a date.
This PR adds a `UseEffect` to force a `setPickUpDate` state update when the item's availableDates actually become, well.. available :)
=> useEffect when item.availableDates becomes defined

cardigan/.storybook/preview.js, common/views/components/AppContext/AppContext.tsx, common/views/components/Modal/Modal.test.tsx, common/views/components/Modal/Modal.tsx
#10915 
This PR adds a value in the context that checks if the cookie banner has been acknowledged. I put it at that level as I thought it could be useful elsewhere, but if we think it's overkill I can move it.
In that regard, I've added the context to Storybook and to the concerned tests.
> When the cookie banner shows on a page with a `Modal` (such as [this work](https://wellcomecollection.org/works/nny5wq9u/items)), the latter is stopping the former from being interacted with as it is locked in with `FocusTrap` (for a11y reasons).
>
> We need to deactivate `FocusTrap` if the cookie banner has yet to be acknowledged and interacted with, then re-activate it to stick by good a11y practices.
The banner can be considered acknowledged in three different ways:
- The user clicks "Accept All": …
=> Add mutation observer to check if cookie banner has been acknowledged

common/views/components/Modal/Modal.tsx, playwright/test/events.test.ts
Follow-up for #10920 (ticket #10915)
I realised that some sort of race condition was causing the bug to still be there when there was a hard refresh/on first load. This wasn't happening in local which is why it wasn't caught there and why it's harder to test.
I put the `shouldLock` in the state instead, and made sure it got updated properly in all the different scenarios
I broke an e2e test on purpose so the environment would stay up longer (fixed now) and tested it there, and it seemed to work perfectly fine, so I'm hoping it's a good representation of other live environments.
=> Modal: Set `shouldLock` in state

common/views/components/AppContext/AppContext.tsx, common/views/components/Modal/Modal.tsx
Reverts wellcomecollection/wellcomecollection.org#10921
Might want to revert; the focus isn't put back on the Modal after the cookie banner is dismissed anymore, which is really bad for keyboard nav users and screen readers. The cookie banner is always available for interaction, though.
This was an attempted fix for a problem that only happened on first load and hard-refresh (#10920 fixed it for normal refresh), so I feel like it might be preferable to revert.
=> Revert "Modal: Set `shouldLock` in state"

content/webapp/components/EventsByMonth/EventsByMonth.tsx
for [#10855](https://github.com/wellcomecollection/wellcomecollection.org/issues/10855)
=> Only display the the next 4 months (inclusive) on the what's on page

common/prismicio-types.d.ts, common/views/slices/GuideTextItem/mocks.json, common/views/slices/GuideTextItem/model.json
Having discussed the new guides models with the content editors, it was decided an additional field is required on the Exhibition texts slice
=> add an additional field for exhibition-text slice

common/services/app/civic-uk.ts, common/views/components/AppContext/AppContext.tsx, common/views/components/CivicUK/index.tsx, common/views/components/Modal/Modal.tsx, playwright/test/work.test.ts
#10915 
On live environments it seems that the modal/cookie banner need more time to detect interactions with the other, and so we need to be able to control `hasAcknowledgedCookieBanner` from the Modal. The modal checks if the overlay is active (which means either the banner or the popup is there) and that turns off the focus lock.
I've aimed to test as much as possible on the e2e environment and it seems to work nicely, but as we had to revert the last "fix" (which was wonky I admit), if this can be tested locally as well I reckon all the better!
I'll squash and merge for this as I made a lot of noisy useless commits for the sake of debugging.
=> Acknowledge Cookie banner state from Modal to avoid locking issues

content/webapp/services/prismic/transformers/pages.ts
Missed the [comment on this PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/10930) about the type being removed. This puts in the correct one
=> add missing type

common/server-data/prismic.ts, common/services/prismic/transformers/collection-venues.ts
Relates to https://github.com/wellcomecollection/wellcomecollection.org/pull/10930
A part of that PR we prefaced Prismic types with 'Raw' to help distinguish them from transformed types.
This does the same to a similar type
=> rename type to bring it in line with others

cardigan/stories/components/VenueHours/VenueHours.stories.tsx, common/test/fixtures/components/galleries-venue.ts, common/views/slices/CollectionVenue/index.tsx, content/webapp/components/VenueHours/VenueHours.tsx, content/webapp/services/prismic/transformers/body.ts, content/webapp/types/body.ts
Following the slice machine/migration work we no longer have labels on slices. This removes the redundant code
=> Remove old label code

cardigan/stories/data/untransformed-body.ts
Body story has been flagging as changed in recent PRs, this is to make UI checks more relevant
Uses static assets as its a known fix for the "slight pixel changes" issue on images that come from Prismic.
Sorry, untransformedBody slightly transformed now! 😄 
Do have a look at the rendering in Chromatic: https://www.chromatic.com/build?appId=62f13cdbd0ff140768a8d87b&number=6007 not as pretty, but less likely to be flagged so worth it?
=> Use static asset for Body Story

.github/workflows/prismic-linting.yml
#10843 
- Have it run earlier in the morning so it's ready before we start our day (it's 8 UTC and so runs at 9, let's have it be early and ready to go in case it's the first thing we look at)
- Only run on week days
- Upgrade checkout to v4 as per Dependabot recommendation (so closes #10975)
I think mostly just testable once deployed and having seen that [the action runs every morning](https://github.com/wellcomecollection/wellcomecollection.org/actions/workflows/prismic-linting.yml).
Biggest risk is it won't run properly, which isn't that big of an issue and we can address it then.
=> Change schedule and upgrade checkout

content/webapp/components/Work/Work.tsx
We have works with restricted access conditions that are reporting that they have volumes available online, which is confusing ([from Slack](https://wellcome.slack.com/archives/C8X9YKM5X/p1719829738540849)).
This PR checks the work's access condition isn't `restricted` or `closed` using logic from the pre-existing `showItemLink` function and hides the label where necessary.
E.g. this url: https://wellcomecollection.org/works/z3mb56ec
__Before__
__After__
=> Don't show available online label if access condition is restricted

content/webapp/components/PhysicalItems/PhysicalItems.tsx
This fixes a bug [discussed on slack](https://wellcome.slack.com/archives/C8X9YKM5X/p1719928655349099), where the items availability doesn't update when the tree navigation is used to move between items
- Run the site locally using `yarn run-concurrently`
- Log in
- Visit http://localhost:3000/works/pxr3mfzx
- notice that under where to find it the item is listed as 'Temporarily unavailable' (N.B. this is true 4/7/2024)
- click on the next item in the archive tree '[Diary 1941]'
- notice the where to find it now has a request button
- click the request button and see available dates are present
=> set itemsState to ‘stale’ when work items change

content/webapp/components/PhysicalItems/PhysicalItems.tsx
Following [this](https://github.com/wellcomecollection/wellcomecollection.org/pull/10987) fix, there was still a case where the items' status and method didn't refresh correctly when navigating an archive tree
This adds 'items' in the dependency array so that the itemsState is change whenever the items change (as happens when  navigating an archive tree)
Running this branch locally: 
https://wellcomecollection.org/works/pxr3mfzx is on hold
Navigate to Diary 1943: it should be requestable online
Back to Diary 1940: it should be on hold
https://wellcomecollection.org/works/vksj5snf
1st item on the next level (PP/AMI/D/1) is not requestable 
Navigate to PP/AMI/D/10: is requestable
Back to PP/AMI/D/1: not requestable
=> add items as dependency for setItemsState

common/services/conversion/track.ts, common/views/pages/_app.tsx
Does an extra check on whether or not to display the cookie banner. As per #10962 , the banner has been displaying in the page builder previews and the slice simulator, as it's actually an iframe of the website. 
I went for [what was suggested here](https://www.geeksforgeeks.org/how-to-check-a-webpage-is-loaded-inside-an-iframe-or-into-the-browser-window-using-javascript/) to figure out whether or not the document is rendered within an iframe. Had to do it through `useEffect` to access `window`, so there's a slight delay in hiding it in `iframe` as we wanted it to display by default.
Run locally, both the website (it should display the banner) and the slice simulator (it shouldn't)
We don't see the banner in the page builder previews and they're made useful again!
Banner stops displaying …
=> Suggestion to hide cookie banner within iframes

content/webapp/components/WorkDetails/WorkDetails.Holdings.tsx
Removes duplicate keys that caused a console warning. Keys aren't necessary here (they're not part of a list) and made for duplicate elements when hot reloading.
Run locally; no error in console when on a work page that has a holding (like https://wellcomecollection.org/works/ysmqsfhg)
It works!
No risk here that I can think of.
=> Remove unnecessary keys that caused console error

cache/cloudfront_functions/rss-url-rewrite.js, cache/cloudfront_rss.tf, content/webapp/app.ts
This change adds a CloudFront distribution for `rss.wellcomecollection.org` so that we can continue to serve content from that URL. We are using a [CloudFront Function](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-functions.html) to rewrite URLs.
Requests come to https://rss.wellcomecollection.org/stories, the CloudFront distribution described in this PR will direct them to a behaviour which points them at the content app ALB origin, but rewrites requests for /stories to /rss and returns 404s for all other requests to `rss.wellcomecollection.org`.
Follows: https://github.com/wellcomecollection/wellcomecollection.org/pull/10982, which implements the RSS endpoint on the content app.
```console
+ resource "aws_cloudfront_distribution" "wc_org" {
+ aliases …
```
=> Add CloudFront distro to front requests to rss.wellcomecollection.org

content/webapp/services/prismic/fetch/exhibitions.test.ts
We have a test that will break once in a while when a new exhibition gets published in Prismic. I came across it as the end of a day when I was trying to fix something I'd merged to `main`, so I didn't really want to have to fix a test on top of it. This could happen when we need a quick fix in prod and would block deployments, so here is what I suggest: Instead of looking at all events forever after, we slice the results and only keep the first few to compare. AFAIK, we only want to check that the exhibitions that closed on 23 April 2023 are no longer returned the next day, so this should do?
Does it pass here in CI? (yes it does)
We never have to add an exhibition to our tests ad-hoc again
I do wonder what happens to Prismic IDs once we run out of "Z" to start them with, the ordering by …
=> Suggest change to exhibition test

toggles/webapp/package.json, yarn.lock
I ony noticed when reviewing `node-toggles`, but when I [changed the tsconfig in toggles](https://github.com/wellcomecollection/wellcomecollection.org/pull/10978), it broke our scripts which weren't happy. I googled the errors that were coming back, and it seems [others have come across it](https://stackoverflow.com/a/76343394). They recommended switching from `ts-node` to `tsx` ([here](https://www.npmjs.com/package/tsx)) to run TS in node. And it fixed it!
- Run branch locally
- `yarn`
- `yarn deploy` (I added a test toggle to test with and then removed it)
It works!
It stops working and we fix it but it doesn't stop anyone from doing anything.
Follow-up ticket created [here](https://github.com/wellcomecollection/wellcomecollection.org/issues/11005) for more tidying
=> Fix toggles deployments

content/webapp/components/IIIFViewer/IIIFViewerImage.tsx
Removes string used for tests as per [confirmation here](https://wellcome.slack.com/archives/CBT40CMKQ/p1720583824239179?thread_ts=1720452922.330679&cid=CBT40CMKQ) (related to #10999)
Run locally and use item viewer, for example on `works/nny5wq9u/items`
Do they show up, is the console error free?
We are sure this was not meant to be there, so risk free.
=> Remove test string from url

updown/package.json
Putting back a dependency that I erroneously believed to have been shared at the root
=> Re-add Typescript as a devDependency for upddown

cache/send_slack_alert_for_5xx_errors.js
We've seen [errors](https://wellcome.slack.com/archives/CQ720BG02/p1720597318517099) with this code, which should be fixed by this addition of optional chaining in case `query` is `null`
`send_slack_alert_for_5xx_errors` stop erroring 
Yes
terraform plan output
```
Terraform will perform the following actions:
~ resource "aws_lambda_function" "lambda_function" {
id                             = "send_slack_alert_for_5xx_errors"
~ last_modified                  = "2023-11-07T16:48:07.000+0000" -> (known after apply)
~ source_code_hash               = "Kk8nGDlMCyoPjl/O+gF+5ZWlC+daOijuIUoooE+egs8=" -> "K2lUcAtnTSHqH5gLPlSjrzaOfESI34TxSxxzZNm+yC0="
tags                           = {}
}
Plan: 0 to add, 1 to change, 0 to destroy.
```
=> optional chaining in case query is not defined/null

package.json, yarn.lock
Two `lint-staged` dependencies were flagged as having a critical security issue, [`property-expr`](https://github.com/wellcomecollection/wellcomecollection.org/security/dependabot/114) and [`simple-git`](https://github.com/wellcomecollection/wellcomecollection.org/security/dependabot/145). 
We used a very old version of `lint-staged`, so I upgraded it to `v14` (`v15` wants Node 20 and we're not officially there yet).
I removed `git add` as the last command as it's [done automatically since `v10`](https://github.com/lint-staged/lint-staged/releases/tag/v10.0.0).
I tested and it seems to still catch all errors so think we're good! 
Run locally and commit code (`pre-commit` should catch errors if there are any)
No more critical warnings!
Pre commit doesn't work and we address it.
=> Upgrade `lint-staged`

pa11y/webapp/package.json, pa11y/webapp/write-report.js, pa11y/webapp/yarn.lock
One of our critical flags ([here](https://github.com/wellcomecollection/wellcomecollection.org/security/dependabot/85)) has to do with one of this package's dependencies. Here's [the repo](https://github.com/ahmadnassri/mkdirp-promise?tab=readme-ov-file). They've made it pretty clear we shouldn't be using it (hasn't been touched in 7 years, is archived and unmaintained), but they did say how to replace it, which was a simple use of `fs.mkdir` instead :)
I followed [the docs](https://nodejs.org/api/fs.html#fs_fspromises_mkdir_path_options) here.
I ran `write-report` locally and it worked well.
Run it locally too
Pa11y still runs successfully
Pa11y fails, and we fix it.
=> Remove `mkdirp-promise` package and replace its use

.github/workflows/chromatic.yml, .github/workflows/performance.yml, .github/workflows/tsc.yml
Relates to #10846 
Addresses older TODO; we chose to always specify the `node-version` as per documentation's recommendation.
Upgraded it to use node 20 as per our recent upgrades. 
[It's been flagged as a step in future Node upgrades](https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/DPDDj27NI2F2kPukWrC1/language-tool-specific-notes/nodejs-updates) as well.
Did the actions run ok in here? (Yes)
The actions ran ok in here.
N/A
=> Upgrade github action's node-versions

content/webapp/components/WorkDetails/WorkDetails.DownloadItem.tsx
For #11012 
Adding a `data-gtm-trigger` attribute to links in the `DownloadTable` component that houses the born digital items that are available to download.
There will be an accompanying piece of work to complete within GTM to use thes data-attributes as triggers (in keeping with how we've done long-lived GTM tracking before) to fire tags.
I don't think it's possible to test locally because the triggers are behind a toggle which doesn't work in conjunction with GTM preview. 
Events are being sent through to GA4
can't think of any
=> Add data-gtm-trigger for born digital items

common/data/microcopy.tsx
Relates to #11013 
__Before__
__After__
=> Update born-digital microcopy

common/customtypes/articles/index.json, common/customtypes/books/index.json, common/customtypes/event-series/index.json, common/customtypes/events/index.json, common/customtypes/exhibition-guides/index.json, common/customtypes/exhibition-highlight-tours/index.json, common/customtypes/exhibition-texts/index.json, common/customtypes/exhibitions/index.json, common/customtypes/guides/index.json, common/customtypes/pages/index.json, common/customtypes/projects/index.json, common/customtypes/seasons/index.json, common/customtypes/series/index.json, common/customtypes/visual-stories/index.json, common/customtypes/webcomic-series/index.json, common/customtypes/webcomics/index.json, common/prismicio-types.d.ts, common/services/prismic/documents.ts, content/webapp/services/prismic/transformers/pages.test.ts
For #11023
It adds a uid field to the content types we will want to query by uid
These have been applied to the stage environment so are visible there. (Once this approved I will notify the content team and apply then to the prod environment).
- Login to Prismic
- Switch to the stage environment
- Visit any of the relevant content types and see the uid field is present
We are able to add values to uid fields in Prismic.
Have tested in the stage environment first to determine how the uid field behaves:
Before saving a document the uid field will auto populate with text from the first rich text field to be edited, but will be overidden with whatever is in the title field when that is edited.
After saving a document the uid field will only change if it is edited directly.
=> Add uid fields to custom types

pa11y/webapp/package.json, pa11y/webapp/yarn.lock
Should get rid of these two "High" level security flags 
- https://github.com/wellcomecollection/wellcomecollection.org/security/dependabot/180
- https://github.com/wellcomecollection/wellcomecollection.org/security/dependabot/185
`ip` is removed from the new version of puppeteer and `ws` is upgraded to a patched version.
Run `yarn write-report` and `AWS_PROFILE=experience-developer yarn deploy` locally, do they work?
No more security flags for pa11y
N/A
=> Upgrade `puppeteer` to get rid of security issues

content/webapp/services/iiif/fetch/manifest.ts
Wrap the `fetch` in a try/catch. We're getting [a lot of errors in the #platform-alerts channel](https://wellcome.slack.com/archives/CQ720BG02/p1722324584987659) that seem related to this, so thinking this might give us more information.
Are the tests passing?
We get more information and can get to the bottom of what is causing the errors
No harm in adding this.
=> Wrap Manifest fetch in try/catch to get more details on error

cache/edge_lambdas.tf, cache/edge_lambdas/Dockerfile, cache/locals.tf
This change upgrades the runtime for our edge lambdas to Node version 20 (LTS), in order to remain on a supported version of the node runtime. For the edge-lambdas this is especially important as the response lambda is using node 12 which is out of support in AWS and cannot be modified without upgrading the runtime.
See: https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-node-js-12-x-in-the-aws-sdk-for-javascript-v3/
Currently the request edge lambda is using node 16, and the response edge lambda using node 12 despite being the same code and both being tested with a node 16 based Dockerfile. This change aligns the tests and runtimes to node 20.
Edge lambdas require using [versioned lambdas and specifying the lambda version …
=> Upgrade edge lambdas to node 20

playwright/test/helpers/contexts.ts, playwright/test/work.test.ts
Adds two tests
1. To check that clicking on inner tree items doesn't close the tree
2. To check that the relevant GTM trigger (`download_table_link`) fires when a link is clicked
`cd playwright && yarn test work.test.ts`
=> Tests for ArchiveTree.ListItem with born digital items

content/webapp/pages/exhibitions/[exhibitionId]/index.tsx
For #11078
Loads the Hotjar script on the [Jason exhibition page](https://wellcomecollection.org/exhibitions/ZZP8BxAAALeD00jo)
- Visit the Jason exhibition page and see the hotjar script being added in the network panel
- Visit a different exhibition and see that the script isn't being added there
We get heatmap data showing up in Hotjar (I've set this up [here](https://insights.hotjar.com/sites/3858/heatmap/view?url=https%3A%2F%2Fwellcomecollection.org%2Fexhibitions%2FZZP8BxAAALeD00jo&match=simple_match&device=desktop&type=click&overlays=top_clicked_elements&filters=%7B%7D&date=%7B%22DAYS_AGO%22%3A%7B%22created%22%3A30%7D%7D))
=> Add Hotjar to Jason exhibition page

common/views/components/PageHeader/PageHeader.tsx, content/webapp/components/ExhibitionGuideLinks/ExhibitionGuideLinks.tsx, content/webapp/components/ExhibitionGuideLinks/TypeOption.tsx, content/webapp/components/ExhibitionGuidePromo/ExhibitionGuidePromo.tsx, content/webapp/components/ExhibitionGuideRelevantIcons/index.tsx, content/webapp/pages/guides/exhibitions/[id]/[type].tsx, content/webapp/pages/guides/exhibitions/index.tsx
Relates to #11033 
I aimed to make separate commits that made sense, so you could review them one by one.
- Adjust `PageHeader` so that where there are no breadcrumbs (no items and no home link), there is still spacing above the title
- New component `RelevantGuideIcons` to render out the right icons in the landing page, the exhibition specific guide page and the guide pages themselves
- Style Landing page as per mockups, behind toggle
- Moved some things from `<TypeOption>` declaration to `TypeOption.tsx` itself (like the `onClick` function).
Run locally, test with toggle and without to ensure the current versions stayed the same. 
Ensure cookie is being set.
N/A - WIP
N/A
=> Exhibition Guides: Main landing page

common/views/components/PageHeader/PageHeader.tsx, content/webapp/components/ExhibitionGuidePromo/ExhibitionGuidePromo.tsx, content/webapp/pages/guides/exhibitions/[id]/[type].tsx
Minor style tweaks after initial chat:
- Make spacing smaller between title and subheading
- Change "captions and transcripts" subheading to "Exhibition text" behind toggle. The URL probably still needs to be updated, but as discussed with @LaurenFBaily it'll wait.
- Change subheading font as per #11081
- Adjusted spacing between text and icons on cards - done live on a share screen with Kasia.
Run locally and admire.
N/A
N/A
=> EG: Small visual changes from initial chat with Kasia

playwright/test/article.test.ts
There is a known Prismic issue with crops that they're in the process of fixing
https://github.com/wellcomecollection/wellcomecollection.org/issues/10853
In the meantime, the `expected` is not reliable enough and makes this test flaky
See https://wellcome.slack.com/archives/CUA669WHH/p1722527788912479
Run the tests, they pass and this one is skipped
Catalogue-api can be deployed (it runs the e2e tests)
Experience team are aware of the issue and keeping in touch with Prismic
A ticket has been created as a reminder to reinstate the test when Prismic has fixed 
https://github.com/orgs/wellcomecollection/projects/18/views/1#
=> commenting out test until Prismic fixes the underlying issue

content/webapp/components/ArchiveTree/ArchiveTree.ListItem.tsx, content/webapp/components/ArchiveTree/ArchiveTree.NestedList.tsx, content/webapp/components/ArchiveTree/index.tsx, content/webapp/components/WorkDetails/WorkDetails.AvailableOnline.tsx
For #11065
Allows a consumer of `NestedList` (and by extension, `ArchiveList.TreeItem`) to decide whether clicks on the TreeItems should trigger a fetching of child items. It does this by adding a required boolean `shouldFetchChildren` prop.
I found I _could_ have tested for `ItemRenderer.name === 'DownloadItemRender'`, without the need for an additional prop with our current setup, but this felt a bit brittle and less clear as to what the intention was.
1. Turn on the showBornDigital toggle
2. Open the 'objects' tree on http://localhost:3000/works/htzhunbw
3. Click on one of the revealed rows (not the 'download' link)
4. Check there aren't any XHR requests being made/erroring in the console
We stop making unnecessary network requests
We have to remember to make the `shouldFetchChildren` …
=> Add shouldFetchChildren prop to NestedList/ListItem

content/webapp/components/ExhibitionGuideLinks/TypeOption.tsx, content/webapp/components/ExhibitionGuideLinksPromo/ExhibitionGuideLinksPromo.tsx, content/webapp/components/ExhibitionGuideRelevantIcons/index.tsx
Changes made based on [Kasia's comment](https://github.com/wellcomecollection/wellcomecollection.org/issues/11033#issuecomment-2262921790) in #11033 to better align BSL/AD/TEXT icons with arrow.
Before
After
Compare with [designs](https://www.figma.com/design/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?node-id=1333-2854&t=sM1uvCzEWBLfeSBl-0)
N/A
N/A
=> Tweak icon alignment on Exhibition Guide cards

common/prismicio-types.d.ts, common/views/slices/GuideStop/model.json
- Adds an image field to the GuideStop slice (for #11042)
- Adds a Video subtitles field to the GuideStop slice (part of #11038)
- Changes existing 'transcript' label to 'Audio transcript' (api ID remains as `transcript`)
We don't have any published Exhibition highlight tour documents yet so don't think there's anything to test
Let's us create frontend EG journeys
Naming of fields could have been confusing – hopefully the labels/placeholders and orderings of them provide enough clarity for use
=> EG GuideStop image, audio transcript, and video subtitles fields

content/webapp/components/ExhibitionGuideLinks/TypeOption.tsx
As part of #11033, I merged #11083 without realising that on bigger desktop screens, the alignment was off: 
**Before**
**After**
I'm aware I might be taking a hammer to the fix, my brain still tends to think in `flex`, so do let me know if there's a nicer way to do this.
Run locally
Kasia's happy!
N/A
=> Fix alignment of TypeOption cards

.github/workflows/prismic-linting.yml, README.md
Prismic linting action [was repeatedly failing](https://github.com/wellcomecollection/wellcomecollection.org/actions/runs/10242411617) and [I reached out on Slack](https://wellcome.slack.com/archives/C3TQSF63C/p1722849702140089) to figure out why. @StepanBrychta sent this thread our way and explained the fix:
https://github.com/orgs/community/discussions/116610#discussioncomment-10239694
> [...] the latest Ubuntu release (ubuntu-latest) in [Ubuntu 22.04 (20240730) Image Update](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240730.2) removed Docker Compose v1 support as announced in [GitHub's blog post](https://github.blog/changelog/2024-04-10-github-hosted-runner-images-deprecation-notice-docker-compose-v1/). The relevant issue is here: …
=> Prismic Linting: Move from `docker-compose` (v1) to `docker compose` (v2) 

content/webapp/components/ExhibitionGuideLinks/TypeOption.tsx
Relates to #11033 (specifically [this comment](https://github.com/wellcomecollection/wellcomecollection.org/issues/11033#issuecomment-2270727174))
`CardBody` matches most of what we need for this component and it aligns it with the other cards' padding.
Run locally and check tablet and mobile paddings now match the other cards.
N/A
N/A
=> Use CardBody SC for TypeOption component

.github/workflows/prismic-linting.yml
As only the author of the action gets alerted when it fails, we wanted to add it as a Slack alert as well.
I've done it using a mix of https://github.com/slackapi/slack-github-action (thanks @davidpmccormick !) and https://tomjones.dev/blog/send-github-action-workflow-failure-notifications-to-slack/ for understanding how to fire it under certain conditions.
Adds an `on-failure` step to `prismic-linting.yml` that only fires when the task status is `failure` or `timed_out`.
It works in tandem with the `GitHub actions workflow` automation in Slack to send a message to #wc-platform-alerts when fired, with relevant information.
Create a new branch and re-add these lines https://github.com/wellcomecollection/wellcomecollection.org/pull/11093/commits/16e5d38eccd32d81faf08f64d46797c5a6f39a4e to …
=> GitHub action slack

updown/package.json, updown/yarn.lock
Fixes flagged security issues:
High:
https://github.com/wellcomecollection/wellcomecollection.org/security/dependabot/187
Moderate:
https://github.com/wellcomecollection/wellcomecollection.org/security/dependabot/110
https://github.com/wellcomecollection/wellcomecollection.org/security/dependabot/109
`cd updown`
`rm -rf node_modules && rm -rf yarn.lock`
`yarn`
Follow README doc to run `apply`, should work nicely and use updated versions of the problematic dependencies listed above.
Enhanced security
N/A
=> Updown: Upgrade packages to avoid security issues

content/webapp/services/iiif/fetch/manifest.ts
This change logs an error when no IIIF manifest is found rather than throwing as this breaks works pages in the whole when we could still display useful information.
In general we should try to degrade gracefully and avoid extraneous requests failing whole page loads.
Reduced noise in our alerts channel, more graceful failure on works pages
This change returns the behaviour to a previous known state, hopefully mitigating any risk.
=> When IIIF manifest 404s, log don't throw

dash/webapp/pages/toggles.tsx
Relates to #11100 
We realised that the current way of resetting does not actually work in Safari, as it _sets_ them without a value instead of deleting them.
That's fine for our actual use of toggles as they are checking if the value is `true` and `undefined` is falsy, but as we [made changes to the error page](https://github.com/wellcomecollection/wellcomecollection.org/pull/11090) and that checks if a cookie _exists_, they are listed there if set, whatever their value.
One of the fixes would've been to just change that error message and only list a toggle if true, but I feel like it's still useful to have it listed whatever its value, and therefore the fix laid here.
- Use of `cookies-next` for setting and deleting (as we used it to `get` them anyway). Makes it more readable IMO as …
=> Toggles dashboard: Fix Safari and use library

content/webapp/services/iiif/transformers/manifest.ts, content/webapp/types/manifest.ts, content/webapp/utils/iiif/v3/index.ts
For #11096.
Adds iiif V2 auth services to TransformedManifest
Our manifests reference both the v1 and v2 Auth services.
We currently use the v1 services. This is the first step in making use of the v2 services.
Not really easy to test as nothing on the front end should change yet.
This is part of the work that will make restricted items available to staff with the correct permissions, but needs further work to make this possible.
This shouldn't impact the site.
=> Add iiif V2 auth services to TransformedManifest

cardigan/stories/components/BookPromo/BookPromo.stories.tsx, cardigan/stories/components/Cards/Cards.stories.tsx, cardigan/stories/components/ImageGallery/ImageGallery.stories.tsx, cardigan/stories/components/SeasonsHeader/SeasonsHeader.stories.tsx, cardigan/stories/components/Tabs/Tabs.stories.tsx
[Tabs has been flagging a lot as different recently](https://wellcome.slack.com/archives/CUA669WHH/p1724054820504579). The theory is that it's because of the Readme Decorator loading, so we'll add a second delay to allow the snapshot more time.
I also took the opportunity to test removing `delay` and `diffThreshold` from the stories with images. [We originally thought it was needed](https://github.com/wellcomecollection/wellcomecollection.org/pull/9680) but then found out it was most likely that the images weren't static, which we've now addressed.
See the Chromatic tests below.
Tabs stop being flagged unnecessarily.
None, really.
=> Chromatic snapshots: Remove delays for image, add delay for Tabs

content/webapp/components/AudioPlayer/AudioPlayer.tsx
For #10995
This makes sure the browser's default `<audio>` element will be visible if JavaScript isn't available
- Visit `/guides/exhibitions/Zdcs4BEAACMA6abC/audio-without-descriptions`
- Turn off JS
- Check you can still play the audio
Not sure
=> Load the default browser audio element if there's no JS

content/webapp/pages/guides/exhibitions/[id]/[type]/[stop]/index.tsx
Uses `useEffect` in conjunction with `useCallback` so that the `ResizeObserver` can be disconnected when it is no longer needed.
Check the audio player still sticks beneath the header the correct point when scrolling the page
We prevent potential memory leaks (although not sure how to measure this)
=> Disconnect the resize observer in a useEffect

toggles/webapp/toggles.ts
Relates to https://github.com/wellcomecollection/platform/issues/5747
Adds a toggle for using IIIF auth v2 services.
Our iiif manifests contain both auth V1 and auth V2 services.
This will help with the work around viewing restricted items and moving over to auth V2 services more generally.
Can't really, but once deployed the toggle will show at https://dash.wellcomecollection.org/toggles/ in the temporary section.
=> add a toggle for auth v2

content/webapp/pages/guides/exhibitions/[id]/[type]/[stop]/index.tsx
If you opened the transcript on a guide stop page and scrolled to the bottom, then clicked next/previous, you would still be at that window scroll position because the routing is being done client side. This resets the scroll position to the top of the page after a client-side route change
- Make your browser window small enough that the transcripts need to scroll a good deal
- Visit [test stop 1](http://localhost:3000/guides/exhibitions/ZrHvtxEAACYAWmfc/audio-without-descriptions/1)
- Click the 'Next' link bottom right
- Verify that you are scrolled to the top of the new page
n/a
n/a
=> Scroll the page to the top after a client-side update

content/webapp/components/AudioPlayer/AudioPlayer.tsx
If you have an audio file playing and change the stop using the prev/next buttons, the play/pause button doesn't currently reset itself because it's a client-side routing event and we don't re-instantiate the AudioPlayer component. This leaves the UI in a broken state.
- Go to a [stop page](http://localhost:3000/guides/exhibitions/ZrHvtxEAACYAWmfc/audio-without-descriptions/2)
- Play the audio
- Click Previous or Next and see the stopped audio shows a play button rather than a pause button
n/a
Is this something that would benefit from a test?
=> Fix AudioPlayer bug

content/webapp/pages/exhibitions/[exhibitionId]/index.tsx, content/webapp/pages/guides/exhibitions/[id]/[type]/index.tsx, content/webapp/types/exhibition-guides.ts, content/webapp/utils/digital-guides.ts, playwright/test/exhibition-guides.test.ts
Relates to #11039
After work on #11118, this serves to add loads of tests, aimed to test if we still supported legacy exhibition guides, as well as if the new ones behaved the way we expect them to.
- "Exhibition Guides redesign/restructure work" toggle is ON
- Run locally with the [Prismic endpoint](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/common/services/prismic/fetch/index.ts#L32) set to wellcomecollection-stage.
- Once this is done, you can uncomment the last tests, they need the data that's in staging right now to work. Then run all the tests.
Test with and without the `egWorks` toggle, with and without the Prismic staging, so we can make sure it won't affect current behaviour.
Green tests 👍 
N/A
Although, can you see anything I would've forgotten?
=> Digital Guides QR logic pt II: Add e2e tests

content/webapp/pages/guides/exhibitions/[id]/[type]/index.tsx
For #11126 
Makes the exhibition guide type title slightly smaller in line with the designs
I don't think it's required
n/a
n/a
=> Smaller exhibition guide type title

content/webapp/components/GuideStopCard/index.tsx
Exhibition Guide QA revealed that the icons should be center aligned with the first line of text if the text flows onto more than one line. This would also be a problem in the `GuideStopCard`s so I'm fixing pre-emptively
__before__
__after__
Visit e.g. `guides/exhibitions/ZrHvtxEAACYAWmfc/audio-without-descriptions`, make your browser very narrow to force card icon/text copy onto a second line and check the icon is aligned properly in the center of the first line
n/a
n/a
=> Align icons to center of first line of text in GuideStopCard

.github/workflows/stale.yml
Call the reusable workflow https://github.com/wellcomecollection/.github/blob/main/.github/workflows/stale.yml, avoids duplication in multiple projects
Change the cron expression to something more frequent and wait for the workflow to run
Runs only on `main`
Stale PRs are checked every morning Mon-Thu
Workflow is easier to maintain, changes applied only in one place
Negligible
=> use-new-stale-PR-workflow

content/webapp/pages/guides/exhibitions/[id]/[type]/[stop]/index.tsx
This increases the space below the CollapsibleContent on an exhibition guide stop page, so that there is some room between the content and the fixed footer.
__before__
__after__
Visit e.g. `/guides/exhibitions/ZrHvtxEAACYAWmfc/audio-without-descriptions/2`, click 'Read full transcript', scroll to the bottom of the page and check there's space between the bottom of the content and the fixed footer.
n/a
n/a
=> Increase space below content (to clear fixed footer)

content/webapp/components/ExhibitionGuideLinks/ExhibitionGuideLinks.tsx
Adds spacing if "Exhibition text" is the second section in a Guides listing page
**Before**
**After**
Run locally with staging content, where I've added the new Jason guides to Kola Nut (to keep the current legacy guides up as well)
N/A
N/A
=> Add spacing above Exhibition text section

.buildkite/urls/expected_200_urls.txt, .buildkite/urls/expected_404_urls.txt
Relates to #11073 
Changed the [Check URL tests](https://buildkite.com/wellcomecollection/wc-dot-org-end-to-end-tests/builds/4855#0191c797-ce1b-4e22-9c1f-6a1f639e7be5) to look at URLs based on UIDs instead of ID
- Do we want to keep some ID-based URLs in there?
- Do we want to test more things?
Unsure, if it passes on this PR it should be fine, maybe just have a look at if anything else could be done!
We don't encounter surprise content types that don't support UIDs
Things don't get flagged when they should because we only test by UID
=> 5. Get Check URL to use uid-based URLs for its checks

content/webapp/pages/articles/[articleId].tsx, content/webapp/pages/books/[bookId].tsx, content/webapp/pages/event-series/[eventSeriesId].tsx, content/webapp/pages/events/[eventId]/index.tsx, content/webapp/pages/exhibitions/[exhibitionId]/index.tsx, content/webapp/pages/guides/exhibitions/[id]/[type]/index.tsx, content/webapp/pages/guides/exhibitions/[id]/index.tsx, content/webapp/pages/pages/[pageId].tsx, content/webapp/pages/seasons/[seasonId].tsx, content/webapp/pages/series/[seriesId].tsx, content/webapp/pages/visual-stories/[visualStoryId].tsx
Part of #11073 
We want the canonical ref to be referencing the UID, not the ID.
- Does it break any API Toolbar links to Prismic? (Should be using ID)
- Did I miss any? [See list](https://github.com/wellcomecollection/wellcomecollection.org/issues/11023)
- Does it work with and without `egWorks` on the guides pages, AND with and without the `Prismic staging` toggle as we need to check both legacy (Jason) and new (Kola Nut) guides are supported.
UID becomes the main URLs, incl on Google results
Something breaks?
=> 2. UID: Modify canonical URLs

common/views/components/Breadcrumb/Breadcrumb.tsx, common/views/components/LabelsList/LabelsList.tsx, content/webapp/pages/guides/[guideId].tsx, content/webapp/pages/guides/[pageId].tsx, content/webapp/pages/index.tsx, content/webapp/pages/pages/[pageId].tsx, content/webapp/pages/projects/[pageId].tsx, content/webapp/pages/projects/[projectId].tsx, content/webapp/pages/whats-on/index.tsx, content/webapp/services/prismic/fetch/guides.ts, content/webapp/services/prismic/fetch/pages.ts, content/webapp/services/prismic/fetch/projects.ts, content/webapp/services/prismic/transformers/index.ts, content/webapp/services/prismic/transformers/json-ld.ts, content/webapp/services/prismic/transformers/projects.ts, content/webapp/services/prismic/types/index.ts, content/webapp/types/projects.ts, content/webapp/utils/urls.ts
Relates to #11147
As part of the work in #11124, I realised Pages, Projects and Guide were using everything from `[pageId]`, including the `pageTransformer`, although guides and projects do not have the same shape, and `fetchPage`.
To simplify `fetchByUid`, which expects to know exactly which content type is being looked for, I've fully split them up, giving them their own fetches.
I've also moved some repeated helper files into various files, but out of `pageId`.
Run locally
**Project**
`YNx66hAAACYAG0x8`
`joy-is-a-protest`
URL prefix: `/projects/`
**Page**
`Zmq95BEAACMAGTxS`
`hard-graft--work--health-and-rights`
URL prefix: `/pages/`
**Guide**
`YL9OAxIAAB8AHsyv`
`archives-at-wellcome-collection`
URL prefix: `/guides/`
It's more readable and clearer what is being fetched where, easier to …
=> 4. UID: Split `guides` and `projects` from `pages`

common/views/components/CollapsibleContent/index.tsx
Relates to #11037 
[See visual change request in comment here](https://github.com/wellcomecollection/wellcomecollection.org/issues/11037#issuecomment-2340276294).
Before
After
Run locally with staging content activated and go to http://localhost:3000/guides/exhibitions/ZthrZRIAACQALvCC/audio-without-descriptions/1
Looks good.
N/A
=> CollapsibleContent; use margin instead of transform for indent

common/data/hardcoded-ids.ts, content/webapp/components/EventSchedule/EventSchedule.tsx, content/webapp/components/EventSchedule/EventScheduleItem.tsx, content/webapp/pages/events/[eventId]/index.tsx, content/webapp/services/prismic/transformers/events.ts
This changes the logic which determines whether the 'just show up' message is displayed on an EventScheduleItem
The [change was requested by Grace](https://wellcome.slack.com/archives/C8X9YKM5X/p1725962331127929?thread_ts=1717509512.966409&cid=C8X9YKM5X)
The 'just turn up' message will now only show if the 'drop in at any time' policy is added to the event.
There was already logic in place to prevent the message from showing under certain circumstances and I have left this in place. We will only show the message if  
- the event isn't past AND
it doesn't require booking (either through Eventbrite or by contacting the booking enquiry team) AND
- it doesn't have it's own event schedule
Also, if the event has early registration, then we will show 'Arrive early to register' rather than 'Just …
=> Just turn up logic

dash/README.md, dash/webapp/pages/prismic-linting.tsx
A follow up to https://github.com/wellcomecollection/wellcomecollection.org/pull/11167, I hadn't realised it wasn't reusing the same URL...
Deploy dash from local, but I've done it now so unless there's been a redeployment since you should be able to see the change. https://dash.wellcomecollection.org/prismic-linting
Actually useful for editors!
N/A
=> Change URL in dashboard for prismic document editing

content/webapp/components/ExhibitionGuideLinks/ExhibitionGuideLinks.tsx, content/webapp/pages/guides/exhibitions/[id]/index.tsx
Relates to #11174 
[Slack chat for Lauren's review](https://wellcome.slack.com/archives/CUA669WHH/p1726148985668539)
Run locally
Confirm it doesn't affect legacy exhibition guide copy or copy without toggle on.
N/A
N/A
=> Digital guides exhibition index page copy amendments

prismic-model/lintPrismicData.ts
Added a test that checks 1. which content types have a UID and 2. if one of their document is missing one.
I think the logic makes sense but it's possibly a bit iffy as it assumes the UID field is always in the first tab of the editor?
Run script locally.
N/A
N/A
=> Add a Prismic linting UID check

content/webapp/utils/digital-guides.ts
Now that the `egWork` toggle is set to true publicly, we're happy to remove the check.
The value isn't returned properly when checked in the code since remote toggle values (publicly set ones) are not being fetched yet, only on the client. We _should_ add something to fetch them SS, but because we need this to work today, as agreed with Lauren we're happy to remove this bit in the code to fix it.
Legacy EG should still be supported, so it shouldn't cause any issues.
- new type: `guides/exhibitions/ZsdFlRIAACIAqKGB?usingQRCode=true&stopNumber=2&utm_source=Gallery1&utm_medium=QRCode&utm_id=HardGraftGuides&utm_content=Stop2`
- legacy type: `guides/exhibitions/Zdcs4BEAACMA6abC/audio-without-descriptions?utm_campaign=JasonWilsherMillsGuide&utm_medium=QRCode&utm_source=Gallery2&utm_content=Stop0 …
=> Remove toggle check on redirection for Digital Guides

cache/edge_lambdas/src/redirects.ts, playwright/test/exhibition-guides.test.ts, playwright/test/helpers/contexts.ts
relates to https://github.com/wellcomecollection/wellcomecollection.org/issues/11131
relates to [#11140](https://github.com/wellcomecollection/wellcomecollection.org/issues/11140)
Add redirection URLs for the legacy Jason guide to redirect to the new ones. A new PR will be created to apply it to prod if it's successful in staging.
Also amends the e2es to point to this new guide, and removes the `.skip()` that was there on the two last ones since we've now made the `egWork` toggle public.
Do tests pass?
Better test coverage and redirections work in staging. 
Borked redirects, but it won't affect prod at this stage.
=> Jason DG redirections and e2e amendments

dash/webapp/package.json, dash/webapp/yarn.lock
https://github.com/wellcomecollection/wellcomecollection.org/security/dependabot/207
Addresses vulnerability alert.
The other repos are using `13.2.3` which isn't affected (although maybe we'd want to upgrade it soonish as it's not on the newest major version?)
Run it locally! 
No mo' of that High security issue.
N/A patch fix
=> Dash upgrade patch version of Next for security vulnerability

cache/locals.tf
Changes edge lambda versions to reflect the recent redirections so they're applied to prod (og ticket #11180)
Only once in prod can we check this works but you can check in staging if they do already (see og ticket for redirects). You might have to use an incognito window or clear the cache for it to work as it's a recent change.
Legacy Jason DG can be archived and we don't have to support it
Maybe other changes have been applied but staging works just fine so reckon we're good to go.
=> Change edge_lambda_*_versions to newest ones for redirections

.buildkite/pipeline.yml
Following https://github.com/wellcomecollection/wellcomecollection.org/pull/11183 it was noticed that the `"Add steps for e2e tests (if necessary)"` was still run on `main` even though it doesn't do anything (we run e2e tests in the deployment pipeline for `main`)
See: https://wellcome.slack.com/archives/CUA669WHH/p1726676801756259
When merging something to `main` check the [wc.org: build + test](https://buildkite.com/wellcomecollection/wc-dot-org-build-plus-test) pipeline. It should not have a "Add steps for e2e tests (if necessary)" step.
Less noise in the pipeline. 
This step currently fails gracefully and doesn't do anything.
=> Add steps for e2e tests (if necessary) step not to run on main

content/webapp/components/ExpandedImage/ExpandedImage.tsx, content/webapp/pages/works/[workId]/download.tsx, content/webapp/pages/works/[workId]/index.tsx, content/webapp/pages/works/[workId]/items.tsx, content/webapp/services/iiif/fetch/manifest.ts
Relates to [#11128](https://github.com/wellcomecollection/wellcomecollection.org/issues/11128), see ticket for details.
Difficult to test without a known "broken" work (should have a manifest but doesn't), but we mostly want to make sure the condition makes sense still and nothing of this shows on the alerts channel if it's a BD work
Less hacky good 👍 
Alerts channel not spammed.
Worst case we get the alerts and tweak the condition.
=> Use new workType to identify BD works

content/webapp/components/ArchiveTree/ArchiveTree.ListItem.tsx
Users should be able to tab to the link within a selected item of the archive tree. This isn't currently the case and this PR fixes it
Visit http://localhost:3000/works/g7zn5j4n, tab to the archive tree - use the arrow keys to move to items within the tree. You should be able to tab to the link within the selected item.
The archive tree links are accessible via keyboard controls
I don't think there are any. It's broken at the moment
=> Fix keyboard control of archive tree

content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.Stop.tsx, content/webapp/components/ExhibitionCaptions/ExhibitionCaptions.tsx, content/webapp/components/ExhibitionGuideLinks/ExhibitionGuideLinks.tsx, content/webapp/components/ExhibitionGuideLinks/TypeOption.tsx, content/webapp/components/ExhibitionGuidePromo/ExhibitionGuidePromo.tsx, content/webapp/pages/guides/exhibitions/[id]/[type]/index.tsx, content/webapp/pages/guides/exhibitions/[id]/index.tsx, content/webapp/pages/guides/exhibitions/index.tsx, content/webapp/types/exhibition-guides.ts, content/webapp/utils/digital-guides.test.ts, content/webapp/utils/digital-guides.ts, playwright/test/exhibition-guides.test.ts, toggles/webapp/toggles.ts
#11131 tidies the codebase after `egWorks` has successfully been made public, and we stop supporting legacy QR codes. As we've moved Jason over and it was the only one still using them, this should be good to go.
- Removed legacy tests
- Removed `getTypeColor()` helper function as we don't use those colours on DG anymore
- Remove all `egWorks` conditions and the toggle
- Removed redirection logic for legacy guides
- Removed redirection check in `content/webapp/pages/guides/exhibitions/[id]/[type]/index.tsx` as we do not point to that page from QR codes anymore.
> [!NOTE]
> There is still tidying work to do once we've migrated all legacy Exhibition Guide content types. They should be identified and done after https://github.com/wellcomecollection/wellcomecollection.org/issues/11181 is …
=> Remove `egWorks` toggle/conditions & legacy QR codes support

common/customtypes/exhibitions/index.json, common/prismicio-types.d.ts
Following [a request from Lalita](https://wellcome.slack.com/archives/CUA669WHH/p1727260676138799) this adds the ability to add  Stories serials and webcomics to the 'Related stories' section of an exhibition page.
I've deployed this change to prismic staging, so you can add these types to the page and preview the page locally.
Content editors can add stories serials and webcomics to the 'Related stories' section of an exhibition page and they will render on the page.
None I can think of
=> Add series and webcomics to ‘about’ linked document field

content/webapp/pages/api/prismic/works.ts
Adds an API endpoint to use with [Prismic's integration field](https://prismic.io/docs/integration)
The endpoint sits in front of the Catalogue API and returns the results in a format that is compatible with Prismic's integration field
I want to play with using the integration field as a way for content editors to add items from the collection into stories etc. directly from within Prismic. The first step is to have an endpoint the integration field can crawl, which is what this PR provides.
N.B. I believe Prismic limits the number of items to 100,000 by default (but it is possible to pay for more). The catalogue API will only let us retrieve 10,000 items. This would be a problem if ever wanted to use this for real as the catalogue contains well over a million items.
Visit …
=> Integration field endpoint

.github/workflows/prismic-linting.yml, prismic-model/lintPrismicData.ts
Relates to [#11202](https://github.com/wellcomecollection/wellcomecollection.org/issues/11202)
Currently, Natalie writes to #wc-editorial when the [Prismic linting script](https://github.com/wellcomecollection/wellcomecollection.org/actions/workflows/prismic-linting.yml) reports errors on [the dashboard](https://dash.wellcomecollection.org/prismic-linting/).
This aims to give her one less task every morning!
I've added a webhook workflow that posts this little message when an error or more is found:
I'll be curious to test it against the action itself, but running it locally it seems to work smoothly. See the #bot-test channel in Slack that I've created for stuff like this for all the versions of the bot 😄 The currently still points to it, I'll change that once we're happy and everything …
=> Trigger Slack bot when errors are found in Prismic linting Github action run

.github/workflows/tsc.yml, common/package.json, content/webapp/pages/guides/exhibitions/[id]/[type]/[stop]/index.tsx, playwright/package.json, playwright/yarn.lock, updown/tsconfig.json, yarn.lock
Relates to #11203 
Adds the `dash` and `updown` run.
Removed the part below, we won't be filtering on running only the repos with changes as it ran them against main the whole time, which means that PRs (e.g. `branch-b`) that should be compared against a parent PR (e.g. `branch-a`) would suffer from the same fails their parents to, even though the work in `branch-b` might have nothing to do with the fail.
Changes will be within `workspaces` 95% of the time anyway, so running the others alongside it doesn't add anything to the build time, as they're all under 30 seconds.
Uses https://github.com/dorny/paths-filter?tab=readme-ov-file to filter paths, determining which `tsc` tests should be run. The patch upgrades were to test the various tsc runs.
> [!NOTE]
> This compares your _branch_ to …
=> Run `tsc` on all TS repos, trial `path-files` to filter out when they run

common/views/components/LoadingIndicator/LoadingIndicator.tsx, common/views/components/TransitionLink/index.tsx, common/views/themes/base/transitions.ts, common/views/themes/default.ts, content/webapp/components/Card/Card.tsx, content/webapp/components/GuideStopCard/index.tsx, content/webapp/pages/guides/exhibitions/[id]/[type]/[stop]/index.tsx, toggles/webapp/toggles.ts
Adds a `TransitionLink` component that is a wrapper around the `next/link` component that allows for the platform–native [View Transitions](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API) to run if they're available.
https://github.com/user-attachments/assets/7d9cb7c5-f618-40fa-a762-0c3bd13f9a9e
Set `toggle_viewTransitions` to true locally and visit e.g. a [stops audio index](http://localhost:3000/guides/exhibitions/ZsdFlRIAACIAqKGB/audio-without-descriptions) – check zoom transitions work from cards to players, and slide transitions work with the previous/next buttons from individual stops.
Possibly requires user testing
If the animation is inconsistent or janky, the experience could feel broken. ~This updates all `CardOuter` components which will then by default …
=> View transitions

.github/dependabot.yml
The grouped updates currently contain some really big pieces ([see here](https://github.com/wellcomecollection/wellcomecollection.org/pull/11227)) that we intend on doing, but carefully and one at a time, so I'm ignoring them so the Dependabot upgrade PRs are relevant again.
Once merged I'll relaunch the action manually.
Dependabot PRs can be considered merge-able.
N/A
=> Dependabot; Ignore chromatic, storybook and next upgrades

.github/dependabot.yml
We have a [ticket](https://github.com/wellcomecollection/wellcomecollection.org/issues/11232) to upgrade eslint so we don't want it flagged in the meantime.
N/A
Less noise
N/A
=> Ignore eslint packages for now

.stylelintrc.js, package.json, yarn.lock
Upgrade to latest stylelint version, only thing that caused issue was `media-query-no-invalid` flagging media queries that used variables 
https://stylelint.io/user-guide/rules/media-query-no-invalid/
> This rule is only appropriate for CSS. You should not turn it on for CSS-like languages, such as Sass or Less, as they have their own syntaxes.
So I turned it off.
Run `yarn lint:css` locally at the root.
Up to date
N/A
=> Upgrade to stylelint 16

cache/edge_lambdas/package.json, cache/edge_lambdas/yarn.lock
Upgrades most packages to latest version
Add a `tsc` command line to typecheck with flags.
I ran `yarn test`, `yarn tsc` and `yarn build`. I don't fully dare testing `yarn deploy`, but I don't believe I've changed anything integral to its running, it's mostly typescript and types packages.
Up to date, no potential security flags
Things break and we revert.
=> Upgrade typescript and types/nodes in cache/edge_lambdas

playwright/test/search-images.test.ts
This adds a fourth(!) test in `search-images.test` to check the Dates filter is applied and returning results. It follows similar logic to the Dates filter check in `search-works.test`, but /images uses `source.production.dates.to/from` to utilise its Date filter. 
> [!NOTE]
> This test was built to meet some requirements in my portfolio as part of my work in Date filtering for `/images`, and so has no related issue par Date filtering work (inc. #9952)
It may not be necessary, so happy to discuss and close if so! 
Would it be useful to consider more specific checks, especially related to removal of the filter which caused some bugs last year? 
- Checking the filter can be removed and displays correct results (only up to YEAR or only from YEAR) when only one year is applied against …
=> e2e test in search-images to check the Date filter

content/webapp/components/IIIFViewer/IIIFViewer.tsx, content/webapp/components/IIIFViewer/MainViewer.tsx, content/webapp/components/IIIFViewer/ViewerStructures.tsx, content/webapp/components/ItemViewerContext/ItemViewerContext.tsx, content/webapp/pages/works/[workId]/items.tsx, content/webapp/utils/iiif/v3/index.ts, toggles/webapp/toggles.ts
For #11234
At the moment if a iiif manifest contains only restricted items then the viewer will not display on the item page and a modal will show telling the user that the items are restricted.
This will stay the same for most users, but if the user is logged in and has a role of 'StaffWithRestricted' the viewer will display instead.
The items themselves will still show as restricted, but this is another step towards making them available.
- Also, adds the accessToken to the ItemViewerContext and makes it available to the ItemRenderer (has no real effect yet, but will be important for [#5761](https://github.com/wellcomecollection/platform/issues/5761))
- Also, tidies up some TODOs that were in the files I was working with.
Run the site locally using `yarn run-concurrently` 
Visit …
=> Show viewer for staff

content/webapp/pages/works/[workId]/items.tsx, content/webapp/utils/iiif/v3/index.ts
Moves the getAuthService function so it can be shared and updates it to:
- return both the external and active services rather than just one. (We could get away with that until now, but we are going to have to use both now in order to make restricted things available to staff https://github.com/wellcomecollection/platform/issues/5761)
- ~only~ prefer to return v2 external services, as these are the only ones that work (v1 external service ids return a 404). We still need to fallback to the v1 service as the presence of the service helps us determine whether to show the viewer or not.
No behaviour should change.
Gets us closer to making restricted items available
No behaviour should change, so as long as e2e tests pass we should be good.
=> always use V2 version of iiif auth services for the external service

common/services/prismic/link-resolver.ts, content/webapp/components/ExhibitionGuideLinksPromo/ExhibitionGuideLinksPromo.tsx, content/webapp/pages/guides/exhibitions/index.tsx, content/webapp/types/exhibition-guides.ts
Relates to #11190
Noticed that the links on the bottom of an Exhibition page weren't going to the correct place:
https://wellcomecollection.org/guides/exhibitions/hard-graft-exhibition-text
Visit https://wellcomecollection.org/guides/exhibitions/hard-graft-exhibition-text and click the links at the bottom of the page under the 'Other exhibition guides available' heading
You can navigate to the expected destination by following the links
It's currently broken so this is an improvement
=> handle exhibition-highlight-tours type in linkResolver

common/views/components/Iframe/Iframe.tsx, content/webapp/pages/works/[workId]/items.tsx, pa11y/webapp/write-report.js
- Pa11y flag: I thought I'd found the Iframe that was being flagged by pa11y, `IframeAuthMessage` being a styled iframe without a title, but it doesn't seem like it since pa11y fails on here still.
- `IFrame` slice: 
- `frameborder` and `scrolling` are deprecated. I replaced one with CSS and the other seems to have been deprecated for a decade(?) without any true replacement. It didn't seem needed anyway?
- I added an aria-hidden as we didn't have a usable/specific title for the slice (unless we want to add a Title field?) [as suggested here](https://dequeuniversity.com/tips/provide-iframe-titles). If we'd rather add a title field let me know.
We currently have three uses for `<IFrame>` , do they still look good?
- articles/WcvK4CsAANQR59Up
- articles/WvQF4SIAAFNX_7Uf
- …
=> Add missing title to iFrame and hide iframe slice from readers

.eslintignore, content/webapp/services/wellcome/catalogue/images.ts, content/webapp/services/wellcome/catalogue/works.ts
Just noticed that cache/edge_lambdas added a .dist folder when running some of its scripts, which then got picked up by eslint, which we don't want.
Also amended two imports that were flagged as warnings.
`yarn lint` at root.
`yarn lint` stays useful
N/A
=> Add dist to eslintignore list

.github/dependabot.yml
We've [upgraded Storybook](#11279) to version 8 and we're ready for Dependabot to complain if there are things we need to address to do with Storybook.
n/a
We are told about problems and can fix them
=> Don't suppress storybook vulnerabilities now we've upgraded

cache/locals.tf
Will apply the redirect changes to prod https://github.com/wellcomecollection/wellcomecollection.org/pull/11293/files
- Go see in the Lambda app that I'm applying the correct new versions
- Once merged all the way to prod we can check that those redirects have stopped working as they have in staging.
Less useless redirects ✨ 
None, those pages have been archived a year ago.
=> Apply new version (lambdas) for redirects changes to apply

cache/edge_lambdas/src/redirects.ts
#11300 
When working on https://github.com/wellcomecollection/wellcomecollection.org/pull/11298 I deleted these few redirects, forgetting they'd still need to be prefixed by `/pages`, so re-adding them!
Can be tested once in staging.
Necessary redirects still in place.
N/A
=> Re-add redirections that should've not been deleted

content/webapp/pages/collections.tsx, content/webapp/pages/concepts/[conceptId].tsx, content/webapp/pages/exhibitions/[exhibitionId]/index.tsx, content/webapp/pages/guides/exhibitions/[id]/[type]/[stop]/index.tsx, content/webapp/pages/guides/exhibitions/[id]/[type]/index.tsx, content/webapp/pages/guides/exhibitions/[id]/index.tsx, content/webapp/pages/search/events.tsx, content/webapp/pages/search/images.tsx, content/webapp/pages/search/index.tsx, content/webapp/pages/search/stories.tsx, content/webapp/pages/search/works.tsx, content/webapp/pages/works/[workId]/images.tsx, content/webapp/pages/works/[workId]/index.tsx, content/webapp/pages/works/[workId]/items.tsx
#11306 
- Removes it from all Exhibitions and Digital Guides pages 
- Adds it to
- `/concepts/[conceptId]`
- `/collections`
- `/search`
- `/search/works`
- `/search/images`
- `/search/events`
- `/search/stories`
- `/works/[workId]`
- `/works/[workId]/items`
- `/works/[workId]/images`
Run locally and check if Hotjar scripts are loaded on the above page **only** when you have given analytics permissions.
Check that it doesn't load anymore where it's been removed.
So much success to be gained from this! 
N/A
=> Track new pages with HotJar

cache/locals.tf
Applies changes from https://github.com/wellcomecollection/wellcomecollection.org/pull/11308 and https://github.com/wellcomecollection/wellcomecollection.org/pull/11298 to production after they seem to work nicely in staging. 
Relates to #11300 
Can't really test until deployed and applied, but you could confirm these are the latest versions.
N/A
N/A
=> Apply new lambda versions for redirects

cache/edge_lambdas/src/redirects.ts, cache/locals.tf
> [!Note]
> This change has been applied!
This pull request includes a few small changes to correct a typo in a redirect URL and update version numbers for edge lambda requests and responses.
Follows:
- https://github.com/wellcomecollection/wellcomecollection.org/pull/11308
- https://github.com/wellcomecollection/wellcomecollection.org/pull/11311
Changes to redirect URLs:
* [`cache/edge_lambdas/src/redirects.ts`](diffhunk://#diff-e6fb2203ddad8ffdd26f180815ff76fae4d709a2a769c18a61039917a71f5d10L86-R86): Corrected the URL for the `/opening-times` redirect to `/pages/opening-times`.
Updates to version numbers:
* [`cache/locals.tf`](diffhunk://#diff-c1ecd0afc8282ce31d400736b1fb4e73d832eafa42261b35630fe3687636369dL6-R7): Updated `edge_lambda_request_version` to 137 and …
=> Fix broken /opening-times redirection

content/webapp/components/SearchResults/SearchResults.tsx
#11249 
As explained in the ticket, there was a lot of repetition, making the file bigger than it needs to be.
The goal here is to not lose _readability_, so if you think that's the case, please do flag.
Run locally and look at documents containing `ContentList` and `SearchResults`.
Increased readability.
N/A
=> Refactor SearchResult component

updown/types.ts, updown/updown-checks.ts, updown/updown.ts
We changed the names of Slack channels a while back, but our Updown integration was still considering "digital-platform" to be what is now "digital-general". To ensure the alerts are posted in the correct channel, we've made these changes.
I've already done the bit on the Updown dashboard itself that should ensure the integration works well.
Unsure tbh, we'll see if we get alerts at some point?
Warned in the correct channel should anything be going haywire.
N/A
=> Point updown to new general channel

content/webapp/pages/pages/[pageId].tsx, content/webapp/services/prismic/fetch/index.ts, content/webapp/services/prismic/fetch/pages.ts
#11072 
The current solution for `/pages/` redirections involves fetching the document before redirecting the user, which means having to fetch the same document twice. We thought we could add a `getBasicDocument` fetch which only returns what is needed to do that (in our case, `id`, `uid` and `tags`). `id` and `tags` are default fields and always get returned, so my graphql request only asks for `uid`. 
The only think I don't like is that it complexifies `getByUid` so I'd love your thoughts.
Run locally, does it work well?
Smaller, lighter queries
N/A
=> (3) Suggestion for basic page fetch

content/webapp/components/IIIFClickthrough/IIIFClickthrough.tsx, content/webapp/components/IIIFViewer/MainViewer.tsx, content/webapp/components/ItemViewerContext/ItemViewerContext.tsx, content/webapp/components/WorkDetails/WorkDetails.AvailableOnline.tsx, content/webapp/hooks/useShowClickthrough.ts, content/webapp/pages/works/[workId]/items.tsx, content/webapp/utils/iiif/v3/index.ts
Makes restricted items viewable on the item page for users with a role of 'StaffWithRestricted'. For [#5761](https://github.com/wellcomecollection/platform/issues/5761)
_N.B. It does not deal with born digital things, which we list on the works page. - this needs further consideration._
The [IIIF Authorization Flow API 2.0 docs](https://iiif.io/api/auth/2.0) describe [three interaction patterns ](https://iiif.io/api/auth/2.0/#33-interaction-patterns) external, kiosk and active. Kiosk is not relevant to us. Active is what we currently use for the clickthrough, but could be used to offer a login. External is the profile used for restricted items.
We use external for restricted items because we don't want to present most users with a login when they either don't have an account, or if they …
=> Display restricted to staff

content/webapp/components/IIIFViewer/ViewerSidebar.tsx, content/webapp/components/WorkDetails/WorkDetails.AvailableOnline.tsx
For [#11304](https://github.com/wellcomecollection/wellcomecollection.org/issues/11304)
Log in with a user that has a role of 'StaffWithRestricted'
Visit http://localhost:3000/works/a24nhdcv and see the following message:
Visit http://localhost:3000/works/a24nhdcv/items and see the following message:
Limited as it only affects a limited number of users.
It is possible that if the user has already visited an item with v2 external services and authorized, then they will be able to see the images, but still receive this message. We could try and address this, but felt it was not a great use of time given the limited impact of the issue and the fact it will resolve once all iiif manifests have been regenerated.
=> display different message to user if only have v1 external service

common/services/prismic/index.ts, content/webapp/__mocks__/whats-on.ts, content/webapp/pages/index.tsx, content/webapp/pages/visual-stories/[visualStoryId].tsx, content/webapp/pages/whats-on/index.tsx, playwright/test/helpers/contexts.ts
#11292 
We had various checks to make as we got further in the ID->UID and URL structure changes, so this covers them. 
- A few "Edit in Prismic" links (API Toolbar) had to be amended to use the document's ID and not its UID.
- I'd noted Visual Story pages didn't have that link so I added it in-
- Amended comment for `looksLikePrismicId`. We're happy to consider `Id` as referring to either Prismic ID OR UIDs as they are both identifiers. If we want to change that in the future, we can address it then.
- Amended a few playwright repo-links so they'd follow their new URL structure. Redirects are in place, ensuring these links still work, but good to have their newest version in our code.
Run locally, test "Edit in Prismic links'.
Tidier codebase not living in the past ✨ 
N/A
=> Fixing various lines of code that referred to ID instead of UID

content/webapp/components/IIIFViewer/ViewerSidebar.tsx, content/webapp/components/WorkDetails/WorkDetails.AvailableOnline.tsx
For #11301: updates the text
View a [works](http://localhost:3000/works/jjdp9v65) and [items](http://localhost:3000/works/jjdp9v65/items) page for a restricted work while logged in with a user with a role of 'StaffWithRestricted'
See the following text:
The message displays
None really
=> text change

common/model/site-section.ts, common/services/prismic/link-resolver.ts, common/views/components/Header/Header.tsx, common/views/components/PageLayout/PageLayout.tsx, content/webapp/components/SearchPageLayout/SearchPageLayout.tsx, content/webapp/pages/guides/[guideId].tsx, content/webapp/pages/pages/[pageId].tsx, content/webapp/services/prismic/fetch/index.ts, content/webapp/services/prismic/fetch/pages.ts, content/webapp/services/prismic/transformers/guides.ts, content/webapp/services/prismic/transformers/pages.ts, content/webapp/services/prismic/transformers/projects.ts, content/webapp/services/prismic/transformers/visual-stories.ts, content/webapp/types/card.ts, content/webapp/types/guides.ts, content/webapp/types/pages.ts, content/webapp/types/projects.ts, content/webapp/types/visual-stories.ts
#11346 
Moves `siteSection` types and type guard into `model` folder.
Amend `linkResolver` to account for untransformed data (which was causing the link to be wrong).
I don't fully grasp why I couldn't import `isSiteSection` from `PageLayout` (build was breaking). I know it had to do with the code not being able to compile properly. I moved it into `model` as anyway it seems to be where we keep types.
Run locally and preview a Prismic `Page` locally, see if the URL makes sense and you can actually preview it.
No more broken previewing of Pages!
N/A
=> Fix Page preview link

content/webapp/services/prismic/fetch/index.ts, content/webapp/services/prismic/fetch/pages.ts
If `getByUid` (for `getBasicDocument`) returns undefined, try `getById` with the same `graphQuery`. 
This causes pages like `pages/YDaP2BMAACUAT7DS` to not redirect to `[siteSection]/[uid]` and therefore renders them as 404, breaking many bookmarked pages.
Run locally
Can you access the database page through http://localhost:3000/pages/YDaP2BMAACUAT7DS ?
Can you still render other pages by ID without any issues caused by the changes to `getById`? (e.g. http://localhost:3000/stories/XuNqyRIAACIArun9)
Any other scenario you can think of
Fixes many many broken bookmarked pages or pages that are linked to from their ID based URL.
Breaks something else?
=> If `getByUid` can't return a basic document, try `getById`

common/views/slices/CollectionVenue/index.tsx
[When we created `ContaineredLayout` and amended the imports to reference the correct one](https://github.com/wellcomecollection/wellcomecollection.org/pull/11267) (`ContaineredLayout` vs the default `Layout`), we didn't do it properly in this file. So it was rendering with `Layout` as it's the default.
[Related Slack convo](https://wellcome.slack.com/archives/CUA669WHH/p1729852658133759)
http://localhost:3000/visit-us/opening-times
http://localhost:3000/visit-us/the-library
Looking gooood.
N/A
=> Import correct `ContaineredLayout` for `CollectionVenue`

cardigan/package.json, yarn.lock
Upgrade `faker` to latest version. Migration guide didn't indicate anything we had to change (we use it quite minimally and weren't using deprecated functions).
Is Cardigan flagging any changes? If not, we're good.
(Update: It did flag changes but just because it's using different random things, which tends to happen when we update the package. They are still working perfectly: https://www.chromatic.com/build?appId=62f13cdbd0ff140768a8d87b&number=6803)
Package upgrade yay
N/A
=> Upgrade `faker` to v9

.github/dependabot.yml
The `koa*` packages are a proper puzzle, see "package upgrade" ticket for more info: https://github.com/wellcomecollection/wellcomecollection.org/issues/11366
N/A
The grouped updates PR Dependabot creates only has easy upgrades in it until we've figured out the more complex ones.
N/A
=> Add `koa*` packages to dependabot ignore list

cache/edge_lambdas/src/redirects.ts
#11181 
Redirects Healing Pavilion exhibition guide to the new formats.
Once we redirect id -> uid, it will probably be ok to remove it as they have the same UIDs? To see then.
Once this gets merged, I'll do the required changes in Prismic.
Run Prismic staging and check out the new guides (I've made them the official ones in staging). Compare the content with prod and see if it checks out. 
One less unsupported document!
Pretty low risk as the exhibition isn't on anymore.
=> Redirect healing pavilion guides

cache/locals.tf
Applies these changes 
[Fix code scanning alert no. 2: Incomplete URL substring sanitization](https://github.com/wellcomecollection/wellcomecollection.org/pull/11337)
[Redirect healing pavilion guides](https://github.com/wellcomecollection/wellcomecollection.org/pull/11365)
N/A
Up to date
Has been tested in staging and looks good, so I'd say low.
=> Lambdas `137`->`139` (resp) and `139`->`141` (req)

content/webapp/pages/about-us/cookie-policy.tsx
https://wellcomecollection.org/about-us/cookie-policy currently does not render the cookies tables.
This is because it's not actually rendering where it should as, in the codebase, that page was considered an orphan (`/pages/cookie-policy.tsx`). It had to be moved to the correct route to use the "special" file we'd created for it in the codebase, in the meantime is was rendering as a normal page (using the code from `/pages/about-us/[uid].tsx`). It's why the Text slices were exposed as is, instead of being replaced with the cookie tables.
Run locally
http://localhost:3000/about-us/cookie-policy with cookie tables
http://localhost:3000/cookie-policy should 404
We're doing the right thing legally and showing people what cookies we're using etc.
N/A
=> Move cookie policy page to its siteSection - about us

prismic-model/lintPrismicData.ts
A Prismic linting flag came up this morning and I noticed a missing part of the error message
So I went in and added the slice title, you can see here as I mocked the script
You could run `lintPrismicData` locally and mock failing content, but this is pretty low risk and impact and doesn't warrant the effort that much?
Clarity over which video/audio duration to amend.
N/A
=> Prismic linter: Add missing title to linting for guides

content/webapp/components/IIIFViewer/IIIFCanvasThumbnail.tsx, content/webapp/components/IIIFViewer/MainViewer.tsx
Users with a role of 'StaffWithRestricted' were still seeing a padlock icon instead of the thumbnails:
This displays a thumbnail image to them instead.
- uses the role in the conditional that determines whether to show the padlock or the thumbnail image
- falls back to the image service to provide a thumbnail image if there is no thumbnail service
- login in a user that has the role of 'StaffWithRestricted'
- visit a page with restricted items localhost:3000/works/k2jjvqk2/items
- click on the thumbnails control and see thumbnail images
users with a role of 'StaffWithRestricted' can see thumbnail images for restricted items
Limited. It only affects a small number of users and currently doesn't work
=> Restricted thumbnails

common/package.json, yarn.lock
⬆️ 
Running `yarn slicemachine` still works
We're on the latest version of slice machine
Limited, we only run this locally and I've tested using slice machine to update types on Prismic stage and it works.
=> update slice machine

playwright/test/concept.test.ts
Change one of the end-to-end tests to use a different concept ID. The old concept ID is no longer in use (i.e. it's no longer referenced from any Works) and has been completely removed in a recent concepts pipeline reindex.
There is no need to test this change outside of our automated testing process. 
End-to-end tests no longer fail with the new concepts index. 
There should be no risks associated with this change.
=> Update concept ID in end to end test #5804

playwright/test/pages.test.ts
https://github.com/wellcomecollection/wellcomecollection.org/issues/11375
Checks if the three tables are accounted for, see ticket for more information.
Are the tests passing in this PR?
No more losing them!
N/A
=> Add a test that checks if the cookie policy is displaying 3 tables

.github/dependabot.yml, common/koa-middleware/withCachedValues.ts, content/webapp/app.ts, content/webapp/package.json, identity/webapp/package.json, package.json, yarn.lock
For https://github.com/wellcomecollection/wellcomecollection.org/issues/11366
- uses @koa/router instead of koa-router (now consistent between identity and content apps)
- updates @koa/router (all other koa packages are using the latest versions)
- fixes breaking change
- removes the types for koa-router
- stops dependabot from ignoring koa packages
yarn all the things
rm -rf node_modules && yarn
Try building/running the following locally:
content
identity
Everything still works
Low if everything is working and tests are passing
=> Upgrade koa

content/webapp/types/body.ts
For #11052 
We check for the type of the first thing in the SliceZone, and if it's an `editorialImage` we want to pull it out and display it as `featuredMedia` before anything else on the page. Previously, we transformed the data we got from Prismic, and gave editorial images a type of `picture`, but now we deal directly with the untransformed data, and the type we get from Prismic is `editorialImage`, so we need to test for that instead.
__After__
Go to `/visit-us/Wuw19yIAAK1Z3Smk` locally and confirm the image appears before the `OnThisPageAnchors`
Pages appear as they were designed
=> Check for slice_type 'editorialImage' not (transformed) 'picture'

content/webapp/pages/stories/[articleId].tsx
⬆️ 
Visit a story and see no hotjar script loaded to the page
hotjar isn't loaded on stories pages
n/a
=> remove hotjar from stories

content/webapp/pages/pages/[pageId].tsx
In trying to fix #11050 I went to the [wayback machine](https://web.archive.org/web/20230701001859/https://wellcomecollection.org/pages/YDaZmxMAACIAT9u8) when I saw the featured text would look strange. I spotted that we used to treat 'Visit us', 'Collections', and 'Get involved' as `sectionLevelPages` and changed the appearance of their header accordingly. The test for this used `id`s which are no longer correct – changing it to `uid` gets us back to where we were.
__Before__
__After__
Without this change, if/when #11050 is fixed, the `featuredText` position will look wrong
visit `/get-involved`, `/collections`, and `/visit-us` and confirm the header appears as it used to.
Pages appear as originally designed
=> Use uid instead of id to check if we're on a 'sectionLevelPage'

common/customtypes/pages/index.json, common/prismicio-types.d.ts, content/webapp/components/Body/Body.tsx, content/webapp/pages/pages/[pageId].tsx, content/webapp/services/prismic/transformers/pages.test.ts, content/webapp/services/prismic/transformers/pages.ts, content/webapp/types/pages.ts
For #11050
The 'featured text' part of a page used to be handled by a `slice_label` of `featured`, but `slice_label`s aren't a thing anymore. This means that the pieces of text that were supposed to have been taken out of the slices and added at the start of the `Body` are currently appearing _after_ the rest of the body content.
Since there can only be _one_ piece of `featuredText` per page, it makes sense for it to be a field on the page model, rather than a piece of text in the slices, so this PR adds a `RichTextField` for 'Featured text'
Using the Prismic stage API, go to `/get-involved` and confirm the para of text ("Get involved with what’s happening…") appears before the cards, rather than after them.
Pages render as they are supposed to
Can't think of any (although content will …
=> Add 'featuredText' to page model (instead of text with a label)

content/webapp/components/Body/Body.tsx
In doing changes for #11050 and #11052 I noticed this long-standing UI weirdness.
Alignment of the `SectionHeader` and the cards below has (apparently) been offset for a long time on the `/get-involved/young-people` page, and it looks bad.
This PR lines up the heading and the content. Doesn't look amazing, but definitely looks better.
__Before__
__After__
Visit `/get-involved/young-people` and see if it looks less bad than in prod.
People don't think our pages look broken
n/a
=> Align SectionHeader with content below

toggles/webapp/toggles.ts
Part of https://github.com/wellcomecollection/platform/issues/5654
Follows https://github.com/wellcomecollection/catalogue-api/pull/830
This change adds a toggle to be used in front-end work to use an implementation of concepts pages and search filters that use concept IDs rather than labels.
Gracefully working on updating concept pages without changing what the public sees.
This change only adds the toggle (which is off by default), so risk should be minimal.
=> Adds toggle for concepts by ID work

cardigan/stories/components/PopupDialog/PopupDialog.stories.tsx, common/customtypes/popup-dialog/index.json, common/prismicio-types.d.ts, common/server-data/prismic.ts, common/services/prismic/documents.ts, common/test/fixtures/prismicData/prismic-data.ts, common/views/components/PageLayout/PageLayout.tsx
Adds the ability to limit where the `PopupDialog` component will appear, by introducing a text field to the model (using the same logic as pre-exists for the Global Alert)
- Locally visit any collections page (i.e. one that starts `/collections`, `/works`, `/search/works`, or `search/images`) and wait five seconds, check the button to launch the dialog appears bottom right of the screen.
- Visit a non-collections page and check the button doesn't appear
We can be more targeted with our user research
=> Add ability to limit where popupDialog appears with regex

common/data/cookies.ts, common/views/components/CivicUK/index.tsx, common/views/components/VideoEmbed/VideoEmbed.tsx, content/webapp/services/prismic/transformers/embeds.ts
#11408 
The `dnt` param (`1` is `true`, `0` is `false`) stands for Do Not Track. We never tracked by default, but now we want to should the user consent.
I moved it to the `VideoEmbed` component which is the only component used to render Vimeos. I did wonder if it should be passed/not in the `getVimeoUrl` helper, but I didn't want to get the consent everywhere that was used in order to pass it in. This feels much more streamlined.
- [This is the list of Vimeo cookies](https://help.vimeo.com/hc/en-us/articles/26080940921361-Vimeo-Player-Cookies). Below the table, they list which cookies are necessary.
- Run locally, allow only necesary cookies. 
- The tracking starts on Play, so find a Vimeo (Hard Graft and Jason' BSL videos) and play it. 
- Ensure only necessary cookies are added.
- …
=> Move `dnt` param for Vimeo to VideoEmbed

cache/modules/cloudfront_policies/cache_policies.tf, cache/modules/cloudfront_policies/locals.tf, cache/modules/cloudfront_policies/request_policies.tf
⬆️ 
For #11391 
Stops varying the cache on ga cookies
Can't think of a straightforward way.
Hopefully see an improvement in apdex scores
n/a
=> remove ga_cookies from cloudfront policies

content/webapp/pages/concepts/[conceptId].tsx, playwright/test/concept.test.ts
For https://github.com/wellcomecollection/platform/issues/5834
This change brings concept pages by ID out from behind a toggle, but keeps links back to works search as label based, removing the possibility of a link give the incorrect number of results, or return you to an empty search page.
To enable this the "all _thing_" link is removed when a label based search has no results.
See [this conversation](https://wellcome.slack.com/archives/C07PUCL8TR8/p1732800543188889) for more information, and videos of expected behaviour.
- http://localhost:3000/concepts/tprv87tq
Follow "all works" and "all images" links, [compare currently live](https://wellcomecollection.org/concepts/tprv87tq).
_Expected behaviour:_ There will be more works and images on the concept page, the links to works and …
=> Concept pages link to works search by label

common/views/components/RecommendedStories/index.tsx, common/views/slices/Text/index.tsx, content/webapp/components/Body/Body.tsx, content/webapp/pages/stories/[articleId].tsx
#11425
Adds a new component under the fifth paragraph of an article. The logic for this is very basic: As it's meant for a short-lived test, I wouldn't recommend doing more work on this logic to stop it from displaying in awkward looking places - should we want to keep this, we could spend longer thinking about the logic and how it could work. 
It's what I'd consider hacky code; a lot of this we would not want all of this as a stable version.
Currently only using hard-coded content for the recommended list.
[Here's the designs](https://www.figma.com/design/6XYRHJjrRGVveTenps4iWZ/Deepen-engagement-with-stories?node-id=132-3478&node-type=frame&focus-id=131-1182&m=dev)
I know we see the horizontal scrollbar. We also do on `/search`'s story section on mobile, so I assumed it was good to not …
=> Add basic recommended stories container under toggle

cardigan/stories/components/WobblyEdge/WobblyBottom.stories.tsx, cardigan/stories/components/WobblyEdge/WobblyEdge.stories.tsx, common/views/components/RecommendedStories/index.tsx, playwright/test/helpers/contexts.ts
As part of the work for #11425, I found out `WobblyEdge` was pretty customisable but not advertised as such in Cardigan, so adding it!
Slight tweaks on Recommended stories while I'm at it to make them less horrible looking on a huge screen.
Run Cardigan locally, play with it!
Recommended stories are under their named toggle
[I ran the e2es with the added toggle cookie ](https://buildkite.com/wellcomecollection/wc-dot-org-build-plus-test/builds/15320)as well to ensure it wouldn't break them once made public.
Cardigan even more useful to all!
N/A
=> Add `WobblyEdge` to Cardigan, slight tweaks on Recommended stories

common/views/components/RecommendedStories/index.tsx
The classes that styled-components generates doesn't give us anything sensible to hook onto for a tagmanager trigger. We've used a data-attribute for this in the past – `data-gtm-trigger={x}`, so reusing that principle here.
View a story with the recommended stories toggle turned on and verify the `data-gtm-trigger="popular_story"` attribute is added to the containing `li` elements for each recommended story card
We can use tagmanager to measure events
n/a
=> Add data-gtm-trigger for popular_story

content/webapp/pages/collections/[uid].tsx
For [#11440](https://github.com/wellcomecollection/wellcomecollection.org/issues/11440)
looks like 
/concepts*
/works*
and collections landing page already load hotjar.
This adds the hotjar script to the collections sub pages
Visit a collections sub page, e.g. http://localhost:3000/collections/what-s-in-the-collections
Look for the hotjar scrip in the Elements tab of Dev tools
The hotjar script is present
none really, we load this script on pages already
=> Add hotjar to collections sub pages

common/customtypes/articles/index.json, common/prismicio-types.d.ts, playwright/test/mocks/one-schedule-item.ts
#11439 
Adds a document link for stories and exhibitions in the story content type.
I've already pushed it to Prismic staging.
I've following the casing from other such fields for its ID.
Check out prismic staging?
Able to move forward with the rest of the #11439 work
N/A
=> Add explore more document link on stories

common/views/components/ApiToolbar/index.tsx, content/webapp/pages/works/[workId]/images.tsx, content/webapp/utils/works.ts
Adds a subtle link to the new Library Data Link Explorer onto the API toolbar. Avoids colleagues from saving the temporary Amplify link as a bookmark. 
Ensure you have the toolbar enabled on your local. Click the link, it should open in a new tab (to allow colleagues to go back and forth to the catalogue with ease, rather than refreshing their search). 
The application opened should work as normal. 
Is the 🏷️ link too subtle? Does it match the style of the toolbar to avoid clutter? 
Prevents overuse of the application, keeps the toolbar tidy, even when in mini mode.
=> added a Library Data Link Explorer link in the API toolbar

build-speedtracker.sh, content/webapp/pages/api/exhibitions/exhibition.ts, content/webapp/pages/stories/[articleId].tsx, content/webapp/services/prismic/fetch/exhibitions.ts, content/webapp/services/prismic/transformers/articles.ts, content/webapp/services/wellcome/content/article.ts, content/webapp/services/wellcome/content/index.ts, content/webapp/types/articles.ts
#11439 #11429 #11428 
- [Deletes an unused script](https://wellcome.slack.com/archives/C3TQSF63C/p1734087650881209?thread_ts=1734087512.439279&cid=C3TQSF63C) (unrelated to ticket work)
- Adds API endpoint to fetch single exhibition (from Prismic API) or single article (Content API) client-side
- Adds `exploreMoreDocument` field to Articles' type and transformer, returning only the required information for a client-side fetch of the document. This had to be done because we couldn't get the required shape only from the content relationship field ([see Slack conversation here](https://wellcome.slack.com/archives/CUA669WHH/p1734452938489909)), and we didn't want to load even more things Server side.
- Add the code to render the Featured Card on articles pages should the field have a value in. …
=> Featured card stories

common/views/slices/Text/index.tsx, content/webapp/components/Body/Body.tsx
#11482 
Renamed the component to be shameeeedd because we don't want it to be there forever and it should be clear. Added comment to explain.
Changed references to fifth paragraph to fifteenth.
Run locally, explore a few stories.
These have less than 15th, and therefore should not display the block: 
- http://localhost:3000/stories/mistakes-and-perfect-medicine
- http://localhost:3000/stories/does-mass-media-pave-the-way-to-fascism-
We get better numbers for interaction
Probably pretty low risk, we're not changing much from what we already made available.
=> Move Recommended stories to after 15th paragraph

content/webapp/pages/search/index.tsx, content/webapp/services/wellcome/catalogue/types/aggregations.ts, content/webapp/services/wellcome/catalogue/types/index.ts, content/webapp/services/wellcome/content/all.ts, content/webapp/services/wellcome/content/articles.ts, content/webapp/services/wellcome/content/events.ts, content/webapp/services/wellcome/content/index.ts, content/webapp/services/wellcome/content/types/api.ts, content/webapp/services/wellcome/index.ts
#11487 
I've aimed to make the commits clear and separate if you'd like to follow along on there instead.
- Adds an "all" endpoint
- Because this is the first endpoint without filters/aggregations, I had to change some types. I think `aggregations`'s type was `null` because the Catalogue API uses `null`? But we use `undefined`? Anyway, TS was unhappy, and this seems to do the job, but I'd love to discuss if we think this could cause problems.
- I've created a very basic/awful-looking results page under the toggle. I've merged "works and images" in one as the "catalogue query". I've ensured that "events/stories" queries weren't being done if the toggle was active, and that the "all" query wouldn't happen if no toggle was detected, to save on the amount of queries.
Run locally with and …
=> Add "all" api endpoint and create alternative page

common/views/components/PageHeader/HighlightedHeading.tsx
For #11400 
Adds the (now standard) `box-decoration-break` property to target Chrome, Edge, and Firefox where previously we only had the (`--webkit`) vendor-prefixed version which worked for Safari and Chrome.
visit `/about-us` in Firefox and see the white background only covers the words.
The purpose of `box-decoration-break: clone` is to pad the second and subsequent lines of text with the white background.
__without__
__with__
Site looks similar in more browsers
n/a
=> Use box-decoration-break

content/webapp/pages/concepts/[conceptId].tsx, content/webapp/utils/concepts.ts
Query for contributor and subject concepts by ID only on concept pages introduced in https://github.com/wellcomecollection/catalogue-api/pull/832, this change attempts to accommodate the API change at the moment that impacts concept pages.
We are able to push the catalogue-api change in main to prod without any unexpected behavior in the frontend.
>[!Note]
> This change needs to go out **before promoting stage to prod**!
This is slightly risky is it relies on edge-case behaviour of the catalogue api to discard unexpected params, we should be protected by e2e tests and other steps in the build pipeline.
=> Concepts query by ID only

content/webapp/components/Accordion/Accordion.tsx
Ensures screenreaders correctly announce whether the accordion drawer is 'expanded' or 'collapsed'.
View the component in Cardigan, launch VoiceOver, tab to an item, check it announces 'collapsed', press enter/space to open the item, check it announces 'expanded'.
Screenreader users get a consistent experience.
We're not screenreader users ourselves, so in the next accessibility audit this would be a good component to single out for testing.
=> Don't announce 'hide/show' in favour or 'collapsed/expanded'

content/webapp/utils/concepts.ts, toggles/webapp/toggles.ts
> [!Note]
> We should merge this on or after 2024-01-20
Follows: https://github.com/wellcomecollection/wellcomecollection.org/pull/11505
This change implements a couple of small clean-ups to the concepts work.
- Remove the double filter names following the release of: https://github.com/wellcomecollection/platform/issues/5838
- Update the concepts toggle title and description to better match what's being tested
Happier developers because unused or incorrect code isn't hanging around to confuse people.
This should not change any user facing content. We are keeping the old pipeline around until Monday, 2024-01-20 in case we need to revert, so a good idea to wait until that's deleted to ensure we don't need to roll this back.
=> Concepts filters & toggle clean-up

common/customtypes/series/index.json, common/prismicio-types.d.ts
For #11488 prep; we'll want this field to exist specifically for Body Squabbles when we move it from a webcomic series to a series. 
It should match what we have in "articles". The label is different as Prismic no longer allows for more than 35 characters.
Able to migrate content seamlessly.
N/A not much danger in adding a field
=> Add override publishDate field in series

content/webapp/components/IIIFItem/IIIFItem.tsx, content/webapp/components/IIIFViewer/IIIFViewer.tsx, content/webapp/components/IIIFViewer/IIIFViewerImage.tsx, content/webapp/components/IIIFViewer/ImageViewer.tsx, content/webapp/components/IIIFViewer/MainViewer.tsx, content/webapp/components/IIIFViewer/ViewerTopBar.tsx, content/webapp/components/VideoPlayer/VideoPlayer.tsx, content/webapp/pages/works/[workId]/items.tsx, content/webapp/utils/iiif/v3/index.ts
Makes it possible for the /items page to display video, audio and pdfs in the viewer, as well as images.
This work is currently behind a toggle (toggle_extendedViewer), as there are some issues with displaying these new things that need ironing out.
Run with the toggle turned off and the following should behave exactly as they do on production:
Digitised book: [localhost:3000/works/jm4kaz67/items](localhost:3000/works/jm4kaz67/items)
please check image alt text, search (search highlighting), rotation and zoom controls, downloads (downloads selected image)
Pdf ingested pre born digital: [localhost:3000/works/yycbn2r4/items](localhost:3000/works/yycbn2r4/items)
Digitised video: [localhost:3000/works/sx4p4b75/items](localhost:3000/works/sx4p4b75/items)
Digitised audio: …
=> Item viewer all the things

content/webapp/components/IIIFViewer/MainViewer.tsx
For #11513
It only makes sense to show the rotation and zoom controls for items that have an image service. They shouldn't show when display the audio/video players or pdfs.
Make sure the extendedViewer toggle is turned on
Visit http://localhost:3000/works/enye955g/items
The controls for rotation and zoom should appear when each canvas is scrolled to
Visit:
http://localhost:3000/works/yycbn2r4/items (pdf)
http://localhost:3000/works/tp9njewm/items (audio)
http://localhost:3000/works/qvgcmea3/items (born digital)
http://localhost:3000/works/fhy2fv5k/items (video)
The controls for rotation and zoom should **not** appear
Redundant controls aren't displayed
The controls don't show when they should.
=> Only show controls for things with an image service

cache/cloudfront_rss.tf, cache/modules/wc_org_cloudfront/distribution.tf, cache/modules/wc_org_cloudfront/waf.tf, cache/terraform.tf
For https://github.com/wellcomecollection/platform/issues/5884
This change adds a WAF rule that rate limits requests from clients that contain either "PetalBot" or "ClaudeBot" in their user-agent strings. We've seen this block enough traffic to be useful and reduce errors from bot load.
Less outages, happier users.
This could block potential requests from users who are taking advantage of LLMs to query the site, we mitigate this risk by applying a rate limit rather than a blanket block.
=> Update WAF rules to block bots with matching user-agents

common/README.md
For #11500 
Adds a bullet to the README linking to Gitbook
Read it?
Developers find the information about casing IDs they've been looking for
n/a
=> Add note on casing to README

content/webapp/components/IIIFItemList/IIIFItemList.tsx, content/webapp/components/IIIFViewer/MainViewer.tsx, content/webapp/utils/iiif/v3/canvas.ts
#11512 
Use function that already existed that checks if there is a PDF in a canvas, in order to display it for Born Digital items too.
I made that function a separate helper as to not duplicate it and have the context in one place.
I also simplified what gets displayed, but it might be due to a lack of understanding of what COULD display, so please question it/let me know if it doesn't work like that. I couldn't find an example where it broke.
This work isn't done explicitly behind the toggle as it works already without the toggle, now it'll just work for both. 
With extended viewer toggle;
PDFs are viewable no matter their format!
Breaks some works that I'm not aware of.
=> Born digital PDFs to display in viewer

.github/dependabot.yml, identity/webapp/config.js, identity/webapp/package.json, prismic-model/package.json, yarn.lock
[Had a look at packages to upgrade](https://github.com/wellcomecollection/wellcomecollection.org/pull/11529) and noticed we were way behind on dotenv, so went for that. It seemed a simple enough change, [not a lot of breaking changes](https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md) and just simplified the code [as per their instructions](https://github.com/motdotla/dotenv). Ran identity locally and all seems good.
I also added an ignore for Babel packages while I was at it because I'm creating [a separate ticket](https://github.com/wellcomecollection/wellcomecollection.org/issues/11530) for it, and Husky already has one indicated it wasn't straightforward.
Run identity locally, it should still work as normal.
Up to date ✨ 
If it runs well, we'll check again in staging.
=> Upgrade `dotenv` in `identity` and ignore a few packages in dependabot

common/README.md, content/webapp/package.json, identity/webapp/package.json
Just found a pretty weighty folder in the dash s3 bucket, and turns out [it's not something we use anymore](https://wellcome.slack.com/archives/CUA669WHH/p1738146586058779). 
I'm removing the command lines which hadn't been used since 2023 anyway, and adding a section in the common README for instructions if anyone is interested in running it locally.
The folder on s3 has been deleted manually, now only at 161mb.
Try to run the script locally, see if the README is satisfying
Tidier 🤷‍♀️ ✨ 
N/A not been used in ages.
=> Remove `deployBundleAnalysis` script, add README section on how to run locally

common/data/segment-values.ts, common/utils/search.ts, content/webapp/components/ImageCard/ImageCard.tsx, content/webapp/pages/search/index.tsx
For https://github.com/wellcomecollection/wellcomecollection.org/issues/11459
This PR:
- fetches the aggregations for the works and uses them to create the correct links for the catalogue results section
- converts the images results so we can use them with ImageCard and create the necessary links for the image results section
Next comes styling
Visit /search with the all allSearch toggle enabled
The data/functionality of the catalogue and images sections of the all search is available
Behind a toggle so they're limited
=> All search works

common/prismicio-types.d.ts, common/views/slices/GuideTextItem/index.tsx, common/views/slices/GuideTextItem/mocks.json, common/views/slices/GuideTextItem/model.json, content/webapp/components/GuideTextItem/GuideTextItem.tsx, content/webapp/services/prismic/transformers/exhibition-texts.ts
#11522
Adds a transcript field to "Guide text item" slice.
Displays it on the FE inside a CollapsibleContent component.
I added one in Kola Nut (first instance of guide text) on staging, so you could run staging locally and see it there.
A feature we lost is back ✨ 
N/A?
=> Add transcript field to Exhibition Text

common/views/slices/index.ts
I feel like this used to error when we removed it, but I couldn't replicate - let's get rid of it fully?
What scenario haven't I tested?
=> Remove quotev2 from slice list

cardigan/stories/components/ContentSearchResult/ContentSearchResult.stories.tsx, common/services/prismic/content-types.ts, common/services/prismic/link-resolver.ts, content/webapp/components/ContentSearchResult/ContentSearchResult.tsx, content/webapp/pages/search/index.tsx, content/webapp/services/wellcome/content/types/api.ts
Part of #11460 
Adds a `ContentSearchResult` component and uses it behind the `allSearch` toggle on the new search page
Turn on the toggle, search for something, check the linkResolver takes you to where it should for each of the possible content types.
I used the existing Pagination component (if/when we update to match the designs, I think that could be a larger piece of work to make that change everywhere we do pagination).
Catalogue results are being dealt with separately. I also backed out of tackling the styling of the search box and adding then number of hits per section as part of this PR. It would require several more requests and maybe needs more discussion before it gets built
We can serve site-search information to users rather than them having to Ask Jeeves
Things link to the …
=> All search

common/services/prismic/link-resolver.ts
[Flagged as a bug by Grace on Slack](https://wellcome.slack.com/archives/C3N7J05TK/p1738237445998549?thread_ts=1738228074.651889&cid=C3N7J05TK)
This I think is due to a change we made for the search links to work as expected.
As that's still behind a toggle, I'm just reverting the change to the link on the exhibition guides page gets back to normal/working. 
We can address the fix for the search component at a later point: [#11549](https://github.com/wellcomecollection/wellcomecollection.org/issues/11549)
UPDATE: To address [other problems that were found](https://github.com/wellcomecollection/wellcomecollection.org/pull/11548#issuecomment-2624321268), all changes to the link resolvers from the [search work](https://github.com/wellcomecollection/wellcomecollection.org/pull/11534/files) …
=> Revert change to link-resolver 

cache/modules/wc_org_cloudfront/waf.tf
This change codifies some new AWS WAF rules that codify new geo rate limits from requests originating in Brazil after seeing significant suspected bot traffic.
The rate limit blocks requests originating from Brazil if they exceed 500 requests per minute.
This change has been deployed in production for the last week to test impact in traffic.
See WAF results:
See GA active users for the same period:
We see no drop in reported active users although there is significant requests counted as blocked. This indicates sucessful reduction in bot traffic without impacting active users.
Reduced load, no outages.
As the bot traffic does not advertise itself as such and attempts to use advanced WAF features to match this traffic have failed there is a risk we are degrading the experience for real …
=> Codify new geo rate limits

prismic-model/sliceAnalysis.ts
Realised the script didn't account for when slices were not within something called "Body". Guides' model is a bit different and they weren't getting caught; is that something we'd be happy to amend so it matches the rest? (@gestchild @davidpmccormick )
Before
After
Run it locally
Data is valid again
N/A but should we make sure models are aligned?
=> Amend `sliceAnalysis` script to account for guides' model

common/package.json, common/views/components/Buttons/Buttons.Dropdown.tsx, common/views/components/Header/Header.tsx, common/views/components/Modal/Modal.tsx, yarn.lock
Went for a quite simple update, I don't think the changes affected us much https://github.com/focus-trap/focus-trap-react/releases/tag/v11.0.0
Run locally, test with a modal box that the focus stays within.
Up to date 🤷 
N/A
=> Upgrade focus-trap-react

content/webapp/components/IIIFViewer/MainViewer.tsx
#11521 
I just changed what we passed to `itemSize`, using the viewerHeight instead of its width. We believe the width is used because it makes images much more readable; but we can use the height for audio/video to align them centrally.
I left comments in the code for more info.
Try various types and see they still look good
- Multi audio http://localhost:3000/works/dmpcsthv/items
- Book http://localhost:3000/works/a2239muq/items
- PDF http://localhost:3000/works/pmv8cncs/items
- Mixed born digital http://localhost:3000/works/dn9jwck6/items
Audio looks better!
N/A?
=> ItemViewer; Change height of item based on type

scripts/configure-local-apis.sh
Update docs in run local APIs script to use a command that is happy if you haven't started nginx yet:
`(nginx -s stop || true) && nginx`
Can you run it without error?
Less confused developers.
This is a docs change only, risks should be minimal.
=> Tweak docs for running locally

content/webapp/pages/search/index.tsx
Makes some tweaks following a conversation with Dana
- always show the catalogue results box with a loading icon until the results arrive:
- limit the works links to first 6
- rather than loading another javascript library just to align the images, they are now smaller and we'll evaluate how this works first.
- replaced useSkipInitialEffect with useEffect as there were instances when the results weren't appearing
Vist http://localhost:3000/search with the allSearch toggle enabled
We're happy with how the results look/behave
Still behind a toggle for evaluation, so none really
=> All search tweaks

content/webapp/components/Tabs/Tabs.Switch.tsx
For #10437
Checks if you have JS and adds the `tablist` and `tab` roles to the Tabs.Switch component if you do.
Visit `/whats-on` locally with and without JS. Inspect the Months and check for the presence/absence of the above attributes.
The site is accessible in more circumstances
=> Conditionally add tablist/tab roles if there's JS

content/webapp/components/ImageGallery/ImageGallery.styles.tsx
For #11150 
The close cross in the image gallery has `padding-right` which, on smaller screens, could lead to a horizontal scrollbar appearing when the galleries were opened. Replacing the `padding-right` with a larger `margin-right` prevents this from happening.
Unrelated to the horizontal scrollbar, I spotted that we'd originally intended this close button to be `position: sticky`, but since we added `overflow: auto` to the `ContentPage__Wrapper` more than two years ago, this wouldn't have worked. I don't think anyone noticed or cared, so I haven't tried to fix it in this PR and have removed the sticky classes instead.
Go to http://localhost:3000/exhibitions/ZZP8BxAAALeD00jo, open the image gallery, scroll to the bottom of the page and check that a horizontal scrollbar doesn't appear …
=> Prevent horizontal scrollbar appearing

common/data/microcopy.tsx, common/views/components/Header/Header.tsx, common/views/components/SearchForm/SearchForm.tsx, content/webapp/components/SearchPageLayout/SearchNavigation.tsx
For #11546 
Changes the 'Search our stories, images, catalogue and events' label above the search bar on the `/search` (All search) page, to 'Search for anything'
[Search for anything](http://localhost:3000/search?query=anything)
Labels are simpler and more consistent
n/a
=> Change microcopy for overview to 'Search for anything'

content/webapp/components/ContentPage/ContentPage.tsx, content/webapp/components/ImageGallery/ImageGallery.styles.tsx
Makes the close button stick to the top of the image gallery when the user scrolls, as it was originally designed. This behaviour stopped working c. 2 years ago when we added a `overflow: auto;` property to the `ContentPage__Wrapper` (a measure put in place to prevent margin collapsing causing white spaces at the bottom of the articles pages) and we apparently never noticed that this broke the stickiness of the button.
There's now a [well-supported `display: flow-root` property](https://caniuse.com/?search=flow-root) which was seemingly created to reduce the need for hacks (like `overflow: auto`). Some information about it on [CSS Tricks here](https://css-tricks.com/display-flow-root/). And it doesn't stop sticky elements from sticking.
Visit a [page with an image …
=> Sticky image gallery close button

content/webapp/components/SearchPageLayout/SearchNavigation.tsx
For #11575
Adds a full-width border below the tabs if the `allSearch` toggle is turned on. The `Tabs` component does have a `hideBorder` prop which if `false` puts a border under the tabs, but since we want the border to span the whole width of the page it made more sense to hide the border on the tabs themselves and add it to a wrapping element.
- With the `allSearch` toggle on: [Search for something](http://localhost:3000/search?query=something). Click on the search tabs and verify the border is there for each.
- With the `allSearch` toggle off: check that 1. the All tab doesn't have a border, and 2. the other tabs only display the border the width of the Tabs component itself.
n/a
n/a
=> Add border under tabs component

content/webapp/services/wellcome/common/filters.ts
#11467 
Displays interpretation/access filters in `/search/events`.
The work had already been done content API side when we first released events, as well as all of it in this repo. We'd commented out the lines modified here to hide it because of the duplicates issue that's since been addressed.
So this is quite simple in the end!
There are currently no e2e tests for the events search. Is that something we'd like to put in? All the search tests feel a bit repetitive, so I'm not sure and I'd love opinions on that. @gestchild @davidpmccormick 
Run locally, filter out various mixes of filters and see if it behaves as expected.
A new filter to filter with!
Don't think there are any?
=> Display access filter in events search

content/webapp/pages/search/index.tsx
When a query changes on the all search page, the catalogue results update with a slight delay compared to the content results (because the catalogue results are requested client side).
This PR clears the catalogue results when a new query is made, so that the loading icon appears before the new results arrive.
See [conversation in Slack](https://wellcome.slack.com/archives/CUA669WHH/p1738923916074529)
- Run the site with the allSearch toggle enabled.
- Search for something
- Search for something else and see the loading icon appear in the catalogue section before the new results arrive.
The page doesn't ever display results for different searches across the content and catalogue sections.
None really
=> Show loading indicator when query changes

content/webapp/components/ImageGallery/ImageGallery.styles.tsx, content/webapp/components/ImageGallery/index.tsx
For #11580 
Gives focus to the image gallery close button when the gallery is opened
Open an image gallery then press return – the gallery should close. If you open the gallery using the keyboard the close button should also have visible focus.
Nicer user experience (back to how it was originally implemented).
n/a
=> Allow ImageGallery close button to gain focus

.buildkite/pipeline.yml, docker-compose.yml
Stops `dash` from deploying on _every merge_. It's just about the dash's UI, not its reports. It pushes a new folder in S3 every time (`_next/static/[random folder name]`) and although they are small, it seems unnecessary and a bit much.
[We'd discussed this in Slack already](https://wellcome.slack.com/archives/CUA669WHH/p1727700670906309), and the main "con" was that dependencies should be deployed more often than we now would (only deploying dash manually when it has changes), but my feel is that 1) it's a tool we use, so it breaking only affects us and not that much 2) Dependabot now flags when upgrades are required so it wouldn't get ignored.
But very happy to hear more cons/ideas!
Also; did I miss anything?
We'll see when we merge?
Did I miss anything else that should've been …
=> Stop deploying dash on merges to main

content/webapp/services/wellcome/index.ts
Remove a log line, useful in development but this gets called quite a lot in production and isn't very useful!
See: https://logging.wellcomecollection.org/app/r/s/Y4Olw
Does this line stop getting logged?
Less noise in logs.
Risks should be minimal, this removes a log event only.
=> Do not log api config

content/webapp/pages/search/index.tsx
For #11463 
Hides the catalogue/image sections when there are no results.
- Search for 'asd' and verify there is no mention of image results (the diving line that previously separated image/works results should be gone too)
- Search for 'relaxed openings hard graft' and verify there is no box at all for works/image results
n/a
n/a
=> Hide catalogue results when none present

cache/modules/wc_org_cloudfront/waf.tf, cache/terraform.tf
Part of https://github.com/wellcomecollection/platform/issues/5919
This change further updates our WAF rules to:
- Further tighten the LATAM rate limit rule to 200 requests per minute following increased traffic from this region
- Consolidation of "GoogleOther" blocking role with manual user agent rate limit to simplify rules
- Block on LATAM requests that match a suspicious pattern we've seen in logs (outdate IE user-agent appearing in large request spikes.
Better identification of "bad" traffic, less downtime.
These rule changes do impact who can access the site and apply a rate limit. Care has been taken to ensure this impacts bot users only where possible and to minimise the impact otherwise.
=> Update WAF rules, block suspicious agents, increase rate limits

content/webapp/pages/search/index.tsx
For #11589 
[Search for "bananana"](https://www-dev.wellcomecollection.org/search?query=bananana) and check it looks like the screenshot above
Consistent appearance across search tabs
n/a
=> Show SearchNoResults component if there aren't any results

content/webapp/pages/search/index.tsx
For #11590 
Changes the size of the all search image thumbnails based on their aspect ratios. If they're portrait they're made slightly wider, if they're landscape they're made slightly narrower (this was how _all_ images were being treated up till this change). I think this seems to let them take up roughly equivalent amounts of space. One possible down-side is if there's a mixture of landscape and portrait images they are centre-aligned rather than sharing the same baseline – we could change this if we think that would be preferable, either aligning them to a baseline, or giving them all an e.g. black background.
I tried implementing a [react-photo-album](https://react-photo-album.com/) solution (such as is in use for the image search), but I think that all of the available patterns …
=> All image sizing

.buildkite/urls/expected_404_urls.txt, content/webapp/pages/series/[seriesId].tsx, content/webapp/services/prismic/transformers/index.ts, content/webapp/services/prismic/transformers/series.ts
At the moment it is not possible to preview a series page if none of the articles attached to it are published. This fixes that.
The reason for the current state is that we never used to fetch the series itself. In order to reduce the number of requests we made, we would fetch the articles linked to the series id, and get the series data from the linked series document on the first article we got back. Therefore, if we have articles (because they are unpublished) we have no data about the series.
However, when we moved to using uids in the url, we began fetching the series directly. Therefore, there is no reason to 404 if there are no articles returned.
- Visit wellcomecollection.org/series/the-joy-of-being-disabled, see that it 404s because no articles attached to it are published
- …
=> Series preview

content/webapp/components/SearchPageLayout/SearchNavigation.tsx
For #11591 
Rearranges the tabs to All | Catalogue | Images | Events | Stories
(The ticket references 'Events & Exhibtions', but we don't have that yet).
Look at the search pages to check they're in the above order
Catalogue researchers can get to what they want quicker/easier
n/a
=> Rearrange tabs for all search

.github/workflows/performance.yml
Following this email from GitHub:
```
The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025. To raise awareness of the upcoming removal, we will temporarily fail jobs using Ubuntu 20.04. Builds that are scheduled to run during the brownout periods will fail. 
```
We update the runner to `ubuntu-latest`.
Does the job run?
Less failing CI jobs!
Risks should be minimal, this only impacts CI.
=> Update ubuntu runner

common/views/components/PageLayout/PageLayout.tsx
Removes the polyfill.io script that we used to add missing browser features to older browsers.
[About one year ago](https://github.com/wellcomecollection/wellcomecollection.org/issues/10697#issuecomment-1997024141), less than 0.01% of our site visitors were using Internet Explorer, and this is the only browser with features that we are polyfilling. We no longer have it on our [browser support list](https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/DPDDj27NI2F2kPukWrC1/readme/front-end/front-end-principles#browser-device-support) in any form (full or basic) so it makes sense to remove it.
Test on Browserstack against our supported browsers. I've been unable to find a way to test Opera Mini – every suggestion (and link) on [this SO post](https://stackoverflow.com/questions/2594450/how-to-debu …
=> Remove polyfill.io

content/webapp/components/ImageEndpointSearchResults/ImageEndpointSearchResults.tsx, content/webapp/pages/search/index.tsx, content/webapp/services/wellcome/catalogue/types/index.ts
For #11616
Uses the ImageEndpointSearchResults component so that image results behave the same way they do on other parts of the website, i.e. opening a modal with similar images etc.
I needed to move some of the spacing around/use styled component props to compensate for the spacing inside this component.
As a side effect the images are now laid out with React Photo Album, which I think is an improvement.
**Before**:
**After**:
- enable the allSearch toggle
- make a search (e.g. http://localhost:3000/search?query=tree)
- click on an image search result and make sure it opens the modal rather than taking you to the item viewer page
The behaviour is consistent with the results behind the Image search tab (and the current All search image results)
None really, the component is already being …
=> Image search modal

toggles/webapp/toggles.ts
Adds a toggle ('exhibitionAccessContent') for making the access content changes to the Exhibition page.
The changes won't be releasable until they are all complete, so this allows us to work on the various bits in isolation and check everything works as expected before releasing them.
Once deployed the toggle will appear at https://dash.wellcomecollection.org/toggles/
We can use the toggle in our code.
None
=> add toggle

content/webapp/components/WorkDetails/WorkDetails.DownloadItem.tsx
#11020 
See ticket conversation for details.
It's still not perfect because if the column to the left takes up to much room it gets pushed to the left, but it's better in many places.
Still gets pushed a bit
But generally better
http://localhost:3000/works/htzhunbw
http://localhost:3000/works/tzdty2uj
Looks a bit less waaavy
N/A
=> Align format to the right in Download item list

common/services/conversion/track.ts, common/views/pages/_app.tsx, content/webapp/pages/about-us/cookie-policy.tsx
#11374 
[See comment in ticket](https://github.com/wellcomecollection/wellcomecollection.org/issues/11374#issuecomment-2671972326), I wrote it all there
Navigate to Cookie Policy
- Delete all cookies, navigate to website, cookie banner should appear.
- Click "manage cookies"
- Click "cookie policy"
- The banner should not display on cookie policy (the cookie has been set, empty)
- Scroll down and click "Cookie preferences" in the footer
- The modal box should appear.
Land directly on Cookie Policy
- Delete all cookies
- Navigate directly to the Cookie policy page
- The banner will display but hide immediately and you should be able to navigate.
- If you navigate to ANY OTHER PAGE, the banner should show again as you have not yet selected your preferences.
More legit? Users should be able …
=> Load cookie banner on cookie policy page but hide it

content/webapp/pages/search/index.tsx, playwright/test/all-search.test.ts, playwright/test/helpers/contexts.ts, playwright/test/search-all.test.ts, playwright/test/search-images.test.ts, playwright/test/search-stories.test.ts, playwright/test/search-works.test.ts, playwright/test/search.test.ts
#11498 
- [Adds a test to check if Content results are still available should Catalogue results not come through](https://github.com/wellcomecollection/wellcomecollection.org/pull/11641/files#diff-4ab95d6441ce1e971bae2f0e0cd9b33a126074b522ce07b22a2bced4acb0bcb2R90-R115)
- I couldn't figure out how to do the other way around easily, as it's a server-side request. It seems to require [new libraries that are experimental](https://github.com/vercel/next.js/blob/canary/packages/next/src/experimental/testmode/playwright/README.md) and weren't very easy to make work. I think we can try to rely on our Check URLs tests for big errors coming through, they cover this page already and expect 200s.
- I removed `newAllSearch` context and moved the new tests to use the existing context which now has the …
=> Add test when Catalogue API 500s and remove "old" test

common/customtypes/exhibitions/index.json, common/prismicio-types.d.ts
Adds an `embed` field to the exhibition model to contain BSL leaflet video.
This has been pushed to Prismic stage so you can see the field in Prismic on e.g. the [Hard Graft exhibition](https://wellcomecollection-stage.prismic.io/builder/pages/ZpE1ghAAACQAgRSg?s=unclassified)
Editors can add BSL content
n/a
=> Add bslLeafletVideo embed field to exhibition model

content/webapp/components/Exhibition/Exhibition.tsx
For #11629
Reorders components on the exhibitions page
- Visit [an exhibition page](http://localhost:3000/exhibitions/hard-graft-work-health-and-rights#events-list) with the exhibitionAccessContent toggle disabled
- The page should appear the same [as it does on the live site](https://wellcomecollection.org/exhibitions/hard-graft-work-health-and-rights)
- Visit [an exhibition page](http://localhost:3000/exhibitions/hard-graft-work-health-and-rights#events-list) with the exhibitionAccessContent toggle enabled
- The order of the page should match what is described in #11629
As long as the page appears the same without the toggle enabled there is little risk
=> Reorder exhibition page

content/webapp/components/Exhibition/Exhibition.tsx
For #11495 
Wraps content in logic so that the links and text that are displayed reflect what is available.
- Visit [an exhibition page](http://localhost:3000/exhibitions/hard-graft-work-health-and-rights#events-list) with the exhibitionAccessContent toggle enabled
- Use Prismic stage to add/remove visual stories/exhibition texts and exhibition highlight tours from the exhibition
- OR (fake the conditions in the code)
- The displayed text should match what is available - the [logic is described in the comments of this document](https://wellcomecloud-my.sharepoint.com/:w:/r/personal/l_baily_wellcome_ac_uk/Documents/Exhibition%20access%20copy%5B31%5D.docx?d=w83af6d26e2594c6bbcb8c01ebc646ff3&csf=1&web=1&e=FWiunK)
As long as the page appears the same without the toggle enabled there is little …
=> Exhibition page display logic

common/customtypes/exhibitions/index.json, common/prismicio-types.d.ts
Prep work for #11473, required for https://github.com/wellcomecollection/content-api/issues/219
- Change "Access content" tab name to "Access", matches Events'
- Adds Interpretations as a repeatable group comprised of a content relationship field, a boolean (in events this is a Select, but it's causing problems (https://github.com/wellcomecollection/wellcomecollection.org/issues/11165) so I thought I'd go with that?
Does it match event's closely? Have I missed anything?
Exhibitions can have access types added!
N/A
=> Add interpretations to Exhibitions

content/webapp/pages/search/index.tsx
#11610 
Did a few things here, so I'm sorry it looks like more than it is.
- I moved the client-side fetch functions and everything they needed to the `NewSearchPage` component, so it'd all be centralised. I did this to better contain what it needed, but also because I wanted to control state from them.
- I improved how the API toolbar links were created; they are buggy at the moment, and will often only add just the image or just the work link, because they overwrote each other. This ensures they should both be there and updated.
- I removed the works-only and images-only loaders, in favour of a generic one, that way it only displays content once we have it all, which makes it smoother IMO.
- This fixes the "no results" displaying in between a search result with content results and a …
=> Loading state in search and better API toolbar links

content/webapp/components/ContentSearchResult/ContentSearchResult.tsx
Removes the precise dates from exhibitions in search results and replaces it with the text from the `StatusIndicator` component using the same logic (one of 'Now on', 'Past', 'Final weeks', and 'Coming soon').
__Before__
__After__
It was confusing to see the end dates (or no end dates) for 'Permanent exhibitions'.
- Search for 'Being human' – check it's 'Now on'
- Search for 'Medicine man' – check it's 'Past'
- Search for 'Zines forever' – check it's 'Coming soon'
People aren't confused about whether an exhibition is on or not
There's less granular information in the search result (but the link to the result itself gives you all the information, so probably not a real risk)
=> Use status indicator text for exhibitions in content search results

common/data/cookies.ts, common/views/components/ApiToolbar/index.tsx
What it says in the title!
Little treat to ourselves.
Run locally and test the button behaviour
Able to remove the API toolbar then and there and not being confused anymore by what 🤏 means 😄 
If anyone used the 🤏, they can tell us we'll re-add it.
=> Add a close button and remove the mini button from the API Toolbar

cache/send_slack_alert_for_5xx_errors.js, cache/send_slack_alert_for_5xx_errors.tf
https://github.com/wellcomecollection/platform/issues/5965
Upgrade lambda to node20 and changes related to aws-sdk  v2 -> v3
Terraform not applied (will deploy to changes) 
```
Terraform will perform the following actions:
~ resource "aws_lambda_function" "lambda_function" {
id                             = "send_slack_alert_for_5xx_errors"
~ last_modified                  = "2024-07-30T12:59:53.000+0000" -> (known after apply)
~ runtime                        = "nodejs16.x" -> "nodejs20.x"
~ source_code_hash               = "3/BZ0yK45j7KVGKl7pVCWFpNyltVRR8mioUnTuwGKrU=" -> "cliy9H2EDnl+U99BlvLOjV66rP94tyH6o0S4QECog7I="
tags                           = {}
}
Plan: 0 to add, 1 to change, 0 to destroy.
```
The changes were tested by calling `findCloudFrontHitsFromLog` in isolation
The rest …
=> lambda on node20 and account for aws-sdk v3

common/views/components/VideoEmbed/VideoEmbed.tsx, content/webapp/components/BslLeafletVideo/index.tsx, content/webapp/services/prismic/transformers/embeds.ts
For #11452 
Checks for the presence of a `?` in the `embedUrl` that is extracted by a regex. If it's there, it means there's already a query string, so future parameters (we want to add `rel=0`) should be added with an `&` instead.
I've added the vimeo embed referenced in the issue above to [this article](http://localhost:3000/stories/rag-mags-and-monthly-issues--five-period-zines-to-stop-you-seeing-red) in prismic stage, so update the `getRepositoryUrl` to fetch from `wellcomecollection-stage` and check that it works
People can view embedded unlisted videos from vimeo
Can't think of any, but might be worth investigating if a similar fix needs to be implemented for YouTube/other embeds as well
=> Fix Vimeo embed for unlisted videos

common/data/microcopy.tsx, common/views/components/Header/Header.tsx, common/views/components/SearchForm/SearchForm.tsx, content/webapp/components/SearchPageLayout/SearchNavigation.tsx, content/webapp/pages/search/index.tsx, playwright/test/helpers/contexts.ts, toggles/webapp/toggles.ts
For [#233](https://github.com/wellcomecollection/content-api/issues/233)
Removes all references to `allSearch` and makes the previously toggled behaviour the default (and removing the old code)
Note: github has hidden the diff for search/index.tsx but it definitely needs reviewing
Search for something and check that the new search works
Less code to maintain
=> Make anything previously toggled by allSearch the default

common/data/microcopy.tsx, content/webapp/components/Exhibition/Exhibition.tsx
For #11694
- View [an exhibition page](http://localhost:3000/events/lights-up-on-hard-graft) with the exhibitionAccessContent toggle enabled, make sure the text matches what is described in the above issue.
n/a
None really
=> Accessibility resources text changes

content/webapp/components/TextWithDot/Dot.tsx, content/webapp/components/TextWithDot/index.tsx
The dots in the status indicator don't quite line up correctly with their accompanying text.
Before:
After:
Visit [a page with status indicators on it](http://localhost:3000/whats-on) and see that the dot aligns correctly with the text
n/a
none really
=> Centre the status indicator dot with its text

common/views/components/FindUs/FindUs.tsx, common/views/components/Footer/Footer.A11y.tsx, common/views/components/Footer/Footer.Social.tsx, common/views/components/Footer/FooterWithA11y.tsx
Removes exhibition/event access info from the footer because there wasn't a way to display it succinctly enough.
Footer looks like the screenshot and [designs](https://www.figma.com/design/juZQR2wi2BsYG8TDH6R4uk/Wellcome-Collection-%E2%80%93-Styles-and-Component-Library?node-id=3535-8488&m=dev)
n/a
n/a
=> Remove exhibition/event access info from footer

playwright/test/concept.test.ts
Adds back a failing e2e test. We should be able to merge this right after deploying the new concepts API to production. See https://wellcome.slack.com/archives/C02ANCYL90E/p1742485792254039 for more info.
=> Add back failing concepts e2e test

updown/updown-checks.ts
> [!Note]
> This change has been deployed.
This change updates a concept ID for an updown test as it has changed with a recent concept release.
See: https://wellcome.slack.com/archives/CQ720BG02/p1742544292065409
No false positive tests!
This impacts our alerting minimally, and correct an existing error. Risk should be minimal.
=> Update updown checks for new concept

content/webapp/components/Accordion/Accordion.tsx, content/webapp/components/BslLeafletVideo/index.tsx, content/webapp/components/Exhibition/Exhibition.tsx
Relates to [#11733](https://github.com/wellcomecollection/wellcomecollection.org/issues/11733)
-Enable the exhibitionAccessContent toggle
- View [an exhibition page](http://localhost:3000/exhibitions/zines-forever-diy-publishing-and-disability-justice) and use dev tools to confirm the presence of data-gtm-trigger attributes on the summary elements of the accordion and the link for the BSL video
We are able to set up tracking in GTM relating to the use of the accordion and the BSL video link
none really
=> Add gtm hooks

content/webapp/components/Exhibition/Exhibition.tsx
For [#11732](https://github.com/wellcomecollection/wellcomecollection.org/issues/11732)
Removes Access Resources section from the Being Human exhibition page
- Enable the exhibitionAccessContent toggle
- Visit the [Being Human](http://localhost:3000/exhibitions/being-human) exhibition page and see that there there is no Access Resource section
- Visit another[ exhibition page](http://localhost:3000/exhibitions/hard-graft-work-health-and-rights) and see that there is an Access Resources section
n/a
n/a
=> Don’t show access content on being human exhibition

common/data/microcopy.tsx, common/views/components/AccessibilityProvision/AccessibilityProvision.tsx
For [#11720](https://github.com/wellcomecollection/wellcomecollection.org/issues/11720)
Makes the changes described in the issue
- Enable the exhibitionAccessContent toggle
- view the [homepage](http://localhost:3000), [what's on page](http://localhost:3000/whats-on) and an [exhibition page](http://localhost:3000/exhibitions/hard-graft-work-health-and-rights) and check the copy and the icons are correct
n/a
n/a
=> Access resources tweaks

content/webapp/components/BslLeafletVideo/index.tsx
For #11747 
Changes the BSL leaflet video button to be black on iOS (where buttons are apparently blue by default if otherwise unstyled)
Run it in Simulator (or take my word for it that it works)
Consistent style
n/a
=> Make bsl leaflet video button color black on iOS

common/data/hardcoded-ids.ts, content/webapp/pages/events/[eventId]/index.tsx
Sets an `iconName` for the two bsl interpretation types, which then both map onto the `bslLiveInterpretationSquare` (signing hands) icon. As per decision previously outlined [here](https://github.com/wellcomecollection/wellcomecollection.org/issues/11516#issuecomment-2650486701)
Visit `/events/access-to-work` and check the icon appears next to the British Sign Language heading in the yellow box
Consistent iconography
n/a
=> Use bslLiveInterpretationSquare icon for event bsl interpretation types

content/webapp/components/Exhibition/Exhibition.tsx
For #11779 
Allows the StatusIndicator to wrap onto the next line if there isn't enough space for it alongside the date.
Visit `/exhibitions/zines-forever-diy-publishing-and-disability-justice` and shrink browser window
UI doesn't look broken
n/a
=> Allow StatusIndicator to wrap if neeeded

toggles/webapp/toggles.ts
Allows for [Filterable events listing page milestone](https://github.com/wellcomecollection/wellcomecollection.org/milestone/65)
=> Add toggle for Events listing pages changes

content/webapp/pages/events/index.tsx, content/webapp/pages/search/events.tsx, content/webapp/services/prismic/transformers/json-ld.ts
#11780
- Move use of toggle to `getServerSideProps`, then depending on what is returned, display something different
- Created a new json-ld helper function; `eventLdContentApi`. See comment I left to see what's been removed from it.
- Added a redirect from `/events/past?availableOnline=true` to `/events/past?isAvailableOnline=true`, which doesn't yet work but will once we do https://github.com/wellcomecollection/wellcomecollection.org/issues/11472. It was meant to be done as part of https://github.com/wellcomecollection/wellcomecollection.org/issues/11775 but it felt silly to just leave a comment there.
Run locally; 
- Does it look the same as in prod without the toggle? 
- Do both upcoming and past still return what they should?
- Does the pagination work?
We can move ahead with adding …
=> Use Content API behind toggle on events listing page

cardigan/stories/components/Tabs/Tabs.stories.tsx, content/webapp/components/Tabs/Tabs.Navigate.tsx, content/webapp/components/Tabs/Tabs.Switch.tsx, content/webapp/components/Tabs/Tabs.styles.tsx, content/webapp/pages/events/index.tsx
[Dana left comments in Figma](https://www.figma.com/design/Ab9RUk62Ah5MqTnPecwOdl/All-events-landing-page?node-id=4459-4145&m=dev), this addresses those.
#11799 
We also landed on applying new styles across all Tabs: unselected tab is paler (except when white) and uses a thinner font weight. We didn't want to apply the colour change that we can see in the mockups (where the underline is green) as we still use `yellow` as our main accent colour.
So `hasNewLook` is gone (yay) and it's just what it is now, toggle or not!
I've applied a full width border underneath the tabs in the Events listing.
Run locally, with and without toggle
It looks good
N/A
=> Events list header/ Tabs tweaks

content/webapp/components/Tabs/Tabs.styles.tsx
Based on chats with Dana.
Just changes the colour of the underline on hover on inactive tabs from grey to pale yellow, and the font colour is back to black for inactive/active tabs.
[See in Cardigan.](https://62f13cdbd0ff140768a8d87b-nvvrjrmryt.chromatic.com/?path=/story/components-tabs--basic)
=> Tabs colour change

cardigan/stories/components/AudioPlayerNew/AudioPlayerNew.stories.tsx, common/views/components/CollapsibleContent/index.tsx, content/webapp/components/AudioPlayerNew/AudioPlayer.tsx
Makes the AudioPlayer look nicer in Cardigan by adding some padding. Also we make any transcript added to the AudioPlayer obey the light/dark theme (and update cardigan background accordingly).
I'd also noticed that a transcript in a CollapsibleContent that was part of the light version would appear blue on iOS because of [the previously discovered issue](https://github.com/wellcomecollection/wellcomecollection.org/issues/11747) and fixed that at the same time.
Look at the [component in Cardigan](http://localhost:9001/?path=/story/components-audioplayernew--basic&args=isDark:!false&globals=backgrounds.value:transparent) and change the `isDark` prop. Check the component has some padding and the transcript toggle changes with the light/dark version change
n/a
n/a
=> Fix new AudioPlayer styling in cardigan (and make transcript obey theme)

content/webapp/components/AudioPlayerNew/AudioPlayer.PlayRate.tsx
Adds a hover state to the play rate toggle button that I missed in the spec.
Check it looks like this
Looks like designs
n/a
=> Add hove state to playrate toggle

content/webapp/components/PhysicalItemDetails/PhysicalItemDetails.tsx, content/webapp/components/PhysicalItems/PhysicalItems.tsx, content/webapp/components/WorkDetails/index.tsx
For [#5879](https://github.com/wellcomecollection/platform/issues/5879)
- Prevents the request button from being visible we know you can click it
- Simplifies the `useItemsState` hook into two lines
- Memoises the `physicalItems` which reduces re-rendering locally (I'm not sure if it would necessarily make things better in prod but can't hurt?)
I'm not clear on what is different about the way I've re-implemented `useItemsState` (with a `useState` and `useEffect` not wrapped in a function), but it seems to improve the situation (and I find it easier to reason about)
- Visit a requestable work (http://localhost:3000/works/spq4snpy) and refresh lots of times – check that the requesting button consistently appears
- Visit an archive with requestable items …
=> Item available dates

content/webapp/components/IIIFViewer/GridViewer.tsx, content/webapp/components/IIIFViewer/IIIFCanvasThumbnail.tsx, content/webapp/components/IIIFViewer/ViewerTopBar.tsx, content/webapp/utils/iiif/v3/index.ts
> [!NOTE]
> Would recommend reviewing while hiding whitespace changes
#11690
IF an Audio/Video/PDF file does not have either a thumbnail image or a `placeholderId`, (which is a poster image, I believe mostly for videos?), then it displays the relevant icon.
This is quite rare, most files have a (bad) thumbnail image, so most of the time that'll be what's shown: 
and sometimes the field is not empty and yet the image does not work and therefore loads forever (ex: https://www-dev.wellcomecollection.org/works/sx4p4b75/items): 
But should it happen that those fields are empty, then the relevant icon should be shown. I only found one example: https://wellcomecollection.org/works/dn9jwck6/items
A change from prod is that we didn't pass `placeholderId` before, so it was the loading thumbnail for …
=> Video, audio, PDF thumbnails

content/webapp/components/AudioPlayerNew/index.tsx
Fixes a bug on iOS where the time and now playing scrubber wouldn't reset after an audioFile change (i.e. if you client-side route to a different page without reinstantiating the AudioPlayer)
Visit a [guide stop](http://localhost:3000/guides/exhibitions/hard-graft/audio-without-descriptions/11) using the iOS simulator, move the now playing timeline into the middle of the slider, click prev or next, check that the scrubber is reset to the start and the time is 00:00
Less bugs
Still behind a toggle so minimal
=> Reset scrubber to zero after audioFile change on iOS

content/webapp/components/AudioPlayerNew/AudioPlayer.Scrubber.tsx
Adds hover behaviour to the timeline that scales up the thumb (previously this only happened if you hovered the thumb itself).
https://github.com/user-attachments/assets/3b8861bd-d885-4f8c-9e09-000e66bcc65b
Visit a [guide stop](http://localhost:3000/guides/exhibitions/hard-graft/audio-without-descriptions/2) (or Cardigan) and hover the timeline
Better UX
n/a
=> Apply scrubber thumb hover styles when timeline is hovered too

content/webapp/components/IIIFViewer/ImageViewerControls.tsx, content/webapp/components/IIIFViewer/ViewerBottomBar.tsx, content/webapp/components/IIIFViewer/ViewerTopBar.tsx
I think the `.btn__text` class was a leftover from a different configuration of the viewer and wasn't actually working, so I removed. Do flag if I'm wrong!
I needed to add some spacing between the icon and the text following https://github.com/wellcomecollection/wellcomecollection.org/pull/11860 because it's a bit tight
---
Now looks like: 
Check out item viewer locally
Less unused code / looks better?
N/A
=> Add spacing between icon and text for full screen

dash/webapp/pages/toggles.tsx, dash/webapp/yarn.lock
> [!Note]
> This change has been deployed.
This change allows the addition of URL parameters to dashboard requests that will enable or disable toggles. This allows links to be passed around that will turn on or off features for users, rather than requiring them to find the necessary toggle in the list.
For example:
**Enable** the new theme pages: `https://dash.wellcomecollection.org/toggles/?enableToggle=newThemePages` 
**Disable** the new theme pages: `https://dash.wellcomecollection.org/toggles/?disableToggle=newThemePages` 
**Error** with invalid toggle: `https://dash.wellcomecollection.org/toggles/?disableToggle=notThemePages` 
**Reset** all toggles: `https://dash.wellcomecollection.org/toggles/?resetToggles`
Easier to show users new features.
Risks should be minimal as this does not …
=> Add URL parameter 

common/views/slices/AudioPlayer/index.tsx, content/webapp/components/IIIFItem/index.tsx
https://github.com/wellcomecollection/wellcomecollection.org/issues/11520
Only show the new viewer if `audioPlayer` is on (in case we turn the public status OFF) as well as `extendedViewer`.
I tested behaviour (playing and then switching canvas to make sure it didn't keep playing, changing the speed and making sure it keeps it as a preference) and it all works really well (props @davidpmccormick)
Here's a work with multiple players: https://www-dev.wellcomecollection.org/works/k9k5vv2q/items
Test it with and without the `extendedViewer` toggle, the new player should only display behind it - mostly because we haven't developed for light mode yet, but also because we should think of a solution for a page without multiple players and making sure they don't all play at the same time (was this …
=> Show new audio viewer if toggle is on for audioPlayer and extendedViewer

content/webapp/pages/guides/exhibitions/[id]/[type]/[stop]/index.tsx
[Fixes bug where audio player also displays in BSL guides](https://wellcome.slack.com/archives/CUA669WHH/p1746528403116589)
=> Only show audio player in audio guide

content/webapp/components/PhysicalItems/index.tsx, content/webapp/components/WorkDetails/index.tsx
Reverts some changes from https://github.com/wellcomecollection/wellcomecollection.org/pull/11841/files
I left the changes to the `showButton` conditions as it made sense for me to keep it, but I haven't dug deep. [Mostly removing because of all the alerts we've been getting in Slack since the PR and I don't have the headspace to fully fix.](https://wellcome.slack.com/archives/C02ANCYL90E/p1746536494213419)
Does requesting items still work nicely?
No more alerts in the Slack channel
Breaks something else
=> Req items: revert some changes from prior PR

cache/locals.tf
Will allow for change to be applied to production
Sequel to https://github.com/wellcomecollection/wellcomecollection.org/pull/11878 for https://github.com/wellcomecollection/wellcomecollection.org/issues/11775
=> `/events/current-and-coming-up` redirect prod

content/webapp/pages/concepts/[conceptId].tsx, toggles/webapp/toggles.ts
For https://github.com/wellcomecollection/platform/issues/6007
Deletes a now unused toggle.
Removal of unused toggles/code to keep things understandable.
The risks should be minimal as this toggle is now unused.
=> Remove conceptsById toggle

content/webapp/components/DownloadLink/index.tsx, content/webapp/components/IIIFItem/index.tsx, content/webapp/components/IIIFViewer/MainViewer.tsx, content/webapp/components/VideoTranscript/index.tsx
For [#11519](https://github.com/wellcomecollection/wellcomecollection.org/issues/11519)
- makes sure the video player is never displayed larger than the screen
- styles the download link on a dark background
see designs: https://www.figma.com/design/OxxzV0GrHOEofLRb9sm2fP/Audio-and-video-player?node-id=24-4171&m=dev
- turn on the extendedViewer toggle
- view [a video item with transcript link](http://localhost:3000/works/sx4p4b75/items)
- can watch videos in the viewer and download transcripts
- behind a toggle, so none really
=> Video in viewer

content/webapp/components/VisuallySimilarImagesFromApi/index.tsx
For #11618 
Adds a data-attribute to the visually similar images so that we can track clicks on them through gtm (currently we do this with Segment, which we're moving away from)
Open an image search result and inspect the visually similar images beneath – do they contain a `data-gtm-trigger="visually_similar_image"` attribute?
with gtm
n/a
=> Add gtm trigger for visually similar images

common/views/slices/Contact/index.tsx, content/webapp/components/AudioPlayerNew/AudioPlayer.PlayRate.tsx, content/webapp/components/AudioPlayerNew/AudioPlayer.Scrubber.tsx, content/webapp/components/AudioPlayerNew/index.tsx, content/webapp/services/prismic/fetch/guides.ts
Note: [This commit](https://github.com/wellcomecollection/wellcomecollection.org/pull/11887/commits/ca30fb1fc71371261645c112025b5f77582db1c5) to add `teamsFetchLinks` to guide pages was included in this PR accidentally but stayed in because it was fixing a live issue
For #11883 
Open AudioPlayerNew in Cardigan and check light/dark version match [designs](https://www.figma.com/design/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?node-id=2528-4005&p=f&m=dev) (I didn't add the trust yellow because it felt like overkill for such a small piece of UI)
Consistent UI across light/dark versions
n/a
=> Audio player qa 2

content/webapp/components/EventsSearchResults/index.tsx
[Feedback from Steven Pocock in Slack](https://wellcome.slack.com/archives/C8X9YKM5X/p1746696012366219?thread_ts=1746621405.647939&cid=C8X9YKM5X)
There is no reason why not! And it does look better
Before
After
Check it out locally everywhere we have events listing (search, /events..)
Happy photography
N/A
=> Use 16:9 crop instead of 32:15 in events listings

README.md, docker-compose.yml, identity/README.md, pa11y/Dockerfile, pa11y/webapp/write-report.js
Spent a couple hours trying to debug why our pa11y dashboard task fails so often (e.g. https://buildkite.com/wellcomecollection/wc-dot-org-deployment/builds/3966#_), but I think it's out of my knowledge level and not worth me spending more time on for now. I did find out it errors because the `write-report` script fails (seems to be puppeteer/chrome browser related) and therefore the report isn't written, which means the `.dist/report.json` folder/file doesn't, indeed, exist.
I did end up tidying up a few bits. 
- command line `docker-compose` should now be `docker compose`.
- Added comments to explain the pa11y Dockerfile more
- Added logging to the pa11y report for further understanding/exploration.
=> Tiny tidy of TODOs and READMEs

content/webapp/components/VisuallySimilarImagesFromApi/index.tsx
For #11618 
[We want to know the id of the visually similar image being clicked,](https://github.com/wellcomecollection/wellcomecollection.org/issues/11618#issuecomment-2876051922) but this isn't currently available as an attribute in the DOM. It would probably be possible with some tagmanager acrobatics, but I think the simpler/better solution is to add it as an attribute to the element that we're tracking clicks on.
Visit a [page with a modal displaying visually similar images](http://localhost:3000/search?query=test#djjp3ye7) and inspect the `<a>` tags that wrap the images – do they have a `data-gtm-img-id` attribute populated with the image id?
We can track what we need to in GTM
n/a
=> Add data-gtm attribute for the related image id

content/webapp/components/Map/index.tsx
https://github.com/wellcomecollection/wellcomecollection.org/security/code-scanning/23
https://github.com/wellcomecollection/wellcomecollection.org/security/code-scanning/22
Seemed a sensible change so went for it; I'm still able to render the Map locally, unsure what else could be affected?
https://www-dev.wellcomecollection.org/visit-us/getting-here
Other ideas?
Less flags!
N/A
=> Address Incomplete URL substring sanitisation security flags

.buildkite/urls/expected_200_urls.txt, pa11y/webapp/write-report.js
[#11885](https://github.com/wellcomecollection/wellcomecollection.org/issues/11885)
From this PR's tests:
https://buildkite.com/wellcomecollection/wc-dot-org-build-plus-test/builds/16285#0196ca56-05e8-4128-b78a-fc65df9a309e/141-329
https://buildkite.com/wellcomecollection/wc-dot-org-end-to-end-tests/builds/5910#0196ca59-3d94-4077-862e-e78edb36f875/146-175
All search pages are checked
N/A
=> Add events search to pa11y and Check URL

content/webapp/pages/events/index.tsx, content/webapp/pages/events/past.tsx, content/webapp/pages/search/events.tsx, toggles/webapp/toggles.ts
#11473
Adding exhibitions is a work in progress but the param is now available, so setting now so it's ready when we switch the pipeline over to the one with exhibitions in events.
I added it everywhere in the end so we could merge the Content API work slowly instead of all at once ([this PR for example](https://github.com/wellcomecollection/content-api/pull/228)). 
> [!NOTE]
> I did not add e2es as per ticket; would we want a test for this? I wasn't sure it was that useful.
Consider:
- https://www-dev.wellcomecollection.org/search/events
- https://www-dev.wellcomecollection.org/events
- https://www-dev.wellcomecollection.org/events/past
1. Run locally, no exhibitions should be in any pages above.
2. Run locally with [this branch](https://github.com/wellcomecollection/content-api/pull/228) …
=> Add `filterOutExhibitions` to event listing queries

content/webapp/components/VisuallySimilarImagesFromApi/index.tsx
After #11912 I thought I'd be able to get the currently-being-viewed image id from the URL in tagmanager, but it is always the previously viewed image (this is also true if I use the gtm built in `newHistoryFragment` or `oldHistoryFragment` variables, so doesn't seem easy to pluck out with gtm alone. So instead I'm adding the original image id as an attribute as well.
Can you see a `data-gtm-original-img-id` attribute on the visually similar images on e.g. [this page](http://localhost:3000/search?query=test#d6yspfaz)
Visually similar image journeys can be tracked
n/a
=> Add original image id data attribute

common/types/periods.ts, content/webapp/pages/events/index.tsx, content/webapp/pages/events/past.tsx, content/webapp/pages/search/events.tsx, toggles/webapp/toggles.ts
https://github.com/wellcomecollection/wellcomecollection.org/issues/11851
Removes all traces of the toggle! Everything should work as it currently does in prod.
Affected pages:
1. https://www-dev.wellcomecollection.org/events
2. https://www-dev.wellcomecollection.org/events/past
3. https://www-dev.wellcomecollection.org/search/events
Ensure the filters still work
The pagination still works
The ordering is the same as in production
Less code yay
N/A
=> Remove `filterEventsListing` toggle and related code

content/webapp/components/VisuallySimilarImagesFromApi/index.tsx
We previously tried to use data attributes to send these values and pick them up with a GTM clicked links trigger, but The `onClickImage` function was updating the `originalId` before it was sent (making the `relatedId` and `originalId` appear the same in GA). By pushing to the dataLayer before `onClickImage` runs we make sure the correct values are sent.
This bit of site functionality is ripe for a refactor though – there is definitely some confusion with potentially extra history changes and unwanted hash behaviour (#11631)
Not sure – if you want to run tag manager locally you should be able to see the `visually_similar_images_click` event happening when you click a similar image with the correct parameters being set
Get the right results in GTM
n/a
=> Use dataLayer to send 'visually_similar_image_click' event

content/webapp/components/PhysicalItems/index.tsx, content/webapp/components/WorkDetails/index.tsx
For https://github.com/wellcomecollection/platform/issues/5879
Original ticket: #11841
Partially reverted in #11875 as we thought it was the cause of a lot of alerts, but then [Robert found it was probably due to something else](https://wellcome.slack.com/archives/CQ720BG02/p1746708905563989).
As the alerts have now subsided, we are wanting this code back in to address #5879. We'll keep an eye on it to make sure it was unrelated.
From original ticket:
- > Visit a requestable work (http://localhost:3000/works/spq4snpy) and refresh lots of times – check that the requesting button consistently appears
- > Visit an archive with requestable items (http://localhost:3000/works/pxr3mfzx) and click to another item in the archive – does the requesting section re-render (it should)?
Bug is addressed …
=> Revert #11875 which was a partial revert of #11841

content/webapp/components/IIIFItem/index.tsx
Forgot this case when I did https://github.com/wellcomecollection/wellcomecollection.org/pull/11921 for https://github.com/wellcomecollection/wellcomecollection.org/issues/11899
https://www-dev.wellcomecollection.org/works/k9k5vv2q
without the Extended viewer canvas should now display the new viewer instead of the old one (and only one at a time now woo)
I believe that's NOW the new player everywhere
N/A
=> Works audio to be the new audio player

cache/README.md
Adds a link to the newly created A/B test steps in GitBook
Read it?
We can make A/B tests easier
n/a
=> Add a link to A/B tests steps in cache README

prismic-model/lintPrismicData.ts
We were flagged a broken link recently, it started with `www.` and was counted as a relative link, so after chatting with Vanesha, I thought I'd try and figure out a way to spot outliers...
Run `yarn lintPrismicData` locally, could try to break a link for it 🤷‍♀️  - There is a broken one already which looks like a link from an iPhone that isn't a link, I'm keeping it there to give the example to Editorial!
Less chances of borked links? The logic is far from perfect, let's be honest, but would reduce chances.
🤷‍♀️
=> Find invalid links in Prismic (prismic linter check)

cardigan/stories/components/Contact/Contact.stories.tsx, common/customtypes/teams/index.json, common/prismicio-types.d.ts, content/webapp/components/Contact/index.tsx, content/webapp/services/prismic/transformers/events.ts, content/webapp/services/prismic/types/index.ts, content/webapp/types/events.ts
I think this had been broken for a _while_. The FE expects a hyperlink field and the content type field was a text field? It didn't work. And anyway only one or two Teams document had something in that field, which hadn't rendered them out (it's not in the transformer either!) in I don't know how long.
It seems we do add pass a link to the Contact component, but manually, directly from the codebase [in one instance](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/content/webapp/components/Exhibition/index.tsx#L600-L604). It might not be a debatable use since it's only once but 🤷‍♀️ 
So am removing from the model since it didn't work anyway.
Does it seem to break anything?
Less unused fields/confusing code
Editorial are sad about not having the field; we re-add in …
=> Remove link field in Teams content type

content/webapp/components/RelatedWorks.tsx
For [#11964](https://github.com/wellcomecollection/wellcomecollection.org/issues/11964)
Uses the current work's subject labels as a filter when fetching the content for the date tab, as specified in the [figma design files](https://www.figma.com/design/6ZvjrD9yhBBZSAXENc8vK4/Related-content-on-Works-pages?node-id=706-11755&m=dev)
- turn on the relatedContentOnWorks toggle
- open the network tab in dev tools
- visit [a work with a date tab](http://www-dev.wellcomecollection.org/works/y9t4zfsh)
-  click on the date tab and see that the network request it initiates includes the subject labels as parameters
n/a
None really. This work is behind a toggle and is an MVP to aid further research/discussion/development
=> filter date results by the same subject labels the current work has

content/webapp/pages/pages/[pageId].tsx, content/webapp/services/prismic/transformers/pages.ts, content/webapp/types/pages.ts
The [linkResolver](https://github.com/wellcomecollection/wellcomecollection.org/blob/0cb4e0aeb1f8a2328de6961ac0aa8d534120f194/common/services/prismic/link-resolver.ts#L85-L93) gets information from a page's `siteSection` and `tags`, but we don't currently store these things on `page.parentPages` so we're not handling certain breadcrumbs correctly (#11982).
Check the 'Library and facilities' link in the breadcrumb correctly includes `/collections` in it's URL for these pages
- http://localhost:3000/collections/study-rooms
- http://localhost:3000/collections/computers--printing-and-wifi
- http://localhost:3000/collections/copying-and-photography
Links don't 404
=> Add tags and siteSection to parentPages

content/webapp/components/RelatedWorks/RelatedWorks.Card.tsx, content/webapp/components/RelatedWorks/RelatedWorks.helpers.tsx, content/webapp/components/RelatedWorks/index.tsx
- Realised the `catalogueBasicQuery` helper returned `{}` when no results came up where it's better if it returns `undefined`, so fixed that. I can't remember the work that made me realise it was an issue, sorry 🙈 but the fix makes sense still.
- Moved the `SVG` so it's only injected once **per component** (so could still be injected more than once should we have the component more than once on the page. Doesn't currently happen, but something I'm thinking about!), instead of once per tab. It also checks first if any works has a thumbnail image and is therefore needed. Added positioned it absolute otherwise it added a space even though it was `0x0` in width/height 🤷‍♀️ 
- After chatting with Lauren, Type/Techniques and date range queries only happen if there is at least one subject label. …
=> Related works tweaks/fixes

cardigan/stories/components/OnThisPageAnchors/Sticky.stories.tsx, content/webapp/components/OnThisPageAnchors/index.tsx
Follows https://github.com/wellcomecollection/wellcomecollection.org/pull/11951, implements changes from QA as described here: https://github.com/wellcomecollection/wellcomecollection.org/issues/11977
https://github.com/user-attachments/assets/43cc4148-e9c1-4bac-b592-33ab21731da0
Issues addressed:
Issues not addressed:
- Component renaming: This should be done separately if we're going to do it as it updates the name of an existing component.
[Review the component in Cardigan](https://62f13cdbd0ff140768a8d87b-lkjzfwdlqx.chromatic.com/?path=/story/components-onthispageanchors--side-bar).
Some really jolly nice in-page navigation.
This change is not (yet) added to a page so should be minimal. We should check instances of the existing component are un-impacted.
=> Update "sticky" in page navigation post-QA

content/webapp/components/RelatedWorks/RelatedWorks.helpers.tsx, content/webapp/components/RelatedWorks/index.tsx, content/webapp/pages/works/[workId]/index.tsx
I was thinking that since we changed the logic to not query types and date range if there is no subjects, that the component shouldn't even be declared if the work has no subject, since then it wouldn't even do anything. 
So I change the type of `work` in `RelatedWorks` to ensure it has at least one subject label, moving the conditions higher up with a type guard. 
I removed the conditions that were lower in the tree, since at that point, we know there's at least one subject label.
> [!NOTE]
> I also wonder if we should reduce the amount of data we're passing to `RelatedWorks`. It only needs the work id, its subjects, labels and date (if valid). We don't need to pass the whole Work object. [I made a separate PR for it](https://github.com/wellcomecollection/wellcomecollection.org/pull/12007 …
=> Stop `RelatedWorks` from being declared if work has no subject

content/webapp/components/RelatedWorks/RelatedWorks.styles.tsx
For #12014
Wraps the image in a `display: flex` element which by default stretches the child (img) to fill the available space, doing away with the need for a `max-height` which was the root of the [Safari bug](https://stackoverflow.com/questions/19119910/safari-height-100-element-inside-a-max-height-element)
Visit a related work in Safari with `toggle_relatedContentOnWorks` set to `true` and check the images don't break out of the container
Fewer UI bugs
n/a
=> Fix iOS mobile RelatedWorksCard image size

common/views/components/ApiToolbar/index.tsx, content/webapp/components/ArchiveBreadcrumb/index.tsx
Just scrolls the API toolbar when it gets too big for the page. Works pages, for example, have a lot of content in there, and it creates this big white space on the right hand side, on smaller screens and mobile. When I'm developing, it often makes me think I've done bad CSS or something 😄 so treating myself to an overflow scroll, here.
Also noticed that some Archive Breadcrumbs were really big and caused an extra space on the right hand side too, on mobile (e.g. https://www-dev.wellcomecollection.org/works/a222zvge), so removed the margin from the last child.
Have API tool bar, go to [a works page](https://www-dev.wellcomecollection.org/works/zsgh5y3z), there shouldn't be a big gap on the right on a smaller screen anymore.
It's nicer isn't it?
N/A
=> Scroll toolbar when too big

content/webapp/components/Tabs/Tabs.Navigate.tsx, content/webapp/components/Tabs/Tabs.Switch.tsx, content/webapp/components/Tabs/Tabs.styles.tsx
We change the font-weight of the selected tab which has a knock-on effect of shifting all other tabs one or two pixels horizontally.
Adding a `visibility: hidden; height: 0` element containing the tab's text content that has the inter bold font-weight (700) ensures the tabs always take up the same amount of space regardless of whether they're selected. Setting `visibility: hidden` means it won't be read by screenreaders either.
[Initial attempt](https://github.com/wellcomecollection/wellcomecollection.org/pull/12025/commits/7e34506e160931d81172f0b3771c8b39e10524c9) was to add this as a pseudo-element, but the fact the tab content can be a ReactNode (containing other nodes) made this problematic.
__before__
__after__
- Visit a work with `toggle_relatedContentOnWorks` turned on and click on …
=> Prevent tabs layout shift

content/webapp/components/RelatedWorks/RelatedWorks.styles.tsx
For #11996
__before__
__after__
- View RelatedWorksCard on a small screen and check the image doesn't exceed 200px.
- View it on a wider screen to check everything still looks ok
Users get unpixelated images
n/a
=> Limit image size and center on mobile

content/webapp/components/Exhibition/Exhibition.Installation.tsx, content/webapp/components/Exhibition/Exhibition.helpers.tsx
#12028 #12032
- Modifies Breadcrumb to point to Exhibitions listing (as per [Lauren request](https://wellcome.slack.com/archives/CUA669WHH/p1750337739581069))
- Display related stories to match other exhibitions
- Changes to the info displayed in yellow box IF Finger Talk installation (hopefully to be dealt with more elegantly soon) 
Run locally and access [Finger talk](https://www-dev.wellcomecollection.org/exhibitions/finger-talk-installation) installation
Does it change anything on other exhibitions?
Finger talks displays what it should
N/A apart from having a very specific conditional (risk of annoying code 😏 )
=> Installation: add related stories, change breadcrumb

updown/README.md, updown/types.ts, updown/updown-checks.ts
This change disables uptime monitoring in the asia pacific region, to avoid false positives on bot-traffic throttles.
View the updown dashboard, are these changes reflected there?
- Less false positives in downtime alarms.
It is possible that temporary outages due to bot traffic in these regions are early signifiers of potential issues in other regions. We will still be able to see geographic region specific issue in AWS WAF.
=> Disable Asia–Pacific updown monitoring

prismic-model/lintPrismicData.ts
It can be hard to find where a faulty link is when it's flagged in a document with a huge amount of text ([see Slack](https://wellcome.slack.com/archives/C3N7J05TK/p1750825028476759)), so I thought I'd add this. It seems to work fine as I tested, if it print horrendous things we can remove it.
I put a faulty link in https://wellcomecollection.prismic.io/builder/pages/ZIclmBAAAMwEH7EL?s=archived&v=aF0AkxAAACUAvYj6 to test with if you'd like to! (republish it and run `lintPrismicData` locally
Easier for Editorial to fix those
N/A
=> Prismic linting: Add an indication as to what the text might be around a faulty link

common/views/components/Buttons/Buttons.Dropdown.tsx
Dana's flagged a visual bug that seems to have been there for a long time (I stopped looking after seeing it was there at the end of May and can't recall changes to Dropdown that would've caused this).
[Slack convo](https://wellcome.slack.com/archives/CUA669WHH/p1751540606514549)
Opted for a max-height (although arbitrary number picked, suggestions welcomed) as it was hard to use anyway:
Currently:
This branch:
If we think more changes are required, please flag so. This is vm a quick fix.
Run it?
No more huge white space under footer, but also easier to use as it's not mega long anymore.
N/A?
=> Visual bug fix: Max height on dropdowns

content/webapp/views/concepts/concept/index.tsx
For #12103
Aligns the hotjar poll with the other elements in the right column
The poll only appears on prod, so you'll have to trust me
nicer UI
n/a
=> Move hotjar placeholder  into right column

content/webapp/views/pages/concepts/concept/concept.styles.tsx, content/webapp/views/pages/concepts/concept/index.tsx
Using the `Container` to determine the right amount of space around the hotjar component instead of being defined on the placeholder itself. This allows us to align it properly whether it's in the right-hand column or not.
__before__
__after__ (probably)
Think you'll have to trust me again
Nicer ui
I've missed something because I can't see it locally (but I don't think I have)
=> Take padding off placeholder (use container where needed)

common/views/themes/typography.ts
For #12103 
Applies `scroll-margin-top` to h2s and h3s that are children of `data-id` sections (which we have recently created to deal with the scroll-spy OnThisPageAnchors).
There's enough (3rem) margin to clear the sticky header on mobile, then an equivalent amount of space as the side nav has, to make the top of the header align with the top of the side nav on desktop.
__desktop__
__mobile__
- Visit a [concept](http://localhost:3000/concepts/patspgf3) page, click in the side nav, verify there is space above the headings
- Make the window small, click in the mobile nav, verify the headings are visible below the nav
Nicer UI
Maybe the [data-id] selector is a bit vague (could be section[data-id] perhaps?) I don't mind it like this, but happy to change it if others don't like it.
=> Apply scroll margin to the data-id sections

content/webapp/views/components/CatalogueImageGallery/useExpandedImage.ts
Stops the browser scrolling to the hash of the clicked image when opening the image modal. This has apparently always been a thing, but now that we add `scroll-behavior: smooth` it is much more noticeable/jarring.
__before__
__after__
Visit a [page with an image modal](http://localhost:3000/concepts/patspgf3), click the images, check there's little to no visible scrolling either when the image opens or closes
People don't feel like they're going to be sick when they open an image
can't think of any
=> Pin scroll position when opening/closing image modal

playwright/test/concept.test.ts
We previously encountered a [bug](https://github.com/wellcomecollection/wellcomecollection.org/issues/12042#issuecomment-3049213573) where navigating from a concept to a work and back again didn't present the correct concept page information even though the URL was correct. Adding an e2e to make sure we don't introduce a regression.
`cd playwright && yarn test test/concept.test.ts`
We get notified if things break before anyone else knows
n/a
=> Add an e2e for concept -> work -> concept back button

content/webapp/views/components/InPageNavigation/InPageNavigation.Sticky.styles.tsx, content/webapp/views/components/SourcedDescription/index.tsx
For #12128
- Makes sure source description container is above mobile nav
- Adds some padding at the bottom of the mobile nav
- Visit a [concept page](http://localhost:3000/concepts/usqyr9ur) with a narrow window and hover the 'Wikidata' button – check the tooltip is above the mobile nav
- Open the mobile nav and check there's 12px padding at the bottom
UI works/looks nicer
n/a
=> Concept Page QA

content/webapp/views/components/CatalogueImageGallery/CatalogueImageGallery.Scrollable.Buttons.tsx
https://github.com/wellcomecollection/wellcomecollection.org/issues/12133
[See this comment](https://github.com/wellcomecollection/wellcomecollection.org/issues/12133#issuecomment-3097621326)
On browserstack for Chrome mobile:
On normal browser:
Honestly, think we'll just have to merge this to staging and test there.
I've tested it in Browserstack in a very awkward manner by running code in the console there and I really feel it's a good path to go down on.
Scroll works on Chrome Android
Pretty low risk this.
=> Scroll bug on Android/Chrome; Round up container "scroll left" value

content/webapp/views/components/CatalogueImageGallery/CatalogueImageGallery.Scrollable.Buttons.tsx
https://github.com/wellcomecollection/wellcomecollection.org/issues/12133
Follow up to https://github.com/wellcomecollection/wellcomecollection.org/pull/12146
I'd originally tested with Math.round, then only tested scroll right with Math.ceil, which was a mistake as it doesn't work for Left. I've test both now and believe this should do it
I've tested manually in browserstack, but again think we're better off getting this to staging. Happy to demonstrate though!
Scrolling in Android Chrome
N/A
=> Scroll bug on android; Change Math ceil to Math round

content/webapp/views/components/SourcedDescription/index.tsx
For #12131
Adds a trigger to the `SourceBox` that is shown on hover(/tap) 
You can preview the `source_box_shown` GA event firing 
We can measure component usage
Not specifically, although worth mentioning that I had to use the 'Every time an element appears on screen' version of the trigger, rather than the 'Once per page' version, probably because of the way our routing is done client-side.
=> Add gtm trigger to SourceBox

common/views/components/FeaturedWorkLink/index.tsx
https://github.com/wellcomecollection/wellcomecollection.org/issues/12159
Also amended padding as it was in `em` and looked strange with a smaller logo.
[Article with this in captions and under images](https://www-dev.wellcomecollection.org/stories/a-history-of-art-in-hospitals)
[Article with this in Text and under images](https://www-dev.wellcomecollection.org/stories/YZJzrhEAACUARhC3)
Looks the same everywhere
N/A
=> Make featured works icon a set size

common/utils/gtm.ts, content/webapp/views/pages/concepts/concept/concept.Header.tsx, content/webapp/views/pages/concepts/concept/concept.RelatedConceptsGroup.tsx, content/webapp/views/pages/concepts/concept/index.tsx
For #12131 
Different RelatedConcepts need different data-gtm-attributes, so we need to move where the props get passed in higher up
Check the RelatedConcept tags at the top of a concept page have a `data-trigger="field_of_work"` attribute, and the ones at the bottom of a concept page have a `data-trigger="related_topics"` attribute. We should also be able to get the `relationshipType` (frequently referenced together, related to, broader than etc. ) sent along if it exists.
We can track things
n/a
=> Allow dataGtmProps to be passed in higher up to differentiate RelatedConceptsGroups

content/webapp/views/pages/works/work/IIIFViewer/ViewerSidebar.tsx
If you click on e.g. Licence and re-use in the viewer sidebar currently, the button that toggles showing the content gets a yellow border when it's active. This is a style that we only want to apply when the user's navigating with a keyboard and [we updated this globally a couple of years ago](https://github.com/wellcomecollection/wellcomecollection.org/blob/4e8f73796387b5e47c3abee899681f06896102fd/common/views/themes/base/wellcome-normalize.ts#L30-L40) so I think we should remove it here
Visit a [page in the viewer](http://localhost:3000/works/ww3byp9j/images?id=bym8rg4n), click Licence and re-use, verify the button doesn't get a yellow border. Navigate to the button with the keyboard and verify it does get a yellow border
Less jarring/more consistent UI
Maybe it was deliberately like …
=> Remove bespoke active style from ViewerSidebar buttons

content/webapp/views/pages/concepts/concept/concept.ImagesResults.tsx, content/webapp/views/pages/concepts/concept/index.tsx
https://github.com/wellcomecollection/wellcomecollection.org/issues/12168
See [comment](https://github.com/wellcomecollection/wellcomecollection.org/pull/12167/files?diff=split&w=1#diff-6d2329ed65ac1b10c41ac34bf21c98a462421efc3be796c7b01598b62bcd6cbcR430-R433) for more details...
As the modal was working ok in `/search/image`, I thought this was a palatable enough fix. 
I've checked in Firefox and Chrome that it still behaved ok and it looks like it to me!
Users of <Safari 18.2 can view images in their modal on concept pages
If it breaks it on other browsers 🤷‍♀️
=> Move ImageModal outside of its parent

content/webapp/views/pages/concepts/concept/concept.styles.tsx
For #12168 
Makes the side nav show up in Safari
- Open a concept in Safari 17.3 (MacOS Sonoma)in Browserstack
- Check the nav is there, that is has mix-blend-mode: difference working on desktop, and that the mobile styles remain unchanged
- have a look in Firefox and Chrome for good measure
People can see the nav(!)
Perhaps I've inadvertently broken something else (don't think so though)
=> Safari fix

content/webapp/views/components/InPageNavigation/InPageNavigation.Sticky.styles.tsx, content/webapp/views/components/InPageNavigation/InPageNavigation.Sticky.tsx
Moves the overlay to the end of `document.body` using a [React portal](https://react.dev/reference/react-dom/createPortal).
My other attempts to make Safari `position: fixed` relative to the viewport (mostly sticking `transform: translateY(0)` on things and hoping for the best) didn't bear fruit.
Open a concept in old Safari, make the window small and open the mobile nav when it's stuck. Check you can see a dark overlay behind the nav, that scroll is locked and that clicking the overlay dismisses it/unlocks scroll. Check this still works in other browsers.
Cross-browser consistency
A bit of extra React magic just for old Safari? I think it's probably ok though?
=> Make the dark overlay appear consistently across browsers when mobile nav stuck and open

content/webapp/contexts/ConceptPageContext/concept.config.tsx, content/webapp/views/pages/concepts/concept/concept.Collaborators.tsx
(I conflated the spec for Frequent collaborators and Related topics in the Figma file)
If we show collaborators on a concept, there should only ever be a maximum of 4, but I got confused when looking through the Figma spec because it was close to Related topics where 12 is the maximum
Visit a [person concept](http://localhost:3000/concepts/patspgf3#frequent-collaborators), check that there's only 4 frequent collaborators
Meets design spec
n/a
=> Make collaborator max always 4

content/webapp/views/pages/works/work/IIIFViewer/IIIFViewer.tsx
If we pass a `iiifImageLocation` to the `ZoomedImage` component, it will use that image to zoom. Otherwise it will try to use the image service on the current canvas. But we now have a [situation](https://wellcome.slack.com/archives/C8X9YKM5X/p1753864052307589) where a catalogue response contains a `iiifImageLocation` for a single image from a work as well as all the items for the work and the end result was the single image would always be the one that was zoomed.
This PR checks whether we have an image service available, and if so, stops the `iiifImageLocation` from being sent to the `ZoomedImage` component (and the viewer top bar that handles downloads, where the same problem would have been happening).
This feels like a bit of a sticking plaster that should probably be fixed …
=> Only use IIIF image location if we don't have an image service on the current canvas

content/webapp/contexts/ConceptPageContext/concept.config.tsx, content/webapp/views/pages/concepts/concept/concept.RelatedConceptsGroup.tsx
We were defining concepts to filter out from each concepts 'related topics' on the front end, but this has already been done further up the chain so isn't needed.
Can't think of a thorough way to do it, but e.g. visit a [person concept](http://localhost:3000/concepts/patspgf3) and check that they don't have any 'person', 'agent', or 'organisation' related topics
Less unnecessary front end code to maintain
n/a
=> Don't exclude topics on the frontend because this has already happened

content/webapp/views/components/MoreLink/index.tsx, content/webapp/views/pages/concepts/concept/concept.ImagesResults.tsx, content/webapp/views/pages/concepts/concept/concept.WorksResults.tsx, content/webapp/views/pages/concepts/concept/concept.helpers.ts, content/webapp/views/pages/concepts/concept/index.tsx, playwright/test/pages/concept.ts
Change the all images/works buttons to 'View all' with extra aria-label content.
Visit a [concept](http://localhost:3000/concepts/patspgf3), check the 'all' buttons say 'View all' and have additional aria-label information
Better UI/UX
We probably need to validate that this approach is reasonable with a11y testing.
=> View all buttons

content/webapp/views/pages/concepts/concept/concept.Collaborators.tsx, content/webapp/views/pages/concepts/concept/concept.ImagesResults.tsx, content/webapp/views/pages/concepts/concept/concept.RelatedConceptsGroup.tsx, content/webapp/views/pages/concepts/concept/concept.WorksResults.tsx, content/webapp/views/pages/concepts/concept/concept.styles.tsx, content/webapp/views/pages/concepts/concept/index.tsx
Adds an h2 section headings above images/works in line with designs, and update other h2s to be Wellcome Bold. Also changes side navigation to link to these (h2) sections (i.e. not the images sub-sections).
Note: the Figma has the heading in a lighter weight of Wellcome Bold which we don't have (yet) in production. @dana-saur has Said it's ok to use what we've currently got for now.
Visit a concept page and check that 'Images from the collections' and 'Works from the collections' headings are above the images/works sections. Check the 'Frequent collaborators' and 'Related topics' headings are in Wellcome Bold, and that these are now the sections that are linked from side nav.
Matches design spec
=> Concept Headings

common/data/hardcoded-ids.ts, common/views/layouts/PageLayout/index.tsx, content/webapp/pages/collections/[uid].tsx, content/webapp/pages/collections/index.tsx, content/webapp/views/pages/collections/index.tsx
#12214 
The new page [was created in Prismic](https://wellcomecollection.prismic.io/builder/pages/aKb_ahAAAB8AhtQC?s=published) and has a `delist` tag as to not get picked up by our All search.
I added the capacity to add the `noIndex` meta, which I think Lauren wanted us to have anyway so that could stay in. It's all manual at the moment though, it's not perfected.
Also manually done was the `isHiddenPage` const, which returns a 404 if a user is trying to access this page straight from its id/uid (`collections/collections-landing` would otherwise work).
So I think it's general the page SHOULD be hidden from all, but let me know if I've missed something!
Otherwise the PR is mostly about displaying and fetching alternative content should the user have the `collectionsLanding` toggle turned …
=> Alt landing page for Collections

common/data/microcopy.tsx, content/webapp/pages/collections/index.tsx, content/webapp/services/prismic/transformers/collections-landing.ts, content/webapp/views/pages/collections/index.tsx
#12219
- Tweaks the new collections landing page to get more curated content from the server queries (more like our What's On page - the other page that's half coded/half coming from Prismic)
- I hard coded the "Inside our collections" block, similarly to "Latest stories" on the homepage, with the actual cards coming from Prismic. I do not love it, it looks like the CardGrid needs to get adjusted when it's fed by Prismic as all the images have a different height?
I won't close the ticket when this gets deployed. I still want to:
- Fix the image ratio on the cards
- Add the format so it displays? Although it's not in the mockup so it's probably good without.
- Tidy up the helper; we won't be fetching from Content API but really from Prismic, so make it better and remove the comment saying …
=> CL: Inside our collections

content/webapp/views/components/ItemLink/index.tsx, content/webapp/views/pages/works/work/IIIFViewer/GridViewer.tsx, content/webapp/views/pages/works/work/IIIFViewer/IIIFViewer.tsx, content/webapp/views/pages/works/work/IIIFViewer/MainViewer.tsx, content/webapp/views/pages/works/work/items.tsx, playwright/test/view-items.test.ts
Fixes the issue where clicking a thumbnail wouldn't update the main UI #12259 
- Visit a [work](http://localhost:3000/works/ckyptptb/items)
- Click a thumbnail
- Check the URL and the UI both change
It works
I've not reviewed Claude's work here thoroughly yet:
Summary
The problem was that `shouldScrollToCanvas` was being set to `false`, which prevented the MainViewer from scrolling to the correct canvas position when thumbnail links were clicked. Even though all the data was flowing correctly through the component tree, the visual update wasn't happening because the scroll function wasn't being called.
The original problematic commit `88bc92ef36c1c563fc198c7837bae56c281ce4bb` broke the link generation by:
1. Removing the `as` prop from NextLink components
2. Not properly handling query …
=> Make clicking thumbnails change the main viewer UI

content/webapp/utils/breakpoints.ts, content/webapp/utils/page-header.tsx
Remove a util file that's used once that declares breakpoints, which we also have as `sizes` in our theme. 
Replaced the one place where it was used to the equivalent value (medium size is also 600)
Do the Hero images still look fine?
No double declaration of breakpoints
N/A
=> Remove double breakpoints

common/views/components/SearchForm/index.tsx, content/webapp/views/pages/collections/index.tsx
#12290 
I wasn't sure where to add it but I think it belongs in `SearchForm`, to ensure it uses the same ID. `SearchForm` is used elsewhere but mostly for works (as well as the header search). Shout if we think it'd be better off elsewhere!
Test the search bar with and without the checkbox being selected, see if the results make sense.
More search control
N/A
=> Add checkbox to collections search

content/webapp/views/components/ContentPage/index.tsx, toggles/webapp/toggles.ts
#12336 
Quick work, this one! Removed the toggle and its condition (dashboard will be updated upon merge)
Run locally and ensure featured works still show in incognito mode. (e.g https://www-dev.wellcomecollection.org/stories/YZJzrhEAACUARhC3)
One less toggle, work made official = success
N/A
=> Remove `featuredWorksInAddressables` toggle conditions

common/views/components/SearchBar/SearchBar.New.tsx, content/webapp/views/components/ScrollContainer/ScrollContainer.Navigation.tsx, content/webapp/views/components/SelectableTags/index.tsx, content/webapp/views/pages/collections/collections.BrowseByThemes.tsx
Addresses various a11y issues arising from #12350 (I hadn't intended to do this, but in testing theories about why certain things weren't working it made more sense to put the end result in a PR).
- Check screenreader announces number of ThemePromos (and the topic) when the theme radio button selection changes
- Check the contrast of the Typewriter is WCAG AA compliant
- Check NVDA announces 'people and organisations' when it is the selected radio button
- Check the 'prev' button is announced as 'previous' by screenreaders
Site is more accessible than before
=> Collections a11y qa
